### ISSUE TITLE
Post Process Failing for All Media

### ISSUE THREAD

**Issue by kushfest** [clinton-hall/nzbToMedia#1000]
I use nzbToMedia in conjunction with Sonarr, CouchPotato, NZBGet and Deluge on Ubuntu. This system has worked beautifully until yesterday. Suddenly all post-processing is failing. The only changes to the computer I can think of since it worked are some system updates and updates through apt. Here's the log from a recent download that failed to post-process:
http://pastebin.com/z0SfK2iz

Any idea how I broke it?

**Comment by clinton-hall** [comment]
Your config appears to be corrupt... perhaps a failed migration?

Check autoProcessMedia.cfg to see that it all looks ok.
if it looks ok, try removing it, then copy autoProcessMedia.cfg.spec to autoProcessMedia.cfg and then edit this as per your needed settings. see if this works ok.

**Comment by kushfest** [comment]
I just gave that a go and it looks like it worked! NZBGet was able to download and process a a TV episode without issue. Thank you very much, Clinton!
