### ISSUE TITLE
qnap setup

### ISSUE THREAD

**Issue by hroman73** [clinton-hall/nzbToMedia#1001]
Thanks for the qnap qpkg of this. Is there any way you can include mp4_automator and it's dependencies so I can have it work with my apple tv?

https://github.com/mdhiggins/sickbeard_mp4_automator

Including this would make the perfect setup...Thanks!

**Comment by clinton-hall** [comment]
This project includes automated transcoder.
sickbeard_mp4_automator can be added to QNAP. Problem here is it appears to require python setup tools or PIP, which requires compiling tools. So making this into a QNAP package is not a simple process.
