### ISSUE TITLE
[d7ad96c] Extra params were passed to processEpisode: KWARGS={'dir': '/mnt/media/downloads/transmission/complete/tv/Elementary S04E19\xef\x80\xa9'}, ARGS=()

### ISSUE THREAD

**Issue by natetheskate** [clinton-hall/nzbToMedia#1002]
Started having a problem tonight and was hoping for some help. Post processing not working no matter what I try, log below:

http://pastebin.com/raw/qdPxEXzK

I can also upload my config if needed. Thanks!

**Comment by utookmyid** [comment]
no answer, but I'm having the same exact issue

**Comment by GregSawin** [comment]
Same issue, started 3hrs ago for me.

**Comment by natetheskate** [comment]
Good to know I'm not alone.

**Comment by michaelshobbs** [comment]
Having the same issue. I turned on http logging to confirm that nzbToMedia is getting logged in as well; since other issues seem to indicate a possible issue with user/pass mismatch between nzbToMedia and SickBeard/SickRage. That does not seem to be the case here.

```
2016-04-10 20:28:14 ERROR    Thread-16 :: [d7ad96c] Extra params were passed to processEpisode: KWARGS={'dir': '/volume1/Media/downloads/complete/11.22.63.S01E03.1080p.HDTV.X264-DIMENSION'}, ARGS=()
2016-04-10 20:28:13 INFO     TORNADO :: User logged into the SickRage web interface
AANone
```

**Comment by rbeall** [comment]
same issue

**Comment by clinton-hall** [comment]
I think this is related to the change of arg name in SickRage...
Should be fixed in latest nightly? https://github.com/clinton-hall/nzbToMedia/pull/1004

**Comment by rbeall** [comment]
There is now a script section: https://github.com/SickRage/SickRage/wiki/Post-Processing#extra-scripts

**Comment by rbeall** [comment]
I suck at git apparently but I went in and manually nano'ed the one line that changed in the nightly and everything worked.  I'll learn git at some point to properly pull branches etc.  Thanks!

**Comment by natetheskate** [comment]
Updated to the latest commit this am on SickRage and all is well again. Thanks everyone.
