### ISSUE TITLE
Changed Hard drive :SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!

### ISSUE THREAD

**Issue by WerdnaP1980** [clinton-hall/nzbToMedia#1005]
Hoping someone can provide a little help as I am struggling here. I have changed my harddrive and changed the drive letter where my media is stored.

Everything was working before that. I am using Sickrage with Sabnzbd. These are the settings for the autoprocessmedia.cfg:

When the first error occurred, I checked the autoprocessmedia.cfg and none of the settings under [SickBeard] required changing (I don't believe)

_[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[tv]]
        enabled = 1
        host = localhost
        port = 8082
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        process_method = ""
        # force processing of already processed content when running a manual scan.
        force = 0
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleteing ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""_

I then checked the [NZB] settings and noticed the Drive letter was still pointing at the old (E:) drive and not the new new F:. This was changed. 

_[Nzb]
    ###### clientAgent - Supported clients: sabnzbd, nzbget
    clientAgent = sabnzbd
    ###### SabNZBD (You must edit this if your using nzbToMedia.py with SabNZBD)
    sabnzbd_host = localhost
    sabnzbd_port = 8080
    sabnzbd_apikey = cf4fa9a91f570dc56fa1836b3fbbf3ed
    ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode.
    default_downloadDirectory = f:\Usenet\Random TV_

I don't have post processing enabled in SickRage.

I re-downloaded an episode using Sickrage. yet the error persisits. 

This is the messages I receive in Sab:

Exit(1) Sickbeard: Failed to post-Process  - returned log from sickbeard was not expected.!

I have re-checked all the folder settings in Sickrage and Sabnzbd. Can anyone help?

Thanks

Andrew

**Comment by clinton-hall** [comment]
can you show the full log from the postprocess?

**Comment by WerdnaP1980** [comment]
Made two changes.
Created a Season 2 folder for the show (the episode I grabbed was a first episode of the new season)

Changed the Fork setting under sickbeard to Sickrage.

It has now worked. Odd. I will now make one change and see which one has fixed it.

**Comment by WerdnaP1980** [comment]
Hi Clinton-Hall,

I am bit of a noobie, the post-process form SAB?

**Comment by WerdnaP1980** [comment]
It was the fork settng. Changed from Auto to SickRage. Working now!!

**Comment by clinton-hall** [comment]
Please see https://github.com/clinton-hall/nzbToMedia/pull/1004
This auto should work on nightly.

**Comment by WerdnaP1980** [comment]
I am not sure where to get the nightly build from. I'll take a look though. I don;t think I have upgraded NZBtoMedia since I lasted it many months ago.

**Comment by clinton-hall** [comment]
if using git
```
git pull
git checkout nightly
git pull
```
otherwise, download nightly from here https://github.com/clinton-hall/nzbToMedia/archive/nightly.zip
then extract, put your existing autoProcessMedia.cfg into the extracted folder, then replace your existing nzbToMedia folder with the new one.

**Comment by WerdnaP1980** [comment]
Thanks, I don't use Git. But have made a note of the link and will do that.

Thanks again for your help,
