### ISSUE TITLE
QQ: is this a concern

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1006]
I'm trying to disable all nice / ionice so i set it to 0 and the logline looks like below. Just wondering if that causing any concerns?

2016-04-11 17:00:25 DEBUG   ::MAIN: calling command: nice -n0 ionice -c0 -n0 /usr/local/bin/ffmpe 2016-04-11 16:48:45 DEBUG   ::MAIN: Starting torrent Mystery.Diners.S10E03.Partner.Problems.WS.DSR.
g -loglevel warning -hwaccel auto -fflags +genpts -i /home/@send/TV/Angel/Angel.-.S03E15.-.Loyalt x264-[NY2].mp4 in utorrent
y.AC3.WS.DVDRip.XviD-FoV.avi -map 0:0 -map 0:1 -map 0:1 -c:v copy -c:a:0 aac -strict -2 -c:a:1 co 2016-04-11 16:48:51 ERROR   ::MAIN: A problem was reported in the /opt/nzbtomedia/nzbToMedia/Torren
py -sn /home/@send/TV/Angel/Angel.-.S03E15.-.Loyalty.AC3.WS.DVDRip.XviD-FoV.mp4

**Comment by clinton-hall** [comment]
0 actually has a meaning... You would need to look it up, I can't recall.
I believe just leaving this blank should disable it...

**Comment by mgaulton** [comment]
That looks like it worked. Thank you sir.
