### ISSUE TITLE
A problem was reported in the /usr/local/nzbget-testing/share/nzbget/scripts/nzbToMedia/nzbToNzbDrone.py script

### ISSUE THREAD

**Issue by Kazcara** [clinton-hall/nzbToMedia#1007]
Think I have resolved it via "TAGS" in Sonarr- it was messy to apply but I think im there now :)

Hi Guys,

I setup NZBGet & Sonnarr on my Synoligy yesterday but im having issues with post processing.

I have setup the ndCatogory as TV (uppercase) , localhost etc as well as API key , but it seems the information is not saved some how. If I look at history PP Failure , category is missing , **if I select drop down and add "TV" and save the I can get it to work** - what can I do to rectify  the issue?

im not able to get to root stuff /dont know how. Im sure iv missed something to ensure TV is added by default but cant see it currently.

Wed Apr 13 2016 08:31:49	Post-process-script nzbToMedia/nzbToNzbDrone.py for 
(EDIT)
INFO	Wed Apr 13 2016 08:31:49	nzbToNzbDrone: [08:31:49] [ERROR]::MAIN: A problem was reported in the /usr/local/nzbget-testing/share/nzbget/scripts/nzbToMedia/nzbToNzbDrone.py script.
INFO	Wed Apr 13 2016 08:31:49	nzbToNzbDrone: [08:31:49] [ERROR]::MAIN: Category:[] is not defined or is not enabled. Please rename it or ensure it is enabled for the appropriate section in your autoProcessMedia.cfg and try again.
INFO	Wed Apr 13 2016 08:31:48	nzbToNzbDrone: [08:31:48] [INFO]::MAIN: Script triggered from NZBGet Version 16.0-testing-r1439.
INFO	Wed Apr 13 2016 08:31:48	nzbToNzbDrone: [08:31:48] [INFO]::MAIN: #########################################################
INFO	Wed Apr 13 2016 08:31:48	nzbToNzbDrone: [08:31:48] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
INFO	Wed Apr 13 2016 08:31:48	nzbToNzbDrone: [08:31:48] [INFO]::MAIN: #########################################################
INFO	Wed Apr 13 2016 08:31:48	nzbToNzbDrone: [08:31:48] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
INFO	Wed Apr 13 2016 08:31:48	nzbToNzbDrone: [08:31:48] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
INFO	Wed Apr 13 2016 08:31:48	nzbToNzbDrone: [08:31:48] [INFO]::MAIN: nzbToMedia Version:10.12 Branch:master (Linux 2.6.32.12)
INFO	Wed Apr 13 2016 08:31:48	nzbToNzbDrone: [08:31:48] [INFO]::MAIN: No update needed
INFO	Wed Apr 13 2016 08:31:48	nzbToNzbDrone: [08:31:48] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
INFO	Wed Apr 13 2016 08:31:48	nzbToNzbDrone: [08:31:48] [INFO]::MAIN: Checking if git needs an update
INFO	Wed Apr 13 2016 08:31:48	nzbToNzbDrone: [08:31:48] [INFO]::MAIN: Checking database structure...
INFO	Wed Apr 13 2016 08:31:40	Executing post-process-script nzbToMedia/nzbToNzbDrone.py for (EDIT )

Thanks
Kaz

**Comment by clinton-hall** [comment]
glad you got it sorted. Please let me know if you have any further issues.

**Comment by Kazcara** [comment]
Hi, just wanted to say - after many years of Sickbeard and SAB (still great btw) I have transitioned over to Sonarr and NZBGet and wanted to say I really like it.

Great Job guys and thanks for all your work.
Kaz
