### ISSUE TITLE
error on unicode for remove_group

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1009]
I was updating the remove_groups and got an error with [Underwater-µtw] ,

```
remove_group = "[Commie],[Hatsuyuki],[KAA],[Ohys-Raws],[HorribleSubs],[KaMi],[Leopard-Raws],[Zero-Raws],Hatsuyuki,[Hatsuyuki-Tsuki],[ScavvyKiD],[Ruberia],[ www.torrenting.com ] - ,[ UsaBit.com } - ,[ www.Speed.Cd ] - ,[ www.TorrentDay.com ] - ,[CHARMING TEAM],[CommieRaws] ,[NOP] ,[Ruberia],[SSP] ,[Tsukino Jyogi] ,[UTW-Mazui]_,[SubDESU-H] ,[AnimeSub] ,[AU] ,[Over-Time] ,[FileTracker.pl],[PW],[AnimeRG] ,[Blaze077] ,[OZC],[ UsaBit.com ] - ,{www.scenetime.com},[gg]_,PRiVATE-,[HorribleSubs] ,[DeadFish] ,[Doki-Chihiro] ,[Freedom] ,[AnimeRG] ,[Underwater] ,[Scales] ,[Underwater-µtw] ,"
```

Traceback (most recent call last):
  File "/opt/Sick-Beard/autoProcessTV/nzbToMedia.py", line 807, in <module>
    exit(main(sys.argv))
  File "/opt/Sick-Beard/autoProcessTV/nzbToMedia.py", line 633, in main
    core.initialize(section)
  File "/opt/Sick-Beard/autoProcessTV/core/**init**.py", line 268, in initialize
    if not config.migrate():
  File "/opt/Sick-Beard/autoProcessTV/core/nzbToMediaConfig.py", line 233, in migrate
    CFG_OLD.write()
  File "/opt/Sick-Beard/autoProcessTV/libs/configobj/configobj.py", line 2123, in write
    'ascii'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb5' in position 22922: ordinal not in range(128)
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x7f2f313bf7a0>> ignored
Ferngully The Last Rainforest 1992 iNTERNAL DVDRip XViD-iLSclose

**Comment by clinton-hall** [comment]
it appears `µ` is not recognized as ascii.

**Comment by mgaulton** [comment]
Indeed. Not entirely surprising.
