### ISSUE TITLE
Deluge not resuming torrents after pause

### ISSUE THREAD

**Issue by Enf0** [clinton-hall/nzbToMedia#1010]
As you know, nzbToMedia pauses torrents while post-processing them (not sure why?) and resumes them after it's done processing. 
However, as of a while ago, the torrents no longer get resumed and instead remain in a paused state. I'm not sure when this started happening. I've attached an excerpt from my logs along with my config file, please let me know if you need anything else.

[nzbToMedia.log](https://gist.github.com/Enf0/b9f3a3fc2fb55f5ebba9d5f5ebfbeb8f)
[autoProcessMedia.cfg](https://gist.github.com/Enf0/ae0d1b915dd166fc0afe733233a7cb84)

Thanks in advance!

**Comment by clinton-hall** [comment]
Torrents don't resume because the script fails and ends early.
Please enable debug logging 
```
[General]
   log_debug = 1
```
Then check logs next time this happens.

As a note. Torrents are paused to remove any file locks and also to prevent any issues with files being moved/linked etc during processing,

**Comment by Enf0** [comment]
Not sure what changed, but of course when I open a ticket to report the issue, it no longer occurs.

**Comment by clinton-hall** [comment]
lol... I love self-resolving issues.
Let me know if it happens again (with debug logging).
