### ISSUE TITLE
QQ: trascode files at rest

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1011]
So i have a library of files with some transocded to iPad and the rest not. I'm wondering if there is a way to scan the library and transcode just the files that need it, replacing the file in place? The problem i have is 720p and higher doesn't like playing on my iPad :)

**Comment by clinton-hall** [comment]
possible, but not practical.
Basically, you can make this script process a directory as part of a manual scan, however it will then try and post-process this to CouchPotato/SickBeard. So you need to stop these services to prevent this happening.

For cleaning up historical files, I would recomend an external tool (handbrake etc) to do this.

**Comment by mgaulton** [comment]
Ok, i'll take a look at handbrake. Thanks. I just figured if i could do it with nTM for consistancy, why not lol

**Comment by mgaulton** [comment]
Out of curiosity, any suggestions on how to identify 720p or higher or media not already iPad encoded? i'm seeing a mixed back of answers. I thought you had a check already to skip encoding if its not needed.

**Comment by clinton-hall** [comment]
So with the custom profile, or the defined profiles, these have allowed codecs, and resolutions.
If these are matched, the transcode should copy the stream.
so it will only down-scale based on resolution etc... 
What profile (or custom settings) do you have?

**Comment by mgaulton** [comment]
This is what i'm using. I jus pass --preset=iPad, i didn't mess wiht anything else.
Which, according to the output of HandBrakeCLI --preset-list "ipad" is equal to "    -e x264  -q 20.0 -r 30 --pfr  -a 1 -E ffaac -B 160 -6 dpl2 -R Auto -D 0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 -f mp4 -X 1280 -Y 720 --loose-anamorphic --modulus 2 -m --x264-preset medium --h264-profile high --h264-level 3.1


#!/bin/bash

#Uncomment a Preset FLAGS and Uncomment a file type (mkv,avi,mp4)!

export FLAGS='--preset=iPad'

if [ -z "$1" ] ; then
    TRANSCODEDIR="."
else
    TRANSCODEDIR="$1"
fi
if [ -z "$2" ] ; then
    TRANSCODEFILE="*"
else
    filename=$(basename "$2")
    extension="${filename##*.}"
    filename="${filename%.*}"
    TRANSCODEFILE="$filename"

fi

    ###To use [&& find . -name '*.***' -delete] Uncomment and delete once to add to previous line of code
    ###Removes source files after completing ALL conversions. Use at your own risk!

    #AVI
    find "$TRANSCODEDIR"/* -type f -name "$TRANSCODEFILE.avi" -mtime -1 -exec bash -c 'HandBrakeCLI -i "$1" -o "${1%\.*}".mp4 $FLAGS' __ {} \; 
#&& find . -name '*.avi' -delete

    #MKV 
    find "$TRANSCODEDIR"/* -type f -name "$TRANSCODEFILE.mkv" -mtime -1 -exec bash -c 'HandBrakeCLI -i "$1" -o "${1%\.*}".mp4 $FLAGS' __ {} \; 
#&& find . -name '*.mkv' -delete

    #MP4 
    find "$TRANSCODEDIR"/* -type f -name "$TRANSCODEFILE.mp4" -mtime -1 -exec bash -c 'HandBrakeCLI -i "$1" -o "${1%\.*}"-new.mp4 $FLAGS' __ {} \;
##&&find . -type f -not -name '*-new.mp4' -name '*.mp4' -delete && rename 's/-new//' *.mp4
