### ISSUE TITLE
understanding nzbtomedia(I am a noob)

### ISSUE THREAD

**Issue by seed1234** [clinton-hall/nzbToMedia#1012]

**Comment by seed1234** [comment]
I have a small issue understanding categories in nzbtomedia
Does "categories" mean the last destination folder to post process into?
i.e:movie, tvshow

For example:
[NzbDrone]
#### autoProcessing for TV Series
#### ndCategory - category that gets called for post-processing with NzbDro$
[[tv]]

do i need to change that "tv" to my last destination of where my TV shows reside?

Also another question regarding the torrent section

[Torrent]
###### clientAgent - Supported clients: utorrent, transmission, deluge, rto$
clientAgent = transmission
###### useLink - Set to hard for physical links, sym for symbolic links, mo$
useLink = hard
###### outputDirectory - Default output directory (categories will be appen$
outputDirectory =

The output directory for me is on different data sets for different applications
CP: /mnt/nas/movies/moviedowloads
Sonarr: /mnt/nas/series/tvdownload

What do i write in the outputDirectory ?

or is it enough to add these :
Cp:
##### Set to path where download client places completed downloads locally for this category
watch_dir = /mnt/nas/movies/moviedowloads

Sonarr:
##### Set to path where download client places completed downloads locally for this category
watch_dir = /mnt/nas/series/tvdownload

Thank You for your help

**Comment by clinton-hall** [comment]
Categoriers are:

CP = moviedowloads
Sonarr = tvdownload

outputDirectory = /mnt/nas/processed
