### ISSUE TITLE
Deleting shows not getting matched.

### ISSUE THREAD

**Issue by IngoVals** [clinton-hall/nzbToMedia#1013]
So i had a show that seems to have to have had a year in the title to get it matched because there was an older show with same name. Nothing we can do about that I guess, but I found it troublesome that after processing it would delete the show, I would liked to have been able to edit the year into the title and manually post processed. Is there any option for that?

Here is the part of the log it happens.

```
[02:05:45] [POSTPROCESS]::SICKBEARD: Processing folder Showname.lacking.realeaseYear
[02:05:45] [POSTPROCESS]::SICKBEARD: Unable to match Showname.lacking.realeaseYear.mkv to a show in your database
[02:05:45] [POSTPROCESS]::SICKBEARD: Unable to match Showname.lacking.realeaseYear to a show in your database
[02:05:45] [POSTPROCESS]::SICKBEARD: Showname.lacking.realeaseYear : No processable items found in folder
[02:05:45] [POSTPROCESS]::SICKBEARD: Successfully processed
[02:05:45] [INFO]::CLEANDIR: Doing Forceful Clean of /volume1/downloads/complete/tv/Showname.lacking.realeaseYear
[02:05:45] [INFO]::MAIN: Deleting /volume1/downloads/complete/tv/Showname.lacking.realeaseYear
[02:05:45] [INFO]::MAIN: The /usr/local/sabnzbd/var/scripts/nzbToMedia/nzbToSickBeard.py script completed successfully.
SickBeard: Successfully post-processed Showname.lacking.realeaseYear.nzb!
```

**Comment by clinton-hall** [comment]
was this show actually in SickBeard? was this snatched by sickbeard or was this a manual scan?
The problem here is that SickBeard never identified and processed the show.

**Comment by IngoVals** [comment]
Yes the show was in SickRage, however it seems the name needs to have the year in the title because of a older show with same name. I manually added it and a few others becuase the correct quality wasn't available but I had no problems with the other shows manually added.

I don't really have a problem with it not identifying the show, but if that happens I want it not to delete it, is there any setting for that?

**Comment by clinton-hall** [comment]
In autoProcessMedia.cfg
[General]
   force_clean = 0

**Comment by IngoVals** [comment]
Doesn't this then not force clean any show at all. I would love for a option not to force clean, on the occasion the show wasn't found. If the show hasn't been moved anywhere I don't want to delete it. But I want to delete all other shows.

**Comment by clinton-hall** [comment]
I appreciate what you are asking for, but this becomes a lot more problematic to determine.'

Currently, the "successful" process is determined by the final line from SickBeaard/SickRage = `Successfully processed` which is returned even when this case you highlighted... 
So To me this should be done in SickBeard/SickRage where this shouldn't return "succesfully processed".

For this script to distibguish this, I'd need to parse each line for `Unable to match` or `No processable items found` to set this to "failed" status... I can do this, but any changes to logging in SickBeard/Sickrage would break this...

**Comment by IngoVals** [comment]
Yeah, I kind of figured that the problem is more how SickRage reports the post process. I however found an option in SickRage that is going to makes this a much more uncommon problem.

This was mostly happening when the download name for a show didn't match the name on TVDB, SickRage has this Scene Exception rule where you can define alternate name. I guess this will all but remove this problem.
