### ISSUE TITLE
Corrupt videos found, but SR is processing the 'failed' video

### ISSUE THREAD

**Issue by cgmille2** [clinton-hall/nzbToMedia#1017]
Hi,
ffprobe is recognizing corrupt videos and nzbtomedia is sending 'failed' to sickrage, but SR processes it as an uncorrupt video anyways. Manually marking the video failed in SR works fine.
http://pastebin.com/ztwpeQi4
Any ideas? I'm sure it's something simple again. Thanks

**Comment by clinton-hall** [comment]
Which Version of SickRage?

The script is passing failed status:
`Opening URL: http://192.168.82.112:8081/home/postprocess/processEpisode with params: {'nzbName': 'Game.of.Thrones.S06E01.HDTV.x264-KILLERS.mp4', 'quiet': 1, 'failed': 1, 'proc_dir': '/mnt/user/Limbo/Processed/tv/Game.of.Thrones.S06E01.HDTV.x264-KILLERS', 'delete_on': 1}`
So this looks to be an issue with sickrage ignoring the flag.

**Comment by cgmille2** [comment]
The sickrage.github.io (github.com/SickRage/SickRage) version. Latest commit on master.

**Comment by cgmille2** [comment]
Hey. Was wondering if you have any thoughts or should I take this to the sickrage forum. Thanks

**Comment by clinton-hall** [comment]
Sorry no thoughts. I haven't seen this behaviour. Ask SickRage team and let me know if I need to edit the scripts.

**Comment by cgmille2** [comment]
The team said that 'sickragetv' is from the old repo and to use 'sickrage' now for the tv fork. I was using 'auto' for the fork in nzbtomedia

https://github.com/SickRage/SickRage/issues/1640

Thanks clinton-hall

**Comment by clinton-hall** [comment]
Strange. I can't replicate.
Try changing the fork from "auto" to "sickrage" and see if that works.
There may be an issue with the order of checking in the auto fork checks.

**Comment by cgmille2** [comment]
It works when when changing auto to sickrage (Sorry, I should have mentioned that previously).
Thanks

**Comment by clinton-hall** [comment]
Oh. Now I see.
Please switch to nightly branch and test. There were changes made to failed parameter testing and fork detection that have not yet been merged.

**Comment by cgmille2** [comment]
I will switch to nightly and wait for a failed download

**Comment by cgmille2** [comment]
Sorry, I have been away from my home for a while. I am still having this issue, even with the nightlies. I'm fairly positive that this is a SR issue but no one is responding to me over there (https://github.com/SickRage/SickRage/issues/1668).
Anyways, you've always been very helpful... Do you have any thoughts?

**Comment by clinton-hall** [comment]
Have you got logs from latest test on nightly?
This has me baffled...

**Comment by cgmille2** [comment]
I have one from a recent nzbtomedia nightly (http://pastebin.com/WWHrVgzm). My SR debug log is on, so it has run past that failed video date; so I don't have a log from when it failed... I am running SR on master, as I always seem to have something come up on the nightlies or dev.
