### ISSUE TITLE
Need help with my configuration..

### ISSUE THREAD

**Issue by millertime23** [clinton-hall/nzbToMedia#1019]
I've been trying to set up my nzbToMedia transcoder configuration to accomplish the following:

Container: mkv
video stream: copy (no transcoding whatsoever)
audio: If AC3 codec: copy
           if DTS (or anything other than AC3): copy AND transcode an AC3 track
subs: copy all english subs
etc: remove all non-english audio/subs from the completed mkv file

I haven't been able to set up my configuration in a way that accomplishes this without transcoding errors. In fact, the only way I've been able to successfully transcode anything is if I use the "Roku-1080p" profile (or one of the other profiles). The profiles don't accomplish what I'm trying to do though.. I don't want the transcoder to touch the video stream at all. Just audio and subs..

**Comment by millertime23** [comment]
Nevermind.. I figured it out. It didn't occur to me to leave the fields for video blank in order to copy. For anyone else who may be trying to do the same thing, here's the settings I used that seem to be working:

> [Transcoder]

    # getsubs. enable to download subtitles.
    getSubs = 1
    # subLanguages. create a list of languages in the order you want them in your subtitles. 
    subLanguages = eng
    # transcode. enable to use transcoder
    transcode = 1
    ###### duplicate =1 will create a new file. =0 will replace the original
    duplicate = 1
    # concat. joins cd1 cd2 etc into a single video.
    concat = 1
    # IgnoreExtensions is a comma-separated list of extensions that will not be transcoded.
    ignoreExtensions = .avi
    # outputFastStart. 1 will use -movflags + faststart. 0 will disable this from being used.
    outputFastStart = 0
    # outputQualityPercent. used as -q:a value. 0 will disable this from being used.
    outputQualityPercent = 0
    # outputVideoPath. Set path you want transcoded videos moved to. Leave blank to disable.
    outputVideoPath = D:\Encodes
    # processOutput. 1 will send the outputVideoPath to SickBeard/CouchPotato. 0 will send original files.
    processOutput = 1
    # audioLanguage. set the 3 letter language code you want as your primary audio track.
    audioLanguage = eng
    # allAudioLanguages. 1 will keep all audio tracks (uses AudioCodec3) where available.
    allAudioLanguages = 0
    # allSubLanguages. 1 will keep all existing sub languages. 0 will discard those not in your list above.
    allSubLanguages = 0
    # embedSubs. 1 will embed external sub/srt subs into your video if this is supported.
    embedSubs = 1
    # burnInSubtitle. burns the default sub language into your video (needed for players that don't support subs)
    burnInSubtitle = 0
    # extractSubs. 1 will extract subs from the video file and save these as external srt files.
    extractSubs = 0
    # externalSubDir. set the directory where subs should be saved (if not the same directory as the video)
    externalSubDir = ""
    # hwAccel. 1 will set ffmpeg to enable hardware acceleration (this requires a recent ffmpeg)
    hwAccel = 0
    # generalOptions. Enter your additional ffmpeg options here with commas to separate each option/value (i.e replace spaces with commas).
    generalOptions = ""
    # outputDefault. Loads default configs for the selected device. The remaining options below are ignored.
    # If you want to use your own profile, leave this blank and set the remaining options below.
    # outputDefault profiles allowed: iPad, iPad-1080p, iPad-720p, Apple-TV2, iPod, iPhone, PS3, xbox, Roku-1080p, Roku-720p, Roku-480p, mkv, mp4-scene-release
    outputDefault = ""
    #### Define custom settings below.
    outputVideoExtension = .mkv
    outputVideoCodec = ""
    VideoCodecAllow = ""
    outputVideoPreset = ""
    outputVideoResolution = ""
    outputVideoFramerate = ""
    outputVideoBitrate = ""
    outputVideoCRF = ""
    outputVideoLevel = ""
    outputAudioCodec = ac3
    AudioCodecAllow = ""
    outputAudioChannels = ""
    outputAudioBitrate = 640k
    outputAudioTrack2Codec = ""
    AudioCodec2Allow = "a_dts,dts"
    outputAudioTrack2Channels = ""
    outputAudioTrack2Bitrate = ""
    outputAudioOtherCodec = ""
    AudioOtherCodecAllow = ""
    outputAudioOtherChannels = ""
    outputAudioOtherBitrate = ""
    outputSubtitleCodec = ""

**Comment by clinton-hall** [comment]
thanks for posting your config.
Sorry I didn't see this until you already resolved.

The transcoder still need improvements to be able to change the transcode requirements based on multiple criteria... I just haven't had time to look at this any further.

**Comment by millertime23** [comment]
No problem. Thanks for replying. I just started using this script and you've done an amazing job so far
