### ISSUE TITLE
TorrentToMedia.py won't execute from deluge on Windows 10

### ISSUE THREAD

**Issue by millertime23** [clinton-hall/nzbToMedia#1022]
Apologies if this has been addressed already, I couldn't find anything in a google search. I have set up deluge to execute TorrentToMedia.py, using the full path from the deluge execute plugin per the instructions.

When a torrent completes, TorrentToMedia.py doesn't seem to execute. No log entries are made either. I was suspicious that it may be a Windows issue executing a .py file directly, so I created a .bat to execute TorrentToMedia.py instead:

`python "%~dp0TorrentToMedia.py" %1 %2 %3`

I named the .bat file "delugeExecute.bat" and placed it in the same directory as TorrentToMedia.py, then changed the deluge execute plugin to run the .bat file instead of TorrentToMedia.py. 

This seems to be working so far, but I was wondering if this is the proper solution to get TorrentToMedia.py to execute on Windows or if there's a better way?

**Comment by clinton-hall** [comment]
Just make sure the TorrentToMedia.py file can be executed.. 
Check out the windows section under https://github.com/clinton-hall/nzbToMedia/wiki/installation

Also, you might want to ensure .py is added to the pathext variable.
