### ISSUE TITLE
CouchPotato Post Processing issue with archives

### ISSUE THREAD

**Issue by tonyp1983** [clinton-hall/nzbToMedia#1023]
I'm having a bit of an issue with movies I'm downloading via torrent. In nzbToMedia for the CP category I have extract=1. Most movies I download have a folder structure something like 'the.movie.year' (as per the torrent name) and then a set of subfolders with one being the movie with release name 'the.movie.year.quality.groupname' containing the Rar files. On completion the folders/files are hard linked from the completed directory to an intermediary directory, without flattening (which I disabled as flattening caused issues for some season/movie packs) for processing (all good here), then nzbToMedia extracts the movie but does it at the top level directory ('the.movie.year'). Following this, When CP runs the renamer, it attempts to do this on the subdirectory and then fails because it can't find any media files there (due to them being at the top level).

If the extractor in nzbToMedia did it's magic in the same directory as the rar files then everything would work but there doesn't appear to be an option for this.

**Comment by clinton-hall** [comment]
can you show logs for this please? I understand what you are saying, but I just want to trace through the logging to see why the renamer isn't called on the actual folder with the movie file.

**Comment by tonyp1983** [comment]
Hi, here's my current log file, you can see an example of this by looking at Prometheus, starting at 23:15:46 on 01/05.
[nzbtomedia.log.zip](https://github.com/clinton-hall/nzbToMedia/files/248526/nzbtomedia.log.zip)
