### ISSUE TITLE
Keep Getting Traceback when processing files

### ISSUE THREAD

**Issue by iceman73** [clinton-hall/nzbToMedia#1024]
Could someone assist me whenever nzbget calls nzbToMedia, it does not postprocess the file, and I get a traceback. Below is the same error I get for processing any of the files:

```
Mon May  2 09:19:40 2016        INFO    Nothing to cleanup for Scandal.US.S05E19.720p.HDTV.x264-AVS-Obfuscated
Mon May  2 09:19:40 2016        INFO    Executing post-process-script nzbToMedia.py for Scandal.US.S05E19.720p.HDTV.x264-AVS-Obfuscated
Mon May  2 09:19:41 2016        INFO    nzbToMedia: [09:19:41] [INFO]::MAIN: Checking database structure...
Mon May  2 09:19:41 2016        INFO    nzbToMedia: [09:19:41] [INFO]::MAIN: Checking if git needs an update
Mon May  2 09:19:41 2016        INFO    nzbToMedia: [09:19:41] [INFO]::MAIN: No update needed
Mon May  2 09:19:41 2016        INFO    nzbToMedia: [09:19:41] [INFO]::MAIN: nzbToMedia Version:c50957d0b4683a125df039329d8f90df630d4e28 Branch:master (Linux 4.4.0-21-generic)
Mon May  2 09:19:41 2016        INFO    nzbToMedia: Traceback (most recent call last):
Mon May  2 09:19:41 2016        INFO    nzbToMedia:   File "/home/media/addons/nzbget/scripts/nzbToMedia.py", line 807, in <module>
Mon May  2 09:19:41 2016        INFO    nzbToMedia:     exit(main(sys.argv))
Mon May  2 09:19:41 2016        INFO    nzbToMedia:   File "/home/media/addons/nzbget/scripts/nzbToMedia.py", line 633, in main
Mon May  2 09:19:41 2016        INFO    nzbToMedia:     core.initialize(section)
Mon May  2 09:19:41 2016        INFO    nzbToMedia:   File "/home/media/addons/nzbget/scripts/core/__init__.py", line 369, in initialize
Mon May  2 09:19:41 2016        INFO    nzbToMedia:     REMOTEPATHS = [ (local.strip(), remote.strip()) for local, remote in REMOTEPATHS ] # strip trailing and leading whitespaces
Mon May  2 09:19:41 2016        INFO    nzbToMedia: ValueError: need more than 1 value to unpack
Mon May  2 09:19:41 2016        INFO    nzbToMedia: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x7fa2d84bd878>> ignored
Mon May  2 09:19:41 2016        ERROR   Post-process-script nzbToMedia.py for Scandal.US.S05E19.720p.HDTV.x264-AVS-Obfuscated failed (terminated with unknown status)
Mon May  2 09:19:41 2016        INFO    Collection Scandal.US.S05E19.720p.HDTV.x264-AVS-Obfuscated added to history
```

This is what the file in the directory looks like:

```
media@stream:/var/log/media$ ls -ls /home/media/Downloads/tv/Scandal.US.S05E19.720p.HDTV.x264-AVS-Obfuscated/
total 1032084
1032084 -rwxrwxrwx 1 media media 1056845908 Apr 29 03:57 rdxRRcpDdWwAHfKWfqbIF4.mkv
```

My autoconfig file:
`[Transcoder]
    # getsubs. enable to download subtitles.
    getSubs = 0
    # subLanguages. create a list of languages in the order you want them in your subtitles.
    subLanguages = eng
    # transcode. enable to use transcoder
    transcode = 1
    ###### duplicate =1 will create a new file. =0 will replace the original
    duplicate = 1
    # concat. joins cd1 cd2 etc into a single video.
    concat = 1
    # IgnoreExtensions is a comma-separated list of extensions that will not be transcoded.
    ignoreExtensions = ".avi,.mkv"
    # outputFastStart. 1 will use -movflags + faststart. 0 will disable this from being used.
    outputFastStart = 1
    # outputQualityPercent. used as -q:a value. 0 will disable this from being used.
    outputQualityPercent = ""
    # outputVideoPath. Set path you want transcoded videos moved to. Leave blank to disable.
    outputVideoPath = ""
    # processOutput. 1 will send the outputVideoPath to SickBeard/CouchPotato. 0 will send original files.
    processOutput = 1
    # audioLanguage. set the 3 letter language code you want as your primary audio track.
    audioLanguage = eng
    # allAudioLanguages. 1 will keep all audio tracks (uses AudioCodec3) where available.
    allAudioLanguages = 0
    # allSubLanguages. 1 will keep all existing sub languages. 0 will discard those not in your list above.
    allSubLanguages = 0
    # embedSubs. 1 will embed external sub/srt subs into your video if this is supported.
    embedSubs = 0
    # burnInSubtitle. burns the default sub language into your video (needed for players that don't support subs)
    burnInSubtitle = 0
    # extractSubs. 1 will extract subs from the video file and save these as external srt files.
    extractSubs = 1
    # externalSubDir. set the directory where subs should be saved (if not the same directory as the video)
    externalSubDir = ""
    # hwAccel. 1 will set ffmpeg to enable hardware acceleration (this requires a recent ffmpeg)
    hwAccel = 0
    # generalOptions. Enter your additional ffmpeg options here with commas to separate each option/value (i.e replace spaces with commas).
    generalOptions = ""
    # outputDefault. Loads default configs for the selected device. The remaining options below are ignored.
    # If you want to use your own profile, leave this blank and set the remaining options below.
    # outputDefault profiles allowed: iPad, iPad-1080p, iPad-720p, Apple-TV2, iPod, iPhone, PS3, xbox, Roku-1080p, Roku-720p, Roku-480p, mkv, mp4-scene-release
    outputDefault = None
    #### Define custom settings below.
    outputVideoExtension = .mp4
    outputVideoCodec = libx264
    VideoCodecAllow = ""
    outputVideoPreset = medium
    outputVideoResolution = 1920:1080
    outputVideoFramerate = 24
    outputVideoBitrate = 800k
    outputVideoCRF = 19
    outputVideoLevel = 3.1
    outputAudioCodec = ac3
    AudioCodecAllow = ""
    outputAudioChannels = 6
    outputAudioBitrate = 640k
    outputAudioTrack2Codec = libfaac
    AudioCodec2Allow = ""
    outputAudioTrack2Channels = 2
    outputAudioTrack2Bitrate = 160k
    outputAudioOtherCodec = libmp3lame
    AudioOtherCodecAllow = ""
    outputAudioOtherChannels = 2
    outputAudioOtherBitrate = 128k
    outputSubtitleCodec = ""
`

**Comment by c0m3d1an** [comment]
What is the output of "python -V" on the affected system?

**Comment by clinton-hall** [comment]
in NZBGet, settings, for the script called, check the "mountPoints"
This needs to have a comma separated pair... but only if your SickRage and NZBGet are different systems.
