### ISSUE TITLE
UTorrent post processing not working

### ISSUE THREAD

**Issue by boomertheweim** [clinton-hall/nzbToMedia#1026]
uTorrent is not working.  I have attached the log file and my config file. In uTorrnt I have a label called 'tv' a and label mapping is c:\nzb\temp.

For Directories I have the following

C:\nzb\temp for Put new downloads in
C:\nzb\complete for Move completed downloads to

What am I missing?

2016-05-05 02:56:23 INFO    ::MAIN: ############################## ###########################
2016-05-05 02:56:23 INFO    ::MAIN: ## ..::[TorrentToMedia.py]::.. ##
2016-05-05 02:56:23 INFO    ::MAIN: #########################################################
2016-05-05 02:56:23 DEBUG   ::MAIN: Options passed into TorrentToMedia: ['C:\Rager\contrib\nzbToMedia\TorrentToMedia.py']
2016-05-05 02:56:23 WARNING ::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
2016-05-05 02:56:23 INFO    ::MAIN: Searching C:\nzb\complete\tv for mediafiles to post-process ...
2016-05-05 02:56:23 DEBUG   ::MAIN: No directories identified in SickBeard:tv for post-processing
2016-05-05 02:56:23 INFO    ::MAIN: Searching C:\nzb\complete\sports for mediafiles to post-process ...
2016-05-05 02:56:23 DEBUG   ::MAIN: No directories identified in SickBeard:sports for post-processing
2016-05-05 02:56:23 INFO    ::MAIN: Searching C:\nzb\complete\Tor for mediafiles to post-process ...
2016-05-05 02:56:23 DEBUG   ::MAIN: No directories identified in SickBeard:Tor for post-processing
2016-05-05 02:56:23 INFO    ::MAIN: Searching C:\nzb\complete for mediafiles to post-process ...
2016-05-05 02:56:23 INFO    ::MAIN: Starting manual run for SickBeard:\* - Folder:C:\nzb\complete\Blindspot.S01E20.HDTV.x264-LOL[ettv]
2016-05-05 02:56:23 INFO    ::MAIN: Checking database for download info for Blindspot.S01E20.HDTV.x264-LOL[ettv] ...
2016-05-05 02:56:23 DB      ::DB: Getting download info for Blindspot.S01E20.HDTV.x264-LOL[ettv] from the DB
2016-05-05 02:56:23 DB      ::MAIN: nzbtomedia.db: SELECT \* FROM downloads WHERE input_name=? AND status=? with args [u'Blindspot.S01E20.HDTV.x264-LOL[ettv]', 0]
2016-05-05 02:56:23 INFO    ::MAIN: Unable to locate download info for Blindspot.S01E20.HDTV.x264-LOL[ettv], continuing to try and process this release ...
2016-05-05 02:56:23 DEBUG   ::MAIN: Received Directory: C:\nzb\complete\Blindspot.S01E20.HDTV.x264-LOL[ettv] | Name: Blindspot.S01E20.HDTV.x264-LOL[ettv] | Category: *
2016-05-05 02:56:23 DEBUG   ::MAIN: SEARCH: Could not find the category: \* in the directory structure
2016-05-05 02:56:23 INFO    ::MAIN: SEARCH: Found torrent directory Blindspot.S01E20.HDTV.x264-LOL[ettv] in the directory structure
2016-05-05 02:56:23 DEBUG   ::MAIN: Determined Directory: C:\nzb\complete\Blindspot.S01E20.HDTV.x264-LOL[ettv] | Name: Blindspot.S01E20.HDTV.x264-LOL[ettv] | Category: *
2016-05-05 02:56:23 INFO    ::MAIN: Auto-detected SECTION:SickBeard
2016-05-05 02:56:23 INFO    ::MAIN: Output directory set to: c:\nzb\complete*\Blindspot.S01E20.HDTV
2016-05-05 02:56:23 DEBUG   ::MAIN: Scanning files in directory: C:\nzb\complete\Blindspot.S01E20.HDTV.x264-LOL[ettv]
2016-05-05 02:56:23 DEBUG   ::MAIN: Found 1 files in C:\nzb\complete\Blindspot.S01E20.HDTV.x264-LOL[ettv]
2016-05-05 02:56:23 DEBUG   ::MAIN: Checking for archives to extract in directory: c:\nzb\complete*\Blindspot.S01E20.HDTV
2016-05-05 02:56:23 INFO    ::MAIN: FLATTEN: Flattening directory: c:\nzb\complete*\Blindspot.S01E20.HDTV
2016-05-05 02:56:23 WARNING ::MAIN: Found no media files in c:\nzb\complete*\Blindspot.S01E20.HDTV
2016-05-05 02:56:23 INFO    ::MAIN: Calling SickBeard:\* to post-process:Blindspot.S01E20.HDTV.x264-LOL[ettv]
2016-05-05 02:56:23 INFO    ::MAIN: Attempting to auto-detect \* fork
2016-05-05 02:56:25 INFO    ::MAIN: SickBeard:\* fork auto-detection successful ...
2016-05-05 02:56:25 INFO    ::MAIN: SickBeard:\* fork set to sickragetv

Hrere's the config file
# nzbToMedia Configuration
# For more information, visit https://github.com/clinton-hall/nzbToMedia/wiki

[General]
    # Enable/Disable update notifications
    version_notify = 1
    # Enable/Disable automatic updates
    auto_update = 1
    # Set to the full path to the git executable
    git_path = ""
    # GitHUB user for repo
    git_user = ""
    # GitHUB branch for repo
    git_branch = ""
    # Enable/Disable forceful cleaning of leftover files following postprocess 
    force_clean = 1
    # Enable/Disable logging debug messages to nzbtomedia.log
    log_debug = 1
    # Enable/Disable logging database messages to nzbtomedia.log
    log_db = 1
    # Enable/Disable logging environment variables to debug nzbtomedia.log (helpful to track down errors calling external tools.)
    log_env = 1
    # Enable/Disable logging git output to debug nzbtomedia.log (helpful to track down update failures.)
    log_git = 1
    # Set to the directory where your ffmpeg/ffprobe executables are located
    ffmpeg_path = ""
    # Enable/Disable media file checking using ffprobe.
    check_media = 0
    # Enable/Disable a safety check to ensure we don't process all downloads in the default_downloadDirectories by mistake.
    safe_mode = 1

[Posix]
    ### Process priority setting for External commands (Extractor and Transcoder) on Posix (Unix/Linux/OSX) systems.
    # Set the Niceness value for the nice command. These range from -20 (most favorable to the process) to 19 (least favorable to the process).
    niceness = 0
    # Set the ionice scheduling class. 0 for none, 1 for real time, 2 for best-effort, 3 for idle.
    ionice_class = 0
    # Set the ionice scheduling class data. This defines the class data, if the class accepts an argument. For real time and best-effort, 0-7 is valid data.
    ionice_classdata = 0

[CouchPotato]
    #### autoProcessing for Movies
    #### movie - category that gets called for post-processing with CPS
    [[movie]]
        enabled = 0
        apikey = ""
        host = localhost
        port = 5050
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        ssl = 0
        web_root = ""
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        method = renamer
        delete_failed = 0
        wait_for = 2
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if Couchpotato is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[tv]]
        enabled = 1
        host = 127.0.0.1
        port = 8081
        username = 
        password =
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 1
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 1
        keep_archive = 1
        process_method = ""
        # force processing of already processed content when running a manual scan.
        force = 0
        # tell SickRage to delete all source files after processing.
        delete_on = 1
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 1
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = C:\nzb\complete
    [[sports]]
        enabled = 1
        host = 127.0.0.1
        port = 8081
        username =
        password = 
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 1
        Torrent_NoLink = 1
        process_method = ""
        force = 0
        extract = 1
        nzbExtractionBy = Downloader
        minSize = 0
        delete_ignored = 1
        remote_path = 0
        watch_dir = C:\nzb\complete
    [[Tor]]
        enabled = 1
        host = 127.0.0.1
        port = 8081
        username = 
        password = 
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 1
        Torrent_NoLink = 1
        process_method = ""
        force = 0
        extract = 1
        nzbExtractionBy = Downloader
        minSize = 0
        delete_ignored = 1
        remote_path = 0
        watch_dir = C:\nzb\complete
    [[*]]
        enabled = 1
        host = 127.0.0.1
        port = 8081
        username = 
        password =
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 1
        Torrent_NoLink = 1
        process_method = ""
        force = 0
        extract = 1
        nzbExtractionBy = Downloader
        minSize = 0
        delete_ignored = 1
        remote_path = 0
        watch_dir = C:\nzb\complete
    [[movies]]
        enabled = 1
        host = 127.0.0.1
        port = 8081
        username = 
        password = 
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 1
        Torrent_NoLink = 1
        process_method = ""
        force = 0
        extract = 1
        nzbExtractionBy = Downloader
        minSize = 0
        delete_ignored = 1
        remote_path = 0
        watch_dir = C:\nzb\complete

[NzbDrone]
    #### autoProcessing for TV Series
    #### ndCategory - category that gets called for post-processing with NzbDrone
    [[tv]]
        enabled = 0
        apikey = ""
        host = localhost
        port = 8989
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
        nzbExtractionBy = Downloader
        wait_for = 2
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if NzbDrone is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

[HeadPhones]
    #### autoProcessing for Music
    #### music - category that gets called for post-processing with HP
    [[music]]
        enabled = 0
        apikey = ""
        host = localhost
        port = 8181
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        ssl = 0
        web_root = ""
        wait_for = 2
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if HeadPhones is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

[Mylar]
    #### autoProcessing for Comics
    #### comics - category that gets called for post-processing with Mylar
    [[comics]]
        enabled = 0
        host = localhost
        port = 8090
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if Mylar is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

[Gamez]
    #### autoProcessing for Games
    #### games - category that gets called for post-processing with Gamez
    [[games]]
        enabled = 0
        apikey = ""
        host = localhost
        port = 8085
        ###### 
        library = Set to path where you want the processed games to be moved to.
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        ssl = 0
        web_root = ""
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 1
        keep_archive = 1
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if Gamez is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

[Network]
    # Enter Mount points as LocalPath,RemotePath and separate each pair with '|'
    # e.g. MountPoints = /volume1/Public/,E:|/volume2/share/,\NAS\
    mount_points = C:\nzb\complete, Y:\

[Nzb]
    ###### clientAgent - Supported clients: sabnzbd, nzbget
    clientAgent = sabnzbd
    ###### SabNZBD (You must edit this if your using nzbToMedia.py with SabNZBD)
    sabnzbd_host = 127.0.0.1
    sabnzbd_port = 8080
    sabnzbd_apikey = 83f0ed7369e3f62065b6f66980c8dfcf
    ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode.
    default_downloadDirectory = Y:\sickrage\complete

[Torrent]
    ###### clientAgent - Supported clients: utorrent, transmission, deluge, rtorrent, vuze, other
    clientAgent = utorrent
    ###### useLink - Set to hard for physical links, sym for symbolic links, move to move, move-sym to move and link back, and no to not use links (copy)
    useLink = no
    ###### outputDirectory - Default output directory (categories will be appended as sub directory to outputDirectory)
    outputDirectory = c:\nzb\complete
    ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode. 
    default_downloadDirectory = c:\nzb\temp
    ###### Other categories/labels defined for your downloader. Does not include CouchPotato, SickBeard, HeadPhones, Mylar categories.
    categories = tv, Tor
    ###### A list of categories that you don't want to be flattened (i.e preserve the directory structure when copying/linking.
    noFlatten = tv, Tor
    ###### uTorrent Hardlink solution (You must edit this if your using TorrentToMedia.py with uTorrent)
    uTorrentWEBui = http://localhost:8082/gui/
    uTorrentUSR = 
    uTorrentPWD = 
    ###### Transmission (You must edit this if your using TorrentToMedia.py with Transmission)
    TransmissionHost = localhost
    TransmissionPort = 9091
    TransmissionUSR = your username
    TransmissionPWD = your password
    #### Deluge (You must edit this if your using TorrentToMedia.py with deluge. Note that the host/port is for the deluge daemon, not the webui)
    DelugeHost = localhost
    DelugePort = 58846
    DelugeUSR = your username
    DelugePWD = your password
    ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
    deleteOriginal = 1
    chmodDirectory = 0
    resume = 1
    resumeOnFailure = 1

**Comment by clinton-hall** [comment]
is the log above from a manual run or called from uTorrent?

you need to have uTorrent call the script and pass in the parameters...

In µTorrent go to preferences > Advanced > Run Program > Run this program when torrent finishes:

i. Set full path to script, pass paramaters as "%D" "%N" "%L" "%I".

`/usr/local/utorrent/nzbToMedia/TorrentToMedia.py "%D" "%N" "%L" "%I"`

**Comment by boomertheweim** [comment]
Hi,


I have that set up in uTorrent and this was called form uTorrent

**Comment by c0m3d1an** [comment]
Judging from the error you received 

> 2016-05-05 02:56:23 WARNING ::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...

And the fact that you have 

> Category: *

Showing in your error logs

It *looks* like you may not have set  "Append Torrents Label" = Enabled in Utorrent, or labels are not properly passing to it from Sickbeard.
