### ISSUE TITLE
trancode double processing

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1027]
I realize this might be an edge case but i have noticed a number of times where i've aborted/reboot during transcode and then later, see lines like the below. Note the -transcoded-transcoded.mp4.
I'm wondering if a check for existing -transcode.ext, verifying it, and overwriting it if it is invalid or skipping if valid.

2016-05-07 23:07:46 INFO    ::MAIN: Transcoding video: /home/@send/TV/Wynonna echnician Tools']
 Earp/Wynonna.Earp.-.S01E04.-.WEB-DL.x264-RARBG-transcoded-transcoded.mp4

**Comment by clinton-hall** [comment]
interesting.

Certainly a check for "transcoded" and non transcoded files would be easy, and just force over-write of transcoded... this would assume that the transcoded wasn't post-processed fully and therefore there may have been a failure.

If I add a check for valid, I would also add a check to see if a non "trascoded" file exists and see if both transcoded and non transcoded have the same video length?? Just in case the video was cut short in transcoding but is still "playable"?

**Comment by mgaulton** [comment]
So funny story, i found a folder full of files named oddly
Full.House.-.S02E20.-.I'm.There.for.You.Babe.DVDRip.x264-MaG-Chamele0n-transcoded-transcoded-transcoded-transcoded-transcoded-transcoded-transcoded-transcoded-transcoded.mp4
