### ISSUE TITLE
sickrage: custom branch does not handle failed downloads

### ISSUE THREAD

**Issue by dreaganluna** [clinton-hall/nzbToMedia#1028]
Since a couple weeks I've been having trouble to find why nzbToMedia won't post-process my failed downloads anymore. I'm using the branch that comes with sickRage, which is currently at 1cd6405, and have the following config:

```
[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[series]]
        enabled = 1
        host = localhost
        port = 8081
        username = admin
        password = admin
        web_root = ""
        ssl = 0
        fork = SickRage
        delete_failed = 0
        Torrent_NoLink = 0
        process_method = ""
        force = 0
        extract = 1
        nzbExtractionBy = Downloader
        minSize = 0
        delete_ignored = 0
        remote_path = 0
        watch_dir = ""
```

The logs tell me this:

> [13:13:04] [INFO]::MAIN: Calling SickBeard:series to post-process:Family.Guy.S14E17.Take.a.Letter.720p.WEB-DL.DD5.1.H.264-CtrlHD.nzb
> [13:13:05] [INFO]::MAIN: Attempting to auto-detect series fork
> [13:13:09] [INFO]::MAIN: SickBeard:series fork auto-detection found custom params {'failed': None, 'force': None, 'process_method': None}
> [13:13:09] [INFO]::MAIN: SickBeard:series fork set to custom
> [13:13:09] [WARNING]::SICKBEARD: No media files found in directory C:\Users\Watson\Documents\Downloads\incomplete\Family.Guy.S14E17.T. Processing this as a failed download
> [13:13:09] [POSTPROCESS]::SICKBEARD: FAILED: The download failed. custom branch does not handle failed downloads. Nothing to process
> [13:13:09] [ERROR]::MAIN: A problem was reported in the C:\SickRage\contrib\nzbToMedia\nzbToMedia.py script.

It seems to me that there might be an issue with detecting the fork config? I have no idea if "fork set to custom" is expected behaviour.

Do you know what might be going wrong here?
I have already double-checked my config in sickRage itself, to make sure failed processing is turned on.

best regards,
dreagan

**Comment by clinton-hall** [comment]
I fixed this in nightly branch.
I'll merger this to master shortly, but you need to update to latest.

**Comment by dreaganluna** [comment]
Thanks! When merged into master, I'll try again.
