### ISSUE TITLE
Make renaming of movies with imdb id optional?

### ISSUE THREAD

**Issue by bendavid** [clinton-hall/nzbToMedia#1030]
In case a downloaded film does not have an imdb id in the filename, the script tries to rename the file to add it here
https://github.com/clinton-hall/nzbToMedia/blob/master/core/autoProcess/autoProcessMovie.py#L211-L216

This breaks re-linking of torrents for seeding since the filename is changed.  Actually I don't think this step is really needed at all, since couchpotato has its own logic for finding the missing imdb id.  (Arguably couchpotato should just append the needed information to the download folder when queuing up the torrent download anyway).  At minimum it could be made configurable.

**Comment by clinton-hall** [comment]
ok... I had to follow this through a little.

I think what you are saying is this is an issue when using the move-link option?
this wouldn't be a problem for move, copy, hard, or sym link options...

**Comment by clinton-hall** [comment]
please test the latest nightly.

**Comment by bendavid** [comment]
Alright, will give it a try. (and agreed that it should fix the immediate issue)

I think my comment was more general that searching for the imdb in the nzbToMedia script shouldn't be needed at all, given that this functionality already exists and will be called in couchpotato when it scans the directory.
