### ISSUE TITLE
Target folder gets "extension" removed if input is a directory

### ISSUE THREAD

**Issue by Metarded** [clinton-hall/nzbToMedia#1033]
2016-05-06 19:17:54 INFO    ::COPYLINK: SOURCE FOLDER: [**/volume1/download/complete/movie/Idiocracy.2006.1080p.WEB-DL.DD5.1.H264-FGT**]
2016-05-06 19:17:54 INFO    ::COPYLINK: TARGET FOLDER: [**/volume1/download/movie/Idiocracy.2006.1080p.WEB-DL.DD5.1**]
2016-05-06 19:17:54 INFO    ::COPYLINK: Moving SOURCE MEDIAFILE -> TARGET FOLDER

Changing 
if not os.path.isdir(os.path.join(inputDirectory, inputName)):
to
if os.path.isdir(os.path.join(inputDirectory, inputName)) is None:

in TorrentToMedia.py seems to help, but I'm no python expert.

I'm on a synology NAS.

**Comment by Metarded** [comment]
some more details:

When inputDirectory is a folder and inputName doesn't contain an extension (which happens quite often); then 

**_if not os.path.isdir(os.path.join(inputDirectory, inputName)):_**

gives a true because the folder doesn't exists and removes the "extension" from the inputName.

When inputDirectory is a file,  **_if not os.path.isdir(os.path.join(inputDirectory, inputName)):_** is always true because joining inputDirectory with inputName will always generate a file/folder that doesn't exit. 

A suggestion is to only check if inputDirectory is a file or not.
for example: if os.path.isfile(inputDirectory): then chop the extension.

**Comment by MrCee** [comment]
@Metarded This was happening for myself also, the last master commit fixed this. I have not seen this problem since. Are we all on the same master commit? 

`MAIN: nzbToMedia Version:c50957d0b4683a125df039329d8f90df630d4e28 Branch:master`

Having said that, there certainly is a difference between a torrent being downloaded by itself as a video file, and a torrent being downloaded within a folder and the video file contained within the folder. 

Let me know if this may relate, I have not looked into the python side of things as you have: https://github.com/clinton-hall/nzbToMedia/issues/964

Cheers

**Comment by Metarded** [comment]
Yes. Same master commit. 
I did a git clone just in case and tried it on a recent release that generated the error. Still cuts the folder name. 

```
MAIN: Received Directory: /volume1/download/complete/movie/London.Has.Fallen.2016.1080p.WEB-DL.AAC2.0.H264-FGT | Name: London.Has.Fallen.2016.1080p.WEB-DL.AAC2.0.H264-FGT | Category: movie
MAIN: SEARCH: Found the Category: movie in directory structure
MAIN: SEARCH: Found a unique directory London.Has.Fallen.2016.1080p.WEB-DL.AAC2.0.H264-FGT in the category directory
MAIN: Determined Directory: /volume1/download/complete/movie/London.Has.Fallen.2016.1080p.WEB-DL.AAC2.0.H264-FGT | Name: London.Has.Fallen.2016.1080p.WEB-DL.AAC2.0.H264-FGT | Category: movie
MAIN: Auto-detected SECTION:CouchPotato
MAIN: Output directory set to: /volume1/download/movie/London.Has.Fallen.2016.1080p.WEB-DL.AAC2.0
MAIN: Scanning files in directory: /volume1/download/complete/movie/London.Has.Fallen.2016.1080p.WEB-DL.AAC2.0.H264-FGT
MAIN: Found 2 files in /volume1/download/complete/movie/London.Has.Fallen.2016.1080p.WEB-DL.AAC2.0.H264-FGT
COPYLINK: MEDIAFILE: [London.Has.Fallen.2016.1080p.WEB-DL.AAC2.0.H264-FGT.mkv]
COPYLINK: SOURCE FOLDER: [/volume1/download/complete/movie/London.Has.Fallen.2016.1080p.WEB-DL.AAC2.0.H264-FGT]
COPYLINK: TARGET FOLDER: [/volume1/download/movie/London.Has.Fallen.2016.1080p.WEB-DL.AAC2.0]

```
It could be my setup file or couchpotato that's messing with me. But replacing ```not os.path.isdir(os.path.join(inputDirectory, inputName))``` with ```os.path.isfile(inputDirectory)``` in TorrentToMedia.py sorts it out for now.

**Comment by clinton-hall** [comment]
I believe this should be fixed in current nightly after this
https://github.com/clinton-hall/nzbToMedia/commit/9225aa26ae92a8e70cd204ba98037dc2ac8f6ad0

please switch to nightly and test.

**Comment by Metarded** [comment]
The nightly seems to have solved it. 
Keep up the good work!
