### ISSUE TITLE
subtitle download problem

### ISSUE THREAD

**Issue by diglam** [clinton-hall/nzbToMedia#1035]
I'm new to nzbToMedia and having problem with subtitle download.
There are two different case:
Case 1 - No error message in nzbtomedia.log for subtitle download

> 2016-05-13 20:25:23 INFO    ::MAIN: 
> ###### 
> 
> 2016-05-13 20:25:23 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
> 2016-05-13 20:25:23 INFO    ::MAIN: #########################################################
> 2016-05-13 20:25:23 DEBUG   ::MAIN: Options passed into nzbToMedia: ['nzbToMedia.py']
> 2016-05-13 20:25:23 WARNING ::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
> 2016-05-13 20:25:23 INFO    ::MAIN: Searching /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film for mediafiles to post-process ...
> 2016-05-13 20:25:23 INFO    ::MAIN: Starting manual run for CouchPotato:film - Folder:/media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N
> 2016-05-13 20:25:23 INFO    ::MAIN: Checking database for download info for Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N ...
> 2016-05-13 20:25:23 DB      ::DB: Getting download info for Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N from the DB
> 2016-05-13 20:25:23 DB      ::MAIN: nzbtomedia.db: SELECT \* FROM downloads WHERE input_name=? AND status=? with args [u'Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N', 0]
> 2016-05-13 20:25:23 INFO    ::MAIN: Unable to locate download info for Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N, continuing to try and process this release ...
> 2016-05-13 20:25:23 INFO    ::MAIN: Auto-detected SECTION:CouchPotato
> 2016-05-13 20:25:23 DEBUG   ::MAIN: Checking for archives to extract in directory: /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N
> 2016-05-13 20:25:23 INFO    ::MAIN: Calling CouchPotato:film to post-process:Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N
> 2016-05-13 20:25:23 INFO    ::MAIN: Attemping imdbID lookup for Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N
> 2016-05-13 20:25:23 INFO    ::MAIN: Searching folder and file names for imdbID ...
> 2016-05-13 20:25:23 INFO    ::MAIN: Searching IMDB for imdbID ...
> 2016-05-13 20:25:25 DEBUG   ::MAIN: Opening URL: http://www.omdbapi.com
> 2016-05-13 20:25:26 INFO    ::MAIN: Found imdbID [tt1411250]
> 2016-05-13 20:25:26 DEBUG   ::MAIN: Opening URL: http://localhost:5050/api/fccfd86a9abf436c8e69de214b4d40c3/media.get with PARAMS: {'id': u'tt1411250'}
> 2016-05-13 20:25:26 DEBUG   ::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0000-betik/nzbToMedia/tests/test.mp4
> 2016-05-13 20:25:27 INFO    ::TRANSCODER: Checking [Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N.mkv] for corruption, please stand by ...
> 2016-05-13 20:25:27 DEBUG   ::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N/Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N.mkv
> 2016-05-13 20:25:28 INFO    ::TRANSCODER: SUCCESS: [Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N.mkv] has no corruption.
> 2016-05-13 20:25:28 DEBUG   ::SUBTITLES: Attempting to download subtitles for /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N/Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N.mkv
> 2016-05-13 20:25:49 DEBUG   ::COUCHPOTATO: Opening URL: http://localhost:5050/api/fccfd86a9abf436c8e69de214b4d40c3/renamer.scan with PARAMS: {'download_id': u'SABnzbd_nzo_56adIP', 'media_folder': '/media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N', 'downloader': u'Sabnzbd'}
> 2016-05-13 20:25:49 POSTPROCESS::COUCHPOTATO: Starting renamer scan for Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N
> 2016-05-13 20:28:04 POSTPROCESS::COUCHPOTATO: SUCCESS: Finished renamer scan for folder /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N
> 2016-05-13 20:28:04 POSTPROCESS::COUCHPOTATO: Checking for status change, please stand by ...
> 2016-05-13 20:28:04 DEBUG   ::MAIN: Opening URL: http://localhost:5050/api/fccfd86a9abf436c8e69de214b4d40c3/media.get with PARAMS: {'id': u'ff9df9d5f43246a49d02b06e4df2bd9f'}
> 2016-05-13 20:28:04 POSTPROCESS::COUCHPOTATO: SUCCESS: Input Directory [/media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N] has no remaining media files. This has been fully processed.
> 2016-05-13 20:28:04 INFO    ::CLEANDIRS: Directory /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N has been processed, removing ...
> 2016-05-13 20:28:04 INFO    ::MAIN: The nzbToMedia.py script completed successfully.

but no subtitle downloaded

with command

> subliminal --debug --opensubtitles username password download -l tr Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N.mkv
> Collecting videos  [####################################]  100%  Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N.mkvDEBUG:subliminal.cli:Collecting path Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N.mkv
> INFO:subliminal.video:Scanning video 'Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N.mkv' in ''
> DEBUG:subliminal.video:Size is 4260332538
> DEBUG:subliminal.video:Computed hashes {'opensubtitles': 'fb1c8155104738ad', 'thesubdb': '601fa837fa99b9e114f04991dcc48486', 'napiprojekt': 'a17b1108bb51780eee53dbd373d371ad'}
> DEBUG:subliminal.video:Found subtitles {}
> DEBUG:subliminal.video:Found video_codec h264 with enzyme
> DEBUG:subliminal.video:Found audio_codec DTS with enzyme
> DEBUG:subliminal.video:Found embedded subtitle set([<Language [fr]>, <Language [und]>, <Language [es]>]) with enzyme
> Collecting videos  [####################################]  100%
> 1 video collected / 0 video ignored / 0 error
> Downloading subtitles  [####################################]  100%  Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N.mkvINFO:subliminal.api:Listing subtitles with provider 'podnapisi' and languages set([<Language [tr]>])
> INFO:subliminal.api:Initializing provider podnapisi
> INFO:subliminal.providers.podnapisi:Searching subtitles {'sK': u'Riddick', 'sXML': 1, 'sY': 2013, 'sL': 'tr'}
> DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle 'RoIr' [tr]>
> DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle 'F_0p' [tr]>
> INFO:subliminal.api:Skipping provider 'tvsubtitles': not a valid video
> INFO:subliminal.api:Listing subtitles with provider 'opensubtitles' and languages set([<Language [tr]>])
> INFO:subliminal.api:Initializing provider opensubtitles
> INFO:subliminal.providers.opensubtitles:Logging in
> DEBUG:subliminal.providers.opensubtitles:Logged in with token '6gre6c94p6cl0772gj5acad471'
> INFO:subliminal.providers.opensubtitles:Searching subtitles [{'moviebytesize': '4260332538', 'sublanguageid': u'tur', 'moviehash': 'fb1c8155104738ad'}]
> DEBUG:subliminal.providers.opensubtitles:No subtitles found
> INFO:subliminal.api:Skipping provider 'addic7ed': not a valid video
> INFO:subliminal.api:Skipping provider 'subscenter': no language to search for
> INFO:subliminal.api:Listing subtitles with provider 'thesubdb' and languages set([<Language [tr]>])
> INFO:subliminal.api:Initializing provider thesubdb
> INFO:subliminal.providers.thesubdb:Searching subtitles {'action': 'search', 'hash': '601fa837fa99b9e114f04991dcc48486'}
> DEBUG:subliminal.providers.thesubdb:No subtitles found
> INFO:subliminal.subtitle:Computing score for matches set(['title', 'year', 'video_codec', 'format', 'resolution', 'hearing_impaired']) and <Movie [u'Riddick', 2013]>
> DEBUG:subliminal.subtitle:Final matches: set(['title', 'video_codec', 'format', 'year', 'resolution', 'hearing_impaired'])
> INFO:subliminal.subtitle:Computed score 50
> INFO:subliminal.subtitle:Computing score for matches set(['year', 'hearing_impaired', 'title']) and <Movie [u'Riddick', 2013]>
> DEBUG:subliminal.subtitle:Final matches: set(['title', 'hearing_impaired', 'year'])
> INFO:subliminal.subtitle:Computed score 36
> INFO:subliminal.api:Downloading subtitle <PodnapisiSubtitle 'RoIr' [tr]> with score 50
> INFO:subliminal.api:Downloading subtitle <PodnapisiSubtitle 'RoIr' [tr]>
> INFO:subliminal.providers.podnapisi:Downloading subtitle <PodnapisiSubtitle 'RoIr' [tr]>
> INFO:subliminal.subtitle:Guessing encoding for language tr
> DEBUG:subliminal.subtitle:Trying encodings ['utf-8', 'iso-8859-9', 'windows-1254']
> INFO:subliminal.subtitle:Guessed encoding iso-8859-9
> INFO:subliminal.subtitle:Guessing encoding for language tr
> DEBUG:subliminal.subtitle:Trying encodings ['utf-8', 'iso-8859-9', 'windows-1254']
> INFO:subliminal.subtitle:Guessed encoding iso-8859-9
> DEBUG:subliminal.api:All languages downloaded
> Downloading subtitles  [####################################]  100%
> DEBUG:subliminal.api:Terminating initialized providers
> INFO:subliminal.api:Terminating provider podnapisi
> INFO:subliminal.api:Terminating provider thesubdb
> INFO:subliminal.api:Terminating provider opensubtitles
> INFO:subliminal.providers.opensubtitles:Logging out
> DEBUG:subliminal.providers.opensubtitles:Logged out
> INFO:subliminal.api:Saving <PodnapisiSubtitle 'RoIr' [tr]> to 'Riddick.2013.UNRATED.DC.720p.REPACK.Bluray.DTS.x264-LEGi0N.tr.srt'
> Downloaded 1 subtitle

subliminal downloads related subtitle.

Case 2 - There is error message in nzbtomedia.log for subtitle download

> 2016-05-13 20:47:22 INFO    ::MAIN: #########################################################
> 2016-05-13 20:47:22 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
> 2016-05-13 20:47:22 INFO    ::MAIN: #########################################################
> 2016-05-13 20:47:22 DEBUG   ::MAIN: Options passed into nzbToMedia: ['nzbToMedia.py']
> 2016-05-13 20:47:22 WARNING ::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
> 2016-05-13 20:47:22 INFO    ::MAIN: Searching /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film for mediafiles to post-process ...
> 2016-05-13 20:47:22 INFO    ::MAIN: Starting manual run for CouchPotato:film - Folder:/media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG
> 2016-05-13 20:47:22 INFO    ::MAIN: Checking database for download info for Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG ...
> 2016-05-13 20:47:22 DB      ::DB: Getting download info for Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG from the DB
> 2016-05-13 20:47:22 DB      ::MAIN: nzbtomedia.db: SELECT \* FROM downloads WHERE input_name=? AND status=? with args [u'Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG', 0]
> 2016-05-13 20:47:22 INFO    ::MAIN: Unable to locate download info for Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG, continuing to try and process this release ...
> 2016-05-13 20:47:22 INFO    ::MAIN: Auto-detected SECTION:CouchPotato
> 2016-05-13 20:47:22 DEBUG   ::MAIN: Checking for archives to extract in directory: /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG
> 2016-05-13 20:47:22 INFO    ::MAIN: Calling CouchPotato:film to post-process:Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG
> 2016-05-13 20:47:22 INFO    ::MAIN: Attemping imdbID lookup for Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG
> 2016-05-13 20:47:22 INFO    ::MAIN: Searching folder and file names for imdbID ...
> 2016-05-13 20:47:22 INFO    ::MAIN: Searching IMDB for imdbID ...
> 2016-05-13 20:47:23 DEBUG   ::MAIN: Opening URL: http://www.omdbapi.com
> 2016-05-13 20:47:24 INFO    ::MAIN: Found imdbID [tt2395427]
> 2016-05-13 20:47:24 DEBUG   ::MAIN: Opening URL: http://localhost:5050/api/fccfd86a9abf436c8e69de214b4d40c3/media.get with PARAMS: {'id': u'tt2395427'}
> 2016-05-13 20:47:24 DEBUG   ::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0000-betik/nzbToMedia/tests/test.mp4
> 2016-05-13 20:47:24 INFO    ::TRANSCODER: Checking [Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG.avi] for corruption, please stand by ...
> 2016-05-13 20:47:25 DEBUG   ::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG/Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG.avi
> 2016-05-13 20:47:26 INFO    ::TRANSCODER: SUCCESS: [Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG.avi] has no corruption.
> 2016-05-13 20:47:26 DEBUG   ::SUBTITLES: Attempting to download subtitles for /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG/Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG.avi
> 2016-05-13 20:47:39 ERROR   ::SUBTITLES: Failed to download subtitles for /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG/Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG.avi due to: string index out of range
> 2016-05-13 20:47:39 DEBUG   ::COUCHPOTATO: Opening URL: http://localhost:5050/api/fccfd86a9abf436c8e69de214b4d40c3/renamer.scan with PARAMS: {'media_folder': '/media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG'}
> 2016-05-13 20:47:39 POSTPROCESS::COUCHPOTATO: Starting renamer scan for Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG
> 2016-05-13 20:49:10 POSTPROCESS::COUCHPOTATO: SUCCESS: Finished renamer scan for folder /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG
> 2016-05-13 20:49:10 POSTPROCESS::COUCHPOTATO: Checking for status change, please stand by ...
> 2016-05-13 20:49:10 DEBUG   ::MAIN: Opening URL: http://localhost:5050/api/fccfd86a9abf436c8e69de214b4d40c3/media.get with PARAMS: {'id': u'a42d5c52ad16451e950ac4b55836aabc'}
> 2016-05-13 20:49:10 POSTPROCESS::COUCHPOTATO: SUCCESS: Release Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG has now been marked with a status of [DONE]
> 2016-05-13 20:49:11 INFO    ::CLEANDIRS: Directory /media/11da2037-bc72-4bae-8257-c88ed9d5f521/0200-Indirme/0100-Otomatik_Indirmeler/0200-NZB/0100-Tamam/Film/Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG has been processed, removing ...
> 2016-05-13 20:49:11 INFO    ::MAIN: The nzbToMedia.py script completed successfully.

and no subtitle downloaded

with command

> subliminal --debug --opensubtitles username password download -l tr Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG.avi
> Collecting videos  [####################################]  100%  Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG.aviDEBUG:subliminal.cli:Collecting path Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG.avi
> INFO:subliminal.video:Scanning video 'Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG.avi' in ''
> DEBUG:subliminal.video:Size is 1475850396
> DEBUG:subliminal.video:Computed hashes {'opensubtitles': '7841c4c58b86f766', 'thesubdb': '612442a9317e34c2369e14124e2fe379', 'napiprojekt': '121f22cb13c356fcf2a4b10f01d25fd2'}
> DEBUG:subliminal.video:Found subtitles {}
> Collecting videos  [####################################]  100%
> 1 video collected / 0 video ignored / 0 error
> Downloading subtitles  [####################################]  100%  Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG.aviINFO:subliminal.api:Listing subtitles with provider 'podnapisi' and languages set([<Language [tr]>])
> INFO:subliminal.api:Initializing provider podnapisi
> INFO:subliminal.providers.podnapisi:Searching subtitles {'sK': u'Avengers Age of Ultron', 'sXML': 1, 'sY': 2015, 'sL': 'tr'}
> DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle 'M-I9' [tr]>
> DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle 'NuI9' [tr]>
> DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle 'NeI9' [tr]>
> DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle 'NOI9' [tr]>
> DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle 'jdI9' [tr]>
> DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle '8qI9' [tr]>
> INFO:subliminal.api:Skipping provider 'tvsubtitles': not a valid video
> INFO:subliminal.api:Listing subtitles with provider 'opensubtitles' and languages set([<Language [tr]>])
> INFO:subliminal.api:Initializing provider opensubtitles
> INFO:subliminal.providers.opensubtitles:Logging in
> DEBUG:subliminal.providers.opensubtitles:Logged in with token 'fhidf3isrgf4f4lms1at97jmg0'
> INFO:subliminal.providers.opensubtitles:Searching subtitles [{'moviebytesize': '1475850396', 'sublanguageid': u'tur', 'moviehash': '7841c4c58b86f766'}]
> DEBUG:subliminal.providers.opensubtitles:No subtitles found
> INFO:subliminal.api:Skipping provider 'addic7ed': not a valid video
> INFO:subliminal.api:Skipping provider 'subscenter': no language to search for
> INFO:subliminal.api:Listing subtitles with provider 'thesubdb' and languages set([<Language [tr]>])
> INFO:subliminal.api:Initializing provider thesubdb
> INFO:subliminal.providers.thesubdb:Searching subtitles {'action': 'search', 'hash': '612442a9317e34c2369e14124e2fe379'}
> DEBUG:subliminal.providers.thesubdb:No subtitles found
> INFO:subliminal.subtitle:Computing score for matches set(['format', 'year', 'hearing_impaired', 'title']) and <Movie [u'Avengers Age of Ultron', 2015]>
> DEBUG:subliminal.subtitle:Final matches: set(['title', 'year', 'hearing_impaired', 'format'])
> INFO:subliminal.subtitle:Computed score 42
> INFO:subliminal.subtitle:Computing score for matches set(['title', 'format', 'audio_codec', 'year', 'video_codec', 'hearing_impaired']) and <Movie [u'Avengers Age of Ultron', 2015]>
> DEBUG:subliminal.subtitle:Final matches: set(['audio_codec', 'title', 'video_codec', 'format', 'year', 'hearing_impaired'])
> INFO:subliminal.subtitle:Computed score 48
> INFO:subliminal.subtitle:Computing score for matches set(['title', 'format', 'audio_codec', 'year', 'video_codec', 'hearing_impaired']) and <Movie [u'Avengers Age of Ultron', 2015]>
> DEBUG:subliminal.subtitle:Final matches: set(['audio_codec', 'title', 'video_codec', 'format', 'year', 'hearing_impaired'])
> INFO:subliminal.subtitle:Computed score 48
> INFO:subliminal.subtitle:Computing score for matches set(['format', 'year', 'hearing_impaired', 'title']) and <Movie [u'Avengers Age of Ultron', 2015]>
> DEBUG:subliminal.subtitle:Final matches: set(['title', 'year', 'hearing_impaired', 'format'])
> INFO:subliminal.subtitle:Computed score 42
> INFO:subliminal.subtitle:Computing score for matches set(['audio_codec', 'year', 'video_codec', 'format', 'title', 'hearing_impaired']) and <Movie [u'Avengers Age of Ultron', 2015]>
> DEBUG:subliminal.subtitle:Final matches: set(['title', 'audio_codec', 'year', 'video_codec', 'format', 'hearing_impaired'])
> INFO:subliminal.subtitle:Computed score 48
> INFO:subliminal.subtitle:Computing score for matches set(['audio_codec', 'year', 'video_codec', 'title', 'hearing_impaired']) and <Movie [u'Avengers Age of Ultron', 2015]>
> DEBUG:subliminal.subtitle:Final matches: set(['video_codec', 'title', 'hearing_impaired', 'audio_codec', 'year'])
> INFO:subliminal.subtitle:Computed score 42
> INFO:subliminal.api:Downloading subtitle <PodnapisiSubtitle 'NuI9' [tr]> with score 48
> INFO:subliminal.api:Downloading subtitle <PodnapisiSubtitle 'NuI9' [tr]>
> INFO:subliminal.providers.podnapisi:Downloading subtitle <PodnapisiSubtitle 'NuI9' [tr]>
> INFO:subliminal.subtitle:Guessing encoding for language tr
> DEBUG:subliminal.subtitle:Trying encodings ['utf-8', 'iso-8859-9', 'windows-1254']
> INFO:subliminal.subtitle:Guessed encoding utf-8
> INFO:subliminal.subtitle:Guessing encoding for language tr
> DEBUG:subliminal.subtitle:Trying encodings ['utf-8', 'iso-8859-9', 'windows-1254']
> INFO:subliminal.subtitle:Guessed encoding utf-8
> DEBUG:subliminal.api:All languages downloaded
> Downloading subtitles  [####################################]  100%
> DEBUG:subliminal.api:Terminating initialized providers
> INFO:subliminal.api:Terminating provider podnapisi
> INFO:subliminal.api:Terminating provider thesubdb
> INFO:subliminal.api:Terminating provider opensubtitles
> INFO:subliminal.providers.opensubtitles:Logging out
> DEBUG:subliminal.providers.opensubtitles:Logged out
> INFO:subliminal.api:Saving <PodnapisiSubtitle 'NuI9' [tr]> to 'Avengers.Age.of.Ultron.2015.TR.BRRip.XviD.AC3-BTRG.tr.srt'
> Downloaded 1 subtitle

subliminal downloads a subtitle.

**autoProcessMedia.cfg:**

> [Transcoder]
>     # getsubs. enable to download subtitles.
>     getSubs = 1
>     # subLanguages. create a list of languages in the order you want them in your subtitles.
>     subLanguages = tur, eng
>     # transcode. enable to use transcoder
>     transcode = 0
>     ###### duplicate =1 will create a new file. =0 will replace the original
>     duplicate = 1
>     # concat. joins cd1 cd2 etc into a single video.
>     concat = 1
>     # IgnoreExtensions is a comma-separated list of extensions that will not be transcoded.
>     ignoreExtensions = .avi, .mkv, .mp4
>     # outputFastStart. 1 will use -movflags + faststart. 0 will disable this from being used.
>     outputFastStart = 0
>     # outputQualityPercent. used as -q:a value. 0 will disable this from being used.
>     outputQualityPercent = 0
>     # outputVideoPath. Set path you want transcoded videos moved to. Leave blank to disable.
>     outputVideoPath = ""
>     # processOutput. 1 will send the outputVideoPath to SickBeard/CouchPotato. 0 will send original files.
>     processOutput = 0
>     # audioLanguage. set the 3 letter language code you want as your primary audio track.
>     audioLanguage = tur
>     # allAudioLanguages. 1 will keep all audio tracks (uses AudioCodec3) where available.
>     allAudioLanguages = 1
>     # allSubLanguages. 1 will keep all existing sub languages. 0 will discard those not in your list above.
>     allSubLanguages = 1
>     # embedSubs. 1 will embed external sub/srt subs into your video if this is supported.
>     embedSubs = 1
>     # burnInSubtitle. burns the default sub language into your video (needed for players that don't support subs)
>     burnInSubtitle = 0
>     # extractSubs. 1 will extract subs from the video file and save these as external srt files.
>     extractSubs = 1
>     # externalSubDir. set the directory where subs should be saved (if not the same directory as the video)
>     externalSubDir = ""
>     # hwAccel. 1 will set ffmpeg to enable hardware acceleration (this requires a recent ffmpeg)
>     hwAccel = 1
>     # generalOptions. Enter your additional ffmpeg options here with commas to separate each option/value (i.e replace spaces with commas).
>     generalOptions = ""
>     # outputDefault. Loads default configs for the selected device. The remaining options below are ignored.
>     # If you want to use your own profile, leave this blank and set the remaining options below.
>     # outputDefault profiles allowed: iPad, iPad-1080p, iPad-720p, Apple-TV2, iPod, iPhone, PS3, xbox, Roku-1080p, Roku-720p, Roku-480p, mkv, mp4-scene-release
>     outputDefault = ""
>     #### Define custom settings below.
>     outputVideoExtension = .mp4
>     outputVideoCodec = libx264
>     VideoCodecAllow = ""
>     outputVideoPreset = medium
>     outputVideoResolution = 1920:1080
>     outputVideoFramerate = 24
>     outputVideoBitrate = 800000
>     outputVideoCRF = 19
>     outputVideoLevel = 3.1
>     outputAudioCodec = ac3
>     AudioCodecAllow = ""
>     outputAudioChannels = 6
>     outputAudioBitrate = 640k
>     outputAudioTrack2Codec = libfaac
>     AudioCodec2Allow = ""
>     outputAudioTrack2Channels = 2
>     outputAudioTrack2Bitrate = 128000
>     outputAudioOtherCodec = libmp3lame
>     AudioOtherCodecAllow = ""
>     outputAudioOtherChannels = ""
>     outputAudioOtherBitrate = 128000
>     outputSubtitleCodec = ""

And
I used subliminal which was installed with:
`pip install subliminal`

is it different then used by nzbToMedia?
Because I couldn't find any where to enter username and password for opensubtitle.

Thank you.

**Comment by clinton-hall** [comment]
this script packages it's own (old) version of subliminal
https://github.com/clinton-hall/nzbToMedia/tree/master/libs/subliminal

It looks like I need to update this and add user/pass options.

Current command passed is:
https://github.com/clinton-hall/nzbToMedia/blob/master/core/nzbToMediaUtil.py#L1102-L1104
