### ISSUE TITLE
::CLEANDIRS: Directory <DIR> has been processed, removing ... - Trying to keep RAR download (SickRage + Torrent)

### ISSUE THREAD

**Issue by caeci11ius** [clinton-hall/nzbToMedia#1039]
Using SickRage + uTorrent + TorrentToMedia.py.

Attempting to copy extracted media to destination folder on disk 2 from torrent download folder on disk 1, then delete extracted files, leaving the original rar files in their folder for seeding purposes.

I've tried pretty well every combination of settings I can think of, but can't seem to avoid the folder itself being removed following processing with the message "::CLEANDIRS: Directory <DIR> has been processed, removing ..." in the log.

In Sickrage, I have "Unpack" and "Delete RAR contents" turned on. In autoprocessconfig:

...fork = auto
delete_failed = 0
Torrent_NoLink = 0
keep_archive = 1
process_method = copy
force = 0
delete_on = 0
extract = 1
nzbExtractionBy = Destination
minSize = 50
delete_ignored = 0
remote_path = 0
watch_dir = ...

At my wits end here...it seems no matter what settings I use, the folder always gets deleted (unless I set it so the extracted MKV stays in there, but then it only skips it as there's an unprocessed file left over with message "::CLEANDIRS: Directory <DIR> still contains 1 unprocessed file(s), skipping ...".

Can someone suggest to me what I'm doing wrong? I've tried a lot of other settings as well but nothing seems to avoid the deletion of the folder once it's processed...

**Comment by clinton-hall** [comment]
I'd need to see all of the logs to know what is going on, but as a guess you have input directory and output directory the same.

in autoProcessMedia.cfg
```
[Torrent]
    useLink = hard
    outputDirectory  = <another directory on disk 1, but not the same as torrent download>
```

**Comment by caeci11ius** [comment]
Brilliant, that seem to have solved it. Appreciate the help! Had no idea the operations the script performs needed to take place in a different directory from where the downloader puts them...
