### ISSUE TITLE
Failed to Post Process or Python Quit unexpectedly Errors

### ISSUE THREAD

**Issue by npeters1205** [clinton-hall/nzbToMedia#1041]
I am trying a fresh install of OSX 10.7.5 (Lion) and trying to install NzbGet and upon trying to use any of the scripts I either get this error `env: python2: No such file or directory` . I have done the following to verify versions of Python.

`/usr/bin/python -V
/usr/local/bin/python -V
python -V`

All return the same 2.7.1.  This is what the default version seems to be in Mac OSX 10.7.5 (Lion). 

I've went into every script and changed the path from `/usr/bin/env python2` to `/usr/bin/env python`  this made no difference

I then tried running the following commands.

`sudo ln -s /usr/bin/python /usr/local/bin/python2` No change
I then added `ln -s /usr/bin/python /usr/bin/python2` and this seems to work, somewhat.
After the last comment.  it seems as though it tries to post process, however....  I then get an actual MacOS popup stating "Python quit unexpectedly"  When I go tho the report I get this as a report of the error.

`Process:         Python [2493]
Path:            /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:      Python
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  Python [2492]

Date/Time:       2016-05-27 17:04:33.899 -0400
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          118099 sec
Crashes Since Last Report:           242
Per-App Crashes Since Last Report:   224
Anonymous UUID:                      02F2C3B1-B1D8-4F6F-BFD8-B02C5B1620E3

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 0

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 2564
    thread_create: 0
    thread_set_state: 0

`

The thing that stands out to me on this is in this error it shows the Version as ???(???)

I am completely lost as to where to turn now.

Any help would be greatly appreciated.

**Comment by clinton-hall** [comment]
have you tried using the OSX branch of these scripts?

cd into the nzbToMedia directory then:
```
git checkout OSX
git pull
```
