### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by danielb2** [clinton-hall/nzbToMedia#1042]
From sabnzbd I get the following error:

``` bash
Traceback (most recent call last):
  File "/...SNIP.../nzbToMedia/core/autoProcess/autoProcessTV.py", line 5, in <module>
    import requests
ImportError: No module named requests
```

What am I doing wrong?

**Comment by clinton-hall** [comment]
https://github.com/clinton-hall/nzbToMedia/tree/master/libs/requests

this is included in the repository, so requests should be found.

does
`...SNIP.../nzbToMedia/libs/requests`
exist in your local clone?

**Comment by danielb2** [comment]
Yes it does. I checked that first :/

**Comment by MadOtis** [comment]
I, also, have this error.  However, when comparing the contents of the requests folder in my .../lib/requests folder, I only see 5 files and a sub-folder:

```
packages (sub-folder)
api.py
certs.py
cookies.py
hooks.py
sessions.py
```

Compared to (git repo: master branch):

```
packages (sub-folder) 
__init__.py
adapters.py
api.py
auth.py
cacert.pem
certs.py
compat.py
cookies.py
exceptions.py
hooks.py
models.py
sessions.py
status_codes.py
structures.py
utils.py
```

The confusing part is, I pulled directly from the repo using the instructions provided in the wiki.  I'm going to re-clone the requests folder and overlay what I have in my install and see if it makes any difference.

**Comment by labrys** [comment]
All vendored libs have been updated so this should no longer be an issue.  If it is, let us know and we'll reopen the issue.
