### ISSUE TITLE
SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!

### ISSUE THREAD

**Issue by spacecabbie** [clinton-hall/nzbToMedia#1045]
http://pastebin.com/SWS7hrj5

I am moving from a nas to dedicated windows server.
Te nas is still used for storage but nothing else
i get the above error running the scripts.
I hope this is the correct place to post this issue if not i am sorry for bothering you.

I dit find similar issues but the fixes for those do not work for me any advice ?

**Comment by labrys** [comment]
@spacecabbie Make sure your SickBeard fork and nzbToMedia are up to date, as a change was made to a couple of the parameters used in fork detection and if both are not updated you will likely get this issue.  You can try setting the actual fork in the config file if that doesn't work.  Lastly whichever fork you use may also need a changed pushed to it so you should report this issue there as well.

**Comment by JRShield** [comment]
I just wanted to report that I had to change my fork from Sickrage to auto and the PP went ok again. I had it on sickrage as that was the only fork NZBTOSICKBEARD handled properly in the past.
