### ISSUE TITLE
Sabnzbd history cleanup

### ISSUE THREAD

**Issue by michaelarlt** [clinton-hall/nzbToMedia#1046]
i dont know if this is an issue since it may not be implemented ;)
i have a running setup between sab using postprocess script nzbtoSickbeard.py and Sickrage. SR is marking failed downloads just fine and is even set to not trigger the postprocessing by itself, but let sab trigger that right after the download. Everything is working just fine apart from the history cleanup in sab after SR has processed either failed or successfully.
Is there any option built in to clean the respective download, and if so what options i have to focus on?

**Comment by clinton-hall** [comment]
I think the issue here is that SickRage can delete the completed download from SABnzbd history after processing, however since nzbToMedia sits between SABnzbd and SickRage, this doesn't happen.

This would need to be a new feature to be added to this script.

**Comment by michaelarlt** [comment]
Alrite, i thought its maybe some option i didnt find in the script itself. So ill address this question to the SickRage issue tracker as well since CouchPotato is even able to clean up its own history and i believe Sonarr (NZBDrone) as well. i suggest to keep this on hold until i come back with newer information.
If this enhancement will be implemented anyways to support all of those clients like Headphones, classic SickBeard and SickRage i wouldnt be sad :)

**Comment by michaelarlt** [comment]
ticket opened on SickRage Issue tracker
https://github.com/SickRage/SickRage/issues/1930
