### ISSUE TITLE
Transcoding question

### ISSUE THREAD

**Issue by c0m3d1an** [clinton-hall/nzbToMedia#1047]
Hi Clinton- I still love nzbToMedia more than cornflakes, so you're stuck with me for awhile.

I have a question about Transcoding settings for ffmpeg (for NZBToNZBDrone and NZBToCouchPotato specifically)

My transcoding settings are as follows:

outputVideoExtension:.mp4
outputVideoCodec: libx264
VideoCodecAllow: libx264, h264, h.264, AVC, avc, mpeg4, msmpeg4, MPEG-4, Xvid, DivX
outputVideoPreset:
outputVideoFramerate:
outputVideoBitrate:
outputAudioCodec: libfdk_aac
AudioCodecAllow: aac, libaac, libfdk_aac
outputAudioBitrate: 128k
outputQualityPercent:100
outputAudioTrack2Codec: libfdk_aac
AudioCodec2Allow: aac, libaac, libfdk_aac
outputAudioTrack2Bitrate: 384k
outputAudioOtherCodec: libaac
AudioOtherCodecAllow: aac, libaac, libfdk_aac
outputAudioOtherBitrate: 128k
outputSubtitleCodec: mov_text

My understanding is that, according to the settings above, if the input video is encoded in any of the VideoCodecAllow formats, ffmpeg should issue a COPY for the video stream (and the same for the audio stream as well, but that's usually what I'm converting to comply with native mp4).

If that is correct, I'm not getting that in the current GIT master.  In the example below, the source video is encoded h264, so I want to leave it alone and just transcode the audio.

`nice -n10 ionice -c2 -n4 /usr/sbin/ffmpeg -loglevel warning -fflags +genpts -i /Downloads/NZBGet/dst/tv/Grace.and.Frankie.S02E11.720p.WEBRip.x264-DEFLATE/Grace.and.Frankie.S02E11.720p.WEBRip.x264-DEFLATE.mkv -map 0:0 -map 0:1 -map 0:1 -map 0:2 -map 0:3 -c:v libx264 -crf 19 -level 3.1 -c:a:0 libfdk_aac -b:a:0 128000 -q:a:0 100 -c:a:1 libfdk_aac -ac:a:1 2 -b:a:1 384000 -q:a:1 100 -c:s mov_text -movflags +faststart /Downloads/NZBGet/dst/tv/Grace.and.Frankie.S02E11.720p.WEBRip.x264-DEFLATE/Grace.and.Frankie.S02E11.720p.WEBRip.x264-DEFLATE.mp4
`

So the command line should look something like:

`nice -n10 ionice -c2 -n4 /usr/sbin/ffmpeg -loglevel warning -fflags +genpts -i /Downloads/NZBGet/dst/tv/Grace.and.Frankie.S02E11.720p.WEBRip.x264-DEFLATE/Grace.and.Frankie.S02E11.720p.WEBRip.x264-DEFLATE.mkv -map 0:0 -map 0:1 -map 0:1 -map 0:2 -map 0:3 -c:v` **copy** `-crf 19 -level 3.1 -c:a:0 libfdk_aac -b:a:0 128000 -q:a:0 100 -c:a:1 libfdk_aac -ac:a:1 2 -b:a:1 384000 -q:a:1 100 -c:s mov_text -movflags +faststart /Downloads/NZBGet/dst/tv/Grace.and.Frankie.S02E11.720p.WEBRip.x264-DEFLATE/Grace.and.Frankie.S02E11.720p.WEBRip.x264-DEFLATE.mp4
`

Or did I just pick the wrong week to stop smoking crack?

**Comment by clinton-hall** [comment]
never the wrong week to stop smoking crack... but apparently this can cause some bad withdrawal symptoms.

To the tanscoder:
Your understanding is correct and this should copy the video.

Are you able to check the ouput of ffprobe on the video `Downloads/NZBGet/dst/tv/Grace.and.Frankie.S02E11.720p.WEBRip.x264-DEFLATE/Grace.and.Frankie.S02E11.720p.WEBRip.x264-DEFLATE.mkv`
I really need to see what ffprobe returns as the video codec.

**Comment by c0m3d1an** [comment]
Yeah it was h264, which was why I was confused.

**Comment by clinton-hall** [comment]
ok... I see...
Even though you didn't post above, you must have
```
[Transcoder]
    outputVideoCRF = 19
    outputVideoLevel = 3.1
```
which are the defaults... set these to
```
[Transcoder]
    outputVideoCRF = ""
    outputVideoLevel = ""
```
to see if that fixes it.

**Comment by c0m3d1an** [comment]
Yup that fixed it.  Yay!
