### ISSUE TITLE
Errors after latest update

### ISSUE THREAD

**Issue by saxonthebeach** [clinton-hall/nzbToMedia#1056]
I am getting the following errors; began after the latest update on 5/29. No NzbDrone items will post process since the update. Below is my nzbget log:

ERROR	Tue Jun 07 2016 07:19:32	Post-process-script nzbToMedia/nzbToNzbDrone.py for [x] failed (terminated with unknown status)
INFO	Tue Jun 07 2016 07:19:32	nzbToNzbDrone: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0xf6248f0c>> ignored
INFO	Tue Jun 07 2016 07:19:32	nzbToNzbDrone: ValueError: {} is not in list
INFO	Tue Jun 07 2016 07:19:32	nzbToNzbDrone: fork = core.FORKS.items()[core.FORKS.keys().index(cfg.get("fork", "auto"))]
INFO	Tue Jun 07 2016 07:19:32	nzbToNzbDrone: File "/share/MD0_DATA/Download/nzbToMedia/core/nzbToMediaAutoFork.py", line 24, in autoFork
INFO	Tue Jun 07 2016 07:19:32	nzbToNzbDrone: fork, fork_params = autoFork(section, inputCategory)
INFO	Tue Jun 07 2016 07:19:32	nzbToNzbDrone: File "/share/MD0_DATA/Download/nzbToMedia/core/autoProcess/autoProcessTV.py", line 69, in processEpisode
INFO	Tue Jun 07 2016 07:19:32	nzbToNzbDrone: download_id, inputCategory, failureLink)
INFO	Tue Jun 07 2016 07:19:32	nzbToNzbDrone: File "/share/MD0_DATA/Download/nzbToMedia/nzbToMedia.py", line 605, in process
INFO	Tue Jun 07 2016 07:19:32	nzbToNzbDrone: failureLink=failureLink)
INFO	Tue Jun 07 2016 07:19:32	nzbToNzbDrone: File "/share/MD0_DATA/Download/nzbToMedia/nzbToMedia.py", line 705, in main
INFO	Tue Jun 07 2016 07:19:32	nzbToNzbDrone: result = nzbToMedia.main(sys.argv, section)
INFO	Tue Jun 07 2016 07:19:32	nzbToNzbDrone: File "/share/MD0_DATA/.qpkg/NZBGet/nzbget/scripts/nzbToMedia/nzbToNzbDrone.py", line 236, in <module>
INFO	Tue Jun 07 2016 07:19:32	nzbToNzbDrone: Traceback (most recent call last):

**Comment by labrys** [comment]
@saxonthebeach Fix is in nightly, let me know if the issue still persists.

**Comment by saxonthebeach** [comment]
Thanks will check when I get home tonight

**Comment by saxonthebeach** [comment]
How do I switch to nightly build? Tried changing that parameter in autoprocessmedia.cfg and didn't seem to do it.

**Comment by saxonthebeach** [comment]
Switched to nightly via git checkout and this does not appear to have fixed it.

**Comment by saxonthebeach** [comment]
@labrys in case helpful this is the output when I try to run nzbToMedia.py via ssh:

Traceback (most recent call last):
  File "nzbToMedia.py", line 807, in <module>
    exit(main(sys.argv))
  File "nzbToMedia.py", line 633, in main
    core.initialize(section)
  File "/share/MD0_DATA/Download/nzbToMedia/core/__init__.py", line 279, in initialize
    if not config.migrate():
  File "/share/MD0_DATA/Download/nzbToMedia/core/nzbToMediaConfig.py", line 242, in migrate
    CFG_OLD.write()
  File "/share/MD0_DATA/Download/nzbToMedia/libs/configobj/configobj.py", line 2123, in write
    'ascii'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 421: ordinal not in range(128)
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0xf6225f2c>> ignored

**Comment by labrys** [comment]
It looks like this is a different error.  It looks like you have a unicode error in your config file.  The `\u201c` is a left smart-quote (`“` instead of `"`).  See if changing the quote fixes that error.  Also since you have a left smart-quote, check for right smart-quotes as well (`”`) and replace them.  Likely the quotes can be fixed with the rewrite of the config parser.

**Comment by labrys** [comment]
Also noticed I merged the fix to dev instead of nightly.  It is now in both dev and nightly.

**Comment by saxonthebeach** [comment]
@labrys I fixed the quote and tried both dev and nightly branches. Strangely if I run nzbToMedia.py via ssh I get no errors, but when I attempt to postprocess downloads in nzbget that failed previously I still get the following:

```
ERROR	Wed Jun 08 2016 07:51:10	Post-process-script nzbToMedia/nzbToNzbDrone.py for Stephen.Colbert.2016.06.06.James.Corden.720p.HDTV.x264-CROOKS failed (terminated with unknown status)
INFO	Wed Jun 08 2016 07:51:10	nzbToNzbDrone: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0xf6379f8c>> ignored
INFO	Wed Jun 08 2016 07:51:10	nzbToNzbDrone: ValueError: 'auto' is not in list
INFO	Wed Jun 08 2016 07:51:10	nzbToNzbDrone: fork = core.FORKS.items()[core.FORKS.keys().index(cfg.get("fork", "auto"))]
INFO	Wed Jun 08 2016 07:51:10	nzbToNzbDrone: File "/share/MD0_DATA/Download/nzbToMedia/core/nzbToMediaAutoFork.py", line 24, in autoFork
INFO	Wed Jun 08 2016 07:51:10	nzbToNzbDrone: fork, fork_params = autoFork(section, inputCategory)
INFO	Wed Jun 08 2016 07:51:10	nzbToNzbDrone: File "/share/MD0_DATA/Download/nzbToMedia/core/autoProcess/autoProcessTV.py", line 69, in processEpisode
INFO	Wed Jun 08 2016 07:51:10	nzbToNzbDrone: download_id, inputCategory, failureLink)
INFO	Wed Jun 08 2016 07:51:10	nzbToNzbDrone: File "/share/MD0_DATA/Download/nzbToMedia/nzbToMedia.py", line 605, in process
INFO	Wed Jun 08 2016 07:51:10	nzbToNzbDrone: failureLink=failureLink)
INFO	Wed Jun 08 2016 07:51:10	nzbToNzbDrone: File "/share/MD0_DATA/Download/nzbToMedia/nzbToMedia.py", line 705, in main
INFO	Wed Jun 08 2016 07:51:10	nzbToNzbDrone: result = nzbToMedia.main(sys.argv, section)
INFO	Wed Jun 08 2016 07:51:10	nzbToNzbDrone: File "/share/MD0_DATA/.qpkg/NZBGet/nzbget/scripts/nzbToMedia/nzbToNzbDrone.py", line 236, in <module>
INFO	Wed Jun 08 2016 07:51:10	nzbToNzbDrone: Traceback (most recent call last):
```

**Comment by clinton-hall** [comment]
@saxonthebeach 
Please try latest nightly / dev
@labrys 
I put back the try/except for the form parameter. Basically, if the fork parameter isn't a valid fork, it defaults to "auto"... I know this isn't pretty, so this needs to be reviewed.
I also put the quotes back around the param  e.g. `name="failed"` as this is the way this appears in the html response.

**Comment by labrys** [comment]
Yeah that was a regex change and shouldn't have been changed to a `repr`.  Might need to double check to make sure other's weren't changed erroneously.

**Comment by saxonthebeach** [comment]
That got it working again, thanks very much to you both.
