### ISSUE TITLE
[Request] IMDB runtime checking

### ISSUE THREAD

**Issue by nslee0** [clinton-hall/nzbToMedia#1065]
Given that nzbToMedia already checks media files with ffprobe, would it be possible to compare the runtime of a given movie to the listed runtime in IMDB in order to verify the movie CouchPotato snatched is in fact the correct one?

CP has a somewhat spotty record for me of grabbing similarly titled (but incorrect) movies from indexers. In addition, CP sometimes downloads files that are "Disk 1", or "Part 1" without downloading the other half, leading to broken movies in the library. If nzbToMedia was somehow able to check the runtime of snatched file against IMDB and make sure it's with x% (or within a few minutes) of the correct runtime, it seems like many of these errors would be averted.

Python has 3rd party libraries for querying IMDB such as [IMDbPy](http://imdbpy.sourceforge.net). Should be a simple lookup given that nzbToMedia already has the IMDB title of the movie it's processing.

**Comment by clinton-hall** [comment]
I like this idea... just need to find time to add this.
