### ISSUE TITLE
Unable To Migrate autoProcessMedia.cfg

### ISSUE THREAD

**Issue by brando56894** [clinton-hall/nzbToMedia#1069]
I know you have seen a lot of these in the past and I've tried a lot of the solutions but they don't seem to apply to me. I'm running Arch Linux in a KVM on my server that is used specifically for usenet apps (the KVM, not the server) and all was well up until I moved to a new apartment 2 weeks ago, when I reconnected everything NFS kept screwing up, which was in turn screwing up all my usenet stuff since the download and storage locations are shared out via NFS.

I finally got the whole (or most of!) the NFS mess straightened out but now post-processing refuses to work, even though it worked fine a few days ago and I don't really remember changing anything.

I'm currently using SABnzbd with nzbToMedia and CouchPotato, I switch to NZBget whenever SAB starts to act goofy and I don't feel like fixing it haha. Whenever SAB executes one of the nTM scripts I just get this error:

```
[root@usenet]: nzbToMedia># python2 nzbToCouchPotato.py
[00:14:06] [ERROR]::MAIN: Unable to migrate config file /opt/sabnzbd/scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...
```

It doesn't matter if I run it manually or SAB runs it, permissions are correct on everything (tried running as root just to be sure), I've delelted all of the autoProcessMedia.cfg files and it still happens. I even cloned a new repo in a completely different directory, copied in my cfg file and got the same error! I deleted the config file and downloaded a fresh one from the repo and didn't touch a thing and still got the error!

I have enabled all the debug settings in the logs and still only get that one line. Also I made sure that all my categories were matching between SAB/NZBget, CP and nTM but the error still persisted so I have no clue what the issue is.

**Comment by michaelarlt** [comment]
how you did edit the file? there might be invalid characters inside like linebreaks. Did you use vi or nano to edit or maybe some other editor which may includes invalid characters, python cannot parse?

**Comment by jonskoglund** [comment]
Having the same error here with sabnzbd 1.1.0 [8abcf08] and Python at version 2.7.11-15 on my Synology (DSM 6.0.2-8451 Update 2): 
`ERROR ::MAIN: Unable to migrate config file /volume1/shared/scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...`
`Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x2c0b84b8>> ignored`
Did a compare between autoProcessMedia.cfg and autoProcessMedia.cfg.spec to make sure I wasn't missing any setting. But didn't find any irregularities.
This issue has been posted (and solved) before. I have read all the post and tested every possible solution but to no avail. :-(

**Comment by clinton-hall** [comment]
This is usually either an issue with a character in the .cfg, or a permissions issue.
If you email me the .cfg I can test to see if it can be loaded at my end.
