### ISSUE TITLE
Episode is not renamed

### ISSUE THREAD

**Issue by sv2241** [clinton-hall/nzbToMedia#1070]
https://gist.github.com/sv2241/fb56d453730673363c12eb81ebe73213 https://gist.github.com/sv2241/849e890846b982406718d88a6ccfae22

Both filenames, S01E01 and S01E10 respectively, had different names than their folders but only one was renamed to the folder name. Why wasn't S05E01 renamed as well?

**Comment by clinton-hall** [comment]
In Both Cases SickGear just used the original file name...
so check your postprocess settings in SickGear to ensure the naming is set to `Season %S/%SN - S%0SE%0E - %EN - %QN` or similar.
