### ISSUE TITLE
CouchPotato Post-Processing Error Upon Discovering Corrupt Video

### ISSUE THREAD

**Issue by jsn0327** [clinton-hall/nzbToMedia#1085]
There have been quite a few spam videos posted lately, and ffprobe does it's job in scanning the video file and reporting that it is corrupt.  The problem is that after the video file is reported as corrupt, I receive an error stating, "[ERROR]::COUCHPOTATO: Could not find a downloaded movie in the database matching movie.nzb, exiting!".  I have searched github and found that other people have reported the same error, but their posts were over 2 years ago, and at the end of their threads, it appeared as though their issues were resolved through code modifications.  I have tried both the current Master branch, as well as the current nightly branch of nzbToMedia, and i receive the error with both.  I confirmed in the logs that nzbToMedia is updating properly and is current.  I also verified that my API key, IP Address, and Port are correct within autoProcessMedia.cfg.  I do have a few releases of the move marked as ignore, but I did that myself.  I'm not sure if this is a bug that only occurs when a movie has numerous releases marked as ignore or not, but that seems to be a common factor that I noticed in other posts of this issue.  

Clinton-hall I will e-mail my logs to you directly.  If anyone has any suggestions, please let me know.  Thanks!

**Comment by clinton-hall** [comment]
Sorry for this. I have been unavailble for a while.

I don't seem to see any email with logs??? are you able to re-send?

In general, this is likely due to nzbToMedia failing to identify the movie. In this case, trying to preserve the cp(ttxxxxx) tag in the download name, once passed from CouchPotato should ensure this is correctly identified.

**Comment by jsn0327** [comment]
Hi, thanks for the reply!  Below is the e-mail that I sent to you
previously.  I checked the pastebin links and they still work.  Thanks for
any help that you can provide and GREAT job on the applications that you
provide!

   -Jason

Good afternoon.  I recently posted a post-processing error that I am
receiving in SABnzbd when using nzbToMedia to post-process video files to
CouchPotato.  The issue is titled "CouchPotato Post-Processing Error Upon
Discovering Corrupt Video #1085" on Github.  I have posted the nzbToMedia
log output to pastebin, as well as the output of the api call to CouchPotatofor
the specific release; which you requested from another user with the same
issue that i'm having.  Would you please review this issue and let me know
how to fix it?  Thanks a lot for your help!

nzbToMedia Log via SABnzbd - http://pastebin.com/QALRCyra

Output of http://192.168.x.x:5050/api/c6aaa41249d7407a8c53302af0a635
51/media.get/?id='tt2241351 -http://pastebin.com/MnXiCRw9

**Comment by clinton-hall** [comment]
Very strange,


When we ask SABnzbd it tells us the download id is SABnzbd_nzo_Av6NaY


but in the output from the URL call it appears the "snatched" release is SABnzbd_nzo_pciSdF, and SABnzbd_nzo_Av6NaY does not appear in the list.


This leads me to believe that SABnzbd or CouchPotato are changing the IDs that were previously used to confirm the correct release is in use...


What version of SABnzbd are you using?


________________________________

**Comment by jsn0327** [comment]
SABnzbd version 1.0.0

-Jason
