### ISSUE TITLE
Transcoding: subtitle language not embedded correctly with ffmpeg

### ISSUE THREAD

**Issue by ladude626** [clinton-hall/nzbToMedia#1088]
I'm using the transcoding feature to automatically convert MKV -> MP4. I've turned on the subtitle grabbing feature and embedding into the MP4. However, I notice all foreign subtitles showing as english in Plex and in other applications. I believe the problem is when subtitles are downloaded, a 2 letter code for language (ISO 939-1) is used at the end of the file (ie movie.en.srt for english). This 2 letter code is then feed into ffmpeg. However, when I look at ffmpeg documentations, looks like 3 letter codes (ISO 939-2) should be used instead: https://ffmpeg.org/ffmpeg.html

Here's an example of the how nzbToMedia is executing ffmpeg using 2 letter codes. In this case, I'm trying to integrate an English and Vietnamese subtitle.

`nice -n19 ionice -c0 -n0 /ffmpeg/ffmpeg -loglevel warning -fflags +genpts -i /downloads/tv/True Detective S02E08 720p HDTV x264-0SEC/True Detective S02E08 720p HDTV x264-0SEC.mkv -i /downloads/tv/True Detective S02E08 720p HDTV x264-0SEC/True Detective S02E08 720p HDTV x264-0SEC.en.srt -i /downloads/tv/True Detective S02E08 720p HDTV x264-0SEC/True Detective S02E08 720p HDTV x264-0SEC.vi.srt -map 0:0 -map 0:1 -map 0:1 -map 0:2 -map 0:3 -map 1:0 -map 2:0 -c:v libx264 -c:a:0 aac -strict -2 -c:a:1 ac3 -c:s mov_text -metadata:s:s:2 language=en -metadata:s:s:3 language=vi /downloads/tv/True Detective S02E08 720p HDTV x264-0SEC/True Detective S02E08 720p HDTV x264-0SEC.mp4`

When I run the above code manually and replacing "en" with "eng" and "vi" with "vie", it works correctly.

Perhaps we need to convert 2 letter codes to 3 letter codes before feeding into ffmpeg. Here's some reference for ISO 639-1/2: https://www.loc.gov/standards/iso639-2/php/English_list.php

**Comment by clinton-hall** [comment]
https://github.com/clinton-hall/nzbToMedia/commit/e5a46f581d2cadab95af73bcc0888c20276a3bbd

Ok, I just added a "fix" for this now that doesn't write into the metadata unless we have a 3-character code (or 3 character '-' 2 character... e.g. `fre-ca`).
I will need time to look at converting 2 letter to 3 letter etc, so the current fix in nightly hopefully stops this causing errors.

**Comment by clinton-hall** [comment]
Please test in latest nightly build.

**Comment by ladude626** [comment]
This works correctly now. Here's the ffmpeg command that that's being produced:

nice -n6 ionice -c0 -n0 /usr/bin/ffmpeg -loglevel warning -fflags +genpts -i /mnt/downloads/movies/Return to Never Land (2002) 1080p.x264.mkv.cp(tt0280030)/Return to Never Land (2002) 1080p.x264.mkv -i /mnt/downloads/movies/Return to Never Land (2002) 1080p.x264.mkv.cp(tt0280030)/Return to Never Land (2002) 1080p.x264.aaaaaaa.srt -i /mnt/downloads/movies/Return to Never Land (2002) 1080p.x264.mkv.cp(tt0280030)/Return to Never Land (2002) 1080p.x264.en.srt -map 0:2 -map 0:3 -map 0:3 -map 1:0 -map 2:0 -c:v copy -c:a:0 aac -strict -2 -ac:a:0 2 -b:a:0 160000 -c:a:1 copy -c:s mov_text -metadata:s:s:1 language=eng -movflags +faststart /mnt/downloads/movies/Return to Never Land (2002) 1080p.x264.mkv.cp(tt0280030)/Return to Never Land (2002) 1080p.x264.mp4
