### ISSUE TITLE
Custom Transcoding Profile

### ISSUE THREAD

**Issue by ptowns188** [clinton-hall/nzbToMedia#1089]
Hi, first of all let me say that when using one of your pre built in transcoding profiles everything works perfectly.

Sonarr >> Deluge >> NzbToMedia >> Sonarr

When I try to use my own settings however Deluge calls the script (I get a log file, but no info inside to help me) and nothing happens.

My cfg settings: http://pastebin.com/Q4UjDVSQ

My log file: http://pastebin.com/NaU5du8f

Can you see what i am doing wrong

Thanks

PS. Is there a way to edit your built in profiles?

**Comment by ptowns188** [comment]
Ok, i have now got it set as the following but with these settings the video and audio gets transcoded and not stream copied. the video file i am importing is an x264/aac.mkv (audio has 2 channels)

    #### Define custom settings below.
    outputVideoExtension = .mp4
    outputVideoCodec = libx264
    VideoCodecAllow = "libx264,h264"
    outputVideoPreset = medium
    outputVideoResolution = ""
    outputVideoFramerate = ""
    outputVideoBitrate = ""
    outputVideoCRF = 19
    outputVideoLevel = 3.1
    outputAudioCodec = aac
    AudioCodecAllow = libfdk_aac
    outputAudioChannels = 3.1
    outputAudioBitrate = 128k
    outputAudioTrack2Codec = ""
    AudioCodec2Allow = ""
    outputAudioTrack2Channels = ""
    outputAudioTrack2Bitrate = ""
    outputAudioOtherCodec = ""
    AudioOtherCodecAllow = ""
    outputAudioOtherChannels = ""
    outputAudioOtherBitrate = ""
    outputSubtitleCodec = mov_text

**Comment by clinton-hall** [comment]
I believe you need
```
VideoCodecAllow = libx264,h264,h.264
outputAudioBitrate = ""
```
