### ISSUE TITLE
No module named cookielib

### ISSUE THREAD

**Issue by homerjsim** [clinton-hall/nzbToMedia#1090]
Hello,

I installed your scripts on my QNAP and I get the message, that there is no module named cookielib. I have [QPython2 ] [ 2.7.11.0.1 ] Python 2 + modules from https://forum.qnap.com/viewtopic.php?f=217&t=109899&start=120 installed. Everything should be there but it does not work.
Any ideas?

error   Mon Aug 08 2016 23:32:41    Post-process-script nzbToNzbDrone.py for Ballers.2015.S02E04.720p.HDTV.x264-KILLERS failed (terminated with unknown status)
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: ImportError: No module named cookielib
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: import cookielib
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: File "/share/MD0_DATA/.qpkg/QNZBGet/bin/scripts/libs/requests/compat.py", line 39, in <module>
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: from .compat import parse_http_list as _parse_list_header
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: File "/share/MD0_DATA/.qpkg/QNZBGet/bin/scripts/libs/requests/utils.py", line 26, in <module>
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: from . import utils
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: File "/share/MD0_DATA/.qpkg/QNZBGet/bin/scripts/libs/requests/__init__.py", line 58, in <module>
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: import requests
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: File "/share/MD0_DATA/.qpkg/QNZBGet/bin/scripts/core/autoProcess/autoProcessComics.py", line 4, in <module>
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: from core.autoProcess.autoProcessComics import autoProcessComics
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: File "/share/MD0_DATA/.qpkg/QNZBGet/bin/scripts/core/**init**.py", line 28, in <module>
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: import core
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: File "/share/MD0_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia.py", line 503, in <module>
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: import nzbToMedia
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: File "/share/MD0_DATA/.qpkg/QNZBGet/bin/scripts/nzbToNzbDrone.py", line 233, in <module>
info    Mon Aug 08 2016 23:32:41    nzbToNzbDrone: Traceback (most recent call last):
warning Mon Aug 08 2016 23:32:41    nzbToNzbDrone: Fixing permissions for/share/MD0_DATA/.qpkg/QNZBGet/bin/scripts/nzbToNzbDrone.py
info    Mon Aug 08 2016 23:32:41    Executing post-process-script nzbToNzbDrone.py for Ballers.2015.S02E04.720p.HDTV.x264-KILLERS

**Comment by Apulo** [comment]
I'm having the same issue. I can start Python from the command line and import cookielib without error but the script fails with "nzbToCouchPotato: ImportError: No module named cookielib"

**Comment by clinton-hall** [comment]
you will need to find out which phyton is being called by nzbToMedia.
When you run python manually you use a version that has the correct libs, but when the script is called from SABnzbd/NZBGet it appears the PATH variable is causing this to open another version of Python.
I modified the start scripts for those apps some time agai to auto-choose the most RECENT version of Python, but obviously you have a newer version of Python installed that is missing these libs...

**Comment by neothematrix** [comment]
I have the same issue, but I think it's not related to nzbtomedia, it started after I installed QNZBget from the community repository instead of the "NZBget" from the qnap official repository, since I needed a more updated version.
The problem goes away by manually restarting QNzbget after the QNap is on, if QNZBget starts on boot with the QNap, then you get this error. I think it has to do with the fact that on boot qnzbget starts before the python installed from the repository is ready to be used but I have to go deeper into this.

**Comment by clinton-hall** [comment]
QNZBget is more up to date?
NZBGet app allows you to update within the app. It uses the binaries compiled by NZBGet.

**Comment by neothematrix** [comment]
uhmmm sorry I don't remember where I got the old NZBGet package (15.x), I thought from the official QNap repository but it's not there, I must had taken it from somewhere else, and that particular version didn't have the update withing the app option enabled. That's why I installed the QNZbget package from the "QNapclub.eu" repository, that has version 17.x and update within the app enabled.

**Comment by neothematrix** [comment]
ok found the issue, when QNZBget is started at boot or from the web interface, the PATH variable is missing a few paths.
The default interpreter of nzbToMedia.py script is "#!/usr/bin/env python2" that with the PATH defined on boot points to a python2.7.5 installation that is missing the cookielib and probably every other modules. It's probably the QNap default python version.
When started manually from the command line, then python2 resolves to "/opt/bin/python2" which is the one installed by Entware, and it's version 2.7.11 with all the modules.

So it's not nzbtomedia issue, more likely it's QNzbget startup script issue.
However, had nzbtomedia.py used "#!/usr/bin/env python2.7" interpreter, then the issue wouldn't be present.

**Comment by clinton-hall** [comment]
You can switch to the "OSX" branch that does use python2.7 interpreter.

Also, my (update supported) version of NZBGet is here https://forum.qnap.com/viewtopic.php?f=141&t=70719
