### ISSUE TITLE
NoneType object is not callable

### ISSUE THREAD

**Issue by jiska78** [clinton-hall/nzbToMedia#1093]
I've downloaded and installed nzbToMedia fresh from the website and put in the SABnzbd settings, but I get this error (clicking "More" does nothing).

Any ideas?

Exit(1) Exception TypeError: "'NoneType' object is not callable" in (More)

**Comment by whvanderpost** [comment]
Are you on trying to get it working on a NAS?
Could be that you should set the owner of the script files to the user under which SABnzbd runs. SSH into your NAS and use (full path without the [ ] of course):
`chown -R sabnzbd:users [full path to the folder that contains the nzbToMedia scripts]`

**Comment by clinton-hall** [comment]
Clicking more in SABnzbd should give the traceback. 
Otherwise, SABnzbd logs should give more info... find the SABnzbd log from the time of the failure and post the details here.

**Comment by whvanderpost** [comment]
I've also had this issue, you can't click "more" in SABnzbd, it's not a link when this happens.
In my case the logs didn't show anything more than the single exception line (no exception details or whatsoever).

**Comment by clinton-hall** [comment]
From sabnzbd site...

The console output of the script is captured by SABnzbd and is saved in the so called "Script Log" which can be opened from the history details. The output will be added to the (optional) notification email and can be examined in the History page.

So on the history page, there must be an option to expand/view the output. From memory, and I don't have a system to test right now, it isn't linked through "more" but there is an option to expand/view... Just click around the place where the error is displayed.
