### ISSUE TITLE
New obfuscating?

### ISSUE THREAD

**Issue by jkoopmann** [clinton-hall/nzbToMedia#1101]
Hi,

likely a very old thing but I just saw it the first time. After PAR/UNRAR I find a structure much as this:

28.06.2016.1
28.06.2016.2
28.06.2016.3
28.06.2016.4
28.06.2016.5
4ever.html
Click.rar
MUST_READ.txt
Thats_the_Board.nfo
UnRAR.exe
What.rar
a_Linux_2rename.sh
win_click2rename.bat

basically the numbered files are the video files (unencrypted). what.rar is encrypted (with the passwords being in the bat or sh files). So a_Linux_2rename.sh decrypts/unrars What.rar. The result is a What.sh file which only contains mkdir and mv commands to convert the numbered files in correct movie names, subtitles etc.

Looks as if this is not handled by nzbToMedia. I thought this was a one time thing but it happened to me 10 times today... Maybe worth implementing?

Regards,
   JP

**Comment by jkoopmann** [comment]
Ok looks like this is extremely old and covered for months. Strange enough it did not work here but maybe this was something different... Will keep looking and in case this turns out to be other issues close the ticket.

**Comment by jkoopmann** [comment]
I can mail/pastebin an example. Would not want to attach the real filenames here. :-) Looks as if the enhanced mechanism does not work with the scheme above. Example:

2016-09-11 16:54:17 DEBUG   ::EXCEPTION: Replacing file name What with download name XYZ.nzb

**Comment by clinton-hall** [comment]
Ok... The script does support rename script parsing.... but I'll need to check that the exception renaming isn't done first... Also, this may not match the current check for rename.sh....
