### ISSUE TITLE
Post processing Failed/Empty log file

### ISSUE THREAD

**Issue by carleycr** [clinton-hall/nzbToMedia#1107]
I have FreeNAS 9.10.1. Script is running as I have a log file being created and the PID file, but the log file is empty. The downloads do not go to their respective directories.

**Comment by clinton-hall** [comment]
can you run the script manually?

**Comment by carleycr** [comment]
I'm not sure how to do this. I've attached a screenshot of what scripts I have in my jail and their location.
![jail scripts](https://cloud.githubusercontent.com/assets/11008793/18819920/4ce4c4a4-835e-11e6-84bb-0ac086afb8a5.png)

**Comment by clinton-hall** [comment]
via ssh

```
/usr/local/share/nzbToMedia/nzbToMedia.py
```
