### ISSUE TITLE
Books support - copy once only to an output folder

### ISSUE THREAD

**Issue by KaraokeStu** [clinton-hall/nzbToMedia#1110]
Hi,

I have Calibre setup to auto-import books loaded into a certain directory, which deletes the source file.

Is it possible to have a user script or something setup to copy the file once only into that import folder on completion?

**Comment by clinton-hall** [comment]
if you are using a Torrent Downloader, in autoProcessMedia.cfg
```
[UserScript]
    #Use user_script for uncategorized downloads
    #Set the categories to use external script.
    #Use "UNCAT" to process non-category downloads, and "ALL" for all defined categories.
    [[Books]]
        #Enable/Disable this subsection category
        enabled = 1
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
```
Where [[Books]] is the category used for Calibre downloads.

This will therefore link, copy, move files as per your Torrent settings.

I am assuming this is for torrents, as for NZB I can't see why deleting source would be any issue.
