### ISSUE TITLE
[Question] Remove leftovers that CP leaves behind?

### ISSUE THREAD

**Issue by schumi2004** [clinton-hall/nzbToMedia#1111]
I got some issues with CP leaving *.idx files in place and therefore is unable to remove directory.
Is this something nzbtomedia can resolve for CP?

https://github.com/CouchPotato/CouchPotatoServer/issues/6846

**Comment by clinton-hall** [comment]
Yes, nzbToMedia can clean these up.

autoProcessMedia.cfg
```
[General]
    force_clean = 1
```

**Comment by schumi2004** [comment]
Mmmm strange, it seems it was already enabled. Will do some debugging and open new ticket if needed.
