### ISSUE TITLE
[INFO]::MAIN: Unable to locate download info for...

### ISSUE THREAD

**Issue by billbo01028** [clinton-hall/nzbToMedia#1112]
please help.  I am stuck trying to figure out why this is broken after working for at least 6 months.  please find the attached logfile
[log.txt](https://github.com/clinton-hall/nzbToMedia/files/520980/log.txt)

**Comment by clinton-hall** [comment]
Try again and see if this fixes it.

**Comment by billbo01028** [comment]
no go still.... here is the top part of the log (it's still going through the rest of the files)
[nzbToMediaLog.txt](https://github.com/clinton-hall/nzbToMedia/files/523265/nzbToMediaLog.txt)

**Comment by clinton-hall** [comment]
Looks to be working ok. What is happening here is that it is asking CP to rename the movies, but there is no status change reported by CouchPotato (presumably because these movies have already been renamed previously?).

What do CP logs show during this time?

**Comment by billbo01028** [comment]
I am attaching the head portion of the CP logs and the NZBtoCouchpotato logs to this response.  I started a new NZBtoCouchpotato at 19:47 local time.  I looked them over briefly, but, can't see a smoking gun.  the script is still running, otherwise I would give you the entire log to review from both Couchpotato and NZBtoCouchpotato.  Thank you for any advice you may be able to provide.  I am getting tired, so I am heading to bed, but thank you again for any assistance
[HeadOfCPLogs.txt](https://github.com/clinton-hall/nzbToMedia/files/535061/HeadOfCPLogs.txt)
[HeadOfNzbToCPLogs.txt](https://github.com/clinton-hall/nzbToMedia/files/535062/HeadOfNzbToCPLogs.txt)

 you may be able to provide.

**Comment by clinton-hall** [comment]
Ok.. this is a CP issue
`Renamer is already running, if you see this often, check the logs above for errors.`
so you need to restart couchpotato, clear the logs, then run nzbToMedia.
check CP logs... if this error shows up again we need to look at the logs prior to the first time this appears to figure out why the renamer is hanging.

**Comment by billbo01028** [comment]
I am going to start from scratch.  I am deleting all my completed downloads (now at 100 movies) and see if I can get a fresh set of logs up for this weekend.  Thank you for you patience, and I should have something to look at soon.

**Comment by billbo01028** [comment]
Thank you!!!!!  it works now :)
