### ISSUE TITLE
Unable to connect to git

### ISSUE THREAD

**Issue by Th3MadHatter** [clinton-hall/nzbToMedia#1117]
I just noticed I was using an ancient version from 3 years ago so I manually updated since the auto update didn't work but after manually updating it still fails.

here are is the log

> 2016-10-24 01:32:01 INFO    ::MAIN: Loading config from [C:\nzbToMedia\autoProcessMedia.cfg]
> 2016-10-24 01:32:01 INFO    ::MAIN: Checking database structure...
> 2016-10-24 01:32:06 INFO    ::MAIN: Checking if git needs an update
> 2016-10-24 01:32:15 ERROR   ::MAIN: Unable to contact github, can't check for update
> 2016-10-24 01:32:15 INFO    ::MAIN: No update needed
> 2016-10-24 01:32:15 INFO    ::MAIN: nzbToMedia Version:77da142216ba6dc91bb654635d4bd03f13c881e5 Branch:master (Windows 7)
> 2016-10-24 01:32:17 ERROR   ::MAIN: Failed to connect to uTorrent
> 2016-10-24 01:32:17 INFO    ::MAIN: #########################################################
> 2016-10-24 01:32:17 INFO    ::MAIN: ## ..::[TorrentToMedia.py]::.. ##
> 2016-10-24 01:32:17 INFO    ::MAIN: #########################################################`

and here are my general settings

> 
> # nzbToMedia Configuration
> # For more information, visit https://github.com/clinton-hall/nzbToMedia/wiki
> 
> [General]
>     # Enable/Disable update notifications
>     version_notify = 1
>     # Enable/Disable automatic updates
>     auto_update = 1
>     # Set to the full path to the git executable
>     git_path = C:\Program Files (x86)\Git\bin\git.exe
>     # GitHUB user for repo
>     git_user = ""
>     # GitHUB branch for repo
>     git_branch = ""
>     # Enable/Disable forceful cleaning of leftover files following postprocess 
>     force_clean = 0
>     # Enable/Disable logging debug messages to nzbtomedia.log
>     log_debug = 0
>     # Enable/Disable logging database messages to nzbtomedia.log
>     log_db = 0
>     # Enable/Disable logging environment variables to debug nzbtomedia.log (helpful to track down errors calling external tools.)
>     log_env = 0
>     # Enable/Disable logging git output to debug nzbtomedia.log (helpful to track down update failures.)
>     log_git = 0
>     # Set to the directory where your ffmpeg/ffprobe executables are located
>     ffmpeg_path = C:\ffmpeg\bin\
>     # Enable/Disable media file checking using ffprobe.
>     check_media = 1
>     # Enable/Disable a safety check to ensure we don't process all downloads in the default_downloadDirectories by mistake.
>     safe_mode = 1

I noticed that I had a git folder of 3 GB after a few years of use so something is going wrong.

**Comment by clinton-hall** [comment]
Was this installed via git clone, or did you download the .zip?
Can you use cmd, navigate to the nzbToMedia Directory, then issue a git pull?

**Comment by Th3MadHatter** [comment]
It was a zip download and its still pretty fresh with the exception of the cfg file.
If I git pull it errors out as well.

> error: refs/heads/master does not point to a valid object!
> error: refs/remotes/origin/HEAD does not point to a valid object!
> error: refs/remotes/origin/dev does not point to a valid object!
> error: refs/remotes/origin/master does not point to a valid object!
> error: refs/heads/master does not point to a valid object!
> error: refs/remotes/origin/HEAD does not point to a valid object!
> error: refs/remotes/origin/dev does not point to a valid object!
> error: refs/remotes/origin/master does not point to a valid object!
> error: refs/heads/master does not point to a valid object!
> error: refs/remotes/origin/HEAD does not point to a valid object!
> error: refs/remotes/origin/dev does not point to a valid object!
> error: refs/remotes/origin/master does not point to a valid object!
> error: refs/heads/master does not point to a valid object!
> error: refs/remotes/origin/HEAD does not point to a valid object!
> error: refs/remotes/origin/dev does not point to a valid object!
> error: refs/remotes/origin/master does not point to a valid object!
> error: Could not read 617bf378787fad05691d3e214cc870aed4d1021f
> remote: Counting objects: 1852, done.
> remote: Compressing objects: 100% (47/47), done.
> remote: Total 1852 (delta 685), reused 658 (delta 658), pack-reused 1147
> Receiving objects: 100% (1852/1852), 1.84 MiB | 1.70 MiB/s, done.
> Resolving deltas:  49% (509/1023), completed with 24 local objects.
> fatal: pack has 514 unresolved deltas
> fatal: index-pack failed
>

**Comment by clinton-hall** [comment]
Auto update is not supported for the zip downlaod.

If you want this to work you need to do a git clone of the repo..

`git clone https://github.com/clinton-hall/nzbToMedia.git`

**Comment by Th3MadHatter** [comment]
That seems to do the trick, thanks :)
