### ISSUE TITLE
Feature Request: Transcoder - options for failed transcoding

### ISSUE THREAD

**Issue by natoriousbigg** [clinton-hall/nzbToMedia#1119]
Would nice to have an option for medias that download correctly but fails during transcoding due to various reasons. Here are some examples of options:

1) marked as failed and send to CouchPotato/SickBeard as failed (and delete if needed)
2) exit script and leave media as is
3) continue to postprocess original media

Thanks!

**Comment by clinton-hall** [comment]
fair call.. I'll try and action this
