### ISSUE TITLE
nzbToSickbeard - server did not respond

### ISSUE THREAD

**Issue by gmikulski** [clinton-hall/nzbToMedia#1121]
Hi,

I have some issue to connect from NZBGet to Sickrage. My setup is:
a) NZBGet 16.4 running on WDMYCLOUD linux (IP **192.168.0.18**)
b) SickRage running on Windows 10 (IP **192.168.0.17:7081**)
c) CouchPotato running on Windows 10 (IP **192.168.0.17:5050**)

In NZBGet I managed to successfully run nzbToCouchpotato, so I reckon my network / firewall is not an issue. But in this case I also supply the API code of couchpotato.

I cannot however communicate well with SickRage. Here is the log:
[http://pastebin.com/xRidiVm7](http://pastebin.com/xRidiVm7)

Can someone help / advise?

Thanks!

These are my settings:
**[CouchPotato]**
    #### autoProcessing for Movies
    #### movie - category that gets called for post-processing with CPS
    [[Movies]]
        enabled = 1
        apikey = ****************************
        host = 192.168.0.17
        port = 5050
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        ssl = 0
        web_root = ""
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        method = renamer
        delete_failed = 0
        wait_for = 2
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if Couchpotato is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

**[SickBeard]**
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[Series]]
        enabled = 1
        host = 192.168.0.17
        port = 7081
        username = test
        password = test
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        process_method = ""
        # force processing of already processed content when running a manual scan.
        force = 0
        # tell SickRage to delete all source files after processing.
        delete_on = 0
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

**Comment by clinton-hall** [comment]
can you please test with the latest version of nightly branch? I added more logging to try and capture this.

Also please ensure you have 
```
[General]
    log_debug = 1
```

**Comment by gmikulski** [comment]
I did try the nightly and it gave me a hint... Problem was with Windows Firewall - it was blocking incoming traffic to Sickrage from outside localhost.

Solution for anyone who is looking is to add C:\Program Files (x86)\SickRage\Python\python.exe on allowed apps.

Sorry Clinton that I wasted your time, but I was looking in wrong places for over half a day... :)

**Comment by clinton-hall** [comment]
no worries... wasn't wasting my time.
Glad you have it resolved and thanks for posting your solution.
