### ISSUE TITLE
nzbtomedia error after automatic update

### ISSUE THREAD

**Issue by mikkihugo** [clinton-hall/nzbToMedia#1123]
I get this on qnap after automatic update

/share/nzbToMedia] # /opt/QCouchPotato/bin/python nzbToMedia.py                                               
Traceback (most recent call last):
  File "nzbToMedia.py", line 514, in <module>
    import core
  File "/share/CACHEDEV1_DATA/nzbToMedia/core/__init__.py", line 35, in <module>
    from core.autoProcess.autoProcessComics import autoProcessComics
  File "/share/CACHEDEV1_DATA/nzbToMedia/core/autoProcess/autoProcessComics.py", line 7, in <module>
    from core.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
  File "/share/CACHEDEV1_DATA/nzbToMedia/core/nzbToMediaUtil.py", line 19, in <module>
    import subliminal
  File "/share/CACHEDEV1_DATA/nzbToMedia/libs/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/share/CACHEDEV1_DATA/nzbToMedia/libs/subliminal/core.py", line 3, in <module>
    from concurrent.futures import ThreadPoolExecutor
  File "/share/CACHEDEV1_DATA/nzbToMedia/libs/concurrent/futures/__init__.py", line 17, in <module>
    from concurrent.futures.process import ProcessPoolExecutor
  File "/share/CACHEDEV1_DATA/nzbToMedia/libs/concurrent/futures/process.py", line 48, in <module>
    import multiprocessing
  File "/opt/QCouchPotato/lib/python2.7/multiprocessing/__init__.py", line 65, in <module>
    from multiprocessing.util import SUBDEBUG, SUBWARNING
  File "/opt/QCouchPotato/lib/python2.7/multiprocessing/util.py", line 41, in <module>
    from subprocess import _args_from_interpreter_flags
ImportError: cannot import name _args_from_interpreter_flags

Any clue?

**Comment by raymatos** [comment]
Also getting some errors from the auto update

**Comment by clinton-hall** [comment]
It appears there is a problem with this python install. 
`ImportError: cannot import name _args_from_interpreter_flags`

Can you test this running a different python install?

**Comment by mikkihugo** [comment]
Yes but they miss different libraries since its qnap. The point was this seemed to work fine with this until we updated.

**Comment by clinton-hall** [comment]
Agreed... The update was actually updating an external lib
`subliminal/core.py`

I see issues in sourceforge which suggests this is a circular reference issue...

Can you please show the output of the following command (run as admin)
`find / -name 'subprocess.py'`

IF that gives too many, try
`find /opt/QCouchPotato -name 'subprocess.py'`

**Comment by mikkihugo** [comment]
[/opt] # find / -name 'subprocess.py'                
/share/CACHEDEV1_DATA/.qpkg/Glacier/python/lib/python2.7/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/CloudLink/python/lib/python2.7/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/matplotlib/compat/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/gevent/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/trollius/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/future/moves/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/Qffmpeg/lib/python2.7/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/QCouchPotato/lib/python2.7/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/PlexPy/lib/python2.7/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/NZBHydra/nzbhydra-master/libs/future/moves/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/NZBHydra/nzbhydra-master/libs/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/NZBHydra/lib/python2.7/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/QPython3/lib/python3.4/site-packages/gevent/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/QPython3/lib/python3.4/site-packages/future/moves/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/QPython3/lib/python3.4/asyncio/subprocess.py
/share/CACHEDEV1_DATA/.qpkg/QPython3/lib/python3.4/subprocess.py

**Comment by clinton-hall** [comment]
What you can try is backing up/renaming `/share/CACHEDEV1_DATA/.qpkg/QCouchPotato/lib/python2.7/subprocess.py`
and then replacing this with 
`/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/subprocess.py`

Then test and see if that fixes the issue...
It does not look like there is any circular reference here, it just appears that this subprocess.py is missing _args_from_interpreter_flags

for me this starts at line 513
```
# XXX This function is only used by multiprocessing and the test suite,
# but it's here so that it can be imported when Python is compiled without
# threads.

def _args_from_interpreter_flags():
    """Return a list of command-line arguments reproducing the current
    settings in sys.flags and sys.warnoptions."""
    flag_opt_map = {
        'debug': 'd',
        # 'inspect': 'i',
        # 'interactive': 'i',
        'optimize': 'O',
        'dont_write_bytecode': 'B',
        'no_user_site': 's',
        'no_site': 'S',
        'ignore_environment': 'E',
        'verbose': 'v',
        'bytes_warning': 'b',
        'hash_randomization': 'R',
        'py3k_warning': '3',
    }
    args = []
    for flag, opt in flag_opt_map.items():
        v = getattr(sys.flags, flag)
        if v > 0:
            args.append('-' + opt * v)
    for opt in sys.warnoptions:
        args.append('-W' + opt)
    return args
```

**Comment by mikkihugo** [comment]
That solved the issue :) Thank you so much!

**Comment by clinton-hall** [comment]
Glad to hear... just hold on to that backup file just in case something else was relying on the modified file...
