### ISSUE TITLE
SyntaxError: from __future__ imports must occur at the beginning of the file

### ISSUE THREAD

**Issue by cyl0n** [clinton-hall/nzbToMedia#1124]
Moving from SickBeard to SickRage with SABnzbd...
I have followed the instructions in the Wiki but keep getting this error in SABnzbd:
`Traceback (most recent call last):
  File "/media/sdt1/username/sab3_data/scripts/nzbToSickBeard.py", line 251, in <module>
    import nzbToMedia
  File "/media/sdt1/usernam/sab3_data/scripts/nzbToMedia.py", line 507
    from __future__ import print_function
SyntaxError: from __future__ imports must occur at the beginning of the file`

**Comment by clinton-hall** [comment]
Have you edited on un-commented the top section of the nzbToMedia.py file?
How did you install the script? via git?

Basically, this error looks like the script has been edited or changed.

**Comment by cyl0n** [comment]
Thankyou! I was editing the incorrect file. Working now, I fell very silly.

**Comment by clinton-hall** [comment]
no worries. Glad it is working now.
