### ISSUE TITLE
NZBGet + nzbtomedia: unrar inifinite loop after failed extraction by NZBGet

### ISSUE THREAD

**Issue by ladude626** [clinton-hall/nzbToMedia#1131]
I'm running the nightly version update 2 days ago.

I have this strange issue. After NZBGet downloads a file fine, it can't seem to extract the rar file due to possibly corrupted rar file. The status was set as "FAILURE/UNPACK" before sedding to CouchPotato. nzbtomedia then tries to extract these also but seem to extracting in a loop for 3 hours straight. Please see log:

http://pastebin.com/WcmBTeAS

**Comment by clinton-hall** [comment]
It looks like it is trying to extract every .rar in an attempt to recover any media.
When it does successfully extract, it doesn't try and extract the rest... but when it fails on one it continues for every part...
It will "eventually" stop trying... I'll try and look at the code to see if I can make this smarter.
For now, I have recently added the option `no_extract_failed`

**Comment by ladude626** [comment]
Actually I'm using `no_extract_failed=1`. The files appears to download correctly but fails on extract by NZBGet, which then gives the status "FAILURE/UNPACK".

**Comment by clinton-hall** [comment]
But that's the thing... `FAILURE/UNPACK` is considered `failed` in nzbToMedia. as such this should ignore extraction if `no_extract_failed` is set...

**Comment by ladude626** [comment]
So it's a bug and extraction shouldn't be attempted if `no_extract_failed=1` is set? Hopefully it can be a quickfix to prevent extraction.

**Comment by ladude626** [comment]
I'm sorry! I thought I had updated my config but guess forgot to save it. Above error occurred with `no_extract_failed=0`. So only issue just long time it takes to attempt to unrar failed downloads.

**Comment by ladude626** [comment]
Looks like there's another bug. I save the config file with `no_extract_failed = 1` but everything it runs, it's overwritten to `no_extract_failed = 0`.

**Comment by ladude626** [comment]
Sorry seem to be an issue on my end again. At first NZBGet didn't load no_extract_failed option after I updated nzbtomedia. I guess it eventually loaded it into NZBGet and was set `no_extract_failed = 0` without my knowledge. I think this was overriding the config file.

**Comment by clinton-hall** [comment]
All good. With NZBGet when a new option is introduced in the script, you need to update the script, then set the option, save the changes and reload NZBGet.

**Comment by ladude626** [comment]
Ok. So I'm using nzbtomedia with SABnzbd again. I've confirmed that 'no_extract_failed = 0' is set, and 'extract = 1' for CouchPotato in the config. This downloads fails on verification and on extraction with exit code 3 but nzbtomedia is still trying to extract the corrupted rar files: http://pastebin.com/bbKcz7Y8

**Comment by clinton-hall** [comment]
AH... SABnzbd sends this as `3` and I only check for `1`!!

I'll change this shortly...

**Comment by ladude626** [comment]
Great, let me test it out.

**Comment by ladude626** [comment]
Still seem to be trying to exact here with error code 2:

http://pastebin.com/vgikx2cR

**Comment by clinton-hall** [comment]
Did you definately update to the latest nightly? I note this says
`Version checking is disabled, not checking for the newest version`
So you would need to manually update.
Basically any code from SAB > 0 should not be extracting if no_extract_failed = 1

**Comment by ladude626** [comment]
Ok, pulled he latest nightly and still getting error:

http://pastebin.com/LRHKDL4V
