### ISSUE TITLE
Not notifying CP

### ISSUE THREAD

**Issue by whatupcraig** [clinton-hall/nzbToMedia#1139]
I have an issue with nzbtomedia not notifying cp. I have all the info typed in but after the download in sabnzbd and running the script it does not notify cp. When I say notify I am assuming that it will notify cp that a particular movie was downloaded and cp should rename and move that file. 

Fair warning I know very little when it comes to coding. I am sure I didn't do soemthing right in the setup. Below is my info I typed in. 

## CouchPotato

# CouchPotato script category.
#
# category that gets called for post-processing with CouchPotatoServer.
#cpsCategory=couchpotato

# CouchPotato api key.
#cpsapikey= took this out for obvious reasons but I copy and pasted it directly from CP

# CouchPotato host.
#
# The ipaddress for your CouchPotato server. e.g For the Same system use localhost or 127.0.0.1
#cpshost=localhost

# CouchPotato port.
#cpsport=5050

# CouchPotato uses ssl (0, 1).
#
# Set to 1 if using ssl, else set to 0.
#cpsssl=0

# CouchPotato URL_Base
#
# set this if using a reverse proxy.
#cpsweb_root=

# CouchPotato Postprocess Method (renamer, manage).
#
# use "renamer" for CPS renamer (default) or "manage" to call a manage update.
#cpsmethod=renamer

# CouchPotato Delete Failed Downloads (0, 1).
#
# set to 1 to delete failed, or 0 to leave files in place.
#cpsdelete_failed=1

# CouchPotato wait_for
#
# Set the number of minutes to wait after calling the renamer, to check the movie has changed status.
#cpswait_for=1

# Couchpotato and NZBGet are a different system (0, 1).
#
# Enable to replace local path with the path as per the mountPoints below.
#cpsremote_path=0

any help is greatly appreciated

**Comment by clinton-hall** [comment]
Please copt autoProcessMedia.cfg.spec to autoProcessMedia.cfg

Then edit this file and put all of the details into the section
```
[CouchPotato]
    [[couchpotato]]
```
also, you should not edit any of the .py files... please fix this by navigating to the nzbToMedia folder and then `git reset --hard`

**Comment by whatupcraig** [comment]
Sorry for the delayed response. So I redownloaded everything and edited just the autoProcessMedia.cfg file. I am not sure if it is notifying cp or not. I am getting this error message in sab after it runs the script.

raceback (most recent call last):
  File "C:\PlexStuff\Scripts\nzbToMedia\nzbToMedia.py", line 520, in <module>
    import core
  File "C:\PlexStuff\Scripts\nzbToMedia\core\__init__.py", line 35, in <module>
    from core.autoProcess.autoProcessComics import autoProcessComics
  File "C:\PlexStuff\Scripts\nzbToMedia\core\autoProcess\autoProcessComics.py", line 7, in <module>
    from core.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
  File "C:\PlexStuff\Scripts\nzbToMedia\core\nzbToMediaUtil.py", line 14, in <module>
    import guessit
  File "C:\PlexStuff\Scripts\nzbToMedia\libs\guessit\__init__.py", line 6, in <module>
    from .api import guessit, GuessItApi
  File "C:\PlexStuff\Scripts\nzbToMedia\libs\guessit\api.py", line 17, in <module>
    from .rules import rebulk_builder
  File "C:\PlexStuff\Scripts\nzbToMedia\libs\guessit\rules\__init__.py", line 11, in <module>
    from .properties.episodes import episodes
  File "C:\PlexStuff\Scripts\nzbToMedia\libs\guessit\rules\properties\episodes.py", line 14, in <module>
    from .title import TitleFromPosition
  File "C:\PlexStuff\Scripts\nzbToMedia\libs\guessit\rules\properties\title.py", line 14, in <module>
    from .language import SubtitlePrefixLanguageRule, SubtitleSuffixLanguageRule, SubtitleExtensionRule
  File "C:\PlexStuff\Scripts\nzbToMedia\libs\guessit\rules\properties\language.py", line 9, in <module>
    import babelfish
  File "C:\PlexStuff\Scripts\nzbToMedia\libs\babelfish\__init__.py", line 20, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "C:\PlexStuff\Scripts\nzbToMedia\libs\babelfish\converters\__init__.py", line 6, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
  File "C:\PlexStuff\Scripts\nzbToMedia\libs\pkg_resources.py", line 29
    def _bypass_ensure_directory(name, mode=0777):
                                               ^
SyntaxError: invalid token

Also I am trying to re-encode each file as it is downloaded to cosnerve space however it does not seem to be encoding the files with ffmpeg. I have ffmpeg isntalled and seems to be functioning but the file sizes are coming out the same as when I download them.

**Comment by clinton-hall** [comment]
What version of Python did you install? this needs to be 2.7.X

**Comment by whatupcraig** [comment]
So I had 3.5.x installed. I donwloaded 2.7.x and now get this error after sab downloads the file. 

Traceback (most recent call last):
  File "C:\PlexStuff\Scripts\nzbToMedia\nzbToMedia.py", line 520, in <module>
    import core
  File "C:\PlexStuff\Scripts\nzbToMedia\core\__init__.py", line 35, in <module>
    from core.autoProcess.autoProcessComics import autoProcessComics
  File "C:\PlexStuff\Scripts\nzbToMedia\core\autoProcess\autoProcessComics.py", line 7, in <module>
    from core.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
  File "C:\PlexStuff\Scripts\nzbToMedia\core\nzbToMediaUtil.py", line 22, in <module>
    from core.linktastic import linktastic
  File "C:\PlexStuff\Scripts\nzbToMedia\core\linktastic\linktastic.py", line 31, in <module>
    info.dwFlags |= subprocess.STARTF_USESHOWWINDOW
AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'


Sorry for the constant issues but I appreciate you helping me out.

**Comment by clinton-hall** [comment]
Please install the pywin module for the matching Python version.

**Comment by whatupcraig** [comment]
I have downloaded 3 different versions and I am still getting the same thing. Does it matter if python is the 64 version? I have 2.7.12 (64 Bit) and have downloaded what I thought was the 64 bit version. I have also downloaded a few others and they also don't work. Currently I have Pywin 32-218 installed.

**Comment by whatupcraig** [comment]
I get this error at the end when trying to install pywin32-218.win-amd64-py2.7.exe

close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr

**Comment by whatupcraig** [comment]
Sorry for the ton of comments. I fixed it, with your help of course. Just reinstalled python and pywin and now it works! Thanks again for the help. You're a great dev.

**Comment by clinton-hall** [comment]
Glad you got it working.
Let me know if you have any further issues.
