### ISSUE TITLE
[QPKG] NZBGet Latest + Postprocessing QNAP  -> ImportError: No module named __future__

### ISSUE THREAD

**Issue by kaio85** [clinton-hall/nzbToMedia#1142]
Hi,

I´m getting this error when trying to use nzbtomedia:

`[/share/HDA_DATA/Download/nzbToMedia]`` # python2 nzbToSickBeard.py
Traceback (most recent call last):
  File "nzbToSickBeard.py", line 257, in <module>
    import nzbToMedia
  File "/share/HDA_DATA/Download/nzbToMedia/nzbToMedia.py", line 513, in <module>
    from __future__ import print_function
ImportError: No module named __future__
`

I tried setting up a symlink with `ln -sf /usr/local/bin/python2.7 /usr/local/bin/python2`

`[~] # which python`
`/usr/local/bin/python`

NZBGET error is " PP-FAILURE" with "nzbToSickBeard: ImportError: No module named __future__"

My setup is:
Clinton.Hall:        NZBGet_150706.qpkg -> updated to 17.1
qnap.stephane:  Qpython2 V2.7.12.0 + QCouchpotato + Qsickrage + Qheadphones
Latest QNAP firmware on TS-659

Everything works fine except NZBtomedia.
How can i fix this error?
I´m clueless now some help would be great:)
thx

**Comment by clinton-hall** [comment]
what versions of pythin qpkg do you have installed?
The problem here is there are so many different packages and most of them miss some standard packages...

**Comment by kaio85** [comment]
Thanks for the quick answer.
The version is QPython2_2.7.12.0_x86.qpkg
[](https://forum.qnap.com/viewtopic.php?f=217&t=109899&hilit=qpython2)

**Comment by gespenstergangster** [comment]
I second this post. It's not working for me, either. Please be kind and fix it.

**Comment by clinton-hall** [comment]
This is a broken python package, that does not include the __future__ module.
I can try and look at including __future__ but I need to test to ensure this doesn't break every other system.

**Comment by kaio85** [comment]
That would be awesome. I'm definitely lost with all these different python packages available.
Thanks for your great work ;)

**Comment by gespenstergangster** [comment]
Yes Clinton, please do that - keep up the good work.

**Comment by MnC2004** [comment]
Same issue here. Any news on this 'future' module?

**Comment by NewLunchbox** [comment]
I agree. a Python .qpgk with future module is needed. Any news?
