### ISSUE TITLE
NZBget Post Processing errors with renamer

### ISSUE THREAD

**Issue by shanester64** [clinton-hall/nzbToMedia#1143]
Post-process-script nzbToCouchPotato.py for Sully.2016.1080p.BluRay.x264-SPARKS failed (terminated with unknown status)

If I restart CP the renamer works fine.

[nzbtomedia.txt](https://github.com/clinton-hall/nzbToMedia/files/629172/nzbtomedia.txt)

**Comment by clinton-hall** [comment]
This appears to be taking you to the CouchPotato login page when calling http://192.168.0.24:5050/api/XXXXXXXXXX/renamer.scan

IS CP and NZBGet on the same system? if so, try setting the host to localhost not 182.168.0.24
Also check if you have any reverse proxy/url base set etc?

**Comment by shanester64** [comment]
It is on the same system. Originally was localhost and I changed it in attempt to resolve. I will change it back and post the results.

**Comment by shanester64** [comment]
After changing it back to localhost it is now working again!!
I have been struggling for some time now with PP renamer failures (Failed returning results or media not found) after moving from SAB to NZBGet. Prior to submitting this issue, I changed CP from windows exe to git source as well as starting out with a fresh autoprocessmedia.cfg.

Thanks for your quick response!!!
