### ISSUE TITLE
Transmission Post Processing able to seed?

### ISSUE THREAD

**Issue by natetheskate** [clinton-hall/nzbToMedia#1144]
I apologize in advance as this isn't really an issue but more of a question I haven't been able to find an answer to. Is it possible to have a torrent continue to seed after post processing and running of scripts? Everything works great but I would love to be able to seed some torrents from a private tracker once they complete. Thanks for any help!

**Comment by clinton-hall** [comment]
That was why Torrent support was added to this script.

The basic idea here is that TorrentToMedia will create a hardlink of the seeding media to the output directory. The linked file is then renamed/processed while the original files continue to seed.

**Comment by natetheskate** [comment]
Thanks for the fast response. Is there a guide to the settings to accomplish this? Maybe i need to update my scripts, I tried changing the advanced option deleteOriginal = 0 thinking that may do the trick but no luck, here is what I have for torrent in my cfg:

[Torrent]
    ###### clientAgent - Supported clients: utorrent, transmission, deluge, rtorrent, vuze, other
    clientAgent = transmission
    ###### useLink - Set to hard for physical links, sym for symbolic links, move to move, move-sym to move and link back, and no to not use links (copy)
    useLink = move
    ###### outputDirectory - Default output directory (categories will be appended as sub directory to outputDirectory)
    outputDirectory = /mnt/media/downloads/transmission/complete
    ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode.
    default_downloadDirectory = ""
    ###### Other categories/labels defined for your downloader. Does not include CouchPotato, SickBeard, HeadPhones, Mylar categories.
    categories = music_videos, pictures, software, manual
    ###### A list of categories that you don't want to be flattened (i.e preserve the directory structure when copying/linking.
    noFlatten = pictures, manual
    ###### uTorrent Hardlink solution (You must edit this if your using TorrentToMedia.py with uTorrent)
    uTorrentWEBui = http://localhost:8090/gui/
    uTorrentUSR = your username
    uTorrentPWD = your password
    ###### Transmission (You must edit this if your using TorrentToMedia.py with Transmission)
    TransmissionHost = localhost
    TransmissionPort = 9091
    TransmissionUSR = your username
    TransmissionPWD = your password
    #### Deluge (You must edit this if your using TorrentToMedia.py with deluge. Note that the host/port is for the deluge daemon, not the webui)
    DelugeHost = localhost
    DelugePort = 58846
    DelugeUSR = your username
    DelugePWD = your password
    ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
    deleteOriginal = 1
    chmodDirectory = 0
    resume = 1
    resumeOnFailure = 1

**Comment by natetheskate** [comment]
So I think i found the section you're referring to:

###### useLink - Set to hard for physical links, sym for symbolic links, move to move, move-sym to move and link back, and no to not use links (copy)
useLink = move

Do I want to set it to "move-sym" or "hard" to have the torrent extract and move the extracted file and the continue seeding the original? 

Thanks again.

**Comment by clinton-hall** [comment]
I recommend UseLink = hard

But also, if Transmission downloads to /mnt/media/downloads/transmission/complete
You should set 
outputDirectory = /mnt/media/downloads/transmission/temp 
Or similar.

Finally, make sure you set
TransmissionUSR
TransmissionPWD

**Comment by natetheskate** [comment]
Thanks you!
