### ISSUE TITLE
 [ERROR]::MAIN: Unable to migrate config file

### ISSUE THREAD

**Issue by Casburggraaf** [clinton-hall/nzbToMedia#1147]
When i try to run nzbToMedia after a download in nzbget on my synology nas I get this error:
 [ERROR]::MAIN: Unable to migrate config file

any help? After replace the hdd on my nass and reinstalling everything its giving this error. Perviously it was working without problems..

`Sat Dec 17 18:18:47 2016	INFO	Post-processing again HIDDEN
Sat Dec 17 18:18:47 2016	INFO	HIDDEN returned from history back to download queue
Sat Dec 17 18:18:47 2016	INFO	HIDDEN for post-processing
Sat Dec 17 18:18:47 2016	INFO	Executing post-process-script nzbToMedia/nzbToMedia.py for 3.Percent.S01E03.480p.WEBRip.x264-ITSat
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia: [18:18:48] [ERROR]::MAIN: Unable to migrate config file /volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia: Traceback (most recent call last):
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:   File "/usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 817, in <module>
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:     exit(main(sys.argv))
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:   File "/usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 649, in main
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:     core.initialize(section)
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:   File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/core/__init__.py", line 292, in initialize
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:     CFG = config.addnzbget()
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:   File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/core/nzbToMediaConfig.py", line 253, in addnzbget
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:     CFG_NEW = config()
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:   File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/core/nzbToMediaConfig.py", line 94, in __init__
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:     super(configobj.ConfigObj, self).__init__(*args, **kw)
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:   File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/libs/configobj/configobj.py", line 1229, in __init__
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:     self._load(infile, configspec)
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:   File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/libs/configobj/configobj.py", line 1318, in _load
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia:     raise error
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia: configobj.configobj.ConfigObjError: Parsing failed with several errors.
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia: First error at line 117.
Sat Dec 17 18:18:48 2016	INFO	nzbToMedia: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x755e7870>> ignored
Sat Dec 17 18:18:48 2016	ERROR	Post-process-script nzbToMedia/nzbToMedia.py for 3.Percent.S01E03.480p.WEBRip.x264-ITSat failed (terminated with unknown status)
Sat Dec 17 18:18:48 2016	INFO	HIDDEN added to history
`

`/volume1/@appstore/nzbget/share/nzbget/scripts$ ls -l
total 24
-rwxr-xr-x 1 nzbget root 9671 Nov 21 10:04 EMail.py
drwxr-xr-x 3 nzbget root 4096 Nov 21 10:04 GetScripts
-rwxr-xr-x 1 nzbget root 3297 Nov 21 10:04 Logger.py
drwxr-xr-x 7 nzbget root 4096 Dec 17 18:14 nzbToMedia
/volume1/@appstore/nzbget/share/nzbget/scripts$ 
`

`/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia$ ls -l
total 236
-rw-rw-rw-  1 root   root 18825 Dec 17 18:14 autoProcessMedia.cfg
-rw-rw-rw-  1 root   root 17499 Dec 17 18:14 autoProcessMedia.cfg.old
-rw-rw-rw-  1 root   root 17501 Dec 17 18:14 autoProcessMedia.cfg.spec
-rw-rw-rw-  1 root   root 22321 Dec 17 18:14 changelog.txt
drwxr-xr-x 10 nzbget root  4096 Dec 17 18:14 core
-rwxr-xr-x  1 nzbget root   504 Nov 21 10:04 getffmpeg.sh
drwxr-xr-x 30 nzbget root  4096 Dec 17 18:14 libs
-rw-r--r--  1 nzbget root 35127 Nov 21 10:04 license.txt
drwxrwxrwx  2 root   root  4096 Dec 17 18:14 logs
-rwxrwxrwx  1 root   root  7074 Dec 17 18:14 nzbToCouchPotato.py
-rwxr-xr-x  1 nzbget root  2719 Nov 21 10:04 nzbToGamez.py
-rwxrwxrwx  1 root   root  3372 Dec 17 18:14 nzbToHeadPhones.py
-rw-r--r--  1 root   root  4096 Dec 17 18:14 nzbtomedia.db
-rwxrwxrwx  1 root   root 27064 Dec 17 18:14 nzbToMedia.py
-rwxr-xr-x  1 nzbget root  3087 Nov 21 10:04 nzbToMylar.py
-rwxrwxrwx  1 root   root  6677 Dec 17 18:14 nzbToNzbDrone.py
-rwxrwxrwx  1 root   root  6999 Dec 17 18:14 nzbToSickBeard.py
-rw-r--r--  1 nzbget root  5042 Nov 21 10:04 README.md
drwxr-xr-x  2 nzbget root  4096 Nov 21 10:04 tests
-rwxr-xr-x  1 nzbget root 16385 Nov 21 10:04 TorrentToMedia.py`

**Comment by clinton-hall** [comment]
Try changing the owner of `/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia` and all sub-files/folders to nzbget root

**Comment by Casburggraaf** [comment]
That didnt help. Even setting everthing to 777 did not the trick. What fixed it was setting autoProcessMedia.cfg by vi.. So nzbget is doing something that corrupts the config.

A other question. Is it possible to run nzbdronescript with the categories Serrie and tv? Because spotweb use tv as categorie and i can't change it. But i would like that it's downloading in the Series folder and being processed by sonar

**Comment by clinton-hall** [comment]
To support multiple categories, just set Category `Serrie` and Category `tv` to both call nzbToNZBDrone in NZBGet.

**Comment by Casburggraaf** [comment]
Thnx that works but how can i disable AppendCategoryDir for a Category?

**Comment by Casburggraaf** [comment]
A other question. It there a possibility to ad a artist to headphones that is not in the wanted list. Now if i download a album with a artist that is not in the wanted list nzbtomedia fails

**Comment by clinton-hall** [comment]
I believe you need to add the artist to HeadPhones first.
I don't know how to disable the cetegory directory. Honestly, if this was anissue I would simply create 1 as a symlink to the other.

e.g. if you have `/volume1/media/tv` then I woulc create a symlink to `/volume1/media/tv`  at `/volume1/media/Serrie`

This way both categories are actually in the same place...
