### ISSUE TITLE
QQ: scene release videos

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1148]
I'm stumble on a handful of instances so far where either SR or CP end up with a media file with is just the scene group video ie RARBG's little loop video. Not sure what's causing this so I thought i would inquire. its been sort of random so i haven't caught one in the logs yet.

**Comment by clinton-hall** [comment]
Yeah, would need to see logs. I have not observed this myself.
In general these files should be small and should be ignored...
