### ISSUE TITLE
Extraction Failed; Could not call command

### ISSUE THREAD

**Issue by creoden** [clinton-hall/nzbToMedia#1149]
Getting the following error when sending any compressed file from utorrent to TorrentToMedia,

Error from nzbtomedia.log
`ERROR   ::MAIN: EXTRACTOR: Extraction failed for D:\Downloads\Complete\tv\SHOW\SHOW.rar. Could not call command ['C:\\nzbToMedia\\core\\extractor\\bin\\invisible.cmd', 'C:\\nzbToMedia\\core\\extractor\\bin\\AMD64\\7z.exe', 'x', '-y', 'D:\\Downloads\\Complete\\tv\\SHOW\SHOW.rar', '-p-']`

The command it is erroring out on

Command from nzbtomedia.log
`2016-12-23 00:41:59 DEBUG   ::MAIN: Extracting ['C:\\nzbToMedia\\core\\extractor\\bin\\invisible.cmd', 'C:\\nzbToMedia\\core\\extractor\\bin\\AMD64\\7z.exe', 'x', '-y'] D:\Downloads\Complete\tv\SHOW\SHOW.rar D:\Downloads\Pending\tv\SHOW
`

If i try to use the extractor paramaters in 7zip
E.g:
`C:\\nzbToMedia\\core\\extractor\\bin\\AMD64\\7z.exe x -y D:\Downloads\Complete\tv\SHOW\SHOW.rar D:\Downloads\Pending\tv\SHOW`

 I get the error

```
Error:
Cannot use absolute pathnames for this command
```

7zip is wanting the path to be sent to it as -oD:\Downloads\Pending\tv\SHOW

Any assistance would be appreciated.

This is on a Windows 7 x64 box, with a freshly pulled master repo of nzbToMedia.

**Comment by clinton-hall** [comment]
Try updating to latest nightly and test.

**Comment by creoden** [comment]
Still getting the same error, I've included a full log, is there any way to get the error that 7zip is providing when extraction fails through extractor.py?

https://gist.github.com/creoden/274387d57d0098e93d344ed1e7e45b99

**Comment by creoden** [comment]
Just deleted everything, and pulled a fresh master, and redid the autoprocessmedia.cfg file and everything is working now, not sure what the problem is but it is gone.
