### ISSUE TITLE
CouchPotato style Category option (?)

### ISSUE THREAD

**Issue by Finch106** [clinton-hall/nzbToMedia#1151]
In CouchPotato, you can assign categories to choose while selecting a movie, and setup folders to send these catagorized downloads i.e. No category/standard goes to /Media/Movies, 3D goes to /Media/3D, and UHD goes to /Media/4K. If I want to manually run nzbToMedia, I have setup an additional [[4k]] category in the CouchPotato section of autoProcessMedia.cfg, but because it's not looking at the couch category, it'll just rename whatever is in /Complete/4k and place it in /Media/Movies. Is there a section in a config where I can tell it to move the /Complete/4k downloads after renaming to /Media/4K ?

**Comment by clinton-hall** [comment]
No, unfortunately at this time nzbToMedia only tells CP to rename and there is no option in CP's api to feed in a category.
The only time category is currently used in CP is when the movies is already in CP's database with that category assigned.

If CP's api is modified to allow feed-in of category, I'll add that in to nzbTomedia.
