### ISSUE TITLE
QQ: too many downloads / too fast downloads?

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1156]
So i've discovered that while i'm using SAB / uTorrent, both with nTM but i get timeouts talking to CP occasionally. I've now discovered that I have movie folders with somemedia.ext somemedia cd 1.ext and somemedia cd 2.ext (ext being some variable media type) which are technically 3 copies of the movie in, various formats / sources / sizes. They aren't always actually 2 part movies, but 2 files were found in the download folder at the time of postproc and considered to be 2 parts of the same movie.

I'd like to figure out how to do the following, but not sure the best route:
1. recursively find all folders over a certain size with multiple media files (i don't want any folder over 2.1GB)
2. if there are more than one media file consider the following:
a. newest file
b. highest quality
3. if there are cd1 cd 2 files, check duration to see if its a partial or full movie file.
4 cleanup all but the 1 relevant file.
5 rename if needed

**Comment by clinton-hall** [comment]
So, what you are looking for is a media management tool to go through your collection?

How has this actually come about? Has nzbToMedia actually caused this to be renamed as such, or is this in CouchPotato etc?

Basically, if there are .cd1 and .cd2 this means CoucPotato was passed a folder with 2 files in it. If there are .ext as well as .cd1.ext and cd2.ext this means CP was originally give 1 file, then later asked to rename 2 files.
I can't understand how this could really come about... nzbToMedia should only copy/move/link the files associated with any single download and then process them to CP.

**Comment by mgaulton** [comment]
I was hoping to script something to poke the files and pick the newest with best quality and nuke the rest.

I can only think that multiple downloads got put into a folder of the same name (not sure how) and then got passed. i only noticed this with more recent downloads. 

I'm not sure either. I was puzzled to find it but it seems like quite a few have been like that. i'm manually cleaning them up.

here's an example of what i found
-rwxr-xr-x 1          500 1000 1611246411 Sep 29 05:08 'Moonrise Kingdom (2012) cd1.mkv'
-rwxrw-r-- 1           99 1000       8750 Jan  1 03:42 'Moonrise Kingdom (2012) cd1.nfo'
-rwxrw-r-- 1           99 1000     304222 Jan  1  1979 'Moonrise Kingdom (2012) cd2-poster.jpg'
-rwxr-xr-x 1          500 1000 1418839736 Sep 29 06:29 'Moonrise Kingdom (2012) cd2.mp4'
-rwxrw-r-- 1           99 1000       9167 Jan  1 03:42 'Moonrise Kingdom (2012) cd2.nfo'
-rwxrwxrwx 1          500 1000  724442222 May  8  2015 'Moonrise Kingdom (2012).avi'
-rwxrw-r-- 1 silverdragon 1000     163840 Jan  1  1979 'Moonrise Kingdom (2012).eng.srt'
-rwxr-xr-x 1          500 1000 1560701134 Feb 27  2016 'Moonrise Kingdom (2012).mp4'
-rwxrw-r-- 1           99 1000       8763 Jan  1 03:42 'Moonrise Kingdom (2012).nfo'
-rwxr-xr-x 1          500 1000       2121 Jan  1  1979 'Moonrise Kingdom (2012).orig.nfo'
-rwxr-xr-x 1          500 1000        104 Jan  1  1979 'Moonrise Kingdom (2012).srt'
-rwxrw-r-- 1           99 1000     499054 Jan  1  1979 fanart.jpg
-rwxrw-r-- 1           99 1000      94419 Jan  1  1979 logo.png
