### ISSUE TITLE
Confused!

### ISSUE THREAD

**Issue by romprod** [clinton-hall/nzbToMedia#1159]
Hi,

I'm very confused by the config file and could do with a little help please!

I have Deluge setup to download TV shows, they end up in "D:\Downloads\TV.Torrents.Finished" when they've finished downloading. I also have "D:\Downloads\TV.Torrents.Sickbeard.To.Process" setup and ready for SickBeard/SickRage to postprocess from, but I'm not sure that's needed??

I'd like to copy these files and have SickRage/SickBeard then post process these files but leaving the original files intact for Deluge to continue seeding.

Can someone help me with which sections in the config file that I need to change.

Thanks!

**Comment by clinton-hall** [comment]
```
[Torrent]
    clientAgent = deluge
    useLink = hard
    outputDirectory = D:\Downloads\TV.Torrents.Sickbeard.To.Process
    default_downloadDirectory =D:\Downloads
    DelugeHost = localhost
    DelugePort = 58846
    DelugeUSR = your username
    DelugePWD = your password
    deleteOriginal = 0
    chmodDirectory = 0
    resume = 1
    resumeOnFailure = 1
```
Then set-up {SickRage] [[TV]]

The separate ouputDirectory is necessary to prevent renaming processes from messing up the seeding torrents.

**Comment by romprod** [comment]
Not sure I understand what I'm doing wrong or what nzbtomedia is going to be doing for me.

I'll go over what I have setup.

Deluge Starts downloading to D:\Downloads\TV.Torrents.Downloading and then moves to D:\Downloads\TV.Torrents.Finished. I had a post.bat setup to copy the single download to D:\Downloads\TV.Torrents.Sickbeard.To.Process  and then call the mediatosickrage.py script to then push it into Sickrage from D:\Downloads\TV.Torrents.Sickbeard.To.Process (mediastosickrage.py D:\Downloads\TV.Torrents.Sickbeard.To.Process) Pretty simple!

The only stumbling block I had with the above is the fact that it fails to connect to SickRage when I set a User/Pass in Sickrage which I need to do, I can't have it open for the world to openly access!

Can I not have Nzbtomedia just do the final hurdle and push the single download into Sickrage?

I've tried setting it as you suggested but it tried to process my whole D:\Downloads\TV.Torrents.Finished folder and created a bunch of subfolders everywhere and created a bunch of hardlinks.

**Comment by clinton-hall** [comment]
Ok, you need to set Deluge to call TorrentToMEdia.py (not nzbToMedia.py) with the correct parameters so that it only processes the current file, not the whole folder.

https://github.com/clinton-hall/nzbToMedia/wiki/deluge

**Comment by romprod** [comment]
OK thank you.

The script is still creating subfolders "D:\Downloads\TV.Torrents.Sickbeard.To.Process\TV" and "D:\Downloads\TV.Torrents.Sickbeard.To.Process\Showname" and the original file is still in "D:\Downloads\TV.Torrents.Sickbeard.To.Process" these subfolders are also leftover.

Sorry am I missing something very basic here? I have a single file in a single directory that I need to be moved into Sickrage and then deleted from "D:\Downloads\TV.Torrents.Sickbeard.To.Process" Not sure why I need extra subdirectories creating and hardlinks to the file. Can I not skip past all of that? Seems very complicated for a simple process?

I can use "mediatosickrage.py D:\Downloads\TV.Torrents.Sickbeard.To.Process" etc fine and it does exactly that, but the ability to log into sickrage with a username/password means it doesn't work anymore.

Sorry for the questions! :)

**Comment by clinton-hall** [comment]
ok, so forget the old post.bat, and just have deluge trigger TorrentToMedia.
in autoProcessMedia.cfg
```
[Torrent]
    outputDirectory = D:\Downloads\TV.Torrents.Sickbeard.To.Process
```

the files are downloaded by deluge to D:\Downloads\TV.Torrents.Finished.
then TorrentToMedia will hard-link the files to D:\Downloads\TV.Torrents.Sickbeard.To.Process\TV\Showname
and then this is sent to SickRage to move the download to the final media location.

The advantage to this method is that it links the file, so that your renamed media file and original (seeding) file both exist and appear as separate files, but this doesn't take up additional space (with your copy, from post.bat, you were doubling up the drive use).

**Comment by romprod** [comment]
OK Brilliant thankyou.

Think I've got it sorted now.

A few questions...

My current Deluge finished directory has 20 separate downloads in it, how do I run TorrentToMedia.py on this directory for the first time without creating havoc? Also, will it remember which of these downloads it has processed so that it doesn't have to re-do the entire lot every time?

I've run it on a test directory which had a torrent named folder with a bunch of mkv's in it, it processed everything correctly but left over the directory  D:\Downloads\TV.Torrents.Sickbeard.To.Process\tv\ShowName.WEBRip.AAC2.0.H.264-123 how do I go about making it remove this torrent named folder? I guess otherwise I'll just end up with an endless list of folders in there?

**Comment by romprod** [comment]
Also, it seems that Deluge locks the download I guess when it's being uploaded to a peer. This happens before the file has been postproccessed and after the file has been hard linked. Which causes issues postproccessing as well as issues if/when SickRage needs to update the existing version of the episode from say 720 to 1080p.

So I guess hard linking isn't really suitable with Deluge and Sickrage if you need to seed the torrent after post process and if you need SickRage to update episode qualities to 1080p etc.

**Comment by clinton-hall** [comment]
When called from Deluge, TorrentToMedia should only process the 1 download, and yes it remembers what it has processed (but not from a manual run).
Personally, I prefer each download to be in a separate folder (if the download client can support this) to avoid cross-contamination of downloads.

The way the lock file works, TorrentToMedia is supposed to pause the download (which removes the lock) and then wait for postprocessing to complete before resuming seeding. So there shouldn't be any issue with postprocessing.
With updating episode quality, this may prevent SickRage from deleting the existing quality. The solution to this would be to replace the pause of the seeding file with a "universal" pause of all seeding files... 
I'd have to look into this to see if it is feasible and just how much work would be involved.
