### ISSUE TITLE
Transcoder / Couchpotato Renamer Issue

### ISSUE THREAD

**Issue by mediaman88** [clinton-hall/nzbToMedia#1161]
Everything is working swimmingly with my nzbToMedia / Couchpotato setup with one exception, I have the files set to transcode (remux) and when it finishes I'm left with the MKV file and the MP4 file with cd1 and cd2 appended to each.  I'm assuming this has something to do with the timing of my renamer but I can't seem to identify.  I have the "Rename Downloaded Movies" scraper in Couchpotato set to 10 minutes, which should be plenty of time to avoid issues given my remux usually only takes a minute or two per movie.

**Comment by clinton-hall** [comment]
Set CouchPotato Renamer Run_Every = 0 and force_every = 0 (so it only runs when nzbToMedia calls it.

Also, in autoProcessMedia
```
[Transcoder]
   duplicate = 0
```
eill ensure the original .mkv is deleted when the .mp4 is created.

**Comment by mediaman88** [comment]
Yet again, fixed!  Thank you!
