### ISSUE TITLE
nzbToMedia needs a update for sick rage 

### ISSUE THREAD

**Issue by Fish2** [clinton-hall/nzbToMedia#1162]
sickrage has had a update 8c44b578f178e25e02df9acd66d61e87c9c4516c and nzbToMedia needs a update for processing

**Comment by clinton-hall** [comment]
#1158

**Comment by miigotu** [comment]
That issue I put a temp fix for by adding the `Successfully processed` in hidden html of the page. Most importantly now force_clean=0 needs to be set because SR isnt processing anything by the time it returns to nzbtomedia, it just adds the processing task to a queue to be processed now.

**Comment by fontes31** [comment]
Where i can find force_clean=0?

**Comment by clinton-hall** [comment]
autoProcessMedia.cfg
```
[General]
        force_clean = 0
```

**Comment by fontes31** [comment]
thanks you.
