### ISSUE TITLE
Renaming of files based on country

### ISSUE THREAD

**Issue by mediaman88** [clinton-hall/nzbToMedia#1164]
I'm evidently missing a setting that adds videos to folder based on a scan of the filename.  For example, I have a file called "Around the World in 80 Gardens - 1x01 - Mexico and Cuba" and when it is processed it creates a directory called Around the World in 80 Gardens (MX)  same thing happens with Around the World in 80 Gardens - 1x08 - South Africa, creates a directory called Around the World in 80 Gardens (ZA)  Most of the shows end up in the main Around the World in 80 Gardens directory but I end up with 3-4 additional directories where it has read the filename containing a country.  I have about 20-30 travel shows so you can imagine how many extra directories this creates.

**Comment by clinton-hall** [comment]
I don't think this is done in nzbToMedia. I am guessing this is the way these are renamed by Sonaar or SickBEard/SickRage?
