### ISSUE TITLE
SickRage Failed Download Handling Integration

### ISSUE THREAD

**Issue by drspangle** [clinton-hall/nzbToMedia#1167]
Seems that when a failed download is signalled to SickRage, something along the line isn't working. See the log below:
[pastebin link](http://pastebin.com/JNkdtfwp)

Problem is, the SickRage history is not showing this episode as failed, and it's still marked as SNATCHED. It'll sit like this forever until I manually mark the episode as FAILED through the episode status management interface. I can't tell whether this is because of the changes to the autoPostProcess code in SickRage, a problem with the new parameters in the API call from nzbToMedia to SickRage, or a problem with nzbToMedia that I can't identify. My gut tells me that this has something to do with both, because the failed download handling stopped working since the autoPostProcess queue was introduced, but the recent patch there and also to nzbToMedia ought to have fixed this.

**Comment by clinton-hall** [comment]
please switch to nightly build, update and test.

**Comment by Jon87** [comment]
+1 same behaviour, logs look like everything's working but eps still marked as snatched. Moved to nightly and still getting the same.

**Comment by schubydoo** [comment]
I'm having the same issue.  In fact, ever since the latest SickRage update, even successful files are being deleted.  Also switched to nightly.

**Comment by Jon87** [comment]
Weird, seems deleting and re-cloning does fix it. Fine now on nightly.

**Comment by drspangle** [comment]
Switched to nightly, updated, still experiencing the same problem. nzbToMedia reports that the episode was set to FAILED, but there isn't any change in status reflected in SickRage. Not sure where the problem is.

**Comment by clinton-hall** [comment]
Note the above comments. It appears wiping the entire NzbToMedia directory and re-cloning the repo fixes  this. Alos, this is in master branch now.

**Comment by drspangle** [comment]
Would be nice if there was a good explanation for why re-cloning from repo fixes this, but I imagine that's the price we pay for using git to manage this.
Probably worth creating stable releases and managing versioning of them using the same repo, but that's just a suggestion. For now the issue seems to be solved.
