### ISSUE TITLE
QTS 4.3.2 + nzbToMedia

### ISSUE THREAD

**Issue by gespenstergangster** [clinton-hall/nzbToMedia#1168]
Hi, my problem is that your /usr/bin/env python2 shebang selects the first python in the usr/bin/. On archlinux python3 is falsely/confusingly named python. The script then tries to run under python3, obviously crashes. I changed the shebang to point directly to /usr/bin/python2.7. Now the script launches, but I've got problems with the auto update routine, it seems to fail to detect the currently used nzbToMedia Version, auto-update fails. If it would succeed it would change the shebang again, script wouldn't work again, right? What can I do about it?

**Comment by clinton-hall** [comment]
ok, the she bang calls /usr/bin/env python2 which should find the first `python2` in the system Path and not `python`
You should be able to do an export in the init script for your downloader. This would change the order of selection...
e.g. in the init.d for nzbget put `export PATH=/usr/local/bin:$PATH` and ensure that /usr/local/bin/python2 links to /usr/bin/python2.7

otherwise switch to OSX branch. this has shebang `/usr/bin/env python2.7`

**Comment by gespenstergangster** [comment]
Thanks for your answer. Got it to work that way. Now I've stumbled into another issue. I wanted to have nzbtomedia updatable. So I saved the cfg-file, deleted the whole thing and cloned it via git clone. Now for whatever reason nzbtomedia refused to load the settings from the configfile I just copied back. Restarting everything did nothing. So I deleted the folder that was created by git, reentered the git clone command and now I get this. 
`git: error while loading shared libraries: libcharset.so.1: cannot open shared object file: No such file or directory`
Any ideas?

**Comment by clinton-hall** [comment]
when you saved the cfg file, and copies it back, was this done as a different user than is used to run the script?

**Comment by gespenstergangster** [comment]
I think it was under the same user. I'm a bit confused now because now nzbtomedia seems to save the settings somewhere else and completely ignores the cfg file. I can't edit the path to ffmpeg over the web-interface, though.

**Comment by clinton-hall** [comment]
Can you show the log from nzbToMedia? this will show where the settings are being saved.

**Comment by gespenstergangster** [comment]
Hey clinton. First of all thanks for your replies. I've got almost everything setup now, so will soon stop bugging you :) Now my last Problem is this:

`2017-01-14 11:18:23 INFO    ::MAIN: Checking if git needs an update
2017-01-14 11:18:23 ERROR   ::MAIN: Unable to determine installed version via git, please check your logs!
2017-01-14 11:18:23 INFO    ::MAIN: No update needed`

I setup the path to git, cloned from git and the nzbtomedia-folder contains the hidden .git folder. Any ideas?

**Comment by gespenstergangster** [comment]
Help :(
