### ISSUE TITLE
Question: NZBtoMedia - Couchpotato

### ISSUE THREAD

**Issue by HPMSGEN8** [clinton-hall/nzbToMedia#1169]
Hi @clinton-hall 

So now CouchPotato seems to be an issue. It works 100% no issues asked there but for some odd reason when the file starts with the group, version or anything other then the name i get this:

`[21:34:48] [INFO]::MAIN: Loading config from [/volumeX/Downloads/103 NZB/Scripts/nzbToMedia/autoProcessMedia.cfg]`
`[21:34:48] [INFO]::MAIN: Checking database structure...`
`[21:34:48] [INFO]::MAIN: Checking if git needs an update`
`[21:34:49] [INFO]::MAIN: No update needed`
`[21:34:49] [INFO]::MAIN: nzbToMedia Version:66abb2d562aa9491c5c5fad0c228e20a05982fd7 Branch:master (Linux 3.10.77)`
`[21:34:49] [INFO]::MAIN: #########################################################`
`[21:34:49] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##`
`[21:34:49] [INFO]::MAIN: #########################################################`
`[21:34:49] [INFO]::MAIN: Script triggered from SABnzbd`
`[21:34:49] [INFO]::MAIN: Auto-detected SECTION:CouchPotato`
`[21:34:49] [INFO]::MAIN: Calling CouchPotato:movies to post-process:The.Early.Hatchling.Gets.the.Worm.2016.1080p.BluRay.x264-FLAME.nzb`
`[21:34:49] [INFO]::MAIN: Attemping imdbID lookup for The.Early.Hatchling.Gets.the.Worm.2016.1080p.BluRay.x264-FLAME.nzb`
`[21:34:49] [INFO]::MAIN: Searching folder and file names for imdbID ...`
`[21:34:49] [INFO]::MAIN: Searching IMDB for imdbID ...`
`[21:34:50] [INFO]::MAIN: Found imdbID [tt5797476]`
`/volumeX/@appstore/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)`
`/volumeX/@appstore/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)`
`[21:34:51] [INFO]::TRANSCODER: Checking [flame-the.early.hatchling.gets.the.worm.2016.1080p.bluray.x264.mkv] for corruption, please stand by ...`
`/volumeX/@appstore/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)`
`/volumeX/@appstore/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)`
`[21:34:51] [INFO]::TRANSCODER: SUCCESS: [flame-the.early.hatchling.gets.the.worm.2016.1080p.bluray.x264.mkv] has no corruption.`
`[21:34:51] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for The.Early.Hatchling.Gets.the.Worm.2016.1080p.BluRay.x264-FLAME.nzb`
`[21:34:51] [POSTPROCESS]::COUCHPOTATO: SUCCESS: Finished renamer scan for folder /volumeX/Downloads/103 NZB/Complete/102 Movies/The Early Hatchling Gets the Worm 2016 1080p BluRay x264-FLAME`
`[21:34:51] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...`
`[21:35:11] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...`
`[21:35:31] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...`
`[21:35:51] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...`
`[21:36:11] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...`
`[21:36:31] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...`
`[21:36:51] [WARNING]::COUCHPOTATO: The.Early.Hatchling.Gets.the.Worm.2016.1080p.BluRay.x264-FLAME.nzb does not appear to have changed status after 2 minutes, Please check your logs.`
`[21:36:51] [ERROR]::MAIN: A problem was reported in the /volumeX/Downloads/103 NZB/Scripts/nzbToMedia/nzbToCouchPotato.py script.`
`CouchPotato: Failed to post-process - No change in status!`

File Name: `flame-the.early.hatchling.gets.the.worm.2016.1080p.bluray.x264.cp(tt5797476).mkv`

No it does not Re-Name the file like it states it does.

So is there no way this process can look at the Folder Name instead of the file name and re-name it to the Folder Name and Process it as well. This way the issues will be solved. If it is doing this then great but then why is this one listed about not working. 

Thanks alot again :)

**Comment by HPMSGEN8** [comment]
Anyone have any advice here please... As this one is driving me nuts on why it will not work.

**Comment by clinton-hall** [comment]
Check CouchPotato logs from [21:34:51]
It appears CouchPotato is not renaming (possible because of confusing file name...
The thing here is nzbToMedia appear to have identified the movie, and should have passed in the imdb_id

I'd need to see debug logs from nzbToMedia and debug logs from CouchPotato to see what is happening

**Comment by HPMSGEN8** [comment]
Thanks for the reply. I ran the script manually now and this is what CouchPotato has in the logs. nzbToMedia logs are the same as the first post. 

`01-14 09:37:08 INFO [tato.core.plugins.renamer] Scanning media folder /volumex/Downloads/103 NZB/Complete/102 Movies/The Early Hatchling Gets the Worm 2016 1080p BluRay x264-FLAME-1...`

`01-14 09:37:08 INFO [tato.core.plugins.scanner] Download ID provided (None), but no groups found! Make sure the download contains valid media files (fully extracted)`

Thanks

**Comment by clinton-hall** [comment]
CouchPotato doesn't work with short-films. This movie is only 2 mins in duration and therefore I am assuming is less that 400MB in file size? CouchPotato will not recognize this a valid media file.

**Comment by HPMSGEN8** [comment]
Thanks alot for this info and it is good to know :). I will close this now.
