### ISSUE TITLE
[Request] AutoUpdate Feature For Repo

### ISSUE THREAD

**Issue by HPMSGEN8** [clinton-hall/nzbToMedia#1173]
Hi,

Is there an AutoUpdate Feature for this at all. I have moved to nightly and want it to check the repo every 4 to 12 hours and then do an update if you have made changes.

Thanks

**Comment by clinton-hall** [comment]
Yes, if you have installed via git clone, then on script run this should auto-update.
Assumes git is in the system path. Otherwise you can specify the git binary location in [general] settings.

**Comment by HPMSGEN8** [comment]
Thanks alot :)
