### ISSUE TITLE
7za Windows missing argument

### ISSUE THREAD

**Issue by romprod** [clinton-hall/nzbToMedia#1175]
7za.exe on windows needs an extra argument in a command line, this script isn't passing that argument.

Apparently it needs -o to specify the output directory ie;

`7z.exe x -y D:\Downloads\Movie.Torrents.Finished\Movie.2012.720p.BluRay.x264\Movie-720.rar -oD:\Downloads\TV.Torrents.Sickbeard.To.Process\movies\Movie.2012.720p.BluRay.x264`

If not, it exits with this error.

`Error:
Cannot use absolute pathnames for this command`

Using Windows 10

**Comment by creoden** [comment]
I thought clinton-hall fixed it after  #1149 with the [append -o to output path for 7zip.] (https://github.com/clinton-hall/nzbToMedia/commit/e96998a7310db57cbee8077ac242bdf2181b90ba) but it appear to have caused more problems. a rollback, removing the changes from this commit should fix the problem, 

I think the root of the problem for requiring -o stemmed from the fact that on the install i was running it on, pythons path wasn't listed as a system variable, and I was calling all scripts through the full path to python, which required -o for some reason. upon fixing the issue with pythons path, it worked without the commit, and this commit didn't get pushed to master it looks like, till the whole debacle with sickrage and queuing.

**Comment by clinton-hall** [comment]
Seemed easier to just reverse instead of trying to squash as commit :)
