### ISSUE TITLE
Categories used for re-naming

### ISSUE THREAD

**Issue by facted** [clinton-hall/nzbToMedia#1176]
I see that couchpotato supports categories which is great! But it looks like it only passes this to SabNZBD where I can set the folder for the movie to download to. However, if I then post-process in couch potato to rename, etc..., I'm only allowed the global settings. Is there a way to incorporate the use of categories for different post-process renaming so different categories are moved to different folders? Thanks!

**Comment by clinton-hall** [comment]
This is all handled in CouchPotato.

CP will snatch the movie to SABnzbd where all downlaods are done in the same location (either default SABnzbd location, or in the directory given to SABnzbd by CP (settings, downlaoders, sabnzbd).

Once the renamer is triggered in CP it knopws that the movie is allocated to the category, so it will renamed to the folder given in CP Settings, renamer, "To". Note there is a "To" folder for each category.
