### ISSUE TITLE
transcoder config

### ISSUE THREAD

**Issue by brinkdogg** [clinton-hall/nzbToMedia#1178]
Hello,
I'm looking for just the transcoder config - No couchpotato or anything. I just want to convert .mkv to .mp4 for all movies. To be honest I've tried changing the autoProcessMedia.cfg and nzbtomedia many time and post process fails. I'd like to see a full functional config to compare what I'm doing wrong. Not trying to cheat just see WTF I'm missing. ubuntu 16.04 -

**Comment by clinton-hall** [comment]
I don't have a full functional config myself (I don't use transcoder)
I can take a look at your config, and logs that show the failure... The main issue is I haven't really set this up to do transcoder in isolation. i.e. without a connection to SickBeard/CouchPotato this script will give an error and will not continue to transcode.

**Comment by brinkdogg** [comment]
Thanks for hitting me up on the NZBGET Forum. SOOOOOO I believe I got it working!!!! nzbtocouch. But heres a quick question. The server this is running on has 2x 14 core dual threaded CPU'a (56 CPU's) and 386GB RAM & 10 2tb drives. 

1. When I watched the process it was only using 1 of the CPU's. How and where could I specify the number of CPU's to use?  I'm not really familiar with ffmpeg so if could spell out all the variables that be AWESOME. 

2. I'm currently using a program called iflicks (Mac) that converts/MUX's (might be the right term) in just a few mins. 8gb video file takes about 10 15 mins to move from .mkv to .mp4.

3. What does it mean mount point? in the autoProcessMedia.cfg 
[Network]
    # Enter Mount points as LocalPath,RemotePath and separate each pair with '|'
    # e.g. MountPoints = /volume1/Public/,E:\|/volume2/share/,\\NAS\
    mount_points = "SHOULD I have something here?"

**Comment by clinton-hall** [comment]
don't worry about mount_points, this is only when nzbToMedia (NZBGet) runs on one system and sends the processed files to SickRage/CouchPotato running on another system.

To use more CPUs you can try
```
[Transcoder]
    generalOptions = -threads,0
```
this should auto detect and assign number of CPUs

or try
```
[Transcoder]
    generalOptions = -threads,8
```
```
[Transcoder]
    generalOptions = -threads,14
```
etc to specify the number to use... I wouldn't try 56 right off the bat... play and see what, if anything, works...

**Comment by brinkdogg** [comment]
-codec copy would this work as well to MUX the file?

**Comment by brinkdogg** [comment]
I do see this 

ERROR	Wed Feb 01 2017 00:13:08	Post-process-script nzbToMedia-master/nzbToCouchPotato.py for SOMEMOVIE failed
INFO	Wed Feb 01 2017 00:13:08	nzbToCouchPotato: CouchPotato: Failed to post-process - No change in status!
INFO	Wed Feb 01 2017 00:13:08	nzbToCouchPotato: [00:13:08] [ERROR]::MAIN: A problem was reported in the /usr/share/nzbget/scripts/nzbToMedia-master/nzbToCouchPotato.py script.
INFO	Wed Feb 01 2017 00:13:08	nzbToCouchPotato: [00:13:08] [WARNING]::COUCHPOTATO: SOMEMOVIE does not appear to have changed status after 2 minutes, Please check your logs.

**Comment by clinton-hall** [comment]
so are you using CouchPotato to rename movies?
was this movie snatched by CouchPotato?

**Comment by brinkdogg** [comment]
No and No. I've using another app (iFlicks) to do the Metadata, conversion. I'll make the change sorry was getting sleepy when I posted. So as I read it I realized that!. DOH!

**Comment by brinkdogg** [comment]
Still not seeing the performance I'd like. the system load is very low when transcoding occurs even with the call out of -threads 14. Any other ideas? The renaming aspect of couchpotato  does a good job but would love if it embedded the the picture of the movie along with all the metadata.

**Comment by brinkdogg** [comment]
Can I use avconv instead of FFMPEG? The thread command is just not working

**Comment by clinton-hall** [comment]
yes, avconv (avprobe) is supported. Give it a go...

Also, if you send through the log of a transcode event, I can look to see if this can be easily stream-lined to work more efficiently.

As a suggestion:
```
[Transcoder]
    getSubs = 1
    subLanguages = eng
    transcode = 1
    duplicate = 0
    concat = 1
    ignoreExtensions = 
    outputFastStart = 0
    outputQualityPercent = 0
    outputVideoPath = ""
    processOutput = 1
    audioLanguage = eng
    allAudioLanguages =1
    allSubLanguages = 1
    embedSubs = 1
    burnInSubtitle = 0
    extractSubs = 0
    externalSubDir = ""
    hwAccel = 0
    generalOptions = -threads,14
    outputDefault = ""
    #### Define custom settings below.
    outputVideoExtension = .mp4
    outputVideoCodec = copy
    VideoCodecAllow =
    outputVideoPreset =
    outputVideoResolution =
    outputVideoFramerate =
    outputVideoBitrate =
    outputVideoCRF =
    outputVideoLevel =
    outputAudioCodec = copy
    AudioCodecAllow =
    outputAudioChannels =
    outputAudioBitrate =
    outputAudioTrack2Codec = copy
    AudioCodec2Allow =
    outputAudioTrack2Channels =
    outputAudioTrack2Bitrate =
    outputAudioOtherCodec = copy
    AudioOtherCodecAllow =
    outputAudioOtherChannels =
    outputAudioOtherBitrate =
    outputSubtitleCodec = mov_text
```

**Comment by clinton-hall** [comment]
for the comment on CP, I assume you have looked at the Kodi metadata options in CP?

**Comment by brinkdogg** [comment]
DAMN YOU!, (on the avconv)! ;)  

 I have and THANK YOU so much for all your help!

**Comment by brinkdogg** [comment]
Sorry on last question, how would I use AVCONV in the script? Example if you don't mind and I'm sorry for being a pain in the ass.

**Comment by clinton-hall** [comment]
ok.. a couple of things here... the script looks for ffmpeg first in specified path (or the system path) and then looks for avconv...
So you need to have only avconv available in the searched location.

What I suggest is you use
```
[General]
    ffmpeg_path = <path to avconv>
```
where `path to avconv> is the location of the avconv binaries

e.g. `ffmpeg_path = /usr/local/bin`

Now the issue is if both ffmpeg and avconv are in the same location...
then you will need to create a sym-link in another location

e.g. 
create a directory /home/avconv
then 
```
ln -sf /usr/local/bin/avconv /home/avconv/avconv
ln -sf /usr/local/bin/avprobe /home/avconv/avprobe
```
and set `ffmpeg_path =/home/avconv` (or whereever you have linked the avconv files to.

I hope this makes sense...

**Comment by brinkdogg** [comment]
Makes complete sense! Thanks again and if I could I'd buy you a couple of beers.
