### ISSUE TITLE
Correct configuration of AutoProcessMedia.cfg for TorrenToMedia

### ISSUE THREAD

**Issue by littlejeem** [clinton-hall/nzbToMedia#1181]
Hello Folks

This is a question /request for help not a bug. I'm having some issues getting the script to run as I am expecting for  SickRage.

My set up is a Raspberry Pi 2, running debian jessie. I'm running fully updated versions of SickRage and CouchPotato with Transmission.

I have two tv series that I'm asking TorrentToMedia to process which have failed, triggered by transmission.

I link the nzbtomedia.log that I generated from a manual run on test location with extra logging options turned on: `http://pastebin.com/BJkkXLSb`

I wondered is someone would be willing to take a look and point me in right direction as to how to resolve.

The main issues seem to come between line 187-193

`2017-01-31 21:34:04 ERROR   ::MAIN: Failed to add directories from {} for post-processing: 'Section' object has no attribute 'endswith'`

My autoProcessMedia.cfg is here:
`http://pastebin.com/y21yUryk`

**Comment by clinton-hall** [comment]
Please update to the latest version of nzbToMedia. there were fixes made to handle the new Sickrage PP queue.

**Comment by littlejeem** [comment]
Thanks clinton-hall, I'll close this query
