### ISSUE TITLE
Exception TypeError: "'NoneType' object is not callable"

### ISSUE THREAD

**Issue by sinterlkaas** [clinton-hall/nzbToMedia#1184]
nzbtomedia fails to run.

> [00:29:24] [INFO]::MAIN: Loading config from [/home/X/nzbToMedia/autoProcessMedia.cfg]
> [00:29:24] [INFO]::MAIN: Checking database structure...
> [00:29:24] [INFO]::MAIN: Checking if git needs an update
> [00:29:24] [INFO]::MAIN: No update needed
> [00:29:24] [INFO]::MAIN: nzbToMedia Version:80c8ad58523ab99825c02f3855f9bd3dc9945d57 Branch:master (Linux 3.16.0-4-amd64)
> [00:29:24] [INFO]::MAIN: #########################################################
> [00:29:24] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
> [00:29:24] [INFO]::MAIN: #########################################################
> [00:29:24] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
> [00:29:24] [INFO]::MAIN: Searching /mnt/Storage/Downloads/complete/movies/ for mediafiles to post-process ...
> [00:29:24] [INFO]::MAIN: Searching /mnt/Storage/Downloads/complete/movies for mediafiles to post-process ...
> [00:29:24] [INFO]::MAIN: Starting manual run for CouchPotato:movies - Folder: /mnt/Storage/Downloads/complete/movies/Ted.2.2015.720p.BluRay.DTS.x264-iFT
> [00:29:24] [INFO]::MAIN: Checking database for download info for Ted.2.2015.720p.BluRay.DTS.x264-iFT ...
> [00:29:24] [INFO]::MAIN: Unable to locate download info for Ted.2.2015.720p.BluRay.DTS.x264-iFT, continuing to try and process this release ...
> [00:29:24] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
> [00:29:24] [INFO]::MAIN: Calling CouchPotato:movies to post-process:Ted.2.2015.720p.BluRay.DTS.x264-iFT
> [00:29:24] [INFO]::MAIN: Attemping imdbID lookup for Ted.2.2015.720p.BluRay.DTS.x264-iFT
> [00:29:24] [INFO]::MAIN: Searching folder and file names for imdbID ...
> [00:29:24] [INFO]::MAIN: Searching IMDB for imdbID ...
> Traceback (most recent call last):
>   File "./nzbToMedia.py", line 817, in <module>
>     exit(main(sys.argv))
>   File "./nzbToMedia.py", line 792, in main
>     download_id=download_id or None, inputCategory=subsection)
>   File "./nzbToMedia.py", line 618, in process
>     inputCategory, failureLink)
>   File "/home/X/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 131, in process
>     imdbid = find_imdbid(dirName, inputName)
>   File "/home/X/nzbToMedia/core/nzbToMediaUtil.py", line 1072, in find_imdbid
>     results = r.json()
>   File "/home/X/nzbToMedia/libs/requests/models.py", line 805, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
> Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7f36a8ad2110>> ignored
>

**Comment by clinton-hall** [comment]
Does this happen for every post-process event?
The issue here is that it appears to not receive data from imdb when searching for the imdb id.

**Comment by sinterlkaas** [comment]
Yes it happens to a few others aswel.. The problem is that it stops completely after this exception

so none of the items is post-processed

**Comment by clinton-hall** [comment]
Try updating to latest Nightly build... 
The OMDB api server is down and causes issues looking up the movie.

**Comment by Enf0** [comment]
I'm also experiencing this issue and have updated to latest nightly build.

`Traceback (most recent call last):
  File "nzbToMedia.py", line 817, in <module>
    exit(main(sys.argv))
  File "nzbToMedia.py", line 769, in main
    clientAgent = text_type(core.DOWNLOADINFO[0].get('client_agent', 'manual'))
AttributeError: 'sqlite3.Row' object has no attribute 'get'
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7feb78eb7990>> ignored`


> \# git status
> On branch nightly
> Your branch is up-to-date with 'origin/nightly'.

**Comment by clinton-hall** [comment]
this appears to be an issue retrieving the download from the database. I am assuming this was a manual call of nzbToMedia and not trigger from your downloader?
you may want to delete `nzbToMedia/nzbtomedia.db` then try again.

**Comment by Enf0** [comment]
That seems to have done the trick @clinton-hall, thanks.
