### ISSUE TITLE
Reduce dependency on OMDB api?

### ISSUE THREAD

**Issue by theCheek** [clinton-hall/nzbToMedia#1185]
Looks like omdb got ddoséd last night:
Attention Users!

> 02/04/17 - Error 503/The service is unavailable! I KNOW! I've been working throughout the night trying to track down the bot/script/attack causing this issue, it's not normal activity as someone decided it was a good idea to open over 50+ concurrent connections and spam 300+ million requests an hour. Unfortunately the majority of features available to me to prevent these sorts of attacks are browser security checks (which are currently enabled so you can read this message) this is only temporary as I'm aware it breaks the majority of API implementations. Sorry for the inconvenience and I'll be working nonstop to get this resolved ASAP.

This means that when nzbtomedia extracts/hardlinks from a downloader to its temporary directory, it seems to get stuck during the identification process because it can't get through to omdb.

Is there a way to remove this dependency perhaps by using themoviedatabase or something?

**Comment by clinton-hall** [comment]
Added a catch to prevent the errors. I'll need to investigate other sources to use...
