### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by romprod** [clinton-hall/nzbToMedia#1187]
Is it possible to spit the output of everything to a single log file somewhere?

**Comment by clinton-hall** [comment]
in nzbToMedia/logs/nzbtomedia.log

**Comment by philsynek** [comment]
Hi!
Is there a special way to activate this? I can't seem to get nzbToMedia running with SickRage, even though I followed the [instructions](https://github.com/SickRage/SickRage/wiki/NZBtoMedia). Now I would like to see the logging, because sabnzbd.log simply outputs "INFO::[newsunpack:184] Running external script" and SickRage  shows only "Snatched".

**Comment by 0HFgX1pM8hUbvsCpAl3D** [comment]
nzbToMedia/logs is not generated and the 'nzbtomedia.log' is not mentioned in any of the python scripts.

**Comment by 0HFgX1pM8hUbvsCpAl3D** [comment]
It's supposed to be created when you run 'setup.py build'
This doesn't seem to be mentioned in the instructions and doesn't actually work on my system.

**Comment by clinton-hall** [comment]
The log is not created when you run setup.py, the log is created/updated when the TorrentToMedia/nzbToMedia script runs.

if the log is not created, it is most probably due to the user that is calling the script not having write permissions in the nzbToMedia directory and therefore unable to create the logs directory or create the nzbToMedia.log file

**Comment by 0HFgX1pM8hUbvsCpAl3D** [comment]
I tried running automatically from sabnzbdplus to no avail. Running the same command manually returns "syntax error near unexpected token".

**Comment by clinton-hall** [comment]
What command are you running?
Hiw did you install the script. This almost looks like corrupt files.

**Comment by 0HFgX1pM8hUbvsCpAl3D** [comment]
/opt/nzbToMedia/nzbToSickBeard.py(<path to folder>, <path to nzb>, <folder name>, , tv, alt.binaries.british.drama, -1, )

The first three variables may be slightly different, I don't know what cmdline options it is supposed to take. That command is what sabnzbdplus runs.

**Comment by clinton-hall** [comment]
No brackets, no commas.

Try 

/opt/nzbToMedia/nzbToSickBeard.py

To start with to see if it creates the logs.

Then try

/opt/nzbToMedia/nzbToSickBeard.py <path to folder> <path to nzb> <folder name> "" tv alt.binaries.british.drama -1

**Comment by 0HFgX1pM8hUbvsCpAl3D** [comment]
I was able to get it to work commenting variables out in nzbToSickBeard.py but am running into the syntax error again. It fails due to a space in the path and when I add single quotes I can "unexpected token".

**Comment by 0HFgX1pM8hUbvsCpAl3D** [comment]
Commenting out variables set in nzbToSickBeard.py fixed that issue. Now I'm back to dealing with the "syntax error near unexpected token".
More specifically, the string is formatted like this:
`/opt/nzbToMedia/nzbToSickBeard.py(/home/xxxxxx/Media/TV/Show Name/Season 4/downloaded_episode-name.1, nzbfile.nzb, show_folder, , tv, alt.binaries.british.drama, -1, )`
Putting either single or double quotes works to get rid of the syntax error on the space in the path name but brings about another.

**Comment by clinton-hall** [comment]
ok, no need to set variables in the script... in fact you should not edit any files in nzbToMedia... you only create a copy of autoProcessMedia.cfg.spec -> autoProcessMedia.cfg then edit that file.

when calling the script, you don't pass the variables inside of brackets `()`

```
/opt/nzbToMedia/nzbToSickBeard.py '/home/xxxxxx/Media/TV/Show Name/Season 4/downloaded_episode-name.1' 'nzbfile.nzb' 'show_folder' '', 'tv, alt.binaries.british.drama' '-1' ''
```

**Comment by 0HFgX1pM8hUbvsCpAl3D** [comment]
Ah, any idea why sabnzbd is adding the brackets?

**Comment by 0HFgX1pM8hUbvsCpAl3D** [comment]
Got it working. Thank you!

**Comment by clinton-hall** [comment]
Glad to hear. Let me know if anything else comes up.
