### ISSUE TITLE
nzbToCouchPotato not renaming file with right file extension

### ISSUE THREAD

**Issue by yp6128** [clinton-hall/nzbToMedia#1194]
Hello,

I have a little issue, sometime after downloading a file, the file is processed but it loose or get rename with not readable file extension. I can rename it manually to .avi or .mkv but it's not working with the script :-(

Is there someone who can help ? 

in the log I have .cp, how to set it to .mkv or .avi 
[lognzbget.txt](https://github.com/clinton-hall/nzbToMedia/files/769543/lognzbget.txt)

**Comment by clinton-hall** [comment]
This is not an issue with nzbToMedia, but with your CouchPotato renamer settings.
According to the log, the folder is named .cp(ttxxxx) but the actual file is crealy a playable .mkv.

In CouchPotato, settings, renamer please make sure `filename` ends in `.<ext>`
with out this, CP will rename the movie without the extension.
