### ISSUE TITLE
Failed Download Handling

### ISSUE THREAD

**Issue by romprod** [clinton-hall/nzbToMedia#1195]
I have the following error after a failed download.

SickBeard does not support failed downloads!

> Branch: master
> Commit: 5ba0a5263267c8f7fc568325de523ef869dccf7f
> Version: v2017.02.12-2
> Database Version: 44.0

Log below.

> [11:10:39] [DEBUG]::MAIN: Options passed into nzbToMedia ['C:\\Programs\\nzbToMedia\\nzbToSickBeard.py', 'C:\\Users\\Administrator\\Downloads\\incomplete\\show', 'show', '', 'tv', 'alt.binaries.movies', '3']
> 
> [11:10:39] [INFO]::MAIN: Script triggered from SABnzbd
> 
> [11:10:39] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
> 
> [11:10:39] [DEBUG]::MAIN: Found nzoid: SABnzbd_nzo_pkknw9
> 
> [11:10:39] [DEBUG]::MAIN: Adding NZB download info for directory C:\Users\Administrator\Downloads\incomplete\show to database
> 
> [11:10:39] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'sabnzbd', 736373, u'SABnzbd_nzo_pkknw9', u'SABnzbd_nzo_pkknw9', u'show.nzb', u'C:\\Users\\Administrator\\Downloads\\incomplete\\show']
> 
>  [11:10:39] [DB]::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (status, client_agent, last_update, input_id, input_hash, input_name, input_directory) VALUES (?, ?, ?, ?, ?, ?, ?) with args [0, u'sabnzbd', 736373, u'SABnzbd_nzo_pkknw9', u'SABnzbd_nzo_pkknw9', u'show', u'C:\\Users\\Administrator\\Downloads\\incomplete\\show']
> 
> [11:10:39] [INFO]::MAIN: Auto-detected SECTION:SickBeard
> 
> [11:10:39] [DEBUG]::MAIN: Checking for archives to extract in directory: C:\Users\Administrator\Downloads\incomplete\show
> 
> [11:10:39] [INFO]::MAIN: Calling SickBeard:tv to post-process:show.nzb
> 
> [11:10:39] [DEBUG]::SERVER: Attempting to connect to server at http://192.168.0.10:65500
> 
> [11:10:39] [DEBUG]::SERVER: Server responded at http://192.168.0.10:65500
> 
> [11:10:40] [INFO]::MAIN: Attempting to auto-detect tv fork
> 
> [11:10:40] [INFO]::MAIN: SickBeard:tv fork auto-detection found custom params {'proc_dir': None, 'delete_on': None, 'process_method': None, 'force': None, 'force_next': None}
> 
> [11:10:40] [INFO]::MAIN: SickBeard:tv fork set to custom
> 
> [11:10:40] [WARNING]::SICKBEARD: No media files found in directory C:\Users\Administrator\Downloads\incomplete\show. Processing this as a failed download
> 
> [11:10:40] [POSTPROCESS]::SICKBEARD: FAILED: The download failed. custom branch does not handle failed downloads. Nothing to process
> 
> [11:10:40] [ERROR]::MAIN: A problem was reported in the C:\Programs\nzbToMedia\nzbToSickBeard.py script.
>  SickBeard: Failed to post-process. SickBeard does not support failed downloads!

**Comment by clinton-hall** [comment]
So what version of SickBeard/SickRage do you have?
If your version does support failed handling, you need to enable this option in SickBeard/SickRage.

Search settings, episode search, `Use Failed Downloads`??
