### ISSUE TITLE
Git is not aware of updates.

### ISSUE THREAD

**Issue by IngoVals** [clinton-hall/nzbToMedia#1197]
I have NzbToMedia set up on my synology, inside my Sabnzbd install there. I'm had some issue regarding Sickrage new queue systems and so I re-pulledeverything from GIT a few days ago. So my head for nightly is at [868c8c3](https://github.com/clinton-hall/nzbToMedia/commit/868c8c36bfa9a1ebfe395851bd82bcd2ca93d9f7). I'm trying to fix a issue I'm having similar to #1191 so when I SCP into the repo it seems that my codebase is updated to latest changes but GIT is not aware and handles these changes as local changes I need to commit.

How does the auto-update happen?

**Comment by clinton-hall** [comment]
I'm not sure what you are saying is happening? Have you made manual changes to the code?

The way the updater works is it performs a git pull.

Having a guess, likely issues would arise if the code is clones, or updated/pulled by one user, and then nzbToMedia runs as another user and tries to update?

**Comment by IngoVals** [comment]
It seems the git pull fails for some reason according to logs. Likely permission issues. But the code changes are still present, like instead of pulling and moving the HEAD reference of git, the changes are added to the codebase totally like I had made them manually (which I haven't).

My guess is that it isn't a problem with this library, but perhaps with users and permissions in Synology. I'll have to investigate more.

**Comment by clinton-hall** [comment]
That sounds to me like nzbToMedia has permissions in the main directoru, but not the (hidden) `.git` directory... Check the permissions on this directory.
