### ISSUE TITLE
Trim the API key field user input before saving it

### ISSUE THREAD

**Issue by xosofox** [clinton-hall/nzbToMedia#1199]
tl;dr: trim the API key user input before storing it to remove whitespace

I just figured out why my config failed... I found the HTML of couchppotatoes login form in my nzbtomedia.log so I assumed my API key was wrong - but it wasn't... so I thought...

Took me some time to notice that I copy&pasted it with additional whitespace which created the error.

So, my request is to do a trim (or whatever python calls it) to remove whitespaces on the input before storing it in the config

**Comment by clinton-hall** [comment]
Was this entered in the NZBGet web ui, or did you enter it directly in the autoProcessMedia.cfg?

I'll see what I can do for this.

**Comment by Xosofox** [comment]
Honestly, I don't rememer. Could be I edited the file manually...

However, it obviously IS possible to enter

[SPACE][SPACE][SPACE]mysecretapikey

into the field and it would be saved like that, leading to failing AUTH
