### ISSUE TITLE
Unable to process media downloaded by SABnzbd

### ISSUE THREAD

**Issue by josurr** [clinton-hall/nzbToMedia#1201]
The following is produced by SAB automatically calling of nzbToSickbeard.py (also occurs for manual runs with python 2.7 via command line):

`Traceback (most recent call last):
  File "nzbToSickBeard.py", line 257, in <module>
    import nzbToMedia
  File "D:\scripts\nzbToMedia\nzbToMedia.py", line 520, in <module>
    import core
  File "D:\scripts\nzbToMedia\core\__init__.py", line 35, in <module>
    from core.autoProcess.autoProcessComics import autoProcessComics
  File "D:\scripts\nzbToMedia\core\autoProcess\autoProcessComics.py", line 7, in
 <module>
    from core.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
  File "D:\scripts\nzbToMedia\core\nzbToMediaUtil.py", line 22, in <module>
    from core.linktastic import linktastic
  File "D:\scripts\nzbToMedia\core\linktastic\linktastic.py", line 31, in <module>
    info.dwFlags |= subprocess.STARTF_USESHOWWINDOW
AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'`

This occurs after manually pulling down the latest nightly

**Comment by clinton-hall** [comment]
So was this working on master, or previous nightly?

Do you have python AND pywin installed?

**Comment by josurr** [comment]
It was working on Friday with the master that was last pulled down via the script on Friday 2/17/2017.

On 2/18/2017, my machine crashed and I rebuilt it in Win7 Pro SP1 x64.

Please close the issue, I had installed both Python 2.7 and pywin32 x64 versions. After removing both of those and installing the x86 versions, the scripts are functioning normally again.

Thanks for all your work!
