### ISSUE TITLE
enhancement : config verification check

### ISSUE THREAD

**Issue by jzahraoui** [clinton-hall/nzbToMedia#1204]
is it possible to run a kind of test to verify the current parameters. something that make a nzb download and a torrent download and check if the files are placed where is expected for every enabled client( sickbead, couchpotato, headphones, etc.). 
it's very difficult to test every scenario by hand. this will be very helpful and make able to solve problems quickly and alone.

**Comment by clinton-hall** [comment]
Not easy. The biggest issue is CP and SickBeard etc will only rename valid media. In the case of SickBeard it needs to be a show that has been added etc...
Not sure how to start creating such a test...

**Comment by jzahraoui** [comment]
may be you can start by the easiest thing to do. if it's not possible to make a real test may be you can read the config files to check the configured paths ?
