### ISSUE TITLE
NZBget + Headphones + nzbToMedia : PP-Failure

### ISSUE THREAD

**Issue by thesatman** [clinton-hall/nzbToMedia#1206]
[LOG NZBget_artist-track-title.pdf](https://github.com/clinton-hall/nzbToMedia/files/797765/LOG.NZBget_artist-track-title.pdf)
[headphones-nzbTomedia-config.txt](https://github.com/clinton-hall/nzbToMedia/files/797741/headphones-nzbTomedia-config.txt)
[LOG nzbTomedia.txt](https://github.com/clinton-hall/nzbToMedia/files/797740/LOG.nzbTomedia.txt)

Hi

Not sure if this is the right place to ask, but since you know your way around the software blindfolded, I'll give it a go.

I have a working setup with NZBget v.18 on Win7, with CP, SR, and uTorrent. I just started testing this setup with Headphones. I have two scenarios where I have entered a search in Headphones, where in bothe cases the downloader does the job, but where it ends with a PP-FAILURE.

The first method was by searching for an album. The downloaded data was stored, and I did not make a big fuzz about the PP-FAILURE since i wanted to manually check all meta data anyway.

The second method is what I would like to share here. What I wanted to do was to download singles, not albums. I used a nifty little script called billhead.py. It scrapes billboard.com for albums, and for singles if you edit the py file. It then forwards the info to Headphones. Here you'll see the titles listed as Singles, not albums. Headphones goes searching for the singles and send them to NZBget. So far so good...

I'm only looking at the NZB section here. Torrent will be next on my list, just to keep this topic uncluttered.

NZBget log, nzbtoMedia config section for Headphones and nzbToMedia log is attached. 

Since i am uncertain about what nzbToMedia file NZBget is using I went into the NZBget settings. i copied the original nzbToMedia file from the Clinton GIT download to the NZBget script folder. then under settings > Headphones I edited the localhost + port and entered the API key. Did a post-process re-run of the file, and got other results:

INFO	Thu Feb 23 2017 20:36:01	Collection Artist - track_name added to history
ERROR	Thu Feb 23 2017 20:36:00	Post-process-script nzbToMedia.py for Artist - track_name
INFO	Thu Feb 23 2017 20:36:00	nzbToMedia: HeadPhones: Failed to post-process - No change in wanted status!
INFO	Thu Feb 23 2017 20:36:00	nzbToMedia: [20:36:00] [ERROR]::MAIN: A problem was reported in the C:\nzbToMedia-GIT\nzbToMedia\nzbToMedia.py script.
INFO	Thu Feb 23 2017 20:36:00	nzbToMedia: [20:36:00] [WARNING]::HEADPHONES: The music album does not appear to have changed status after 2 minutes. Please check your Logs
INFO	Thu Feb 23 2017 20:35:40	nzbToMedia: [20:35:40] [DEBUG]::MAIN: Opening URL: http://localhost:5060/api with PARAMS: {'cmd': 'getHistory', 'apikey': 'my_key'}
INFO	Thu Feb 23 2017 20:35:40	nzbToMedia: [20:35:40] [DEBUG]::MAIN: Attempting to get current status for release:Artist - track_name
INFO	Thu Feb 23 2017 20:35:20	nzbToMedia: [20:35:20] [DEBUG]::MAIN: Opening URL: http://localhost:5060/api with PARAMS: {'cmd': 'getHistory', 'apikey': 'my_key'}
INFO	Thu Feb 23 2017 20:35:20	nzbToMedia: [20:35:20] [DEBUG]::MAIN: Attempting to get current status for release:Artist - track_name
INFO	Thu Feb 23 2017 20:35:00	nzbToMedia: [20:35:00] [DEBUG]::MAIN: Opening URL: http://localhost:5060/api with PARAMS: {'cmd': 'getHistory', 'apikey': 'my_key'}

I just don't get it... what am i missing??

**Comment by clinton-hall** [comment]
"message": "API not enabled", 

Have you enabled the api in HeadPhones?

**Comment by thesatman** [comment]
LOL... ! Yes that was the first thing I checked. But I guess it has
something to do with the fact that I only had the key inserted in one of
the two places where it can be entered. As you can read from in comments
I got a different result when playing around with the key.

For me to better understand what is happening, I would like to know why
there are 2 ways / pointers to the nzbToMedia.py file, and what to use.
Before I started to use NZBget, I used sabnzbd. Sabnzbd had no entries
for special commands, no other then that all post processing was done by
the files located in my C:\nzbToMedia-GIT\nzbToMedia folder. So that was
all I had to maintain. CP, SR, utorrent (run command after download) and
Sabnzbd had only one point of reference : "C:\nzbToMedia-GIT\nzbToMedia".

In NZBget it gets a little confusing.
Under settings / paths I have ScriptsDir : C:\nzbToMedia-GIT\nzbToMedia
Under settings / Extention Scripts I have FailureLink.py, nzbToMedia.py
Under settings / NZBTOMEDIA it gets confusing. For example, I have a
"movie" cpsCategory, but no CP key, yet all seems to work fine. Now for
hpCategory and stuff I filled out all information. Have have done the
same in the original nzbtoMedia.cfg file. Do I need both? What software
is using which config file. Can it be that only utorrent is using the 
C:\nzbToMedia-GIT\nzbToMedia config file, or ??

If I understand what is happening here, it maybe will be easier to
analize the next question, but I'll take one step at the time. I'll be
looking forward to your reply.

Many thanks in advance :)

**Comment by clinton-hall** [comment]
When using other downloaders, all config is in the .cfg
When using NZBGet, all config is set in the web UI (and on execution this is written into the cfg) any advanced config not in the web UI can be set in the .cfg

If you call nzbToMedia.py you need to enter the hpCategory, hpHost, hpPort, and hpApi. If you call nzbToHeadPhones.py for the music category, you need to configure the webUI for this script to include hpHost, hpPort, and hpApi

**Comment by thesatman** [comment]
Thank you for the clarification :). Now that I have checked the HP info, I still can't get the mp3 from the NZBget download folder to my Plex music folder. This is what i get in the NZBget log after I do a "post-process again" with nzbToMedia.

INFO	Sat Feb 25 2017 17:03:33	Collection xxxxxxARTIST-ALBUMxxxxxxxx added to history
ERROR	Sat Feb 25 2017 17:03:33	Post-process-script nzbToMedia.py for xxxxxxARTIST-ALBUMxxxxxxxx failed
INFO	Sat Feb 25 2017 17:03:33	nzbToMedia: HeadPhones: Failed to post-process - No change in wanted status!
INFO	Sat Feb 25 2017 17:03:32	nzbToMedia: [17:03:32] [ERROR]::MAIN: A problem was reported in the C:\nzbToMedia-GIT\nzbToMedia\nzbToMedia.py script.
INFO	Sat Feb 25 2017 17:03:32	nzbToMedia: [17:03:32] [WARNING]::HEADPHONES: The music album does not appear to have changed status after 2 minutes. Please check your Logs
INFO	Sat Feb 25 2017 17:03:11	nzbToMedia: [17:03:11] [DEBUG]::MAIN: Opening URL: http://localhost:5060/api with PARAMS: {'cmd': 'getHistory', 'apikey': 'here-is-my-api-key'}
INFO	Sat Feb 25 2017 17:03:11	nzbToMedia: [17:03:11] [DEBUG]::MAIN: Attempting to get current status for release:xxxxxxARTIST-ALBUMxxxxxxxx
INFO	Sat Feb 25 2017 17:02:50	nzbToMedia: [17:02:50] [DEBUG]::MAIN: Opening URL: http://localhost:5060/api with PARAMS: {'cmd': 'getHistory', 'apikey': 'here-is-my-api-key'}
INFO	Sat Feb 25 2017 17:02:50	nzbToMedia: [17:02:50] [DEBUG]::MAIN: Attempting to get current status for release:xxxxxxARTIST-ALBUMxxxxxxxx
INFO	Sat Feb 25 2017 17:02:29	nzbToMedia: [17:02:29] [DEBUG]::MAIN: Opening URL: http://localhost:5060/api with PARAMS: {'cmd': 'getHistory', 'apikey': 'here-is-my-api-key'}

The Headphones log tells me this:

2017-02-25 17:03:12	INFO	Recieved API command: getHistory
2017-02-25 17:02:51	INFO	Recieved API command: getHistory
2017-02-25 17:02:30	INFO	Recieved API command: getHistory
2017-02-25 17:02:09	INFO	Recieved API command: getHistory
2017-02-25 17:01:48	INFO	Recieved API command: getHistory
2017-02-25 17:01:27	INFO	Recieved API command: getHistory
2017-02-25 17:01:26	INFO	Found no folders to process. Aborting.
2017-02-25 17:01:26	WARNING	Directory W:\ProgramData\NZBGet\complete\Music does not exist. Skipping
2017-02-25 17:01:26	INFO	Force checking download folder for completed downloads
2017-02-25 17:01:26	INFO	Recieved API command: forceProcess

The warning is strange. The W drive with the folder mentioned is accessible from file explorer. This is a network mapped folder, located on a NAS. I retried post-processing. Same issue.

Is there any information missing in the cfg file?

**Comment by thesatman** [comment]
Found it !! Headphones has a problem with networked drives. Had to change W:\ProgramData\....etc to \\XPENDISKSTATION\NAS-data2\ProgramData\NZBGet :). So all clear with nzbtoMedia. 

Thanks for listening !!

**Comment by clinton-hall** [comment]
All good. Glad you found it...
Yes, networking and shared drives can make things very interesting, and users will always find combinations of software that don't handle the shares as expected/wanted...
