### ISSUE TITLE
postprocessing failing since yesterday

### ISSUE THREAD

**Issue by jadm557** [clinton-hall/nzbToMedia#1209]
Since yesterday all my postprocessing tasks failed (sickrage setup)
I did upgrade to the latest version of sabnzbd (1.2.1). No idea if that was the cause. 

-I upgraded to the latest version of nzbtomedia > still the same error.

The error I am getting seems to be caused by the system not detecting a mediafile in the folder. I can confirm that the file is actually there just not being detected. 

I think this is where it goes wrong (logs)
WARNING ::SICKBEARD: No media files found in directory \\?\K:\ServerFolders\Usenet\Complete\tv\Stephen.Colbert.2017.02.24.Allison.Williams.720p.WEB.h264-HEAT.1. Processing this as a failed download
Afterwards the system processes the download as failed and removes the folder and the file.

**Comment by clinton-hall** [comment]
Please update to latest nightly version of nzbToMedia.
Until I have a few features tested (and merge up to master) only the nightly branch supports the long file paths used by the latest SABnzbd.

**Comment by jadm557** [comment]
I changed to the nightly build. It works fine now. Thx
