### ISSUE TITLE
NZBtoMEdia Illegal Instruction

### ISSUE THREAD

**Issue by fuuss** [clinton-hall/nzbToMedia#1211]
Hello 

I have a problem getting this script working. 
I have NZBGET running on the qnap Beta 64 bit , everything is working as it should except the script , 

I change the $Path to get it working , launching Manual the script I get Illegal instruction. I don't se any further log , where can I change the log level in NZBGET and where can I see those logs , What does this message means

Thank in advance

**Comment by clinton-hall** [comment]
How are you launching the script manually?
NZBget Logging is changed through NZBGet web ui, settings, logging. You then see the logging under "messages"

**Comment by fuuss** [comment]
As I had some isues with the $Path and Python 27 , I was launching <pathtopython>python2  /<pathscript>/nzbToMedia.py , firt I got a problem that he doesn't find a library so I adapted the python path and now I get Illegal instruction , nothing more , In NZGGET I get terminated with unknown status .  Very strange isn't it

**Comment by clinton-hall** [comment]
what python path did you add, and how? is this a valid pythin path for that version of Python?
It sounds like this python version is broken/missing required libs.

**Comment by fuuss** [comment]
Ok so here are the details
>which python 
>/usr/local/bin/python

>python2.7 /share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia.py  
or 
>python2 /share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia.py  
give the same result

  File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/core/autoProcess/autoProcessComics.py", line 7, in <module>
    from core.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
  File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/core/nzbToMediaUtil.py", line 19, in <module>
    import subliminal
  File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/libs/subliminal/__init__.py", line 16, in <module>
    from .providers import Provider
  File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/libs/subliminal/providers/__init__.py", line 5, in <module>
    from six.moves.xmlrpc_client import SafeTransport
  File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/libs/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/libs/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/libs/six.py", line 82, in _import_module
    __import__(name)
ImportError: No module named xmlrpclib
[~] # 

So I downloaded QPython2 qpkg to my Qnap

>/share/CACHEDEV1_DATA/.qpkg/QPython2/bin/python2.7 /share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia.py

And there I get result 

Illegal Instruction

**Comment by clinton-hall** [comment]
Ok, search in QPython2 to see if the file xmlrpclib.py exists. if so, try copying this in to the Python package directory and try running 
`python2 /share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia.py`

**Comment by fuuss** [comment]
Ok that seems to work , but still I get some error 

So now if I manually launch the script i get
script completed successfully

On the other hand in NZBGET i still get 
Post-process-script nzbToCouchPotato.py for I don't Care 2014 German DL 720p BluRay x264_.cp(tt0000001) failed (terminated with unknown status)

**Comment by clinton-hall** [comment]
Looks like the PATH in NZBGet is causing another instance of python2 to be called?

**Comment by fuuss** [comment]
Yes it seems you are right I have no clue what Path NZBGET use but I could change it in the Variable ShellOverride=.py=/share/PATH/python2.7 in the nzbget.conf

This might help someone later


Thank you very much for the help even if this was more a NZBGET problem than your script.

**Comment by clinton-hall** [comment]
All good... the hardest part is dealing with compatibility... particularly on embedded systems without the full compiler libraries etc.

**Comment by clinton-hall** [comment]
Thanks for posting the ShellOverride feature... I had never noticed this one (like most things, we use what we need and ignore the rest).
Not surprised though: @hugbug is damn efficient. He always adds features that I'll someday need (before I even know that I will need them).

**Comment by kpt-yleviavant** [comment]
Hi,
Same problem on my QNAP (ARM).

I’ve just installed python2.7 from the QNAP App Center and added in NZBGet conf under ShellOverride  : 
`.py=/share/MD0_DATA/.qpkg/Python/bin/python2.7`

Everything works like charm !

Thanks @fuuss and @clinton-hall for your great job

**Comment by YoannLeViavant** [comment]
Hi,
Same problem on my QNAP (ARM).

I’ve just installed python2.7 from the QNAP App Center and added in NZBGet conf under ShellOverride  : 
`.py=/share/MD0_DATA/.qpkg/Python/bin/python2.7`

Everything works like charm !

Thanks @fuuss and @clinton-hall for your great job
