### ISSUE TITLE
Request - Filter for Country of Origin

### ISSUE THREAD

**Issue by koshia** [clinton-hall/nzbToMedia#1217]
I tried filtering out genres, keywords, etc.. using the built in ignore and preferred options but am still getting a lot of automated downloads of foreign, international, india movies.  Can we add a filter for filtering preferred country of origin or ignore.  This option seems to be tracked by IMDB?

**Comment by clinton-hall** [comment]
Is this in nzbToMedia, or CouchPotato?
If CouchPotato, you have come to the wrong place. If nzbToMedia, this script only gets applied to movies after they have finished downloading.

**Comment by koshia** [comment]
**** it, I searched your name to find the CP issues section, found your post, and apparently my brain forgot what it was supposed to be doing.  Sorry, moving request to tweet as CP issues area was taken down.

**Comment by clinton-hall** [comment]
No worries... post on CP forums.
Just wanted to make sure I wasn't missing something for nzbToMedia, but I couldn't see how I could do anything here.
