### ISSUE TITLE
Sonarr Failed Download Handling not working

### ISSUE THREAD

**Issue by imatt9959** [clinton-hall/nzbToMedia#1218]
Hi,

I've been having some issues with the Sonarr handling with nzbtodrone.

Pretty much whenever nzbtomedia fails a download and sends it back to Sonarr, the failed download handling never picks it up. However whenever SAB fails the download such as aborting the download because its knows its unable to complete, Sonarr's failed download handling works fine.

I think this might be because when SAB fails it for that it doesn't run post processing.

 I've got it set to remove the download from history on failed download so I know its working then.

https://gyazo.com/f22f1976233f15a741ac23d9aac850ee

So pretty much whenever the download fails it like that it doesn't get sent back.

Here's the post processing log from SAB

> [00:19:11] [INFO]::MAIN: Loading config from [C:\Users\PVR\Desktop\USENET\nzbToMedia\autoProcessMedia.cfg]
> [00:19:11] [INFO]::MAIN: Checking database structure...
> [00:19:11] [INFO]::MAIN: Checking if source needs an update
> [00:19:13] [INFO]::MAIN: No update needed
> [00:19:13] [INFO]::MAIN: nzbToMedia Version:80c8ad58523ab99825c02f3855f9bd3dc9945d57 Branch:master (Windows 2012Server)
> [00:19:13] [INFO]::MAIN: #########################################################
> [00:19:13] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
> [00:19:13] [INFO]::MAIN: #########################################################
> [00:19:13] [INFO]::MAIN: Script triggered from SABnzbd
> [00:19:15] [INFO]::MAIN: Auto-detected SECTION:NzbDrone
> [00:19:15] [INFO]::MAIN: Calling NzbDrone:sonarr to post-process:show.2016.S01E09.HDTV.x264-LOL.nzb
> [00:19:15] [INFO]::MAIN: Attempting to verify sonarr fork
> [00:19:16] [INFO]::MAIN: NzbDrone:sonarr fork set to default
> [00:19:16] [WARNING]::NZBDRONE: No media files found in directory C:\Users\PVR\Desktop\USENET\Downloads\complete\sonarr\MacGyver.2016.S01E09.HDTV.x264-LOL. Processing this as a failed download
> [00:19:16] [POSTPROCESS]::NZBDRONE: FAILED: The download failed. Sending failed download to default for CDH processing
> [00:19:16] [ERROR]::MAIN: A problem was reported in the C:\Users\PVR\Desktop\USENET\nzbToMedia\nzbToNzbDrone.py script.
> NzbDrone: Download Failed. Sending back to NzbDrone!

I'm pretty sure I have everything setup correctly, if I dont I'm not sure what else I can change to fix this.

Heres a screenshot of my Sonarr config

https://gyazo.com/3991b068107d50ea9dfeb99de44eb401

>   [[sonarr]]
>         enabled = 1
>         apikey = ***
>         host = localhost
>         port = 8989
>         username = ***
>         password = ***
>         web_root = /sonarr
>         ssl = 0
>         delete_failed = 1
>         Torrent_NoLink = 0
>         keep_archive = 0
>         extract = 0
>         nzbExtractionBy = Downloader
>         wait_for = 2
>         minSize = 0
>         delete_ignored = 0
>         remote_path = 0
>         watch_dir =  C:\Users\PVR\Desktop\USENET\Downloads\complete\sonarr

Also every nown and then the post process will say something completely different like "Nzbdrone: Complete Download Handling is enabled. Passing back to Nzbdrone!"

https://gyazo.com/84300f1068a68689c4134b0cb88e3a34

Thanks.

**Comment by clinton-hall** [comment]
> Also every nown and then the post process will say something completely different like "Nzbdrone: Complete Download Handling is enabled. Passing back to Nzbdrone!"

Ok, this shouldn't be an issue. this just means the renaming was completed while the script was running.... Check that these have been correctly renamed and identified by Sonarr.

For the issue of failed downloads not being processed, can you check Sonarr logs from the time the script was running, til about 10-15 minutes afterwards? Does it say anything about this finished download?

**Comment by imatt9959** [comment]
> Ok, this shouldn't be an issue. this just means the renaming was completed while the script was running.... Check that these have been correctly renamed and identified by Sonarr.

The renaming seems to be working fine when it does this :).

> 17-3-9 21:03:50.8|Info|NzbSearchService|Searching 1 indexers for [Veep : S05E08]
> 17-3-9 21:03:52.4|Info|DownloadDecisionMaker|Processing 13 releases
> 17-3-9 21:03:57.7|Info|Sabnzbd|Adding report [Veep.S05E08.Camp.David.720p.HBO.WEBRip.DD5.1.H.264-monkee] to the queue.
> 17-3-9 21:03:58.0|Info|DownloadService|Report sent to SABnzbd. Veep.S05E08.Camp.David.720p.HBO.WEBRip.DD5.1.H.264-monkee

> [21:09:22] [INFO]::MAIN: Loading config from [C:\Users\PVR\Desktop\USENET\nzbToMedia\autoProcessMedia.cfg]
> [21:09:22] [INFO]::MAIN: Checking database structure...
> [21:09:22] [INFO]::MAIN: Checking if source needs an update
> [21:09:24] [INFO]::MAIN: No update needed
> [21:09:24] [INFO]::MAIN: nzbToMedia Version:80c8ad58523ab99825c02f3855f9bd3dc9945d57 Branch:master (Windows 2012Server)
> [21:09:24] [INFO]::MAIN: #########################################################
> [21:09:24] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
> [21:09:24] [INFO]::MAIN: #########################################################
> [21:09:24] [INFO]::MAIN: Script triggered from SABnzbd
> [21:09:27] [INFO]::MAIN: Auto-detected SECTION:NzbDrone
> [21:09:27] [INFO]::MAIN: Calling NzbDrone:sonarr to post-process:Veep.S05E08.Camp.David.720p.HBO.WEBRip.DD5.1.H.264-monkee.nzb
> [21:09:27] [INFO]::MAIN: Attempting to verify sonarr fork
> [21:09:27] [INFO]::MAIN: NzbDrone:sonarr fork set to default
> [21:09:27] [WARNING]::NZBDRONE: No media files found in directory C:\Users\PVR\Desktop\USENET\Downloads\complete\sonarr\Veep.S05E08.Camp.David.720p.HBO.WEBRip.DD5.1.H.264-monkee.1. Processing this as a failed download
> [21:09:27] [POSTPROCESS]::NZBDRONE: FAILED: The download failed. Sending failed download to default for CDH processing
> [21:09:27] [ERROR]::MAIN: A problem was reported in the C:\Users\PVR\Desktop\USENET\nzbToMedia\nzbToNzbDrone.py script.
> NzbDrone: Download Failed. Sending back to NzbDrone!

So the logs from Sonarr don't actually seem to show much apart from the initial report getting sent to SAB

https://gyazo.com/e907821ee70bd2d19da0f2d8360c1a37

It seems it's actually getting marked as complete in SAB (Screenshot).

I'm running SAB 1.2.2 [555d841]
