### ISSUE TITLE
Transcoding and keeping multiple languages doesn't seem to work

### ISSUE THREAD

**Issue by JHurk** [clinton-hall/nzbToMedia#1219]
Been trying different settings for days, but can't seem to get things to work correct.

What I want;
Transcode all downloads (NZBget) to mp4/m4v with all languages that are downloaded.

What I get;
The files are transcoded, but only the 'audioLanguage' is in container. Even if I have the addAllAudioLanguages enabled. If I have that one enabled I do get a second audiostream as output, but this is also in the 'audioLanguage' but the format is AC3. So I have an English stream in aac and one Enlish stream in AC3. While I was hoping for one English stream and one Dutch stream.
In the download (.mkv) there is both an English and Dutch stream, so it should be available.

My transcode settings in the autoProcessMedia.cnf are:
[Transcoder]
    # getsubs. enable to download subtitles.
    getSubs = 0
    # subLanguages. create a list of languages in the order you want them in your subtitles. 
    subLanguages = dut
    # transcode. enable to use transcoder
    transcode = 1
    ###### duplicate =1 will create a new file. =0 will replace the original
    duplicate = 1
    # concat. joins cd1 cd2 etc into a single video.
    concat = 1
    # IgnoreExtensions is a comma-separated list of extensions that will not be transcoded.
    ignoreExtensions = ".m4v,.mp4"
    # outputFastStart. 1 will use -movflags + faststart. 0 will disable this from being used.
    outputFastStart = 0
    # outputQualityPercent. used as -q:a value. 0 will disable this from being used.
    outputQualityPercent = ""
    # outputVideoPath. Set path you want transcoded videos moved to. Leave blank to disable.
    outputVideoPath = ""
    # processOutput. 1 will send the outputVideoPath to SickBeard/CouchPotato. 0 will send original files.
    processOutput = 0
    # audioLanguage. set the 3 letter language code you want as your primary audio track.
    audioLanguage = dut
    # allAudioLanguages. 1 will keep all audio tracks (uses AudioCodec3) where available.
    allAudioLanguages = 1
    # allSubLanguages. 1 will keep all existing sub languages. 0 will discard those not in your list above.
    allSubLanguages = 0
    # embedSubs. 1 will embed external sub/srt subs into your video if this is supported.
    embedSubs = 0
    # burnInSubtitle. burns the default sub language into your video (needed for players that don't support subs)
    burnInSubtitle = 0
    # extractSubs. 1 will extract subs from the video file and save these as external srt files.
    extractSubs = 0
    # externalSubDir. set the directory where subs should be saved (if not the same directory as the video)
    externalSubDir = ""
    # hwAccel. 1 will set ffmpeg to enable hardware acceleration (this requires a recent ffmpeg)
    hwAccel = 0
    # generalOptions. Enter your additional ffmpeg options here with commas to separate each option/value (i.e replace spaces with commas).
    generalOptions = ""
    # outputDefault. Loads default configs for the selected device. The remaining options below are ignored.
    # If you want to use your own profile, leave this blank and set the remaining options below.
    # outputDefault profiles allowed: iPad, iPad-1080p, iPad-720p, Apple-TV2, iPod, iPhone, PS3, xbox, Roku-1080p, Roku-720p, Roku-480p, mkv, mp4-scene-release
    outputDefault = None
    #### Define custom settings below.
    outputVideoExtension = .m4v
    outputVideoCodec = libx264
    VideoCodecAllow = "libx264, h264, h.264, AVC, avc, mpeg4, msmpeg4, MPEG-4, mpeg2video"
    outputVideoPreset = ""
    outputVideoResolution = 1920:1080
    outputVideoFramerate = ""
    outputVideoBitrate = ""
    outputVideoCRF = 19
    outputVideoLevel = 3.1
    outputAudioCodec = aac
    AudioCodecAllow = libfaac
    outputAudioChannels = 2
    outputAudioBitrate = ""
    outputAudioTrack2Codec = ac3
    AudioCodec2Allow = ac3
    outputAudioTrack2Channels = 6
    outputAudioTrack2Bitrate = ""
    outputAudioOtherCodec = libmp3lame
    AudioOtherCodecAllow = ""
    outputAudioOtherChannels = 2
    outputAudioOtherBitrate = 128k
    outputSubtitleCodec = ""

I have tried iPad-1080 output settings, but this results in a '.mp4' with above issue.
The custom settings (outputDefault=None) gives me an error during PP.
Could you please help me with getting the settings right?

**Comment by clinton-hall** [comment]
Try the following, and then tweak to add settings as you want.
Note. For blank settings use `""` and for any non-blank value don'e have any `"`
I have set this to use .mp4 output (haven't tried .m4v output myself)
I have also set this to make both languages tracks `aac` note, you can add more codecs into `AudioCodecAllow ` and `AudioOtherCodecAllow` to just copy streams instead of transcoding (so long as they are codecs that are supported by .mp4 and your player)
```
outputVideoExtension = .mp4
outputVideoCodec = libx264
VideoCodecAllow = libx264,h264,h.264,AVC,avc,mpeg4,msmpeg4,MPEG-4
outputVideoPreset = ""
outputVideoResolution = ""
outputVideoFramerate = ""
outputVideoBitrate = ""
outputVideoCRF = ""
outputVideoLevel = ""
outputAudioCodec = aac
AudioCodecAllow = libfaac
outputAudioChannels = ""
outputAudioBitrate = ""
outputAudioTrack2Codec = ""
AudioCodec2Allow = ""
outputAudioTrack2Channels = ""
outputAudioTrack2Bitrate = ""
outputAudioOtherCodec = aac
AudioOtherCodecAllow = libfaac,libmp3lame
outputAudioOtherChannels = ""
outputAudioOtherBitrate = ""
outputSubtitleCodec = ""
```

**Comment by JHurk** [comment]
Thanks for your help, unfortunately it did not do the trick. I get an error as soon as the download starts 
transcoding:
<img width="1368" alt="nzbtomedia failed pp" src="https://cloud.githubusercontent.com/assets/7835370/23765841/dea70124-0502-11e7-8487-bd2bb20309e2.png">

I have the following config file (the complete file)
As you can see there are " before and after VideoCodecAllow and AdioOtherCodecAllow, these get added as soon as I save the file without them, restart NZBget and run the PP-script (only nzbToMedia, no other scripts). Could this be the problem? Or is there something else in the config file that is causing this?


# nzbToMedia Configuration
# For more information, visit https://github.com/clinton-hall/nzbToMedia/wiki

[General]
    # Enable/Disable update notifications
    version_notify = 1
    # Enable/Disable automatic updates
    auto_update = 1
    # Set to the full path to the git executable
    git_path = ""
    # GitHUB user for repo
    git_user = ""
    # GitHUB branch for repo
    git_branch = ""
    # Enable/Disable forceful cleaning of leftover files following postprocess 
    force_clean = 0
    # Enable/Disable logging debug messages to nzbtomedia.log
    log_debug = 0
    # Enable/Disable logging database messages to nzbtomedia.log
    log_db = 0
    # Enable/Disable logging environment variables to debug nzbtomedia.log (helpful to track down errors calling external tools.)
    log_env = 0
    # Enable/Disable logging git output to debug nzbtomedia.log (helpful to track down update failures.)
    log_git = 0
    # Set to the directory where your ffmpeg/ffprobe executables are located
    ffmpeg_path = /usr/local/ffmpeg/bin
    # Enable/Disable media file checking using ffprobe.
    check_media = 1
    # Enable/Disable a safety check to ensure we don't process all downloads in the default_downloadDirectories by mistake.
    safe_mode = 1

[Posix]
    ### Process priority setting for External commands (Extractor and Transcoder) on Posix (Unix/Linux/OSX) systems.
    # Set the Niceness value for the nice command. These range from -20 (most favorable to the process) to 19 (least favorable to the process).
    niceness = 10
    # Set the ionice scheduling class. 0 for none, 1 for real time, 2 for best-effort, 3 for idle.
    ionice_class = 2
    # Set the ionice scheduling class data. This defines the class data, if the class accepts an argument. For real time and best-effort, 0-7 is valid data.
    ionice_classdata = 4

[CouchPotato]
    #### autoProcessing for Movies
    #### movie - category that gets called for post-processing with CPS
    [[movie]]
        enabled = 1
        apikey = ""
        host = localhost
        port = 5050
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        ssl = 0
        web_root = ""
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        method = renamer
        delete_failed = 0
        wait_for = 2
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if Couchpotato is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""
    [[Movies]]
        apikey = <API of CPS>
        host = localhost
        port = 5050
        ssl = 0
        web_root = ""
        method = manage
        delete_failed = 0
        remote_path = 0
        wait_for = 2
        enabled = 1

[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[tv]]
        enabled = 1
        host = localhost
        port = 8081
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        process_method = ""
        # force processing of already processed content when running a manual scan.
        force = 0
        # tell SickRage to delete all source files after processing.
        delete_on = 0
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

[NzbDrone]
    #### autoProcessing for TV Series
    #### ndCategory - category that gets called for post-processing with NzbDrone
    [[tv]]
        enabled = 0
        apikey = ""
        host = localhost
        port = 8989
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
        nzbExtractionBy = Downloader
        wait_for = 2
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if NzbDrone is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""
    [[tv2]]
        host = localhost
        apikey = ""
        port = 8989
        ssl = 0
        web_root = ""
        delete_failed = 0
        wait_for = 2
        remote_path = 0
        enabled = 1

[HeadPhones]
    #### autoProcessing for Music
    #### music - category that gets called for post-processing with HP
    [[music]]
        enabled = 1
        apikey = ""
        host = localhost
        port = 8181
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        ssl = 0
        web_root = ""
        wait_for = 2
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if HeadPhones is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

[Mylar]
    #### autoProcessing for Comics
    #### comics - category that gets called for post-processing with Mylar
    [[comics]]
        enabled = 1
        host = localhost
        port = 8090
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if Mylar is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

[Gamez]
    #### autoProcessing for Games
    #### games - category that gets called for post-processing with Gamez
    [[games]]
        enabled = 1
        apikey = ""
        host = localhost
        port = 8085
        ###### 
        library = Set to path where you want the processed games to be moved to.
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        ssl = 0
        web_root = ""
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if Gamez is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

[Network]
    # Enter Mount points as LocalPath,RemotePath and separate each pair with '|'
    # e.g. MountPoints = /volume1/Public/,E:\|/volume2/share/,\\NAS\
    mount_points = ""

[Nzb]
    ###### clientAgent - Supported clients: sabnzbd, nzbget
    clientAgent = sabnzbd
    ###### SabNZBD (You must edit this if your using nzbToMedia.py with SabNZBD)
    sabnzbd_host = http://localhost
    sabnzbd_port = 8080
    sabnzbd_apikey = ""
    ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode.
    default_downloadDirectory = /volume1/Downloads/NZBget/dst

[Torrent]
    ###### clientAgent - Supported clients: utorrent, transmission, deluge, rtorrent, vuze, other
    clientAgent = other
    ###### useLink - Set to hard for physical links, sym for symbolic links, move to move, move-sym to move and link back, and no to not use links (copy)
    useLink = hard
    ###### outputDirectory - Default output directory (categories will be appended as sub directory to outputDirectory)
    outputDirectory = /abs/path/to/complete/
    ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode. 
    default_downloadDirectory = ""
    ###### Other categories/labels defined for your downloader. Does not include CouchPotato, SickBeard, HeadPhones, Mylar categories.
    categories = music_videos, pictures, software, manual
    ###### A list of categories that you don't want to be flattened (i.e preserve the directory structure when copying/linking.
    noFlatten = pictures, manual
    ###### uTorrent Hardlink solution (You must edit this if your using TorrentToMedia.py with uTorrent)
    uTorrentWEBui = http://localhost:8090/gui/
    uTorrentUSR = your username
    uTorrentPWD = your password
    ###### Transmission (You must edit this if your using TorrentToMedia.py with Transmission)
    TransmissionHost = localhost
    TransmissionPort = 9091
    TransmissionUSR = your username
    TransmissionPWD = your password
    #### Deluge (You must edit this if your using TorrentToMedia.py with deluge. Note that the host/port is for the deluge daemon, not the webui)
    DelugeHost = localhost
    DelugePort = 58846
    DelugeUSR = your username
    DelugePWD = your password
    ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
    deleteOriginal = 0
    chmodDirectory = 0
    resume = 1
    resumeOnFailure = 1

[Extensions]
    compressedExtensions = .zip, .rar, .7z, .gz, .bz, .tar, .arj, .1, .01, .001
    mediaExtensions = ".mkv,.avi,.divx,.xvid,.mov,.wmv,.mp4,.mpg,.mpeg,.vob,.iso,.ts"
    audioExtensions = .mp3, .aac, .ogg, .ape, .m4a, .asf, .wma, .flac
    metaExtensions = .nfo, .sub, .srt, .jpg, .gif

[Plex]
    # Only enter these details if you want to update plex library after processing.
    # Do not enter these details if you send the plex notifications from Sickbeard/CouchPotato.
    plex_host = localhost
    plex_port = 32400
    plex_token = ""
    plex_ssl = 0
    # Enter Plex category to section mapping as Category,section and separate each pair with '|'
    # e.g. plex_sections = movie,3|tv,4
    plex_sections = ""

[Transcoder]
    # getsubs. enable to download subtitles.
    getSubs = 0
    # subLanguages. create a list of languages in the order you want them in your subtitles. 
    subLanguages = dut
    # transcode. enable to use transcoder
    transcode = 1
    ###### duplicate =1 will create a new file. =0 will replace the original
    duplicate = 1
    # concat. joins cd1 cd2 etc into a single video.
    concat = 1
    # IgnoreExtensions is a comma-separated list of extensions that will not be transcoded.
    ignoreExtensions = ".m4v,.mp4"
    # outputFastStart. 1 will use -movflags + faststart. 0 will disable this from being used.
    outputFastStart = 0
    # outputQualityPercent. used as -q:a value. 0 will disable this from being used.
    outputQualityPercent = ""
    # outputVideoPath. Set path you want transcoded videos moved to. Leave blank to disable.
    outputVideoPath = ""
    # processOutput. 1 will send the outputVideoPath to SickBeard/CouchPotato. 0 will send original files.
    processOutput = 0
    # audioLanguage. set the 3 letter language code you want as your primary audio track.
    audioLanguage = dut
    # allAudioLanguages. 1 will keep all audio tracks (uses AudioCodec3) where available.
    allAudioLanguages = 1
    # allSubLanguages. 1 will keep all existing sub languages. 0 will discard those not in your list above.
    allSubLanguages = 0
    # embedSubs. 1 will embed external sub/srt subs into your video if this is supported.
    embedSubs = 1
    # burnInSubtitle. burns the default sub language into your video (needed for players that don't support subs)
    burnInSubtitle = 0
    # extractSubs. 1 will extract subs from the video file and save these as external srt files.
    extractSubs = 0
    # externalSubDir. set the directory where subs should be saved (if not the same directory as the video)
    externalSubDir = ""
    # hwAccel. 1 will set ffmpeg to enable hardware acceleration (this requires a recent ffmpeg)
    hwAccel = 0
    # generalOptions. Enter your additional ffmpeg options here with commas to separate each option/value (i.e replace spaces with commas).
    generalOptions = ""
    # outputDefault. Loads default configs for the selected device. The remaining options below are ignored.
    # If you want to use your own profile, leave this blank and set the remaining options below.
    # outputDefault profiles allowed: iPad, iPad-1080p, iPad-720p, Apple-TV2, iPod, iPhone, PS3, xbox, Roku-1080p, Roku-720p, Roku-480p, mkv, mp4-scene-release
    outputDefault = None
    #### Define custom settings below.
    outputVideoExtension = .mp4
    outputVideoCodec = libx264
    VideoCodecAllow = "libx264,h264,h.264,AVC,avc,mpeg4,msmpeg4,MPEG-4"
    outputVideoPreset = ""
    outputVideoResolution = 1920:1080
    outputVideoFramerate = ""
    outputVideoBitrate = ""
    outputVideoCRF = ""
    outputVideoLevel = ""
    outputAudioCodec = aac
    AudioCodecAllow = libfaac
    outputAudioChannels = ""
    outputAudioBitrate = ""
    outputAudioTrack2Codec = ""
    AudioCodec2Allow = ""
    outputAudioTrack2Channels = ""
    outputAudioTrack2Bitrate = ""
    outputAudioOtherCodec = "libfaac,libmp3lame"
    AudioOtherCodecAllow = aac
    outputAudioOtherChannels = ""
    outputAudioOtherBitrate = ""
    outputSubtitleCodec = ""

[WakeOnLan]
    ###### set wake = 1 to send WOL broadcast to the mac and test the server (e.g. xbmc) the host and port specified.
    wake = 0
    host = 192.168.1.37
    port = 80
    mac = 00:01:2e:2D:64:e1

[UserScript]
    #Use user_script for uncategorized downloads
    #Set the categories to use external script.
    #Use "UNCAT" to process non-category downloads, and "ALL" for all defined categories.
    [[UNCAT]]
        #Enable/Disable this subsection category
        enabled = 1
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
        #Enable if you are sending commands to a remote server for this category
        remote_path = 0
        #What extension do you want to process? Specify all the extension, or use "ALL" to process all files.
        user_script_mediaExtensions = ".mkv,.avi,.divx,.xvid,.mov,.wmv,.mpg,.mpeg,.vob,.iso,.bin"
        #Specify the path to your custom script. Use "None" if you wish to link this category, but NOT run any external script.
        user_script_path = /nzbToMedia/userscripts/script.sh
        #Specify the argument(s) passed to script, comma separated in order.
        #for example FP,FN,DN, TN, TL for file path (absolute file name with path), file name, absolute directory name (with path), Torrent Name, Torrent Label/Category.
        #So the result is /media/test/script/script.sh FP FN DN TN TL. Add other arguments as needed eg -f, -r
        user_script_param = FN
        #Set user_script_runOnce = 0 to run for each file, or 1 to only run once (presumably on the entire directory).
        user_script_runOnce = 0
        #Specify the successcodes returned by the user script as a comma separated list. Linux default is 0
        user_script_successCodes = 0
        #Clean after? Note that delay function is used to prevent possible mistake :) Delay is intended as seconds
        user_script_clean = 1
        delay = 120
        #Unique path (directory) created for every download. set 0 to disable.
        unique_path = 1
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""
    [[mine]]
        user_script_mediaExtensions = ".mkv,.avi,.divx,.xvid,.mov,.wmv,.mpg,.mpeg,.vob,.iso,.bin"
        user_script_path = /nzbToMedia/userscripts/script.sh
        user_script_param = FN
        user_script_runOnce = 0
        user_script_successCodes = 0
        user_script_clean = 1
        delay = 120
        remote_path = 0
        enabled = 1

[ASCII]
    #Set convert =1 if you want to convert any "foreign" characters to ASCII (UTF8) before passing to SB/CP etc. Default is disabled (0).
    convert = 0

[passwords]
    # enter the full path to a text file containing passwords to be used for extraction attempts.
    # In the passwords file, every password should be on a new line
    PassWordFile = ""

[Custom]
    # enter a list (comma separated) of Group Tags you want removed from filenames to help with subtitle matching.
    # e.g remove_group = [rarbag],-NZBgeek
    # be careful if your "group" is a common "real" word. Please report if you have any group replacements that would fall in this category.
    remove_group = ""

**Comment by clinton-hall** [comment]
When using NZBGet, the settings in nzbget webui for the script you are calling, will over-ride any settings in the autoProcessMedia.cfg.

So use the settings I suggested above, and enter these in the NZBget webui for nzbToMedia.py

**Comment by JHurk** [comment]
If I look at the webui I see these settings there. So I think these settings get called through the webui, and it still results in the error. 

It is something in the transcode because without transcoding the pp works fine. 
The screenshot of the error (in my previous post) doesn't give you a clue?

Is there anything else I can provide (debug log) which would help in pinpointing where the issue is caused?

**Comment by clinton-hall** [comment]
in autoProcessMedia.cfg
```
[General]
    debug_log = 1
```
then postprocess again and post the log here.

**Comment by JHurk** [comment]
Tried it multiple times with the debug on. With .mp4 and with .m4v, all with no succes.
Here are the logfiles. Hopefully you are able to help me out.

[_nzblog.txt](https://github.com/clinton-hall/nzbToMedia/files/834369/_nzblog.txt)

**Comment by clinton-hall** [comment]
```
nice -n10 /usr/local/ffmpeg/bin/ffmpeg -loglevel warning -fflags +genpts -i /volume1/Downloads/NZBget/dst/Movies/Bolt (2008) 1080p NL Audio _amp_ Subs/Bolt (2008) 1080p NL Audio _amp_ Subs.mkv -map 0:0 -map 0:2 -map 0:1 -map 0:3 -c:v copy -c:a:0 aac -strict -2 -c:a:1 libfaac,libmp3lame -c:s copy /volume1/Downloads/NZBget/dst/Movies/Bolt (2008) 1080p NL Audio _amp_ Subs/Bolt (2008) 1080p NL Audio _amp_ Subs.mp4
```
So you have set
```
outputAudioOtherCodec = "libfaac,libmp3lame"
AudioOtherCodecAllow = aac
```
this should be
```
outputAudioOtherCodec = aac
AudioOtherCodecAllow = libfaac,libmp3lame
```

**Comment by JHurk** [comment]
Changed it, sorry for that. But still no luck.
I still get an error, but now there is a .mp4 files being made (32bite big). So the file is there, but the transcoding stops instantly.

This is the new debug line:
nzbToMedia: [13:28:32] [DEBUG]::MAIN: calling command: nice -n10 /usr/local/ffmpeg/bin/ffmpeg -loglevel warning -fflags +genpts -i /volume1/Downloads/NZBget/dst/Movies/Bolt (2008) 1080p NL Audio _amp_ Subs/Bolt (2008) 1080p NL Audio _amp_ Subs.mkv -map 0:0 -map 0:2 -map 0:1 -map 0:3 -c:v copy -c:a:0 aac -strict -2 -c:a:1 aac -strict -2 -c:s copy /volume1/Downloads/NZBget/dst/Movies/Bolt (2008) 1080p NL Audio _amp_ Subs/Bolt (2008) 1080p NL Audio _amp_ Subs.mp4

And after that one I get an generic error:
nzbToMedia: [13:28:32] [ERROR]::MAIN: Transcoding of video to /volume1/Downloads/NZBget/dst/Movies/Bolt (2008) 1080p NL Audio _amp_ Subs/Bolt (2008) 1080p NL Audio _amp_ Subs.mp4 failed with result 1

**Comment by JHurk** [comment]
When I look at the config file I still see the " before and after a non-blanc option, even when I deleted the " and saved the file.
Maybe I am doing it wrong with the file and the webui settings on NZBget??
These are my settings in the config file:
outputVideoExtension = .mp4
    outputVideoCodec = libx264
    VideoCodecAllow = "libx264,h264,h.264,AVC,avc,mpeg4,msmpeg4,MPEG-4"
    outputVideoPreset = ""
    outputVideoResolution = ""
    outputVideoFramerate = ""
    outputVideoBitrate = ""
    outputVideoCRF = ""
    outputVideoLevel = ""
    outputAudioCodec = aac
    AudioCodecAllow = libfaac
    outputAudioChannels = ""
    outputAudioBitrate = ""
    outputAudioTrack2Codec = ""
    AudioCodec2Allow = ""
    outputAudioTrack2Channels = ""
    outputAudioTrack2Bitrate = ""
    outputAudioOtherCodec = aac
    AudioOtherCodecAllow = "libfaac,libmp3lame"
    outputAudioOtherChannels = ""
    outputAudioOtherBitrate = ""
    outputSubtitleCodec = ""
I deleted the " in the non-blanc fields, but they keep getting added when I reload.

And these are the settings in the webui
<img width="854" alt="settings webui nzbget" src="https://cloud.githubusercontent.com/assets/7835370/23823293/d38fe284-065f-11e7-98ba-e27348294a77.png">

**Comment by JHurk** [comment]
I just tried to delete the entire config file and reload the application. Now the pp is transcoding. Do not know yet if this is being done right, but at least we are getting somewhere.
Will let you know as soon as the transcoding is done.

**Comment by JHurk** [comment]
Sorry to keep it waiting, but my usenetprovider had a server crash. It works now so thanks for your help. Seems like a corrupt config file was the problem.
