### ISSUE TITLE
support for qbittorrent

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1220]
Just curious if there is support for this client.

I'm still using utorrent for linux because I have a bunch of script api scrubbing and don't really want to move away but its getting to be time. 

I've looked at a couple of the other supported clients and they don't really jump out at me, this one was suggested.

**Comment by mgaulton** [comment]
oh and since i don't want to run a gui etc but want an api, suggestions would be great (community comment welcome)

**Comment by clinton-hall** [comment]
Sopport exists for
rtorrent
utorrent
deluge
transmission
vuze

To support qbittorrent, I just need to know the way scripts are called... i.e. what options/parameters are passed, or can be passed, and is these are passed as environment variables, or arguments.

Additionally, if there is an api interface to pause/resule torretns etc, and possible an open-source interface client already available.

**Comment by DrakeJones** [comment]
I switched to qBittorrent from Transmission.  I'm using Windows 7 and was having issues with Transmission.   qBittorrent's more flexible and feature rich, imho.   I'm not a coder.  How can I give you the info you need (above) to support qBittorrent?  Medusa and Headphones already have built-in support for qBittorrent.

**Comment by DrakeJones** [comment]
I switched to qBittorrent from Transmission.  I'm using Windows 7 and was having issues with Transmission.   qBittorrent's more flexible and feature rich, imho.   I'm not a coder.  How can I give you the info you need (above) to support qBittorrent?  Medusa and Headphones already have built-in support for qBittorrent.

Is this the best solution? [https://www.reddit.com/r/qBittorrent/comments/6x4cg7/postprocessing_script_for_sickrage/](url) 

[https://gist.github.com/nosmokingbandit/ddf8f8a9d156bef7269ec32b6873ec1a](url)

**Comment by clinton-hall** [comment]
qbittorrent is supported in nightly branch:
https://github.com/clinton-hall/nzbToMedia/commit/e34ba9af89b07e668824b6a7593eaddf201ae73e
https://github.com/clinton-hall/nzbToMedia/commit/12a7e3c5ceddbfb16d3461dd79aa5da4084894a0
https://github.com/clinton-hall/nzbToMedia/commit/d67ed51104a56c3c46d060842e7fa0201118b1fb
https://github.com/clinton-hall/nzbToMedia/commit/4fa0dc4572576c351ff3faa46cc223a38e0579ba

So switch to nightly:

Then in autoProcessMEdia.cfg:
```
[Torrent]
    clientAgent = qbittorrent
    qBittorrenHost = localhost
    qBittorrentPort = 8080
    qBittorrentUSR = your username
    qBittorrentPWD = your password
```
In qbittorrent set the PP script as `C:\full\path\to\nzbToMedia\TorrentToMedia.py "%D|%N|%L|%I"`
Also ensure that in qBittorrent you configured the webui:
under options, you need to go to the 7th item on the left-hand frame. Then on the right hand side you need to enable Web User Interface (remote Control)

**Comment by DrakeJones** [comment]
Thank you CH.  Is this the command sequence get to on the nightly commit?

 

git branch --set-upstream-to=origin/nightly e34ba9a12a7e3cd67ed514fa0dc4

**Comment by clinton-hall** [comment]
That should work, and then would update to latest... the first commit won't work, there were subsequent updates...

the easiest IMO is
```
git checkout nightly
git pull
```

**Comment by DrakeJones** [comment]
So far so good.  Thanks.
