### ISSUE TITLE
Windowserror [123]

### ISSUE THREAD

**Issue by Phyxsius7** [clinton-hall/nzbToMedia#1222]
Hi,
Starting from 25/02/2017 (not sure how relevant this date is) processing of every files fail with the following error.

WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: '\\\\?\\E:\\Process\\Completed Download\\Temp\\Star.Trek.TNG.S05E01.720p.BluRay.x264-GECKOS/*.*'

I have not made any changes to the "autoProcessMedia.cfg" file ,so I am guessing that it has something to do with an update.

The dir in question has been noted as foloowing:
default_downloadDirectory = E:\Process\Completed Download\Temp

I have added a processes log as an attachement;
[windowserror 123.txt](https://github.com/clinton-hall/nzbToMedia/files/832361/windowserror.123.txt)

What could the cause of the problem be?

**Comment by clinton-hall** [comment]
on that date you updated SABnzbd...

So, to fix this, please update nzbToMedia to the nightly branch.
