### ISSUE TITLE
Suddenly Post-Processing Fails

### ISSUE THREAD

**Issue by kushfest** [clinton-hall/nzbToMedia#1226]
nzbToMedia has been a total rockstar for me. I've been using it with Sonarr and CouchPotato with great success, but suddenly this morning all post-processing is failing on me. Yesterday I tweaked some settings through nzbget, which I'm hoping didn't somehow corrupt my .cfg file. Log output is below. Any suggestions?

```
Sun Mar 12 2017 08:54:10	INFO	Move for Mercy.Street.S02E06.BDRip.X264-REWARD English successful
Sun Mar 12 2017 08:54:10	INFO	Executing post-process-script nzbToMedia/nzbToCouchPotato.py for Mercy.Street.S02E06.BDRip.X264-REWARD English
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato: [08:54:11] [ERROR]::MAIN: Unable to migrate config file /opt/nzbget/scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato: Traceback (most recent call last):
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:   File "/opt/nzbget/scripts/nzbToMedia/nzbToCouchPotato.py", line 257, in <module>
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:     result = nzbToMedia.main(sys.argv, section)
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:   File "/opt/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 649, in main
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:     core.initialize(section)
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:   File "/opt/nzbget/scripts/nzbToMedia/core/__init__.py", line 292, in initialize
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:     CFG = config.addnzbget()
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:   File "/opt/nzbget/scripts/nzbToMedia/core/nzbToMediaConfig.py", line 253, in addnzbget
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:     CFG_NEW = config()
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:   File "/opt/nzbget/scripts/nzbToMedia/core/nzbToMediaConfig.py", line 94, in __init__
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:     super(configobj.ConfigObj, self).__init__(*args, **kw)
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:   File "/opt/nzbget/scripts/nzbToMedia/libs/configobj/configobj.py", line 1229, in __init__
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:     self._load(infile, configspec)
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:   File "/opt/nzbget/scripts/nzbToMedia/libs/configobj/configobj.py", line 1318, in _load
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato:     raise error
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato: configobj.configobj.ConfigObjError: Parsing failed with several errors.
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato: First error at line 125.
Sun Mar 12 2017 08:54:11	INFO	nzbToCouchPotato: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0xb73ab2cc>> ignored
Sun Mar 12 2017 08:54:11	ERROR	Post-process-script nzbToMedia/nzbToCouchPotato.py for Mercy.Street.S02E06.BDRip.X264-REWARD English failed (terminated with unknown status)
Sun Mar 12 2017 08:54:11	INFO	Collection Mercy.Street.S02E06.BDRip.X264-REWARD English added to history

```

**Comment by kushfest** [comment]
This is likely relevant...I've discovered this is only happening with nzbget. Transmission doesn't seem to be having the same issue when calling nzbtomedia. It also looks like nzbget is trying to send tv to couchpotato, though when I post-process again and set it to tv, nzbdrone has the same error. It looks like maybe the category is not getting set, which is making it call the wrong app to post-process the files. As far a I can tell my config looks to be correct in nzbget.

**Comment by clinton-hall** [comment]
make sure category tv is set to call nzbToNzbDrone.py and that you set the config in nzbTonzbDrone in the NZBGet WebUI.

Likewise make sure category movies is set to call nzbToCouchPotato.py and that you set the config in nzbToCouchPotato.py in the NZBGet WebUI.

**Comment by kushfest** [comment]
Well this is weird...you were correct that the tv category was incorrectly set to call nzbToCouchPotato.py. I'm not at all sure how that changed, but I keep changing it to call nzbToNzbDrone.py in the nzbget settings, and after nzbget restarts it has changed back to nzbToCouchPotato.py. Any suggestions?

From what I can tell, the movies category is configured correctly, as are both nzbToCouchPotato.py and nzbToNzbDrone.py in the nzbget webui.

**Comment by kushfest** [comment]
Looks a reinstall of nzbget was the solution. I also found a phantom category that somehow got added to my autoProcessMedia.cfg file. That was mucking up the works after the reinstall, but things seem to be running smoothly again. Thanks!

**Comment by anoteng** [comment]
I got the exact same error with nzbtosickbeard using sickrage and sabnzbd. Everything has been running smoothly, but suddenly som time during the 10th of march it started failing with the same error message as OP. From the changelog of sickrage it looks like they changed something in the postprocessing on the 8th, it's not unlikely that the change was installed on my server on the 10th (i no longer have the log..)
From the changelog: NOTE: Post Processor is still going through changes, this may or may not work well for you.

**Comment by 2fst4u** [comment]
@anoteng did you ever fix this?
