### ISSUE TITLE
Postprocessing failed (autoProcessMusic.py)

### ISSUE THREAD

**Issue by count00zero** [clinton-hall/nzbToMedia#1227]
Hi,

if have discovered a still existing Postprocessing Problem on my new Ubuntu 16.10 box!
In #1146 you wrote to fix the problem in autoProcessMusic.py:
from

                'dir': remoteDir(dirName) if remote_path else dirName

to

                'dir': remoteDir(dirName) if remote_path else os.path.split(dirName)[0]

BUT ... there is still a portion of the code unchanged (master, develop, nightly)

Now I adjusted it myself and voila, PP is running again greatly!
Would you fix it in your sources as well?
It's line 131 in autoProcessMusic.py (master).

THANKS and BR,
count

**Comment by clinton-hall** [comment]
I actually changed this a lot... to try the full path, and then try the parent directory (to avoid backwards compatibility issues).
https://github.com/clinton-hall/nzbToMedia/commit/614f8f6a325542516876b5b6464e533cf42329d8

this should be working in current nightly.
I'm planning to merge up to master soon, but need to debug a few other changes.

**Comment by count00zero** [comment]
Thanks a lot!
Will try again when in master.

BR,
count
