### ISSUE TITLE
[ERROR]::MAIN: Unable to migrate config file /xxx/xxx/autoProcessMedia.cfg

### ISSUE THREAD

**Issue by neil-bh** [clinton-hall/nzbToMedia#1230]
Hi,

I'm receiving the following error during post processing after a successful download:

`nzbToMedia: [01:53:59] [ERROR]::MAIN: Unable to migrate config file /diskpool1-raidz1/NAS/LinuxStore/nzbget/scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...`

- I am using nzbget with Sonarr and Radarr.
- I am using the latest version of nzbget, and the latest Sonarr and Radarr forks.
- I am also using the latest nightly fork of the nzbToMedia scripts.

I've been checking the issues area and googled this issue to find that a lot of it revolves around having duplicate category names in the autoProcessMedia.cfg.

In my autoProcessMedia.cfg I have configured/enabled the settings correctly under [Radarr] using the category [[movie]] and I am have also configured/enabled the settings correctly under [NzbDrone] using the category [[tv]].  All the other settings for the other programs are not enabled.

What is unusual is that once I have saved the file and tried a few test downloads from Sonarr, everything goes to nzbget correctly, and the post processing kicks off, however it fails with the error message shown at the begining of this post.  If I then go back into the autoProcessMedia.cfg I can see that for some strange reason, all the other program sections that I am not using (i.e. CouchPotato, SickBeard, Headphones etc) have additional lines added under a new category called [[""]] - and this is why I think the error message is complaining that it cannot merge because in theory I guess these are all duplicates since these lines appear under each program section.

For example, these lines that magically appear in the file look like this:

```
    [[""]]
        apikey = ""
        host = ""
        port = ""
        ssl = 0
        web_root = ""
        method = renamer
        delete_failed = 0
        remote_path = 0
        wait_for = ""
        enabled = 1
```

I have pasted my autoProcessMedia.cfg file here for your reference: [https://gist.github.com/wizzkidd/2ce34e0151badde59c63f827fea2f398](https://gist.github.com/wizzkidd/2ce34e0151badde59c63f827fea2f398)

1. Also can anyone clarify the correct way to use nzbToMedia, i.e do I configure the settings in the autoProcessMedia.cfg only, and leave the settings as they are in the GUI/webpage...
2. Or do I leave the autoProcessMedia.cfg as it is (default), and configure the settings in the GUI/webpage...
3. And also, if I change the settings in the GUI/webpage under NZBTOMEDIA, should I leave the NZBTONZBDRONE and NZBTORADARR untouched?
4. And lastly, in the categories section, for the tv category, do I choose to add "nzbtonzbdrone.py" to the extensions, or would i choose to add "nzbtomedia.py" to the extensions? and likewise with the movie category, would I add "nzbtoradarr.py" or "nzbtomedia.py" ?

I hope thats enough info for someone to help assist this problem.

Thanks in advance,

WizzKidd

**Comment by clinton-hall** [comment]
When using NZBGet you need to set the config from within NZBGet webui.
i.e. if NZBGet calls nzbToMedia.py you need to set the categories and hosts, ports, apis etc under the nzbToMedia section in NZBGet settings.

**Comment by wizzkidd** [comment]
Hi Clinton-Hall, I can confirm that in the nzbget web interface i have set nzbget to post process the nzbToMedia.py script which is working fine.

Do you have any idea why I'm getting the new lines added to my autoProcessMedia.cfg file? The error is saying that it cannot merge.

**Comment by wizzkidd** [comment]
In view of never leaving a problem unsolved for others to be frustrated at for not seeing an answer... I have solved my problem.

The reason the the config could not migrate was because of the duplicate category names and additional lines that were mysteriously getting auto added into the config file.

The reason these extra lines were being added is due to NZBGet being instructed to execute the wrong script.  I was telling anything discovered from the 'tv' category to post process the nzbToMedia.py script, when in fact I should have been telling it to post process the nzbToNzbDrone.py script instead.  The same goes for the 'movies' category.  It should have been post processing the nzbToRadarr.py script.

Once that was solved, the errors went away.

I'd still like to know if once I edit the autoProcessMedia.cfg do I need to also edit the files representing nzbToNzbDrone and nzbToRadarr in NZBGet?  It seems like i'm configuring the same settings twice?

**Comment by clinton-hall** [comment]
Yes, in NZBGet you need to enter the config (for the scripts you call via NZBGet) in the web ui. When the script is called, these settings are written into the autoProcessMedia.cfg

The intentions here is that you use NZBGet to set up the scripts and don't need autoProcessMedia to be manually edited (unless for some advanced settings, or for use by other/Torrent downloaders).
