### ISSUE TITLE
QUESTION: nzbToMedia config for nzbget seperate from autoProcessMedia.cfg?

### ISSUE THREAD

**Issue by xios01** [clinton-hall/nzbToMedia#1232]
I just want to verify that this is the case... regarding the wiki page for configuring nzbToMedia for nzbget... 
https://github.com/clinton-hall/nzbToMedia/wiki/nzbget

I'm just wanting to confirm that nzbget's webui interface for nzbToMedia scripts are the only method to configure nzbtomedia for nzbget... is the autoProcessMedia.cfg file read at all when nzbget initiates the script?  is there a way of ignoring the web configuration and instead relying on the only the autoprocessmedia.cfg file?  

fyi, been using this script for a while now... and its a wonderful script...  Just trying to verify if there's a way to centralize my configuration in only 1 place for multiple downloaders...

**Comment by wizzkidd** [comment]
+1

I'm trying to get clarity on the exact same question.

At the moment, everything I do in autoProcessMedia.cfg I am repeating in the NZBGet webui sections for nzbToNzbDrone and nzbToRadarr (or nzbToCouchPotato).

Do we need to modify the settings in both areas?

**Comment by Vanhecke** [comment]
The settings in NZBGet are passed to nzbTo* on every run.  
The nzbTo* script takes those settings and writes them to the autoProcessMedia.cfg file [here](https://github.com/clinton-hall/nzbToMedia/blob/66abb2d562aa9491c5c5fad0c228e20a05982fd7/core/nzbToMediaConfig.py#L470).

It also seems like it would overwrite the autoProcessMedia.cfg settings if the setting was configured in NZBGet.

**Comment by clinton-hall** [comment]
Yes, The script will ALWAYS write the settings from NZBGet config into the autoProcessMedia.cfg.
It will only over-write any settings that have been configured in NZBGet. i.e. if you call nzbToCouchPotato then the configuration for nzbToCouchPotato will be written in to autoProcessMedia.cfg in the [CouchPotato} section for the particular category that is being used.
This was you can have multiple different instances that use different settings for different categories etc.

When using any other applications to download, the settings in autoProcessMedia are used.

Finally, any options in the autoProcessMedia that are not shown in NZBGet config (i.e. some advanced settings) need to be manually configured in autoProcessMedia .cfg

So NABGet config is written into autoProcessMedia.cfg, and then the script calls the settinsg from autoProcessMedia.cfg (which is now a combination of the NZBGet config and any previous/exisiting settings that were not defined in NZBGet).

I hope this makes sense. The key here, is if you use multiple downloaders, and these have different settings, you need to make these use different categories...
