### ISSUE TITLE
nzbToSickBeard (or nzbToMedia) unzip not found...

### ISSUE THREAD

**Issue by tenzion** [clinton-hall/nzbToMedia#1235]
Having installed nzbget and SickRage on my Synology DS414 running DSM 6.1 is giving me a bit of trouble:

Trying to extract a file, not working. Whether I use nzbToMedia og nzbToSickBeard script, not working:

nzbToSickBeard: [10:43:43] [ERROR]::MAIN: EXTRACTOR: unzip not found, disabling support for .zip

On my Synology, I both have unrar and 7z, but it does not seem that nzbToMedia/nzbToSickBeard is trying to fall back to use them...

Is there any way to force this?

**Comment by clinton-hall** [comment]
it should fall back to 7zip as long as 7zip is in the PATH as seen by NZBGet (or the user that runs NZBGet).

But NZBGet should do the extracting (you can define the 7zip path).
