### ISSUE TITLE
Choke on special chars

### ISSUE THREAD

**Issue by sinterlkaas** [clinton-hall/nzbToMedia#1237]
It seems that nzbtomedia chokes in some special chars this happend a few times I manually removed the copyright char and the process continued.

File example: ©.U.T.SbuS.LN-462H.0.2CAA.LD-BEW.p0801.6102.loopdaeD

_This happens to other characters too. So the handling of unknown / mismatching characters should be improved_ 

> [16:38:35] [DEBUG]::MAIN: Options passed into nzbToMedia: ['./nzbToMedia.py']
> [16:38:35] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
> [16:38:35] [DEBUG]::MAIN: No directories identified in CouchPotato:movie for post-processing
> [16:38:35] [INFO]::MAIN: Searching /mnt/Storage/Downloads/complete/movies for mediafiles to post-process ...
> [16:38:35] [INFO]::MAIN: Starting manual run for CouchPotato:movies - Folder: /mnt/Storage/Downloads/complete/movies/Deadpool 2016 1080p WEB-DL AAC2 0 H264-NL SubS T U.cp(tt1431045)
> [16:38:35] [INFO]::MAIN: Checking database for download info for Deadpool 2016 1080p WEB-DL AAC2 0 H264-NL SubS T U.cp(tt1431045) ...
> [16:38:35] [INFO]::MAIN: Unable to locate download info for Deadpool 2016 1080p WEB-DL AAC2 0 H264-NL SubS T U.cp(tt1431045), continuing to try and process this release ...
> [16:38:35] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
> /home/crazed/nzbToMedia/core/nzbToMediaUtil.py:418: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
>   if ((Name[Idx] == '\xC2') | (Name[Idx] == '\xC3')) & (
> Traceback (most recent call last):
>   File "./nzbToMedia.py", line 817, in <module>
>     exit(main(sys.argv))
>   File "./nzbToMedia.py", line 792, in main
>     download_id=download_id or None, inputCategory=subsection)
>   File "./nzbToMedia.py", line 608, in process
>     inputName, inputDirectory = convert_to_ascii(inputName, inputDirectory)
>   File "/home/crazed/nzbToMedia/core/nzbToMediaUtil.py", line 473, in convert_to_ascii
>     encoded, filename2 = CharReplace(filename)
>   File "/home/crazed/nzbToMedia/core/nzbToMediaUtil.py", line 419, in CharReplace
>     (Name[Idx + 1] >= '\xA0') & (Name[Idx + 1] <= '\xFF')):
>   File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
>     return codecs.utf_8_decode(input, errors, True)
> UnicodeDecodeError: 'utf8' codec can't decode byte 0xa9 in position 0: invalid start byte
> Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7fc4a3e24190>> ignored
>

**Comment by clinton-hall** [comment]
Yep.... any suggestions welcome... Trying to figure out encoding is something I struggle with.
What encoding is your system set to?

**Comment by sinterlkaas** [comment]
Sorry for late response  but my encoding is set to UTF-8

asdads@asdads:~/nzbToMedia$ echo $LANG
en_US.UTF-8
asdads@asdads:~/nzbToMedia$ locale charmap
UTF-8
asdads@asdads:~/nzbToMedia$ locale -a
C
C.UTF-8
en_US.utf8
POSIX

**Comment by qorron** [comment]
https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/
this helped me a lot.
