### ISSUE TITLE
RARBG Samples / Exception Rename Problem

### ISSUE THREAD

**Issue by grantsewell** [clinton-hall/nzbToMedia#1238]
Seems to only be a problem with RARBG samples that arrive with other media, however it could happen with other groups. Often there are two mp4 files - one is RARBG.mp4, the other is the requested video which is conveniently named the same as the folder. When nzbToMedia processes the two files, an exception is generated and it renames RARBG.mp4 with the directory name, overwriting the actual media file. Log example:

`2017-04-09 10:53:33 DEBUG   ::EXCEPTION: Replacing file name RARBG with directory name MovieName.2001.720p.BluRay.H264.AAC-RARBG`
`2017-04-09 10:53:33 DEBUG   ::EXCEPTION: Replacing file name /mnt/movies/MovieName.2001.720p.BluRay.H264.AAC-RARBG/RARBG.mp4 with download name /mnt/movies/MovieName.2001.720p.BluRay.H264.AAC-RARBG/MovieName.2001.720p.BluRay.H264.AAC-RARBG.mp4`

Crappy workaround: adding RARBG to the [Custom] section of autoProcessMedia.cfg inadvertently prevents the overwrite and allows post-processing to run with no issues. The exception is still present.

`[Custom]`
`# enter a list (comma separated) of Group Tags you want removed from filenames to help with subtitle matching.`
`# e.g remove_group = [rarbag],-NZBgeek`
`# be careful if your "group" is a common "real" word. Please report if you have any group replacements that would fall in this category.`
`remove_group = RARBG`

`2017-04-09 13:37:15 DEBUG   ::EXCEPTION: Replacing file name RARBG with directory name MovieName.2001.720p.BluRay.H264.AAC-RARBG`
`2017-04-09 13:37:15 DEBUG   ::EXCEPTION: Replacing file name /mnt/movies/MovieName.2001.720p.BluRay.H264.AAC-RARBG/RARBG.mp4 with download name /mnt/movies/MovieName.2001.720p.BluRay.H264.AAC-RARBG/MovieName.2001.720p.BluRay.H264.AAC-.mp4`
`2017-04-09 13:37:15 DEBUG   ::EXCEPTION: Replacing file name /mnt/movies/MovieName.2001.720p.BluRay.H264.AAC-RARBG/MovieName.2001.720p.BluRay.H264.AAC-RARBG.mp4 with download name /mnt/movies/MovieName.2001.720p.BluRay.H264.AAC-RARBG/MovieName.2001.720p.BluRay.H264.AAC-.mp4`

**Comment by clinton-hall** [comment]
ok, just made a change.
if `/mnt/movies/MovieName.2001.720p.BluRay.H264.AAC-RARBG/MovieName.2001.720p.BluRay.H264.AAC-RARBG.mp4` exists, then the `RARBG.mp4` will be renamed to `/mnt/movies/MovieName.2001.720p.BluRay.H264.AAC-RARBG/MovieName.2001.720p.BluRay.H264.AAC-RARBG.NTM.mp4`
