### ISSUE TITLE
Do not connect to clients for transcoding only post processing

### ISSUE THREAD

**Issue by natoriousbigg** [clinton-hall/nzbToMedia#1240]
I like using the "transcoding only" feature of nzbtomedia by leaving the API section blank in Radarr/Sonarr. However, at the end of transcoding, nzbtomedia attempts to connect the Radarr/Sonarr with an empty API resulting in a 403 error and the script reports an exit 1 error. In NZBGet, there's no option to ignore this error so Radarr delete the download.

Can we set nzbtomedia to avoid connect to Radarr/Sonarr if running in "transcoding only" mode?

Another solution would be to add another script called something like "transcodingOnly.py" which only handles transcoding only.

**Comment by clinton-hall** [comment]
I have set this to return successful status after transcoding when no user/api set.
This should achieve what you want. I looked at creating a new script or a new option, but that looked like it would bloat the scripts out a bit more and would likely cause more confusion for existing users when they have new scripts and options pop up.
