### ISSUE TITLE
add wiki page re: containerised services

### ISSUE THREAD

**Issue by leviwheatcroft** [clinton-hall/nzbToMedia#1242]
I've run into a few problems with non-obvious solutions.

#872 and #1102 don't say anything about containers, but my symptoms were identical.

Basically, container instance needs to be created with `--net=host` or else one container (sabnzbd) won't be able to access ports exposed by other containers (like 8081 on sickrage).

I'm happy to post some notes about this (and other containerisation issues) if you think this is a good idea.

**Comment by clinton-hall** [comment]
Yes, Please post your notes. You should be able to directly edit the Wiki etc, otherwise please provide more details here.
Where do you create the `--net=host` instance? is this in the container config/init itself?

**Comment by leviwheatcroft** [comment]
yeah, in the container config/init

for example this is the command for [linuxserver/sabznbd](https://github.com/linuxserver/docker-sabnzbd)

```bash
docker create --name=sabnzbd \
--net=host \
-v <path to data>:/config \
-v <path to downloads>:/downloads \
-v <path to incomplete downloads>:/incomplete-downloads \
-e PGID=<gid> -e PUID=<uid> \
-e TZ=<timezone> \
-p 8080:8080 -p 9090:9090 \
linuxserver/sabnzbd
```

The `--net=host` doesn't appear on that container's README.md, without it the sab container's localhost will be a virtual adapter created by docker.
