### ISSUE TITLE
NZBtoMedia: Sabnzbd 2.0 missing execution rights

### ISSUE THREAD

**Issue by maolbo** [clinton-hall/nzbToMedia#1243]
I've updated my sabnzbd to version 2.0.0 and now I'm facing an execution right issue. It says that the execution rights are missing (+x).

I've checked autoprocessmedia.cfg but there is all fine.

I also then tried to re-install the script, but with the same result. Manual-post processing via sickrage is working fine.

I'm using a Qnap NAS and it worked just fine before the update.

**Comment by clinton-hall** [comment]
I think this may be related to other issues with the QNAP SABnzbd qpkg... I do need to try and get back into this.

**Comment by clinton-hall** [comment]
#707

**Comment by maolbo** [comment]
I tried to change the first line of "nzbtomedia.py" and "nzbtosickbeard.py" to #!/opt/bin/phyton2.7 from #!/**usr**/bin/**env phyton2** - no luck. still same issue with no execusion right!

**Comment by maolbo** [comment]
Hi clinton-hall

Is there anything I can try to bring my nzbtomedia back to running?

Appreciate your feedback.
