### ISSUE TITLE
Rename file in post processing

### ISSUE THREAD

**Issue by alexandrezia** [clinton-hall/nzbToMedia#1248]
Downloaded files sometimes are so obfuscated that their names are like hashes, ex.  
```
7902b6025f22497bb3fe26ec314f55be.mkv
```
My Media players don't recognize these files (Kodi, Plex), they don't know which show the file belongs, which episode number, etc.

I'm Using SickRage (sickrage fork) to download TV Shows, and Sickrage post processing is not that good, it runs in polling mode in a 10 mins basis, which is too slow and inefective.
And it also don't recognizes to which show these files belongs, and ends up deleting the files.

At this moment only options are manual renaming or download it again (which in many cases ends up downloading the same hash named file)

As generally the extracted folder name brings the correct name, it would be awesome if nzbToMedia could rename downloaded files to the same as the folder they belongs to.

thanks in advance

**Comment by clinton-hall** [comment]
Have you tried running https://github.com/clinton-hall/GetScripts/blob/master/SafeRename.py before nzbToMedia? (if using NZBGet you can run multiple scripts in a defined order).

**Comment by alexandre-zia-movile** [comment]
Thanks for this advice, I've tested it and worked great.
