### ISSUE TITLE
user_script_clean not working with sickrage

### ISSUE THREAD

**Issue by ccwillia** [clinton-hall/nzbToMedia#1250]
I moved from sickbeard to sickrage and I noticed that folders are not being cleaned up after post processing is complete.  I did a git clone to get the latest nzbtomedia scripts and copied my existing configuration over.  I am using nzbtomedia with nzbget.  Below is the log which looks like a file or files is still being used even though I have the delay set to 120secs.  I can try increase that

2017-05-11 00:50:29 INFO    ::CLEANDIRS: Directory /volume1/downloads/complete/TV/Designated.Survivor.S01E20.720p.HDTV.x264-KILLERS-Obfuscated still contains 1 unprocessed file(s), skipping ...

**Comment by clinton-hall** [comment]
autoProcessMedia.cfg
```
[General]
    force_clean = 1
```

**Comment by ccwillia** [comment]
when i enable force clean the files are cleaned up before post processing is complete which results in missing epsoides.  I Have the usdelay set  to 120 secs but i have tried setting it to 600 secs and it doesn't seem to make a difference.

**Comment by ccwillia** [comment]
I figured out what was going on.  The version of Nzbget i was using did not show the additional sickrage settings and i wasn't using the default category "tv".  I copied the settings under "tv" in the autoProcessMedia.cfg to my category "TV" and now the cleanup is working as expected
