### ISSUE TITLE
Subs

### ISSUE THREAD

**Issue by Stonedestroyer** [clinton-hall/nzbToMedia#1252]
Is there a way to make nzbtomedia grab subs that are in .sub folder in tv shows and the extension is .sub and the filename is same.

**Comment by clinton-hall** [comment]
Please clarify what you want.
Is this for download of external subs, is this extraction of embedded subs, or is this just for the renaming of subs that are part of the download?

**Comment by Stonedestroyer** [comment]
It is just for renaming of the subs that are part of the download. Even though I have enabled subs on both medusa and nzbtomedia it doesn't seem to get it. Is this part of the medusa not picking it up? As it seems to move srt files over to postprocess folder but it seems like medusa/sickbeard isn't picking it up.

**Comment by clinton-hall** [comment]
Yeah, this is at medusa side. All this script is doing is to tell medusa/sickbeard where the download is. The actual renaming is done in medusa.

**Comment by Stonedestroyer** [comment]
Alright thank you, issue was solved at medusa side.
