### ISSUE TITLE
Transcoding failed with result 1

### ISSUE THREAD

**Issue by dadthegamer** [clinton-hall/nzbToMedia#1253]
Every time the script attempts to trans-code it fails with result 1. 

Also I seen this error under the previous: PLEX: Attempting to update Plex Library for category cp.

**Comment by clinton-hall** [comment]
please enable debug logging (settings, general, "log_debug" = 1) then check the logs when a PP fails.

Right before the failure it should print out the actual ffmepg command being called. You can try running this manually to find out what is failing, or otherwise post here.
