### ISSUE TITLE
Update status different on NZBGet and in .py file

### ISSUE THREAD

**Issue by rEes9P** [clinton-hall/nzbToMedia#1254]
I was looking into whether I needed to update my nzbToMedia scripts, even though this option is enabled in my NZBGet configuration, when I noticed something strange. While this option is enabled under NZBGet (auto_update is set to 1 for both _nzbToMedia_ and _nzbToSickBeard_), when I open the _nzbToMedia.py_ and _nzbToSickBeard.py_ files it shows auto_update=0!

Any ideas what is going on? Thanks!

**Comment by clinton-hall** [comment]
the `*.py` files are not to be edited and DO NOT contain any settings... these lines you are looking at are simply what NZBGet reads to display available options.

The actual settings/configuration are stored in autoProcessMedia.cfg
If you look at this file, under `[General]` you should see `auto_update = 1`
