### ISSUE TITLE
After switching from nzbtosickbeard to nzbtomedia for better FDH but still doesn't work

### ISSUE THREAD

**Issue by pvdochtend** [clinton-hall/nzbToMedia#1257]
From nzbget post-processing is started.
NZBToMedia detects failed download (correct) and try to mark as failed in sickrage.
Then responds with an error  (see attached log files) you also see a successful post-process....
So it almost works :D

[nzbtomedia.log.txt](https://github.com/clinton-hall/nzbToMedia/files/1038371/nzbtomedia.log.txt)
[sickrage.log.txt](https://github.com/clinton-hall/nzbToMedia/files/1038372/sickrage.log.txt)

**Comment by clinton-hall** [comment]
In SickRage, do you have the option enabled for Failed Downloads?
Found in config, search, "Use Failed Downloads"

**Comment by pvdochtend** [comment]
Yep. That is activated

Op za 3 jun. 2017 om 14:58 schreef Clinton Hall <notifications@github.com>

**Comment by clinton-hall** [comment]
ok, try enabling debug logging
in autoProcessMedia.cfg
```
[General]
    log_debug = 1
```
and in NZBGet web UI, under settings, NZBTOMEDIA, set `sbfork` = `auto`

**Comment by pvdochtend** [comment]
I have turned it on but didn't help. I have attached the log files again but also the config files of NZBToMedia 



[LOGSandConfigs.zip](https://github.com/clinton-hall/nzbToMedia/files/1056064/LOGSandConfigs.zip)




and Sickbeard
