### ISSUE TITLE
Automation is not adding movies

### ISSUE THREAD

**Issue by mbeebe43083** [clinton-hall/nzbToMedia#1259]
### Steps to reproduce:
1. Install couchpotato on Ubuntu 17.04
2. Automation fails to add movies.
3. Tried complete delete of all couchpotato and settings and reinstall with no luck.

### Information:
Movie(s) I have this with: Any automation adding
Quality of the movie being searched: 1080p
Providers I use: nzb.su and Dognzb
Version of CouchPotato: git:(CouchPotato:CouchPotatoServer develop) f0d7eddc (2017-05-29 16:27:02)
Running on: Ubuntu 17.04

### Logs:
```
06-02 12:14:53 DEBUG [couchpotato.core.settings] Property "automation.cached.martin scorsese's world cinema project, no. 2.1931" doesn't exist: Traceback (most recent call last):
RecordNotFound: Not found
 
```

I am not sure if this is the issue or not, but automation used to work.

**Comment by clinton-hall** [comment]
looks like a corrupt database in CouchPotato? Not related to nzbToMedia.

**Comment by mbeebe43083** [comment]
Sorry, I posted to the wrong git.
