### ISSUE TITLE
CLEANDIRS keep deleting the original files

### ISSUE THREAD

**Issue by HeavensNight** [clinton-hall/nzbToMedia#1260]
Hi.
im using nzbmedia with couchpotato and need to keep the original files.
my postprocess is simple, i use nzbtomedia to talk to couchpotato to make symlink form couchpotato destination folder to download folder and is working until CLEANDIRS keep deleting the original files.
I've tried pretty well every combination of settings to disable CLEANDIRS option, but can't seem to avoid the folder itself being removed,

here is my config:
        force_clean = 0
        Torrent_NoLink = 1
        keep_archive = 1
        method = renamer
        delete_failed = 0
        wait_for = 2
        extract = 1
        minSize = 0
        delete_ignored = 0
        remote_path = 0
        watch_dir = ""
        chmodDirectory = 0

and the logs:
INFO    ::MAIN: SEARCH: Found torrent directory XXXXXXX.1080p.BluRay.x264-XXX in input directory directory D:\Download\movies
INFO    ::MAIN: SEARCH: Setting inputDirectory to D:\Download\movies\XXXXXXX.1080p.BluRay.x264-XXX
INFO    ::MAIN: Auto-detected SECTION:CouchPotato
INFO    ::MAIN: Output directory set to: D:\\Download\movies\XXXXXXX.1080p.BluRay.x264-XXX
INFO    ::MAIN: FLATTEN: Flattening directory: D:\\Download\movies\XXXXXXX.1080p.BluRay.x264-XXX
INFO    ::MAIN: Found 1 media files in D:\\Download\movies\XXXXXXX.1080p.BluRay.x264-XXX
INFO    ::MAIN: Calling CouchPotato:movies to post-process:XXXXXXX.1080p.BluRay.x264-XXX
INFO    ::MAIN: Attemping imdbID lookup for XXXXXXX.1080p.BluRay.x264-XXX
INFO    ::MAIN: Searching folder and file names for imdbID ...
INFO    ::MAIN: Searching IMDB for imdbID ...
POSTPROCESS::COUCHPOTATO: Starting renamer scan for XXXXXXX.1080p.BluRay.x264-XXX
POSTPROCESS::COUCHPOTATO: SUCCESS: Finished renamer scan for folder D:\Download\movies\XXXXXXX.1080p.BluRay.x264-XXX
POSTPROCESS::COUCHPOTATO: Checking for status change, please stand by ...
POSTPROCESS::COUCHPOTATO: SUCCESS: Movie None has now been added to CouchPotato
INFO    ::CLEANDIRS: Directory D:\\Download\movies\XXXXXXX.1080p.BluRay.x264-XXX has been processed, removing ...
::MAIN: The C:\nzbToMedia\TorrentToMedia.py script completed successfully.

**Comment by clinton-hall** [comment]
Try setting [Torrent] outputDirectory = D:\Processed
or something similar. the Output directory should not be the same as the download directory.
This was, the files are linked, processed from the output directory and then this directory is cleaned up and the original files are left in place.

In this configuration you should set [Torrent] UseLink = sym
and in CouchPotato, renamer, you should set Default File Action = Move and Torrent File Action = Move.

**Comment by HeavensNight** [comment]
Hi.
This config keeps original file in the download folder, what i want is move original file to couchpotato destination folder and create sym link in place of the original file.
with the config i have i can do that, just fail in the cleardirs part. 
i like this config because i can delete the torrent in the future and only delete the symlink not the movie. 

Thanks so much for your help.

**Comment by clinton-hall** [comment]
Ok, try this:
[Torrent] 
outputDirectory = D:\Processed
UseLink = move-sym

CouchPotato, renamer, you should set Default File Action = Link and Torrent File Action = Link

This will move the file to D:\Processed and link the original torrent location to this. Then CP will move the file and link back at D:\Processed, finally, this script will recurse the links so that the original torrent file links direct to the renamed media file (not D:\Processed) and then cleandirs will clean up D:\Processed

or, the other thing to consider is using hardlinks...
[Torrent] 
outputDirectory = D:\Processed
UseLink = hard

CouchPotato, renamer, you should set Default File Action = move and Torrent File Action = move

I personally recommend this, as long as your final media location is on D:\

**Comment by HeavensNight** [comment]
i was testing UseLink = move-sym but the symlink only link to the process folder not to the seed folder, and i cant use hardlinks because im using drivepool and is not compatible..
i think i have to restore all and remove the drivepool, because i have it working for months before with hardlinks..

Thanks so much for your help clinton-hall.
