### ISSUE TITLE
AttributeError: 'module' object has no attribute 'LOG_FILE'

### ISSUE THREAD

**Issue by jangrewe** [clinton-hall/nzbToMedia#1261]
I haven't checked when this started (running `nightly` with autoupdate), but i'm getting the following error when using Deluge with the Execute plugin to postprocess torrents:

```
[WARNING ] 16:38:31 core:132 [execute] command '/opt/nzbToMedia/TorrentToMedia.py' failed with exit code 1
[WARNING ] 16:38:31 core:136 [execute] stderr: Traceback (most recent call last):
  File "/opt/nzbToMedia/TorrentToMedia.py", line 9, in <module>
    from core import logger, nzbToMediaDB
  File "/opt/nzbToMedia/core/logger.py", line 249, in <module>
    ntm_log_instance = NTMRotatingLogHandler(core.LOG_FILE, NUM_LOGS, LOG_SIZE)
AttributeError: 'module' object has no attribute 'LOG_FILE'
```

The torrent is not being processed after this error.

**Comment by clinton-hall** [comment]
can you check that you have the file `/opt/nzbToMedia/core/__init__.py`
this file should be loaded on script run, and defines the `LOG_FILE`

**Comment by jangrewe** [comment]
yes, that is present and looks untouched, like in this repo.
The scripts are working fine when called from SABnzbd, as those downloads are processed and i see the log output for them. Only torrents from Deluge give this error.

**Comment by clinton-hall** [comment]
ok... can you try running the torrent script manually
`/opt/nzbToMedia/TorrentToMedia.py`
and see if this gives the same error... try as the same user that runs nzbget and the user that runs deluge...

As a guess, if NZBGet ran first, it may have created the log directory, and the log file... so Deluge may not have permissions to access this directory and file... try opening permissions on this folder and file to allow deluge user to access...

**Comment by jangrewe** [comment]
That fixed it indeed! Now i'm afraid that the next log rotation will recreate the logfile with the old permissions. Is that something that the logging facility could handle? It had the permission 0600 for the user that SABnzbd is running as. Maybe the logger could create it with 0666?
