### ISSUE TITLE
Extracted subs - 2 char country code instead of 3 

### ISSUE THREAD

**Issue by kocane** [clinton-hall/nzbToMedia#1263]
My subtitle downloader for plex (sub-zero) which works pretty well seem to use 2 letter country codes for subtitles where-as nzbToMedia uses 3. I've till now used embedded subs but since Apple TV and Chromecast seem to have a dislike for this (occording to my experience, atleast a dislike to mov_text) then I want to begin extracting them instead. However, since the extracted sub is named .eng.srt it means that sub-zero downloads one called .en.srt. Not a massive problem but still unnessary since the extracted subtitle will likely always prevail in terms of sync.

Is it possible to change this in nzbToMedia? Will it cause other trouble?

**Comment by kocane** [comment]
A little extra question; got does the extractor deal with multiple subtitles of same lang? The  videofile sample I got here contains two english subtitles, one having "SDH" in the title. It seems like the output is just one of the subtitles, the one without hearing impairing. Does the script sort it out, or?

**Comment by clinton-hall** [comment]
The extraction of subs should extract all (both) subs that are tagged as english.

I'll need to look into the sub naming to see if 2 char country codes can be supported. This is actually done by an external tool `subliminal` so I'll need to look into this to see if we can pass any additional options.

**Comment by kocane** [comment]
@clinton-hall thanks for the quick reply. I'll look forward to find out what you discover. I figured that rather than getting Sub-Zero to change to a different standard, it'd be faster to get help from you :-) 

I got a whole bunch of old videofiles that contains embedded subs. Are there an "easy" command to extract subs from all files in a folder and name them accordingly?
