### ISSUE TITLE
[Question] chmodDirectory

### ISSUE THREAD

**Issue by ghultstrand** [clinton-hall/nzbToMedia#1265]
I'm having problems with permissions on my system and I am curious as to what the command chmodDirectory does and can the sonarr and radarr group use it?

Is this the correct use?
chmodDirectory = 2777

**Comment by clinton-hall** [comment]
I think the 2 will cause the system/sticky bit to be set... I would just set either `0777` or `777`
See if this helps, but this should mean all users have read, write, and execute permissions.

**Comment by ghultstrand** [comment]
Does it have to be the numerical or can it be g+rwx?

**Comment by clinton-hall** [comment]
this used the python os.chmod which takes a numeric value. Further, the scripts here convert the cobfig value to Octal so I believe this has to be set as 0777 or you can try 2777 and this should work... give it a go.

**Comment by ghultstrand** [comment]
chmodDirectory = 0775 worked perfectly. Thanks
