### ISSUE TITLE
nzbToMedia/nzbToRadarr: Exception TypeError: "'NoneType' object is not callable"

### ISSUE THREAD

**Issue by dabigc** [clinton-hall/nzbToMedia#1266]
I've looked through the open and closed issues and can't find a reason why this would have just started today when Radarr post processing has been working for me for weeks/months. I performed a clean install this morning and still get the same issue. I can provide debug logs or anything else needed as I run with those enabled.

`nzbToMedia/nzbToRadarr: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7f2ddb9b8790>> ignored`

The file is then deleted and blacklisted in Radarr.

I should note that Sonarr processing is just fine.  Just checked that. I'm also running the nightly branch and have been since Radarr first came out.

UPDATE: I rolled back to a previous version/config that I had and it's working again as expected. Before these failures occurred, there were some IMDB lookups failing. This was a FRESH install from the Nightly branch today and it wasn't working as expected. I'm more than willing to test this out and send logs/configs over if it's helpful. Otherwise this can be closed.

**Comment by clinton-hall** [comment]
Can you post more of the logs (from before the error you posted above)?
There may be a problem with a recent commit, but I can't see where the issues is, so I need to see just where this has been failing.

**Comment by clinton-hall** [comment]
ok... I think I found it... please update to latest nightly and test.

**Comment by dabigc** [comment]
Hi @clinton-hall 

Unfortunately it's the same error with a fresh install this morning of the nightly build. I setup the autoProcessMedia.cfg file from scratch too. I only use Sonarr and Radarr processing in the script so I just have my API keys/username and password (for Sonarr) in the config. Otherwise it's a stock config. Here's the error from the logs. Same as yesterday.

`Thu Jun 15 2017 10:12:59	Post-process-script nzbToMedia/nzbToMedia.py for REDACTED failed (terminated with unknown status)
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7f920bc52f50>> ignored
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: TypeError: find_imdbid() takes exactly 3 arguments (2 given)
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: imdbid = find_imdbid(dirName, inputName)
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: File "/config/scripts/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 164, in process
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: inputCategory, failureLink)
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: File "/config/scripts/nzbToMedia/nzbToMedia.py", line 671, in process
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: failureLink=failureLink)
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: File "/config/scripts/nzbToMedia/nzbToMedia.py", line 773, in main
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: exit(main(sys.argv))
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: File "/config/scripts/nzbToMedia/nzbToMedia.py", line 872, in <module>
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: Traceback (most recent call last):
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [INFO]::MAIN: Calling Radarr:Movies to post-process:REDACTED
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DEBUG]::MAIN: Checking for archives to extract in directory: /media/hdd/tempcache/radarr/REDACTED
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [INFO]::MAIN: Auto-detected SECTION:Radarr
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DB]::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (status, client_agent, last_update, input_id, input_hash, input_name, input_directory) VALUES (?, ?, ?, ?, ?, ?, ?) with args [0, u'nzbget', 736495, u'181c96e0a78140748c779bbcf4b44eb7', u'181c96e0a78140748c779bbcf4b44eb7', u'REDACTED', u'/media/hdd/tempcache/radarr/REDACTED']
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'nzbget', 736495, u'181c96e0a78140748c779bbcf4b44eb7', u'181c96e0a78140748c779bbcf4b44eb7', u'REDACTED', u'/media/hdd/tempcache/radarr/REDACTED']
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DEBUG]::MAIN: Adding NZB download info for directory /media/hdd/tempcache/radarr/REDACTED to database
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [INFO]::MAIN: Script triggered from NZBGet Version 19.0-testing-r2008.
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/config/scripts/nzbToMedia/nzbToMedia.py']
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [INFO]::MAIN: #########################################################
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [INFO]::MAIN: #########################################################
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [WARNING]::MAIN: Failed to locate ffmpeg. Transcoding disabled!
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [INFO]::MAIN: nzbToMedia Version:11.03 Branch:nightly (Linux 4.4.0-79-generic)
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [INFO]::MAIN: No update needed
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DEBUG]::MAIN: No git specified, can't use git commands
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [INFO]::MAIN: Checking if git needs an update
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DEBUG]::MAIN: No git specified, can't use git commands
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DEBUG]::MAIN: Unable to find your git executable - Set git_path in your autoProcessMedia.cfg OR delete your .git folder and run from source to enable updates.
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DEBUG]::MAIN: Not using: "/usr/bin/git"
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DEBUG]::MAIN: Executing "/usr/bin/git" version with your shell in /config/scripts/nzbToMedia
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DEBUG]::MAIN: Checking if we can use git commands: "/usr/bin/git" version
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DEBUG]::MAIN: InitialSchema upgrade not required
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [DEBUG]::MAIN: Checking Initial Schema database upgrade
INFO	Thu Jun 15 2017 10:12:59	nzbToMedia/nzbToMedia: [15:12:59] [INFO]::MAIN: Checking database structure...
INFO	Thu Jun 15 2017 10:12:54	Executing post-process-script nzbToMedia/nzbToMedia.py for REDACTED`

**Comment by clinton-hall** [comment]
ok... sorry for this. The recent OMDB Api changes were done against master, and when I changed this to go against nightly this line was missed!
Hopefully fixed now. Please update and test.

**Comment by dabigc** [comment]
Looking good! I was just able to test and it's working as expected again. Thank you very much @clinton-hall and all the other contributors on this project. Your time and work is very much appreciated!
