### ISSUE TITLE
Error when running nzbTomedia manually

### ISSUE THREAD

**Issue by obiwan866** [clinton-hall/nzbToMedia#1267]
Hi all, 

trying to post-process movies from couchpotato i get this error

Traceback (most recent call last):
  File "nzbToMedia.py", line 872, in <module>
    exit(main(sys.argv))
  File "nzbToMedia.py", line 824, in main
    clientAgent = text_type(core.DOWNLOADINFO[0].get('client_agent', 'manual'))
AttributeError: 'sqlite3.Row' object has no attribute 'get'

I tried to switch on nightly build but i get the same error.

Any ideas ?

Thanks in advance.

**Comment by clinton-hall** [comment]
Odd... can you try deleting nzbtomedia.db, then test again?

**Comment by obiwan866** [comment]
Hi Clinton,

After a new pull & deleting nzbmedia.db, everything is working fine again. Thank you !
