### ISSUE TITLE
"'NoneType' object is not callable"

### ISSUE THREAD

**Issue by dabigc** [clinton-hall/nzbToMedia#1268]
This is a new one I've started seeing today with Radarr processing. The issue looks to be with the list indices being integers. It's happening on every file from Radarr, triggering Radarr to delete the "failed download", download another and do this all over. Any help is appreciated.

I'm running 11.03 nightly.

https://pastebin.com/Q9YnRcbx

**Comment by dabigc** [comment]
I realized that Radarr had a [pretty significant update on June 20th](https://github.com/Radarr/Radarr/releases/tag/v0.2.0.778). I've been working on other types of files lately so I didn't notice this was chewing through movies here and there throughout. I use Docker for everything so I went ahead and rolled back Radar to the previous version from May 12th. With no other changes, this is resolved. I think the new v2 API that they've implemented in this Radarr update is the root of this issue. I can test back and forth on Radarr and nightly updates if you need someone to do so.

**Comment by clinton-hall** [comment]
Thanks for reporting.

Without reading through the code, I can't really see any detail as to the V2 api usage.
Hopefully Radarr team will publish this shortly and I'll be able to implement.

Basically I need to know the format of the api command for scanning downloaded movies, and the forma of the output.

**Comment by dabigc** [comment]
Hey @clinton-hall,

This was figured out in #1272 as an issue for those of us using reverse proxies. I'm not sure what the etiquette is here since you've added labels on this but I'm pasting the same thing from #1272 below and closing this.

As @neox387 and @digitalface stated in #1272, this is an issue for those with reverse proxies. While I've never been able to use nzbToMedia when the webroot setting was defined, the current version of Sonarr AND Radarr now ONLY work with nzbToMedia if the webroot is defined. I've updated both, defined the webroot address in autoProcessMedia.cfg and they're now working beautifully. As far as I can tell this is ready to be closed.
