### ISSUE TITLE
Transcoding - Default Profile

### ISSUE THREAD

**Issue by breezytm** [clinton-hall/nzbToMedia#1269]
Hey Clinton, 

Is there any way you can set the preset profiles to not make a second audio file if the original file only consists of a stereo track. I mean what's the point of having an AC3 secondary track if it's stereo as well as well as the primary AAC?

**Comment by clinton-hall** [comment]
I hear what you are saying...
I think this comes back to a revamped transcoder whereby the output has more dependence on the input...
well, more accurately, the output PROFILE is dependent on user defined input format criteria.

With the current setup, this isn't really a simple change.. I need to try and get my head around a better means to handle the Transcoder

**Comment by breezytm** [comment]
How about using ffprobe to check the audio tracks and base on that result the transcoder can select what to do base on a list of predefined options. 

If audio is DTS, AC3, AAC  and higher or equal to 6 channels, 
then 
Transcode using profile 1

If audio is AAC stereo 
then 
Transcode using profile 2

I know it sounds easier said than done :)

**Comment by clinton-hall** [comment]
Yeah, I do that for most part... i.e. check with ffprobe to check audio, video, and subtitles.
The problem is I only support the 1 profile (to either copy the stream, or transcode the stream). I don't have a way to define the multiple profiles.

Basically, right now it just allows you to define the number of audio tracks you want, and what codec to use.

**Comment by breezytm** [comment]
Yeah sounds like the transcode going to need some work. I guess for now I have to manually remove the second track after the transcoding process is completed. I'll just wait for whenever you get a chance to work on it. 

Thanks for looking into it man. Appreciate it.
