### ISSUE TITLE
Failed downloads cause downloads of lesser quality versions

### ISSUE THREAD

**Issue by Sarcas666** [clinton-hall/nzbToMedia#1270]
Not sure if this is a bug, configuration mistake on my part or something else...
I am on MacOs 10.12.5, currently running SickRage v2017.06.05-1 and SABnzbd v2.2.0, but the issue has been always a problem.

Description of the problem:
I am dl-ing some series. Allowed quality 720 hdtv, webdl, bluray, preferred 1080 hdtv, webdl, bluray. 
SR finds an episode, for example 720 hdtv. Downloads and post processes fine. A while later SR finds a 1080 hdtv version, downloads that. All still fine. Now it finds a 1080 bluray, and starts to dl. But it fails. The script tries the next best, and the next best etc. Until there is a point download starts of the best version I already had, or worse. And since it is somehow a priority download now it replaces the better versions with lower quality versions. At a certain point the downloading stops, when it can no longer find non-failed nzb's I guess. 
How can I prevent the downloading of the same or lower quality version? 
An additional problem for me is that I have a low dl-speed and am on a data-plan (no dal or cable here in my area) and the repeated useless downloads waste my available data I can dl.

Thanks for any advice.

**Comment by clinton-hall** [comment]
This sounds like a SickRage issue? Not sure why it is continuing to download, or why it is failing...
Would need to look at the logs to see what is going on.
