### ISSUE TITLE
QQ: anyone using utserver linux with nzbToMedia?

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1271]
I've been running into a weird issue which only started recently although my configuration has been the same for years on the utserver side.
python keeps going defunct, and the major symptom was the SickRage web UI does not respond.
reported to SR and we've been troubleshooting.
I used some api scripting against utserver which i can't seem to find the same support for in other client, hence my not wanting to move away. it does all the things i need.
I don't know if this is a utserver or a combo thing, i'm still monitoring since disabled utserver to see if it still happens.
Anyone else using utserver linux and nzbToMedia, looking for confirmation its working with other people?

**Comment by c0m3d1an** [comment]
I use utserver with sonarr, and get defunct pythons all the time from utserver.  I run all my other stuff in Dockers, because isolation, why not?

I have a cron script that restarts utserver daily automagically because of the <defunct> issues...

**Comment by mgaulton** [comment]
ok, so that's not unique to me. I'm having a weird SR issue that i thought might be related to that but maybe i've just never noticed it before. Thanks.

**Comment by c0m3d1an** [comment]
Definitely not unique to you.  I haven't used Sickrage / SickGear / Medusa in quite a while though.
