### ISSUE TITLE
NZBDRONE: No scan id was returned due to: list indices must be integers, not str

### ISSUE THREAD

**Issue by dabigc** [clinton-hall/nzbToMedia#1272]
Sonarr released an update today that seems to have broken communication from nzbToMedia with the errors in the log below. I'm running Docker and reverted to a previous release and everything is good with no changes to anything for nzbToMedia.

https://pastebin.com/dDBisvnb

Any help is appreciated.

**Comment by c0m3d1an** [comment]
I use NZBToNZBDrone with Sonarr 2.0.0.4855 and have zero issues.  (Python 2.7.11).

**Comment by ghultstrand** [comment]
Can confirm. "[11:39:38] [WARNING]::NZBDRONE: No scan id was returned due to: list indices must be integers, not str"

Debian 8
Sonarr Version 2.0.0.4855
Mono Version 4.8.1
NzbtoMedia: Nightly Build

**Comment by neox387** [comment]
same issue

**Comment by digitalface** [comment]
Am getting the exact same error, since last Sonarr update.

**Comment by digitalface** [comment]
I've downgraded to the previous Sonarr release on my 4 devices and post processing now works, so I would  advise others to do the same until nzbtomedia is fixed

**Comment by neox387** [comment]
@digitalface how did you do this ? I'm using windows version

**Comment by digitalface** [comment]
I'm using a raspberry pi, so a linux OS, but essentially I stopped Sonarr running and replaced the core files with an older release from a zip file

Here's a Windows release http://download.sonarr.tv/v2/master/windows/NzbDrone.master.2.0.0.4753.windows.zip

**Comment by neox387** [comment]
tnx but sadly windows versions will auto update itself cannot turn it off :/
I guess the problem is in this:
https://github.com/Sonarr/Sonarr/commit/eea34198495ca03b3765334a28481eb56f1b20db

**Comment by neox387** [comment]
Fixed, in autoProcessMedia.cfg webroot wasn't configured

changed to my configured sonarr url: web_root = /tv  and all working again 👍

**Comment by digitalface** [comment]
Haha, yep, that fixed it for me too

I guess this issue only affected those using reverse proxies

**Comment by dabigc** [comment]
As @neox387 and @digitalface stated, this is an issue for those with reverse proxies. While I've never been able to use nzbToMedia when the webroot setting was defined, the current version of Sonarr AND Radarr now ONLY work with nzbToMedia if the webroot is defined. I've updated both, defined the webroot address in autoProcessMedia.cfg and they're now working beautifully. As far as I can tell this is ready to be closed.

**Comment by clinton-hall** [comment]
Thanks all for posting the solution.
Sorry I didn't get a chance to look into it, but glad it is resolved for you.

**Comment by bitchkat** [comment]
This is happening for me now with radarr 5.3.6.8612.  I am adding this comment in case someone finds this page like I did so they can go look at https://github.com/clinton-hall/nzbToMedia/issues/1988  The Radarr API being called is return an array of objects but the nzbtomedia code is expecting an object.
