### ISSUE TITLE
Is it possible to set multiple DIR for default_downloadDirectory  ??

### ISSUE THREAD

**Issue by seanvree** [clinton-hall/nzbToMedia#1280]
Just as the title states, 

Is it possible to set multiple directories in the torrent -> Deluge -> default_downloadDirectory section?

If my torrent client downloads to different directories based on it's label, this would be useful. 

Thanks!

**Comment by mgaulton** [comment]
I did this using labels with UT so each section has its own download dir.

**Comment by clinton-hall** [comment]
The way this script works, `default_downloadDirectory` is for non-category (label) downloads, and is used to protect these from being processed.
The category/label downloads should be processed...

in addition, for each label you can set this in the `watch_dir` parameter for each category
```
[CouchPotato]
    [movies]
        watch_dir

[SickBeard]
    [TV]
        watch_dir
```
