### ISSUE TITLE
Issue opening the .py files after fresh SG install

### ISSUE THREAD

**Issue by Th3MadHatter** [clinton-hall/nzbToMedia#1281]
After Sickgear moving to temporary github I figured I'd install from scratch as they suggested on a Win7 platform with 64 bit installers, the only difference is that they're using ActivePython as their main Python source now. So as suggested here https://github.com/SickGear/SickGear.Wiki/wiki/Install-SickGear-%5B1%5D-Windows I followed all the steps and installed all the latest versions.
After installing it everything was up and running again, snatched something, it finished but instead of getting the normal python popup window I get an installer window saying it requires ...something unknown... and the installer just goes into a loop.
Any idea what could be wrong with it? All .py files from NzbToMedia seem to open the installer now.
No logs available because I can't even get it to start anymore, nothing works. 
I tried to redownload all dependencies but that didn't help, python version 2.7.13 x64.

**Comment by Th3MadHatter** [comment]
Workaround: Removed ActivePython, installed Python from the main Python website, same setup, works perfectly fine.

Might be worth looking in to whats happening with ActivePython though.

**Comment by clinton-hall** [comment]
I note they state the following:
```
ActiveState Python 2.7.13 deprecated the following...

    pypm (1.4.3)
    pythonselect (1.3)
    pywin32 (218.3)
```

nzbToMedia requires `pywin32` so this is likely the issue...
