### ISSUE TITLE
Ignore new _UNPACK_ folders

### ISSUE THREAD

**Issue by KaraokeStu** [clinton-hall/nzbToMedia#1283]
Hi,

sabnzbd 2.2.x has an auto-unpack feature, which starts live-unpacking the RAR files into the destination folder during download.

Can these _UNPACK_ folders be excluded from the scanner, when completed, they are renamed from _UNPACK_ to the correct name.

Cheers!

Stu

**Comment by clinton-hall** [comment]
I can add an ignore for this... but why?
nzbToMedia isn't called until after unpack has finished anyway. So it should never deal with the _UNPACK_ folders.

**Comment by KaraokeStu** [comment]
It is more for when you have called a manual script run, that's all :)

**Comment by clinton-hall** [comment]
Can you show logging from when the script has processed the _UNPACK_ directory?
I can't see how the script would do this.
I need to see an example of just where the _UNPACK_ is created in the final output directory structure.
