### ISSUE TITLE
Renaming file to folder name

### ISSUE THREAD

**Issue by kocane** [clinton-hall/nzbToMedia#1285]
I'm trying to keep original filenames for better subtitle downloading. Problem is as we all know that sometimes the files downloaded come with either very undescriptive or obfuscated filenames. Now it's my understanding that nzbToMedia has a measure to rename obfuscated names - which I'm testing atm - but how about the non-obfuscated but just 'poor' filenames. For instance I got this test movie I found which has a nzb/folder name of "Cowboys.and.Aliens.Extended.2011.German.AC3.HDRip.XviD-AJA" but the actual videofile is called caa-xvid-aja.avi and this _wasn't_ renamed by nzbToMedia.

I've looked into the nzbget script called videosort but I don't know how well it'd work with nzbToMedia, and besides it offers some functionality I don't really need.

**Comment by kocane** [comment]
It also seems like an obfuscated video with the name of 
```
1.5DD.piRBEW.p0801.)7102(.TNEGA.mp4
```
. Am I missing something? I can't find any settings for this functionality. 

Thanks

**Comment by clinton-hall** [comment]
This would need to be added as a new feature.

If using couchpotato you could set renamer "file name" to be "<original foldername>.<ext>"

**Comment by kocane** [comment]
@clinton-hall  - What does "." do in couchpotato do? Rename to original foldername?

Regardless, I would feel much more comfy with your script doing it - I'll happy beta test any added functionaility. I don't know if it's possible to make it only do the renaming if the file doesn't already contain the scene release name and if the folder it's within actually contains the right name.

**Comment by clinton-hall** [comment]
Sorry for this, I didn't wrap the renaming above and github hid it.

If using couchpotato you could set renamer "file name" to be `<original foldername>.<ext>`

**Comment by kocane** [comment]
@clinton-hall 
I'm not sure what's best. Doesn't seem like folder names are always named correctly, either. Right now I just rely on the filename being original from the download source which isn't really realiable so this functionaility would be greatly appreciated, but I can see why it isn't simple. For instance, a torrent download had the name of **"The.Testament.Of.Dr.Mabuse.1933.720p.BluRay.x264-PSiF [PublicHD]"** and the [PublicHD] would have to be excluded from the renaming, I guess.
