### ISSUE TITLE
Avoid having "-transcoded" appended to name

### ISSUE THREAD

**Issue by kocane** [clinton-hall/nzbToMedia#1288]
What must I do in order to make it so the transcoded file does not end out with having -transcoded in the end of its filesname? I've set CP and Medusa to keep original names. Obviously it's because ffmpeg can't output to the same filename as the input file, which explains why it's only appended sometimes (when the input file is mp4 as well), I guess.

**Comment by clinton-hall** [comment]
Set the output directory in Transcoder to be another location.

```
[Transcoder]
    outputVideoPath = new_path_here
    processOutput = 1
```

**Comment by kocane** [comment]
Of course, silly me. Thanks!
