### ISSUE TITLE
Ability to use check_media for only one category

### ISSUE THREAD

**Issue by duramato** [clinton-hall/nzbToMedia#1292]
I only want to check for media files only for one of my configured categories.

**Comment by clinton-hall** [comment]
What downloader?
It might be possible to have multiple versions of the script (1 configured for check_media =1 and one configured for check_media = 0), then call the different script for different categories?
This is possible in NZBGet and SABnzbd.

**Comment by duramato** [comment]
I'm using sabnzbd and Transmission.
I want to enable check_media for the sabnzbd category but not for Transmission one.

**Comment by clinton-hall** [comment]
In this case, the easiest way is to clone nzbToMedia into 2 locations.

Set up sabnzbd to call location 1 (set up for check_media = 1)
and set Transmission to call the other location (set up for check_media = 0)

**Comment by duramato** [comment]
But that way it won't queue right? If both finish a download at the same time they will both try to process it?
