### ISSUE TITLE
QQ: what am I doing wrong?

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1293]
So i have utserver call a bash script to pre-parse just to speed things up a bit but it apparently never fires
Any suggestions?

called with this
/opt/torproc.sh "%D" "%N" "%L" "%I"

#bin/sh 
echo "$1 " " $2 " " $3 " " $4 " "$5" |tee -a  /tmp/utorrent/uttest.log

#/opt/nzbtomedia/nzbToMedia/TorrentToMedia.py  "%D" "%N" "%L" "%I"
if [ "$3" == "comics" ] || [ "$3" == "TV" ] || [ "$3" == "Movies" ] ||  [ "$3" == "Anime" ] ||[ "$3" == "Music" ]   ; then
    /opt/nzbtomedia/nzbToMedia/TorrentToMedia.py   "$1" "$2" "$3" "$4" &
fi

**Comment by clinton-hall** [comment]
I haven't had a lot of success with utserver.

I do know there was a bug where the 1st passed variable was ignored, so if that is the case still, `$5` would be undefined and would cause an error in the first line (no logging made).
You could verify this calling the same script with
`/opt/torproc.sh "%D" "%D" "%N" "%L" "%I"`
and see if this logs correctly, and indeed runs TorrentToMedia correctly.

**Comment by mgaulton** [comment]
I remembered that and tried it, it doubled the first parameter and it didn't like it. I'll revert and play around. Thanks                                                                                                                                                                         Sent from my BlackBerry - the most secure mobile device - via the Rogers Network                                                                                                                                                                            From: notifications@github.comSent: August 27, 2017 8:06 AMTo: nzbToMedia@noreply.github.comReply-to: reply@reply.github.comCc: markgaultonsecurity@gmail.com; author@noreply.github.comSubject: Re: [clinton-hall/nzbToMedia] QQ: what am I doing wrong? (#1293)  I haven't had a lot of success with utserver.
I do know there was a bug where the 1st passed variable was ignored, so if that is the case still, $5 would be undefined and would cause an error in the first line (no logging made).
You could verify this calling the same script with
/opt/torproc.sh "%D" "%D" "%N" "%L" "%I"
and see if this logs correctly, and indeed runs TorrentToMedia correctly.
