### ISSUE TITLE
NzbDrone - Clarification on "ndCategory" purpose

### ISSUE THREAD

**Issue by bengalih** [clinton-hall/nzbToMedia#1297]
So I (incorrectly?) assumed that the ndCategory ([[tv]]) for use with NzbDrone was used to control which labels the script would execute on.

As you are aware the deluge Execute script is scoped for all torrents, not just a particular label.

If I manually add a torrent into a different label (or no label at all) and set it to a different download directory, then NTM logs the following:

`
2017-08-31 01:22:05 ERROR   ::MAIN: Unable to locate a section with subsection:UNCAT enabled in your autoProcessMedia.cfg, exiting!
2017-08-31 01:22:05 ERROR   ::MAIN: A problem was reported in the D:\Program Files (x86)\nzbToMedia\TorrentToMedia.py script.
`

That is to be expected since the NTM script is executing on this file.

However, what I don't understand is if I add this same torrent with a different/no label, but choose as its download location the same watch_dir that [NzbDrone] uses, the file will get processed by the script.

I realize in practice you shouldn't be mixing your downloads, but this was done by accident and now I don't understand what the point of the ndCategory is if all it appears to need is to be placed into the directory that the ndCategory label uses for downloads.
?

**Comment by clinton-hall** [comment]
The answer here is that the category is used so that WHEN a downloader passes that category it will process it accordingly.

However, the issue is not all downloaders pass this label/category, so the script ALSO checks the directory structure for a match (when it can't find a category/match).

So the discrepancy you have found comes from the attempt to handle different configurations.

**Comment by bengalih** [comment]
Ok...this is one of the more confusing things about the configuration that I worked out.  So in the case of TorrentToMedia.py, this wouldn't be used at all I believe?  In fact that script only accepts a hash - not a label.  Technically (if you wanted to ) you could probably make a call to the torrent client (since you already do to pause it) to lookup the torrent based on the passed hash and then grab the label of it (assuming the client exposes that in the API, which I think they must).  This wouldn't work ofc if somehow the torrent got removed prior to the lookup, but it may be a good doublecheck or an option for those that don't rely on file strucutre.  There are more important things to work on...but just an idea :)
