### ISSUE TITLE
Media files not found if containing dir contains "sample"

### ISSUE THREAD

**Issue by dotsam** [clinton-hall/nzbToMedia#1299]
This has previously been raised in #1078 but was attributed to the destination application's post-processor. In fact, this happens before hand-off, in nzbToMedia's [listMediaFiles function](https://github.com/clinton-hall/nzbToMedia/blob/master/core/nzbToMediaUtil.py#L977). The [is_sample function](https://github.com/clinton-hall/nzbToMedia/blob/master/core/nzbToMediaUtil.py#L218) uses a regex to check if the filename being processed contains `sample`, but the problem here is that the full path of the file is passed to `is_sample`, thus a folder containing sample is enough to match.

There will be cases where there could be a `sample` directory inside a release directory that's being processed however, and that should be ignored. So logic needs to be developed so that if the original `path` passed through to listMediaFiles contains "sample", then `is_sample` doesn't return true, but if children directories/files do, then they still get triggered/ignored as normal.

If I have time, I'll see if I can come up with a pull request to resolve this, but I wanted to log the bug as there seems to be at least some active development happening.

**Comment by clinton-hall** [comment]
the issue here is the script recursively calls itself.
So in creating an ignore for the original path, we need to pass a new parameter that is maintained throughout recursive calls.
i.e. add an extra "originpath" at the end that is blank on first call, set to path, and then passed in (and unchanged) on subsequent drilling down into the sub directories...

**Comment by clinton-hall** [comment]
appreciate a pull request if you get a chance.
About to load everything I own into a 20' container and relocate to another country.... time is sparse....
