### ISSUE TITLE
Transcoder questions

### ISSUE THREAD

**Issue by jsaddiction** [clinton-hall/nzbToMedia#1302]
Following the wiki and installing ffmpeg and 7zip I am attempting to transcode only iso/bin files to mkv format and copy audio/subtitle tracks that are English and ensure h264 encoding for the video stream.  So far I have gotten the script to extract the VOB from the ISO but then it crashes.  Not sure what I am doing wrong here.

<pre>

info Wed Sep 13 2017 07:18:14 Deleting file /volume1/Downloads/nzb/Kesha-Rainbow-CD-FLAC-2017-PERFECT.nzb.queued 
detail Wed Sep 13 2017 07:12:08 Deleting https://api.nzbgeek.info/api?t=get&id=57ea1b8d45267f6b914f3e72563afb8a&apikey=64de166633d61c8326232568b42beef1 from feed history 
info Wed Sep 13 2017 07:09:14 Unpausing download after post-processing 
info Wed Sep 13 2017 07:09:14 Collection Central_Intelligence_2016_2in1_BluRay_1080p_AVC_DTS-HD_MA5_1-MTeam added to history 
error Wed Sep 13 2017 07:09:14 Post-process-script nzbToCouchPotato.py for Central_Intelligence_2016_2in1_BluRay_1080p_AVC_DTS-HD_MA5_1-MTeam failed (terminated with unknown status) 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7fb7012aea10>> ignored 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: IndexError: list index out of range 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: video_details, result = getVideoDetails(data['files'][0], img, bitbucket) 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: File "/volume1/Downloads/scripts/nzbToMedia/core/transcoder/transcoder.py", line 137, in buildCommands 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: command = buildCommands(file, newDir, movieName, bitbucket) 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: File "/volume1/Downloads/scripts/nzbToMedia/core/transcoder/transcoder.py", line 741, in Transcode_directory 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: result, newDirName = transcoder.Transcode_directory(dirName) 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: File "/volume1/Downloads/scripts/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 197, in process 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: inputCategory, failureLink) 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: File "/volume1/Downloads/scripts/nzbToMedia/nzbToMedia.py", line 618, in process 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: failureLink=failureLink) 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: File "/volume1/Downloads/scripts/nzbToMedia/nzbToMedia.py", line 718, in main 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: result = nzbToMedia.main(sys.argv, section) 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: File "/volume1/Downloads/scripts/nzbToMedia/nzbToCouchPotato.py", line 257, in <module> 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: Traceback (most recent call last): 
info Wed Sep 13 2017 07:09:13 nzbToCouchPotato: [07:09:13] [DEBUG]::TRANSCODER: Successfully extracted .vob file {'/volume1/Downloads/TempMovies/Central_Intelligence_2016_2in1_BluRay_1080p_AVC_DTS-HD_MA5_1-MTeam/Central.Intelligence.2016.2in1.BluRay.1080p.AVC.DTS-HD.MA5.1-MTeam.iso': {'files': [], 'name': 'Central.Intelligence.2016.2in1.BluRay.1080p.AVC.DTS-HD.MA5.1-MTeam'}} from disk image 
</pre>

<pre>
[Transcoder]
    # getsubs. enable to download subtitles.
    getSubs = 0
    # subLanguages. create a list of languages in the order you want them in your subtitles. 
    subLanguages = eng
    # transcode. enable to use transcoder
    transcode = 1
    ###### duplicate =1 will create a new file. =0 will replace the original
    duplicate = 1
    # concat. joins cd1 cd2 etc into a single video.
    concat = 1
    # IgnoreExtensions is a comma-separated list of extensions that will not be transcoded.
    ignoreExtensions = ".mkv,.avi,.divx,.xvid,.mov,.wmv,.mp4,.mpg,.mpeg,.m4v"
    # outputFastStart. 1 will use -movflags + faststart. 0 will disable this from being used.
    outputFastStart = 0
    # outputQualityPercent. used as -q:a value. 0 will disable this from being used.
    outputQualityPercent = ""
    # outputVideoPath. Set path you want transcoded videos moved to. Leave blank to disable.
    outputVideoPath = ""
    # processOutput. 1 will send the outputVideoPath to SickBeard/CouchPotato. 0 will send original files.
    processOutput = 1
    # audioLanguage. set the 3 letter language code you want as your primary audio track.
    audioLanguage = eng
    # allAudioLanguages. 1 will keep all audio tracks (uses AudioCodec3) where available.
    allAudioLanguages = 0
    # allSubLanguages. 1 will keep all existing sub languages. 0 will discard those not in your list above.
    allSubLanguages = 0
    # embedSubs. 1 will embed external sub/srt subs into your video if this is supported.
    embedSubs = 1
    # burnInSubtitle. burns the default sub language into your video (needed for players that don't support subs)
    burnInSubtitle = 0
    # extractSubs. 1 will extract subs from the video file and save these as external srt files.
    extractSubs = 0
    # externalSubDir. set the directory where subs should be saved (if not the same directory as the video)
    externalSubDir = ""
    # hwAccel. 1 will set ffmpeg to enable hardware acceleration (this requires a recent ffmpeg)
    hwAccel = 0
    # generalOptions. Enter your additional ffmpeg options here with commas to separate each option/value (i.e replace spaces with commas).
    generalOptions = ""
    # outputDefault. Loads default configs for the selected device. The remaining options below are ignored.
    # If you want to use your own profile, leave this blank and set the remaining options below.
    # outputDefault profiles allowed: iPad, iPad-1080p, iPad-720p, Apple-TV2, iPod, iPhone, PS3, xbox, Roku-1080p, Roku-720p, Roku-480p, mkv, mp4-scene-release
    outputDefault = None
    #### Define custom settings below.
    outputVideoExtension = .mkv
    outputVideoCodec = libx264
    VideoCodecAllow = "libx264, h264, h.264"
    outputVideoPreset = ""
    outputVideoResolution = ""
    outputVideoFramerate = ""
    outputVideoBitrate = ""
    outputVideoCRF = 19
    outputVideoLevel = 3.1
    outputAudioCodec = dts
    AudioCodecAllow = "libfaac, dts, ac3, mp2, mp3"
    outputAudioChannels = 8
    outputAudioBitrate = ""
    outputAudioTrack2Codec = libfaac
    AudioCodec2Allow = ""
    outputAudioTrack2Channels = ""
    outputAudioTrack2Bitrate = ""
    outputAudioOtherCodec = ac3
    AudioOtherCodecAllow = "libfaac, dts, ac3, mp2, mp3"
    outputAudioOtherChannels = 8
    outputAudioOtherBitrate = ""
    outputSubtitleCodec = mov_text
</pre>

**Comment by jsaddiction** [comment]
It may also be important that I am on Synology NAS using the FFmpeg package downloaded from the community source.  I am struggling to build FFmpeg as instructed in the wiki.  It complains of not having some things needed to compile yasm.

**Comment by jsaddiction** [comment]
Doing some more searching I found an issue that is very similar to my issue. #793 I have tried multiple iso files and could not get any of them to open.  Additionally what section of the cfg file is the path to 7z?

**Comment by jsaddiction** [comment]
I tried the nightly branch with the same cfg file and still the same result.  Must be related to the 7z installed.  In attempts to fix this, I installed a new 7z using ipkg and still netted the same results.  I manually tried to list the files in several "test" .iso files and all failed to open the archive.  Currently using 7zip Version 9.20

**Comment by clinton-hall** [comment]
interesting, both you and the other user have 7zip V 9.20

I note on 7zip's change log
```
- The BUG in 9.31-9.34 was fixed:
  7-Zip could not correctly extract ISO archives that are larger than 4 GiB.
```

**Comment by breezytm** [comment]
I have been checking this post for a while now for an update. Any chance of using makemkv instead to convert the .iso to mkv?

**Comment by clinton-hall** [comment]
the main issue I have with makemkv is that it is another 3rd party tool to add, and it has less cross platform support (primarily for Windows and OSX). On a system like Synology where we can't even get an update to 7zip, I doubt our chances of getting makemkv or handbrake to run.

it may be possible to update the transcoder to use https://github.com/barneygale/isoparser or https://github.com/clalancette/pycdlib as these would be truely cross platform compatible.

Can you confirm that you still do have a 7zip version older than 9.35 (2014)?

**Comment by breezytm** [comment]
Wait, never mind. I forgot when I started paying attention to this thread I was on a QNAP and have since moved to a small factor headless linux box and I did following the wiki guide on compiling my own 7zip so I am currently running 16.02. It wasn't working simply because I copied settings over so transcoding was disabled. Now that you mentioned it I went through my settings, set to mkv and was able to convert the iso to MKV. 

Uhmm yes, they do look like some pretty cool project and since they are open source, are you thinking about packaging which ever you chose along with nzbToMedia?

**Comment by clinton-hall** [comment]
These could be bundled to remove dependency on 7zip, but there is a lot of work required in doing that. We are also still dependant on 7zip for Windows extraction... although there are potential other libs that may ba able to assist with that...
