### ISSUE TITLE
[Feature Request] EXTRACTOR: Extraction failed for - Time Limit

### ISSUE THREAD

**Issue by ghultstrand** [clinton-hall/nzbToMedia#1303]
Can we get a feature to limit the amount of time the script will try and extract a RAR. As the one mentioned below was running for about 2 hours till I killed the process.

`[ERROR]::MAIN: EXTRACTOR: Extraction failed for /srv/b2e24e20-856e-4b9e-9fa5-c504efb2b7cc/Downloads/Sabnzbd/complete/movies/The.Fifth.Element.1997.REMASTERED.720p.BRRip.XviD.AC3-RARBG-Obfuscated/JnMgRztrAcbpxKfcq2dhhXUFXBCvONEtuWf.part38.rar. Result was 3`

**Comment by StevenNexus** [comment]
I have the same issue. Script will attempt to extract corrupt rar and hang.
