### ISSUE TITLE
Could not find tag for codec subrip in stream

### ISSUE THREAD

**Issue by ghultstrand** [clinton-hall/nzbToMedia#1305]
Commit Version: 8b6a885e87e34fe8f1e988fbf67af39aa2017778 (nightly)
Processor: SABNzbd

Issue: Fails to transcode.
When processing manually: 
`[aac @ 0x58dc5a0] Too many bits 13653.333333 > 12288 per frame requested, clamping to max
[mp4 @ 0x58df9c0] Could not find tag for codec subrip in stream #3, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 --`

Log of what was ran to cause issue:
`/ffmpeg/ffmpeg -loglevel warning -hwaccel auto -fflags +genpts -i /Input.mkv -map 0:0 -map 0:1 -map 0:1 -map 0:2 -c:v libx264 -r 24.0 -b:v 800000 -preset medium -crf 19 -level 3.1 -c:a:0 aac -strict -2 -b:a:0 640000 -c:a:1 ac3 -b:a:1 128000 -c:s copy -movflags +faststart 
/Output.mp4`

Known good transcode:
`/ffmpeg/ffmpeg -loglevel warning -hwaccel auto -fflags +genpts -i /Input.mkv -map 0:0 -map 0:1 -map 0:1 -c:v libx264 -r 24.0 -b:v 800000 -preset medium -crf 19 -level 3.1 -c:a:0 aac -strict -2 -b:a:0 640000 -c:a:1 ac3 -b:a:1 128000 -sn -movflags +faststart /Output.mp4`

Only thing I can see that is different between the two is -c:s copy vs -sn

`[Transcoder]
    # getsubs. enable to download subtitles.
    getSubs = 1
    # subLanguages. create a list of languages in the order you want them in your subtitles. 
    subLanguages = eng
    # transcode. enable to use transcoder
    transcode = 1
    ###### duplicate =1 will create a new file. =0 will replace the original
    duplicate = 0
    # concat. joins cd1 cd2 etc into a single video.
    concat = 1
    # IgnoreExtensions is a comma-separated list of extensions that will not be transcoded.
    ignoreExtensions = ""
    # outputFastStart. 1 will use -movflags + faststart. 0 will disable this from being used.
    outputFastStart = 1
    # outputQualityPercent. used as -q:a value. 0 will disable this from being used.
    outputQualityPercent = 0
    # outputVideoPath. Set path you want transcoded videos moved to. Leave blank to disable.
    outputVideoPath = ""
    # processOutput. 1 will send the outputVideoPath to SickBeard/CouchPotato. 0 will send original files.
    processOutput = 0
    # audioLanguage. set the 3 letter language code you want as your primary audio track.
    audioLanguage = eng
    # allAudioLanguages. 1 will keep all audio tracks (uses AudioCodec3) where available.
    allAudioLanguages = 1
    # allSubLanguages. 1 will keep all existing sub languages. 0 will discard those not in your list above.
    allSubLanguages = 0
    # embedSubs. 1 will embed external sub/srt subs into your video if this is supported.
    embedSubs = 0
    # burnInSubtitle. burns the default sub language into your video (needed for players that don't support subs)
    burnInSubtitle = 0
    # extractSubs. 1 will extract subs from the video file and save these as external srt files.
    extractSubs = 1
    # externalSubDir. set the directory where subs should be saved (if not the same directory as the video)
    externalSubDir = ""
    # hwAccel. 1 will set ffmpeg to enable hardware acceleration (this requires a recent ffmpeg)
    hwAccel = 1
    # generalOptions. Enter your additional ffmpeg options here with commas to separate each option/value (i.e replace spaces with commas).
    generalOptions = ""
    # outputDefault. Loads default configs for the selected device. The remaining options below are ignored.
    # If you want to use your own profile, leave this blank and set the remaining options below.
    # outputDefault profiles allowed: iPad, iPad-1080p, iPad-720p, Apple-TV2, iPod, iPhone, PS3, xbox, Roku-1080p, Roku-720p, Roku-480p, mkv, mp4-scene-release
    outputDefault = ""
    #### Define custom settings below.
    outputVideoExtension = .mp4
    outputVideoCodec = libx264
    VideoCodecAllow = "libx264, h264, h.264"
    outputVideoPreset = medium
    outputVideoResolution = 1920:1080
    outputVideoFramerate = 24
    outputVideoBitrate = 800000
    outputVideoCRF = 19
    outputVideoLevel = 3.1
    outputAudioCodec = aac
    AudioCodecAllow = aac
    outputAudioChannels = 6
    outputAudioBitrate = 640k
    outputAudioTrack2Codec = ac3
    AudioCodec2Allow = ac3
    outputAudioTrack2Channels = 2
    outputAudioTrack2Bitrate = 128000
    outputAudioOtherCodec = libmp3lame
    AudioOtherCodecAllow = ""
    outputAudioOtherChannels = ""
    outputAudioOtherBitrate = 128000
    outputSubtitleCodec = ""`

**Comment by ghultstrand** [comment]
Well. That doesn't look easy to read. Here are the text file versions along with the output log from a successful process and a failed process.

https://1drv.ms/f/s!AtItXRNac1nKhfRKfqgeebbebFpegg

**Comment by clinton-hall** [comment]
try setting:
`outputSubtitleCodec = mov_text` to ensure the subtitles are converted to a format that .mp4 container can handle.
