### ISSUE TITLE
[Feature Request] Enable Par2 Checks

### ISSUE THREAD

**Issue by Veldkornet** [clinton-hall/nzbToMedia#1306]
Some items require that a par2 file is executed in order to rename the files before being sent to SickBeard etc. It would be preferable of the par2 path were listed as part of the config (as is with ffmpeg) and used if available. 

As per [here](https://sabnzbd.org/wiki/scripts/post-processing-scripts), i see this is possible with SAB_PAR2_COMMAND with SABnzbd.

I currently have a separate shell script for this, but it would of course be better if it were built in.

```
#! /bin/bash

cd "$1"
pwd
ls -al

parfile=$(find . -regex ".*\.\(par2\)" -printf "%f\n")
downloadfile=$(ls -1S | head -n 1)

if [ ! -z "$parfile" ]; then
   echo ""
   echo "Found par file for rename: $parfile"
   echo "Found biggest file in folder for rename: $downloadfile"
   echo ""

   echo "Running command: /volume1/@appstore/sabnzbd/bin/par2 r $parfile *"

   /volume1/@appstore/sabnzbd/bin/par2 r $parfile *
else
   echo "Completed, no par file for rename found"
fi

echo "Completed"
```

**Comment by clinton-hall** [comment]
ok... added something into nightly to test.
Currently only for Linux (will need to see if I include windows binary, or just ask for it to be installed.
Also, just checks for the par2 commands in the system Path. Again, could add the option to specify the par2 command path (would also help Windows for non default install if not bundled)... really just curious to see if this work first.

**Comment by aaronkuchma** [comment]
This breaks processing on my BSD server.

Line 151, objects = os.listdir(dirname), throws errors complaining a directory doesn't exist. I tried rm -rf the source and destinations, and wiping the nzbtomedia.db file, but still it was trying to search a non existing directory. I'll try to flip through the logs after work for more info.
