### ISSUE TITLE
NzbToRadarr Error: NoneType' object is not callable..

### ISSUE THREAD

**Issue by Veepas** [clinton-hall/nzbToMedia#1307]
[Fast.and.Furious.Five.log](https://github.com/clinton-hall/nzbToMedia/files/1364579/Fast.and.Furious.Five.log)
Hello there,

i was tinkering with your scripts the last few days and didn't managed to get this working.

I typed in the settings in the autoprocessmedia.cfg.spec and moved it to the non-spec version.
Settings in the nzbtoRadarr Script are set through NZBGet itself.

Now i get the errors stated in the log attached. I guess some variables aren't passed over correctly but i didn't figured it out.

[Fast.and.Furious.Five.log](https://github.com/clinton-hall/nzbToMedia/files/1364585/Fast.and.Furious.Five.log)

**Comment by clinton-hall** [comment]
what version of Radarr are you running? It looks like Radarr has changed the format of the output from the postprocess request.
