### ISSUE TITLE
NZB file name appears to get truncated 

### ISSUE THREAD

**Issue by Trotter73** [clinton-hall/nzbToMedia#1308]
Hi,

I first filed this at SickRage, the guys over there though it was a nzbToMedia
 issue though so here I am.

The issue appears only to be with a specific show, Modern Family, SickRage finds the episode OK, Sab downloads it however during processing the episode number gets cropped and I end up with episode "00" being processed with the original episode still showing as snatched... The guy on SR who was helping couldn't replicate this unfortunately, any ideas ?

[log.txt](https://github.com/clinton-hall/nzbToMedia/files/1398314/log.txt)

**Comment by clinton-hall** [comment]
The log shows that the full folder name is passed to (and scanned by) SickRage.
I wonder is there is a limit on characters being passed via the WebUI url call made to SickRage?

Are you able to repeat this, with the option `log_debug = 1` enabled?
This way we can see what exact data is being passed in to SickRage.

**Comment by Trotter73** [comment]
Hi,
Thanks for getting back ! Sorry for the delay, my mail client keeps putting git emails in junk for whatever reason ?!

I assume you meant enable debug in nzbtomedia, attached is a log with debug enabled, if you need anything else please just shout....

Best Regards,
[nzbtomedia.log](https://github.com/clinton-hall/nzbToMedia/files/1538425/nzbtomedia.log)

**Comment by Trotter73** [comment]
I ran the same with SR debugging enabled, attached is a snip of the log, where I think it gets interesting.... If you need the who thing I'll PM it to you....
[SR-Debug-Snip.txt](https://github.com/clinton-hall/nzbToMedia/files/1538542/SR-Debug-Snip.txt)

**Comment by clinton-hall** [comment]
The culprit appears to be SABnzbd...
`Options passed into nzbToMedia: ['C:\\Utils\\nzbToMedia\\nzbToSickBeard.py', 'C:\\Users\\Foobar\\Documents\\Downloads\\complete\\TV\\Modern Family S09E09 720p HEVC x265-MeGusta-Pre', 'Modern.Family.S09E0.nzb', 'Modern Family S09E09 720p HEVC x265-MeGusta-Pre', '', 'tv', 'alt.binaries.ratcave', '0', '']`

note the download name is given as `Modern.Family.S09E0.nzb`
so how are these being snatched? manually, or via SickRage?

**Comment by Trotter73** [comment]
Hi,

Thanks again! 
These are snatched automatically with Sickrage / Medusa, manual post processing works fine, only appears with this specific series as well...

The issue has been around for a while, sinces the end of the last series anyway... Does it look  like a setting thing or more like a bug ?

**Comment by Trotter73** [comment]
I found this,but there was no solution other than turn off pre-check... I'll try it if it works I'll raise it as a bug over there....

https://forums.sabnzbd.org/viewtopic.php?t=20785

**Comment by clinton-hall** [comment]
ah, very interesting. Thanks for confirming. it may be worth adding to that sabnzbd topic that you also experienced this.
