### ISSUE TITLE
Help with error nzbToMedia: ImportError: No module named libs.six

### ISSUE THREAD

**Issue by hfeixas** [clinton-hall/nzbToMedia#1310]
Post processing fails because the script nzbToMedia.py hangs on this line. 
Any assistance will be appreciated.

Thank you

**Comment by clinton-hall** [comment]
in the same folder as nzbToMedia, there should be a sub-folder named libs, and this should inlude a file named six.py

you need to ensure the full repository is cloned.

If you do have these, then please check you are using python 2.7X
