### ISSUE TITLE
QQ: Burned-in subtitles

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1312]
Is there a tool or method that can strip these off? Or fail the download if they're present?

**Comment by clinton-hall** [comment]
Generally speaking, burned in subs are part of the video stream, so can't be detected using ffprobe as far as I know.
The only easy way is to check if these are mentioned in the stream comments, or in an NFO etc... in either case this would require a specific format to check for, and I don't believe there is a standard in place (anyone who uses such standard should be rejected by SickRage, CouchPotato, Sonarr, Radarr etc.
