### ISSUE TITLE
Help with error nzbToMedia: ImportError: No module named xmlrpclib

### ISSUE THREAD

**Issue by Pseudomax** [clinton-hall/nzbToMedia#1316]
Hi

In the past few days (possibly after a new firmware update from QNAP ... which is where I have NZBGet & Sonarr running) I seem unable to post process any downloaded files? Everything unrar's successfully, but the actual PP fails with the following message in the log (xxxxxx being the file name):
Post-process-script nzbToMedia/nzbToMedia.py for xxxxxx failed (terminated with unknown status)

I did a quick search online and found the following at this address (https://docs.python.org/2/library/xmlrpclib.html):
Note The xmlrpclib module has been renamed to xmlrpc.client in Python 3. The 2to3 tool will automatically adapt imports when converting your sources to Python 3.

I don't use Python 3 I use Python 2.7.12.1 (from the QNAP App Centre) and it was updated on my machine about 10 days ago which is roughly when I noticed this problem. Could this be the cause? If not, then any ideas/suggestions?

Many thanks

**Comment by jubbleys** [comment]
I am also suffering with this and have searched the web for some advice, but cant find any

**Comment by jubbleys** [comment]
Check this out matey worked for me

https://github.com/clinton-hall/nzbToMedia/issues/1256

**Comment by Pseudomax** [comment]
Hi jubbleys

Many thanks for this ... I had actually wondered about shelloveride but had the location of python2.7 wrong!! ... I can confirm your solution worked for me too!

You have to ask why QNAP would update the location (I'm assuming it is QNAP) without linking to the new location. This can't just apply to NZBget?!

Anyhow thanks for sharing the solution!

**Comment by devicenul** [comment]
Thanks. I was pulling my hair out over this one. Whew! Didn't realize they shifted locations. Duh!
