### ISSUE TITLE
Exception AttributeError: "'WindowsProcess' object has no attribute 'mutex'"

### ISSUE THREAD

**Issue by Cold71** [clinton-hall/nzbToMedia#1317]
I've been using NzbToMedia scripts for awhile now with no issues. This error started about 24 hours ago. Rebooted my PC several times, I reinstalled NzbtoMedia, reinstalled Python, reinstalled Pywin32. No dice... any help would be greatly appreciated. Full error below.

```
Traceback (most recent call last):
File "I:\nzbToMedia\nzbToSickBeard.py", line 260, in <module>
result = nzbToMedia.main(sys.argv, section)
File "I:\nzbToMedia\nzbToMedia.py", line 702, in main
core.initialize(section)
File "I:\nzbToMedia\core\__init__.py", line 248, in initialize
MYAPP = RunningProcess()
File "I:\nzbToMedia\core\nzbToMediaUtil.py", line 1246, in __init__
self.process = WindowsProcess()
File "I:\nzbToMedia\core\nzbToMediaUtil.py", line 1261, in __init__
from win32event import CreateMutex
ImportError: No module named win32event
Exception AttributeError: "'WindowsProcess' object has no attribute 'mutex'" in <bound method WindowsProcess.__del__ of <core.nzbToMediaUtil.WindowsProcess object at 0x03298670>> ignored
```

**Comment by regulus0** [comment]
I am also reporting this same issue. Every download from Mylar, Sonarr, Radarr, Headphones you name it triggers it. Items are not processed at all. 

Traceback (most recent call last):
File "D:\ServerApps\SABnzbd\Scripts\nzbToMedia.py", line 872, in <module>
exit(main(sys.argv))
File "D:\ServerApps\SABnzbd\Scripts\nzbToMedia.py", line 702, in main
core.initialize(section)
File "D:\ServerApps\SABnzbd\Scripts\core\__init__.py", line 248, in initialize
MYAPP = RunningProcess()
File "D:\ServerApps\SABnzbd\Scripts\core\nzbToMediaUtil.py", line 1246, in __init__
self.process = WindowsProcess()
File "D:\ServerApps\SABnzbd\Scripts\core\nzbToMediaUtil.py", line 1261, in __init__
from win32event import CreateMutex
ImportError: DLL load failed: %1 is not a valid Win32 application.
Exception AttributeError: "'WindowsProcess' object has no attribute 'mutex'" in <bound method WindowsProcess.__del__ of <core.nzbToMediaUtil.WindowsProcess object at 0x00000000025A4E10>> ignored

**Comment by clinton-hall** [comment]
can you confirm what version of Python you have, and what version of PyWin32?

Usually these errors would suggest the python and Pywin versions don't match.

Can you also confirm what branch of nzbToMedia you are using? there were some changes to nightly branch recently (but these shouldn't have caused this issue...

**Comment by regulus0** [comment]
In my Programs and features I have a Python2.7pywin 32.-219, a Python 2.7.10 and a Python 2.7.14(64-bit). I am using the Nightly branch currently,

Also I wanted to correct myself. I had an album download from Headphones between my last post and now and it did get sorted to the correct directory but I did not get notified via telegram like I typically do.

**Comment by clinton-hall** [comment]
When you launch pywin it should print the full version
`PythonWin 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32.`
Note in programs and features this shows `Python2.7pywin 32.-218`

so this suggests the version you have is latter than 2.7.12, but you have Python 2.7.10.... these won't be compatible. Also, your 64-bit python may not work correctly with pywin32...
in either case, you need to make sure the scripts are launching the correct version of Python that has pywin32.

**Comment by regulus0** [comment]
Thanks, got it resolved. Removed the duplicate 2.7.10 (not sure if this was remnants of an old install), removed 2.7.14 and the current install of Pywin32. Reinstalled Python 2.7.14 64-bit and the matching Pywin32 for 64-bit and all is well again.
