### ISSUE TITLE
Multiple entries for the same nzb since using the nzbToMedia script

### ISSUE THREAD

**Issue by jhuylebroeck** [clinton-hall/nzbToMedia#1324]
I started using nzbToMedia a few months ago both for sickbeard (sickrage actually) and couchpotato.

Ever since I notice that nzb's get added multiple times. My Sabnzbd-config is set to "paused" all the time, and I manually unpause every so often to optimise the limited available space on the unit. When I unpause I notice that shows or movies that haven't been downloaded already are in my download queue multiple times, even for the same release. Once they've been downloaded and processed they don't reappear, so that part of the configuration seems to be correct.

I think I followed the information that's to be found on the wiki correctly: https://github.com/clinton-hall/nzbToMedia/wiki

I'm running all the packages on my Synology DS412+ NAS.

**Comment by clinton-hall** [comment]
This sounds like an issue with SickRage to SABnzbd and CouchPotato to SABnzbd integration. 
Generally these will re-snatch if they don't think the snatched episodes are downloading (failed downloads) so this may even be an issue with a timeout (paused for too long) or when checking for download status from SABnzbd it only checks first page and these have been pushed back to second page (too many paused downloads at once) so it snatches another (and the other downloads are pushed even further back etc).

**Comment by jhuylebroeck** [comment]
Thank you for your very swift response. It seems plausible, and I want to determiine the cause. Do you have any insights into which logs I might refer to to determine the cause? Since both sickrage and couchpotato are doing it, I think it may be SABnzbd (and or settings/scripts in SABnzbd) related?

Thanks for you kind assistance!

**Comment by clinton-hall** [comment]
take a look at CouchPotato logs, search the logs for a movie that has been snatched more than one. 
These logs should say why the movie has been snatched again... either an error during snatch, or the renamer is doing a status check and can't find the download in progress...
