### ISSUE TITLE
Nzbtocouchpotato : Exit(1) Exception TypeError: "’NoneType’ object is not callable" in > ignored 

### ISSUE THREAD

**Issue by tchirou** [clinton-hall/nzbToMedia#1328]
Hi Clinton, Hi Guys
I have git cloned nzbtomedia on my DS418 synology NAS. Master branch, commit ee243fbba51e66ed12ad17d57e016b4db5bdc720

nzbtosickbeard and nzbtomylar work perfectly but nzbtocouchpotato does not

This is the end of the log (I replaced my api and the movie related info) 
`[19:56:31] [DEBUG]::EXCEPTION: Replacing file name blublublu with directory name blablabla
[19:56:31] [DEBUG]::EXCEPTION: Replacing file name /volume1/video/Films/1/blablabla/blublublu.mkv with download name /volume1/video/Films/1/blablabla/blablabla.mkv
[19:56:31] [DEBUG]::COUCHPOTATO: Opening URL: http://192.168.1.18:5053/api/apiapiapiapi/renamer.scan with PARAMS: {'media_folder': '/volume1/video/Films/1/blablabla'}
[19:56:31] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for blablabla.nzb
Traceback (most recent call last):
File "/volume1/Git/nzbToMedia/nzbToCouchPotato.py", line 262, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/volume1/Git/nzbToMedia/nzbToMedia.py", line 802, in main
download_id='', failureLink=''.join(args[8:]))
File "/volume1/Git/nzbToMedia/nzbToMedia.py", line 671, in process
inputCategory, failureLink)
File "/volume1/Git/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 305, in process
result = r.json()
File "/volume1/Git/nzbToMedia/libs/requests/models.py", line 805, in json
return complexjson.loads(self.text, **kwargs)
File "/var/packages/python/target/lib/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/var/packages/python/target/lib/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/var/packages/python/target/lib/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7f10e00f6a90>> ignored`

This is the couchpotato related autoprocessmedia
`[[movies]]
        enabled = 1
        apikey = apiapiapi
        host = 192.168.1.18
        port = 5053
        ssl = 0
        web_root = ""
        Torrent_NoLink = 0
        keep_archive = 1
        method = renamer
        delete_failed = 1
        wait_for = 5
        extract = 1
        minSize = 0
        delete_ignored = 0
        remote_path = 0
        watch_dir = ""
`

If anyone has any clue, it would be great

Thanks a lot

**Comment by clinton-hall** [comment]
is CouchPotato also on your NAS?
if so, you can try using `host = 127.0.0.1` or `host = localhost` to see if either of them work.
the error suggest the script is not getting a response from CouchPotato.

Basically, if you put
`http://192.168.1.18:5053/api/apiapiapiapi/renamer.scan?media_folder=/volume1/video/Films/1/blablabla`
into your web browser, do you get a response?

**Comment by tchirou** [comment]
Hello
Yes CP is also on the NAS. I will try with localhost.
In autoprocessmedia, I have 192.168.1.18 for Sickrage and Mylar and it works.

This is the full log of another try this morning : https://pastebin.com/x4K6hz5J

When I put http://192.168.1.18:5053/api/apiapiapiapi/renamer.scan?media_folder=/volume1/video/Films/1/blablabla and I replace apiapiapi by the CP api, I get
{"success": true}

Thanks a lot

**Comment by clinton-hall** [comment]
check your autoprocessmedia.cfg again to make sure you have the right api key for CP. the response you showed above is right, but in the logs it clearly isn't authenticating correctly.

**Comment by tchirou** [comment]
Very good call
In my hurry to set everything up again, I didn’t change this api, it was
the one from my older NAS
Thanks a lot !!!

Le 29 janv. 2018 à 22:31, Clinton Hall <notifications@github.com> a écrit :

check your autoprocessmedia.cfg again to make sure you have the right api
key for CP. the response you showed above is right, but in the logs it
clearly isn't authenticating correctly.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/clinton-hall/nzbToMedia/issues/1328#issuecomment-361393313>,
or mute the thread
