### ISSUE TITLE
Transcoding thread count

### ISSUE THREAD

**Issue by ghultstrand** [clinton-hall/nzbToMedia#1330]
I am trying to limit the CPU threads to 1. I thought based on my readings it was **generalOptions = -threads, 1**, am I wrong? As my htop more than one PID running ffmpeg. I could also be reading htop wrong.

Screenshot: https://1drv.ms/i/s!AtItXRNac1nKhoh-7BwgA-xGzQI5xA
Snippet from config: https://1drv.ms/t/s!AtItXRNac1nKhoh7zf698Horp4rkMg

**Comment by clinton-hall** [comment]
in your config, just to be sure, remove the space
`generalOptions = -threads,1`
see if that makes any difference?

**Comment by ghultstrand** [comment]
At the end or between the thread , and 1?

**Comment by clinton-hall** [comment]
between the thread and 1. but also ensure no trailing spaces.

**Comment by ghultstrand** [comment]
I don't think it is helping but this isn't a very good test case in the first place as the CPU isn't very strong.

Secondary question, 

why are some videos that are converted the labels are left with -transcoded and others are not? I'm trying to do a mass covert before moving them to radarr.

**Comment by clinton-hall** [comment]
`-transcoded` is added when the output video name is the same as the input (i.e. when the transcoding is to the same container type, in the same directory, and you are using the option to `duplicate`)

to stop this either
 1. set a different `outputVideoPath`
 2. add the output container type to the `ignoreExtensions` (e.g. `.mkv`)
 3. set option `duplicate = 0`

**Comment by ghultstrand** [comment]
sorry to bring up an old thread, but outputVideoPath. When the conversion is done the old stuff is removed? It would run a lot like torrent where you need to another path for it to convert.
