### ISSUE TITLE
Not sure what happened here

### ISSUE THREAD

**Issue by phybersplice** [clinton-hall/nzbToMedia#1331]
I'm using docker and nzbget with a synology 1813+.
I've built my own docker git and everything works up until the point where nzb scripts make a call to talk to RADARR and it does a check for status change.  There's two problems:
Minutes pass, and it will eventually pass and trigger RADARR to update.  Most of the time, it works but has a good 5 minute delay in between NZBGET finishing the unpack process and then the message to RADARR to say it's finished.  Why would this be?
Also, In this particular case, it failed, and I am not sure why.

https://pastebin.com/W1y9C7jX (Not working properly)
https://pastebin.com/sLLBaKFg (Long delays calling RADARR - Status Change)

**Comment by clinton-hall** [comment]
The failure looks to be a timeout where RADARR didn't respond.
For the delays, check the RADARR logs at Tue Feb 13 2018 09:36:59  to see what RADARR did once it was asked to process this.
