### ISSUE TITLE
Question: Headphones postProcess dir vs. album_dir 

### ISSUE THREAD

**Issue by kimpenhaus** [clinton-hall/nzbToMedia#1332]
Hi there,

I was recently applying nzbToMedia headphones music post-processing to my NZBGet setup and was facing some trouble. I am not pretty sure if this is related to my setup, so please consider this more being a question than a bug report.

Every time post-processing started - it was finishing with headphones saying something like this:

```
2018-02-26 08:05:21 | INFO | Found no folders to process. Aborting.
2018-02-26 08:05:21 | DEBUG | Post processing folders: ['/volume1/downloads/nzbget/completed/music/<album-directory>']
2018-02-26 08:05:21 | INFO | Force checking download folder for completed downloads
```
(`<album-directory>` is just a placeholder 😄)

I double checked the path - double checked permissions... everything looks good to me.
Next I searched for the phrase `'Found no folders to process. Aborting.'` inside the Headphones code, trying to understand what's happening there. And I found, that the method signature has to different options:

```
def forcePostProcess(dir=None, expand_subfolders=True, album_dir=None, keep_original_folder=False):
```

`dir` and `album_dir`

From what I understood is, that passing `dir` triggers the folders lookup inside that given directory (which is resulting in the abort because of no sub-folder found), while giving `album_dir` didn't.

also the `forceProcess` API-method is capable handling both different directories:

```
def _forceProcess(self, **kwargs):
        if 'album_dir' in kwargs:
            album_dir = kwargs['album_dir']
            dir = None
            postprocessor.forcePostProcess(self, dir, album_dir)
        elif 'dir' in kwargs:
            self.dir = kwargs['dir']
            postprocessor.forcePostProcess(self.dir)
        else:
            postprocessor.forcePostProcess()
```

So I changed the `autoProcessMusic.py` starting at line 128 from `dir` to `album_dir`:

```
params = {
                'apikey': apikey,
                'cmd': "forceProcess",
                'album_dir': remoteDir(dirName) if remote_path else dirName
            }

            res = self.forceProcess(params, url, apikey, inputName, dirName, section, wait_for)
            if res[0] in [0, 1]:
                return res
```

Starting the post-process from within NZBGet again, this time it succeeded.

So my question is, shouldn't the `dir` parameter be the `album_dir` parameter? Is it kind of special setup (I don't think I did something special 😆)? Hs anyone else been stumbling across this?

Thanks and cheers,
Marcus

PS: If any further information is required I gladly supply.

**Comment by clinton-hall** [comment]
interesting... this was reported previously, and the issue here was to first try and process the directory, and then to process the parent directory if this failed (if this was an album directory).
```
            params = {
                'apikey': apikey,
                'cmd': "forceProcess",
                'dir': remoteDir(dirName) if remote_path else dirName
            }

            res = self.forceProcess(params, url, apikey, inputName, dirName, section, wait_for)
            if res[0] in [0, 1]:
                return res

            params = {
                'apikey': apikey,
                'cmd': "forceProcess",
                'dir': os.path.split(remoteDir(dirName))[0] if remote_path else os.path.split(dirName)[0]
            }
```
I could change this to use your method (album_dir) as a fall back. 
```
            params = {
                'apikey': apikey,
                'cmd': "forceProcess",
                'dir': remoteDir(dirName) if remote_path else dirName
            }

            res = self.forceProcess(params, url, apikey, inputName, dirName, section, wait_for)
            if res[0] in [0, 1]:
                return res

            params = {
                'apikey': apikey,
                'cmd': "forceProcess",
                'album_dir': remoteDir(dirName) if remote_path else dirName)
            }
```
I'm just trying to get my head around the best method. i.e. do we pass album_dir first, and then dir as fall-back, or pass dir first and album_dir as fall-back (as per code snippet above?

are you able to test the above? If it works, I try and commit to nightly build to see if this works for other, or introduces issues...

**Comment by kimpenhaus** [comment]
Hey Clinton,

I tried changing the script like you suggested to:

```
params = {
                'apikey': apikey,
                'cmd': "forceProcess",
                'dir': remoteDir(dirName) if remote_path else dirName
            }

            res = self.forceProcess(params, url, apikey, inputName, dirName, section, wait_for)
            if res[0] in [0, 1]:
                return res

            params = {
                'apikey': apikey,
                'cmd': "forceProcess",
                'album_dir': remoteDir(dirName) if remote_path else dirName
            }
```

My `wait_for` is configured to 1 - the result was: Headphones first says `Found no folders to process. Aborting.` which I expected to say so. Then it retried with the `album_dir` which results in starting post-processing. That was cool! 😁 But in the end the process of converting with ffmpeg and matching the songs took to long (maybe?) Headphones post-processed correctly but the script failed saying post-processing failed. 😞 

My general opinion is to start with the most precise directory information - and fallback to the higher level one. But this is my personal opinion - maybe because this works in my scenario. Maybe its just misconfiguration on my site - and this could be solved?
