### ISSUE TITLE
syntax error on cpsapikey

### ISSUE THREAD

**Issue by ghost** [clinton-hall/nzbToMedia#1336]
File "/opt/autoProcessTV/nzbToCouchPotato.py", line 46
cpsapikey=myapikeyfromfreakingcouchpotato
^
SyntaxError: invalid syntax

**Comment by clinton-hall** [comment]
don't make changes to nzbToCouchPotato.
make the changes in autoProcessMedia.cfg, or in NZBGet's web ui.
Those lines in nzbToCouchPotato are only to enable webui setting in NZBGet.

so reset your nzbToCouchPotato back to original state
```
cd /opt/autoProcessTV
git reset --hard
git pull
```
then copy autoProcessMedia.cfg.spec to autoProcessMedia.cfg and edit this file with your settings.
