### ISSUE TITLE
Post-Process Failure -> Transcoding

### ISSUE THREAD

**Issue by mpvescio** [clinton-hall/nzbToMedia#1338]
Setup: Qnap w/ 4.3.4; Nzbget v 19.1; Radarr + Sonarr

I'm trying to use nzbToMedia for transcoding to mp4 immediately after download. I configured the aPM.cfg file as per wiki, ffmpeg 3.4.2 installed.

Currently bugging out at "No module named xmlrpclib".

Any help would be very appreciative.

> Wed Mar 21 13:15:34 2018	INFO	Executing post-process-script nzbToMedia-master/nzbToMedia.py for Everything.Sucks.S01E02.Maybe.Youre.Gonna.Be.The.One.That.Saves.Me.720p.NF.WEBRip.DD5.1.x264-NTb-AsRequested
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia: Traceback (most recent call last):
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia-master/nzbToMedia.py", line 573, in <module>
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:     import core
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia-master/core/__init__.py", line 35, in <module>
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:     from core.autoProcess.autoProcessComics import autoProcessComics
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia-master/core/autoProcess/autoProcessComics.py", line 7, in <module>
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:     from core.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia-master/core/nzbToMediaUtil.py", line 19, in <module>
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:     import subliminal
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia-master/libs/subliminal/__init__.py", line 16, in <module>
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:     from .providers import Provider
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia-master/libs/subliminal/providers/__init__.py", line 5, in <module>
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:     from six.moves.xmlrpc_client import SafeTransport
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia-master/libs/six.py", line 203, in load_module
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:     mod = mod._resolve()
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia-master/libs/six.py", line 115, in _resolve
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:     return _import_module(self.mod)
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia-master/libs/six.py", line 82, in _import_module
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia:     __import__(name)
Wed Mar 21 13:15:35 2018	INFO	nzbToMedia: ImportError: No module named xmlrpclib
Wed Mar 21 13:15:36 2018	ERROR	Post-process-script nzbToMedia-master/nzbToMedia.py for Everything.Sucks.S01E02.Maybe.Youre.Gonna.Be.The.One.That.Saves.Me.720p.NF.WEBRip.DD5.1.x264-NTb-AsRequested failed (terminated with unknown status)

**Comment by clinton-hall** [comment]
you need to have python compiled with xmlrpclib.
What Python qpkg do you have installed?

**Comment by clinton-hall** [comment]
These scripts are not Python 3 compatible. So you need Python 2.7.X
I am not familiar with the QPython. There used to be a working "python 2.7.X" qpkg, but there are so many different versions running around the forums that I lost track. What is more of an issue is that the "default" python will be inherited from the downloader (NZBget)

**Comment by mpvescio** [comment]
Any additional clues on which qpkg I should be using here?

Re: default python for NZBget -- Is there any way to detach? Should I want this? @clinton-hall

**Comment by mpvescio** [comment]
@clinton-hall my only goal is to transcode as a post-process to NZBGet. Everything else gets taken care of by Sonarr/Radarr after NZBget sends it the final file location

**Comment by clinton-hall** [comment]
to "detach" what you would do is edit the /etc/init.d/NZBGet.sh to make the PATH variable prioritise a different version of Python.
This depends on how the qpkg is set up. I tried some time ago to have it search for and use the most advanced (2.7.X) version, I tried using a "fixed" python package, and I had it so you could specify.

But basically, if you know where the Python you want is...
`EXPORT PATH=<PATH_TO_PYTHON>:${PATH}`
This way any daughter product of NZBGet (i.e. scripts) will use this PATH in order of priority.
The other option is in NZBGet WebUI, settings, extension scripts there is an option `ShellOveride`
Set this to tell the .py scripts to be run with which ever python you find... test them all...
`.py=/usr/bin/python2`
