### ISSUE TITLE
Cleandirs not deleting folder...left over files

### ISSUE THREAD

**Issue by ulrick65** [clinton-hall/nzbToMedia#1340]
First...this is an awesome piece of work.  It does so much for me on a daily basis...I can't thank you enough for it.

Now for my issue...this has always been a problem for me, but I have lived with it as I figured I had something wrong in settings and never took the time to fix it....until today.

nzbget to sickrage.  Basically anytime there is a file with a .par2 or .nfo extension, it leaves those in the download folder and then does not delete the folder because it say 1 (or whatever) files remaining to process.  As long as those files dont exist, it deletes all the other stuff and removes the folder fine.

I see in the code there is a FORCE_CLEAN but I don't see an option for it in the NZB config.  Also, I am curious as to why it leaves only these files.  It moves the media file just fine, deletes all the other files fine (like jpg's and other junk) but leaves these and then wont delete the folder?

Can you point me in the right direction with this?

Thanks.

**Comment by clinton-hall** [comment]
Force Clean should work fine. This applies to all downloaders as it is in the [General] section of the config.

I can understand why .nfo files could cause an issue, but not .par files...
anyway you can try removing `.nfo` from the metaExtensions list
```
[Extensions]
    compressedExtensions = .zip,.rar,.7z,.gz,.bz,.tar,.arj,.1,.01,.001
    mediaExtensions = .mkv,.avi,.divx,.xvid,.mov,.wmv,.mp4,.mpg,.mpeg,.vob,.iso,.m4v,.ts
    audioExtensions = .mp3, .aac, .ogg, .ape, .m4a, .asf, .wma, .flac
    metaExtensions = .nfo,.sub,.srt,.jpg,.gif
```
but force_clean is probably the easiest solution.

```
[General]
    # Enable/Disable forceful cleaning of leftover files following postprocess 
    force_clean = 0
```

**Comment by ulrick65** [comment]
Thanks.  I see that .nfo is in a list of other files that is probably causing it.  Is there a reason why you have it that way?  Seems like it should only care about media files (those defined in the list).

I hate to use force clean if there is a chance that would delete media files at some point if there was two in a download (rare, but could happen).

Is force clean exposed in nzbget config or do I have to set it in the config file itself.  I couldn't find it anywhere.

Thanks.

**Comment by clinton-hall** [comment]
both the `force_clean = 1` and editing the list of metaExtensions can be done from the config file. neither of these were exposed in NZBGet webUI.

force_clean is under the [General] section of the config. autoProcessMedia.cfg (do not edit the .cfg.spec)
