### ISSUE TITLE
Sickrage "'NoneType' object is not callable"

### ISSUE THREAD

**Issue by Svarto** [clinton-hall/nzbToMedia#1347]
Hi,

I have been trying to get the NzbToSickBeard with Nzbget to work with Sickrage so that when downloads fail, that another version is tried. It looks like the connection from Nzbget is not working to Sickrage - but I dont understand why as I have no login and it is on the same host. This is the error I am getting:

error | Fri May 04 2018 19:46:48 | Post-process-script  nzbToMedia-master/nzbToSickBeard.py for  <file>  failed (terminated with unknown status)
-- | -- | --
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:  Exception TypeError: "'NoneType' object is not callable" in <bound  method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess  object at 0x7f19421c6850>> ignored
info | Fri May 04 2018 19:46:48 | nzbToSickBeard: IOError: [Errno 2] No such file or directory: '/nzbget/scripts/nzbToMedia-master/logs/nzbtomedia.log'
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:     file = __builtin__.open(filename, mode, buffering)
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:   File "/usr/lib/python2.7/codecs.py", line 896, in open
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:     stream = codecs.open(self.baseFilename, self.mode, self.encoding)
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:   File "/usr/lib/python2.7/logging/__init__.py", line 945, in _open
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:     StreamHandler.__init__(self, self._open())
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:   File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:     file_handler = logging.FileHandler(self.log_file_path, encoding='utf-8')
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:   File "/nzbget/scripts/nzbToMedia-master/core/logger.py", line 118, in _config_handler
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:     self.cur_handler = self._config_handler()
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:   File "/nzbget/scripts/nzbToMedia-master/core/logger.py", line 99, in initLogging
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:     logger.ntm_log_instance.initLogging()
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:   File "/nzbget/scripts/nzbToMedia-master/core/__init__.py", line 281, in initialize
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:     core.initialize(section)
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:   File "/nzbget/scripts/nzbToMedia-master/nzbToMedia.py", line 702, in main
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:     result = nzbToMedia.main(sys.argv, section)
info | Fri May 04 2018 19:46:48 | nzbToSickBeard:   File "/nzbget/scripts/nzbToMedia-master/nzbToSickBeard.py", line 260, in <module>
info | Fri May 04 2018 19:46:48 | nzbToSickBeard: Traceback (most recent call last):
info | Fri May 04 2018 19:46:48 | nzbToSickBeard: No log folder, logging to screen only
info | Fri May 04 2018 19:46:48 | Executing  post-process-script nzbToMedia-master/nzbToSickBeard.py for  <file>

**Comment by clinton-hall** [comment]
make sure the user that is running NZBGet has permissions to read and write /nzbget/scripts/nzbToMedia-master/
if this folder was installed as root, and NZBGet runs as a user, then the script will fail as per logs above.

**Comment by Svarto** [comment]
that fixed it, thanks a lot!

**Comment by clinton-hall** [comment]
No worries. Glad that was all ;) Often something like that is just the first of many issues to resolve to get it all configured and working.
