### ISSUE TITLE
Postprocess failing with single quote in file/folder names

### ISSUE THREAD

**Issue by mrginogit** [clinton-hall/nzbToMedia#1348]
Having an issue with postprocessing failing for certain shows with an apostrophe in the title.  It downloads, extracts, and checks for corruption just fine, but is failing before moving from the completed downloads directory over to the show's destination folder.

I turned on log_debug=1 and caught the latest occurrence in the log below.  Any ideas on how to fix this?

[04:44:56] [POSTPROCESS]::SICKBEARD: Unable to figure out what folder to process. If your downloader and SickRage aren't on the same PC make sure you fill out your TV download dir in the config.
[04:44:56] [ERROR]::MAIN: A problem was reported in the nzbToSickBeard.py script.
SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!`

**Comment by clinton-hall** [comment]
What happens if you select this directory to process manually in SickBeard's manual postprocessing?

I can't see if it causes an issue when transmitted via URL or if it causes an issue in SickBeard itself...

Can you check SickBeard debug logs at [04:44:51] ?

**Comment by mrginogit** [comment]
Wow thanks for the fast response, I just had the time to follow up on this.  Forgot to mention, I'm actually using SickRage (commit: a7602639bd525f27475f1eeb2fc504111a14b51c)

Looks like SickRage debug logging wasn't enabled so I only have these INFO traces.  Not much help I know:
`2018-05-09 04:44:54 INFO     MANUAL :: Beginning manual post processing task: H:\SABnzbd\Complete\sickrage\The.Handmaid&#39;s.Tale.S02E04.Other.Women.1080p.HULU.WEB-DL.AAC2.0
2018-05-09 04:44:54 INFO     MANUAL :: Manual post processing task for H:\SABnzbd\Complete\sickrage\The.Handmaid&#39;s.Tale.S02E04.Other.Women.1080p.HULU.WEB-DL.AAC2.0 completed`

I enabled debug logs in Sickrage and then tried to process the episode's completed downloads directory as you suggested.  But Sickrage wont even let me navigate into the episode's folder when there's an apostrophe in it!!  I click it but Sickrage doesn't navigate into it. 
If I remove the apostrophe from the directory itself and try again, I can go into the folder just fine. 

But even when I run the manual post processing on that folder, Sickrage still just shows the same INFO lines as above.  I tried restarting Sickrage but same thing, no debug traces.

So is this a problem with Sickrage not being able to handle the single quote?  Should I open a ticket over there?

**Comment by clinton-hall** [comment]
this does look like an issue with SickRage handling of the folder/file names, and it would appear (until something shows otherwise... first to admit when I'm wrong) that nzbToMedia is handling this ok...

I could put in a clean-up to remove the `'` from download names and paths etc.

If I fix here, the "fix" is applied to all Sick* tools i.e. all branches of SickBeard/SickRage, but depending on what SickBeard/SickRage does the final files may not be named correctly...

I think this handling should be fixed in sickbeard/sickrage, but that then means it needs to be fixed in ALL sickbeard/sickrage forks...

**Comment by mrginogit** [comment]
Yep, googling around seems like others are reporting similar issues.  Workaround is to add scene exceptions for alternate show name spellings.  I added a few, will give this a shot for now.  Thanks for your help on this!!
