### ISSUE TITLE
Remote Folder Issues

### ISSUE THREAD

**Issue by HPMSGEN8** [clinton-hall/nzbToMedia#1352]
Hi,

For the life of me i cannot get this to work. I keep on getting this.

SAB is on the 1 machine and this works with my current setup.

I created and new section called medusa with the settings i have even added the local folder to look at. remote to 1 and the Network Mounts to the machine and the mount points but still nothing.

2018-06-06 20:59:41 WARNING  Thread_19 :: [212cd1c] Unable to figure out what folder to process. If your download client and Medusa aren't on the same machine, make sure to fill out the Post Processing Dir field in the config.

Any Advice please.

Thanks

**Comment by clinton-hall** [comment]
Would need to see debug logs, the mount_Points and details as to what folders are mounted on each system.

**Comment by HPMSGEN8** [comment]
Please see the below:

``
[[medusa]]
        
enabled = 1
        
host = 192.168.X.X     
port = 8083
        
username = USERNAME
password = PASSWORD      
web_root = ""
        
ssl = 1
        
fork = auto
        
delete_failed = 0
        
Torrent_NoLink = 0
        
keep_archive = 1
        
process_method = ""
        
force = 0
        
delete_on = 0
        
ignore_subs = 0
        
extract = 1
        
nzbExtractionBy = Downloader
       
minSize = 0
        
delete_ignored = 0
        
remote_path = 1
        
watch_dir = /volume5/Completed/Episodes-Medusa

chmodDirectory = 0

[Network]
    # Enter Mount points as LocalPath,RemotePath and separate each pair with '|'
    
# e.g. MountPoints = /volume1/Public/,E:\|/volume2/share/,\\NAS\
    
mount_points = \\192.168.X.X\Mount\Episodes-Medusa\, /volume4/Mount/Episodes-Medusa/

``

**Comment by clinton-hall** [comment]
So, for a failed postprocess, what is the directory (as seen by SABnzbd) where the files were downloaded to?
I am assuming as far as SABnzbd goes this is not `\\192.168.X.X\Mount\Episodes-Medusa\` but is probably something like `/shares/Mount/Episodes-Medusa/`
Likewise, what is the directory (as seen by Medusa)? if this is `/volume4/Mount/Episodes-Medusa/` then the appropriate mount_points are:
`mount_points = /shares/Mount/,/volume4/Mount`

**Comment by HPMSGEN8** [comment]
SABnzdb will be ```/volume5/Completed/Episodes-Medusa``` This is on Server 1. The Mount Point on Server 2 is  ```/volume4/Mount/Episodes-Medusa/``` So this is the same Folder.

Am i being stupid here :)

**Comment by clinton-hall** [comment]
Try setting:
`mount_points = /volume5/Completed/,/volume4/Mount/`

Basically, what we want is for nzbToMedia to replace the `/volume5/Completed` with `/volume4/Mount` when passing over to Medusa.

i,e, SABnzbd tells nzbToMedia to get the files at `/volume5/Completed/Episodes-Medusa/this.eppisode` and nzbToMedia needs to change this when telling Medusa to process it, and tell Medusa to look at `/volume4/Mount/Episodes-Medusa/this.eppisode`

**Comment by HPMSGEN8** [comment]
Thanks. and sure once i get this working :)

**Comment by HPMSGEN8** [comment]
Finally This Works :) Thanks Again
