### ISSUE TITLE
Yo dawg... strange problem with recursive folder structure

### ISSUE THREAD

**Issue by agladman** [clinton-hall/nzbToMedia#1369]
There are 20 nzbmedia folders inside my nzbtomedia folder and I have no clue how this has come about. Any idea what could be causing this behaviour?

<img width="328" alt="screenshot 2018-08-13 15 42 54" src="https://user-images.githubusercontent.com/20296658/44039040-17bb43d2-9f10-11e8-8586-d0237e9b70ba.png">

Running on a QNAP NAS.

**Comment by clinton-hall** [comment]
How was nzbToMedia installed? is this part of a qpkg that auto installs?

If you delete the first redundant folder, monitor the folders to see if these redundent folders are created when nzbToMedia is run, if they are created when nzbget app is disabled and enabled, or if they are created when the NAS is restarted. Knowing when the folders are created will help narrow down what scripts are re-cloning (or copying) into the wrong place.
