### ISSUE TITLE
"env: python2: No such file or directory" error after updating macOS to Mojave + solution

### ISSUE THREAD

**Issue by Sarcas666** [clinton-hall/nzbToMedia#1376]
(MacMini mid 2012 - Mojave - OSX branch nzbtomedia)

Hi there,
I'm just placing it here so people with a similar problem can find the solution more easily. I knew I had fixed this before but I forgot how an it took me quite a while te rediscover the solution.

The update removes the symlink for python.

All you have to do is restore the symlink.

In Terminal, enter:
`sudo ln -sf /usr/bin/python2.7 /usr/bin/python2`
and enter your password. For me the next download went perfect again.

(note; the source does not mention sudo, but it did not work for me without it.)

(Source: https://github.com/clinton-hall/nzbToMedia/wiki/installation )

**Comment by clinton-hall** [comment]
Thanks for posting. 
I thought using the OSX branch, this called python2.7 not python2 and therefore the symlink wasn't required?

**Comment by Sarcas666** [comment]
My pleasure.
I thought so too, but only this line fixed my error. It is always possible that my setup is corrupt somehow. If I can find some time I'll see if I see any differences in a fresh set of the osx branch and my current scripts.

**Comment by XxUnkn0wnxX** [comment]
also FYI just have brew install python@2 it should do the proper links or if all-ready installed just run 

`brew link --overwrite python@2` be sure you have brew running & setup 4 this. 

& if u don't already use brew I would highly recommend setting this up if ur a macOS user makes life easy if ur a power-user like me.

**Comment by nocturnalmonkey** [comment]
Thanks for posting this :)
