### ISSUE TITLE
TorrentToMedia refuses to work, Manual or via client. (Invalid number of arguments) 

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [clinton-hall/nzbToMedia#1380]
Hi, I have been using this for a very long time for nzbtomedia, and I thought I would give TorrentToMedia try but with no avail. TorrentToMedia fails to see the contents of the downloads as well as not recognise the arguments sent.

I'm running MacOS Mojave 10.14
Python 2.7.15
Sick-Rage: https://github.com/Sick-Rage/Sick-Rage (miigotu)

My Setup:

Root Torrents DL DIR: `/Users/user/Downloads/Torrents/Downloads/`

Config: https://gist.github.com/XxUnkn0wnxX/a6c4617eb5de5bed46dcf4e4e21cd0f9

Log: https://gist.github.com/XxUnkn0wnxX/83d08970e02aa8734e27d9e204721545

I don't know what else to do, even when I run it manually via  `python TorrentToMedia.py "601b322455a85b3190227e6c2ee2459ad10a7ac0" "Manifest.S01E03.Turbulence.720p.AMZN.WEBRip.DDP5.1.x264-AJP69[rarbg]" "/Users/user/Downloads/Torrents/Downloads/sickrage" `

or 

` python TorrentToMedia.py '/Users/user/Downloads/Torrents/Downloads/sickrage', 'Manifest.S01E03.Turbulence.720p.AMZN.WEBRip.DDP5.1.x264-AJP69[rarbg]', 'sickrage', '601b322455a85b3190227e6c2ee2459ad10a7ac0'`

I still get 

`09:23:34] [INFO]::MAIN: Loading config from [/Users/user/Apps/nzbToMedia/autoProcessMedia.cfg]
[09:23:34] [INFO]::MAIN: Checking database structure...
[09:23:34] [INFO]::MAIN: Checking if git needs an update
[09:23:35] [INFO]::MAIN: No update needed
[09:23:35] [INFO]::MAIN: nzbToMedia Version:5d5d69ecdd5fe043be8a915ffa26e8427c9641c4 Branch:master (Darwin 18.0.0)
[09:23:36] [INFO]::MAIN: #########################################################
[09:23:36] [INFO]::MAIN: ## ..::[TorrentToMedia.py]::.. ##
[09:23:36] [INFO]::MAIN: #########################################################
[09:23:36] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[09:23:36] [INFO]::MAIN: Searching /Users/user/Downloads/NZB Downloads/Completed/sickrage for mediafiles to post-process ...
[09:23:36] [INFO]::COPYLINK: MEDIAFILE: [DS_Store]
[09:23:36] [INFO]::COPYLINK: SOURCE FOLDER: [/Users/user/Downloads/NZB Downloads/Completed/sickrage]
[09:23:36] [INFO]::COPYLINK: TARGET FOLDER: [/Users/user/Downloads/NZB Downloads/Completed/sickrage/DS_Store]
[09:23:36] [INFO]::COPYLINK: MEDIAFILE already exists in the TARGET folder, skipping ...
[09:23:36] [INFO]::MAIN: Starting manual run for SickBeard:sickrage - Folder:/Users/user/Downloads/NZB Downloads/Completed/sickrage/DS_Store
[09:23:36] [INFO]::MAIN: Checking database for download info for DS_Store ...
[09:23:36] [INFO]::MAIN: Unable to locate download info for DS_Store, continuing to try and process this release ...
[09:23:36] [INFO]::MAIN: SEARCH: Found torrent file DS_Store in input directory directory /Users/user/Downloads/NZB Downloads/Completed/sickrage/DS_Store
[09:23:36] [INFO]::MAIN: SEARCH: Setting inputDirectory to /Users/user/Downloads/NZB Downloads/Completed/sickrage/DS_Store/DS_Store
[09:23:36] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[09:23:36] [INFO]::MAIN: Output directory set to: /Users/user/Downloads/Torrents/Downloads/sickrage/DS_Store
[09:23:36] [INFO]::MAIN: FLATTEN: Flattening directory: /Users/user/Downloads/Torrents/Downloads/sickrage/DS_Store
[09:23:36] [WARNING]::MAIN: Found no media files in /Users/user/Downloads/Torrents/Downloads/sickrage/DS_Store
[09:23:36] [INFO]::MAIN: Calling SickBeard:sickrage to post-process:DS_Store
[09:23:36] [INFO]::MAIN: SickBeard:sickrage fork set to SickRage
[09:23:36] [WARNING]::SICKBEARD: No media files found in directory /Users/user/Downloads/Torrents/Downloads/sickrage/DS_Store to manually process.
[09:23:36] [INFO]::CLEANDIRS: Directory /Users/user/Downloads/Torrents/Downloads/sickrage/DS_Store has been processed, removing ...
[09:23:36] [INFO]::MAIN: The TorrentToMedia.py script completed successfully.`

no output from SR in logs even regarding the show that was downloaded. as nzbtomedia fails to see the show SR doesnt even see it.

all that the script see's is the stupid file "DS_Store"

qBittorent is properly set up I do see the arguments being passed:

`"/Users/user/Apps/nzbToMedia/TorrentToMedia.py" "%R" "%N" "%L" "%I"`

no issues for `nzbToSickBeard.py` auto detects content in `/Users/user/Downloads/NZB Downloads/Completed/sickrage/` via client or manual mode. doesnt explain why TorrentToMedia.py is having such a hard time...

**Comment by clinton-hall** [comment]
qbittorrent arg parsing caused me so issues... needs to be passed as
`/Users/user/Apps/nzbToMedia/TorrentToMedia.py "%D|%N|%L|%I"`

To run manually you would need
`python TorrentToMedia.py "/Users/user/Downloads/Torrents/Downloads/sickrage|Manifest.S01E03.Turbulence.720p.AMZN.WEBRip.DDP5.1.x264-AJP69[rarbg]|sickrage|601b322455a85b3190227e6c2ee2459ad10a7ac0"`

Please confirm if that works... I'll need to look at both the wiki and any other guidance to make sure this is correctly shown.

**Comment by XxUnkn0wnxX** [comment]
ok it see's it now: https://gist.github.com/XxUnkn0wnxX/335356a2e1161baa729292a6f53c73fe

but now it saying it unwanted and does just deletes it. even though in SR is specify as wanted or ignore which usually does the trick when I am manually testing this for NZBs

**Comment by XxUnkn0wnxX** [comment]
also I don't get why 
resume = 1
resumeOnFailure = 1

are defualted at 1

as most users probably use the Move post process in SR and can cause errors when these are set to 1 in the torrentomedia script.

**Comment by clinton-hall** [comment]
default resume = 1 was to allow people to continue seeding to maintain good ratios for VIP indexers etc.
Originally torrent support was added in this script as this allowed the torrent to be hard-linked and processed while still seeding, so that was originally the default.

FWIW, set UseLink = hard, and have SR set to move.... this keeps the file at the downloader (for seeding) and moved by SR to me an organised library...

**Comment by XxUnkn0wnxX** [comment]
also small update wiki sickbeard forks will need to be updated as miigotu's SR is going through some changes as echel0n going on a legal war the SR name keeps changing from Scikrage to Sick-Rage now current SickChill: https://github.com/SickChill/SickChill if name stick and is finalised link will need to be fixed..

**Comment by clinton-hall** [comment]
Thanks. I am aware of the situation. Just waiting for the final name to settle down.
At this time I believe all functionality with interfacing nzbToMedia and SickChill remains. I'll update the wiki soon.

**Comment by XxUnkn0wnxX** [comment]
got another error this morning: https://gist.github.com/XxUnkn0wnxX/9b62b118c3967f83af72ea6b0c00fe93

`Unable to locate a section with subsection:UNCAT enabled in your autoProcessMedia.cfg, exiting!`

not sure why it wants to worry about uncategorised downloads and this DL was still in the SR label

also how do I configure [[UNCAT]]? for torrents as I can only execute the torrenttomedia script in qbittorrent as it does not support running seperate scripts for other categories unlike SabNZB? or does torrenttomedia detect this as well? 

`[UserScript]
    #Use user_script for uncategorized downloads
    #Set the categories to use external script.
    #Use "UNCAT" to process non-category downloads, and "ALL" for all defined categories.
    [[UNCAT]]
        #Enable/Disable this subsection category
        enabled = 0
        Torrent_NoLink = 0 - ? doesnt hard link when set to 0?
        keep_archive = 1
        extract = 1
        #Enable if you are sending commands to a remote server for this category
        remote_path = 0
        #What extension do you want to process? Specify all the extension, or use "ALL" to process all files.
        user_script_mediaExtensions = .mkv, .avi, .divx, .xvid, .mov, .wmv, .mp4, .mpg, .mpeg
        #Specify the path to your custom script. Use "None" if you wish to link this category, but NOT run any external script.
        user_script_path = /nzbToMedia/userscripts/script.sh - I noticed there is no script for UNCAT
        #Specify the argument(s) passed to script, comma separated in order.
        #for example FP,FN,DN, TN, TL for file path (absolute file name with path), file name, absolute directory name (with path), Torrent Name, Torrent Label/Category.
        #So the result is /media/test/script/script.sh FP FN DN TN TL. Add other arguments as needed eg -f, -r
        user_script_param = FN - FN = Filename, FP = File path? DN = ?, TN = Torrent Name?, TL = ?
        #Set user_script_runOnce = 0 to run for each file, or 1 to only run once (presumably on the entire directory).
        user_script_runOnce = 0 - unsure how these work, clarify more?
        #Specify the successcodes returned by the user script as a comma separated list. Linux default is 0
        user_script_successCodes = 0 - unsure how these work, clarify more?
        #Clean after? Note that delay function is used to prevent possible mistake :) Delay is intended as seconds
        user_script_clean = 1 - unsure what it cleans?
        delay = 120
        #Unique path (directory) created for every download. set 0 to disable.
        unique_path = 1 - not sure why this is needed assume this is if you don't want ur Client to handle where the file finishes to? 
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = /Users/user/Downloads/Torrents/Downloads`

**Comment by clinton-hall** [comment]
Don't worry about [userscript] section, this is only used to run a custom script. You can specify this to run a customs script for "UNCAT".

If you want the script to recognize `Uncategorised` then add that in
```
[Torrent]
    categories = Uncategorised
```
Essentially this will detect and ignore that category... but if it doesn't identify the category it ignores it anyway. This was primarily added to help find the category within a directory structure for some clients.

Looking at the log, **the actual issue** you have here is that qbittorrent isn't sending the Category/Label

`'/Users/user/Apps/nzbToMedia/TorrentToMedia.py', '/Users/user/Downloads/Torrents/Downloads/|Black.Lightning.S02E01.Rise.of.the.Green.Light.Babies.720p.AMZN.WEBRip.DDP5.1.x264-SiGMA[rarbg]||31a4b3b83839923152aa05447be944c0fd8693f4'`
Note the `[rarbg]**||**31a` there should be a category in between the two `||`

So, make sure this is set up in qbittorrent `/Users/user/Apps/nzbToMedia/TorrentToMedia.py "%D|%N**|%L|**%I"`

Check to see if in fact the download is assigned a label/category in qbittorrent, and also check to see if there is any description when setting the postprocess script in qbittorrent to say what variables can be passed. I am wondering if they updated "label" `%L` to be "Category" `%C` or similar.

**Comment by XxUnkn0wnxX** [comment]
`/Users/user/Apps/nzbToMedia/TorrentToMedia.py "%D|%N|%L|%I"`

I do have it, because all the previous downloads while I as asleep passed right fine:

`2018-10-10 18:12:25 DEBUG   ::MAIN: Options passed into TorrentToMedia: ['/Users/user/Apps/nzbToMedia/TorrentToMedia.py', '/Users/user/Downloads/Torrents/Downloads/sickrage/|FBI.S01E03.Prey.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]|sickrage|9656426b1e454f451bec88143f841db56b516f87']`

**Comment by clinton-hall** [comment]
Sab passes the parameters differently.
According to what you showed above, this is working then for some torrents, and the category is passed as `sickrage` but in the previous examples the category wasn't passed, or there truly is no category for those downloads?

From what the log shows, qbittorrent did not pass in a cetegory (label) for download of Black.Lightning.S02E01.Rise.of.the.Green.Light.Babies.720p.AMZN.WEBRip.DDP5.1.x264-SiGMA[rarbg

**Comment by XxUnkn0wnxX** [comment]
I also started getting this error when I added: categories = Uncategorised under the [Torrent] Tag

`[22:03:16] [ERROR]::MAIN: Unable to migrate config file /Users/user/Apps/nzbToMedia/autoProcessMedia.cfg, exiting ...
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x11290d710>> ignored
`

**Comment by XxUnkn0wnxX** [comment]
ran another test just now. this one seemed to pass: https://gist.github.com/XxUnkn0wnxX/db627afe111fb1072ee56f428d28bad4

but when I have the categories = Uncategorised set it breaks the torrenttomedia script completely...

**Comment by clinton-hall** [comment]
`[22:03:16] [ERROR]::MAIN: Unable to migrate config file `
This looks as thought when you added `categories = Uncategorised` something was corrupted? Perhaps the spacing/formatting of the config got changed, or a CRLF (Windows) line ending etc... This is one real issue I have that I haven't been able to look into yet, but some small issues within the config can be problematic.
Or make sure you just added `Uncategorised` into the existing `categories` field and not trying to add a whole new line??

**Comment by XxUnkn0wnxX** [comment]
ya no issues if added to exisiting, config must not like duplicate lines..
