### ISSUE TITLE
NOOP (i.e. unnecessary) transcoding

### ISSUE THREAD

**Issue by brianjmurrell** [clinton-hall/nzbToMedia#1381]
I've been noticing that nzbtomedia is transcoding files unnecessarily.  Ultimate the transcoding operation is:

```
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
```

So I'm not sure what the point of that transcoding is.  Here's the entire [ffmpeg log for the transcode](https://github.com/clinton-hall/nzbToMedia/files/2464373/transcode.txt).

Is there something in there that I am missing that the transcode is achieving?

**Comment by clinton-hall** [comment]
No, this doesn't appear to achieve anything.
The intention of the transcoding was to allow files to be converted to a desired format. If the input format is ok, this can be ignored.

As a simple start point here, of you have `outputVideoExtension = .mkv` then you would usually want to have `ignoreExtensions = .mkv` unless you have a need to be doing some other transcode features (changing to a specific codec etc).

**Comment by brianjmurrell** [comment]
> No, this doesn't appear to achieve anything.

OK.  Glad I wasn't missing something.  :-)

> The intention of the transcoding was to allow files to be converted to a desired format. If the input format is ok, this can be ignored.

Indeed, understood.  I use it to make sure files are playable on any device around here and there are times when a transcode from unplayable codec to playable codec happens, and that's a good thing.

> As a simple start point here, of you have outputVideoExtension = .mkv then you would usually want to have ignoreExtensions = .mkv unless you have a need to be doing some other transcode features (changing to a specific codec etc).

As above, I do have a desire to transcode unplayable codecs to a playable one, which you can see from the `[Transcoder]` section snippet below which I have included to provide a more fulsome picture of my configuration here.

```
[Transcoder]
    # getsubs. enable to download subtitles.
    getSubs = 0
    # subLanguages. create a list of languages in the order you want them in your subtitles. 
    subLanguages = eng, spa, fra
    # transcode. enable to use transcoder
    transcode = 1
    ###### duplicate =1 will create a new file. =0 will replace the original
    duplicate = 0
    # concat. joins cd1 cd2 etc into a single video.
    concat = 1
    # IgnoreExtensions is a comma-separated list of extensions that will not be transcoded.
    ignoreExtensions = ""
    # outputFastStart. 1 will use -movflags + faststart. 0 will disable this from being used.
    outputFastStart = 0
    # outputQualityPercent. used as -q:a value. 0 will disable this from being used.
    outputQualityPercent = 0
    # outputVideoPath. Set path you want transcoded videos moved to. Leave blank to disable.
    outputVideoPath = ""
    # processOutput. 1 will send the outputVideoPath to SickBeard/CouchPotato. 0 will send original files.
    processOutput = 0
    # audioLanguage. set the 3 letter language code you want as your primary audio track.
    audioLanguage = eng
    # allAudioLanguages. 1 will keep all audio tracks (uses AudioCodec3) where available.
    allAudioLanguages = 0
    # allSubLanguages. 1 will keep all existing sub languages. 0 will discard those not in your list above.
    allSubLanguages = 0
    # embedSubs. 1 will embed external sub/srt subs into your video if this is supported.
    embedSubs = 1
    # burnInSubtitle. burns the default sub language into your video (needed for players that don't support subs)
    burnInSubtitle = 0
    # extractSubs. 1 will extract subs from the video file and save these as external srt files.
    extractSubs = 0
    # externalSubDir. set the directory where subs should be saved (if not the same directory as the video)
    externalSubDir = ""
    # hwAccel. 1 will set ffmpeg to enable hardware acceleration (this requires a recent ffmpeg)
    hwAccel = 0
    # generalOptions. Enter your additional ffmpeg options here with commas to separate each option/value (i.e replace spaces with commas).
    generalOptions = -report
    # outputDefault. Loads default configs for the selected device. The remaining options below are ignored.
    # If you want to use your own profile, leave this blank and set the remaining options below.
    # outputDefault profiles allowed: iPad, iPad-1080p, iPad-720p, Apple-TV2, iPod, iPhone, PS3, xbox, Roku-1080p, Roku-720p, Roku-480p, mkv, mp4-scene-release
    outputDefault = ""
    #### Define custom settings below.
    outputVideoExtension = .mkv
    outputVideoCodec = libx264
    VideoCodecAllow = "libx264,h264,h.264,AVC,avc,mpeg4,msmpeg4,MPEG-4"
    outputVideoPreset = ""
    outputVideoResolution = ""
    outputVideoFramerate = ""
    outputVideoBitrate = ""
    outputVideoCRF = ""
    outputVideoLevel = ""
    outputAudioCodec = ""
    AudioCodecAllow = ""
    outputAudioChannels = ""
    outputAudioBitrate = ""
    outputAudioTrack2Codec = ""
    AudioCodec2Allow = ""
    outputAudioTrack2Channels = ""
    outputAudioTrack2Bitrate = ""
    outputAudioOtherCodec = ""
    AudioOtherCodecAllow = ""
    outputAudioOtherChannels = ""
    outputAudioOtherBitrate = ""
    outputSubtitleCodec = ""
```

**Comment by clinton-hall** [comment]
Ok, so this is where you are probably operating outside of my original intentions. 
I had originally expected transcoding from one container to another, i.e. mkv to mp4 to allow playing on Ipads and Roku etc... so ignoring a playable container was added.
Obviously a lot more features were added and certainly changing of codecs is possible.

On the other side, this sort of transcoding should be quite fast... nothing to do, but I'll see what I can do here.

One thought I have is to create a check that if all codecs were set to copy (or -sn for subs) and the same container, with direct 1-1 mapping, this would ignore transcoding...

**Comment by brianjmurrell** [comment]
So, yes, while containers can be a point of [in]compatibility, just as much, if not even moreso can be the codecs within the container.  The container itself could very well be quite acceptable to a device but the codecs not so much.

> One thought I have is to create a check that if all codecs were set to copy (or -sn for subs) and the same container, with direct 1-1 mapping, this would ignore transcoding...

Yes, this would work.
