### ISSUE TITLE
API not functioning properly with SickChill

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [clinton-hall/nzbToMedia#1386]
[nzbtomedia API Test.zip](https://github.com/clinton-hall/nzbToMedia/files/2475331/nzbtomedia.API.Test.zip)

I have attached the zip with all the logs for all the tests I ran.

now this is very odd

via login user & pass within [SickBeard] config the directory gets passed on fine.

but when doing via API both NZB & Torrents when `tv_download_dir = ""` (blank) or `/Users/USER/Downloads/Torrents/Downloads/sickchill/`  within sickchill config file

`tv_download_dir` takes precedence. when it not blank it uses the above folder to process and ignores the folder given to by nzbtomedia. or when it blank it still ignore folder given by nzbtomedia and just gives error.

refer to logs for details... I ran numerous tests. in the end API broken. I feel like might be issue in SC end? 

this config is to do with Post-Processing in SC and I do have `enable the automatic post processor to scan and process any files in your Post Processing Dir?`option disabled... but somehow this gets triggered when using API and it prefers to use the path given (Post Processing Dir) AKA `tv_download_dir`

**Comment by XxUnkn0wnxX** [comment]
@clinton-hall @miigotu

**Comment by XxUnkn0wnxX** [comment]
I probably forgot to mention but I did have it setup like that: https://gist.github.com/XxUnkn0wnxX/9f24babb4f930b34bd695d509329009d

when I ran all the tests. as you can seen config file.

**Comment by clinton-hall** [comment]
In the config you have
```
[SickBeard]
    [[tv]]
        fork = auto
    [[sickchill]]
        fork = sickchill
```
In order to use the api, you need to have the api key set AND yo need to have `fork = auto` or `fork = sickbeard-api`

The logs for your api tests all say:
`MAIN: SickBeard:sickchill fork set to SickChill`
So, please test with the fork set to auto to see how this detects it.

**Comment by XxUnkn0wnxX** [comment]
nope: https://gist.github.com/XxUnkn0wnxX/9e6e2d3fcdb185707eaa381039c6c392

with auto or sickbeard-api with API set, it does not even  detect the fork

`Category:[sickrage] is not defined or is not enabled. Please rename it or ensure it is enabled for the appropriate section in your autoProcessMedia.cfg and try again.
`

![screen shot 2018-10-15 at 1 09 01 pm](https://user-images.githubusercontent.com/2242880/46926233-925e2b80-d07b-11e8-8552-c51613aa4d9a.jpg)

**Comment by miigotu** [comment]
```
2018-10-15 13:05:32 DEBUG   ::MAIN: SEARCH: Found the Category: sickrage in directory structure
```

**Comment by XxUnkn0wnxX** [comment]
ok from SAB no issues but from torrent it detects but for some reason it cannot find the files:

https://gist.github.com/XxUnkn0wnxX/694cd860588f416cdcca026a643f4ed5
https://gist.github.com/XxUnkn0wnxX/de0f7f62132c433ca67fbbb2b15fdc64

I feel like the torrenttomedia script is dropping the full path of the file location?

notices that the full both does not contain `[rarbg]`

South.Park.S22E03.The.Problem.with.a.Poo.UNCENSORED.720p.WEB-DL.AAC2.0.H264-YFN[rarbg]
changes to /Users/USER/Downloads/AppDL/sickchill/South.Park.S22E03.The.Problem.with.a.Poo.UNCENSORED.720p.WEB-DL.AAC2.0

something is getting lost in translation.

**Comment by XxUnkn0wnxX** [comment]
although I would like to add that once it finishes for some reason TorrentToMedia or SC? doesnt cleanup the original DL folder completely it always leaves the DL folder.

![screen shot 2018-10-15 at 1 52 48 pm](https://user-images.githubusercontent.com/2242880/46927530-a2790980-d081-11e8-9430-af6622a3ab10.jpg)

Logs:
https://gist.github.com/XxUnkn0wnxX/883fe0da6f73eaafe0b01707e4803b9f
https://gist.github.com/XxUnkn0wnxX/4af32ec63ad75c3456f7b2e55f4395f0

**Comment by clinton-hall** [comment]
Thanks for testing.
I'm about to have a few downloads go through tonight... that time of week ;)
So hopefully I'll be able to verify the same.

**Comment by XxUnkn0wnxX** [comment]
YW, here my final config file: https://gist.github.com/XxUnkn0wnxX/d50ad94f44d04b7aa8b982a68c35245c (blanked out pass & Keys) I have the delete stuff on. not sure why it failing to cleanup original folders? not coded in?

**Comment by XxUnkn0wnxX** [comment]
nothing useful in qbittorrent logs. but as you can see here:
![screen shot 2018-10-15 at 4 50 36 pm](https://user-images.githubusercontent.com/2242880/46932240-8897f080-d09a-11e8-8b10-36ca35811d97.jpg)

via manual it allows for selection to delete files, not just remove. so however you are removing the torrent after the processing should also contain the delete files flag or option. but I'm unsure where to find this in qbittorrent API...

**Comment by clinton-hall** [comment]
ok... qbittorrent call was set to delete, not delete_permanently...
Should now be set to do the right thing in currently nightly.

**Comment by XxUnkn0wnxX** [comment]
yep, just tested. works with no issues now.

**Comment by clinton-hall** [comment]
Great... So I just need to clean up my wiki now... Why does that sound harder than trying to trace through the code to make changes?

**Comment by markheloking** [comment]
> In the config you have
> 
> ```
> [SickBeard]
>     [[tv]]
>         fork = auto
>     [[sickchill]]
>         fork = sickchill
> ```
> In order to use the api, you need to have the api key set AND yo need to have `fork = auto` or `fork = sickbeard-api`
> 
> The logs for your api tests all say:
> `MAIN: SickBeard:sickchill fork set to SickChill`
> So, please test with the fork set to auto to see how this detects it.

As far as I can tell the code has no `sickbeard-api` fork, just a `sickrage-api` fork (which is indeed the right one it seems for SickChill), but auto fork detection for SickChill is broken (as outlined in #1393)

**Comment by clinton-hall** [comment]
fork = auto works, as does fork = sickbeard-api
This is indeed in the code: https://github.com/clinton-hall/nzbToMedia/blob/nightly/core/__init__.py#L67

However this is all in Nightly branch. So please switch to nightly and test.

**Comment by markheloking** [comment]
Directly from that link: `FORKS[FORK_SICKCHILL] = {"proc_dir": None, ...`, the SickChill api uses `path` not `proc_dir`, so yes, SickChill will work now with the `sickbeard-api` settings, but then why have the SickChill setting in there in the first place? (and having it not work).

I'll see to check if it works on the nightly with auto detection.

**Comment by markheloking** [comment]
If you use `proc_dir` instead of `path` the api returns a `please provide a valid path to process` error, so in practice on the API: no it does not (at least not current versions).

**Comment by clinton-hall** [comment]
`FORKS[FORK_SICKCHILL] = {"proc_dir": None, ...`
That is for the web UI... not for the api

For the api the only one that works (and is detected by the auto fork) is "SickBeard-api"
