### ISSUE TITLE
NZBget with NZBtoMedia to SiCKRAGE

### ISSUE THREAD

**Issue by Renetje666** [clinton-hall/nzbToMedia#1387]
My NZBtoMedia wont work. Her are some screenshots.
![autoprocessmedia cfg](https://user-images.githubusercontent.com/26803653/46911141-6b0c3f00-cf53-11e8-8a30-d6d65f820c62.png)
![nzbget](https://user-images.githubusercontent.com/26803653/46911142-6ba4d580-cf53-11e8-8901-501803771ad7.png)

I thoug it because SiCKRAGE so i reported it there.
https://forums.sickrage.ca/t/sickbeard-does-not-support-failed-downloads/232/11

But there they send me here.

Can you help me?

**Comment by clinton-hall** [comment]
To help determine what has happened here, can you please enable debug logging by editing autoProcessMedia.cfg
```
[General]
    log_debug = 1

[SickBeard]
    [[tv]]
        fork = auto
```
Also, please update to latest nightly build
```
cd /home/pi/scripts/nzbToMedia
git checkout nightly
git pull
```
Then show the logs from the next postprocess.

**Comment by Renetje666** [comment]
Here you go
[nzbget.log](https://github.com/clinton-hall/nzbToMedia/files/2476792/nzbget.log)
[nzbtomedia.log](https://github.com/clinton-hall/nzbToMedia/files/2476793/nzbtomedia.log)
![schermafdruk van 2018-10-14 21-21-35](https://user-images.githubusercontent.com/26803653/46921195-7d8c8400-cff8-11e8-828b-11af463ce77d.png)

**Comment by Renetje666** [comment]
This is a new install of my raspberry pi 3. 
Had a 8GB card but that was full (so can use that 1 anymore) so 1 got a 32GB card and started over. 

Raspbian stretch 27-06-2018
SR version bdb914ef724206aca0c7dd1dd6e69fc0ac027cd2
NZBget 20.0
NZBtoMedia fb24a987cae0015c18c1952c369702f55bcb4a24

The only thing what realy changed was SiCKRAGE now you have 2 logon (aut.sickrage.ca). So i first contacted the forums at sickrage.ca.
https://forums.sickrage.ca/t/sickbeard-does-not-support-failed-downloads/232/11 

But they send me here.

**Comment by clinton-hall** [comment]
ok, just to rule out any silly little issues here...
Can you check that the correct SickRage is running on port 8081, and that the api you have in autoPorcessMedia.cfg is the correct api key for your new SickRage install?

What do you get if you go to `http://<ip_for_pi>:8081/api/<apikey>/?cmd=help&subject=postprocess`
in your local browser?

**Comment by Renetje666** [comment]
![schermafdruk van 2018-10-15 00-08-11](https://user-images.githubusercontent.com/26803653/46922810-dd8e2500-d00e-11e8-8856-6575c958b30e.png)
Then i get a error page

**Comment by Renetje666** [comment]
I took a beter look at my api-key and copied it again. That did the trick. So sorry for this mistake. (nooob)
