### ISSUE TITLE
nzbtoheadphones fails, it seems the variable "delete_failed" is missing

### ISSUE THREAD

**Issue by ernstblaauw** [clinton-hall/nzbToMedia#1388]
Hi,

I try to get nzbtoheadphones running. It does not succeed. As far as I can tell from the logs, it seems the variable delete_failed is missing. How can I set that one? In the global settings in nzbget (nzbtomedia), I don't see this field. 
I also tried the nightly branch, but it gave the same error.

Thanks for helping!
Ernst

info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones:  Exception TypeError: "'NoneType' object is not callable" in <bound  method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess  object at 0x76c39350>> ignored
-- | -- | --
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones: KeyError: 'delete_failed'
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones:     delete_failed = int(cfg["delete_failed"])
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones:   File "/home/osmc/nzbget/scripts/nzbToMedia/core/autoProcess/autoProcessMusic.py", line 124, in process
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones:      result = autoProcessMusic().process(sectionName, inputDirectory,  inputName, status, clientAgent, inputCategory)
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones:   File "/home/osmc/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 719, in process
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones:     failureLink=failureLink)
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones:   File "/home/osmc/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 818, in main
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones:     result = nzbToMedia.main(sys.argv, section)
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones:   File "/home/osmc/nzbget/scripts/nzbToMedia/nzbToHeadPhones.py", line 124, in <module>
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones: Traceback (most recent call last):
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones:  [21:16:40] [INFO]::MAIN: Calling HeadPhones:headphones to  post-process:<download>
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones: [21:16:40] [INFO]::MAIN: Auto-detected SECTION:HeadPhones
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones: [21:16:40] [INFO]::MAIN: Script triggered from NZBGet Version 21.0-testing-r2220.
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones: [21:16:40] [INFO]::MAIN: #########################################################
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones: [21:16:40] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones: [21:16:40] [INFO]::MAIN: #########################################################
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones: [21:16:40] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones: [21:16:40] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones: [21:16:40] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones: [21:16:40] [WARNING]::MAIN: Failed to locate ffmpeg. Transcoding disabled!
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones:  [21:16:40] [INFO]::MAIN: nzbToMedia  Version:5d5d69ecdd5fe043be8a915ffa26e8427c9641c4 Branch:master (Linux  4.14.34-6-osmc)
info | Sun Oct 14 2018 21:16:40 | nzbToHeadPhones: [21:16:40] [INFO]::MAIN: No update needed
info | Sun Oct 14 2018 21:16:38 | nzbToHeadPhones: [21:16:38] [INFO]::MAIN: Checking if git needs an update
info | Sun Oct 14 2018 21:16:38 | nzbToHeadPhones: [21:16:38] [INFO]::MAIN: Checking database structure...

**Comment by clinton-hall** [comment]
Sorry about this. I believe this has been fixed in nightly build, but not yet in master.

Can you please switch to nightly build and test?

**Comment by ernstblaauw** [comment]
On nightly, I have the same problem.

**Comment by clinton-hall** [comment]
ok, update to latest version (git pull). then go back to the nzbToHeadphones script within NZBGet WebUI, save changes, and restart NZBGet.
You can then postprocess again and verify if this is fixed.

**Comment by ernstblaauw** [comment]
Thank you very much for the fast solution! It works now 👍
