### ISSUE TITLE
Transmission over SSL/HTTPS?

### ISSUE THREAD

**Issue by a10kiloham** [clinton-hall/nzbToMedia#1391]
Setting the server/port as https://192.168.1.2 and port to my SSL port fails. Should there be SSL support configurable in some other way?
Thanks

**Comment by clinton-hall** [comment]
so you have this set as
```
[Torrent]
    TransmissionHost = https://192.168.1.2
    TransmissionPort = <SSL port>
```
and this is not working?
According to the Transmission client, this should actually parse this Host through six module to determine the protocol... The logging in TorrentToMedia will log this with an http:// in front, btu the functionality should work.

```
logger.debug("Connecting to {0}: http://{1}:{2}".format(
                clientAgent, core.TRANSMISSIONHOST, core.TRANSMISSIONPORT))
```
This adds the https:// to the logging, then 
```
tc = TransmissionClient(core.TRANSMISSIONHOST, core.TRANSMISSIONPORT,
                                    core.TRANSMISSIONUSR,
                                    core.TRANSMISSIONPWD)
```
then the Transmission client takes over
```
class Client(object):
    """
    Client is the class handling the Transmission JSON-RPC client protocol.
    """

    def __init__(self, address='localhost', port=DEFAULT_PORT, user=None, password=None, http_handler=None,
                 timeout=None):
        if isinstance(timeout, (integer_types, float)):
            self._query_timeout = float(timeout)
        else:
            self._query_timeout = DEFAULT_TIMEOUT
        urlo = urlparse(address)
        if not urlo.scheme:
            self.url = 'http://{host}:{port}/transmission/rpc/'.format(host=address, port=port)
        else:
            if urlo.port:
                self.url = '{url.scheme}://{url.hostname}:{url.port}{url.path}'.format(url=urlo)
            else:
                self.url = '{url.scheme}://{url.hostname}{url.path}'.format(url=urlo)
            LOGGER.info('Using custom URL {url!r}.'.format(url=self.url))
```
so if this is failing in the urlparse (from six) it will not work.

As a local fix (requires stashing your own commit) you can edit this:
https://github.com/clinton-hall/nzbToMedia/blob/master/core/transmissionrpc/client.py#L145
from:
`            self.url = 'http://{host}:{port}/transmission/rpc/'.format(host=address, port=port)`
to
`            self.url = 'https://{host}:{port}/transmission/rpc/'.format(host=address, port=port)`

**Comment by a10kiloham** [comment]
Ok thanks. I'll stash my own commit. Cheers!
