### ISSUE TITLE
Struggling with PostProcessing to Sickrage/sickbeard

### ISSUE THREAD

**Issue by billbo01028** [clinton-hall/nzbToMedia#1394]
Fresh install of Sicrage and nzbget on Windows.  I get the following error when attempting to post process:

[The.Chilling.Adventures.of.Sabrina.S01E10.WEBRip.x264-STRiFE-postbot.log](https://github.com/clinton-hall/nzbToMedia/files/2568678/The.Chilling.Adventures.of.Sabrina.S01E10.WEBRip.x264-STRiFE-postbot.log)

**Comment by billbo01028** [comment]
I should add, I had to install Python for windows and PIP to clear errors with that, so you will notice python errors in that log

**Comment by clinton-hall** [comment]
The latest entry in the log suggest pywin32 still isn't installed.
You need to have the pywin32 installed that matches the python version you have.

https://github.com/clinton-hall/nzbToMedia/wiki/installation

**Comment by billbo01028** [comment]
That was is!  Pywin32 not installed correctly, all fixed now, thank you!
