### ISSUE TITLE
Category:[tv] is not unique, ['SickBeard', 'NzbDrone'] are using it. 

### ISSUE THREAD

**Issue by iDVB** [clinton-hall/nzbToMedia#1395]
```
nzbToNzbDrone: [02:22:34] [ERROR]::MAIN: Category:[tv] is not unique, ['SickBeard', 'NzbDrone'] are using it. Please rename it or disable all other sections using the same category name in your autoProcessMedia.cfg and try again.
```

Still having this issue with V11.05 27/06/2018 of nzbToMedia pulled directly from the repo.
Weird part is that it seems that it was working at first and then at some point it failed and now all I get are these errors. 

I only use NZBDrone (Sonarr) and CouchPotato settings. I have Sonarr set to `tv` and Sickbeard set to `donotuse`. But continue to get this error. 

I've read people talking about forcablity "disabling" sickbeard in the config. But since up till now I've only edited things in the UI, I'm not sure which file is the config. I did search for it unsuccessfully though.

![image](https://user-images.githubusercontent.com/189506/48456296-848beb00-e78c-11e8-855b-c8080d9d44c0.png)

**Comment by clinton-hall** [comment]
Wherever your nzbToMedia installation is, there will be a file inside of this directory called autoProcessMedia.cfg

within this file look for 
```
[SickBeard]
    [[tv]]
```
You can disable this via either of the following

1. Rename the category from `tv` to `tv2`
```
[SickBeard]
    [[tv2]]
```
2. enabled = 0
```
[SickBeard]
    [[tv]]
        enabled = 0
```

By Default this should not have been enabled, but if you ever ran nzbToSickBeard.py this would have enabled by default.

**Comment by iDVB** [comment]
Yes, I've seen this file however, mine in named `autoProcessMedia.cfg`, and everything in it seems to be `enabled = 0`. Even though the NZBGet UI all shows NZBDrone, Couch etc all working and enabled.

Anyway, I ended up fixing the issue by changing the category of NZBDrone to `DroneTv` and ensuring NZBDrove's category is set to the same. 

🤷‍♂️

**Comment by breezytm** [comment]
@clinton-hall I think it would be ideal to add an Enable 0 | 1 button at the top of each script in NZBGet for example. Would make this issue so much easier for troubleshoot. Also if let's say a category, 'music', is already being used, the log file can explicitly say more than one script is using 'category music. Only one can be used at a time. Please check both NzbToHeadphones and NzbToLidarr and disable one or change the category to music2 if they are both in use" 

Something of that nature.

**Comment by clinton-hall** [comment]
@breezytm 
I'll see what I can do. I guess I hadn't considered adding an enable/disable as the scripts themselves can be enabled for only specific categories in NZBGet, but I see where this can get confusing with the category names.

**Comment by breezytm** [comment]
I must say it got me confused a few times and you and I both know I've been using your scripts for ages now. It wasn't until recently I just realized all I need to make, when using NZBGet, is to make a copy of the autoProcessMedia.cfg.spec file and name it autoProcessMedia. That's it.. Frankly every time I introduce a new application I always mistakenly go in the config file to configure it and then I started having issues. Each time I have to try to resolve it. If the error message explicitly told me what could be wrong I would have saved a lot of troubleshooting time and energy.

**Comment by iDVB** [comment]
@clinton-hall 
Weird..... years later I'm having this same issue again and google my own github issue trying to resolve. This time it's happening after I started using Radarr and stopped using CouchPotato.

The part that is odd is that I've ...
- `removed` couchpotato from the extension scripts page and now only radarr scripts are being used. 
- Gave radarr the category "movies" and changed the category for CouchPotato to "moviesold".

Other than that, not sure where else I need to disable or kill the couchpotato category... but i'm still getting this error.

I should also call out that I've not edited the scripts directly... I only ever use the nzbget UI.

**Comment by clinton-hall** [comment]
How did you remove nzbToCouchpotato from extension scripts? You need to remove this from BOTH Extension Scripts -> Extensions AND CategoryX -> Extensions. 
You should also ensure that the CategoryX -> Extensions is set to call nzbToRadarr (for the movies category)

Note. I recommedn removing nzbToNZBDrone from Extension Scripts -> Extensions and add this to the CategoryX -> Extensions (for the category used by nzbDrone)

In the NZBTOCOUCHPOTATO page, change the category to moviesold. Also in NZBTOMEDIA change cpsCategory to moviesold.

In NZBTORADARR change category to movies. In NZBTOMEDIA change raCategory to movies.

Restart NZBGet to apply changes. Then try and postprocess again.

**Comment by iDVB** [comment]
I did not "remove" the script itself, I simply removed it from the excensions list 
![image](https://user-images.githubusercontent.com/189506/84029463-6c784f80-a960-11ea-8127-0c4a3d186269.png)

and changed the category in the movie script UI to something else. 
![image](https://user-images.githubusercontent.com/189506/84029525-8b76e180-a960-11ea-9a83-4d0d577654f0.png)

I even tried setting it to something else... but still got that same error.

IS there a way to remove the script itself?

**Comment by clinton-hall** [comment]
There have been a few changes over the years, both here and at NZBGet.
I think the best way to resolve this is to change the way the scripts are called.

First remove the nzbTo* scripts from the Extensions (these all run on every download, unless specified differently in categories... so it was intended that nzbToMedia be run here as a catch-all for all downloads. This is a different option that we could pursue...)

![image](https://user-images.githubusercontent.com/1888006/84086136-4378bd00-aa3b-11ea-9a07-abb27626e387.png)

Now, in Categories you set each category to call the specific script you want:
![image](https://user-images.githubusercontent.com/1888006/84086472-18db3400-aa3c-11ea-85c1-c735f4165da9.png)
Note: You can set these to call other scripts before (e.g. DeleteSamples and ResetDateTime first then nzbTo*

Now the only issue is that the .cfg may still have CP set to use `movies`. The setup above should correct that. If not we can either set a downlaod to call nzbToCouchPotato with the new category in the config (to force the chnages into the cfg) or we can manually edit the cfg....
Let me know how the above changes work, and we can then look at either of these 2 options if required.
