### ISSUE TITLE
Unrar fails

### ISSUE THREAD

**Issue by FlyingPersian** [clinton-hall/nzbToMedia#1399]
Hi
I've had this issue 3 yeaes ago as well and we couldn't fix it.. My nzbToMedia fails to unrar my movies and shows. Extraction is enabled in the autoProcessMedia.cfg, and I tried hard-linking, sym-linking, and copying (no). It seems as doesn't really attempt to copy over the shows/movies, it just tries to unpack and fails. 

Here the autoProcessMedia.cfg: https://pastebin.com/cHNCgVuQ

Here the log (they're the same, whether I use hard-linking, sym-linking, or copying): https://pastebin.com/LvT4UjiE

Here a working manual run of a file without rars: https://pastebin.com/QQW6z7tR

You can see at the time stamps that no time passes between copy-linking and trying to extract, meaning it doesn't really try to copy. The folder is created and the nfo is moved, but the rar files aren't. I tried both manual run and automatic run. Permissions in the respective folders are fine (all owned by user "admin"). unrar itself works fine, manually unraring is not an issue. The script also works fine when there are no rar files, thus only .mkv files or whatever. 

This all runs in an iocage jail under FreeNAS 11.2

**Comment by clinton-hall** [comment]
Can you confirm the naming of the files in these rar downloads?

are these
<archive name>.rar.r01
<archive name>.rar.r02
etc.

or are they just
<archive name>.r01
<archive name>.r02
etc.

**Comment by clinton-hall** [comment]
Please update to latest nightly branch and test.

**Comment by nikagl** [comment]
Correct me if I'm wrong, but extracting seems to not work anymore... I now get errors after ffprobe (masked out filenames, folders and apikey from the logging):
```
2018-12-04 00:24:31 DEBUG   ::MAIN: Checking for archives to extract in directory: X:\Test
2018-12-04 00:24:31 INFO    ::MAIN: Extracting X:\Test\testfile.r00 to X:\TestProcess
2018-12-04 00:24:31 DEBUG   ::MAIN: Extracting ['X:\\Python\\nzbToMedia\\core\\extractor\\bin\\invisible.cmd', 'X:\\Python\\nzbToMedia\\core\\extractor\\bin\\AMD64\\7z.exe', 'x', '-y'] X:\Test\testfile.r00 X:\TestProcess
2018-12-04 00:26:27 INFO    ::MAIN: EXTRACTOR: Extraction was successful for X:\Test\testfile.r00 to X:\TestProcess
2018-12-04 00:26:36 INFO    ::MAIN: FLATTEN: Flattening directory: X:\TestProcess
2018-12-04 00:26:36 DEBUG   ::MAIN: Checking for empty folders in:X:\TestProcess
2018-12-04 00:26:36 INFO    ::MAIN: Found 1 media files in X:\TestProcess
2018-12-04 00:26:36 INFO    ::MAIN: Calling CouchPotato:movie to post-process:Test
2018-12-04 00:26:36 INFO    ::MAIN: Attemping imdbID lookup for Test
2018-12-04 00:26:36 INFO    ::MAIN: Searching folder and file names for imdbID ...
2018-12-04 00:26:36 INFO    ::MAIN: Searching IMDB for imdbID ...
2018-12-04 00:26:37 INFO    ::MAIN: Unable to determine imdbID: No api key provided for ombdapi.com.
2018-12-04 00:26:37 DEBUG   ::SERVER: Attempting to connect to server at http://localhost:8082/api/YYYY/
2018-12-04 00:26:38 DEBUG   ::SERVER: Server responded at http://localhost:8082/api/YYYY/
2018-12-04 00:26:38 DEBUG   ::MAIN: Opening URL: http://localhost:8082/api/YYYY/media.list with PARAMS: {}
2018-12-04 00:26:41 DEBUG   ::MAIN: calling command: ffprobe.exe -v quiet -print_format json -show_format -show_streams -show_error X:\Python\nzbToMedia\tests\test.mp4
2018-12-04 00:26:42 INFO    ::TRANSCODER: Checking [testfile.avi] for corruption, please stand by ...
2018-12-04 00:26:42 DEBUG   ::MAIN: calling command: ffprobe.exe -v quiet -print_format json -show_format -show_streams -show_error X:\TestProcess\testfile.avi
2018-12-04 00:26:43 ERROR   ::TRANSCODER: FAILED: [testfile.avi] is corrupted!
2018-12-04 00:26:43 INFO    ::COUCHPOTATO: Status shown as success from Downloader, but corrupt video files found. Setting as failed.
2018-12-04 00:26:43 POSTPROCESS::COUCHPOTATO: FAILED DOWNLOAD DETECTED FOR Test
2018-12-04 00:26:43 ERROR   ::COUCHPOTATO: Could not find a downloaded movie in the database matching Test, exiting!
2018-12-04 00:26:43 ERROR   ::MAIN: A problem was reported in the autoProcess* script. If torrent was paused we will resume seeding
2018-12-04 00:26:43 DEBUG   ::MAIN: Starting torrent Test in utorrent
2018-12-04 00:26:50 ERROR   ::MAIN: A problem was reported in the X:\Python\nzbToMedia\TorrentToMedia.py script.
```

To test this, I also executed the command line manually with the r00 file and the rar file:
```
C:\Python\nzbToMedia\core\extractor\bin\AMD64\7z.exe x -y X:\Test\testfile.r00 -p-

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
Processing archive: X:\Test\testfile.r00
Extracting  testfile.avi     CRC Failed
Sub items Errors: 1

C:\Python\nzbToMedia\core\extractor\bin\AMD64\7z.exe x -y X:\Test\testfile.rar -p-

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
Processing archive: X:\Test\testfile.rar
Extracting  testfile.avi
Everything is Ok
Size:       732325888
Compressed: 732330886
```

As you can see CRC fails when doing it on the r00 file. Not sure why... will hopefully test some more tomorrow. I will also look into why using the invisible.cmd/vbs method (which originally came from me if I remember correctly) it does not see errors from 7z correctly and see whether we can redirect 7z.exe output into the log so these types of errors can be debugged easier...

**Comment by clinton-hall** [comment]
thanks @nikagl 
This does show something I was concerned about.... this should actually work with any archive where they are .r00 .r01 .r02 etc (as per the original post).... but not archives that have .rar .r00 .r01 etc. as per your test... but I only considered the possibility of double-extraction and never expected the .r00 extraction to fail.

Not sure if this only pertains to 7zip on Windows? unrar on linux may work?

**Comment by nikagl** [comment]
Using a newer version of 7z.exe and 7z.dll also has this issue. I guess you'd need to check for .rar before using .r00? Newer release does verbose a little more. For some reason, when using .r00 it thinks .rar does not exist and will not extract it:

```
C:\Python\nzbToMedia\core\extractor\bin\AMD64\7z.exe x -y X:\TEMP\test.rar -p-

7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30

Scanning the drive for archives:
1 file, 15000000 bytes (15 MiB)

Extracting archive: X:\TEMP\test.rar
--
Path = X:\TEMP\test.rar
Type = Rar
Physical Size = 15000000
Total Physical Size = 732330886
Characteristics = Volume FirstVolume VolCRC
Solid = -
Blocks = 1
Multivolume = +
Volume Index = 0
Volumes = 49

Everything is Ok

Size:       732325888
Compressed: 732330886

C:\Python\nzbToMedia\core\extractor\bin\AMD64\7z.exe x -y X:\TEMP\test.r00 -p-

7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30

Scanning the drive for archives:
1 file, 15000000 bytes (15 MiB)

Extracting archive: X:\TEMP\test.r00
--
Path = X:\TEMP\test.r00
Type = Rar
Physical Size = 15000000
Total Physical Size = 717330886
Characteristics = Volume VolCRC
Solid = -
Blocks = 1
Multivolume = +
Volume Index = 1
Volumes = 48

ERROR: CRC Failed : test.avi

Sub items Errors: 1

Archives with Errors: 1

Sub items Errors: 1
```

**Comment by nikagl** [comment]
I tried creating a pull request, hope this worked:
https://github.com/clinton-hall/nzbToMedia/pull/1400

**Comment by zamsler** [comment]
Forgive me piggy backing this, but I am seeing the same issue on alpine linux.
The issue occurs on master and nightly.

Manual unrar works successfully

Debug log
https://pastebin.com/kQn5F6ub

**Comment by nikagl** [comment]
Judging from this it's not a problem because it's extracting the wrong file, but something in the extractor code. It fails somewhere in extractor.extract as the error is from nzbToMediaUtil.py and no lines from extractor.py which you'd expect... Maybe adding additional debugging in nzbToMediaUtil.py would help? 

For instance add:
```
        logger.debug("Running extractor for file {0} in dir {1}", inputFile, dst or dirPath)
```

In front of:
```
        try:
            if extractor.extract(inputFile, dst or dirPath):
```

And try again to see what file it's trying to extract? Hope @clinton-hall has a better idea of what be happening on unix systems that causes this...

**Comment by zamsler** [comment]
Added. Output:

https://pastebin.com/BUCFZHqN

**Comment by nikagl** [comment]
That looks fine. You can remove the debug line again.

If you want to troubleshoot further, you can try adding more debug lines. But we may also want to wait for @clinton-hall?

Maybe somehow the extension is not correctly recognized? I don't entirely understand the code here:
```
    ext = os.path.splitext(filePath)
    cmd = []
    if ext[1] in (".gz", ".bz2", ".lzma"):
        # Check if this is a tar
        if os.path.splitext(ext[0])[1] == ".tar":
            cmd = EXTRACT_COMMANDS[".tar{ext}".format(ext=ext[1])]
    elif ext[1] in (".1", ".01", ".001") and os.path.splitext(ext[0])[1] in (".rar", ".zip", ".7z"):
        cmd = EXTRACT_COMMANDS[os.path.splitext(ext[0])[1]]
    elif ext[1] in (".cb7", ".cba", ".cbr", ".cbt", ".cbz"):  # don't extract these comic book archives.
        return False
    else:
        if ext[1] in EXTRACT_COMMANDS:
            cmd = EXTRACT_COMMANDS[ext[1]]
        else:
            core.logger.debug("EXTRACTOR: Unknown file type: {ext}".format
                              (ext=ext[1]))
            return False
```

We could try adding debug info for instance after the ext = os.path.splitext(filePath) line:
```
    logger.debug("Extension is {0} for file {1}", ext, filePath)
```

Regards,

Nika.

**Comment by FlyingPersian** [comment]
@nikagl can't you just add the lines to your local copy and check what's wrong? I'm not that familiar with python anymore..

**Comment by clinton-hall** [comment]
ok, initially I missed the fact that this failed to extract the .rar file. I thought it was ignoring the .r00 file. I am now reversing the previous commit. The issue is the failed extraction.

**Comment by nikagl** [comment]
@FlyingPersian, I don't have the issue so it's not something I can test. It works fine on Windows, but for some reason on your (and @zamsler) environment the extraction command is not correctly executed. Using extra debug lines I hope we can figure it out... any suggestion from your side @clinton-hall? Why does extractor.extract fail? It does not show any lines while executing it, so none of the core.logger lines are hit, which means we need to add additional debugging...

**Comment by clinton-hall** [comment]
I just tested passing in the variables as per @zamsler logs... On my system it reports a "Extraction failed for /downloads/_SRPEND/Law.And.Order.S10E12.MULTi.1080p.HDTV.x264-HYBRiS/law.and.order.s10e12.multi.1080p.hdtv.x264-hybris.rar. Result was 127" so it works past the points of failure at their end.

Looking at the code, it can only be failing at the point of creating the output directory (but in @FlyingPersian logs this has already happened, and that function has try/except in it anyway) or in the part where it reads the Passwords file. But @FlyingPersian config doesn't show this as being configured...

**Comment by clinton-hall** [comment]
Please update to latest nightly and test again... ensure 
```
[General]
    log_debug =1
```
then post logs.

**Comment by zamsler** [comment]
Updated.
Log:

https://pastebin.com/4TEAzAaX

Manual extract:
https://pastebin.com/mCSLfLVg

**Comment by zamsler** [comment]
SUCCESS! Thank you @clinton-hall  @nikagl

**Comment by nikagl** [comment]
@FlyingPersian I think this can be closed?

**Comment by FlyingPersian** [comment]
I'm sorry, I have been super busy the last few days! 

I can confirm that it's working over here as well!! Thanks a lot @clinton-hall
