### ISSUE TITLE
Auto subtitle translation

### ISSUE THREAD

**Issue by nikagl** [clinton-hall/nzbToMedia#1402]
Localized subtitles are often not available. Does anyone have tips or references to Python scripts that allow translation of the downloaded English sub if localized download fails? I have always used Subtitle Edit to do translation but with the latest changes to the Google API it does not work anymore...

**Comment by clinton-hall** [comment]
https://github.com/naruse/SRTTranslate  -  Only works in Python3

https://github.com/gunesmes/subtitle_translator

https://pypi.org/project/pysrttranslator/

https://pypi.org/project/subtitle_translator/

any of these could theoretically be added to this script....
