### ISSUE TITLE
Nightly fails with SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by labrys** [clinton-hall/nzbToMedia#1433]
See #1425 

Lib updates do not appear to be fully Python 2 compatible.

**Comment by labrys** [comment]
No need.  I already have a fix in place.  Just add the python 2 version `yaml` to `libs\py2`.  Since its inserted in the path ahead of custom it overrides the Python 3 yaml in `libs\custom`.  `BeautifulSoup4` has the same issue.

**Comment by clinton-hall** [comment]
all seem to be running ok now.
did you have a solution for the updater to remove/clean-up old directories?

**Comment by clinton-hall** [comment]
ahhh... even using `git clean -fd`
still results in
```
Traceback (most recent call last):
  File "./nzbToMedia.py", line 630, in <module>
    import core
  File "/volume1/Public/test/nzbToMedia/core/__init__.py", line 40, in <module>
    from core.autoProcess.autoProcessComics import Comic
  File "/volume1/Public/test/nzbToMedia/core/autoProcess/autoProcessComics.py", line 9, in <module>
    from core.nzbToMediaUtil import convert_to_ascii, remote_dir, server_responding
  File "/volume1/Public/test/nzbToMedia/core/nzbToMediaUtil.py", line 22, in <module>
    from qbittorrent import Client as qBittorrentClient
```
left over `/nzbToMedia/core/qbittorrent` directory contains `.pyc` files

I need to 
```
git pull
find . -name "*.pyc" -exec rm -f {} \;
git clean -fd
git pull
```
not sure if there is a cleaner way to remove the .pyc and/or force a delete of the old directories no-longer tracked in git....  but if the script updates and then tries to execute, these left-over folders will screw up the imports etc....

**Comment by SerhatG** [comment]
I can confirm I get the same issues as the last comment. After removing leftover `.pyc` files it works as expected. Didn't need a `git clean -fd` on my side.
Let me know if I can test something out.

**Comment by labrys** [comment]
I do have a couple of ideas for cleaning up the files, but I have a lot more refactors I would like to do before I submit it.  

The cleanest would be to read the current config, run `git clean -fdx` and then rewrite the config file.  The `-x` option deletes files included in the `.gitignore`.  This would also delete the users config, thus the reason for reading and rewriting it.

Another, possibly safer, option would be to remove `*.py[co]` from the `.gitignore`, run `git clean -fd` and then restore the original `.gitignore`.

Both of those would need to be tested first of course, to avoid any problems.  I do have some other options if those two prove problematic.

**Comment by nikagl** [comment]
Thanks. Also on windows had to remove old pyc files...

**Comment by littlejeem** [comment]
I can confirm that I had the same issues running on nightly branch. running these commands from @clinton-hall earlier post resolved the issue. Running on Debian Stretch.

git pull
find . -name "*.pyc" -exec rm -f {} \;
git clean -fd
git pull
