### ISSUE TITLE
Refactors leave behind unused directories and bytecode after update

### ISSUE THREAD

**Issue by labrys** [clinton-hall/nzbToMedia#1436]
See discussion from #1433.

Possible solutions:

- Cache the users config, run `git clean -fdx`, then restore the config
- Remove bytecode from `.gitignore` (i.e. *.py[co]), run `git clean -fd`, then restore `.gitignore`
- Use python script to find and remove bytecode, then run `git clean -fd` to clean up directories

**Comment by clinton-hall** [comment]
Great work...
Now, once we have all of this tested and ready for merge (or more importantly, before the merge) we will need to merge #1440 into dev, Master, and OSX branches before everything else.

As I see it, we need the "updater" to be updated to include this cleanup before the rest of the code updates. Otherwise the first update will pull all of the new code, but won't run the cleanup and basically everyone would have a broken setup...

**Comment by nikagl** [comment]
Hmmm. I am not sure what would happen when you run the cleanup and do not yet get the new code. The old code will generate the pyc files again when it executes the first time, and that might also cause the fail? Also, with git clean -fd it will purge any customized files (for instance, I had a cmd that starts nzbToMedia that was deleted. So... how safe it is to run this automatically?

**Comment by SerhatG** [comment]
I had the same problem but with a different stacktrace this time.. Cleaning the `*.pyc` files manually helped.

```Shell
[11:17:04] [INFO]::MAIN: Loading config from [/home/nzbget/scripts/nzbToMedia/autoProcessMedia.cfg]
Traceback (most recent call last):
  File "./nzbToMedia.py", line 932, in <module>
    exit(main(sys.argv))
  File "./nzbToMedia.py", line 760, in main
    core.initialize(section)
  File "/home/nzbget/scripts/nzbToMedia/core/__init__.py", line 323, in initialize
    main_db.upgrade_database(main_db.DBConnection(), databases.InitialSchema)
AttributeError: 'module' object has no attribute 'InitialSchema'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.PosixProcess object at 0x7f51733104d0>> ignored
nzbget@HTPC:~/scripts/nzbToMedia$ find . -name "*.pyc" -exec rm -f {} \;
nzbget@HTPC:~/scripts/nzbToMedia$ ./nzbToMedia.py
[11:17:16] [INFO]::MAIN: Loading config from [/home/nzbget/scripts/nzbToMedia/autoProcessMedia.cfg]
[11:17:16] [INFO]::MAIN: Checking database structure...
[11:17:16] [INFO]::MAIN: Checking if git needs an update
[11:17:16] [INFO]::MAIN: No update needed
[11:17:16] [INFO]::MAIN: nzbToMedia Version:cbc8655b9a4cfb3d1393210335b6d77a2ff9c5e0 Branch:nightly (Linux 4.4.0-139-generic)
[11:17:16] [INFO]::MAIN: #########################################################
[11:17:16] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[11:17:16] [INFO]::MAIN: #########################################################
[11:17:16] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[11:17:16] [ERROR]::MAIN: Failed to add directories from {} for post-processing: 'Section' object has no attribute 'endswith'
[11:17:16] [ERROR]::MAIN: Failed to add directories from {} for post-processing: 'Section' object has no attribute 'endswith'
[11:17:16] [INFO]::MAIN: The ./nzbToMedia.py script completed successfully.```

**Comment by labrys** [comment]
@clinton-hall You are correct, a clean-up method will need to be implemented and merged to master before nightly is merged.

@nikagl Try running `git clean -fdx core libs`.  This is what the current cleanup code does, and should not  present any problems as user-code should not exist in the `core` and `libs` folders.

@SerhatG thanks for the bug report.  If you could re-run with debug logging enabled so I can investigate the cause of the errors you're getting after cleanup, it would be appreciated.

**Comment by labrys** [comment]
Ok so it looks like the most effective would be to run:
```
# Remove bytecode
git clean -fdx -e *.* -e !*.py[co] -e !/**/__pycache__/

# Remove folders
git clean -fdx core libs
```
The most convenient way to do this would be a `cleanup.py` script in the project root.

This still leaves the issue of running the cleanup automatically after update.  As @nikagl pointed out bytecode files in use when the cleaner runs may not be properly cleaned.  As I see it we have several potential options:

#### 1. Require users to run the cleanup script manually
Pros:
- Effective - should not have any issues with cleanup 

Cons:
- Requires user intervention
- User may not know about script availability

#### 2. Always run the cleanup script
This would be implemented temporarily during a transitional period while most users migrate to the new codebase, after which the manual script run is still an option.

Pros:
- Effective - should not have any issues with cleanup
- Does not require user intervention
- Updating from old versions will not miss cleanup

Cons:
- Run on every run, even if not required 
- Slight increase in runtime due to cleanup and subsequent bytecode regeneration on every run

#### 3.  Use a flag
Examples of flags:
- Version number / commit last run stored in a file or the database
- Command line argument (could be added to `sys.argv` during update)

Pros:
- Limits run to a single time

Cons:
- Requires detection of update points which could be affected by future code changes
- Updating from a version prior to implementation may miss cleanup

------

I think for the short term option 2 is the most reliable.  The minor increase in runtime while the majority of users update should be acceptable.

In the long term, option 3 would probably be the best option, but would require a longer development and testing period.

Option 1 would still be available as a fallback for both Options 2 and 3, leaving an easy resolution path for those with issues in the future.

**Comment by labrys** [comment]
@clinton-hall I'd like to have your feedback on this before I implement a solution.

**Comment by clinton-hall** [comment]
Yeah, I like option 2.
The manual implentation can be done easy enough by anyone who can follow command line / terminal instructions.
But a lot of the userbase who just update automatically as the script runs wont want to be doing any manual intervention.

Option 3 sounds efficient, but that is a lot more work and I'm barely following what you are doing with the updates... ;)

I like the idea of a separate cleanup file that gets executed after update. This could be easily added to the master/dev branch (and stay there for a few weeks to get the user base ready for major refactor merge). 
This can be merged back into dev and resolve merge conflicts to that it can be merged together into dev and master later.

**Comment by nikagl** [comment]
Not sure what's happening. Two comments about current dev:

1. My nzbToMedia is executed by uTorrent. Example command line:
```
C:\>C:\Python27\python.exe "C:\Python27\nzbToMedia\TorrentToMedia.py" "D:\Downloads\xxx" "xxx" "tv" "xxx"
-- Cleaning bytecode --
fatal: Not a git repository (or any of the parent directories): .git
Error Code: 128
-- Cleaning folders: ('core', 'libs') --
fatal: Not a git repository (or any of the parent directories): .git
Error Code: 128
Traceback (most recent call last):
  File "C:\Python27\nzbToMedia\TorrentToMedia.py", line 11, in <module>
    import core
  File "C:\Python27\nzbToMedia\core\__init__.py", line 47, in <module>
    from core.auto_process import Comic, Game, Movie, Music, TV
  File "C:\Python27\nzbToMedia\core\auto_process\__init__.py", line 3, in <module>
    from core.auto_process.comics import Comic
```

2. When running nzbToMedia I get the following error now:
```
-- Cleaning folders: ('core', 'libs') --
No folders to clean

Traceback (most recent call last):
  File "C:\Python27\nzbToMedia\TorrentToMedia.py", line 11, in <module>
    import core
  File "C:\Python27\nzbToMedia\core\__init__.py", line 47, in <module>
    from core.auto_process import Comic, Game, Movie, Music, TV
  File "C:\Python27\nzbToMedia\core\auto_process\__init__.py", line 3, in <module>
    from core.auto_process.comics import Comic
ImportError: cannot import name Comic
```

Regards,

Nika.

**Comment by nikagl** [comment]
For item 1, you should CD into the home directory for nzbToMedia before running GIT.
For item 2, after moving my cfg file, removing the folders and cloning the repo again and restoring the cfg, this was solved. Some leftovers still not correctly cleaned?

**Comment by labrys** [comment]
@nikagl I assume you're running Nightly and not Dev

For Item 1, I was avoiding CDing into the the directory for simplicity as my tests with my Windows + SAB config didn't require it.  If you are having issues then I can add that code fairly simply.

As for item 2, I missed including a commit during the most recent changes.  I'll push that now.
