### ISSUE TITLE
sickchill: Double slash when web_root set to /

### ISSUE THREAD

**Issue by sinterlkaas** [clinton-hall/nzbToMedia#1444]
if you set the web_root property for sickbeard (chill) to / it will cause an issue with postprocessing... 

for example if I visit http://sickchill.domain//api/<api-key>/...
I get a 404 page not found error message. Causing the postprocess proces to fail.

Also posted this to sickchill itself but.. mayb it should be fixed on nzbToMedia
https://github.com/SickChill/SickChill/issues/5255

**Comment by clinton-hall** [comment]
I see why this is an issue, but surely just leaving webroot blank will work. This would be the same for all Sick* forks.
