### ISSUE TITLE
PP Error nzbToMedia\nzbToNzbDrone: fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by lexguy2007** [clinton-hall/nzbToMedia#1451]
I noticed the script updated today and suddenly I am getting this error during post-processing - "nzbToMedia\nzbToNzbDrone: fatal: Not a git repository (or any of the parent directories): .git". Did not do that before and worked flawlessly on both Sonarr and Radarr. Now no shows with complete processing successfully.

**Comment by labrys** [comment]
Which branch?

**Comment by lexguy2007** [comment]
Master branch

**Comment by labrys** [comment]
Odd.  Try the following:

git fetch
git reset -hard origin/master

**Comment by labrys** [comment]
Oh sorry, I forgot to ask.  Is it a git install?

**Comment by lexguy2007** [comment]
I cloned it with Git Desktop.

**Comment by labrys** [comment]
Did the above command work for you?

**Comment by lexguy2007** [comment]
Nope. Same error. It is occurring in both nzbtoRadarr and nzbtoSonarr. I cannot download anything now.

**Comment by labrys** [comment]
I have a hotfix that will resolve it until a proper fix is out.  Pushing it now.

**Comment by labrys** [comment]
Update to the latest release (11.7.1) and let me know if PP succeeds.

**Comment by lexguy2007** [comment]
Does not appear to have worked....


Tue Dec 25 2018 18:59:42	INFO	ResetDateTime: reseting datetime for file D:\TV Show Downloads\Turn.S01E02.720p.HDTV.x264-REMARKABLE\Turn.S01E02.720p.HDTV.x264-REMARKABLE.mkv
Tue Dec 25 2018 18:59:42	INFO	Post-process-script ResetDateTime.py for Turn.S01E02.720p.HDTV.x264-REMARKABLE successful
Tue Dec 25 2018 18:59:42	INFO	Executing post-process-script nzbToMedia\nzbToNzbDrone.py for Turn.S01E02.720p.HDTV.x264-REMARKABLE
Tue Dec 25 2018 18:59:44	INFO	nzbToNzbDrone: fatal: Not a git repository (or any of the parent directories): .git
Tue Dec 25 2018 18:59:44	INFO	nzbToNzbDrone: -- Cleaning bytecode --
**Tue Dec 25 2018 18:59:44	ERROR	Post-process-script nzbToMedia\nzbToNzbDrone.py for Turn.S01E02.720p.HDTV.x264-REMARKABLE failed (terminated with unknown status)**
Tue Dec 25 2018 18:59:44	INFO	Collection Turn.S01E02.720p.HDTV.x264-REMARKABLE added to history

**Comment by labrys** [comment]
It doesn't look like you updated.  Did you update manually or are you relying on the autoupdate to update?

**Comment by lexguy2007** [comment]
My apologies. You're right I didn't do it correctly. I thought about that after I posted that last message. The HotFix worked. Thank you very much!

**Comment by labrys** [comment]
No problem.. sorry for the hiccup, and thanks for all your help!
