### ISSUE TITLE
Don't complain of empty ffmpeg_path if ffmpeg/ffprobe are available in Windows PATH env

### ISSUE THREAD

**Issue by samkatakouzinos** [clinton-hall/nzbToMedia#1454]
I have Windows 10 and a PATH env that includes a directory where ffmpeg/ffprobe reside. 
Apparently using ffmpeg/ffprobe fails if I don't specify an explicit ffmpeg_path value. 
Yet I can type ffmpeg.exe in a Command Window and access it. 

Please allow ffmpeg/ffprobe use if they're accessible via Windows PATH env.
If there isn't a response THEN complain of empty ffmpeg_path value.

**Comment by clinton-hall** [comment]
Ok, so we'll need to test for execution of ffmpeg.exe, the same way as we test various linux executables...
