### ISSUE TITLE
NZBToMedia Script fails to run following most recent update

### ISSUE THREAD

**Issue by death2all110** [clinton-hall/nzbToMedia#1457]
Hello,

It appears that the most recent update broke my install. Its been working for the past 6+ months without error. I'm running the master branch on Windows 10. Following the recent upgrade (auto update), it has been failing since.

It appears the cleanup script is causing issues. manually running nzbtomedia.py gives the following error:

```
PS C:\Python27> .\python.exe C:\nzbToMedia\nzbToMedia.py
-- Cleaning bytecode --
Traceback (most recent call last):
  File "C:\nzbToMedia\nzbToMedia.py", line 627, in <module>
    cleanup.clean('core', 'libs')
  File "C:\nzbToMedia\cleanup.py", line 79, in clean
    result = clean_bytecode()
  File "C:\nzbToMedia\cleanup.py", line 50, in clean_bytecode
    '!**/__pycache__/',  # and __pycache__ folders
  File "C:\nzbToMedia\cleanup.py", line 38, in git_clean
    return subprocess.check_output(command)
  File "C:\Python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

Can someone help? Was this update tested with windows?

**Comment by labrys** [comment]
It was actually developed on Windows but with a git install.  Are you are running from source?

**Comment by labrys** [comment]
@death2all110 Hotfix pushed.  Let me know if you still have issues.

**Comment by AJohnsonCHC** [comment]
Was having the same issue, just wanted to let you know I'm not longer having problems.

**Comment by labrys** [comment]
@AJohnsonCHC thanks for the quick response.  I appreciate it.

**Comment by death2all110** [comment]
@labrys can confirm this is resolved. Thank you for the quick response!
