### ISSUE TITLE
Sickchill upgrade results in errors

### ISSUE THREAD

**Issue by SoftNotWork** [clinton-hall/nzbToMedia#1472]
18:12:57] [POSTPROCESS]::SICKBEARD: Successfully processed
Traceback (most recent call last):
  File "/home/user/nzbToMedia/TorrentToMedia.py", line 375, in <module>
    exit(main(sys.argv))
  File "/home/user/nzbToMedia/TorrentToMedia.py", line 316, in main
    result = process_torrent(input_directory, input_name, input_category, input_hash, input_id, client_agent)
  File "/home/user/nzbToMedia/TorrentToMedia.py", line 258, in process_torrent
    if result.status_code != 0:
AttributeError: 'list' object has no attribute 'status_code'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.PosixProcess object at 0x7f8d3653ba10>> ignored

**Comment by labrys** [comment]
Looks like I missed a ProcessResult refactor somewhere.  I'll try to get a fix for it tonight or first thing tomorrow.

**Comment by SoftNotWork** [comment]
Should I switch to a different branch?

**Comment by labrys** [comment]
This should be fixed now.  Let me know if you have any issues
