### ISSUE TITLE
Sub download debugging

### ISSUE THREAD

**Issue by nikagl** [clinton-hall/nzbToMedia#1484]
Hi,

How do I enable debugging for subdownload? Looking at the code, sublime does support debugging, but I hardly see any events in the logging...

Regards,

Nika.

**Comment by nikagl** [comment]
And... how to chose provider, or use passwords for providers that need it...?

**Comment by labrys** [comment]
@nikagl Could you open another issue for your second request.  As for your first, I plan on eventually reworking the logger but it likely won't be any time soon.
