### ISSUE TITLE
nzbToMedia.py is missing the Post Processing Script header for nzbget

### ISSUE THREAD

**Issue by alexholliz** [clinton-hall/nzbToMedia#1495]
This could be me just downloading the wrong branch or something, but when running a:
`git clone https://github.com/clinton-hall/nzbToMedia.git`
The nzbToMedia.py that gets pulled down doesn't have the header for NZBGet to treat it as a post processing script.

**Comment by alexholliz** [comment]
I was able to work around it for now by downloading the 11.8.1 tag.

**Comment by SerhatG** [comment]
They are on it: https://github.com/clinton-hall/nzbToMedia/pull/1455#commitcomment-31837566 !
Had the same issue.

**Comment by labrys** [comment]
Fixed in 12.0.1
