### ISSUE TITLE
ImportError: cannot import name Client

### ISSUE THREAD

**Issue by Tiwas** [clinton-hall/nzbToMedia#1503]
After the last problem was resolved I have a new one. Nothing's changed on my end (with my knowledge). No Windows update, no python update. This is running on Windows 10 Pro x64. I'm not using it for bittorrent.

```
-- Cleanup finished --

Traceback (most recent call last):
File "C:\SickRage\Scripts\nzbToMedia\nzbToSickBeard.py", line 261, in <module>
import nzbToMedia
File "C:\SickRage\Scripts\nzbToMedia\nzbToMedia.py", line 633, in <module>
import core
File "C:\SickRage\Scripts\nzbToMedia\core\__init__.py", line 48, in <module>
from core.utils import (
File "C:\SickRage\Scripts\nzbToMedia\core\utils.py", line 19, in <module>
from qbittorrent import Client as qBittorrentClient
ImportError: cannot import name Client
```

**Comment by djderan** [comment]
I don't know if this is related or not, but I had the same exact error happening for all of my scripts and I did a clean install of the scripts and the issue went away for everything other than nzbToRadarr and am now getting the following messages.

nzbToRadarr: AttributeError: 'list' object has no attribute 'status_code'
nzbToRadarr: if result.status_code == 0:
nzbToRadarr: File "C:\Program Files (x86)\NZBGet\scripts\nzbToMedia\nzbToMedia.py", line 767, in process
nzbToRadarr: failure_link=failure_link)
nzbToRadarr: File "C:\Program Files (x86)\NZBGet\scripts\nzbToMedia\nzbToMedia.py", line 856, in main
nzbToRadarr: result = nzbToMedia.main(sys.argv, section)
nzbToRadarr:   File "C:\Program Files (x86)\NZBGet\scripts\nzbToMedia\nzbToRadarr.py", line 255, in <module>
nzbToRadarr: Traceback (most recent call last):
nzbToRadarr: -- Cleanup finished --
nzbToRadarr: Returning to directory: C:\WINDOWS\system32
nzbToRadarr: No folders to clean
nzbToRadarr: -- Cleaning folders: ('core', 'libs') --
nzbToRadarr: Removing nzbToMedia.pyc
nzbToRadarr: c

**Comment by labrys** [comment]
@djderan Your issue should have been hotfixed in v12.0.2, if it is not please open a separate issue and I'll look into it immediately.

**Comment by labrys** [comment]
@Tiwas I'm running on Win 10 with no issues.  Could you please check which version you are running with by opening a command prompt and executing the following command from your nzbToMedia directory:

`python -c "import core; print(core.__version__)"`

If you are running version 12.0.2 you are up to date and your system may need a cleanup of the byte code files.  You can do that with the following command from the same directory:

`python cleanup.py`

**Comment by djderan** [comment]
Hot Fix worked for me thank you!!! The other thing I can add, is i saw this problem being described immediately after a windows update.

**Comment by Tiwas** [comment]
@labrys 
'C:\SickRage\Scripts\nzbToMedia>python -c "import core; print(core.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "core\__init__.py", line 48, in <module>
    from core.utils import (
  File "core\utils.py", line 19, in <module>
    from qbittorrent import Client as qBittorrentClient
ImportError: cannot import name Client'

I'm on the latest (from tarball). Ran cleanup.py with no errors, reran the above command and got the same error again.

**Comment by labrys** [comment]
Can you try the following from the nzbtomedia directory:
```
python -c "import libs.autoload; from qbittorrent import Client"
```

**Comment by Tiwas** [comment]
> Can you try the following from the nzbtomedia directory:
> 
> ```
> python -c "import libs.autoload; from qbittorrent import Client"
> ```

C:\SickRage\Scripts\nzbToMedia>python -c "import libs.autoload; from qbittorrent import Client"

C:\SickRage\Scripts\nzbToMedia>

(no output)

**Comment by labrys** [comment]
That means its able to `import qbittorrent` otherwise you would have seen an error.  I'll think about some other tests for you and get back with you shortly.

**Comment by labrys** [comment]
@Trotter73 Can you try the following from the nzbtomedia directory:

`python -c "import libs.autoload; from qbittorrent import Client"`

**Comment by Tiwas** [comment]
> That means its able to `import qbittorrent` otherwise you would have seen an error. I'll think about some other tests for you and get back with you shortly.

Cool! I'll be awake for another hour or two. I'll game some CS, walk the dog - and if there's anything I don't get to try for you before I go to bed I'll do it first thing tomorrow morning. I'm GMT+1, btw.

**Comment by labrys** [comment]
@Tiwas Ok.  If I miss you I'll list as many things I can think of for you to try when you get a chance.  Thanks for your patience and your bug report, it makes our jobs much easier when we get clear detailed error descriptions :)

**Comment by Tiwas** [comment]
> @Tiwas Ok. If I miss you I'll list as many things I can think of for you to try when you get a chance. Thanks for your patience and your bug report, it makes our jobs much easier when we get clear detailed error descriptions :)

Sounds good!

And the thanks goes to you. Without your effort we wouldn't have something to report on, so please pat yourself on the back for me 👍

**Comment by labrys** [comment]
@Tiwas @Trotter73 can you list the contents of the nzbToMedia libs directory?

**Comment by Tiwas** [comment]
Volume in drive C has no label.
 Volume Serial Number is 4040-9DEC

 Directory of C:\SickRage\Scripts\nzbToMedia\libs

05.01.2019  23:31    <DIR>          .
05.01.2019  23:31    <DIR>          ..
05.01.2019  06:53                71 autoload.py
05.01.2019  23:31               202 autoload.pyc
04.01.2019  04:56    <DIR>          babelfish
31.12.2018  06:07    <DIR>          backports
29.12.2018  18:22               314 backports.functools_lru_cache-1.2.1-py3.5-nspkg.pth
04.01.2019  04:56    <DIR>          beets
31.12.2018  06:07    <DIR>          beetsplug
04.01.2019  04:56    <DIR>          bs4
04.01.2019  04:56    <DIR>          chardet
31.12.2018  06:07    <DIR>          colorama
05.01.2019  23:31    <DIR>          common
04.01.2019  04:56    <DIR>          concurrent
04.01.2019  04:56    <DIR>          configobj
04.01.2019  04:55    <DIR>          custom
04.01.2019  04:56    <DIR>          dateutil
04.01.2019  04:56    <DIR>          dogpile
31.12.2018  06:07    <DIR>          enum
04.01.2019  04:56    <DIR>          enzyme
04.01.2019  04:56    <DIR>          guessit
31.12.2018  06:07    <DIR>          jaraco
29.12.2018  18:22               305 jaraco.collections-1.3.2-py3.5-nspkg.pth
29.12.2018  18:22               305 jaraco.functools-1.11-py2.7-nspkg.pth
29.12.2018  18:22               305 jaraco.text-1.7-py3.5-nspkg.pth
29.12.2018  18:22               305 jaraco.windows-3.6-py3.5-nspkg.pth
31.12.2018  06:07    <DIR>          jellyfish
31.12.2018  06:07    <DIR>          more_itertools
29.12.2018  18:22            24ÿ745 munkres.py
31.12.2018  06:07    <DIR>          musicbrainzngs
31.12.2018  06:07    <DIR>          mutagen
29.12.2018  18:22            55ÿ644 path.py
29.12.2018  18:22            85ÿ429 pkg_resources.py
05.01.2019  11:40    <DIR>          py2
04.01.2019  04:56    <DIR>          pysrt
29.12.2018  18:22            58ÿ809 rarfile.py
31.12.2018  06:07    <DIR>          rarfile1
04.01.2019  04:56    <DIR>          rebulk
04.01.2019  04:56    <DIR>          requests
05.01.2019  06:53               129 requirements-common.txt
05.01.2019  06:53                27 requirements-custom.txt
05.01.2019  06:53                67 requirements-py2.txt
05.01.2019  06:53                15 requirements-win.txt
05.01.2019  06:53               124 requirements.txt
29.12.2018  18:22            30ÿ098 six.py
04.01.2019  04:56    <DIR>          stevedore
04.01.2019  04:56    <DIR>          subliminal
29.12.2018  18:22            36ÿ713 test_path.py
31.12.2018  06:07    <DIR>          unidecode
05.01.2019  06:53             1ÿ083 util.py
05.01.2019  23:31             1ÿ384 util.pyc
05.01.2019  23:31    <DIR>          win
31.12.2018  06:07    <DIR>          xdg
04.01.2019  04:56    <DIR>          yaml
05.01.2019  06:53               863 __init__.py
05.01.2019  23:31             1ÿ442 __init__.pyc
05.01.2019  06:53               528 __main__.py
              23 File(s)        298ÿ907 bytes
              34 Dir(s)  89ÿ933ÿ463ÿ552 bytes free

**Comment by labrys** [comment]
Well there's the problem, the old libs aren't cleaned from your libs directory.  Can you try the following from the nzbToMedia folder and print the full results:

`python cleanup.py`

**Comment by labrys** [comment]
No some installations are gitless, so we can't do that.  I just need to modify the cleanup script, but to do so I need a clear idea for the reason for the failure, which I believe I have now.

**Comment by Tiwas** [comment]
> No some installations are gitless, so we can't do that. I just need to modify the cleanup script, but to do so I need a clear idea for the reason for the failure, which I believe I have now.

Ok, cool. Tell me if I should download a new version :)

**Comment by labrys** [comment]
If you want a quick fix to get you back up and running, delete the libs folder and then re-extract the tarball.  This will install the updated libs and remove all the remaining ones that were never cleaned up.  Otherwise I will be working on a patch for the cleanup script that should get you straightened out.

**Comment by Tiwas** [comment]
I'll wait then. That way I can test the new cleanup script for you :)

**Comment by labrys** [comment]
@Tiwas Thanks! Thats greatly appreciated.

**Comment by Tiwas** [comment]
@labrys  No worries. It's the least I can do :)

**Comment by labrys** [comment]
@Tiwas @Trotter73 this issue should be fixed in v12.0.3.  Please update and run the cleanup script.

**Comment by Tiwas** [comment]
Two runs. Seems to work now. Below's the log from stdout. Thanks!

C:\SickRage\Scripts\nzbToMedia>python cleanup.py

-- Cleaning bytecode --
Removing libs/common/bin/mid3cp
Removing libs/common/bin/mid3iconv
Removing libs/common/bin/mid3v2
Removing libs/common/bin/moggsplit
Removing libs/common/bin/mutagen-inspect
Removing libs/common/bin/mutagen-pony
Removing libs/common/pytz/zoneinfo/Africa/
Removing libs/common/pytz/zoneinfo/America/
Removing libs/common/pytz/zoneinfo/Antarctica/
Removing libs/common/pytz/zoneinfo/Arctic/
Removing libs/common/pytz/zoneinfo/Asia/
Removing libs/common/pytz/zoneinfo/Atlantic/
Removing libs/common/pytz/zoneinfo/Australia/
Removing libs/common/pytz/zoneinfo/Brazil/
Removing libs/common/pytz/zoneinfo/CET
Removing libs/common/pytz/zoneinfo/CST6CDT
Removing libs/common/pytz/zoneinfo/Canada/
Removing libs/common/pytz/zoneinfo/Chile/
Removing libs/common/pytz/zoneinfo/Cuba
Removing libs/common/pytz/zoneinfo/EET
Removing libs/common/pytz/zoneinfo/EST
Removing libs/common/pytz/zoneinfo/EST5EDT
Removing libs/common/pytz/zoneinfo/Egypt
Removing libs/common/pytz/zoneinfo/Eire
Removing libs/common/pytz/zoneinfo/Etc/
Removing libs/common/pytz/zoneinfo/Europe/
Removing libs/common/pytz/zoneinfo/Factory
Removing libs/common/pytz/zoneinfo/GB
Removing libs/common/pytz/zoneinfo/GB-Eire
Removing libs/common/pytz/zoneinfo/GMT
Removing libs/common/pytz/zoneinfo/GMT+0
Removing libs/common/pytz/zoneinfo/GMT-0
Removing libs/common/pytz/zoneinfo/GMT0
Removing libs/common/pytz/zoneinfo/Greenwich
Removing libs/common/pytz/zoneinfo/HST
Removing libs/common/pytz/zoneinfo/Hongkong
Removing libs/common/pytz/zoneinfo/Iceland
Removing libs/common/pytz/zoneinfo/Indian/
Removing libs/common/pytz/zoneinfo/Iran
Removing libs/common/pytz/zoneinfo/Israel
Removing libs/common/pytz/zoneinfo/Jamaica
Removing libs/common/pytz/zoneinfo/Japan
Removing libs/common/pytz/zoneinfo/Kwajalein
Removing libs/common/pytz/zoneinfo/Libya
Removing libs/common/pytz/zoneinfo/MET
Removing libs/common/pytz/zoneinfo/MST
Removing libs/common/pytz/zoneinfo/MST7MDT
Removing libs/common/pytz/zoneinfo/Mexico/
Removing libs/common/pytz/zoneinfo/NZ
Removing libs/common/pytz/zoneinfo/NZ-CHAT
Removing libs/common/pytz/zoneinfo/Navajo
Removing libs/common/pytz/zoneinfo/PRC
Removing libs/common/pytz/zoneinfo/PST8PDT
Removing libs/common/pytz/zoneinfo/Pacific/
Removing libs/common/pytz/zoneinfo/Poland
Removing libs/common/pytz/zoneinfo/Portugal
Removing libs/common/pytz/zoneinfo/ROC
Removing libs/common/pytz/zoneinfo/ROK
Removing libs/common/pytz/zoneinfo/Singapore
Removing libs/common/pytz/zoneinfo/Turkey
Removing libs/common/pytz/zoneinfo/UCT
Removing libs/common/pytz/zoneinfo/US/
Removing libs/common/pytz/zoneinfo/UTC
Removing libs/common/pytz/zoneinfo/Universal
Removing libs/common/pytz/zoneinfo/W-SU
Removing libs/common/pytz/zoneinfo/WET
Removing libs/common/pytz/zoneinfo/Zulu
Removing libs/common/pytz/zoneinfo/leapseconds
Removing libs/common/pytz/zoneinfo/posixrules
Removing libs/py2/enum/LICENSE
Removing libs/py2/enum/README

Removing libs/common/bin/mid3cp
Removing libs/common/bin/mid3iconv
Removing libs/common/bin/mid3v2
Removing libs/common/bin/moggsplit
Removing libs/common/bin/mutagen-inspect
Removing libs/common/bin/mutagen-pony
Removing libs/common/pytz/zoneinfo/Africa/
Removing libs/common/pytz/zoneinfo/America/
Removing libs/common/pytz/zoneinfo/Antarctica/
Removing libs/common/pytz/zoneinfo/Arctic/
Removing libs/common/pytz/zoneinfo/Asia/
Removing libs/common/pytz/zoneinfo/Atlantic/
Removing libs/common/pytz/zoneinfo/Australia/
Removing libs/common/pytz/zoneinfo/Brazil/
Removing libs/common/pytz/zoneinfo/CET
Removing libs/common/pytz/zoneinfo/CST6CDT
Removing libs/common/pytz/zoneinfo/Canada/
Removing libs/common/pytz/zoneinfo/Chile/
Removing libs/common/pytz/zoneinfo/Cuba
Removing libs/common/pytz/zoneinfo/EET
Removing libs/common/pytz/zoneinfo/EST
Removing libs/common/pytz/zoneinfo/EST5EDT
Removing libs/common/pytz/zoneinfo/Egypt
Removing libs/common/pytz/zoneinfo/Eire
Removing libs/common/pytz/zoneinfo/Etc/
Removing libs/common/pytz/zoneinfo/Europe/
Removing libs/common/pytz/zoneinfo/Factory
Removing libs/common/pytz/zoneinfo/GB
Removing libs/common/pytz/zoneinfo/GB-Eire
Removing libs/common/pytz/zoneinfo/GMT
Removing libs/common/pytz/zoneinfo/GMT+0
Removing libs/common/pytz/zoneinfo/GMT-0
Removing libs/common/pytz/zoneinfo/GMT0
Removing libs/common/pytz/zoneinfo/Greenwich
Removing libs/common/pytz/zoneinfo/HST
Removing libs/common/pytz/zoneinfo/Hongkong
Removing libs/common/pytz/zoneinfo/Iceland
Removing libs/common/pytz/zoneinfo/Indian/
Removing libs/common/pytz/zoneinfo/Iran
Removing libs/common/pytz/zoneinfo/Israel
Removing libs/common/pytz/zoneinfo/Jamaica
Removing libs/common/pytz/zoneinfo/Japan
Removing libs/common/pytz/zoneinfo/Kwajalein
Removing libs/common/pytz/zoneinfo/Libya
Removing libs/common/pytz/zoneinfo/MET
Removing libs/common/pytz/zoneinfo/MST
Removing libs/common/pytz/zoneinfo/MST7MDT
Removing libs/common/pytz/zoneinfo/Mexico/
Removing libs/common/pytz/zoneinfo/NZ
Removing libs/common/pytz/zoneinfo/NZ-CHAT
Removing libs/common/pytz/zoneinfo/Navajo
Removing libs/common/pytz/zoneinfo/PRC
Removing libs/common/pytz/zoneinfo/PST8PDT
Removing libs/common/pytz/zoneinfo/Pacific/
Removing libs/common/pytz/zoneinfo/Poland
Removing libs/common/pytz/zoneinfo/Portugal
Removing libs/common/pytz/zoneinfo/ROC
Removing libs/common/pytz/zoneinfo/ROK
Removing libs/common/pytz/zoneinfo/Singapore
Removing libs/common/pytz/zoneinfo/Turkey
Removing libs/common/pytz/zoneinfo/UCT
Removing libs/common/pytz/zoneinfo/US/
Removing libs/common/pytz/zoneinfo/UTC
Removing libs/common/pytz/zoneinfo/Universal
Removing libs/common/pytz/zoneinfo/W-SU
Removing libs/common/pytz/zoneinfo/WET
Removing libs/common/pytz/zoneinfo/Zulu
Removing libs/common/pytz/zoneinfo/leapseconds
Removing libs/common/pytz/zoneinfo/posixrules
Removing libs/py2/enum/LICENSE
Removing libs/py2/enum/README


Directory is not a git repository

Force cleaning folder: libs
Skipping required subfolders ['common', 'custom', 'py2', 'win']
Removing libs\babelfish
Removing libs\backports
Removing libs\beets
Removing libs\beetsplug
Removing libs\bs4
Removing libs\chardet
Removing libs\colorama
Removing libs\concurrent
Removing libs\configobj
Removing libs\dateutil
Removing libs\dogpile
Removing libs\enum
Removing libs\enzyme
Removing libs\guessit
Removing libs\jaraco
Removing libs\jellyfish
Removing libs\more_itertools
Removing libs\musicbrainzngs
Removing libs\mutagen
Removing libs\pysrt
Removing libs\rarfile1
Removing libs\rebulk
Removing libs\requests
Removing libs\stevedore
Removing libs\subliminal
Removing libs\unidecode
Removing libs\xdg
Removing libs\yaml

Force cleaning folder: core
Skipping required subfolders ['auto_process', 'extractor']
Removing core\autoProcess
Removing core\databases
Removing core\linktastic
Removing core\qbittorrent
Removing core\synchronousdeluge
Removing core\transcoder
Removing core\transmissionrpc
Removing core\utorrent

-- Cleanup finished --


C:\SickRage\Scripts\nzbToMedia>python cleanup.py

-- Cleaning bytecode --

No bytecode to clean

Directory is not a git repository

Force cleaning folder: libs
Skipping required subfolders ['common', 'custom', 'py2', 'win']

Force cleaning folder: core
Skipping required subfolders ['auto_process', 'extractor']

-- Cleanup finished --

**Comment by labrys** [comment]
Glad to hear.  Thanks for helping.

**Comment by Trotter73** [comment]
Thanks gents, perfect, really appreciated !
