### ISSUE TITLE
Error on running TorrentToMedia.py

### ISSUE THREAD

**Issue by jeffski10** [clinton-hall/nzbToMedia#1520]
Since the latest git updates I'm getting my torrent processing crashing out with this error.  

Traceback (most recent call last):
  File "/share/Downloads/nzbToMedia/TorrentToMedia.py", line 375, in <module>
    exit(main(sys.argv))
  File "/share/Downloads/nzbToMedia/TorrentToMedia.py", line 361, in main
    if results[0] != 0:
TypeError: 'ProcessResult' object does not support indexing
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.PosixProcess object at 0x22c20f0>> ignored

**Comment by clinton-hall** [comment]
Hopefully this will right itself on next run (via auto-update)
