### ISSUE TITLE
ImportError: No module named unidecode

### ISSUE THREAD

**Issue by Jivebunny** [clinton-hall/nzbToMedia#1522]
Since 12.x.x I get the following error on nzbget 20.0. I've tried the nightlies as well as the master but it fails after multiple `python cleanup.py` (it did clean up the first round) runs as well as `python(2) nzbToMedia.py`.

```
-- Cleaning bytecode --
fatal: Not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Error Code: 128

Directory is not a git repository

Force cleaning folder: libs
Skipping required subfolders ['common', 'custom', 'py2', 'win']

Force cleaning folder: core
Skipping required subfolders ['auto_process', 'extractor', 'utils']

-- Cleanup finished --

Traceback (most recent call last):
  File "nzbToMedia.py", line 633, in <module>
    import core
  File "/mnt/user/downloads/scripts/core/__init__.py", line 46, in <module>
    from core import logger, main_db, version_check, databases, transcoder
  File "/mnt/user/downloads/scripts/core/databases.py", line 4, in <module>
    from core.utils import backup_versioned_file
  File "/mnt/user/downloads/scripts/core/utils/__init__.py", line 15, in <module>
    from core.utils.files import (
  File "/mnt/user/downloads/scripts/core/utils/files.py", line 7, in <module>
    import beets.mediafile
  File "/mnt/user/downloads/scripts/libs/common/beets/__init__.py", line 20, in <module>
    from beets.util import confit
  File "/mnt/user/downloads/scripts/libs/common/beets/util/__init__.py", line 33, in <module>
    from unidecode import unidecode
```

Not sure where it goes wrong, but it's dockerized, never had any issue and reverting back to 11.8.1 makes it work again. I've checked the folder for unidecode, and tried the other suggestions I've found before: `python -c "import libs.autoload; from unidecode import unidecode"`.

This gives me: 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named unidecode
```

But it is there though. It's under /libs/common/

My method is just extract the master/nightly etc. in the scriptdir for nzbget and that has always worked out just fine so far.

I can just continue with 11.8.1 for now, but seeing this is not anywhere in the issues listed, I thought I'd post about it.

**Comment by clinton-hall** [comment]
What does `python2 -c "import libs.autoload; from unidecode import unidecode"` give you? Just wondering if your default python might be a version that is incompatible with this version on unidecode?

**Comment by labrys** [comment]
@Jivebunny Can you also make sure that `unidecode` is only in the `libs/common` folder and doesn't also appear in `libs/`

**Comment by Jivebunny** [comment]
@clinton-hall 
> What does `python2 -c "import libs.autoload; from unidecode import unidecode"` give you? Just wondering if your default python might be a version that is incompatible with this version on unidecode?

I get no error with that line while using 11.8.1. When I use 12.0.7:
```
python2 -c "import libs.autoload; from unidecode import unidecode"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named unidecode
```
My versions:

```
Python 2.7.14 (default, Sep 22 2017, 11:31:09)
Python 3.6.2 (default, Sep 10 2017, 21:16:47)
```

@labrys 
`unidecode` is only in libs/common, no where to be seen in libs/

I'm guessing it might be a thing with the python2 version and unicode version like Clinton said, but then again:
`python3 -c "import libs.autoload; from unidecode import unidecode"`
gives:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'unidecode'
```

For what it's worth, I'm running Unraid 6.6.6, nzbget 20.0 is dockerized, 11.8.1 gives no issues at all.

I'm okay with 11.8.1 and if I am the only one with this issue then maybe let it be. Thanks though.

**Comment by Jivebunny** [comment]
@labrys Thank you, so am I, but it's no worries for now is what I guess is what I'm trying to say :-)

Oh and if you want me to test stuff, let me know, I'll gladly help!

**Comment by labrys** [comment]
@Jivebunny All required dependencies should come pre-installed with nzbToMedia.  Can you CD into the `libs/common` folder and run `python -c "import beets.mediafile"`

**Comment by labrys** [comment]
@Jivebunny Can you try the following from your nzbToMedia folder:
```
cd libs
python --version
python -m pip install -r requirements-common.txt -t templibs
cd templibs
python -c "import beets.mediafile"
```

**Comment by Jivebunny** [comment]
@labrys 

```
/mnt/cache/downloads/scripts# cd libs
python --version
Python 2.7.14
/mnt/cache/downloads/scripts/libs# python -m pip install -r requirements-common.txt -t templibs
Collecting babelfish (from -r requirements-common.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/34/b7/b36c651a9136990060ab4d6c9a32de81752123105b940b2f3b958e5c6cd0/babelfish-0.5.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-K8Y8Sb/babelfish/
/mnt/cache/downloads/libs# cd templibs
-bash: cd: templibs: No such file or directory
/mnt/cache/downloads/libs# python -c "import beets.mediafile"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named beets.mediafile
```

**Comment by labrys** [comment]
Ok so you dont have setuptools installed.

Can you download and extract a copy of the [latest release](https://github.com/clinton-hall/nzbToMedia/releases/latest) to a new folder.  Then try `python -c "import libs.autoload; from unidecode import unidecode"`

**Comment by Jivebunny** [comment]
@labrys If I run this line in a 12.0.7 folder:
```
root@gen8:/mnt/cache/downloads/scripts12.x.x# python -c "import libs.autoload; from unidecode import unidecode"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named unidecode
```

If I run it after installing setuptools:
```
root@gen8:/mnt/cache/downloads/scripts12.x.x# pip install setuptools
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/37/06/754589caf971b0d2d48f151c2586f62902d93dc908e2fd9b9b9f6aa3c9dd/setuptools-40.6.3-py2.py3-none-any.whl (573kB)
    100% |████████████████████████████████| 573kB 14.9MB/s
Installing collected packages: setuptools
Successfully installed setuptools-40.6.3
root@gen8:/mnt/cache/downloads/scripts12.x.x# python -c "import libs.autoload; from unidecode import unidecode"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named unidecode
```
