### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by digitalnaiveDE** [clinton-hall/nzbToMedia#1530]
Hi guys,

i've followed a guide and now i am receiving the error: sqlite3.OperationalError: unable to open database file and unfortunately i am not sure what the reason for that is.

Any idea? I added the lines behind the error and hope the help anyhow to identify the issue

Traceback (most recent call last):
  File "/home/pi/nzbToMedia/nzbToSickBeard.py", line 261, in <module>
    import nzbToMedia
  File "/home/pi/nzbToMedia/nzbToMedia.py", line 633, in <module>
    import core
  File "/home/pi/nzbToMedia/core/__init__.py", line 46, in <module>
    from core import logger, main_db, version_check, databases, transcoder
  File "/home/pi/nzbToMedia/core/databases.py", line 4, in <module>
    from core.utils import backup_versioned_file
  File "/home/pi/nzbToMedia/core/utils/__init__.py", line 7, in <module>
    from core.utils.download_info import get_download_info, update_download_info_status
  File "/home/pi/nzbToMedia/core/utils/download_info.py", line 7, in <module>
    database = main_db.DBConnection()
  File "/home/pi/nzbToMedia/core/main_db.py", line 32, in __init__
    self.connection = sqlite3.connect(db_filename(filename), 20)
sqlite3.OperationalError: unable to open database file

**Comment by clinton-hall** [comment]
You can try deleting the database file (make a backup first if you are worried about loosing history... but this is only used for manual torrent processing).

so just delete these files and then see if the scripts run.
/home/pi/nzbToMedia/nzbtomedia.db
/home/pi/nzbToMedia/cachefile.dbm

**Comment by Mickroz** [comment]
I recently pulled a new version since autoupdate failed with the python 2.7 message, but now i get this message aswell, there is no nzbtomedia.db or cachefile.dbm file.
Im on 12.1.03

**Comment by clinton-hall** [comment]
if the nzbtomedia.db and cachefile.dbm don't exist, and the script is unable to open the file, this suggests the permissions don't allow creation of new files...

so check that the permissions on the nzbToMedia directory allow read and write permissions for the user that is calling the script.

**Comment by Mickroz** [comment]
hmm that could be it, its under my user account, but the user group hasn't got write permissions.

**Comment by Mickroz** [comment]
changing mine fixed it, havent looked at theirs yet.
