### ISSUE TITLE
directory issue

### ISSUE THREAD

**Issue by ikkeenjij36** [clinton-hall/nzbToMedia#1531]
Hi as in issue #1498 and #1503 i have had the same issue,solved it by reading the issues and folow instructions.
Now my script is working again and all went wel but after that i got this as well as report after running the script:
```
-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory

Directory is not a git repository

Force cleaning folder: libs
Skipping required subfolders ['common', 'custom', 'py2', 'win']

Force cleaning folder: core
Skipping required subfolders ['auto_process', 'extractor', 'utils']
Returning to directory:  /volume1/@appstore/sabnzbd/share/SABnzbd

-- Cleanup finished --

NzbDrone: Successfully post-processed
```
Is there anything else i can do so it's cleaned up automaticlly?

**Comment by labrys** [comment]
@ikkeenjij36 If your script is successfully executing, the warning above can be ignored.
