### ISSUE TITLE
postprocessing failure headphones

### ISSUE THREAD

**Issue by littlejeem** [clinton-hall/nzbToMedia#1536]
Question:

Hi All
I'm having some difficulty getting postprocessing to work on linux debian stretch with headphones. I've configured nzbtomedia so that sickchill and couchpotato work perfectly but for some reason headphones is just not playing ball. I can't for the life of my figure out if its my nzbtomedia config or the way I have headphones set up. In terms of logs I have the following which seem to suggest that nzbtomedia is successfully connecting to headphones and passing the folder to be processed, however headphones states that I can't find any folders to process.

nzbtomedia debug log
[https://pastebin.com/5fVXWzWu](url)

headphones debug log
[https://pastebin.com/nd506yi1](url)

autoProcessMedia.cfg - headphones section
[https://pastebin.com/Drd4dYGp](url)

The expected action I have is that transmission downloads to:
`/mnt/usbstorage/download/complete/transmission/music/`

nzbtomedia is called by transmission and processes and copies to:
`/mnt/usbstorage/download/process/music/`

headphones is called by nzbtomedia, post processes the downloads and moves to:
`/mnt/usbstorage/music/lossy/`

Can anybody help me figure out if this is my user error or an issue with nzbtomedia or headphones?

**Comment by clinton-hall** [comment]
according to the logs, HeadPhones was passed the correct path `/mnt/usbstorage/download/process/music/Faultline - Your Love Means Everything (Japanese Edition) [2004]`
but then it says no folders found... 
What user is running transmission, and what user is running HeadPhones? This can happen if the permissions are such that HeadPhones can't see the files linked by nzbToMedia (Transmission).

**Comment by littlejeem** [comment]
Hi Clinton

Thanks so much for coming back so quickly.

While trying to resolve this myself I did read that this can be the case, so I looked to make sure I'd tried to get this right (although permissions in Linux is a particular knowledge issue for me!)

Checking using ps aux gives:

[https://pastebin.com/3V8ttbdz](https://pastebin.com/3V8ttbdz)

Folders being used are owned by user:group pi:pi and have rwx permissions

pi@raspberrypi-3:/mnt/usbstorage $ ls -lsha
total 24K
4.0K drwxrwsr-x  6 pi   pi   4.0K Jan 26 00:42 .
4.0K drwxr-xr-x  3 root root 4.0K Jan 12 19:47 ..
4.0K drwxr-sr-x  6 pi   pi   4.0K Jan 25 20:42 download
4.0K drwxr-sr-x  3 pi   pi   4.0K Jan 26 02:23 movies
4.0K drwxr-sr-x  4 pi   pi   4.0K Jan 26 00:45 music
4.0K drwxr-sr-x 11 pi   pi   4.0K Jan 27 01:59 tv

**Comment by clinton-hall** [comment]
ok, a slight omission during recent improvements....
Please switch to latest nightly branch and test again. Hopefully the changes I just made will resolve this issue.

**Comment by littlejeem** [comment]
Hello Clinton

switched to nightly and gave it another go, worked perfectly

thanks a bunch for all your help and work!

Will it help you to see any logs?

**Comment by clinton-hall** [comment]
No logs needed. Thanks for reporting the issue.
