### ISSUE TITLE
nzbtoheadphones 'ProcessResult' object does not support indexing

### ISSUE THREAD

**Issue by gvb1234** [clinton-hall/nzbToMedia#1537]
I have nzbget and headphones talking together, but postprocessing always seem to fail, apparently.

From my understanding, what happens is that nzbget informs headphones that a new download has come, headphones marks the album as being downloaded, but then nzbget waits for the timeout (2 min) to hear back from headphones, then gives up.

In the log, I get the error message below.

Any idea?

Exception AttributeError: "'NoneType' object has no attribute 'path'"  in <bound method PosixProcess.__del__ of  <core.utils.processes.PosixProcess object at 0xb5448e70>>  ignored
-- | --
TypeError: 'ProcessResult' object does not support indexing
if res[0] in [0, 1]:
File  ".../core/auto_process/music.py",  line 80, in process

**Comment by labrys** [comment]
Fix should be pushed shortly.

**Comment by labrys** [comment]
@clinton-hall I read this before I saw your push. It is the same fix.

**Comment by gvb1234** [comment]
Yep, fixed in nightly! Thanks guys.
