### ISSUE TITLE
WARNING: Automatic cleanup could not be executed.

### ISSUE THREAD

**Issue by fadern** [clinton-hall/nzbToMedia#1538]
Hi,

After 2019-01-07 my installation of nzbtomedia stopped working.

hosted at a synology NAS, latest OS.

```
[18:40:15] [INFO]::MAIN: Loading config from [/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/autoProcessMedia.cfg]
Changing to directory: /volume1/@appstore/sabnzbd/var/scripts/nzbToMedia

-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory

-- Cleaning folders: ['libs', 'core'] --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory
Returning to directory:  /volume1/@appstore/sabnzbd/share/SABnzbd

-- Cleanup finished --

Traceback (most recent call last):
File "/usr/local/sabnzbd/var/scripts/nzbToMedia/nzbToCouchPotato.py", line 263, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/nzbToMedia.py", line 780, in main
core.initialize(section)
File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/core/__init__.py", line 346, in initialize
main_db.upgrade_database(main_db.DBConnection(), databases.InitialSchema)
AttributeError: 'module' object has no attribute 'InitialSchema'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f20325d8410>> ignored
```

**Comment by clinton-hall** [comment]
Thanks for reporting. On some systems we are seeing issues with the update and restructure changes.
How was nzbToMedia installed? Via git or by downlaoding the source?

Can you please attempt a manual update (git pull, or otherwise backup your autoProcessMedia.cfg, download and extract the latest release, and then restore your .cfg file)?

**Comment by fadern** [comment]
Hi,

I had to change to radarr but that shouldn't matter.
I've reinstalled the script using "git clone".
The script goes a bit further but I still get some errors and it doesn't move the file to the movie dir...

[21:29:39] [POSTPROCESS]::POSTPROCESS: Radarr response: queued
[21:29:39] [POSTPROCESS]::RADARR: Checking for status change, please stand by ...
[21:30:39] [POSTPROCESS]::RADARR: Checking for status change, please stand by ...
[21:30:39] [INFO]::MAIN: The /usr/local/sabnzbd/var/scripts/nzbToMedia/nzbToRadarr.py script completed successfully.
Changing to directory: /volume1/@appstore/sabnzbd/var/scripts/nzbToMedia

-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory

-- Cleaning folders: ['libs', 'core'] --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory
Returning to directory:  /volume1/@appstore/sabnzbd/share/SABnzbd

-- Cleanup finished --

Radarr: Successfully post-processed

**Comment by clinton-hall** [comment]
Ok, the good news is the script is now running to completion (the error in the cleanup is not an issue at all, although the message is a bit mis-leading).

As far as the movie not being renamed, now that you have moved to Radarr we might need to tweak some settings... 

Can you show the Radarr logs from 21:29? According tot he logs it appears the script asked Radarr to rename, but it doesn't appear to have done it...

To help further diagnose, can you enable debug logging (edit autoProcessMedia.cfg)
```
[General]
    log_debug = 1
```
Then run the script again and paste the full log output...
