### ISSUE TITLE
Is cleanup too aggressive?

### ISSUE THREAD

**Issue by gvb1234** [clinton-hall/nzbToMedia#1539]
Hello,

I've noticed that all pyc files get deleted at each run, but, more importantly, that (sub-)directories get removed as well.

Could this be made optional and/or more granular?

I have put the nzbToMedia folder as the root of the NZBget/scripts directory, and in that same folder, I have a Subliminal.py script (and associated folder Subliminal) that come from somewhere else. But the Subliminal folder gets deleted at each postprocess.

Well, I suppose I could rearrange the folders, but I like having all the scripts on the same level.

**Comment by labrys** [comment]
The cleanup script is intentionally agressive at this time due some major changes to the code base.  Once the code transition is over, the cleanup script will be disabled and provided as tool for use as needed.

As it is today, `nzbToMedia` is a full packaged application and not just a handful of scripts in a common folder.   Python applications don't normally expect other scripts to be installed within its folder.  For related user scripts,  `nzbToMedia` does provide a userscripts folder which does not get touched by the cleanup.

In the future, I would like `nzbToMedia` to be installable as a library or an app.  With a library install, the scripts like `nzbToSickBeard.py` could be located anywhere.

**Comment by clinton-hall** [comment]
yeah, once the transition phase is done, this can be turned off...
I personally have nzbget scripts set as
`/volume1/.@plugins/AppCentral/nzbget/nzbget/scripts`
Then inside that directory I have 
`email.py`
`logger.py`
`nzbToMedia` <- Directory
`GETScripts` <-Directory
`other_script.sh`

note that NZBGet shows all scripts (that have the NZBGet headers) from sub-directories... So really there is no need to embed different scripts within each other.

Embedding scripts into nzbToMedia could cause serious dependency issues. e.g. nzbToMedia does call Subliminal which is pre-packaged. if you embed Subliminal in the wrong location, with an incompatible version, this could break the script.

**Comment by gvb1234** [comment]
All of this makes perfect sense, thanks. Time to move files around, then ;-)
