### ISSUE TITLE
Exception AttributeError

### ISSUE THREAD

**Issue by jbravo2ru** [clinton-hall/nzbToMedia#1540]
Hi, i use nzbtoMedia on my Synology with Sabnzbd and Sickrage. Today i set up sickrage new and now the following warning appears in Sab during PP:

Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x2afb4d10>> ignored

How can i fix this?

**Comment by clinton-hall** [comment]
The above error is the generic exit point. To allow us to determine what is going wrong we need to see the full log.

**Comment by jbravo2ru** [comment]
Hi, thank you for the answer, I set up nzbtomedia new, now it works.
