### ISSUE TITLE
Attribute Error when running Script.

### ISSUE THREAD

**Issue by Peanut-Afl** [clinton-hall/nzbToMedia#1542]
For the last week or two, I have getting the following error message from SAB after I upgraded nzbtomedia to the latest version.

```
Traceback (most recent call last):
File "C:\Program Files\Scripts\nzbToMedia\nzbToSickBeard.py", line 261, in <module>
import nzbToMedia
File "C:\Program Files\Scripts\nzbToMedia\nzbToMedia.py", line 633, in <module>
import core
File "C:\Program Files\Scripts\nzbToMedia\core\__init__.py", line 46, in <module>
from core import logger, main_db, version_check, databases, transcoder
File "C:\Program Files\Scripts\nzbToMedia\core\databases.py", line 4, in <module>
from core.utils import backup_versioned_file
File "C:\Program Files\Scripts\nzbToMedia\core\utils\__init__.py", line 6, in <module>
from core.utils.common import clean_dir, flatten, get_dirs, process_dir
File "C:\Program Files\Scripts\nzbToMedia\core\utils\common.py", line 8, in <module>
from core.utils.files import list_media_files, move_file
File "C:\Program Files\Scripts\nzbToMedia\core\utils\files.py", line 13, in <module>
from core.utils.links import copy_link
File "C:\Program Files\Scripts\nzbToMedia\core\utils\links.py", line 10, in <module>
from jaraco.windows.filesystem import islink, readlink
File "C:\Program Files\Scripts\nzbToMedia\libs\win\jaraco\windows\filesystem\__init__.py", line 24, in <module>
import jaraco.windows.api.filesystem as api
File "C:\Program Files\Scripts\nzbToMedia\libs\win\jaraco\windows\api\filesystem.py", line 3, in <module>
CreateSymbolicLink = ctypes.windll.kernel32.CreateSymbolicLinkW
File "c:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
func = self.__getitem__(name)
File "c:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'CreateSymbolicLinkW' not found
```
Also, when I run the command `python -c "import core; print(core.__version__)"` from the nzbtomedia directory, I get the following error message
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "core\__init__.py", line 46, in <module>
    from core import logger, main_db, version_check, databases, transcoder
  File "core\databases.py", line 4, in <module>
    from core.utils import backup_versioned_file
  File "core\utils\__init__.py", line 6, in <module>
    from core.utils.common import clean_dir, flatten, get_dirs, process_dir
  File "core\utils\common.py", line 8, in <module>
    from core.utils.files import list_media_files, move_file
  File "core\utils\files.py", line 13, in <module>
    from core.utils.links import copy_link
  File "core\utils\links.py", line 10, in <module>
    from jaraco.windows.filesystem import islink, readlink
  File "C:\Program Files\Scripts\nzbToMedia\libs\win\jaraco\windows\filesystem\_
_init__.py", line 24, in <module>
    import jaraco.windows.api.filesystem as api
  File "C:\Program Files\Scripts\nzbToMedia\libs\win\jaraco\windows\api\filesyst
em.py", line 3, in <module>
    CreateSymbolicLink = ctypes.windll.kernel32.CreateSymbolicLinkW
  File "c:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "c:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'CreateSymbolicLinkW' not found
```
I have removed and reinstalled both Python 2.7.5 and Pywin with no success. I have also deleted the nzbtomedia folder and redownloaded it using the git clone command. I did reuse the autoprocess media.cfg file from my old installation.

I am currently running this on a windows vm.

Any thoughts on what might be causing this?

**Comment by labrys** [comment]
@Peanut-Afl First please run the following
```
cd C:\Program Files\Scripts\nzbToMedia
python --version
python -c "import libs.autoload; import jaraco.windows.filesystem"
```

**Comment by Peanut-Afl** [comment]
The results are as follows:

C:\Documents and Settings\Test>cd "\Program Files\Scripts\nzbToMedia"

C:\Program Files\Scripts\nzbToMedia>python --version
Python 2.7.5

C:\Program Files\Scripts\nzbToMedia>python -c "import libs.autoload; import jara
co.windows.filesystem"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Scripts\nzbToMedia\libs\win\jaraco\windows\filesystem\_
_init__.py", line 24, in <module>
    import jaraco.windows.api.filesystem as api
  File "C:\Program Files\Scripts\nzbToMedia\libs\win\jaraco\windows\api\filesyst
em.py", line 3, in <module>
    CreateSymbolicLink = ctypes.windll.kernel32.CreateSymbolicLinkW
  File "c:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "c:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'CreateSymbolicLinkW' not found

C:\Program Files\Scripts\nzbToMedia>

**Comment by labrys** [comment]
Can you try:
```
cd C:\Program Files\Scripts\nzbToMedia
cd libs
python -m pip install -r requirements-win.txt
python -c "import jaraco.windows.filesystem"
```

**Comment by Peanut-Afl** [comment]
Ran into an error on the third and fourth line. Results below.

C:\Documents and Settings\Test>cd "\Program Files\Scripts\nzbToMedia"

C:\Program Files\Scripts\nzbToMedia>cd libs

C:\Program Files\Scripts\nzbToMedia\libs>python -m pip install -r requirements-w
in.txt
c:\Python27\python.exe: No module named pip

C:\Program Files\Scripts\nzbToMedia\libs>python -c "import jaraco.windows.filesy
stem"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named jaraco.windows.filesystem

C:\Program Files\Scripts\nzbToMedia\libs>

**Comment by labrys** [comment]
@Peanut-Afl Can you try installing Python 2.7.15 or Python 3.5 or greater.

**Comment by labrys** [comment]
@Peanut-Afl Also please make sure you include PIP in the install and I also recommend including Py launcher.

**Comment by Peanut-Afl** [comment]
I downloaded and installed python 2.7.15 with pip (no Pylauncher in this install that I could see). I then re-ran the third line, and after it downloaded a number of files, got this at the end of it.

You are using pip version 9.0.3, however version 19.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

However, running the fourth line gave me this still:

C:\Program Files\Scripts\nzbToMedia\libs>python -c "import jaraco.windows.filesy
stem"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Python27\lib\site-packages\jaraco\windows\filesystem\__init__.py", li
ne 24, in <module>
    import jaraco.windows.api.filesystem as api
  File "c:\Python27\lib\site-packages\jaraco\windows\api\filesystem.py", line 3,
 in <module>
    CreateSymbolicLink = ctypes.windll.kernel32.CreateSymbolicLinkW
  File "c:\Python27\lib\ctypes\__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "c:\Python27\lib\ctypes\__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'CreateSymbolicLinkW' not found

**Comment by labrys** [comment]
@Peanut-Afl I think this may be related to your VM.  Could you provide more information on your VM such as Windows version, type of VM, etc.

**Comment by Peanut-Afl** [comment]
I am running Virtual Box 5.2.24 on a windows 7 pc. The vm itself is running windows XP. There is an update for Virtual Box to 5.2.26 available. I did recently upgrade virtualbox, but I cannot recall if it was around the same time as this issue appeared or not.

**Comment by labrys** [comment]
Try to pip install the previous version of `jaraco.windows`:
```
python -m pip install -I jaraco.windows==3.6
python -c "import jaraco.windows.filesystem"
```

**Comment by Peanut-Afl** [comment]
Here is the result of running the two lines you provided. Please note that I ran this from the libs directory.

C:\Program Files\Scripts\nzbToMedia\libs>python -m pip install -I jaraco.windows
==3.6
Collecting jaraco.windows==3.6
  Downloading https://files.pythonhosted.org/packages/a5/3d/9e5aeb911f3cbe90f991
520291e2bfa0c1acc9185334898e2ceee7e90c6c/jaraco.windows-3.6-py2.py3-none-any.whl
 (52kB)
    100% |################################| 61kB 682kB/s
Collecting six (from jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe
898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting path.py (from jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/ea/82/d710e0727980ac1dccd
2887f866e84c614a68c0a8d0c3aee606997e5eeeb/path.py-11.5.0-py2.py3-none-any.whl
Collecting jaraco.collections (from jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/73/22/c81ffbf17b7c2ab650f
363cd9cedb6a950b4b27a17ef806febb2cd2026d9/jaraco.collections-2.0-py2.py3-none-an
y.whl
Collecting more-itertools (from jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/2f/9d/dcfe59e213093695f10
8508af1214cf9cd95cc5489e46877ec5cb56369e5/more_itertools-5.0.0-py2-none-any.whl
Collecting jaraco.structures (from jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/86/de/4a7115ba762495533d0
0c6fd0440d28cacf4066fec64a79823c032059dfc/jaraco.structures-2.0-py2.py3-none-any
.whl
Collecting jaraco.text (from jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/74/f2/40a800c2f9bc1a53393
754acb6e897a6142fc271539e22efd429db21f3ff/jaraco.text-2.0-py2.py3-none-any.whl
Collecting jaraco.ui (from jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/d4/f8/8aee391576ae137d517
cacadd21d5cb5700068d16981668e473803692e03/jaraco.ui-2.0.1-py2.py3-none-any.whl
Collecting importlib-metadata>=0.5 (from path.py->jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/c4/e4/b5dbc3364c296e0510e
739c4e09daba535e9676ffde6c1312c2210c76bf0/importlib_metadata-0.8-py2.py3-none-an
y.whl
Collecting jaraco.classes (from jaraco.collections->jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/f9/6c/d5ad4d56ed9a6f5d2bf
843f30562e4bea2d1a694ecfabe6c56227ef31e90/jaraco.classes-2.0-py2.py3-none-any.wh
l
Collecting jaraco.functools (from jaraco.text->jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/12/a4/3e7366d0f5e75dcad7b
e88524c8cbd0f3a9fb1db243269550981740c57fe/jaraco.functools-2.0-py2.py3-none-any.
whl
Collecting configparser; python_version < "3" (from importlib-metadata>=0.5->pat
h.py->jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/e9/b1/98e5e3094aac1c0efae
b208fb45f9b42eb1d5681b4c5dac77b05d0fec71a/configparser-3.7.1-py2-none-any.whl
Collecting zipp>=0.3.2 (from importlib-metadata>=0.5->path.py->jaraco.windows==3
.6)
  Using cached https://files.pythonhosted.org/packages/00/42/10a1f8d29eaf9c7f2b5
55a5d1d602b9261f2a0cbec08f8f23d9056f5915d/zipp-0.3.3-py2.py3-none-any.whl
Collecting contextlib2; python_version < "3" (from importlib-metadata>=0.5->path
.py->jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/a2/71/8273a7eeed0aff6a854
237ab5453bc9aa67deb49df4832801c21f0ff3782/contextlib2-0.5.5-py2.py3-none-any.whl

Collecting pathlib2; python_version < "3" (from importlib-metadata>=0.5->path.py
->jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/2a/46/c696dcf1c7aad917b39
b875acdc5451975e3a9b4890dca8329983201c97a/pathlib2-2.3.3-py2.py3-none-any.whl
Collecting backports.functools-lru-cache>=1.0.3; python_version == "2.7" (from j
araco.functools->jaraco.text->jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f
539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.
py3-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2; python_version < "3"-
>importlib-metadata>=0.5->path.py->jaraco.windows==3.6)
  Using cached https://files.pythonhosted.org/packages/9e/a5/56b4dec02b16bb720ca
c9872fccd63b61a815b70633ef15bfe3ea5ce4488/scandir-1.9.0-cp27-cp27m-win32.whl
Installing collected packages: six, configparser, zipp, contextlib2, scandir, pa
thlib2, importlib-metadata, path.py, backports.functools-lru-cache, more-itertoo
ls, jaraco.functools, jaraco.text, jaraco.classes, jaraco.collections, jaraco.st
ructures, jaraco.ui, jaraco.windows
Successfully installed backports.functools-lru-cache-1.5 configparser-3.7.1 cont
extlib2-0.5.5 importlib-metadata-0.8 jaraco.classes-2.0 jaraco.collections-2.0 j
araco.functools-2.0 jaraco.structures-2.0 jaraco.text-2.0 jaraco.ui-2.0.1 jaraco
.windows-3.9.2 more-itertools-5.0.0 path.py-11.5.0 pathlib2-2.3.3 scandir-1.9.0
six-1.12.0 zipp-0.3.3
You are using pip version 9.0.3, however version 19.0.1 is available.You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Program Files\Scripts\nzbToMedia\libs>python -c "import jaraco.windows.filesy
stem"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Python27\lib\site-packages\jaraco\windows\filesystem\__init__.py", li
ne 20, in <module>
    import jaraco.windows.api.filesystem as api
  File "c:\Python27\lib\site-packages\jaraco\windows\api\filesystem.py", line 3,
 in <module>
    CreateSymbolicLink = ctypes.windll.kernel32.CreateSymbolicLinkW
  File "c:\Python27\lib\ctypes\__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "c:\Python27\lib\ctypes\__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'CreateSymbolicLinkW' not found

C:\Program Files\Scripts\nzbToMedia\libs>

**Comment by labrys** [comment]
Try one more thing for me if you would be so kind.  Try running the following in an administrative command prompt:
```
python -c "import jaraco.windows.filesystem"
```

**Comment by labrys** [comment]
So I'm fairly certain one of two things is going on here... 

1. Windows XP generally doesn't support Symbolic link
2. Creating Symbolic links generally requires administrative permissions

**Comment by Peanut-Afl** [comment]
I found the following in one of the successfull log files from earlier.

18:23:59] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" rev-list --left-right "@{upstream}"...HEAD : returned successful
[18:23:59] [DEBUG]::MAIN: cur_commit = 713e2378935ea2c9e81869879b57e76dede5a19c % (newest_commit)= 4220b152322b504bbaf150c558438dc7666bf514, num_commits_behind = 323, num_commits_ahead = 0

I do not believe I need the ability to use symbolic links.

**Comment by Peanut-Afl** [comment]
Sorry, did not see that the version numbers were truncated. The cur_commit = 713e2378935ea2c9e81869879b57e76dede5a19c
while (newest_commit)= 4220b152322b504bbaf150c558438dc7666bf514

**Comment by Peanut-Afl** [comment]
cur_commit = 713e2378935ea2c9e81869879b57e76dede5a19c

**Comment by Peanut-Afl** [comment]
The attached file has the current commit number before the issue started happening.

**Comment by Peanut-Afl** [comment]
[Current_Commit.txt](https://github.com/clinton-hall/nzbToMedia/files/2832594/Current_Commit.txt)

This file has the latest commit number before the issues appeared.

**Comment by Peanut-Afl** [comment]
I have retrograded my install to hash 713e2378935ea2c9e81869879b57e76dede5a19c using the command

git checkout 713e2378935ea2c9e81869879b57e76dede5a19c

Testing after doing this shows that it is working again without the error. The issue is that this commit is 331 behind the current one.

**Comment by labrys** [comment]
@Peanut-Afl Sorry I haven't had time to look into this... I will try to look into it during the next week.

**Comment by labrys** [comment]
On the 713e237 can you try the following:
```
cd C:\Program Files\Scripts\nzbToMedia\libs
python -c "import jaraco.windows.filesystem"
```

```

**Comment by Peanut-Afl** [comment]
I received the foolowing:
C:\Program Files\Scripts\nzbToMedia\libs>python -m pip list
DEPRECATION: The default format will switch to columns in the future. You can us
e --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.con
f under the [list] section) to disable this warning.
backports.functools-lru-cache (1.5)
configparser (3.7.1)
contextlib2 (0.5.5)
importlib-metadata (0.8)
jaraco.classes (2.0)
jaraco.collections (2.0)
jaraco.functools (2.0)
jaraco.structures (2.0)
jaraco.text (2.0)
jaraco.ui (2.0.1)
jaraco.windows (3.9.2)
more-itertools (5.0.0)
path.py (11.5.0)
pathlib2 (2.3.3)
pip (9.0.3)
pywin32 (218)
scandir (1.9.0)
setuptools (39.0.1)
six (1.12.0)
zipp (0.3.3)
You are using pip version 9.0.3, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

C:\Program Files\Scripts\nzbToMedia\libs>

C:\Program Files\Scripts\nzbToMedia\libs>python -c "import jaraco.windows.filesystem"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Python27\lib\site-packages\jaraco\windows\filesystem\__init__.py", li
ne 20, in <module>
    import jaraco.windows.api.filesystem as api
  File "c:\Python27\lib\site-packages\jaraco\windows\api\filesystem.py", line 3,
 in <module>
    CreateSymbolicLink = ctypes.windll.kernel32.CreateSymbolicLinkW
  File "c:\Python27\lib\ctypes\__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "c:\Python27\lib\ctypes\__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'CreateSymbolicLinkW' not found

C:\Program Files\Scripts\nzbToMedia\libs>

**Comment by labrys** [comment]
Can you try the following:
```
cd C:\Program Files\Scripts\nzbToMedia\libs
python -m pip uninstall jaraco-windows
python -m pip list
python -c "import jaraco.windows.filesystem"
```

**Comment by Peanut-Afl** [comment]
I had to rebuild the pc to a new OS. Not having the error anymore.
