### ISSUE TITLE
Radarr - post processing may not be working

### ISSUE THREAD

**Issue by littlejeem** [clinton-hall/nzbToMedia#1544]
Hello Folks

I'm having some issues trying to get post processing correctly with nzbtomedia and Radarr. Its not that I'm absolutely sure that its not working but nzbtomedia throws an error. I think its to do with the settings I have in autoprocess.cfg but I can't figure it out.

The behavior I'm expecting is almost for nzbtomedia to do nothing other than I guess check the file and hand back to radarr. The settings in radarr seem to work, movie is downloaded and renamed correctly so happy there.........I'd just like there to be no error!

nzbtomedia settings are here:
[https://pastebin.com/ntLMs4pV](https://pastebin.com/ntLMs4pV)

nzbtomedia log is here:
[https://pastebin.com/s6712DeP](https://pastebin.com/s6712DeP)

radarr log is here:
[https://pastebin.com/CknPTmvr](https://pastebin.com/CknPTmvr)

radarr media mangement settings:
[https://pasteboard.co/HZEByu5.png](https://pasteboard.co/HZEByu5.png)

radarr download settings are here:
[https://pasteboard.co/HZEByu5.png](https://pasteboard.co/HZEByu5.png)

radarr detailed download settings here:
[https://pasteboard.co/HZECjo8.png](https://pasteboard.co/HZECjo8.png)

Any thoughts greatly appreciated

**Comment by clinton-hall** [comment]
`2019-02-04 19:47:26 DEBUG   ::MAIN: Received Directory: /mnt/usbstorage/download/complete/transmission/movies | Name: The Equalizer 2 (2018) [BluRay] [1080p] [YTS.AM] | Category:
2019-02-04 19:47:26 DEBUG   ::MAIN: SEARCH: Could not find a category in the directory structure`
note, in the directory structure, the category appears to be `movies`
but in the .cfg you have
```
[Radarr]
    [[.movies]]
```
the issue is the `.`
so change this to
```
[Radarr]
    [[movies]]
```
and then see if this processes further.

**Comment by littlejeem** [comment]
Thanks, I will check this and re-run, I took the settings from the radarr page in the wike and assumed this was how it needed to be. Will let you know how it goes.

**Comment by littlejeem** [comment]
seems to be running fine now, i'd swear id changed this but must have got it wrong, user error. my apologies. can close this now.

**Comment by clinton-hall** [comment]
Glad you have it working. yell out if you have any further issues.

**Comment by neothematrix** [comment]
hello @clinton-hall !
sorry to revive this old ticket but I found it because I'm getting the same error and I also have my categories starting with ".", perhaps I misinterpreted what's written in the [doc wiki](https://github.com/clinton-hall/nzbToMedia/wiki/radarr)?

> raCategory = [[movies]] - This will make TorrentToMedia recognize movies as the Movie directory. - If another category is used, enter "category". - **If transmission is used, enter ."category". e.g. [[.movies]]**

**Comment by clinton-hall** [comment]
I can only assume I added that to the wiki based on user feedback. Presumably this was the case for Transmission, but now Transmission updates nolonger require this.
I'll try and update the wiki.
