### ISSUE TITLE
nzbtoheadphones error

### ISSUE THREAD

**Issue by ikkeenjij36** [clinton-hall/nzbToMedia#1549]
Hi i find a error in the pp of headphones with the script.
Running it on a synology and dont know how to fix it,hope someone can help em,i get this error:

`Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7fa4a79cba90>> ignored`

How can i solve sthis?

**Comment by labrys** [comment]
Can you post a full debug log?

**Comment by ikkeenjij36** [comment]
like this one?
`raceback (most recent call last):
File "/volume1/scripts/nzbToMedia-master/nzbToMedia.py", line 955, in <module>
exit(main(sys.argv))
File "/volume1/scripts/nzbToMedia-master/nzbToMedia.py", line 885, in main
download_id='', failure_link=''.join(args[8:]))
File "/volume1/scripts/nzbToMedia-master/nzbToMedia.py", line 752, in process
result = music.process(section_name, input_directory, input_name, status, client_agent, input_category)
File "/volume1/scripts/nzbToMedia-master/core/auto_process/music.py", line 28, in process
delete_failed = int(cfg['delete_failed'])
KeyError: 'delete_failed'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f8c3441ca10>> ignored`

**Comment by labrys** [comment]
@ikkeenjij36 Check your config and see if you have a `delete_failed` setting in the headphones section and that its properly formatted.

**Comment by ikkeenjij36** [comment]
#!/usr/bin/env python
# coding=utf-8
#
##############################################################################
### NZBGET POST-PROCESSING SCRIPT                                          ###

# Post-Process to HeadPhones.
#
# This script sends the download to your automated media management servers.
#
# NOTE: This script requires Python to be installed on your system.

##############################################################################
### OPTIONS

## General

# Auto Update nzbToMedia (0, 1).
#
# Set to 1 if you want nzbToMedia to automatically check for and update to the latest version
#auto_update=0

# Safe Mode protection of DestDir (0, 1).
#
# Enable/Disable a safety check to ensure we don't process all downloads in the default_downloadDirectory by mistake.
#safe_mode=1

# Disable additional extraction checks for failed (0, 1).
#
# Turn this on to disable additional extraction attempts for failed downloads. Default = 0 this will attempt to extract and verify if media is present.
#no_extract_failed = 0

## HeadPhones

# HeadPhones script category.
#
# category that gets called for post-processing with HeadHones.
#hpCategory=music

# HeadPhones api key.
#hpapikey=

# HeadPhones host.
#
# The ipaddress for your HeadPhones server. e.g For the Same system use localhost or 127.0.0.1
#hphost=localhost

# HeadPhones port.
#hpport=8181

# HeadPhones uses ssl (0, 1).
#
# Set to 1 if using ssl, else set to 0.
#hpssl=0

# HeadPhones web_root
#
# set this if using a reverse proxy.
#hpweb_root=

# HeadPhones Delete Failed Downloads (0, 1).
#
# set to 1 to delete failed, or 0 to leave files in place.
#hpdelete_failed=0

# HeadPhones watch directory.
#
# set this to where your HeadPhones completed downloads are.
#hpwatch_dir=

# HeadPhones wait_for
#
# Set the number of minutes to wait after initiating HeadPhones post-processing to check if the album status has changed.
#hpwait_for=2

# HeadPhones and NZBGet are a different system (0, 1).
#
# Enable to replace local path with the path as per the mountPoints below.
#hpremote_path=0

## Posix

# Niceness for external tasks Extractor and Transcoder.
#
# Set the Niceness value for the nice command. These range from -20 (most favorable to the process) to 19 (least favorable to the process).
#niceness=10

# ionice scheduling class (0, 1, 2, 3).
#
# Set the ionice scheduling class. 0 for none, 1 for real time, 2 for best-effort, 3 for idle.
#ionice_class=2

# ionice scheduling class data.
#
# Set the ionice scheduling class data. This defines the class data, if the class accepts an argument. For real time and best-effort, 0-7 is valid data.
#ionice_classdata=4

## Network

# Network Mount Points (Needed for remote path above)
#
# Enter Mount points as LocalPath,RemotePath and separate each pair with '|'
# e.g. mountPoints=/volume1/Public/,E:\|/volume2/share/,\\NAS\
#mountPoints= 

## WakeOnLan

# use WOL (0, 1).
#
# set to 1 to send WOL broadcast to the mac and test the server (e.g. xbmc) on the host and port specified.
#wolwake=0

# WOL MAC
#
# enter the mac address of the system to be woken.
#wolmac=00:01:2e:2D:64:e1

# Set the Host and Port of a server to verify system has woken.
#wolhost=192.168.1.37
#wolport=80

### NZBGET POST-PROCESSING SCRIPT                                          ###
##############################################################################

import sys

import nzbToMedia

section = 'HeadPhones'
result = nzbToMedia.main(sys.argv, section)
sys.exit(result)
``
like this?

**Comment by clinton-hall** [comment]
What downloader do you use?

In /volume1/scripts/nzbToMedia-master/autoProcessMedia.cfg you need to ensure you have the delete_failed option
```
[HeadPhones]
    [[Your Category]]
         delete_failed = 0
```
you can set this to 1if you want failed downloads to be automatically deleted.
