### ISSUE TITLE
[Q] - move from DL-folder

### ISSUE THREAD

**Issue by fadern** [clinton-hall/nzbToMedia#1550]
Hi,
Im using SabNZBD and radarr. How do I configurer so that nzbtomedia/radarr moves files from the DL folder to the Movie folder when they are renamed, like postprocessing in sickchill.

**Comment by clinton-hall** [comment]
https://github.com/clinton-hall/nzbToMedia/wiki/sabnzbd

https://github.com/clinton-hall/nzbToMedia/wiki/radarr

**Comment by fadern** [comment]
ok, thank you
