### ISSUE TITLE
rtorrent called nzbToMedia tries to access /root/ and fails to run when it can't

### ISSUE THREAD

**Issue by SoftNotWork** [clinton-hall/nzbToMedia#1552]
Changing to directory: /home/user/nzbToMedia

-- Cleaning bytecode --
Removing cleanup.pyc
Removing eol.pyc

Removing cleanup.pyc
Removing eol.pyc

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /root

-- Cleanup finished --

Traceback (most recent call last):
  File "/home/user/nzbToMedia/TorrentToMedia.py", line 8, in <module>
    cleanup.clean(cleanup.FOLDER_STRUCTURE)
  File "/home/user/nzbToMedia/cleanup.py", line 193, in clean
    print('\n-- Cleanup finished --\n')
  File "/home/user/nzbToMedia/cleanup.py", line 36, in __exit__
    os.chdir(self.original_directory)
OSError: [Errno 13] Permission denied: '/root'

--- Error ---

Why is it trying to touch /root/?

**Comment by labrys** [comment]
You are calling the script from the root directory.  The cleanup script changes directory to the nzbToMedia directory to perform the cleanup and then returns to the original directory once cleanup is complete.  It is unable to return to the original directory (/root in your case) due to a permissions issue.

**Comment by SoftNotWork** [comment]
That makes sense. The rtorrent process itself is started from systemd so I'm not sure how to change the folder it is calling from. Is there any setting where this can be changed in nzbToMedia or rtorrent itself?

The .rtorrent.rc is in /home/user/ and the rtorrent process itself is running under user rather than root. None of it runs as root.

**Comment by labrys** [comment]
@SoftNotWork Try this:
https://unix.stackexchange.com/questions/200654/executing-chdir-before-starting-systemd-service

Essentially says to add a WorkingDirectory option

**Comment by SoftNotWork** [comment]
Unfortunately, I can't verify the fix. As soon as I tried it, all HTTPS/SSL stopped working in rtorrent.

Tracker: "[Problem with the SSL CA cert (path? access rights?)]"

in every single torrent. 

Any ideas on what might be causing it? It works perfectly started other ways.

**Comment by SoftNotWork** [comment]
Would it be possible to disable the bad cleaning code instead of this fix so HTTPS/SSL can work correctly?

**Comment by clinton-hall** [comment]
@labrys 
Is there anything specific that we call in the scripts that specifically cares where we were executed from?
I get that this is the logical approach, but in this case I'm wondering if it would work to put a try/except around the `os.chdir(self.original_directory)`? So as a fall back we now attempt to execute from the nzbToMedia directory (only when we can't cd back to the original dir).

**Comment by labrys** [comment]
@clinton-hall You would know better than I if there are any concerns with working directory.  

I don't have an issue with wrapping the call in a try-except.  

If failing to return to the calling directory causes issues for people though, I would opt to remove the try-except and let the permission error propagate as it's more of a user configuration issue.  For those users a work-around would be to call the nzbToMedia script from another script first that changes the working directory (see example below).

```python
#!/usr/bin/env python
import os
import subprocess
import sys

DEFAULT_DIRECTORY = '/some/folder/with/user/permissions'
NZBTOMEDIA_SCRIPT = '/path/to/nzbToMedia/nzbToSickBeard.py`

os.chdir(DEFAULT_DIRECTORY)
subprocess.call([sys.executable, NZBTOMEDIA_SCRIPT, *sys.argv[1:]])
```
