### ISSUE TITLE
no post processing for Sonarr

### ISSUE THREAD

**Issue by hackermagnet** [clinton-hall/nzbToMedia#1556]
I use CouchPotatoServer, Sonarr and Transmission daemon on a raspberry pi. My files are stored on a NAS drive that I can access through raspberry or my computer with AFP.

In transmission daemon settings I have set:
```
"download-dir": "/mnt/Media/Downloads/torrents"
"incomplete-dir": "/mnt/Media/Downloads/torrents/incomplete"
```

I run a script after a torrent is done that pauses seeding and executes the script nzbToMedia/TorrentToMedia.py

In autoProcessMedia.cfg I have created a category for CouchPotato called [[CPS]]. Also I created a category for NzbDrone(Sonarr) called [[SNRR]]. In Torrent section I have set:
```
clientAgent = transmission
useLink = move
outputDirectory = /mnt/Media/Downloads/torrents/processing
default_downloadDirectory = /mnt/Media/Downloads/torrents
```

In both folders Downloads/torrents and Downloads/torrents/processing there are folders with names CPS and SNRR which correspond to couchpotato and sonarr categories for transmission daemon.

Everything works great with CouchPotatoServer.
When a torrent is snatched, transmission is downloading it in "incomplete-dir". After it finishes, it's moved in /mnt/Media/Downloads/torrents/CPS and then in /mnt/Media/Downloads/torrents/processing/CPS. It's renamed and then it's moved in the folder I have set in CouchPotatoServer settings.

The problem is with Sonarr. I have set transmission as my downloader in Sonarr settings and SNRR as its category. It snatches the torrent and downloads it in "incomplete-dir". Then it moves it in /mnt/Media/Downloads/torrents/SNRR and then in /mnt/Media/Downloads/torrents/processing/SNRR. Here comes the issue:

Sometimes it doesn't recognize the media file and doesn't do anything else.
Also sometimes it recognizes and copies it in the appropriate folder, not moving it and it still exists in the processing folder. I have also noticed that when I connect with AFP on my NAS and navigating in my tv shows folders, I see the copied file having the original name (not renamed), and it's getting renamed in front of my eyes while I browse the show's folder (it has been downloaded days ago).

Here are two log files, one successful movie post processing and one unsuccessful tv show post processing.

[movie](https://pastebin.com/SGFnPRxK)
[tv show](https://pastebin.com/acXZmZ55)

What could be the issue of this odd behaviour?

**Comment by clinton-hall** [comment]
What do Sonarr logs show at 2019-02-18 15:47:06 ??

The NzbToMedia logs says `POSTPROCESS::NZBDRONE: SUCCESS: The download succeeded, sending a post-process request` So it should have asked Sonarr to process.

I'm not immediately familiar with all of the config for Sonarr, but the key thing is that when set up this way you want Sonarr to "move" the file and not link/copy etc. You also want CDH (Completed Download Handling) disabled so that it doesn't try and ask Transmission where the files are and do it by itself...

Can you set debug logging in nzbToMedia 
```
[General]
    log_debug = 1
```
to see if there is more detail in the logs following another Sonarr download?

**Comment by hackermagnet** [comment]
Here is Sonarr log for 15:47:26
```
19-2-18 15:47:26.0|Warn|ImportApprovedEpisodes|Couldn't import episode /mnt/Media/Downloads/torrents/processing/SNRR/Shameless.US.S09E11.WEBRip.x264-ION10/Shameless.US.S09E11.WEBRip.x264-ION10.mp4

[v2.0.0.5301] NzbDrone.Common.Disk.NotParentException: /mnt/Media/Downloads/torrents/processing/SNRR/Shameless.US.S09E11.WEBRip.x264-ION10/Shameless.US.S09E11.WEBRip.x264-ION10.mp4 is not a child of /mnt/Media/Downloads/torrents/SNRR/
  at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath (System.String parentPath, System.String childPath) [0x00021] in <da318c059b2c4e18a12ce1003b1dc734>:0 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.GetOriginalFilePath (NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.Parser.Model.LocalEpisode localEpisode) [0x00027] in <db6accd1acca4b7b89f971b6407b53be>:0 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import (System.Collections.Generic.List`1[T] decisions, System.Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.MediaFiles.EpisodeImport.ImportMode importMode) [0x00263] in <db6accd1acca4b7b89f971b6407b53be>:0
```

I tried another download with CDH disabled although I read in the [wiki](https://github.com/clinton-hall/nzbToMedia/wiki/Sonarr) it should be enabled. Also I enabled log_debug.

Here is Sonarr log
```
19-2-19 13:16:33.9|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0
19-2-19 13:20:41.9|Info|NzbSearchService|Searching 2 indexers for [How to Get Away with Murder : S05E13]
19-2-19 13:20:43.3|Info|DownloadDecisionMaker|Processing 10 releases
19-2-19 13:20:47.8|Info|DownloadService|Report sent to Transmission. How.to.Get.Away.with.Murder.S05E13.HDTV.x264-SVA[rartv]
19-2-19 13:26:45.7|Warn|ImportApprovedEpisodes|Couldn't import episode /mnt/Media/Downloads/torrents/processing/SNRR/How.to.Get.Away.with.Murder.S05E13.HDTV.x264-SVA[rarbg]/How.to.Get.Away.with.Murder.S05E13.HDTV.x264-SVA.mkv

[v2.0.0.5301] NzbDrone.Common.Disk.NotParentException: /mnt/Media/Downloads/torrents/processing/SNRR/How.to.Get.Away.with.Murder.S05E13.HDTV.x264-SVA[rarbg]/How.to.Get.Away.with.Murder.S05E13.HDTV.x264-SVA.mkv is not a child of /mnt/Media/Downloads/torrents/SNRR/
  at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath (System.String parentPath, System.String childPath) [0x00021] in <da318c059b2c4e18a12ce1003b1dc734>:0 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.GetOriginalFilePath (NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.Parser.Model.LocalEpisode localEpisode) [0x00027] in <db6accd1acca4b7b89f971b6407b53be>:0 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import (System.Collections.Generic.List`1[T] decisions, System.Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.MediaFiles.EpisodeImport.ImportMode importMode) [0x00263] in <db6accd1acca4b7b89f971b6407b53be>:0 
```
and [nzbtomedia.log](https://pastebin.com/xT2Shxix)

**Comment by hackermagnet** [comment]
It seems to be a Sonarr issue and got fixed on the develop branch.

**Comment by clinton-hall** [comment]
Great to hear. Sorry if I confused the issue by suggesting turning off CDH. Since I run Sick* forks I can get confused about the Sonarr config.
