### ISSUE TITLE
not working now

### ISSUE THREAD

**Issue by gilly65** [clinton-hall/nzbToMedia#1562]
I have a QNAP TVS-471 with 4.3.6.0867 firmware, since I updated the firmware, nzbToMedia has stopped working, NZBGet also stopped working but I have that fixed now (installed QNZBGet)

I have it setup the same as before, more or less, it tries to process but it always errors on me, this is one I just got;

info | Fri Mar 08 2019 14:25:19 | Collection Doom.Patrol.S01E04.1080p.DCU.WEB-DL.AAC2.0.H.264-NTb added to history
-- | -- | --
error | Fri Mar 08 2019 14:25:19 | Post-process-script  nzbToMedia/nzbToSickBeard.py for  Doom.Patrol.S01E04.1080p.DCU.WEB-DL.AAC2.0.H.264-NTb failed (terminated  with unknown status)
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard:  Exception AttributeError: "'NoneType' object has no attribute 'path'"  in <bound method PosixProcess.__del__ of  <core.utils.processes.PosixProcess object at 0x7f1ea9af5a90>>  ignored
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard: AttributeError: 'module' object has no attribute 'InitialSchema'
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard:     main_db.upgrade_database(main_db.DBConnection(), databases.InitialSchema)
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard:   File "/share/CACHEDEV1_DATA/Download/nzbToMedia/core/__init__.py", line 346, in initialize
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard:     core.initialize(section)
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard:   File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py", line 780, in main
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard:     result = nzbToMedia.main(sys.argv, section)
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard:    File  "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia/nzbToSickBeard.py",  line 264, in <module>
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard: Traceback (most recent call last):
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard: -- Cleanup finished --
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard: Returning to directory:  /share
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard: REASON : Error Code: 127
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard:          If errors occur, manual cleanup may be required.
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard: -- Cleaning folders: ['libs', 'core'] --
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard: REASON : Error Code: 127
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard:          If errors occur, manual cleanup may be required.
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard: -- Cleaning bytecode --
info | Fri Mar 08 2019 14:25:19 | nzbToSickBeard: Changing to directory: /share/CACHEDEV1_DATA/Download/nzbToMedia
info | Fri Mar 08 2019 14:25:18 | nzbToSickBeard:  git: error while loading shared libraries: libcharset.so.1: cannot open  shared object file: No such file or directory
info | Fri Mar 08 2019 14:25:18 | nzbToSickBeard:  git: error while loading shared libraries: libcharset.so.1: cannot open  shared object file: No such file or directory
info | Fri Mar 08 2019 14:25:17 | Executing post-process-script nzbToMedia/nzbToSickBeard.py for Doom.Patrol.S01E04.1080p.DCU.WEB-DL.AAC2.0.H.264-NTb
info | Fri Mar 08 2019 14:25:17 | Post-process-script nzbToMedia/Pushover.py for Doom.Patrol.S01E04.1080p.DCU.WEB-DL.AAC2.0.H.264-NTb successful
info | Fri Mar 08 2019 14:25:17 | Executing post-process-script nzbToMedia/Pushover.py for Doom.Patrol.S01E04.1080p.DCU.WEB-DL.AAC2.0.H.264-NTb

Any help would be greatly appreciated.

**Comment by clinton-hall** [comment]
can you try deleting (make a backup first if you are worried)
`/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbtomedia.db`
and see if postprocessing works after this change.

otherwise it could be a changed version of python that is missing some libs...

**Comment by gilly65** [comment]
Thanks, that didn't do anything for me.

I have been avoiding updating python so it is still at 2.7.12
Anything else to check on?

Here is a log entry after I deleted nzbtomedia.db


info | Sat Mar 09 2019 09:23:08 | Collection Blue.Bloods.S09E16.iNTERNAL.720p.WEB.H264-AMRAP added to history
-- | -- | --
error | Sat Mar 09 2019 09:23:08 | Post-process-script  nzbToMedia/nzbToSickBeard.py for  Blue.Bloods.S09E16.iNTERNAL.720p.WEB.H264-AMRAP failed (terminated with  unknown status)
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard:  Exception AttributeError: "'NoneType' object has no attribute 'path'"  in <bound method PosixProcess.__del__ of  <core.utils.processes.PosixProcess object at 0x7f49b0987a10>>  ignored
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard: AttributeError: 'module' object has no attribute 'InitialSchema'
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard:     main_db.upgrade_database(main_db.DBConnection(), databases.InitialSchema)
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard:   File "/share/CACHEDEV1_DATA/Download/nzbToMedia/core/__init__.py", line 346, in initialize
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard:     core.initialize(section)
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard:   File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py", line 780, in main
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard:     result = nzbToMedia.main(sys.argv, section)
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard:    File  "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia/nzbToSickBeard.py",  line 264, in <module>
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard: Traceback (most recent call last):
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard: -- Cleanup finished --
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard: Returning to directory:  /share
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard: REASON : Error Code: 127
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard:          If errors occur, manual cleanup may be required.
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard: -- Cleaning folders: ['libs', 'core'] --
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard: REASON : Error Code: 127
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard:          If errors occur, manual cleanup may be required.
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard: -- Cleaning bytecode --
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard: Changing to directory: /share/CACHEDEV1_DATA/Download/nzbToMedia
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard:  git: error while loading shared libraries: libcharset.so.1: cannot open  shared object file: No such file or directory
info | Sat Mar 09 2019 09:23:08 | nzbToSickBeard:  git: error while loading shared libraries: libcharset.so.1: cannot open  shared object file: No such file or directory
info | Sat Mar 09 2019 09:23:08 | Executing post-process-script nzbToMedia/nzbToSickBeard.py for Blue.Bloods.S09E16.iNTERNAL.720p.WEB.H264-AMRAP
info | Sat Mar 09 2019 09:23:08 | Post-process-script nzbToMedia/Pushover.py for Blue.Bloods.S09E16.iNTERNAL.720p.WEB.H264-AMRAP successful
info | Sat Mar 09 2019 09:23:07 | Executing post-process-script nzbToMedia/Pushover.py for Blue.Bloods.S09E16.iNTERNAL.720p.WEB.H264-AMRAP
info | Sat Mar 09 2019 09:23:07 | Move for Blue.Bloods.S09E16.iNTERNAL.720p.WEB.H264-AMRAP successful
info | Sat Mar 09 2019 09:23:07 | Moving completed files for Blue.Bloods.S09E16.iNTERNAL.720p.WEB.H264-AMRAP

**Comment by clinton-hall** [comment]
ok, a Synology NAS user reported this same fault:
https://github.com/clinton-hall/nzbToMedia/issues/1538

The solution was to remove the repository completely and then re-clone.
via ssh
```
cd /share/CACHEDEV1_DATA/Download
cp nzbToMedia/autoProcessMedia.cfg .
rm -rf nzbToMedia
git clone https://github.com/clinton-hall/nzbToMedia.git
mv autoProcessMedia.cfg nzbToMedia/autoProcessMedia.cfg
```
hopefully after that the script will run
```
cd /share/CACHEDEV1_DATA/Download/nzbToMedia
./nzbToMedia.py
```

**Comment by gilly65** [comment]
Thanks, when I try that I get this;

git: error while loading shared libraries: libcharset.so.1: cannot open shared object file: No such file or directory

I tried to git it before with the same result.

**Comment by clinton-hall** [comment]
ok... so your git is not working... which git have you installed?
is there a newer qgit or similar?

you may have to change the `git` with the full path to a working git binary e.g. `/usr/local/bin/git` or `/opt/bin/git` etc.

**Comment by clinton-hall** [comment]
to find out which (broken) git you currently have use `which git`

**Comment by gilly65** [comment]
Okay, I uninstalled qgit and then re-installed it, so far everything seems to be working (no more "git: error while loading shared libraries: libcharset.so.1: cannot open shared object file: No such file or directory"), will just have to wait for something to download that gets the nzbToMedia luvin to see if that is working too.

Thanks, I will post the results as they prove themselves to be working or not.

**Comment by gilly65** [comment]
Still not working for me, after I run ./nzbToMedia.py I get;

[/share/CACHEDEV1_DATA/Download/nzbToMedia] # ./nzbToMedia.py

-- Cleaning bytecode --
Removing cleanup.pyc
Removing eol.pyc

Removing cleanup.pyc
Removing eol.pyc


-- Cleaning folders: ['libs', 'core'] --
No folders to clean


-- Cleanup finished --

[08:13:26] [INFO]::MAIN: Loading config from [/share/CACHEDEV1_DATA/Download/nzbToMedia/autoProcessMedia.cfg]
/share/CACHEDEV1_DATA/Download/nzbToMedia/eol.py:139: LifetimeWarning: Python 2.7 is no longer supported.
  warnings.warn(msg, LifetimeWarning)
[08:13:26] [INFO]::MAIN: Python v2.7 will reach end of life in 296 days.
[08:13:26] [WARNING]::MAIN: Please upgrade to a more recent Python version.
[08:13:26] [INFO]::MAIN: Checking database structure...
[08:13:26] [INFO]::MAIN: Database upgrade required: Initial Schema
[08:13:27] [INFO]::MAIN: Checking if git needs an update
[08:13:27] [INFO]::MAIN: No update needed
[08:13:27] [INFO]::MAIN: nzbToMedia Version:ef950d8024b66efb5935a6e0619b9e15b2e1036b Branch:master (Linux 4.2.8)
[08:13:27] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
[08:13:27] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[08:13:27] [INFO]::MAIN: #########################################################
[08:13:27] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[08:13:27] [INFO]::MAIN: #########################################################
[08:13:27] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[08:13:27] [INFO]::MAIN: Searching  for mediafiles to post-process ...
[08:13:27] [ERROR]::MAIN: Failed to add directories from  for post-processing: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "./nzbToMedia.py", line 958, in <module>
    exit(main(sys.argv))
  File "./nzbToMedia.py", line 901, in main
    for dir_name in get_dirs(section, subsection, link='move'):
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/core/utils/common.py", line 93, in get_dirs
    directory = os.path.join(watch_directory, subsection)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'Section' object has no attribute 'endswith'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7efe33ea6bd0>> ignored
[/share/CACHEDEV1_DATA/Download/nzbToMedia] #

and everything is still showing as PP-FAILURE in NZBGet

**Comment by clinton-hall** [comment]
When running manually, each section that is enabled needs to have the watch_dir set.

But this shows that all dependencies have loaded.
What does the log in NZBget look like?

**Comment by gilly65** [comment]
I was going to post the log this morning but I retsarted the NAS to see if that would help, that cleared the log.

I'm doing this from my phone so forgive me if the formatting is bad, I will check it tomorrow and repost if it's messed up.


INFO Mon Mar 11 2019 10:49:17 Collection Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF added to history
ERROR Mon Mar 11 2019 10:49:17 Post-process-script nzbToMedia/nzbToSickBeard.py for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF failed (terminated with unknown status)
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: ImportError: No module named xmlrpclib
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: __import__(name)
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: File "/share/CACHEDEV1_DATA/Download/nzbToMedia/libs/six.py", line 82, in _import_module
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: return _import_module(self.mod)
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: File "/share/CACHEDEV1_DATA/Download/nzbToMedia/libs/six.py", line 115, in _resolve
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: mod = mod._resolve()
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: File "/share/CACHEDEV1_DATA/Download/nzbToMedia/libs/six.py", line 203, in load_module
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: from six.moves.xmlrpc_client import SafeTransport
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: File "/share/CACHEDEV1_DATA/Download/nzbToMedia/libs/subliminal/providers/__init__.py", line 5, in <module>
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: from .providers import Provider
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: File "/share/CACHEDEV1_DATA/Download/nzbToMedia/libs/subliminal/__init__.py", line 16, in <module>
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: import subliminal
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: File "/share/CACHEDEV1_DATA/Download/nzbToMedia/core/nzbToMediaUtil.py", line 19, in <module>
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: from core.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: File "/share/CACHEDEV1_DATA/Download/nzbToMedia/core/autoProcess/autoProcessComics.py", line 7, in <module>
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: from core.autoProcess.autoProcessComics import autoProcessComics
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: File "/share/CACHEDEV1_DATA/Download/nzbToMedia/core/__init__.py", line 35, in <module>
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: import core
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py", line 520, in <module>
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: import nzbToMedia
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: File "/share/CACHEDEV1_DATA/.qpkg/QNZBGet/bin/scripts/nzbToMedia/nzbToSickBeard.py", line 257, in <module>
INFO Mon Mar 11 2019 10:49:17 nzbToSickBeard: Traceback (most recent call last):
INFO Mon Mar 11 2019 10:49:16 Executing post-process-script nzbToMedia/nzbToSickBeard.py for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:49:16 Post-process-script nzbToMedia/Pushover.py for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF successful
INFO Mon Mar 11 2019 10:49:16 Executing post-process-script nzbToMedia/Pushover.py for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:49:15 Move for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF successful
INFO Mon Mar 11 2019 10:49:15 Moving completed files for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:49:15 Cleanup for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF successful
INFO Mon Mar 11 2019 10:49:15 Deleting file 97132e0317b3858fa34eeb475dd70c14.par2
INFO Mon Mar 11 2019 10:49:15 Cleaning up Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:49:15 No renamed files found for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:49:15 Checking renamed files for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:49:14 Unpack for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF successful
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.rar
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r15
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r19
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r17
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r07
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r12
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r20
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r02
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r09
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r05
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r00
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r04
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r03
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r08
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r18
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r21
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r16
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r14
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r11
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r13
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r06
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r10
INFO Mon Mar 11 2019 10:49:14 Deleting file ohyeah.r01
INFO Mon Mar 11 2019 10:49:14 Deleting archive files
INFO Mon Mar 11 2019 10:49:14 Using directly unpacked files
INFO Mon Mar 11 2019 10:49:14 Unpacking Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:49:14 No renamed archive files found for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:49:14 Checking renamed archive files for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:49:14 No renamed files found for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:49:14 Loaded par2-file 97132e0317b3858fa34eeb475dd70c14.par2 for par-rename
INFO Mon Mar 11 2019 10:49:14 Checking renamed files for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:49:13 Direct unpack for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF successful
INFO Mon Mar 11 2019 10:49:13 Unrar: All OK
INFO Mon Mar 11 2019 10:49:13 Unrar: Extracting from ohyeah.r21
INFO Mon Mar 11 2019 10:49:13 Unrar: Extracting from ohyeah.r20
INFO Mon Mar 11 2019 10:49:13 Queueing Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF for post-processing
INFO Mon Mar 11 2019 10:49:13 Collection Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF completely downloaded
INFO Mon Mar 11 2019 10:49:13 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r20
INFO Mon Mar 11 2019 10:49:10 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r21
INFO Mon Mar 11 2019 10:49:08 Unrar: Extracting from ohyeah.r19
INFO Mon Mar 11 2019 10:49:07 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r19
INFO Mon Mar 11 2019 10:49:06 Unrar: Extracting from ohyeah.r18
INFO Mon Mar 11 2019 10:49:05 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r18
INFO Mon Mar 11 2019 10:49:05 Unrar: Extracting from ohyeah.r17
INFO Mon Mar 11 2019 10:49:05 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r17
INFO Mon Mar 11 2019 10:49:03 Unrar: Extracting from ohyeah.r16
INFO Mon Mar 11 2019 10:49:03 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r16
INFO Mon Mar 11 2019 10:49:00 Unrar: Extracting from ohyeah.r15
INFO Mon Mar 11 2019 10:48:59 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r15
INFO Mon Mar 11 2019 10:48:58 Unrar: Extracting from ohyeah.r14
INFO Mon Mar 11 2019 10:48:58 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r14
INFO Mon Mar 11 2019 10:48:57 Unrar: Extracting from ohyeah.r13
INFO Mon Mar 11 2019 10:48:56 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r13
INFO Mon Mar 11 2019 10:48:55 Unrar: Extracting from ohyeah.r12
INFO Mon Mar 11 2019 10:48:54 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r12
INFO Mon Mar 11 2019 10:48:54 Unrar: Extracting from ohyeah.r11
INFO Mon Mar 11 2019 10:48:53 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r11
INFO Mon Mar 11 2019 10:48:52 Unrar: Extracting from ohyeah.r10
INFO Mon Mar 11 2019 10:48:51 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r10
INFO Mon Mar 11 2019 10:48:51 Unrar: Extracting from ohyeah.r09
INFO Mon Mar 11 2019 10:48:51 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r09
INFO Mon Mar 11 2019 10:48:50 Unrar: Extracting from ohyeah.r08
INFO Mon Mar 11 2019 10:48:49 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r08
INFO Mon Mar 11 2019 10:48:48 Unrar: Extracting from ohyeah.r07
INFO Mon Mar 11 2019 10:48:46 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r07
INFO Mon Mar 11 2019 10:48:46 Unrar: Extracting from ohyeah.r06
INFO Mon Mar 11 2019 10:48:45 Unrar: Extracting from ohyeah.r05
INFO Mon Mar 11 2019 10:48:45 Unrar: Extracting from ohyeah.r04
INFO Mon Mar 11 2019 10:48:45 Unrar: Extracting from ohyeah.r03
INFO Mon Mar 11 2019 10:48:45 Unrar: Extracting from ohyeah.r02
INFO Mon Mar 11 2019 10:48:45 Unrar: Extracting from ohyeah.r01
INFO Mon Mar 11 2019 10:48:45 Unrar: Extracting from ohyeah.r00
INFO Mon Mar 11 2019 10:48:45 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r00
INFO Mon Mar 11 2019 10:48:44 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r06
INFO Mon Mar 11 2019 10:48:42 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r05
INFO Mon Mar 11 2019 10:48:40 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r04
INFO Mon Mar 11 2019 10:48:38 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r03
INFO Mon Mar 11 2019 10:48:37 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r02
INFO Mon Mar 11 2019 10:48:36 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.r01
INFO Mon Mar 11 2019 10:48:34 Unrar: Extracting Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF.mkv
INFO Mon Mar 11 2019 10:48:15 Unrar: Extracting from ohyeah.rar
INFO Mon Mar 11 2019 10:48:15 Unrar: UNRAR 5.50 freeware Copyright (c) 1993-2017 Alexander Roshal
INFO Mon Mar 11 2019 10:48:15 Directly unpacking Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:48:15 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/ohyeah.rar
INFO Mon Mar 11 2019 10:48:14 Reordering files for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:48:14 Successfully renamed 23 file(s) for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file e5ab1bab242b59e77fab266481e8ee01 to ohyeah.r14
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file d9bf2abea6678cbd76ea634b9b70e851 to ohyeah.r18
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file cd38a1bcd89ef97d38556fe9c7a9c562 to ohyeah.r16
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file be99d9b5e3cf2bffda8b14e481bb40fd to ohyeah.r01
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file b454c16b42395ee80775a53fda4b01e9 to ohyeah.r21
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 9c4ee42638c5b115de53034458033411 to ohyeah.r20
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 8694ca54e0fbda392ab87a973b8cfc27 to ohyeah.r07
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 78ff4144f13b9236102a76abc5052d87 to ohyeah.r15
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 6fde7f53ec11141d5f2edabdddba4e7d to ohyeah.r03
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 6faac6e923a85f7ae43721671ebe34b8 to ohyeah.r04
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 63d1fac424307a0a7ae7ceb490ae54c8 to ohyeah.r02
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 630d46c43c3ef43d7c45ad32a9a7b0fe to ohyeah.rar
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 62e40c7d29b30cd9930cd3569464ac1e to ohyeah.r09
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 61abaf1b80d1f6d74405aa6e5a21b25c to ohyeah.r17
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 5b6c47c78f4341e473c2447f8651e424 to ohyeah.r08
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 57d3b2554df015fba94eddc2b14e699e to ohyeah.r06
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 561f01ba0b31dc846c16c649c17917a5 to ohyeah.r12
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 4f8369b958ad865fbada0926d64ba723 to ohyeah.r05
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 4a880766e130b67f980de050970ce897 to ohyeah.r19
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 421bec63cf32ed584571a8404c69d848 to ohyeah.r00
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 34025f5f37d6908b85bf1b48bb9155d7 to ohyeah.r11
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 0ffe921b31b95f8cbe505ffd67cb603c to ohyeah.r13
INFO Mon Mar 11 2019 10:48:14 Renaming in-progress file 0efa45f6bcde641eec1c1cbe81d77d1b to ohyeah.r10
INFO Mon Mar 11 2019 10:48:14 Loaded par2-file 97132e0317b3858fa34eeb475dd70c14.par2 for direct-rename
INFO Mon Mar 11 2019 10:48:14 Directly checking renamed files for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:48:13 Successfully downloaded Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF/97132e0317b3858fa34eeb475dd70c14.par2
INFO Mon Mar 11 2019 10:48:12 Reordering files for Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF
INFO Mon Mar 11 2019 10:48:12 Collection Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF added to queue
INFO Mon Mar 11 2019 10:48:12 Adding collection Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF.nzb to queue
INFO Mon Mar 11 2019 10:48:11 Queue Big.Brother.Canada.S07E03.720p.HDTV.x264-aAF @ localhost
INFO Mon Mar 11 2019 10:48:11 Medusa connected to test connection.
INFO Mon Mar 11 2019 08:19:15 nzbget 20.0 daemon-mode
Showing records 1-153 from 153

**Comment by clinton-hall** [comment]
ok, this error is actually a result of a missing library in your python
`ImportError: No module named xmlrpclib`
To be honest, there are so many different python qpkgs that it became difficult to keep my qpks running.

You can try looking for a proper python package that includes xmlrpclib (this is a STANDARD Python package that should have been included)

Otherwise you can try installing the lib:
```
cd /share/CACHEDEV1_DATA/Download
wget http://effbot.org/media/downloads/xmlrpclib-1.0.1.zip
unzip xmlrpclib-1.0.1.zip
cd xmlrpclib-1.0.1
python setup.py build
python setup.py install
```

**Comment by gilly65** [comment]
Hey, sorry I've been away and busy.
I did uninstall Python and QPython and re-installed both, unfortunately I am getting the same error.

I am going to have to find some time to dig a little deeper.

**Comment by gilly65** [comment]
I think I have it working again, using the fix listed here;
https://github.com/clinton-hall/nzbToMedia/issues/1256
