### ISSUE TITLE
Add continuous integration testing

### ISSUE THREAD

**Issue by labrys** [clinton-hall/nzbToMedia#1567]
Currently there are no continuous integration tests and minimal unit testing.  This feature request is for enhancing the test suite to improve software quality.

TODO:
- [ ] Refactor code to facilitate unit testing
- [ ] Add CI clients for supported platforms (e.g. Travis and AppVeyor)
- [ ] Add unit tests
- [ ] Add integration tests with supported clients (e.g. SickBeard, Radarr, etc)

**Comment by clinton-hall** [comment]
Yes, I have looked at the continuous integration testing, and very much want it, but I haven't had a chance to look into it in any detail.

My current checks have basically involved testing the script on my system before pushing to nightly. I test to ensure the script runs to completion (no broken code that would prevent future updates).

If there is anything you need me to do/contribute to here, please let me know. I'm happy to set stuff up, I just need to know where to start/what's needed.

**Comment by clinton-hall** [comment]
#1573 
As a basis for testing that code runs...
