### ISSUE TITLE
Support for LazyLibrarian

### ISSUE THREAD

**Issue by jus7incase** [clinton-hall/nzbToMedia#157]
Wouldn't it be good to have support for LazyLibrarian?

**Comment by Theli93** [comment]
Any chance this is of any use?
ref: https://github.com/DobyTang/LazyLibrarian/issues/113

> Your script could call http://localhost/lazylibrarian/forceProcess?source=books

**Comment by denics** [comment]
This should be closed, it is a duplicated of #1223 and it is quite old. Thanks for your work!
