### ISSUE TITLE
ImportError: No module named plugins.downloaders.configuration

### ISSUE THREAD

**Issue by Tiwas** [clinton-hall/nzbToMedia#1576]
After cleaning up I get the following error:

> Traceback (most recent call last):
> File "C:\SickRage\Scripts\nzbToMedia\nzbToSickBeard.py", line 261, in <module>
> import nzbToMedia
> File "C:\SickRage\Scripts\nzbToMedia\nzbToMedia.py", line 636, in <module>
> import core
> File "C:\SickRage\Scripts\nzbToMedia\core\__init__.py", line 49, in <module>
> from core.plugins.downloaders.configuration import (
> ImportError: No module named plugins.downloaders.configuration

Thanks for your awesome work! Just getting new errors shows me you're still working on the project, so I'm really stoked - especially because you weed out problems quickly. Just tell me if you need any additional info or you want me to test something 👍

**Comment by clinton-hall** [comment]
Interesting. One of the more recent additions we have made is to introduce tests (at pull request time) that actually test that all modules can be imported correctly.

Can you check that you have the following directory/file structure?
C:\SickRage\Scripts\nzbToMedia\core\plugins\downloaders\configuration.py

As a guess I'd have to assume something hasn't cleaned up correctly and you have left-over files/directory that conflicts.

To reset the scripts you can
- Make a backup of C:\SickRage\Scripts\nzbToMedia\autoProcessMedia.cfg
- Delete C:\SickRage\Scripts\nzbToMedia
- re-git clone the script into C:\SickRage\Scripts\nzbToMedia
```
cd C:\SickRage\Scripts
git clone https://github.com/clinton-hall/nzbToMedia.git
```
- Restore your backed up config file into C:\SickRage\Scripts\nzbToMedia\autoProcessMedia.cfg

**Comment by Tiwas** [comment]
Ok. Done. Will report if it fails again :)

**Comment by NoTolerance** [comment]
Something in the script seems to be removing the plugins subfolder. I've extracted the entire source code to my scripts directory, run a job, and it fails with the above error. Even though the plugins folder is present prior to running the job, it disappears afterward.

**Comment by NoTolerance** [comment]
Found the issue.

added:

'plugins',

to:

`FOLDER_STRUCTURE = {
    'libs': [
        'common',
        'custom',
        'py2',
        'win',
    ],
    'core': [
        'auto_process',
        'extractor',
        'utils',
		'plugins',
    ],
}`

in the cleanup.py file.

**Comment by clinton-hall** [comment]
thanks for confirming this. Hopefully it is now fixed.
Please update and confirm.
