### ISSUE TITLE
Q: Where does nzbToLidarr.py extract and process iso files?

### ISSUE THREAD

**Issue by samkatakouzinos** [clinton-hall/nzbToMedia#1581]
**Describe the Question**
I would like to observe the transcoding process as it happens.

**Technical Specs**
1. Running on 'Windows 10 Pro' 
2. Python version '3.7.2'
3. Download Client NZBGet as a service logged on as Local Service
4. Intended Media Management 'Radarr'

**Expected behavior**
Just to make observation as transcoding happens, ultimately to be able to test ffmpeg command line options

**Log**
No log file.

**Comment by clinton-hall** [comment]
To be as efficient as possible, ISO files are not extracted.
Instead we use 7zip to pipe the .vob files out of the ISO and directly into ffmpeg.
ffmpef will then write the output (transcoded .mkv etc) to the Trancoder output directory.

**Comment by samkatakouzinos** [comment]
Ah ok, thanks for explaining.

**Comment by clinton-hall** [comment]
I am sorry for leading you wrong on this thread. I was responding regarding the transcoding process for iso files, but I didn't correctly identify that this pertains to Movies and TV, but not (at this time) music. 

The main reason for my error is that I do not use Radarr, Sonarr, and Lidarr, so I missed the fact that Lidarr is specifically for music, and hence your question really was specific to music transcoding!
