### ISSUE TITLE
Problems with post processing

### ISSUE THREAD

**Issue by elmero1** [clinton-hall/nzbToMedia#1585]
My setup doesn't work anymore. Last successfull download was on 8th March. 
I use the actual nzbToMedia (master branch) and nzbget as a docker conatiner (linuxserver/nzbget).

The downloads are failing in nzbget with this errors:

> Mon Mar 18 08:40:20 2019        INFO    Moving completed files for movie-file.mkv
> Mon Mar 18 08:40:20 2019        INFO    Move for movie-file.mkv successful
> Mon Mar 18 08:40:20 2019        INFO    Executing post-process-script nzb-notify/Notify.py for movie-file.mkv
> Mon Mar 18 08:40:20 2019        INFO    Notify: Traceback (most recent call last):
> Mon Mar 18 08:40:20 2019        INFO    Notify:   File "/downloads/scripts/nzb-notify/Notify.py", line 159, in <module>
> Mon Mar 18 08:40:20 2019        INFO    Notify:     from nzbget import SCRIPT_MODE
> Mon Mar 18 08:40:20 2019        INFO    Notify: ImportError: No module named nzbget
> Mon Mar 18 08:40:20 2019        ERROR   Post-process-script nzb-notify/Notify.py for movie-file.mkv failed (terminated with unknown status)
> Mon Mar 18 08:40:20 2019        INFO    Executing post-process-script nzbToMedia/nzbToSickBeard.py for movie-file.mkv
> Mon Mar 18 08:40:21 2019        INFO    nzbToSickBeard: Changing to directory: /downloads/scripts/nzbToMedia
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: /downloads/scripts/nzbToMedia/eol.py:139: LifetimeWarning: Python 2.7 is no longer supported.
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard:   warnings.warn(msg, LifetimeWarning)
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: [08:40:24] [INFO]::MAIN: Python v2.7 will reach end of life in 289 days.
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: [08:40:24] [WARNING]::MAIN: Please upgrade to a more recent Python version.
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: -- Cleaning bytecode --
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard:          If errors occur, manual cleanup may be required.
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: -- Cleaning folders: ['libs', 'core'] --
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard:          If errors occur, manual cleanup may be required.
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: Returning to directory:  /run/s6/services/nzbget
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: -- Cleanup finished --
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: Traceback (most recent call last):
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard:   File "/downloads/scripts/nzbToMedia/nzbToSickBeard.py", line 264, in <module>
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard:     result = nzbToMedia.main(sys.argv, section)
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard:   File "/downloads/scripts/nzbToMedia/nzbToMedia.py", line 789, in main
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard:     core.initialize(section)
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard:   File "/downloads/scripts/nzbToMedia/core/__init__.py", line 986, in initialize
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard:     main_db.upgrade_database(main_db.DBConnection(), databases.InitialSchema)
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: AttributeError: 'module' object has no attribute 'InitialSchema'
> Mon Mar 18 08:40:24 2019        INFO    nzbToSickBeard: Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f4baa61c390>> ignored
> Mon Mar 18 08:40:24 2019        ERROR   Post-process-script nzbToMedia/nzbToSickBeard.py for movie-file.mkv failed (terminated with unknown status)

cat logs/nzbtomedia.log
> 2019-03-18 08:40:24 INFO    ::MAIN: Python v2.7 will reach end of life in 289 days.
> 2019-03-18 08:40:24 WARNING ::MAIN: Please upgrade to a more recent Python version.

It looks like a Python problem. Do you have an idea, how i can resolve this issue. Thanks a lot.

**Comment by clinton-hall** [comment]
Ok, the issue is that this has failed to cleanup after some re-factoring.

You need to manually clean and update. so open a terminal into you docker and then:
```
cd /downloads/scripts/nzbToMedia
git pull
find . -name "*.pyc" -exec rm -f {} ;
git clean -fd
git pull
```
This should then allow the script to run again.

The python warning is just to let you know that Python2.7 has been discontinued and will no-longer be officially supported. This script is now fully python3 compatible... You can either upgrade to python 3, or waiting for the docker to be updated (I would imagine the linuxserver/nzbget docker will be updated in the future to come with python3 as standard)

**Comment by elmero1** [comment]
I have a lot of *.pyc files:
> ./libs/configobj/configobj.pyc
> ./libs/configobj/_version.pyc
> ./libs/configobj/__init__.pyc
> ./libs/dogpile/__init__.pyc
> ./libs/dogpile/cache/proxy.pyc
> ./libs/dogpile/cache/exception.pyc
> ./libs/dogpile/cache/api.pyc
> ./libs/dogpile/cache/util.pyc
> ./libs/dogpile/cache/backends/__init__.pyc
> ./libs/dogpile/cache/__init__.pyc
> ./libs/dogpile/cache/region.pyc
> ./libs/dogpile/cache/compat.pyc
> ./libs/dogpile/core/dogpile.pyc
> ./libs/dogpile/core/readwrite_lock.pyc
> ./libs/dogpile/core/legacy.pyc
> ./libs/dogpile/core/util.pyc
> ./libs/dogpile/core/__init__.pyc
> ./libs/dogpile/core/nameregistry.pyc
> ./libs/six.pyc
> ./libs/rarfile.pyc
> ./libs/requests/models.pyc
> ./libs/requests/sessions.pyc
> ./libs/requests/status_codes.pyc
> ./libs/requests/adapters.pyc
> ./libs/requests/utils.pyc
> ./libs/requests/api.pyc
> ./libs/requests/cookies.pyc
> ./libs/requests/__init__.pyc
> ./libs/requests/auth.pyc
> ./libs/requests/certs.pyc
> ./libs/requests/structures.pyc
> ./libs/requests/hooks.pyc
> ./libs/requests/packages/urllib3/connection.pyc
> ./libs/requests/packages/urllib3/fields.pyc
> ./libs/requests/packages/urllib3/request.pyc
> ./libs/requests/packages/urllib3/contrib/__init__.pyc
> ./libs/requests/packages/urllib3/contrib/pyopenssl.pyc
> ./libs/requests/packages/urllib3/__init__.pyc
> ./libs/requests/packages/urllib3/util/connection.pyc
> ./libs/requests/packages/urllib3/util/request.pyc
> ./libs/requests/packages/urllib3/util/__init__.pyc
> ./libs/requests/packages/urllib3/util/timeout.pyc
> ./libs/requests/packages/urllib3/util/url.pyc
> ./libs/requests/packages/urllib3/util/ssl_.pyc
> ./libs/requests/packages/urllib3/util/response.pyc
> ./libs/requests/packages/urllib3/util/retry.pyc
> ./libs/requests/packages/urllib3/connectionpool.pyc
> ./libs/requests/packages/urllib3/filepost.pyc
> ./libs/requests/packages/urllib3/_collections.pyc
> ./libs/requests/packages/urllib3/response.pyc
> ./libs/requests/packages/urllib3/poolmanager.pyc
> ./libs/requests/packages/urllib3/packages/ordered_dict.pyc
> ./libs/requests/packages/urllib3/packages/six.pyc
> ./libs/requests/packages/urllib3/packages/__init__.pyc
> ./libs/requests/packages/urllib3/packages/ssl_match_hostname/__init__.pyc
> ./libs/requests/packages/urllib3/exceptions.pyc
> ./libs/requests/packages/__init__.pyc
> ./libs/requests/packages/chardet/__init__.pyc
> ./libs/requests/compat.pyc
> ./libs/requests/exceptions.pyc
> ./libs/rebulk/rules.pyc
> ./libs/rebulk/formatters.pyc
> ./libs/rebulk/utils.pyc
> ./libs/rebulk/processors.pyc
> ./libs/rebulk/rebulk.pyc
> ./libs/rebulk/loose.pyc
> ./libs/rebulk/__init__.pyc
> ./libs/rebulk/debug.pyc
> ./libs/rebulk/match.pyc
> ./libs/rebulk/remodule.pyc
> ./libs/rebulk/chain.pyc
> ./libs/rebulk/validators.pyc
> ./libs/rebulk/toposort.pyc
> ./libs/rebulk/introspector.pyc
> ./libs/rebulk/pattern.pyc
> ./libs/yaml/dumper.pyc
> ./libs/yaml/emitter.pyc
> ./libs/yaml/nodes.pyc
> ./libs/yaml/cyaml.pyc
> ./libs/yaml/loader.pyc
> ./libs/yaml/composer.pyc
> ./libs/yaml/resolver.pyc
> ./libs/yaml/__init__.pyc
> ./libs/yaml/reader.pyc
> ./libs/yaml/parser.pyc
> ./libs/yaml/representer.pyc
> ./libs/yaml/tokens.pyc
> ./libs/yaml/scanner.pyc
> ./libs/yaml/constructor.pyc
> ./libs/yaml/serializer.pyc
> ./libs/yaml/error.pyc
> ./libs/yaml/events.pyc
> ./libs/enzyme/parsers/ebml/core.pyc
> ./libs/enzyme/parsers/ebml/readers.pyc
> ./libs/enzyme/parsers/ebml/__init__.pyc
> ./libs/enzyme/parsers/__init__.pyc
> ./libs/enzyme/__init__.pyc
> ./libs/enzyme/mkv.pyc
> ./libs/enzyme/compat.pyc
> ./libs/enzyme/exceptions.pyc
> ./libs/guessit/rules/properties/crc.pyc
> ./libs/guessit/rules/properties/cds.pyc
> ./libs/guessit/rules/properties/type.pyc
> ./libs/guessit/rules/properties/film.pyc
> ./libs/guessit/rules/properties/date.pyc
> ./libs/guessit/rules/properties/audio_codec.pyc
> ./libs/guessit/rules/properties/release_group.pyc
> ./libs/guessit/rules/properties/episode_title.pyc
> ./libs/guessit/rules/properties/other.pyc
> ./libs/guessit/rules/properties/country.pyc
> ./libs/guessit/rules/properties/__init__.pyc
> ./libs/guessit/rules/properties/format.pyc
> ./libs/guessit/rules/properties/edition.pyc
> ./libs/guessit/rules/properties/container.pyc
> ./libs/guessit/rules/properties/part.pyc
> ./libs/guessit/rules/properties/screen_size.pyc
> ./libs/guessit/rules/properties/mimetype.pyc
> ./libs/guessit/rules/properties/bonus.pyc
> ./libs/guessit/rules/properties/title.pyc
> ./libs/guessit/rules/properties/video_codec.pyc
> ./libs/guessit/rules/properties/episodes.pyc
> ./libs/guessit/rules/properties/website.pyc
> ./libs/guessit/rules/properties/language.pyc
> ./libs/guessit/rules/processors.pyc
> ./libs/guessit/rules/markers/path.pyc
> ./libs/guessit/rules/markers/__init__.pyc
> ./libs/guessit/rules/markers/groups.pyc
> ./libs/guessit/rules/__init__.pyc
> ./libs/guessit/rules/common/words.pyc
> ./libs/guessit/rules/common/formatters.pyc
> ./libs/guessit/rules/common/date.pyc
> ./libs/guessit/rules/common/__init__.pyc
> ./libs/guessit/rules/common/comparators.pyc
> ./libs/guessit/rules/common/validators.pyc
> ./libs/guessit/rules/common/numeral.pyc
> ./libs/guessit/__version__.pyc
> ./libs/guessit/options.pyc
> ./libs/guessit/api.pyc
> ./libs/guessit/__init__.pyc
> ./libs/guessit/reutils.pyc
> ./libs/dateutil/tzwin.pyc
> ./libs/dateutil/tz.pyc
> ./libs/dateutil/relativedelta.pyc
> ./libs/dateutil/__init__.pyc
> ./libs/dateutil/parser.pyc
> ./libs/autoload.pyc
> ./libs/util.pyc
> ./libs/__init__.pyc
> ./libs/stevedore/extension.pyc
> ./libs/stevedore/driver.pyc
> ./libs/stevedore/named.pyc
> ./libs/stevedore/__init__.pyc
> ./libs/stevedore/hook.pyc
> ./libs/stevedore/enabled.pyc
> ./libs/bs4/builder/__init__.pyc
> ./libs/bs4/builder/_html5lib.pyc
> ./libs/bs4/builder/_htmlparser.pyc
> ./libs/bs4/builder/_lxml.pyc
> ./libs/bs4/__init__.pyc
> ./libs/bs4/element.pyc
> ./libs/bs4/dammit.pyc
> ./libs/concurrent/futures/_base.pyc
> ./libs/concurrent/futures/__init__.pyc
> ./libs/concurrent/futures/thread.pyc
> ./libs/concurrent/futures/process.pyc
> ./libs/concurrent/__init__.pyc
> ./libs/chardet/__init__.pyc
> ./libs/beets/__init__.pyc
> ./libs/beets/util/confit.pyc
> ./libs/beets/util/hidden.pyc
> ./libs/beets/util/__init__.pyc
> ./libs/pysrt/srtfile.pyc
> ./libs/pysrt/comparablemixin.pyc
> ./libs/pysrt/srtexc.pyc
> ./libs/pysrt/srttime.pyc
> ./libs/pysrt/version.pyc
> ./libs/pysrt/__init__.pyc
> ./libs/pysrt/srtitem.pyc
> ./libs/pysrt/compat.pyc
> ./libs/subliminal/converters/__init__.pyc
> ./libs/subliminal/converters/thesubdb.pyc
> ./libs/subliminal/cache.pyc
> ./libs/subliminal/core.pyc
> ./libs/subliminal/utils.pyc
> ./libs/subliminal/video.pyc
> ./libs/subliminal/__init__.pyc
> ./libs/subliminal/extensions.pyc
> ./libs/subliminal/providers/subscenter.pyc
> ./libs/subliminal/providers/shooter.pyc
> ./libs/subliminal/providers/podnapisi.pyc
> ./libs/subliminal/providers/tvsubtitles.pyc
> ./libs/subliminal/providers/legendastv.pyc
> ./libs/subliminal/providers/__init__.pyc
> ./libs/subliminal/providers/addic7ed.pyc
> ./libs/subliminal/providers/thesubdb.pyc
> ./libs/subliminal/providers/opensubtitles.pyc
> ./libs/subliminal/score.pyc
> ./libs/subliminal/subtitle.pyc
> ./libs/subliminal/refiners/tvdb.pyc
> ./libs/subliminal/refiners/__init__.pyc
> ./libs/subliminal/refiners/omdb.pyc
> ./libs/subliminal/refiners/metadata.pyc
> ./libs/subliminal/exceptions.pyc
> ./libs/pkg_resources.pyc
> ./libs/babelfish/converters/alpha2.pyc
> ./libs/babelfish/converters/__init__.pyc
> ./libs/babelfish/converters/alpha3b.pyc
> ./libs/babelfish/converters/opensubtitles.pyc
> ./libs/babelfish/country.pyc
> ./libs/babelfish/__init__.pyc
> ./libs/babelfish/script.pyc
> ./libs/babelfish/language.pyc
> ./libs/babelfish/exceptions.pyc
> ./eol.pyc
> ./nzbToMedia.pyc
> ./core/forks.pyc
> ./core/autoProcess/autoProcessMovie.pyc
> ./core/autoProcess/autoProcessTV.pyc
> ./core/autoProcess/autoProcessComics.pyc
> ./core/autoProcess/autoProcessMusic.pyc
> ./core/autoProcess/autoProcessGames.pyc
> ./core/autoProcess/__init__.pyc
> ./core/utorrent/__init__.pyc
> ./core/utorrent/upload.pyc
> ./core/utorrent/client.pyc
> ./core/github_api.pyc
> ./core/databases/mainDB.pyc
> ./core/databases/__init__.pyc
> ./core/user_scripts.pyc
> ./core/linktastic/linktastic.pyc
> ./core/linktastic/__init__.pyc
> ./core/configuration.pyc
> ./core/synchronousdeluge/protocol.pyc
> ./core/synchronousdeluge/transfer.pyc
> ./core/synchronousdeluge/__init__.pyc
> ./core/synchronousdeluge/client.pyc
> ./core/synchronousdeluge/rencode.pyc
> ./core/synchronousdeluge/exceptions.pyc
> ./core/transmissionrpc/six.pyc
> ./core/transmissionrpc/constants.pyc
> ./core/transmissionrpc/utils.pyc
> ./core/transmissionrpc/__init__.pyc
> ./core/transmissionrpc/session.pyc
> ./core/transmissionrpc/client.pyc
> ./core/transmissionrpc/error.pyc
> ./core/transmissionrpc/httphandler.pyc
> ./core/transmissionrpc/torrent.pyc
> ./core/nzbToMediaConfig.pyc
> ./core/nzbToMediaDB.pyc
> ./core/scene_exceptions.pyc
> ./core/__init__.pyc
> ./core/logger.pyc
> ./core/transcoder/transcoder.pyc
> ./core/transcoder/__init__.pyc
> ./core/nzbToMediaUserScript.pyc
> ./core/extractor/extractor.pyc
> ./core/extractor/__init__.pyc
> ./core/nzbToMediaUtil.pyc
> ./core/gh_api.pyc
> ./core/versionCheck.pyc
> ./core/nzbToMediaAutoFork.pyc
> ./core/version_check.pyc
> ./core/main_db.pyc
> ./core/nzbToMediaSceneExceptions.pyc
> ./cleanup.pyc

Should I delete all of them?

**Comment by clinton-hall** [comment]
Yes. When the script runs, every .py file that is loaded creates a .pyc (compiled) file.
It is these files that prevents the un-used directories from being deleted when the directory structure changes.

**Comment by elmero1** [comment]
Great. It looks much better. The download is successful, but in nzbget the download is failed (PP-Failure). Here the logs:
> Mon Mar 18 2019 22:54:15	INFO	Executing post-process-script nzb-notify/Notify.py for movie-file.mkv
> Mon Mar 18 2019 22:54:15	INFO	Notify: Traceback (most recent call last):
> Mon Mar 18 2019 22:54:15	INFO	Notify:   File "/downloads/scripts/nzb-notify/Notify.py", line 159, in <module>
> Mon Mar 18 2019 22:54:15	INFO	Notify:     from nzbget import SCRIPT_MODE
> Mon Mar 18 2019 22:54:15	INFO	Notify: ImportError: No module named nzbget
> Mon Mar 18 2019 22:54:15	ERROR	Post-process-script nzb-notify/Notify.py for movie-file.mkv failed (terminated with unknown status)
> Mon Mar 18 2019 22:54:15	INFO	Executing post-process-script nzbToMedia/nzbToSickBeard.py for movie-file.mkv
> Mon Mar 18 2019 22:54:15	INFO	nzbToSickBeard: Changing to directory: /downloads/scripts/nzbToMedia
> Mon Mar 18 2019 22:54:19	INFO	nzbToSickBeard: /downloads/scripts/nzbToMedia/eol.py:139: LifetimeWarning: Python 2.7 is no longer supported.
> Mon Mar 18 2019 22:54:19	INFO	nzbToSickBeard:   warnings.warn(msg, LifetimeWarning)
> Mon Mar 18 2019 22:54:19	INFO	nzbToSickBeard: [21:54:19] [INFO]::MAIN: Python v2.7 will reach end of life in 289 days.
> Mon Mar 18 2019 22:54:19	INFO	nzbToSickBeard: [21:54:19] [WARNING]::MAIN: Please upgrade to a more recent Python version.
> Mon Mar 18 2019 22:54:19	INFO	nzbToSickBeard: [21:54:19] [INFO]::MAIN: Checking database structure...
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [INFO]::MAIN: Checking if git needs an update
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [INFO]::MAIN: No update needed
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [INFO]::MAIN: nzbToMedia Version:12.0.10 Branch:master (Linux 4.9.0-0.bpo.6-amd64)
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [WARNING]::MAIN: Failed to locate par2. Repair and rename using par files will not be possible!
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [WARNING]::MAIN: Failed to locate ffmpeg. Transcoding disabled!
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [INFO]::MAIN: #########################################################
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [INFO]::MAIN: #########################################################
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [INFO]::MAIN: Script triggered from NZBGet Version 20.0.
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [INFO]::MAIN: Auto-detected SECTION:SickBeard
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [INFO]::MAIN: Calling SickBeard:tvshows to post-process:movie-file.mkv
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [INFO]::MAIN: Attempting to auto-detect tvshows fork
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [INFO]::MAIN: SickBeard:tvshows fork auto-detection found custom params {'force': None, 'is_priority': None, 'failed': None, 'process_method': None, 'proc_dir': None, 'delete_on': None}
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [INFO]::MAIN: SickBeard:tvshows fork set to custom
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [INFO]::MAIN: FLATTEN: Flattening directory: /downloads/completed/tvshows/movie-file.mkv/movie-file.mkv
> Mon Mar 18 2019 22:54:20	INFO	nzbToSickBeard: [21:54:20] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Processing folder /downloads/completed/tvshows/movie-file.mkv/movie-file.mkv
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: PostProcessing Path: /downloads/completed/tvshows/movie-file.mkv
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: PostProcessing Dirs: [u'movie-file.mkv']
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: PostProcessing Files: []
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: PostProcessing VideoFiles: []
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: PostProcessing RarContent: []
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: PostProcessing VideoInRar: []
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Processing folder movie-file.mkv
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Processing folder /downloads/completed/tvshows/movie-file.mkv/movie-file.mkv/Sample
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Found unwanted files: ['movie-file.mkv-sample.mkv']
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Deleting file: movie-file.mkv-sample.mkv
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Deleted folder: /downloads/completed/tvshows/movie-file.mkv/movie-file.mkv/Sample
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Processing folder /downloads/completed/tvshows/movie-file.mkv/movie-file.mkv
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Found unwanted files: ['movie-file.mkv.nfo']
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Processing /downloads/completed/tvshows/movie-file.mkv/movie-file.mkv/movie-file.mkv.mkv (movie-file.mkv)
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Retrieving episode object for 2x1
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Snatch history had a quality in it, using that: 1080p WEB-DL
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: SR snatched this episode and it is not processed before
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Is ep a priority download: True
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: There is no existing file so there's no worries about replacing it
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: This download is marked a priority download so I'm going to replace an existing file if I find one
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Found release name movie-file.mkv
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Destination folder for this episode: /tvshows/American.Gods/Season.02
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Moving file from /downloads/completed/tvshows/movie-file.mkv/movie-file.mkv/movie-file.mkv.mkv to /tvshows/American.Gods/Season.02/movie-file.mkv.mkv
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Processing succeeded for /downloads/completed/tvshows/movie-file.mkv/movie-file.mkv/movie-file.mkv.mkv
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Deleting file: movie-file.mkv.nfo
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Deleted folder: /downloads/completed/tvshows/movie-file.mkv/movie-file.mkv
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [POSTPROCESS]::SICKBEARD: Successfully processed
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [INFO]::CLEANDIRS: Directory /downloads/completed/tvshows/movie-file.mkv has been processed, removing ...
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: [21:54:37] [INFO]::MAIN: The /downloads/scripts/nzbToMedia/nzbToSickBeard.py script completed successfully.
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: -- Cleaning bytecode --
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard:          If errors occur, manual cleanup may be required.
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: -- Cleaning folders: ['libs', 'core'] --
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard:          If errors occur, manual cleanup may be required.
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: Returning to directory:  /run/s6/services/nzbget
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: -- Cleanup finished --
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: SickBeard: Successfully post-processed movie-file.mkv.mkv!
> Mon Mar 18 2019 22:54:37	INFO	Post-process-script nzbToMedia/nzbToSickBeard.py for movie-file.mkv successful
> Mon Mar 18 2019 22:54:37	INFO	Collection movie-file.mkv added to history

**Comment by clinton-hall** [comment]
Status PP failure is because your other script is failing
```
Mon Mar 18 2019 22:54:15	INFO	Executing post-process-script nzb-notify/Notify.py for movie-file
Mon Mar 18 2019 22:54:15	INFO	Notify: Traceback (most recent call last):
Mon Mar 18 2019 22:54:15	INFO	Notify: File "/downloads/scripts/nzb-notify/Notify.py", line 159, in 
Mon Mar 18 2019 22:54:15	INFO	Notify: from nzbget import SCRIPT_MODE
Mon Mar 18 2019 22:54:15	INFO	Notify: ImportError: No module named nzbget
Mon Mar 18 2019 22:54:15	ERROR	Post-process-script nzb-notify/Notify.py for movie-file failed (terminated with unknown status)
```
So you will either need to disable that script for the appropriate categories, or otherwise fix the issues with that script... as per this https://github.com/caronc/nzb-notify/blob/master/Notify.py#L158-L168
I would assume you need to run the following 2 commands inside your docker for that script to work
```
pip install nzbge
pip install apprise
```

**Comment by elmero1** [comment]
Hi clinton-hall

Thanks a lot for your great support! 
I will check the nzb-notify plugin.

The nzbToSickBeard error messages (Error: [Errno 2]) are correct?
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: -- Cleaning bytecode --
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: If errors occur, manual cleanup may be required.
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: -- Cleaning folders: ['libs', 'core'] --
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: If errors occur, manual cleanup may be required.
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: Returning to directory: /run/s6/services/nzbget
> Mon Mar 18 2019 22:54:37	INFO	nzbToSickBeard: -- Cleanup finished --

**Comment by clinton-hall** [comment]
That is the failure to clean folder structure that you first had, but the folder structure was cleaned mamually via the removal of the .pyc and git clean etc...
We are still looking into the cleanup script, but this error during clean attempt should not impact your postprocessing anymore.
If this error is producing any PP-failure notification, please let me know.

If you click on a processed download that shows pp-failure, each PP script should show a status and colour. So I am hoping nzbToSickBeard is green/success.

**Comment by elmero1** [comment]
Thanks a lot for your help. Everything work fine, you can close the ticket.
