### ISSUE TITLE
Post-processing with radarr, nzbget and nzbToMedia

### ISSUE THREAD

**Issue by elmero1** [clinton-hall/nzbToMedia#1589]
I use radarr, nzbget and the nzbToMedia scripts.
In radarr I can add the movies and the download in nzbget works (connection between radarr and nzbget is fine). After the download is finished, the post-processing script (nzbToRadarr) will be executed and I can see the message:
nzbToRadarr: Radarr: Successfully post-processed 
Post-process-script nzbToMedia/nzbToRadarr.py for successful

But in Radarr the movie is still missing. I've a problem between nzbget, radarr and nzbToMedia. Do you have an idea, where exactly the problem is? Which log files do you need for analysis?
Thanks in advance.

**Comment by clinton-hall** [comment]
in the nzbTomedia logs (in NZBGet PP log) looks at the time that the script said it was sending the movie to Radarr.

Then see what the Radarr logs say at the same time.
