### ISSUE TITLE
Error During update of nzbToMedia

### ISSUE THREAD

**Issue by 03397** [clinton-hall/nzbToMedia#1611]
I have the package for QNAP for SABnzbdplus which contains the nzbToMedia.
When I try to start  and during the update I am getting an error during the git. This used to work with no problem I do not know when it broke.

[/share/MD0_DATA/.qpkg/SABnzbdplus] # ./sabnzbd.sh start
= (SABnzbdplus) is not active
* updating (SABnzbdplus): OK
* updating (nzbToMedia): failed!
result=[1]
error: Your local changes to the following files would be overwritten by merge:
        .gitignore
        README.md
        autoProcessMedia.cfg.spec
        changelog.txt
        core/__init__.py
        core/autoProcess/__init__.py
        core/autoProcess/autoProcessComics.py
        core/autoProcess/autoProcessGames.py
        core/autoProcess/autoProcessMovie.py
        core/autoProcess/autoProcessMusic.py
        core/autoProcess/autoProcessTV.py
        core/databases/__init__.py
        core/databases/mainDB.py
        core/extractor/__init__.py
        core/extractor/bin/AMD64/7z.dll
        core/extractor/bin/AMD64/7z.exe
        core/extractor/bin/AMD64/license.txt
        core/extractor/bin/x86/7z.dll
        core/extractor/bin/x86/7z.exe
        core/extractor/bin/x86/license.txt
        core/extractor/extractor.py
        core/gh_api.py
        core/linktastic/__init__.py
        core/linktastic/linktastic.py
        core/logger.py
        core/nzbToMediaAutoFork.py
        core/nzbToMediaConfig.py
        core/nzbToMediaDB.py
        core/nzbToMediaSceneExceptions.py
        core/nzbToMediaUserScript.py
        core/nzbToMediaUtil.py
        core/synchronousdeluge/__init__.py
        core/synchronousdeluge/client.py
        core/synchronousdeluge/exceptions.py
        core/synchronousdeluge/protocol.py
        core/synchronousdeluge/rencode.py
        core/synchronousdeluge/transfer.py
        core/transcoder/__init__.py
        core/transcoder/transcoder.py
        core/transmissionrpc/__init__.py
        core/transmissionrpc/client.py
        core/transmissionrpc/constants.py
        core/transmissionrpc/error.py
        core/transmissionrpc/httphandler.py
        core/transmissionrpc/session.py
        core/transmissionrpc/six.py
        core/transmissionrpc/torrent.py
        core/transmissionrpc/utils.py
        core/utorrent/__init__.py
        core/utorrent/client.py
        core/utorrent/upload.py
        core/versionCheck.py
        libs/__init__.py
        libs/babelfish/__init__.py
        libs/babelfish/converters/__init__.py
        libs/babelfish/converters/alpha2.py
        libs/babelfish/converters/alpha3b.py
        libs/babelfish/converters/alpha3t.py
        libs/babelfish/converters/countryname.py
        libs/babelfish/converters/name.py
        libs/babelfish/converters/opensubtitles.py
        libs/babelfish/converters/scope.py
        libs/babelfish/converters/type.py
        libs/babelfish/country.py
        libs/babelfish/data/get_files.py
        libs/babelfish/data/iso-3166-1.txt
        libs/babelfish/data/iso-639-3.tab
        libs/babelfish/data/iso15924-utf8-20131012.txt
        libs/babelfish/data/opensubtitles_languages.txt
        libs/babelfish/exceptions.py
        libs/babelfish/language.py
        libs/babelfish/script.py
        libs/babelfish/tests.py
        libs/backports.functools_lru_cache-1.2.1-py3.5-nspkg.pth
        libs/backports/functools_lru_cache.py
        libs/beets/__init__.py
        libs/beets/art.py
        libs/beets/autotag/__init__.py
        libs/beets/autotag/hooks.py
        libs/beets/autotag/match.py
        libs/beets/autotag/mb.py
        libs/beets/config_default.yaml
        libs/beets/dbcore/__init__.py
        libs/beets/dbcore/db.py
        libs/beets/dbcore/query.py
        libs/beets/dbcore/queryparse.py
        libs/beets/dbcore/types.py
        libs/beets/importer.py
        libs/beets/library.py
        libs/beets/logging.py
        libs/beets/mediafile.py
        libs/beets/plugins.py
        libs/beets/ui/__init__.py
        libs/beets/ui/commands.py
        libs/beets/ui/completion_base.sh
        libs/beets/util/__init__.py
        libs/beets/util/artresizer.py
        libs/beets/util/bluelet.py
        libs/beets/util/confit.py
        libs/beets/util/enumeration.py
        libs/beets/util/functemplate.py
        libs/beets/util/hidden.py
        libs/beets/util/pipeline.py
        libs/beets/vfs.py
        libs/beetsplug/__init__.py
        libs/beetsplug/acousticbrainz.py
        libs/beetsplug/badfiles.py
        libs/beetsplug/bench.py
        libs/beetsplug/bpd/__init__.py
        libs/beetsplug/bpd/gstplayer.py
        libs/beetsplug/bpm.py
        libs/beetsplug/bucket.py
        libs/beetsplug/chroma.py
        libs/beetsplug/convert.py
        libs/beetsplug/cue.py
        libs/beetsplug/discogs.py
        libs/beetsplug/duplicates.py
        libs/beetsplug/edit.py
        libs/beetsplug/embedart.py
        libs/beetsplug/embyupdate.py
        libs/beetsplug/export.py
        libs/beetsplug/fetchart.py
        libs/beetsplug/filefilter.py
        libs/beetsplug/freedesktop.py
        libs/beetsplug/fromfilename.py
        libs/beetsplug/ftintitle.py
        libs/beetsplug/fuzzy.py
        libs/beetsplug/hook.py
        libs/beetsplug/ihate.py
        libs/beetsplug/importadded.py
        libs/beetsplug/importfeeds.py
        libs/beetsplug/info.py
        libs/beetsplug/inline.py
        libs/beetsplug/ipfs.py
        libs/beetsplug/keyfinder.py

Aborting
Updating 80c8ad5..0db7c3e
* starting (SABnzbdplus): OK

**Comment by clinton-hall** [comment]
via ssh, cd into the nzbToMedia directory `cd /shares/Download/nzbToMedia` from memory...
then
```
git reset --hard
git pull
```
if that doesn't work, try
```
git stash
git pull
git stash clear
```

**Comment by 03397** [comment]
Thanks. The first two did the trick.
Do you have any clue why this might have happened?

Will I have the same problem when there is another update of nzbToMedia?

**Comment by clinton-hall** [comment]
I don't expect this should happen with regular updates. This may have been a once off.

According to the error you posted, the files on your system had local changes... I'm not sure what would have done that, but even something that changes file permissions (or another process 'touching' the files) might cause it.

Let me know if it happens again.

**Comment by clinton-hall** [comment]
Actually, I just realised most of those files were moved by the refactoring updates. So uf related to that, just a once off. When script runs itself it does a clean as well as updating, but when the SABnzbd script calls git pull that is handled differently.

**Comment by 03397** [comment]
Ok Clinton thanks.
