### ISSUE TITLE
Postprocessing scripts failing (Radarr and CouchPotato) - Exit(1) Exception AttributeError: "'NoneType' object has no attribute 'path'"

### ISSUE THREAD

**Issue by Xtropy74** [clinton-hall/nzbToMedia#1613]
I am getting similar errors when either scripts run. I just did a hard reset and GIT pull so running the latest code:

**RADARR**

> [17:23:59] [INFO]::MAIN: Checking database structure...
> [17:23:59] [INFO]::MAIN: Checking if git needs an update
> [17:24:06] [INFO]::MAIN: No update needed
> [17:24:06] [INFO]::MAIN: nzbToMedia Version:0db7c3e10c01cee85814a31fd3c5232b1d7d144e Branch:master (Linux 4.15.0-47-generic)
> [17:24:06] [INFO]::MAIN: #########################################################
> [17:24:06] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
> [17:24:06] [INFO]::MAIN: #########################################################
> [17:24:06] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
> [17:24:06] [INFO]::MAIN: Auto-detected SECTION:Radarr
> [17:24:06] [INFO]::MAIN: Calling Radarr:movie to post-process:Eat.and.Run.1987.DVDRip.x264-CHRONiCLER-xpost.nzb
> [17:24:06] [INFO]::MAIN: Attemping imdbID lookup for Eat.and.Run.1987.DVDRip.x264-CHRONiCLER-xpost.nzb
> [17:24:06] [INFO]::MAIN: Searching folder and file names for imdbID ...
> [17:24:06] [INFO]::MAIN: Searching IMDB for imdbID ...
> [17:24:06] [INFO]::MAIN: Unable to determine imdbID: No api key provided for ombdapi.com.
> [17:24:11] [INFO]::TRANSCODER: Checking [Eat.and.Run.1987.DVDRip.x264-CHRONiCLER.mkv] for corruption, please stand by ...
> [17:24:12] [INFO]::TRANSCODER: SUCCESS: [Eat.and.Run.1987.DVDRip.x264-CHRONiCLER.mkv] has no corruption.
> [17:24:12] [POSTPROCESS]::RADARR: Starting DownloadedMoviesScan scan for Eat.and.Run.1987.DVDRip.x264-CHRONiCLER-xpost.nzb
> l/dumper.pyc
> Removing libs/py2/yaml/emitter.pyc
> Removing libs/py2/yaml/error.pyc
> Removing libs/py2/yaml/events.pyc
> Removing libs/py2/yaml/loader.pyc
> Removing libs/py2/yaml/nodes.pyc
> Removing libs/py2/yaml/parser.pyc
> Removing libs/py2/yaml/reader.pyc
> Removing libs/py2/yaml/representer.pyc
> Removing libs/py2/yaml/resolver.pyc
> Removing libs/py2/yaml/scanner.pyc
> Removing libs/py2/yaml/serializer.pyc
> Removing libs/py2/yaml/tokens.pyc
> Removing libs/util.pyc
> Removing nzbToMedia.pyc
> 
> 
> -- Cleaning folders: ['libs', 'core'] --
> No folders to clean
> 
> Returning to directory:  /usr/bin
> 
> -- Cleanup finished --
> 
> Traceback (most recent call last):
> File "/usr/local/bin/nzbToMedia/nzbToRadarr.py", line 255, in <module>
> result = nzbToMedia.main(sys.argv, section)
> File "/usr/local/bin/nzbToMedia/nzbToMedia.py", line 894, in main
> download_id='', failure_link=''.join(args[8:]))
> File "/usr/local/bin/nzbToMedia/nzbToMedia.py", line 757, in process
> result = movies.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
> File "/usr/local/bin/nzbToMedia/core/auto_process/movies.py", line 233, in process
> logger.postprocess('Radarr response: {0}'.format(result['state']))
> TypeError: list indices must be integers, not str
> Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f34d3bd7f10>> ignored
> 

**COUCHPOTATO**

> [17:24:25] [INFO]::MAIN: Checking database structure...
> [17:24:25] [INFO]::MAIN: Checking if git needs an update
> [17:24:26] [INFO]::MAIN: No update needed
> [17:24:26] [INFO]::MAIN: nzbToMedia Version:0db7c3e10c01cee85814a31fd3c5232b1d7d144e Branch:master (Linux 4.15.0-47-generic)
> [17:24:26] [INFO]::MAIN: #########################################################
> [17:24:26] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
> [17:24:26] [INFO]::MAIN: #########################################################
> [17:24:26] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
> [17:24:29] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
> [17:24:29] [INFO]::MAIN: Calling CouchPotato:movies to post-process:Body.Bags.1993.FS.iNTERNAL.DVDRip.x264-REGRET-xpost.nzb
> [17:24:29] [INFO]::MAIN: Attemping imdbID lookup for Body.Bags.1993.FS.iNTERNAL.DVDRip.x264-REGRET-xpost.nzb
> [17:24:29] [INFO]::MAIN: Searching folder and file names for imdbID ...
> [17:24:29] [INFO]::MAIN: Searching IMDB for imdbID ...
> [17:24:29] [INFO]::MAIN: Unable to determine imdbID: No api key provided for ombdapi.com.
> [17:24:29] [ERROR]::MAIN: CouchPotato returned the following non-json data
> [17:24:29] [ERROR]::MAIN:
> [17:24:29] [ERROR]::MAIN: <!doctype html>
> [17:24:29] [ERROR]::MAIN: <html class="">
> [17:24:29] [ERROR]::MAIN: <head>
> [17:24:29] [ERROR]::MAIN: <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
> [17:24:29] [ERROR]::MAIN: <meta name="apple-mobile-web-app-capable" content="yes">
> [17:24:29] [ERROR]::MAIN: <meta name="mobile-web-app-capable" content="yes">
> [17:24:29] [ERROR]::MAIN: <meta http-equiv="X-UA-Compatible" content="IE=edge" />
> [17:24:29] [ERROR]::MAIN: <meta name="robots" content="noindex, nofollow" />
> [17:24:29] [ERROR]::MAIN:
> [17:24:29] [ERROR]::MAIN: <link data-url="static/style/combined.min.css?1551812681" rel="stylesheet" href="/couchpotato/static/style/combined.min.css?1551812681" type="text/css">
> [17:24:29] [ERROR]::MAIN:
> [17:24:29] [ERROR]::MAIN: <script type="text/javascript" src="/couchpotato/static/scripts/combined.vendor.min.js?1551812681"></script>
> [17:24:29] [ERROR]::MAIN: <script type="text/javascript" src="/couchpotato/static/scripts/combined.base.min.js?1551812681"></script>
> [17:24:29] [ERROR]::MAIN: <link href="/couchpotato/static/images/favicon.ico" rel="icon" type="image/x-icon" />
> [17:24:29] [ERROR]::MAIN: <link rel="apple-touch-icon" href="/couchpotato/static/images/homescreen.png" />
> [17:24:29] [ERROR]::MAIN:
> [17:24:29] [ERROR]::MAIN: <title>CouchPotato</title>
> [17:24:29] [ERROR]::MAIN: </head>
> [17:24:29] [ERROR]::MAIN: <body class="page login">
> [17:24:29] [ERROR]::MAIN: <form action="" method="post">
> [17:24:29] [ERROR]::MAIN: <h1>CouchPotato</h1>
> [17:24:29] [ERROR]::MAIN: <div class="ctrlHolder"><input class="username" name="username" type="text" placeholder="Username" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" autofocus="autofocus" /></div>
> [17:24:29] [ERROR]::MAIN: <div class="ctrlHolder"><input class="password" name="password" type="password" placeholder="Password" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" /></div>
> [17:24:29] [ERROR]::MAIN: <div class="ctrlHolder">
> [17:24:29] [ERROR]::MAIN: <label class="remember_me" title="for 30 days"><input id="remember_me" name="remember_me" type="checkbox" value="1" checked="checked" /> Remember me</label>
> [17:24:29] [ERROR]::MAIN: <input class="button" name="submit" type="submit" value="Login" />
> [17:24:29] [ERROR]::MAIN: </div>
> [17:24:29] [ERROR]::MAIN: </form>
> [17:24:29] [ERROR]::MAIN: </body>
> [17:24:29] [ERROR]::MAIN: </html>
> [17:24:29] [INFO]::TRANSCODER: Checking [body.bags.1993.fs.internal.dvdrip.x264-regret.mkv] for corruption, please stand by ...
> [17:24:29] [INFO]::TRANSCODER: SUCCESS: [body.bags.1993.fs.internal.dvdrip.x264-regret.mkv] has no corruption.
> [17:24:29] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for Body.Bags.1993.FS.iNTERNAL.DVDRip.x264-REGRET-xpost.nzb
> l/dumper.pyc
> Removing libs/py2/yaml/emitter.pyc
> Removing libs/py2/yaml/error.pyc
> Removing libs/py2/yaml/events.pyc
> Removing libs/py2/yaml/loader.pyc
> Removing libs/py2/yaml/nodes.pyc
> Removing libs/py2/yaml/parser.pyc
> Removing libs/py2/yaml/reader.pyc
> Removing libs/py2/yaml/representer.pyc
> Removing libs/py2/yaml/resolver.pyc
> Removing libs/py2/yaml/scanner.pyc
> Removing libs/py2/yaml/serializer.pyc
> Removing libs/py2/yaml/tokens.pyc
> Removing libs/util.pyc
> Removing nzbToMedia.pyc
> 
> 
> -- Cleaning folders: ['libs', 'core'] --
> No folders to clean
> 
> Returning to directory:  /usr/bin
> 
> -- Cleanup finished --
> 
> Traceback (most recent call last):
> File "/usr/local/bin/nzbToMedia/nzbToCouchPotato.py", line 263, in <module>
> result = nzbToMedia.main(sys.argv, section)
> File "/usr/local/bin/nzbToMedia/nzbToMedia.py", line 894, in main
> download_id='', failure_link=''.join(args[8:]))
> File "/usr/local/bin/nzbToMedia/nzbToMedia.py", line 757, in process
> result = movies.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
> File "/usr/local/bin/nzbToMedia/core/auto_process/movies.py", line 218, in process
> result = r.json()
> File "/usr/local/bin/nzbToMedia/libs/common/requests/models.py", line 897, in json
> return complexjson.loads(self.text, **kwargs)
> File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
> return _default_decoder.decode(s)
> File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
> raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
> Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7fdf81f59f10>> ignored

Any idea what the issue could be?

**Comment by clinton-hall** [comment]
do you have the CouchPotato and Radarr api keys set in the appropriate section?

can you enable debug logging and then post logs after more failed processing?
```
[General]
    log_debug = 1
```

**Comment by Xtropy74** [comment]
Here you go. I checked Radarr and there are NO logs related to this download (FYI)

> [18:23:17] [INFO]::MAIN: Python v2.7 will reach end of life in 251 days.
> [18:23:17] [WARNING]::MAIN: Please upgrade to a more recent Python version.
> [18:23:17] [INFO]::MAIN: Checking database structure...
> [18:23:17] [DEBUG]::MAIN: Checking Initial Schema database upgrade
> [18:23:17] [DEBUG]::MAIN: InitialSchema upgrade not required
> [18:23:17] [DEBUG]::MAIN: Checking if we can use git commands: git version
> [18:23:17] [DEBUG]::MAIN: Executing git version with your shell in /usr/local/bin/nzbToMedia
> [18:23:17] [DEBUG]::MAIN: git version : returned successful
> [18:23:17] [DEBUG]::MAIN: Using: git
> [18:23:17] [DEBUG]::MAIN: Executing git symbolic-ref -q HEAD with your shell in /usr/local/bin/nzbToMedia
> [18:23:17] [DEBUG]::MAIN: git symbolic-ref -q HEAD : returned successful
> [18:23:17] [INFO]::MAIN: Checking if git needs an update
> [18:23:17] [DEBUG]::MAIN: Executing git rev-parse HEAD with your shell in /usr/local/bin/nzbToMedia
> [18:23:17] [DEBUG]::MAIN: git rev-parse HEAD : returned successful
> [18:23:17] [DEBUG]::MAIN: Executing git fetch origin with your shell in /usr/local/bin/nzbToMedia
> [18:23:17] [DEBUG]::MAIN: git fetch origin : returned successful
> [18:23:17] [DEBUG]::MAIN: Executing git rev-parse --verify --quiet '@{upstream}' with your shell in /usr/local/bin/nzbToMedia
> [18:23:17] [DEBUG]::MAIN: git rev-parse --verify --quiet '@{upstream}' : returned successful
> [18:23:17] [DEBUG]::MAIN: Executing git rev-list --left-right '@{upstream}'...HEAD with your shell in /usr/local/bin/nzbToMedia
> [18:23:17] [DEBUG]::MAIN: git rev-list --left-right '@{upstream}'...HEAD : returned successful
> [18:23:17] [DEBUG]::MAIN: cur_commit = 0db7c3e10c01cee85814a31fd3c5232b1d7d144e % (newest_commit)= 0db7c3e10c01cee85814a31fd3c5232b1d7d144e, num_commits_behind = 0, num_commits_ahead = 0
> [18:23:17] [INFO]::MAIN: No update needed
> [18:23:17] [INFO]::MAIN: nzbToMedia Version:0db7c3e10c01cee85814a31fd3c5232b1d7d144e Branch:master (Linux 4.15.0-47-generic)
> [18:23:17] [INFO]::MAIN: #########################################################
> [18:23:17] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
> [18:23:17] [INFO]::MAIN: #########################################################
> [18:23:17] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/usr/local/bin/nzbToMedia/nzbToRadarr.py', '/media/Media/Downloads/NZB/Complete/Body.Bags.1993.FS.iNTERNAL.DVDRip.x264-REGRET-xpost.1', 'Body.Bags.1993.FS.iNTERNAL.DVDRip.x264-REGRET-xpost.nzb', 'Body.Bags.1993.FS.iNTERNAL.DVDRip.x264-REGRET-xpost', '', 'movie', 'alt.binaries.wtfnzb.charlie', '0', '']
> [18:23:17] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
> [18:23:17] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
> [18:23:17] [DEBUG]::MAIN: Found nzoid: SABnzbd_nzo_F4F6wS
> [18:23:17] [DEBUG]::MAIN: Adding NZB download info for directory /media/Media/Downloads/NZB/Complete/Body.Bags.1993.FS.iNTERNAL.DVDRip.x264-REGRET-xpost.1 to database
> [18:23:17] [INFO]::MAIN: Auto-detected SECTION:Radarr
> [18:23:17] [DEBUG]::MAIN: Checking for archives to extract in directory: /media/Media/Downloads/NZB/Complete/Body.Bags.1993.FS.iNTERNAL.DVDRip.x264-REGRET-xpost.1
> [18:23:17] [INFO]::MAIN: Calling Radarr:movie to post-process:Body.Bags.1993.FS.iNTERNAL.DVDRip.x264-REGRET-xpost.nzb
> [18:23:17] [INFO]::MAIN: Attemping imdbID lookup for Body.Bags.1993.FS.iNTERNAL.DVDRip.x264-REGRET-xpost.nzb
> [18:23:17] [INFO]::MAIN: Searching folder and file names for imdbID ...
> [18:23:17] [INFO]::MAIN: Searching IMDB for imdbID ...
> [18:23:17] [INFO]::MAIN: Unable to determine imdbID: No api key provided for ombdapi.com.
> [18:23:17] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:7878/api/command
> [18:23:18] [DEBUG]::SERVER: Server responded at http://localhost:7878/api/command
> [18:23:18] [DEBUG]::MAIN: calling command: ffprobe -v quiet -print_format json -show_format -show_streams -show_error /usr/local/bin/nzbToMedia/tests/test.mp4
> [18:23:18] [INFO]::TRANSCODER: Checking [body.bags.1993.fs.internal.dvdrip.x264-regret.mkv] for corruption, please stand by ...
> [18:23:18] [DEBUG]::MAIN: calling command: ffprobe -v quiet -print_format json -show_format -show_streams -show_error /media/Media/Downloads/NZB/Complete/Body.Bags.1993.FS.iNTERNAL.DVDRip.x264-REGRET-xpost.1/body.bags.1993.fs.internal.dvdrip.x264-regret.mkv
> [18:23:18] [INFO]::TRANSCODER: SUCCESS: [body.bags.1993.fs.internal.dvdrip.x264-regret.mkv] has no corruption.
> [18:23:18] [DEBUG]::RADARR: Opening URL: http://localhost:7878/api/command with PARAMS: {'path': '/media/Media/Downloads/NZB/Complete/Body.Bags.1993.FS.iNTERNAL.DVDRip.x264-REGRET-xpost.1', 'importMode': 'Copy', 'name': 'DownloadedMoviesScan', 'downloadClientId': u'SABnzbd_nzo_F4F6wS'}
> [18:23:18] [POSTPROCESS]::RADARR: Starting DownloadedMoviesScan scan for Body.Bags.1993.FS.iNTERNAL.DVDRip.x264-REGRET-xpost.nzb
> to directory:  /usr/bin
> 
> -- Cleanup finished --
> 
> Traceback (most recent call last):
> File "/usr/local/bin/nzbToMedia/nzbToRadarr.py", line 255, in <module>
> result = nzbToMedia.main(sys.argv, section)
> File "/usr/local/bin/nzbToMedia/nzbToMedia.py", line 894, in main
> download_id='', failure_link=''.join(args[8:]))
> File "/usr/local/bin/nzbToMedia/nzbToMedia.py", line 757, in process
> result = movies.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
> File "/usr/local/bin/nzbToMedia/core/auto_process/movies.py", line 233, in process
> logger.postprocess('Radarr response: {0}'.format(result['state']))
> TypeError: list indices must be integers, not str
> Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7fdfb5e53f10>> ignored

**Comment by Xtropy74** [comment]
I found out what the issue was. I am using a Reverse Proxy and the path needed to be added to `web_root =` to fix the problem. Was hard to track down since CP/Radarr/Sonarr use the term `URL BASE` and autoProcessMedia uses the term `web_root`. 

Anyway, once adding the path, it fixed the issue. Sorry for the trouble

**Comment by clinton-hall** [comment]
glad you found the solution. and thanks for posting the fix.
