### ISSUE TITLE
Trying to extract every single part of multi part RAR on aborted download 

### ISSUE THREAD

**Issue by arondurkin** [clinton-hall/nzbToMedia#1618]
**Describe the bug**
Attempting to extract every .rar file on an aborted download. 

**Technical Specs**
1. Running on Synology 1019+ 
2. Python version 3
3. Download Client Sabnzbd
4. Intended Media Management SickChill

**Expected behavior**
Either don’t try and extract when Sab returns “Aborted” and / or after attempting to extract once and failing stop and mark as failed. “No_extract_failed” is set to 1. 

The failed extract is returning code 3.

**Comment by clinton-hall** [comment]
try updating to latest nightly and see if this now works as desired. This should respect `No_extract_failed`
