### ISSUE TITLE
Processing torrents from qBittorrent with apostrophes results in full folder scan

### ISSUE THREAD

**Issue by TheHolyRoger** [clinton-hall/nzbToMedia#1624]
**Describe the bug**
Processing torrents from qBittorrent with apostrophes results in a full folder scan and the folder is not found during identification/search

**Technical Specs**
1. Running on Ubuntu, Windows, Mac
2. Python version 2.7
3. Download Client qBittorrent
4. Intended Media Management Medusa

**Expected behavior**
INFO    ::MAIN: SEARCH: Found torrent directory

**Log**
DEBUG   ::MAIN: Options passed into TorrentToMedia: ['TorrentToMedia.py', "/.../tv_m/|It's.Always.Sunny.in.Philadelphia.S08.Bluray.Remux.1080p.AVC.DTS-HD.MA.5.1-BMF|tv_m|8850562b8e78df8088a730dc6cc6f12268f9258b"]
DEBUG   ::MAIN: Received Directory: /.../tv_m | Name: Its.Always.Sunny.in.Philadelphia.S08.Bluray.Remux.1080p.AVC.DTS-HD.MA.5.1-BMF | Category: tv_m
DEBUG   ::MAIN: SEARCH: Found the Category: tv_m in directory structure
INFO    ::MAIN: SEARCH: Could not find a unique directory for this download. Assume a common directory.
INFO    ::MAIN: SEARCH: We will try and determine which files to process, individually

**Comment by clinton-hall** [comment]
thanks for the fix. This is now in nightly.
