### ISSUE TITLE
execute TorrentToMedia.py just with python3?

### ISSUE THREAD

**Issue by trohnjavolta** [clinton-hall/nzbToMedia#1626]
**Describe the bug**
I'm using nzbtomedia in a deluge docker container.
The script stopped working and I figured out why:
After 2 years deluge now got an update and seems to use python3 now.
So the docker container with alpine linux also got an update.
I read this: https://github.com/clinton-hall/nzbToMedia/wiki/installation#sym-link-python-binaries
but cannot create such symlink since there is no python2 or 2.7 in the container anymore..since it's not needed for deluge anymore.
In /usr/bin I only have pyton3 and 3.6 entries now :(

Is there some way I could still use nzbtomedia scripts in that docker container?

**Technical Specs**
1. Running on: alpine linux docker container, python3 only
2. Python version: '3'
3. Download Client: deluge
4. Intended Media Management: medusa

**Comment by labrys** [comment]
Wiki needs update... The scripts are Python 2/3 compatible.  Just symlink to Python 3 and you're all good.

**Comment by trohnjavolta** [comment]
Yes, I understood that but I cannot link since in the container there is only python3 installed not python2! 
How would I link, if there's nowhere to link? 
Also I don't want to install python2 in that container cause then I would have to maintain it mysef.

**Comment by labrys** [comment]
You do not need Python 2 for TorrentToMedia.   It only looks for python in the system path and will work with any supported python version.  The symlink is only required if python is not on the system path.  I have updated the wiki to make it clear that other python versions are supported and not just 2.7.

**Comment by trohnjavolta** [comment]
Sry, my fault. I tried it and got error back. Then I realized, I didn't update nzbtomedia in a while.
Now I did, copied the old autoprocessmedia.cfg back aaaand...it doesn't work :(
But it isn't an issue with python, so you can close this.
Log doesn't give much info, but says connetion to deluge failed.... I didn't change anything so no idea why it doesn't work.

**Comment by trohnjavolta** [comment]
Hmm.. ok, script isn't triggered.
In console in nzbtomedia folder typing ./TorrentToMedia.py I get this:
`/usr/bin/env: ‘python’: No such file or directory`

So in console I entered:
`ln -sf /usr/bin/python /usr/bin/python3.6`

But it didn't work :(

**Comment by clinton-hall** [comment]
command to link should be `ln -sf /usr/bin/python3.6 /usr/bin/python`
I have updated the wiki to reflect this.

Have you confirmed where your python(3.6) or python exists?
`which python`
`which python3`
`which python3.6`

**Comment by trohnjavolta** [comment]
I now just recreated the container to get rid of the wrong link.
With your correct symlink the script now gets triggered by deluge but postprocessing isn't working:

I get this in the logs:
```
2019-06-16 10:57:41 INFO    ::MAIN: Loading config from [/config/nzbtomedia/autoProcessMedia.cfg]
2019-06-16 10:57:41 INFO    ::MAIN: Python v3.6 will reach end of life in 921 days.
2019-06-16 10:57:41 INFO    ::MAIN: Checking database structure...
2019-06-16 10:57:41 INFO    ::MAIN: Checking if git needs an update
2019-06-16 10:57:41 ERROR   ::MAIN: Unable to determine installed version via git, please check your logs!
2019-06-16 10:57:41 INFO    ::MAIN: No update needed
2019-06-16 10:57:41 INFO    ::MAIN: nzbToMedia Version:12.0.10 Branch:nightly (Linux 4.14.111-odroidxu4)
2019-06-16 10:57:41 WARNING ::MAIN: Failed to locate par2. Repair and rename using par files will not be possible!
2019-06-16 10:57:41 WARNING ::MAIN: Failed to locate ffmpeg. Transcoding disabled!
2019-06-16 10:57:41 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...
2019-06-16 10:57:41 WARNING ::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
2019-06-16 10:57:41 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...
2019-06-16 10:57:41 ERROR   ::MAIN: Failed to connect to Deluge
2019-06-16 10:57:41 INFO    ::MAIN: #########################################################
2019-06-16 10:57:41 INFO    ::MAIN: ## ..::[TorrentToMedia.py]::.. ##
2019-06-16 10:57:41 INFO    ::MAIN: #########################################################
```

Idk why suddenly it fails to connect to deluge, didn't change the autoprocessmedia.cfg. Here's the deluge part:

```
#### Deluge (You must edit this if you're using TorrentToMedia.py with deluge. Note that the host/port is for the deluge daemon, not the webui)
    DelugeHost = localhost
    DelugePort = 58846
    DelugeUSR = localclient
    DelugePWD = *******
```

**Comment by clinton-hall** [comment]
ok... when you recreated the container, did you set up the deluge user again?
https://github.com/clinton-hall/nzbToMedia/wiki/deluge
look at the second bullet point under point 2.

Yes, there has been discussion around an nzbToMedia docker.
https://github.com/clinton-hall/nzbToMedia/issues/1616

the main reason why you can't just add nzbToMedia into a docker (with dependencies) as you suggested is that nzbToMedia needs to be called by the downloader. So really we need to have "trigger" scripts
inside the downloader docker that then call an api/library within nzbToMedia docker.... so a bit more work needed here to allow this.

**Comment by trohnjavolta** [comment]
Oh man...this gets worse and worse: 
Since the auth file is in config folder which is mounted every time the container changes, this shouldn't have changed.
In the file there was localclient:bunchofnumbers:10.
I deleted the numbers and put my pw in saved the file and restarted the container.
Now I cannot connect to the deluge anymore :(
At this point I just want everything to work..

**Comment by clinton-hall** [comment]
https://dev.deluge-torrent.org/wiki/UserGuide/Authentication

yes, you should add the user and pass that you have in autoProcessMedia.cfg
```
[Torrent]
    DelugeUSR = localclient
    DelugePWD = *******
```
I believe that needs to be in addition to the default one that deluge first created when running the daemon.

**Comment by trohnjavolta** [comment]
I now did that. Again, failed to connect to deluge :(
Makes no sense, it used to work. The udate of deluge container shouldn't have changed anything in the config folder at all.
Any other ideas?

**Comment by clinton-hall** [comment]
I wonder if there is something funny happening with Deluge client using Python 3?
Can you enable debug logging 
```
[General]
    log_debug = 1
```
Then see if anything else is logged when the script runs.

Can you do a manual run of TorrentToMedia from winth in your docker?
if so, try editing
https://github.com/clinton-hall/nzbToMedia/blob/master/core/plugins/downloaders/torrent/deluge.py#L16-L21

from
```
    try:
        client.connect(host, port, user, password)
    except Exception:
        logger.error('Failed to connect to Deluge')
    else:
        return client
```
to 
```
   # try:
    client.connect(host, port, user, password)
    #except Exception:
        #logger.error('Failed to connect to Deluge')
    #else:
    return client
```
Then run the script and see if this provides a traceback.

Other option is to try and run TorrentToMedia from outside of the container (Set DelugeHost = <IP of Deluge>)
See if this runs and connects externally. If you have Python2.7 and Python3, try calling the script specifically with each version to see if that makes a difference
`python2 TorrentToMedia.py`
`python3 TorrentToMedia.py`

**Comment by trohnjavolta** [comment]
Thx I appreciate the help. Will try all when I'm at home.
Just 2 questions, I'm not that experienced, was happy that I could make all this work back then somehow:

I can do a manual run inside the deluge container. But how should I edit deluge.py?
Just edit with nano and comment out the lines, save, done?
I didn't know you can run TorrentToMedia.py from outside the container and have it connect to deluge in a container.
Now that I think of it, it makes sense...
So I know I can "reach" deluge container with the containername. So "IP" is deluge.
Do I just edit autoprocessmedia.cfg and set DelugeHost = deluge instead of localhost?
And port stays same, I think... I use dockstarter for all this and I think it also maps ports of local machine to docker container.
Sry, I a bit of debian, linux and docker noob :D

**Comment by clinton-hall** [comment]
ok...  docker ports should be open since you can access the webUI.

I did a test here and found the issue... It was introduced by an update at this end.
Please update to latest nightly and this should work again.

**Comment by trohnjavolta** [comment]
Nice, will do. Thx for this instant fix!

**Comment by trohnjavolta** [comment]
Just wanted to confirm that it works on nightly 👍 
Now I just get the usual stuff:
Failed to delete the torrent in deluge.
Dir still contains an unprocessed file, so it isn't deleted.
Can I somehow tell the script to ignore .nfo files and sub folders, so it does the clean up?
Also why can't it delete the torrent in deluge?..All this also didn't work before.

**Comment by clinton-hall** [comment]
option
```
[General]
    force_clean = 1
```
should help with the .nfo files etc...
with regard failing to delete torrent in deluge, are you able to send me some log files just so I can get my head around the flow you are using?
email to `fock_wulf@hotmail.com`
I am thinking this is an issue with the deluge plugin where it actually fails to send the delete request.

**Comment by clinton-hall** [comment]
ok... that looks like a simple fix, but that actually took me a while to find!

For me, this is working on both Py2 and Py3. I did some test connections into deluge, watched it pause, resume, delete... so I am hoping if you update to latest nightly this will now work for you.

**Comment by trohnjavolta** [comment]
Aww that's great. Normally for that kind of off topic one gets bashed by the dev and issue gets closed :) 

It does not tell me anything, I'm no coder...just 3 lousy semesters of programming and 1 exam :D 
But I appreciate the effort.

**Comment by FlyingPersian** [comment]
Hi
I'm having similar issues with python3. I can't get it to work with neither python3.6 nor python3.7. Python2.7 works fine in both manual and automatic run. I don't get a log file, but this is what's printed when I run the script manually:

https://pastebin.com/EzqL0F2U

Tried both python3.6 and 3.7, same issue. Running the latest master branch in a FreeNAS iocage jail.

**Comment by trohnjavolta** [comment]
> Hi
> I'm having similar issues with python3. I can't get it to work with neither python3.6 nor python3.7. Python2.7 works fine in both manual and automatic run. I don't get a log file, but this is what's printed when I run the script manually:
> 
> https://pastebin.com/EzqL0F2U
> 
> Tried both python3.6 and 3.7, same issue. Running the latest nightly branch ([f1dc672](https://github.com/clinton-hall/nzbToMedia/commit/f1dc6720564ab7c4d255fdf54c87a164e7eb6dcf)) in a FreeNAS iocage jail.

Switch to nightly branch. As of my understanding the fix is not yet merged into master branch....or how it's called :D

**Comment by FlyingPersian** [comment]
> > Hi
> > I'm having similar issues with python3. I can't get it to work with neither python3.6 nor python3.7. Python2.7 works fine in both manual and automatic run. I don't get a log file, but this is what's printed when I run the script manually:
> > https://pastebin.com/EzqL0F2U
> > Tried both python3.6 and 3.7, same issue. Running the latest nightly branch ([f1dc672](https://github.com/clinton-hall/nzbToMedia/commit/f1dc6720564ab7c4d255fdf54c87a164e7eb6dcf)) in a FreeNAS iocage jail.
> 
> Switch to nightly branch. As of my understanding the fix is not yet merged into master branch....or how it's called :D

Yes I did that! I was on master and changed to nightly. I hope I did it right? 

git checkout nightly
git pull
get fetch --all
git reset --hard origin/nightly
git pull

"git log -1" outputs:

commit f1dc6720564ab7c4d255fdf54c87a164e7eb6dcf (HEAD -> nightly, origin/nightly)
Author: clinton-hall <fock_wulf@hotmail.com>
Date:   Wed Jun 19 22:50:36 2019 +1200

    fix deluge client for python3. Fixes #1626

**Comment by clinton-hall** [comment]
```
  File "/usr/home/admin/nzbToMedia/core/utils/processes.py", line 46, in alreadyrunning
    self.lock_socket.bind('\0{path}'.format(path=self.pidpath))
FileNotFoundError: [Errno 2] No such file or directory
```
this is saying it can't make `/usr/home/admin/nzbToMedia/logs/nzbtomedia.pid`
my assumption here would be permissions. Make sure the logs directory exists and the user has permissions to edit.

ok, just saw it works in Py2.7 but not py3.... I'll try some more testing to verify. it could be a missing lib on your install?

**Comment by FlyingPersian** [comment]
> ```
>   File "/usr/home/admin/nzbToMedia/core/utils/processes.py", line 46, in alreadyrunning
>     self.lock_socket.bind('\0{path}'.format(path=self.pidpath))
> FileNotFoundError: [Errno 2] No such file or directory
> ```
> 
> this is saying it can't make `/usr/home/admin/nzbToMedia/logs/nzbtomedia.pid`
> my assumption here would be permissions. Make sure the logs directory exists and the user has permissions to edit.
> 
> ok, just saw it works in Py2.7 but not py3.... I'll try some more testing to verify. it could be a missing lib on your install?

Which lib might that be? To test it with python2.7, I just installed python27, py27-sqlite3 and py27-setuptools. I have the same respective packages for python36 and 37. Unless I need install a lib manually, I'd say I'm good on the lib-side. 

Permissions of the folder for the pid are fine. It's all owned by the user running nzbtomedia

**Comment by clinton-hall** [comment]
By lib, I was wondering if this was a lib actually built into the python packages (on your distro).

I have tested this on Python 3.5 and 3.6 here and cannot replicate (on Ubuntu).
This does appear that the way your "socket" library tries to create the socket is different...

I have found an issue with multiple running instances, that causes a similar error with the exception handling... so hopefully this fix will stop the second error (and may allow this to run) but this may mean your system is not able to detect already running instances...

Please update to latest nightly and test again.

**Comment by FlyingPersian** [comment]
Well now it's starting, but it doesn't extract any rars. Python2.7 does so, so must be something buggy with 3.6 and 3.7:

https://pastebin.com/T2XfDLpr

I mean it's not that big of a deal, in theory I can still keep using python2.7.. On the other hand it does make sense to fix this if it's not just my machine having these issues

**Comment by clinton-hall** [comment]
@FlyingPersian 
So everything is now working correctly for you on Py3?

@trohnjavolta 

> Aww that's great. Normally for that kind of off topic one gets bashed by the dev and issue gets closed :)

I try to keep it easy. You have an issue, I'll try and fix.
My trouble is I don't use every combinations of downloaders/dockers/platforms etc, so sometimes for issues like this I need to actually build a configuration to test with...

So, again for you, is everything now working correctly?

**Comment by FlyingPersian** [comment]
@clinton-hall yes so far to does! I'll report back it it stops for whatever reason. Thanks for the quick help!
