### ISSUE TITLE
script failing after SC updated - SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!

### ISSUE THREAD

**Issue by PonyXpress** [clinton-hall/nzbToMedia#1628]
**Describe the bug**

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) '....'
2. Python version '....'
3. Download Client (NZBget, SABnbzd, Transmission) '....'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) '....'

**Expected behavior**

**Log**
Please provide an extract, or full debug log that indicates the issue.

**Comment by PonyXpress** [comment]
Sick Chill was updated a week or two ago.  I'm now seeing errors in sab when running the nzbtomedia script.  Log info attached.  Any idea what happened and how to fix it?

[sc script errors.txt](https://github.com/clinton-hall/nzbToMedia/files/3311049/sc.script.errors.txt)

**Comment by clinton-hall** [comment]
ok... noy sure what changed there, but it looks as though it is not accepting user/pass and logging you in...

I would suggest trying using API (SC now supports API and it is cleaner)
```
[SickBeard]
    [[tv]]
        apikey =
```
Just enter the api key from SickChill...
This should then use the api interface that still appears to be working here.

**Comment by PonyXpress** [comment]
That did the trick, many thanks for the awesome support and quick response!
