### ISSUE TITLE
How to remove source dir after successful post process

### ISSUE THREAD

**Issue by alon24** [clinton-hall/nzbToMedia#1634]
Now that I am managed to get it working with Medusa and qbittorrent, how can I make so that when the post process is finished, it will delete the source directory?

I need to remove the torrents.. /tv/dir1 after it finished moving the mkv file.

That dir is not empty. And it stays there. And I do not need it to be prese t, it has a few left over files and dies I. It, like smaple or images dir, and I need it to be removed

**Comment by clinton-hall** [comment]
Try this:
```
[General]
    safe_mode = 0

[Torrent]
    useLink = move
    deleteOriginal = 1
    resume = 0
```
see if this works.

**Comment by alon24** [comment]
its not deleting the source dir
It is still there, it has a subdirectory screens in it
/home/ilan/Torrents/tv/Billions.S04E09.480p.x264-mSD/Screens

**Comment by clinton-hall** [comment]
`2019-07-14 00:12:08 DEBUG   ::MAIN: Deleting torrent Billions.S04E10.480p.x264-mSD from qbittorrent`

does the torrent still appear in qbittorrent?
this is supposed to delete all original files.

**Comment by alon24** [comment]
well I have qbittorent automatically stop seeding, soI do not think the script does anything here.
I do this, because I never did manage to get this to work on my machine, so I do it in qbittorrent (stop the seeding)

**Comment by alon24** [comment]
K, so I just made this change u suggested and it did remove the torrent from qbittorrent ,and removed the source dir

Good job, and thank you for responsivness

**Comment by clinton-hall** [comment]
glad to hear. 
I added a brief description on the chmod in wiki too. thanks for reporting.

Let me know if you encounter any further issues.
