### ISSUE TITLE
Problem trying to process multiple folders with manual run of nzbToSickbeard.py

### ISSUE THREAD

**Issue by josurr** [clinton-hall/nzbToMedia#1637]
**Describe the bug**
When trying to process multiple episodes of both the same show and also multiple episodes (each from a different show), the script seems to only process one random folder & its contents and proceeds to appear to be processing the remaining folders. However, the script eventually finishes stating with "SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!"

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) **'Windows 7 Pro x64'**
2. Python version **'2.7.16'**
3. Download Client (NZBget, SABnbzd, Transmission) **'SABnzbd'**
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) **'SickChill'**

**Expected behavior**
All episode folders processed and the files contained within said folders be renamed and moved to their appropriate locations. Out of the 13 episodes, only episode 2 was "successfully" processed by being renamed and moved to the appropriate location.

**Log**
Log files from SickChill (extract from the time frame of the manual run) and the nzbToMedia scripts are attached.

(I figured I would open up a new issue rather than continue to post in that previous issue that was specific to SickGear).

[sickchill_debug_log.log](https://github.com/clinton-hall/nzbToMedia/files/3398995/sickchill_debug_log.log)
[new_nzbtomedia.log](https://github.com/clinton-hall/nzbToMedia/files/3398996/new_nzbtomedia.log)

**Comment by clinton-hall** [comment]
oh wow... now I see....

nzbToMedia tried fork detection:
```
2019-07-16 13:04:55 DEBUG   ::SERVER: Server responded at http://localhost:8081
2019-07-16 13:04:55 INFO    ::MAIN: Attempting to auto-detect tv fork
2019-07-16 13:04:56 INFO    ::MAIN: SickBeard:tv fork auto-detection successful ...
2019-07-16 13:04:56 INFO    ::MAIN: SickBeard:tv fork set to SickBeard-api
```
and this is verified by SickChill
```
2019-07-16 13:04:56 DEBUG    MANUAL :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2019-07-16 13:04:56 DEBUG    MANUAL :: API :: all args: '()'
2019-07-16 13:04:56 DEBUG    MANUAL :: API :: all kwargs: '{'cmd': 'help', 'subject': 'postprocess'}'
2019-07-16 13:04:56 DEBUG    MANUAL :: API :: help: cur_kwargs {'subject': 'postprocess'}
```
and the postprocess works (for the first folder)...

Then for the second folder...
```
2019-07-16 13:05:19 INFO    ::MAIN: Attempting to auto-detect tv fork
2019-07-16 13:05:20 INFO    ::MAIN: SickBeard:tv fork auto-detection failed
2019-07-16 13:05:20 INFO    ::MAIN: SickBeard:tv fork set to default
```
but SickChill seems to respond the same...
```
2019-07-16 13:05:20 DEBUG    MANUAL :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2019-07-16 13:05:20 DEBUG    MANUAL :: API :: all args: '()'
2019-07-16 13:05:20 DEBUG    MANUAL :: API :: all kwargs: '{'cmd': 'help', 'subject': 'postprocess'}'
2019-07-16 13:05:20 DEBUG    MANUAL :: API :: help: cur_kwargs {'subject': 'postprocess'}
```
The issue is nzbToMedia now passes the wrong parameters so SickChill ignores the PostProcess request...

I'm not sure if this is some sort of timing issue, or if I need to force this to release the "session", or if I need to set this to write the auto-detected fork into core on the first run and then re-use this on each subsequent run (not run the auto fork detection on each folder...)

**Comment by josurr** [comment]
I am glad that the errors make sense now. I can get all the folders to process eventually by rerunning the script (and updating the folder path if needed), but that is annoying sometimes when I just want to fix some files that have been borked.

**Comment by clinton-hall** [comment]
can you try switching to the `fix3` branch and testing this?

**Comment by josurr** [comment]
Still does not appear to process more than 1 folder when multiple are present.

There appears to be a permissions issue with the files in the nzbToMedia folder, but the script is being ran from an Administrator Command Prompt.

[new_nzbtomedia_fix3_branch.log](https://github.com/clinton-hall/nzbToMedia/files/3403832/new_nzbtomedia_fix3_branch.log)
[new_sickchill_fix3_branch.log](https://github.com/clinton-hall/nzbToMedia/files/3403833/new_sickchill_fix3_branch.log)

**Comment by clinton-hall** [comment]
The permissions error was relating to a .pyc file. This is preventing auto-updating...
You can delete all .pyc files and then this should auto update...

In any case, just try manually installing/updating to the latest fix3 branch... I am hoping this is now working. I had the "detected fork" made global at the wrong place... (Before the fork was detected!)

**Comment by josurr** [comment]
New error after deleting the .pyd file:

`D:\scripts\nzbToMedia>python nzbToSickBeard.py "D:\NZBs\_TV\Forged in Fire S06E2
1 720p HEVC x265-MeGusta"

-- Cleaning bytecode --
fatal: Not a git repository (or any of the parent directories): .git
WARNING: Automatic cleanup could not be executed.
         If errors occur, manual cleanup may be required.
REASON : Error Code: 128

Directory is not a git repository

Force cleaning folder: libs
Skipping required subfolders ['common', 'custom', 'py2', 'win']
Removing libs\__pycache__

Force cleaning folder: core
Skipping required subfolders ['auto_process', 'extractor', 'plugins', 'utils']
Removing core\__pycache__

-- Cleanup finished --

Traceback (most recent call last):
  File "nzbToSickBeard.py", line 270, in <module>
    import nzbToMedia
  File "D:\scripts\nzbToMedia\nzbToMedia.py", line 684, in <module>
    from core.auto_process import comics, games, movies, music, tv, books
  File "D:\scripts\nzbToMedia\core\auto_process\tv.py", line 25, in <module>
    from core.forks import auto_fork
  File "D:\scripts\nzbToMedia\core\forks.py", line 46
    global core.FORK_SET
                    ^
SyntaxError: invalid syntax`

The ^ is pointing at the period between core and FORK.

**Comment by clinton-hall** [comment]
ok. I have done some tests and this appears to work at my end...
Please update to latest fix3 and test again... hopefully this is there now.

**Comment by josurr** [comment]
New error with a fresh git clone of the fix3 branch:

```
Traceback (most recent call last):
  File "nzbToSickBeard.py", line 273, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "D:\scripts\nzbToMedia\nzbToMedia.py", line 982, in main
    input_name = input_name.encode(core.SYS_ENCODING)
AttributeError: 'bytes' object has no attribute 'encode'
```

Thanks for all your work on this!

**Comment by clinton-hall** [comment]
What has changed since the previous times you ran the code?
This part of the code has not been changed, and happens before the fork detection and indeed before the last error you reported.

**Comment by clinton-hall** [comment]
never mind, I believe the "what changed" is that you are now using python 3

I had not encountered this in my testing since I don't do manual processing... 
I have now hopefully sorted out that issue, so you should be able to update to latest fix3 and try again...

**Comment by josurr** [comment]
New, but more than likely easy to fix error:

`Traceback (most recent call last):
  File "nzbToSickBeard.py", line 273, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "D:\scripts\nzbToMedia\nzbToMedia.py", line 987, in main
    download_id=download_id or None, input_category=subsection)
  File "D:\scripts\nzbToMedia\nzbToMedia.py", line 798, in process
    extract_files(input_directory)
  File "D:\scripts\nzbToMedia\core\utils\files.py", line 178, in extract_files
    for inputFile in list_media_files(src, media=False, audio=False, meta=False,
 archives=True):
  File "D:\scripts\nzbToMedia\core\utils\files.py", line 150, in list_media_file
s
    for cur_file in os.listdir(text_type(path)):
OSError: [WinError 123] The filename, directory name, or volume label syntax is
incorrect: "b'D:\\\\NZBs\\\\_TV\\\\Forged in Fire S06E21 720p HEVC x265-MeGusta'
"`

Looks like it is adding 2 too many \

**Comment by clinton-hall** [comment]
sorry for this.... that was an issue I fixed for Torrent manual processing, but I never realised the same issue happened with manual processing for NZB when using Python3.

Tests here show that this should now get you back to the point where it detects the fork and calls SickChill to process.... so I'm hoping this should actually do it for you.

Once again, please update to latest fix3 (and if this works I'll merge into nightly).

**Comment by josurr** [comment]
You are a rock star.

The latest commit is working perfectly with manual runs for multiple folders.

Thanks again for the quick responses and fix!

**Comment by clinton-hall** [comment]
I have merged this into nightly branch.
You should be able to install the latest nightly branch now (as fix3 branch no-longer exists and will not allow further updating)

**Comment by josurr** [comment]
Awesome, thanks again!
