### ISSUE TITLE
nzbToMedia Faling On SABNZDB & CouchPotato

### ISSUE THREAD

**Issue by HPMSGEN8** [clinton-hall/nzbToMedia#1654]
I have everything running on my Synology and since i have updated to the latest Master i am getting the below:

-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
         If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory

-- Cleaning folders: [u'libs', u'core'] --
WARNING: Automatic cleanup could not be executed.
         If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory

-- Cleanup finished --

[09:49:13] [INFO]::MAIN: Loading config from [/volume1/KingstonSSD/103 NZB/Scripts/nzbToMedia/autoProcessMedia.cfg]
/volume1/KingstonSSD/103 NZB/Scripts/nzbToMedia/eol.py:146: LifetimeWarning: Python 2.7 is no longer supported.
  warnings.warn(msg, LifetimeWarning)
[09:49:13] [INFO]::MAIN: Python v2.7 will reach end of life in 103 days.
[09:49:13] [WARNING]::MAIN: Please upgrade to a more recent Python version.
Traceback (most recent call last):
  File "./nzbToMedia.py", line 1004, in <module>
    exit(main(sys.argv))
  File "./nzbToMedia.py", line 837, in main
    core.initialize(section)
  File "/volume1/KingstonSSD/103 NZB/Scripts/nzbToMedia/core/__init__.py", line 1017, in initialize
    main_db.upgrade_database(main_db.DBConnection(), databases.InitialSchema)
AttributeError: 'module' object has no attribute 'InitialSchema'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7ff980945a90>> ignored

I have installed Python 3

EDIT: I have tried the latest Nightly and still the same error

Thanks

**Comment by clinton-hall** [comment]
please take a look at this
https://github.com/clinton-hall/nzbToMedia/issues/1614

if you follow those steps, does that fix the issue?

**Comment by HPMSGEN8** [comment]
@clinton-hall Thanks a lot that worked 100%
