### ISSUE TITLE
Can't get nzbToMedia running from sabnzbd in docker container

### ISSUE THREAD

**Issue by eric1905** [clinton-hall/nzbToMedia#1657]
I am running sabnzbd in a docker container. i have the nzbtomedia script in a folder open for docker called scripts/nzbToMedia/. 
When i open my docker container with a bash and the command docker exec -it lssdf sh and go to this folder i see the following:

-rwxrwxrwx 1 abc users 21840 Oct  1 16:14 autoProcessMedia.cfg
-rwxrwxrwx 1 abc users 21840 Aug 13 08:40 autoProcessMedia.cfg.spec
-rwxrwxrwx 1 abc users  2868 Aug 13 08:40 azure-pipelines.yml
-rwxrwxrwx 1 abc users  6337 Aug 13 08:40 cleanup.py
-rwxrwxrwx 1 abc users    26 Aug 13 08:40 _config.yml
drwxrwsrwx 6 abc users  4096 Oct  1 15:58 core
-rwxrwxrwx 1 abc users  5379 Aug 13 08:40 eol.py
-rwxrwxrwx 1 abc users   504 Aug 13 08:40 getffmpeg.sh
drwxrwsrwx 6 abc users  4096 Oct  1 15:58 libs
-rwxrwxrwx 1 abc users 35127 Aug 13 08:40 license.txt
-rwxrwxrwx 1 abc users  7506 Aug 13 08:40 nzbToCouchPotato.py
-rwxrwxrwx 1 abc users  2993 Aug 13 08:40 nzbToGamez.py
-rwxrwxrwx 1 abc users  3824 Aug 13 08:40 nzbToHeadPhones.py
-rwxrwxrwx 1 abc users  3413 Aug 13 08:40 nzbToLazyLibrarian.py
-rwxrwxrwx 1 abc users  6979 Aug 13 08:40 nzbToLidarr.py
-rwxrwxrwx 1 abc users 31126 Aug 13 08:40 nzbToMedia.py
-rwxrwxrwx 1 abc users  3378 Aug 13 08:40 nzbToMylar.py
-rwxrwxrwx 1 abc users  7121 Aug 13 08:40 nzbToNzbDrone.py
-rwxrwxrwx 1 abc users  7221 Aug 13 08:40 nzbToRadarr.py
-rwxrwxrwx 1 abc users  7405 Aug 13 08:40 nzbToSickBeard.py
-rwxrwxrwx 1 abc users  3640 Aug 13 08:40 setup.py
drwxrwsrwx 2 abc users  4096 Oct  1 15:58 tests
-rwxrwxrwx 1 abc users 16783 Aug 13 08:40 TorrentToMedia.py
-rwxrwxrwx 1 abc users  3853 Aug 13 08:40 tox.ini

But it is not working. Sabnzbd log says the following
2019-10-01 15:51:00,652::INFO::[newsunpack:169] Running external script /scripts/nzbToMedia/nzbToMedia.py(/downloads/complete_tv/xxx, xxx.nzb, xxx, , tv, alt.binaries.ath, 0, )
2019-10-01 15:51:00,692::DEBUG::[newsunpack:198] Failed script /scripts/nzbToMedia/nzbToMedia.py, Traceback: 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/newsunpack.py", line 172, in external_processing
    startupinfo=stup, env=env, creationflags=creationflags)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

Why is it not possible to execute the nzbtomedia scripts?

**Comment by clinton-hall** [comment]
I think this comes back to a Docker/Sabnzbd question... 
I would look to see what user runs SABnzbd, as that is the user that will execute the script and needs to have execute permissions.

More importantly, make sure that user has execute permissions for 
`#!/usr/bin/env python`

**Comment by clinton-hall** [comment]
also make sure the user has permissions to write to scripts/nzbToMedia (the parent directory) as the script will try and create a log directory and write logs, as well as migrate the config files for nzbToMedia

**Comment by hapklaar** [comment]
Having the same issue as TS with sab in a docker and in this case the scripts in a mounted volume. /usr/bin/env can be executed by everyone and scripts folder is already at 777... As of yet unable to figure out why I'm getting an OSError: [Errno 13] Permission denied

**Comment by hapklaar** [comment]
Found out what my issue was... Volume containing the scripts was mounted with the noexec flag, causing execution of the python scripts to fail. After changing this to exec it started working :)

**Comment by clinton-hall** [comment]
@hapklaar 
Thanks for posting your solution... I haven't had a lot of experience with Docker so I find it hard to provide assistance... I really appreciate it when people post solutions :)
