### ISSUE TITLE
Cannot run TorrentToMedia.py getting PYTHON_EOL issue

### ISSUE THREAD

**Issue by alon24** [clinton-hall/nzbToMedia#1658]
Windwos 10 new install getting this issue
Python 3.8 (fresh new install)
master branch (also nightly)

```
D:\torrents\nzbToMedia>d:\torrents\nzbToMedia\TorrentToMedia.py "D:\torrents\torrentcomplete\tv|The.Flash.2014.S04E23.We.Are.The.Flash.720p.AMZN.WEB-DL.DD+5.1.H.264-ViSUM|tv|2036c5875903207d71fcd89ee304852728d521ac|"
Traceback (most recent call last):
  File "D:\torrents\nzbToMedia\TorrentToMedia.py", line 17, in <module>
    eol.check()
  File "D:\torrents\nzbToMedia\eol.py", line 98, in check
    raise_for_status(version, grace_period)
  File "D:\torrents\nzbToMedia\eol.py", line 118, in raise_for_status
    days_left = lifetime(version)
  File "D:\torrents\nzbToMedia\eol.py", line 69, in lifetime
    time_left = PYTHON_EOL[(major, minor)] - now
KeyError: (3, 8)

````

**Comment by clinton-hall** [comment]
I have just added Python3.8 in the Py3.8 branch.

Azure-Pipelines haven't added Python3.8 yet, so my CI tests can't tell me anything.

Are you able to test the Py3.8 branch to let me know if this works or if I need to add further support?

**Comment by alon24** [comment]
I moved to 3.7, and now things are working, sorry

**Comment by clinton-hall** [comment]
All good. I'll keep working on support for 3.8.

**Comment by clinton-hall** [comment]
Azure CI should support 3.8 soon:
https://github.com/microsoft/azure-pipelines-image-generation/issues/1317

**Comment by clinton-hall** [comment]
CI integration working. Py3.8 now merged to nightly.

**Comment by kcwebby** [comment]
Has this been merged into master yet?

**Comment by clinton-hall** [comment]
yes, this was merged to master some time ago. If you had an eol issue recently it was probably with python2.7? if so, I have just fixed this.
If you are still having this issue, please confirm your python version and provide some logs.
