### ISSUE TITLE
Exit(-1) Cannot run script /opt/sickchill/nzbToMedia/autoProcessMedia.cfg

### ISSUE THREAD

**Issue by chevell** [clinton-hall/nzbToMedia#1660]
**Describe the bug**
Cannot run this script, but certain its something I am missing. I replaced my old downloader box with a new system and reinstalled everything. I can't seem to get the new script to run. I was using the old method on the old box.

**Technical Specs**
1. Ubuntu 18.04
2. 2.7.15+ (default, Oct 7 2019, 17:39:04) [GCC 7.4.0] [UTF-8]
3. sabnzbdplus 2.3.9 [03c10dc]
4. SickChill v2019.06.28-1

**Expected behavior**
Sickchill sends the episode to sabnzbd, dowloads it and then exits with the error: Exit(-1) Cannot run script /opt/sickchill/nzbToMedia/autoProcessMedia.cfg

**Log**
I can't actually find the error in any logs. Could you point me to one?

**Comment by clinton-hall** [comment]
you shouldn't be trying to run /opt/sickchill/nzbToMedia/autoProcessMedia.cfg
this is the config file.

you should be running
/opt/sickchill/nzbToMedia/nzbToMedia.py

**Comment by chevell** [comment]
Well, i'm dumb. That was pretty obvious. Not sure how that got in there, and worse, how I didn't notice. Sorry!

So, i fixed that, and now I'm getting this:
Traceback (most recent call last):
File "/opt/sickchill/nzbToMedia/nzbToMedia.py", line 1004, in <module>
exit(main(sys.argv))
File "/opt/sickchill/nzbToMedia/nzbToMedia.py", line 837, in main
core.initialize(section)
File "/opt/sickchill/nzbToMedia/core/__init__.py", line 1010, in initialize
configure_migration()
File "/opt/sickchill/nzbToMedia/core/__init__.py", line 334, in configure_migration
if not config.migrate():
File "/opt/sickchill/nzbToMedia/core/configuration.py", line 254, in migrate
CFG_NEW.write()
File "/opt/sickchill/nzbToMedia/libs/common/configobj.py", line 2128, in write
with open(self.filename, 'wb') as h:
IOError: [Errno 13] Permission denied: u'/opt/sickchill/nzbToMedia/autoProcessMedia.cfg'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f0cd75e1f90>> ignored

Chmod on the whole directory to 777, what am I missing?

**Comment by clinton-hall** [comment]
This suggests that the autoProcessMedia.cfg is corrupt, has wrong permissions, or has some string that can't be read correctly.

try deleting autoProcessMedia.cfg, copy autoProcessMedia.cfg.spec to autoProcessMedia.cfg and then enter in your settings.

Be sure not to edit using notepad (in windows) as this introduces issues.

**Comment by chevell** [comment]
Thanks... making progress here. Its definitely permissions. I did a chmod to 777 and chown to sabnzbd user and group, but the script will not run manually without doing a sudo first. 

Any thoughts?

Thanks!

**Comment by chevell** [comment]
Figured it out. Not sure why it wouldn't run in /opt, but it runs just fine in /home/sabnzbd/.sabnzbd. Pulled from git into there and its working now. Thanks for everything!

**Comment by clinton-hall** [comment]
Sent from my Samsung Galaxy smartphone.

No worries. Glad you have it working.
