### ISSUE TITLE
Is there a file cleanup list within TorrentToMedia?  

### ISSUE THREAD

**Issue by rr0ss0rr** [clinton-hall/nzbToMedia#1662]
Not a problem, but I'm looking to remove .txt, .exe, .jpg, .png leftovers from post processing.  Using Transmission and do not see any options there. 

Thanks

**Comment by clinton-hall** [comment]
Not specifically an option to remove these... however, when using TorrentToMedia the script should only  link/move/copy/extract the following files to the Output Directory to be postprocessed.
```
[Extensions]
    compressedExtensions = .zip,.rar,.7z,.gz,.bz,.tar,.arj,.1,.01,.001
    mediaExtensions = .mkv,.avi,.divx,.xvid,.mov,.wmv,.mp4,.mpg,.mpeg,.vob,.iso,.m4v,.ts
    audioExtensions = .mp3, .aac, .ogg, .ape, .m4a, .asf, .wma, .flac
    metaExtensions = .nfo,.sub,.srt,.jpg,.gif
```
So as I see, you would want to remove .jpg from the metaExtensions... but .txt, .exe, and .png shouldn't be processed.

From there, it depends if you have options set to keep torrents (if we remove any files, this will break the seeding), and also the Force_clean options

So the following settings should remove all non-processed files once the files above have been processed.
```
[General]
    force_clean = 1

[Torrent]
    deleteOriginal = 1
    resume = 0
```

**Comment by rr0ss0rr** [comment]
Thanks ... I applied the changes.  I originally saw and tried  "force_clean = 1"  but with my NZBGet issues, the episode directory got cleaned along with the video.

**Comment by clinton-hall** [comment]
yes, force_clean does pose a risk of loosing a download if/when processing fails... once everything else is working, this risk is minimised.

you can leave force_clean off... deleteOriginal should take care of it when the processing is successful.

**Comment by rr0ss0rr** [comment]
Thanks again .. I changed force_clean off for now
