### ISSUE TITLE
OSerror, latest master

### ISSUE THREAD

**Issue by Boobybandit** [clinton-hall/nzbToMedia#1663]
Hi,

I just reinstalled NZBGet and Sickchill (previously sickrage) after a malware infection. However, can't get nzbtomedia working. Keep receiving errors. The OSerror was fixed last year, so don't know if that is really the issue.

**Technical Specs**
1. Running on Qnap TS853A - (x86_64)
2. Python version '....'Qpython 2.7.14
3. Download Client: NZBGet (v21)
4. Intended Media Management (SickChill, latest branch)

**Log**

INFO | Thu Oct 31 2019 22:44:07 | Collection The.Handmaids.Tale.S03E13.Mayday.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb added to history
-- | -- | --
ERROR | Thu Oct 31 2019 22:44:07 | Post-process-script nzbToMedia-master/nzbToSickBeard.py for The.Handmaids.Tale.S03E13.Mayday.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb failed (terminated with unknown status)
INFO | Thu Oct 31 2019 22:44:07 | nzbToSickBeard: OSError: [Errno 2] No such file or directory
INFO | Thu Oct 31 2019 22:44:07 | nzbToSickBeard: self.original_directory = os.getcwd() if original is None else original
INFO | Thu Oct 31 2019 22:44:07 | nzbToSickBeard: File "/share/CE_CACHEDEV1_DATA/.qpkg/NZBGet/scripts/nzbToMedia-master/cleanup.py", line 36, in __init__
INFO | Thu Oct 31 2019 22:44:07 | nzbToSickBeard: with WorkingDirectory(module_path()) as cwd:
INFO | Thu Oct 31 2019 22:44:07 | nzbToSickBeard: File "/share/CE_CACHEDEV1_DATA/.qpkg/NZBGet/scripts/nzbToMedia-master/cleanup.py", line 176, in clean
INFO | Thu Oct 31 2019 22:44:07 | nzbToSickBeard: cleanup.clean(cleanup.FOLDER_STRUCTURE)
INFO | Thu Oct 31 2019 22:44:07 | nzbToSickBeard: File "/share/CE_CACHEDEV1_DATA/.qpkg/NZBGet/scripts/nzbToMedia-master/nzbToMedia.py", line 680, in <module>
INFO | Thu Oct 31 2019 22:44:07 | nzbToSickBeard: import nzbToMedia

**Comment by clinton-hall** [comment]
Is there any logging before this? i.e. does it successfully cleanup and files or remove a folder?

This error suggests that the CWD does not exist, or the user that runs the script (the user that runs NZBGet) can't see that directory...

So check the permissions on 
`/share/CE_CACHEDEV1_DATA/.qpkg/NZBGet/scripts`
this needs to be set such that the user that runs NZBGet has read access.
 and 
`/share/CE_CACHEDEV1_DATA/.qpkg/NZBGet/scripts/nzbToMedia-master`
this to be set such that the user that runs NZBGet has read, and write access.

**Comment by Boobybandit** [comment]
Hi clinton. It was indeed a permission issue. Thanks a lot for your very specific answers. 

Awesome!
