### ISSUE TITLE
fault during ppc sabnzbd/sonarr

### ISSUE THREAD

**Issue by ikkeenjij36** [clinton-hall/nzbToMedia#1668]
**Describe the bug**

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) '....'
2. Python version '....'
3. Download Client (NZBget, SABnbzd, Transmission) '....'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) '....'

**Expected behavior**

**Log**
Please provide an extract, or full debug log that indicates the issue.
running on synolog dsm6.1
python:vers3
client sabnzbd
mm:sonarr
i have a issue when postprocessing,it works just fine but in sabnzbd i get this error after postproc 
`fatal: not a git repository (or any parent up to mount point /volume1)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Changing to directory: /volume1/scripts/nzbToMedia-master

-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error Code: 128

Directory is not a git repository

Force cleaning folder: libs
Skipping required subfolders [u'common', u'custom', u'py2', u'win']

Force cleaning folder: core
Skipping required subfolders [u'auto_process', u'extractor', u'plugins', u'utils']
Traceback (most recent call last):
File "/volume1/scripts/nzbToMedia-master/nzbToMedia.py", line 680, in <module>
cleanup.clean(cleanup.FOLDER_STRUCTURE)
File "/volume1/scripts/nzbToMedia-master/cleanup.py", line 205, in clean
force_clean_folder(folder, subfolders)
File "/volume1/scripts/nzbToMedia-master/cleanup.py", line 166, in force_clean_folder
raise Exception('Required subfolders missing:', missing)
Exception: (u'Required subfolders missing:', [u'plugins']) `
how do i get rid of this?

**Comment by clinton-hall** [comment]
was nzbToMedia installed via git?

nzbToMedia needs to be installed as (or have permissions set for full read/write by) the user that runs SABnzbd. ideally this is installed via git.

**Comment by ikkeenjij36** [comment]
I installed it from an old config after that i did a git clone and is has all permissions to read and write

**Comment by ikkeenjij36** [comment]
DDid remove the folder complete,did git clone for latest one,now the cleanup error is gone but heve something different now

`Changing to directory: /volume1/scripts/nzbToMedia

-- Cleaning bytecode --
Removing cleanup.pyc
Removing eol.pyc

Removing cleanup.pyc
Removing eol.pyc


-- Cleaning folders: [u'libs', u'core'] --
No folders to clean

Returning to directory:  /volume1/@appstore/sabnzbd/share/SABnzbd

-- Cleanup finished --

Traceback (most recent call last):
File "/volume1/scripts/nzbToMedia/nzbToMedia.py", line 1004, in <module>
exit(main(sys.argv))
File "/volume1/scripts/nzbToMedia/nzbToMedia.py", line 837, in main
core.initialize(section)
File "/volume1/scripts/nzbToMedia/core/__init__.py", line 1010, in initialize
configure_migration()
File "/volume1/scripts/nzbToMedia/core/__init__.py", line 334, in configure_migration
if not config.migrate():
File "/volume1/scripts/nzbToMedia/core/configuration.py", line 254, in migrate
CFG_NEW.write()
File "/volume1/scripts/nzbToMedia/libs/common/configobj.py", line 2128, in write
with open(self.filename, 'wb') as h:
IOError: [Errno 13] Permission denied: u'/volume1/scripts/nzbToMedia/autoProcessMedia.cfg'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f94e9854950>> ignored  `

**Comment by ikkeenjij36** [comment]
got it running now at least for headphones

**Comment by clinton-hall** [comment]
glad to hear.

**Comment by ikkeenjij36** [comment]
closing issue,advice...git clone the script instead of using old stuff :)
