### ISSUE TITLE
DB error: database is locked

### ISSUE THREAD

**Issue by ausghostdog** [clinton-hall/nzbToMedia#1670]
**Describe the bug**
2019-11-10 08:38:57 DB      ::MAIN: nzbtomedia.db: CREATE TABLE db_version (db_version INTEGER);
2019-11-10 08:39:17 WARNING ::MAIN: DB error: database is locked

Error above, trying to get this to work 
-rwxrwxrwx 1 root root     0 Nov 10 08:16 nzbtomedia.db
-rwxrwxrwx 1 root root 22148 Nov 10 08:38 autoProcessMedia.cfg

/tvshows/scripts/nzbToMedia$ sudo lsof http://nzbtomedia.dbCOMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF     NODE NAMEpython  17681  tim    8ur  REG   0,42        0 50495752 http://nzbtomedia.dbpython  17681  tim   11ur  REG   0,42        0 50495752 http://nzbtomedia.db

autoProcessMedia.cfg settings
[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[tv]]
        enabled = 1
        host = localhost
        port = 7071
        apikey = myapikeyhere
        username = ""
        password = ""

nzbToSickBeard has been left as default 
**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) '....'
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
NAS is a qnap ts-412
2. Python version 'v2.7' 

3. Download Client (NZBget, SABnbzd, Transmission) 'SABnbzd'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) '....'
Medusa
**Expected behavior**

For the system to work, when a show fails to download it tells medusa to grab a different version

**Log**
[nzbtomedia.log](https://github.com/clinton-hall/nzbToMedia/files/3827915/nzbtomedia.log)
Please provide an extract, or full debug log that indicates the issue.

**Comment by wazzaguy** [comment]
I had a similar issue, the issue seems to be permissions related.
The following may resolve your issue,
chmod -R 777 /tvshows/scripts/nzbToMedia

**Comment by ausghostdog** [comment]
required nolock on the mount for the drive
