### ISSUE TITLE
Script exit code is 255 - When SABnzbd fails to fetch .nzb

### ISSUE THREAD

**Issue by detobate** [clinton-hall/nzbToMedia#1673]
When SABnzbd fails to fetch the .nzb file from an indexer, it passes nzbToMedia the full indexer URL instead of local filename, and the input directory of _None_ instead of the local path.
This causes nzbToMedia to exit with error code 255, without returning a failure to SickChill.
SickChill is then left in a state of 'Snatched' instead of failed, so it never retries and requires manual intervention to reset the particular episode back to 'Wanted.

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) '**Ubuntu Bionic amd64**'
2. Python version '**2.7.15~rc1-1**'
3. Download Client (NZBget, SABnbzd, Transmission) '**SABnbzd**'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) '**SickChill**'

**Expected behavior**
nzbToMedia should gracefully return a failure to SickChill so that SickChill may retry an alternative .nzb

**Log**

[04:01:12] [INFO]::ENVIRONMENT: SAB_FINAL_NAME: _[REDACTED_INDEXER_URL]_

<snip>

[03:06:50] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/home/sabnzbdplus/nzbToMedia/nzbToSickBeard.py', '', '_[REDACTED_INDEXER_URL]_', '_[REDACTED_INDEXER_URL]_', '', 'tv', 'None', '3', '']
[03:06:50] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[03:06:50] [ERROR]::MAIN: The input directory:[] is the Default Download Directory. Please configure category directories to prevent processing of other media.
[03:06:50] [ERROR]::MAIN: A problem was reported in the /home/sabnzbdplus/nzbToMedia/nzbToSickBeard.py script.
pyc

**Comment by clinton-hall** [comment]
Can you please confirm that you have the following set in SABnzbd?

Config -> Switches -> Post-Process Only Verified Jobs (off)
Config -> Special -> empty_postproc (on)

When this special parameter is set,

```
 Do post-processing and run the user script even if nothing has been downloaded. 
 This is useful in combination with tools like SickBeard, for which running the 
 script on an empty or failed download is a trigger to try an alternative NZB. 
 Note that the "Status" parameter for the script will be -1. [0.7.5+ only]
```
I would expect the status to be -1, not 3.
I am also hoping this will pass the correct name through. But if this still only passes the URL, then I am going to have to make some changes to handle this scenario.

Does the redacted URL actually contain the NZB name? i.e. If I stripped off the leading path to the URL, would I be able to determine the TV show/episode for the URL?

**Comment by detobate** [comment]
Post-Process Only Verified Jobs is off
empty_postproc is however, off.

Interesting, OK, I didn't realise about that Special flag.  Perhaps this is an issue with SABnzb then?   Sounds like, with the empty_postproc flag unset, it shouldn't even be calling nzbToMedia?

Redacted URLs indeed pointed to the .nzb and included the API keys, although the filenames are obfuscated so it wouldn't be able to parse the show name or episode.

SABnzbd ver is 2.3.9 [03c10dc]

**Comment by clinton-hall** [comment]
I can only suggest turning on empty_postproc to see if that makes any difference. From there I can look to see what may need to change.

**Comment by detobate** [comment]
Seems to be the same with empty_postproc on.

**Comment by clinton-hall** [comment]
ok, I've had another look at this:

you have 
```
[General]
    safe_mode = 1

[Nzb]
    default_downloadDirectory = ""
```

So when no directory is passed, the script thinks the directory (null) is protected and therefore stops processing.

I think by either setting ` safe_mode = 0` or setting the default directory (set as the root download, non category, directory) this will allow the script to go further.

the script should ask SABnzbd for some more details, including the nzoid (the download-ID) then when SickChill is passed the download ID it should match this and correctly mark as failed.

I'm not 100% sure given the input parameters if his will be able to match everything and correctly mark as failed, or if there is any update required to the api etc, but I'm keen to see where this gets to.

**Comment by detobate** [comment]
OK, we got a bit further now with safe mode off, as expected:

`Traceback (most recent call last):
File "/home/sabnzbdplus/nzbToMedia/nzbToSickBeard.py", line 273, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/home/sabnzbdplus/nzbToMedia/nzbToMedia.py", line 990, in main
download_id='', failure_link=''.join(args[8:]))
File "/home/sabnzbdplus/nzbToMedia/nzbToMedia.py", line 853, in process
result = tv.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "/home/sabnzbdplus/nzbToMedia/core/auto_process/tv.py", line 99, in process
os.makedirs(dir_name)  # Attempt to create the directory
File "/usr/lib/python2.7/os.py", line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f3d399ab110>> ignored`

**Comment by clinton-hall** [comment]
ok, I see why this failed... we try to create the empty directory (which fails)

can you update to `SABnzbd-empty-1` branch and test the changes I just made there?

the main issue now is that I believe the script may still have an issue as this was done because sickchill would only process something (even failed) if the directory exists... but they may have fixed this.

the other alternative would be to create  a new "failed" directory and pass this to SickChill to process.... so I can do that this this doesn't work.

**Comment by detobate** [comment]
OK on the `SABnzbd-empty-1` branch now, and it still exits with 255 without updating SickChill.

**Comment by detobate** [comment]
With safe mode off nzbToMedia exits with code 1, tries to callback to Sickchill, but the episodes is still left as Snatched.

```[10:41:39] [INFO]::MAIN: Calling SickBeard:tv to post-process:https://**REDACTED**/api?t=get&id=**REDACTED**&apikey=**REDACTED**
[10:41:39] [DEBUG]::SERVER: Attempting to connect to server at https://**REDACTED**:8081
[10:41:39] [DEBUG]::SERVER: Server responded at https://**REDACTED**:8081
[10:41:39] [INFO]::MAIN: Attempting to auto-detect tv fork
[10:41:39] [INFO]::MAIN: SickBeard:tv fork auto-detection found custom params {'force_next': None, 'delete_on': None, 'force': None, 'proc_dir': None, 'is_priority': None, 'failed': None, 'process_method': None}
[10:41:39] [INFO]::MAIN: SickBeard:tv fork set to custom
[10:41:39] [WARNING]::SICKBEARD: No media files found in directory . Processing this as a failed download
[10:41:39] [POSTPROCESS]::SICKBEARD: FAILED: The download failed. Sending 'failed' process request to custom branch
[10:41:39] [DEBUG]::SICKBEARD: Opening URL: https://**REDACTED**:8081/home/postprocess/processEpisode with params: {'force_next': 1, 'delete_on': 1, 'proc_dir': '', 'failed': 1, 'quiet': 1, 'nzbName': 'https://**REDACTED**/api?t=get&id=**REDACTED**&apikey=**REDACTED**'}
[10:41:39] [POSTPROCESS]::SICKBEARD: <!DOCTYPE html>
[10:41:39] [POSTPROCESS]::SICKBEARD: <html lang="">
[10:41:39] [POSTPROCESS]::SICKBEARD:     <head>

<snip Sickchill's PostProcessing UI html>

[10:41:39] [ERROR]::MAIN: A problem was reported in the /home/sabnzbdplus/nzbToMedia/nzbToSickBeard.py script.
Changing to directory: /home/sabnzbdplus/nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /usr/bin

-- Cleanup finished --

SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!

```

**Comment by detobate** [comment]
Guessing Sick Chill needs the actual nzb file to know which ep to mark as failed?

**Comment by clinton-hall** [comment]
yeah, so I'm thinking what I need to do is create a new option for `Failed_Directory`
so that you specify where this should be, then the script can create a directory named after the download name, within that Failed_Directory location and pass that to SickChill....

the other option would be to simply make the directory inside of nzbToMedia.... but that gets messy with permissions and shares etc.

**Comment by detobate** [comment]
Hrm, but does the script ever know the actual (non-obfuscated) nzb filename in order for it to create that dir?

AFAICT it's always passed the API URL with the nzb ID rather than the filename.  Or is this entirely Indexer-dependent?

**Comment by clinton-hall** [comment]
ah... in this case, unless we can somehow call sickchill api to match that nzb ID back to a release... not much we can do!

**Comment by detobate** [comment]
Was worried about that.  :/

Perhaps we can raise a feature request with Sick Chill, to match indexer urls?  I mean, that's what they're passing to the downloader, right, so it makes sense they should?

**Comment by clinton-hall** [comment]
you can always ask...

**Comment by brianjmurrell** [comment]
> Perhaps we can raise a feature request with Sick Chill, to match indexer urls?

Did this happen?

Did anything more with this issue happen in general to handle the failed-NZB download issue.
