### ISSUE TITLE
Removal of .pyc files everytime during post-processing.

### ISSUE THREAD

**Issue by oppsig** [clinton-hall/nzbToMedia#1674]
**Describe the bug**
Getting a lot of INFO messages about removal of .pyc files everytime i post-process tvshows.
I've tried this is nzbtomedia git folder:

> find . -name "*.pyc" -exec rm -f {} \;
> git clean -fd
> git pull

It removes the files but they always comes back.
Should i move to python 3.8 maybe?

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) 'Ubuntu 18.04'
2. Python version 'Python 2.7.15+'
3. Download Client (NZBget, SABnbzd, Transmission) 'nzbget'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) 'sonarr'

**Expected behavior**
Not removal of .pyc files.

**Log**
[Logfile](https://termbin.com/bq08d)

**Comment by clinton-hall** [comment]
regardless of Python version, every time the scripts run they will create .pyc files.

There was an issue with updating, that required adding the cleanup. This is messy in the logs. In nightly I believe the logging has been tidied up.

I hope to review the need for this cleanup soon.

**Comment by oppsig** [comment]
Ok, thanks. Speaking of python versions. Do you think it would be possible to rename nzbtomedia.py from 
.py ->.py3 then shell override .py3 files to be able to run only nzbtomedia using python3 and not all nzbget addons? Or will that cause issues with all your imported libs. 

Anyway thanks for this project, been following for many years 😊
