### ISSUE TITLE
nzbToSickbeard fails with NZBGet (linuxserver docker) on recent nzbToMedia

### ISSUE THREAD

**Issue by mannibis** [clinton-hall/nzbToMedia#1675]
**Describe the bug**
I (stupidly) updated nzbToMedia via 'git pull' for for the first time in over a year on my QNAP. Post-processing in SickChill no longer works and I had to checkout HEAD all the way back to 493bfe3a329ed221e3edba5cbb7431ebe2608fa4 (Bump version: 11.7.4 → 11.8.0) for nzbToMedia to work again with my install. One thing I have noticed is python3 support. However, linuxserver's latest NZBGet docker container doesn't seem to have python3 installed at all. I looked for it in /usr/bin and I do not believe it's there. Does that mean that that nzbToMedia will not work anymore with 2.7.16? Anyway, see logs below.

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc): QNAP Docker (linuxserver/nzbget:latest)
2. Python version 2.7.16 (there is no python3 installed in this docker container)
3. Download Client (NZBget, SABnbzd, Transmission): NZBGet v21 
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) Sickchill (latest)

**Expected behavior**
After successful download in NZBGet, nzbToSickbeard triggers post-processing in SickChill

**Log**
ERROR | Sun Dec 01 2019 21:28:07 | Post-process-script nzbToMedia/nzbToSickBeard.py for Room.104.S03E12.The.Specimen.Collector.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb failed (terminated with unknown status)
-- | -- | --
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f2023af3ed0>> ignored
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: AttributeError: 'module' object has no attribute 'InitialSchema'
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: main_db.upgrade_database(main_db.DBConnection(), databases.InitialSchema)
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: File "/downloads/NZB-QNAP/docker/scripts/nzbToMedia/core/__init__.py", line 346, in initialize
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: core.initialize(section)
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: File "/downloads/NZB-QNAP/docker/scripts/nzbToMedia/nzbToMedia.py", line 780, in main
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: result = nzbToMedia.main(sys.argv, section)
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: File "/downloads/NZB-QNAP/docker/scripts/nzbToMedia/nzbToSickBeard.py", line 264, in <module>
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: Traceback (most recent call last):
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: -- Cleanup finished --
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: Returning to directory: /run/s6/services/nzbget
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: If errors occur, manual cleanup may be required.
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: -- Cleaning folders: ['libs', 'core'] --
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: If errors occur, manual cleanup may be required.
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
INFO | Sun Dec 01 2019 21:28:07 | nzbToSickBeard: -- Cleaning bytecode --
INFO | Sun Dec 01 2019 21:28:03 | nzbToSickBeard: Changing to directory: /downloads/NZB-QNAP/docker/scripts/nzbToMedia
INFO | Sun Dec 01 2019 21:28:03 | Executing post-process-script nzbToMedia/nzbToSickBeard.py for Room.104.S03E12.The.Specimen.Collector.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb

**Comment by clinton-hall** [comment]
in your docker open a command line terminal (e.g. using putty or ssh) and change to your nzbToMedia directory, git pull to latest then run:

```
python -c "import cleanup; cleanup.force_clean_folder('libs', cleanup.FOLDER_STRUCTURE['libs'])"
python -c "import cleanup; cleanup.force_clean_folder('core', cleanup.FOLDER_STRUCTURE['core'])"
```

does this then get everything working again on the latest?

**Comment by mannibis** [comment]
Hey Clinton! Thanks for your help. It must be 2-3 years since I've last bothered you with nzbToMedia problems :)

So, I checked out master branch again and git pulled to latest. Then did the commands above and that seemed to be successful. Here's the output for that:

`Skipping required subfolders [u'common', u'custom', u'py2', u'win']
Removing libs/babelfish
Removing libs/beets
Removing libs/bs4
Removing libs/chardet
Removing libs/concurrent
Removing libs/configobj
Removing libs/dateutil
Removing libs/dogpile
Removing libs/enzyme
Removing libs/guessit
Removing libs/mutagen
Removing libs/pysrt
Removing libs/rebulk
Removing libs/requests
Removing libs/stevedore
Removing libs/subliminal
Removing libs/unidecode
Removing libs/yaml
`
`Skipping required subfolders [u'auto_process', u'extractor', u'plugins', u'utils']
Removing core/autoProcess
Removing core/databases
Removing core/linktastic
Removing core/synchronousdeluge
Removing core/transcoder
Removing core/transmissionrpc
Removing core/utorrent
`
And running the script works now! I still get some weird messages though. Maybe you can shine some light on what those are? Logs are below. But everything works fine on the post-processing end. Thanks again.

`
INFO | Mon Dec 02 2019 10:35:08 | Collection Silicon.Valley.S06E02.Blood.Money.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb added to history
-- | -- | --
INFO | Mon Dec 02 2019 10:35:08 | Post-process-script nzbToMedia/nzbToSickBeard.py for Silicon.Valley.S06E02.Blood.Money.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb successful
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: SickBeard: Successfully post-processed Silicon.Valley.S06E02.Blood.Money.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb!
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: -- Cleanup finished --
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: Returning to directory: /run/s6/services/nzbget
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: If errors occur, manual cleanup may be required.
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: -- Cleaning folders: [u'libs', u'core'] --
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: If errors occur, manual cleanup may be required.
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: -- Cleaning bytecode --
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: [15:35:08] [INFO]::MAIN: The /downloads/NZB-QNAP/docker/scripts/nzbToMedia/nzbToSickBeard.py script completed successfully.
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: [15:35:08] [INFO]::MAIN: Deleting /downloads/Downloads/Completed/Silicon.Valley.S06E02.Blood.Money.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
INFO | Mon Dec 02 2019 10:35:08 | nzbToSickBeard: [15:35:08] [INFO]::CLEANDIR: Doing Forceful Clean of /downloads/Downloads/Completed/Silicon.Valley.S06E02.Blood.Money.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: FLATTEN: Flattening directory: /downloads/Downloads/Completed/Silicon.Valley.S06E02.Blood.Money.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: SickBeard:tv fork set to SickChill-api
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: SickBeard:tv fork auto-detection successful ...
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: Attempting to auto-detect tv fork
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: Calling SickBeard:tv to post-process:Silicon.Valley.S06E02.Blood.Money.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: Auto-detected SECTION:SickBeard
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: Script triggered from NZBGet Version 21.0.
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: #########################################################
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: #########################################################
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [WARNING]::MAIN: Failed to locate ffmpeg. Transcoding disabled!
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [WARNING]::MAIN: Failed to locate par2. Repair and rename using par files will not be possible!
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: nzbToMedia Version:12.1.01 Branch:master (Linux 4.2.8)
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: No update needed
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: Checking if git needs an update
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: Checking database structure...
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [WARNING]::MAIN: Please upgrade to a more recent Python version.
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: [15:34:59] [INFO]::MAIN: Python v2.7 will reach end of life in 30 days.
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: warnings.warn(msg, LifetimeWarning)
INFO | Mon Dec 02 2019 10:34:59 | nzbToSickBeard: /downloads/NZB-QNAP/docker/scripts/nzbToMedia/eol.py:146: LifetimeWarning: Python 2.7 is no longer supported.
INFO | Mon Dec 02 2019 10:34:57 | nzbToSickBeard: Changing to directory: /downloads/NZB-QNAP/docker/scripts/nzbToMedia
INFO | Mon Dec 02 2019 10:34:57 | Executing post-process-script nzbToMedia/nzbToSickBeard.py for Silicon.Valley.S06E02.Blood.Money.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
`
