### ISSUE TITLE
Install type check doesn't work as submodule

### ISSUE THREAD

**Issue by brianjmurrell** [clinton-hall/nzbToMedia#1677]
The install type checking doesn't work properly when the install is a submodule:

https://github.com/clinton-hall/nzbToMedia/blob/e165bbcefc9686c333978f79e72c0e3e8cba9c56/core/version_check.py#L56

Submodules are recorded with `./.git` being a file with a reference to the parent module in it, not as a directory.

**Comment by clinton-hall** [comment]
Does this also relate to #1678 or are these separate?

so if I understand you are saying to support sub-modules I'd need

`if os.path.isdir(os.path.join(core.APP_ROOT, u'.git')) or os.path.isfile(os.path.join(core.APP_ROOT, u'.git')):`

or even just `if os.path.exists(os.path.join(core.APP_ROOT, u'.git')):`

**Comment by brianjmurrell** [comment]
> or even just if os.path.exists(os.path.join(core.APP_ROOT, u'.git')):

Is what I did here.  I suppose it could be a socket or named pipe but that seems a diminishingly small possibility.
