### ISSUE TITLE
transcoder log location

### ISSUE THREAD

**Issue by brianjmurrell** [clinton-hall/nzbToMedia#1684]
**Describe the bug**
Transcoder output log is in `$PWD`, but perhaps that is not where the user wants to write them.

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) 'Linux'
1. Python version '2.7.5' (yes, I know it's EOL in 28 days -- it's the python that CentOS 7 provides)
1. Download Client (NZBget, SABnbzd, Transmission) 'SABnzbd'
1. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) 'SickChill'

**Expected behavior**
Ability to direct location of transcoder output log.

**Log**
N/A

Currently I have this hack in place to write the logs to /var/tmp/ instead:

```patch
diff --git a/core/transcoder.py b/core/transcoder.py
index f0da8dd..d8cd64c 100644
--- a/core/transcoder.py
+++ b/core/transcoder.py
@@ -928,6 +928,7 @@ def transcode_directory(dir_name):
         logger.info('Transcoding video: {0}'.format(newfile_path))
         print_cmd(command)
         result = 1  # set result to failed in case call fails.
+       os.chdir("/var/tmp/")
         try:
             if isinstance(file, string_types):
                 proc = subprocess.Popen(command, stdout=bitbucket, stderr=subprocess.PIPE)
@@ -969,6 +970,8 @@ def transcode_directory(dir_name):
                     pass
         else:
             logger.error('Transcoding of video to {0} failed with result {1}'.format(newfile_path, result))
+            if "-report" in core.GENERALOPTS:
+                logger.error("Look for report in {0}".format(os.getcwd()))
         # this will be 0 (successful) it all are successful, else will return a positive integer for failure.
         final_result = final_result + result
     if core.MOUNTED: # In case we mounted an .iso file, unmount here.
```

Clearly that's an ugly hack though.  An option to formalise this kind of thing would be interesting.

**Comment by clinton-hall** [comment]
there are 2 ways this could be handled.

1. As you have done, but simply have a config option for `FFMPEG Path = `
    - This would then chdir to that path, or
    - Set that path in the environment variable `FFREPORT`
2. You could just set FFREPORT environment as a global variable so that ALL ffmpeg reports dump in the same location (for all services).
   - This wouldn't require any code change or interfere with git updating.

**Comment by brianjmurrell** [comment]
I'm not sure `FFREPORT` can be just a directory, can it?  My experiments here seem to indicate that setting it to just a directory causes an error:

```
Failed to open report "/var/tmp/": Is a directory
```
