### ISSUE TITLE
libcrypto warning in the log

### ISSUE THREAD

**Issue by Sarcas666** [clinton-hall/nzbToMedia#1685]
**Describe the bug**
Getting a warning in the log about libcrypto. The script continues to work as expected though. 

**Technical Specs**
1. Running on MacOS 10.15.2
2. Python version 2.7
3. Download Clients  SABnbzd, Transmission)
4. Intended Media Management  Radarr, Medusa)

**Expected behavior**
The scripts function as expected, but the warning states this will fail in the future.

**Log**
Please provide an extract, or full debug log that indicates the issue.

`Changing to directory: /Applications/nzbToMedia

-- Cleaning bytecode --
Removing libs/common/babelfish/converters/countryname.pyc
Removing libs/common/babelfish/converters/name.pyc
Removing libs/common/dogpile/cache/backends/file.pyc
Removing libs/common/subliminal/converters/shooter.pyc

Removing libs/common/babelfish/converters/countryname.pyc
Removing libs/common/babelfish/converters/name.pyc
Removing libs/common/dogpile/cache/backends/file.pyc
Removing libs/common/subliminal/converters/shooter.pyc

-- Cleaning folders: [u'libs', u'core'] --
No folders to clean

Returning to directory:  /Applications/SABnzbd.app/Contents/Resources

-- Cleanup finished --

WARNING: Executing a script that is loading libcrypto in an unsafe way. This will fail in a future version of macOS. Set the LIBRESSL_REDIRECT_STUB_ABORT=1 in the environment to force this into an error.
[19:20:40] [INFO]::MAIN: Loading config from [/Applications/nzbToMedia/autoProcessMedia.cfg]
[19:20:40] [INFO]::ENVIRONMENT: SAB_SCRIPT: nzbToSickBeard.py`

**Comment by clinton-hall** [comment]
do you get the same warning if you run the script with python3?

**Comment by Sarcas666** [comment]
I haven't managed to get the scripts working with python 3 yet. I am talking about it with you in "Deprecate Python 2.7 #1533". I'll report back if I get python 3 working.
