### ISSUE TITLE
python2.7 problem

### ISSUE THREAD

**Issue by ikkeenjij36** [clinton-hall/nzbToMedia#1687]
**Describe the bug**

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) '....'
2. Python version '....'
3. Download Client (NZBget, SABnbzd, Transmission) '....'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) '....'

**Expected behavior**

**Log**
Please provide an extract, or full debug log that indicates the issue.
Hi all as of 2020 python.27 is niot supported anymore,wen i want to remove 2.7 from my syno box it says all programs shoulod be deleted to remove 2.7
i also got python 3 installed
is there anyway to update with not to much hassle on my syno box?

this is what i get after running the script

`Please use a newer version of Python.
Python End-of-Life for current versions:
v2.7 in    0 days
v3.5 in  256 days
v3.6 in  722 days
v3.7 in 1273 days
Python 2.7 is no longer supported.`
using ds3617
with sabnzbd radar sonar  headphones

**Comment by walderston** [comment]
sabnzbd still uses python 2.7 which is why it can't be removed. 

For mine, I've created a (2) file/s called `nzbToSickBeard.sh` / `nzbToRadarr.sh`
which contain the below. I've updated sabnzbd to call the `.sh` files. 
```
#!/bin/bash
python3 /Applications/nzbToMedia/nzbToSickBeard.py "$@"
```
```
#!/bin/bash
python3 /Applications/nzbToMedia/nzbToRadarr.py "$@"
```

**Comment by ikkeenjij36** [comment]
> sabnzbd still uses python 2.7 which is why it can't be removed.
> 
> For mine, I've created a (2) file/s called `nzbToSickBeard.sh` / `nzbToRadarr.sh`
> which contain the below. I've updated sabnzbd to call the `.sh` files.
> 
> ```
> #!/bin/bash
> python3 /Applications/nzbToMedia/nzbToSickBeard.py "$@"
> ```
> 
> ```
> #!/bin/bash
> python3 /Applications/nzbToMedia/nzbToRadarr.py "$@"
> ```

I am using the script nzbto media.py for processing all
How and where do i put the files you created so sabnzbd calls on python 3.x cause i also have python 3 installed on my syno
thnx in advance

**Comment by walderston** [comment]
The same as I’ve done it with just nzbtomedia.sh instead.
`#!/bin/bash
python3 /~PATH TO ~/nzbToMedia/nzbtomedia.py "$@" ` and update sabnzbd to use the .sh file

**Comment by LennyM8472** [comment]
Hi,

thanks for the solution, but somehow the new file won't be listed in the categories scirpt selection. They are definately located in the correct nzbToMedia app/script folder.

**Comment by walderston** [comment]
@LennyM8472 check the permissions on the new .sh file. I had to change them to get it to show within SAB

**Comment by LennyM8472** [comment]
> @LennyM8472 check the permissions on the new .sh file. I had to change them to get it to show within SAB
> 
> Also mine shows at the bottom of the list

Great worked, has to be set to 777 (all read write Privileges).

Now I will test, a download and if the script runs.

Thanks

**Comment by LennyM8472** [comment]
in case someone has a Qnap setup with Qpython3 this is the code for the .sh files - in this case for nzbToMedia

`#!/bin/bash
/opt/QPython3/bin/python3 SCRIPTLOCATION/nzbToMedia.py "$@"`

**Comment by ikkeenjij36** [comment]
> The same as I’ve done it with just nzbtomedia.sh instead.
> `#!/bin/bash python3 /~PATH TO ~/nzbToMedia/nzbtomedia.py "$@" ` and update sabnzbd to use the .sh file

done what you said and i get this as result after running script
`Exit(2) python3: can't open file '/~Volmue1/scripts/nzbToMedia/': [Errno 2] No such file or directory`

**Comment by walderston** [comment]
Assuming your `nzbToMedia.py` is located in `/~Volmue1/scripts/nzbToMedia/` ?

Does the .sh file contain /~Volmue1/scripts/nzbToMedia/nzbToMedia.py or just /~Volmue1/scripts/nzbToMedia/ ? You need to call the py script from the sh script.

**Comment by ikkeenjij36** [comment]
This is exactly the path nzbToMedia is placed in,i get this error after starting the script:
'ScriptExit(2) python3: can't open file '/Volume1/scripts/nzbToMedia/nzbToMedia.py': [Errno 2] No such file or directory`

**Comment by LennyM8472** [comment]
> This is exactly the path nzbToMedia is placed in,i get this error after starting the script:
> 'ScriptExit(2) python3: can't open file '/Volume1/scripts/nzbToMedia/nzbToMedia.py': [Errno 2] No such file or directory`
> 
> This is how the nzbToMedia.sh file looks like:
> `#!/bin/bash python3 /Volume1/scripts/nzbToMedia/nzbToMedia.py "$@"`

There must be a really simpler error in your script.
Check exactly the paths - best try to run and check if all parts of the script run on ssh/terminal.
Currently your script does not find the file

**Comment by walderston** [comment]
@ikkeenjij36 as @LennyM8472 mentions, there must be a typo with your file location somewhere. 

In SABNzbd, go to Settings -> Folders and find 'Scripts Folder'. Use that location plus `/nzbToMedia.py`

**Comment by PeterPan669** [comment]
2 comments on the above;

1. Ikkeenjij, is your issue related to the fact u write Volume1 with a capital V? Remember it is cap sensitive.
Also, I noticed Sab only showed the .sh files I created the first time. After saving the config, they no longer appear in the dropdown and the setting is back to Default. However, it does call them. You can confirm by opening op config.ini.

2. Walderston, I've done / tried the exact same approach, however, I still get the 'Python2.7 deprecated error'  with the script. It seems Sab is forcing the script to run under Python2.7 nonetheless. How did you manage to fix that?

**Comment by PeterPan669** [comment]
EDIT; Apparently, pressing 'retry' within Sab also retries the exact same older command, including the older script. I'm testing it now with a new api call from Medusa; I'll post back with the results.

**Comment by LennyM8472** [comment]
> EDIT; Apparently, pressing 'retry' within Sab also retries the exact same older command, including the older script. I'm testing it now with a new api call from Medusa; I'll post back with the results.

yes, that's what I was going to say next. You have to do a complete new download, as the new download will only have the new script file attached to it

**Comment by fbruffaert** [comment]
I don't like the idea of making nzbToMedia scripts fail if python version installed on the client is not supported anymore. It not like python will stop working after the end of the support.

**Comment by ikkeenjij36** [comment]
> 2 comments on the above;
> 
> 1. @ikkeenjij36, is your issue related to the fact u write Volume1 with a capital V? Remember it is cap sensitive.
> 2. @walderston, I've done / tried the exact same approach, however, I still get the 'Python 2.7 is no longer supported' error  with the script.
> 
> The content is:
> #!/bin/bash
> python3 /volume1/downloads/SCRIPTS/nzbToSickBeard.py "$@"
> 
> From CLI it runs fine, but SabNZBD forces it to run under Python2.7, inline with what Clinton Hall mentions in [#1533 (comment)](https://github.com/clinton-hall/nzbToMedia/issues/1533#issuecomment-565746099).
> 
> However, from your comment I get the impression that you managed to overcome this. How did you do that?
> 
> -- Running this from a Synology btw.

I got the script running without errors only now it just keeps running with rinnun nzbToMedia.sh and there is no sight of returning with no errors?
So confused now

**Comment by PeterPan669** [comment]
@ikkeenjij36, I just ran into your issue (nice: can't execute '/volume1/downloads/SCRIPTS/nzbToSickBeard.sh': No such file or directory).
This is how I fixed it;

I noticed the permissions on the file we're wrong, but no matter what I did, it wouldn't resolve;
- I tried running chmod 777 against the file. This would set all R/RW, but it still gave the error.
- I tried pushing the permissions from the Synology console, still gave the error.
- I tried pushing ownership for the sc-sabnzbd on the entire directory and files, still gave me the error. 
Most likely this is due to my lack of knowledge on Linux / Unix, but I kept seeing that it said 'users' on a spot where the other (working) files would say 'sabnzbd'. See attachment "error1".
![error1](https://user-images.githubusercontent.com/59241040/71646018-0f0d1200-2ce1-11ea-9deb-c2bb11406af7.JPG)

So, this is how I fixed it (not knowing any better);
- From CLI, run 'cp -avr nzbToSickBeard.py nzbToSickBeard.sh';
- Then, edit the nzbToSickBeard.sh file to have the correct content: 
#!/bin/bash
python3 /volume1/downloads/SCRIPTS/nzbToSickBeard.py "$@"

This time, the file permissions looked like this (error2):
![error2](https://user-images.githubusercontent.com/59241040/71646037-4d0a3600-2ce1-11ea-998a-2a61d803d0e6.JPG)

And Voilà:
![fix1](https://user-images.githubusercontent.com/59241040/71646045-657a5080-2ce1-11ea-972b-886360ea389e.JPG)

For me, this issue has been resolved. Thanks all, hope the above will help others!

**Comment by ikkeenjij36** [comment]
For me still probs with the script
for now it is this error
`2020-01-01 22:12:51 INFO    ::MAIN: Loading config from [/volume1/scripts/nzbToMedia/autoProcessMedia.cfg]
2020-01-01 22:12:51 INFO    ::MAIN: Python v3.5 will reach end of life in 256 days.
2020-01-01 22:12:51 WARNING ::MAIN: Please upgrade to a more recent Python version.
2020-01-01 22:12:51 INFO    ::MAIN: Checking database structure...
2020-01-01 22:12:51 INFO    ::MAIN: Checking if git needs an update
2020-01-01 22:12:53 INFO    ::MAIN: There is a newer version available (you're 14 commits behind)
2020-01-01 22:12:53 INFO    ::MAIN: Auto-Updating nzbToMedia, Please wait ...
2020-01-01 22:12:56 ERROR   ::MAIN: Update failed, not restarting. Check your log for more information.
2020-01-01 22:12:56 INFO    ::MAIN: nzbToMedia Version:46b2e8998ce7c0e4b853272f0bdb06a558852c81 Branch:master (Linux 3.10.102)
2020-01-01 22:12:56 WARNING ::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
2020-01-01 22:12:56 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ..`
still waiting for the  first succesful run of the script

**Comment by suprawsmninja** [comment]
It's not like python 2.7 will stop working, it's just no longer maintained.
There is no point in nzbToMedia working with 3 when SABnzb only runs on 2.7

Don't bother messing around, simply edit the `eol.py` file in your nzbToMedia directory, give your self another 100 days.

change
`def check(version=None, grace_period=0):`
to
`def check(version=None, grace_period=100):`
 
and 
`def raise_for_status(version=None, grace_period=0):`
to
`def raise_for_status(version=None, grace_period=100):`

**Comment by djskippy50** [comment]
> It's not like python 2.7 will stop working, it's just no longer maintained.
> There is no point in nzbToMedia working with 3 when SABnzb only runs on 2.7
> 
> Don't bother messing around, simply edit the `eol.py` file in your nzbToMedia directory, give your self another 100 days.
> 
> change
> `def check(version=None, grace_period=0):`
> to
> `def check(version=None, grace_period=100):`
> 
> and
> `def raise_for_status(version=None, grace_period=0):`
> to
> `def raise_for_status(version=None, grace_period=100):`

Thank you. This is exactly what I needed.

**Comment by tchirou** [comment]
> It's not like python 2.7 will stop working, it's just no longer maintained.
> There is no point in nzbToMedia working with 3 when SABnzb only runs on 2.7
> 
> Don't bother messing around, simply edit the `eol.py` file in your nzbToMedia directory, give your self another 100 days.
> 
> change
> `def check(version=None, grace_period=0):`
> to
> `def check(version=None, grace_period=100):`
> 
> and
> `def raise_for_status(version=None, grace_period=0):`
> to
> `def raise_for_status(version=None, grace_period=100):`

The best post of the year so far :D !!!

**Comment by drallgood** [comment]
See also https://github.com/sabnzbd/sabnzbd/issues/1203 for the status of the Py3 migration

**Comment by XxUnkn0wnxX** [comment]
this guide somewhat helps: https://opensource.com/article/19/5/python-3-default-mac
although on Catalina pyenv doesnt want to comile anything to many issues like pyexpat module missing

just run `ln -sf /usr/local/bin/python3 /usr/local/bin/python`

and if using hydra via wrapper just use launchd to run it with python2 enviroment variable set.

**Comment by mannibis** [comment]
Linuxserver.io's docker container for NZBGet still doesn't include python3. I believe there is a pull request pending that will add it to the image but as of now, I have had to edit eol.py to increase the grace period as the user above pointed out.

**Comment by ikkeenjij36** [comment]
> It's not like python 2.7 will stop working, it's just no longer maintained.
> There is no point in nzbToMedia working with 3 when SABnzb only runs on 2.7
> 
> Don't bother messing around, simply edit the `eol.py` file in your nzbToMedia directory, give your self another 100 days.
> 
> change
> `def check(version=None, grace_period=0):`
> to
> `def check(version=None, grace_period=100):`
> 
> and
> `def raise_for_status(version=None, grace_period=0):`
> to
> `def raise_for_status(version=None, grace_period=100):`

Thanks for your tempory solution,now all works almost fine this resolved the pyhtom problem

Now a small other thing  maybe someone can help me too with this one

`2020-01-01 22:32:57 DEBUG   ::MAIN: InitialSchema upgrade not required
2020-01-01 22:32:57 DEBUG   ::MAIN: Checking if we can use git commands: git version
2020-01-01 22:32:57 DEBUG   ::MAIN: Executing git version with your shell in /volume1/scripts/nzbToMedia
2020-01-01 22:32:57 DEBUG   ::MAIN: git output: git version 2.19.2
2020-01-01 22:32:57 DEBUG   ::MAIN: git version : returned successful
2020-01-01 22:32:57 DEBUG   ::MAIN: Using: git
2020-01-01 22:32:57 DEBUG   ::MAIN: Executing git symbolic-ref -q HEAD with your shell in /volume1/scripts/nzbToMedia
2020-01-01 22:32:57 DEBUG   ::MAIN: git output: refs/heads/master
2020-01-01 22:32:57 DEBUG   ::MAIN: git symbolic-ref -q HEAD : returned successful
2020-01-01 22:32:57 INFO    ::MAIN: Checking if git needs an update
2020-01-01 22:32:57 DEBUG   ::MAIN: Executing git rev-parse HEAD with your shell in /volume1/scripts/nzbToMedia
2020-01-01 22:32:57 DEBUG   ::MAIN: git output: 46b2e8998ce7c0e4b853272f0bdb06a558852c81
2020-01-01 22:32:57 DEBUG   ::MAIN: git rev-parse HEAD : returned successful
2020-01-01 22:32:57 DEBUG   ::MAIN: Executing git fetch origin with your shell in /volume1/scripts/nzbToMedia
2020-01-01 22:32:58 DEBUG   ::MAIN: git output: 
2020-01-01 22:32:58 DEBUG   ::MAIN: git fetch origin : returned successful
2020-01-01 22:32:58 DEBUG   ::MAIN: Executing git rev-parse --verify --quiet '@{upstream}' with your shell in /volume1/scripts/nzbToMedia
2020-01-01 22:32:58 DEBUG   ::MAIN: git output: 2e7d4a58633b4b7924496ba849636bd5bb3b98cc
2020-01-01 22:32:58 DEBUG   ::MAIN: git rev-parse --verify --quiet '@{upstream}' : returned successful
2020-01-01 22:32:58 DEBUG   ::MAIN: Executing git rev-list --left-right '@{upstream}'...HEAD with your shell in /volume1/scripts/nzbToMedia
2020-01-01 22:32:58 DEBUG   ::MAIN: git output: <2e7d4a58633b4b7924496ba849636bd5bb3b98cc
<9111f815f9edaad117915baad01b8c6a136f587c
<feb4e36c4c1dab5d6b4d467a1355076c50d28de6
<cbd0c25c882e6e84c5e2e32ab8bc9886336e2fdc
<75ecbd48629f31c0456c99b726eff99a650e1530
<d95e4e56c8569bc41a085336a797044ca2c4a1d9
<0d7c59f1f035d51a7409449bc4e335928a6b29bd
<fdaa00775674a887bb4002e82b89ba6de3fa9083
<5cd449632f1f46eb7ad840cd2b39d4206242ef9f
<70ab7d3d611475d0085082aade49d7163e6eb0d1
<fde87148627ff66650201087dab840dfd6fb5d70
<c92588c3bea0b614a4b70cc77d036139c5775f80
<1814bd5ae1a40885217e7a4427768b689b93542b
<80ef0d094e1c316ff9e688d34489b4a1846c6895
2020-01-01 22:32:58 DEBUG   ::MAIN: git rev-list --left-right '@{upstream}'...HEAD : returned successful
2020-01-01 22:32:58 DEBUG   ::MAIN: cur_commit = 46b2e8998ce7c0e4b853272f0bdb06a558852c81 % (newest_commit)= 2e7d4a58633b4b7924496ba849636bd5bb3b98cc, num_commits_behind = 14, num_commits_ahead = 0
2020-01-01 22:32:58 INFO    ::MAIN: There is a newer version available (you're 14 commits behind)
2020-01-01 22:32:58 INFO    ::MAIN: Auto-Updating nzbToMedia, Please wait ...
2020-01-01 22:32:58 DEBUG   ::MAIN: Executing git rev-parse HEAD with your shell in /volume1/scripts/nzbToMedia
2020-01-01 22:32:58 DEBUG   ::MAIN: git output: 46b2e8998ce7c0e4b853272f0bdb06a558852c81
2020-01-01 22:32:58 DEBUG   ::MAIN: git rev-parse HEAD : returned successful
2020-01-01 22:32:58 DEBUG   ::MAIN: Executing git fetch origin with your shell in /volume1/scripts/nzbToMedia
2020-01-01 22:32:58 DEBUG   ::MAIN: git output: 
2020-01-01 22:32:58 DEBUG   ::MAIN: git fetch origin : returned successful
2020-01-01 22:32:58 DEBUG   ::MAIN: Executing git rev-parse --verify --quiet '@{upstream}' with your shell in /volume1/scripts/nzbToMedia
2020-01-01 22:32:58 DEBUG   ::MAIN: git output: 2e7d4a58633b4b7924496ba849636bd5bb3b98cc
2020-01-01 22:32:58 DEBUG   ::MAIN: git rev-parse --verify --quiet '@{upstream}' : returned successful
2020-01-01 22:32:58 DEBUG   ::MAIN: Executing git rev-list --left-right '@{upstream}'...HEAD with your shell in /volume1/scripts/nzbToMedia
2020-01-01 22:32:58 DEBUG   ::MAIN: git output: <2e7d4a58633b4b7924496ba849636bd5bb3b98cc
<9111f815f9edaad117915baad01b8c6a136f587c
<feb4e36c4c1dab5d6b4d467a1355076c50d28de6
<cbd0c25c882e6e84c5e2e32ab8bc9886336e2fdc
<75ecbd48629f31c0456c99b726eff99a650e1530
<d95e4e56c8569bc41a085336a797044ca2c4a1d9
<0d7c59f1f035d51a7409449bc4e335928a6b29bd
<fdaa00775674a887bb4002e82b89ba6de3fa9083
<5cd449632f1f46eb7ad840cd2b39d4206242ef9f
<70ab7d3d611475d0085082aade49d7163e6eb0d1
<fde87148627ff66650201087dab840dfd6fb5d70
<c92588c3bea0b614a4b70cc77d036139c5775f80
<1814bd5ae1a40885217e7a4427768b689b93542b
<80ef0d094e1c316ff9e688d34489b4a1846c6895
2020-01-01 22:32:58 DEBUG   ::MAIN: git rev-list --left-right '@{upstream}'...HEAD : returned successful
2020-01-01 22:32:58 DEBUG   ::MAIN: cur_commit = 46b2e8998ce7c0e4b853272f0bdb06a558852c81 % (newest_commit)= 2e7d4a58633b4b7924496ba849636bd5bb3b98cc, num_commits_behind = 14, num_commits_ahead = 0
2020-01-01 22:32:58 DEBUG   ::MAIN: Executing git pull origin master with your shell in /volume1/scripts/nzbToMedia
2020-01-01 22:32:59 DEBUG   ::MAIN: git output: From https://github.com/clinton-hall/nzbToMedia
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	.bumpversion.cfg
	autoProcessMedia.cfg.spec
	azure-pipelines.yml
	cleanup.py
	core/__init__.py
	core/auto_process/movies.py
	core/configuration.py
	core/forks.py
	core/plugins/subtitles.py
	core/utils/files.py
	core/version_check.py
	eol.py
	libs/common/qbittorrent/client.py
	nzbToMedia.py
	setup.py
Please commit your changes or stash them before you merge.
Aborting
Updating 46b2e89..2e7d4a5
2020-01-01 22:32:59 DEBUG   ::MAIN: git pull origin master returned : From https://github.com/clinton-hall/nzbToMedia
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	.bumpversion.cfg
	autoProcessMedia.cfg.spec
	azure-pipelines.yml
	cleanup.py
	core/__init__.py
	core/auto_process/movies.py
	core/configuration.py
	core/forks.py
	core/plugins/subtitles.py
	core/utils/files.py
	core/version_check.py
	eol.py
	libs/common/qbittorrent/client.py
	nzbToMedia.py
	setup.py
Please commit your changes or stash them before you merge.
Aborting
Updating 46b2e89..2e7d4a5
2020-01-01 22:32:59 ERROR   ::MAIN: Update failed, not restarting. Check your log for more information.
2020-01-01 22:32:59 INFO    ::MAIN: nzbToMedia Version:46b2e8998ce7c0e4b853272f0bdb06a558852c81 Branch:master (Linux 3.10.102)
2020-01-01 22:32:59 WARNING ::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
2020-01-01 22:32:59 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...`
Do i need to worry and is nzbtomedia not the latest now?

**Comment by XxUnkn0wnxX** [comment]
@ikkeenjij36 this happens when you have manuly overwritten the files & git wont update nzbtomedia as it wont you to either commit them or stash them... you will need to delete the files you manualy edited then run `git reset --hard` in the folder & then do `git pull` or just disable ` auto_update` in autoProcessMedia.cfg

**Comment by ted46045** [comment]
alternativly you can just change the date listed in the eol.py to be something else (like 2030 instead of 2020) if the 100 day grace period isnt enough

**Comment by clinton-hall** [comment]
sorry all for the drama.... looks like I took the wrong week to disappear into the bush without internet access...

I have removed the python2.7 eol failure and just set this to log and remind you to update. I'll try and keep support for python2 for now, but note that I may not make all new features compatible with python2....

**Comment by skarekrow** [comment]
I appreciate it, but honestly it’s more the problem of the containers (nzbget and sab) not having python3 available, which would have allowed a fair workaround with using a shell script to call out to nzbtomedia. 

Keeping it dual stacked will inevitably become harder and harder to maintain.

**Comment by clinton-hall** [comment]
thanks @skarekrow 

There are clearly a lot of divided opinions on this issue... I suspect this is only 1 of many apps that will cause some debate around continued, or not, support for python2.

SABnzbd are working on a python3 version, NZBget has a shell override option which allows you for force the binary to call scripts, and I had made some simple .sh scripts available to "pass-through" to any python binary.

Yes, some containers/apps do make it hard, but having built some Apps  for NAS before I know it is pretty easy to only link the needed binaries into the PATH (i.e. when you have a python3.6 binary, python3 suymlinks to that, and python symlinks to python3, all inside some repository location it becomes easier just to symlink 1 'python' into the System Path). I'm not saying it is the "right" thing, but years down the track when Apps are all built on top of each other, some of these NAS systems ans busybox etc can become very temperamental when trying to figure out which command to call....

from what I have seen `python` is the only truly reliable call, but in a world where python2 is now end-of-life, what should that mean.

**Comment by timrettop** [comment]
For those having this issue with linuxserver/nzbget you can modify the scripts shell settings via these instructions, which for me addressed the issue and now the nzbToMedia script runs successfully (without altering eol.py) 
https://github.com/linuxserver/docker-nzbget#python-3-transition

**Comment by mannibis** [comment]
> For those having this issue with linuxserver/nzbget you can modify the scripts shell settings via these instructions, which for me addressed the issue and now the nzbToMedia script runs successfully (without altering eol.py)
> https://github.com/linuxserver/docker-nzbget#python-3-transition

That will work but will also force any other python extension scripts to use Python 3. If those other scripts are not Python 3 compatible, that will cause issues. I have to check VideoSort.py--that is the only other python extension script I use, and I'm not sure if it has been made Python 3 compliant.

**Comment by clinton-hall** [comment]
where did you get VideoSort.py from? I recall working on/contributing to this project back in the day, but can't recall where it ended up being hosted
It shouldn't be too difficult to make that project Python3 compatible.

**Comment by mannibis** [comment]
I believe I'm using this repo: https://github.com/nzbget/VideoSort

**Comment by clinton-hall** [comment]
yes, just found it... Hugbug has added a lot to this from the early discussions I recalled...

I'll see if I do find time to have a play and possibly submit a PR for python3 support....

**Comment by clinton-hall** [comment]
ok... I have updated a few things and got all of the imports to load etc....

https://github.com/clinton-hall/VideoSort

Feel free to give this a test and see if it functions... I'll share it with hugbug to see if he wants to merge.... but I'm not in a position to test it all.

**Comment by ikkeenjij36** [comment]
For me its solved with the work arounds and finally after updating so i will close it for now
Thanks for all the help
