### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by maitikeisi** [clinton-hall/nzbToMedia#1688]
**Describe the bug**
Since Python 2.7 got depracated today I switched nzbget to use python 3.6 and after that the post processing results in the error shown. (works fine with python 2.7, i edited the eol.py to make it work again for the time being...)

TypeError: '>' not supported between instances of 'str' and 'int'

**Technical Specs**
1. Ubuntu 18.04.3 LTS
2. Python version 3.6
3. Download Client NZBGet
4. Intended Media Management Sonarr

**Expected behavior**
Successful post processing

**Log**

Fuller log attached.

Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone: Changing to directory: /opt/nzbget/scripts/nzbToMedia
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone: -- Cleaning bytecode --
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone: b'Removing __pycache__/\n'
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone: b'Removing __pycache__/\n'
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone: -- Cleaning folders: ['libs', 'core'] --
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone: No folders to clean
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone: Returning to directory:  /
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone: -- Cleanup finished --
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone: Traceback (most recent call last):
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone:   File "/opt/nzbget/scripts/nzbToMedia/nzbToNzbDrone.py", line 259, in <module>
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone:     result = nzbToMedia.main(sys.argv, section)
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone:   File "/opt/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 961, in main
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone:     failure_link=failure_link)
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone:   File "/opt/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 853, in process
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone:     result = tv.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone:   File "/opt/nzbget/scripts/nzbToMedia/core/auto_process/tv.py", line 108, in process
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone:     input_name, dir_name = convert_to_ascii(input_name, dir_name)
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone:   File "/opt/nzbget/scripts/nzbToMedia/core/utils/encoding.py", line 64, in convert_to_ascii
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone:     encoded, input_name = char_replace(input_name)
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone:   File "/opt/nzbget/scripts/nzbToMedia/core/utils/encoding.py", line 32, in char_replace
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone:     (name[Idx + 1] >= '\xA0') & (name[Idx + 1] <= '\xFF')):
Wed Jan 01 2020 18:21:37	INFO	nzbToMedia/nzbToNzbDrone: TypeError: '>=' not supported between instances of 'int' and 'str'
Wed Jan 01 2020 18:21:37	ERROR	Post-process-script nzbToMedia/nzbToNzbDrone.py for RENAMED failed (terminated with unknown status)
Wed Jan 01 2020 18:21:37	INFO	Collection RENAMED added to history

[debug.log](https://github.com/clinton-hall/nzbToMedia/files/4014266/debug.log)

**Comment by jonpspri** [comment]
@maitikeisi I've posted a PR against my repository.  If you have the Git foo, feel free to try it out.

**Comment by maitikeisi** [comment]
@jonpspri tested it and it worked fine. I did have to pip3 install future package as I didn't have it (builtins module) installed, but other than that didn't have any problems with it. Thanks.
Log for reference
[debug.log](https://github.com/clinton-hall/nzbToMedia/files/4021695/debug.log)

**Comment by clinton-hall** [comment]
@jonpspri 
thanks for the PR.
I merged that in, made a tweak to only import bytes when using py3 (have added back py2 support) and also ensured that the encoded name was returned.
