### ISSUE TITLE
SickGear: Failed to post-process 403 _xsrf argument missing from POST

### ISSUE THREAD

**Issue by hitcher1971** [clinton-hall/nzbToMedia#1704]
Anyone familiar with this error??
(See Log )
**Describe the bug**
Process after unpacking is failing... worked fine 2 days ago... never changed anything....

**Technical Specs**
1. Running on NAS DS410
2. Python version 2.7.14
3. Download Client SABnbzd,
4. Intended Media Management SickGear

**Expected behavior**
Unpack and move to desired folders

**Log**
2020-01-15 11:56:49 DEBUG    TORNADO :: Gracefully handled exception text:
 1) ['Traceback (most recent call last):\n', '  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado_py2/web.py", line 1567, in _execute\n    self.check_xsrf_cookie()\n', '  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado_py2/web.py", line 1408, in check_xsrf_cookie\n    raise HTTPError(403, "\'_xsrf\' argument missing from POST")\n', "HTTPError: HTTP 403: Forbidden ('_xsrf' argument missing from POST)\n"]

2020-01-15 11:56:49 WARNING  TORNADO :: Sent 403 error response to a `POST` request for `/login` with headers:
 1) Content-Length: 19
 2) Accept-Encoding: gzip, deflate
 3) Connection: keep-alive
 4) Accept: */*
 5) User-Agent: python-requests/2.7.0 CPython/2.7.14 Linux/2.6.32.12
 6) Host: localhost:8083
 7) Content-Type: application/x-www-form-urlencoded
 8) Request body: username=&password=

2020-01-15 11:56:49 WARNING  TORNADO.GEN :: 403 POST /login (127.0.0.1): '_xsrf' argument missing from POST

**Comment by clinton-hall** [comment]
Can you try switching to `SickGear-patch-1` branch and test the change I just made?

If this doesn't work, can you please provide full debug log so I can see what is being passed and where it fails?

**Comment by hitcher1971** [comment]
All working fine now on Patch-1 branch! Sorry for the late reply! Thx!

**Comment by galant56k** [comment]
please help. i have the error repeating every 1 second, after setting sickgear up for the first time on a windows system python 3.8



[sickgear.zip](https://github.com/clinton-hall/nzbToMedia/files/4928577/sickgear.zip)

**Comment by clinton-hall** [comment]
If that is logging every 1 second, what makes you think this is related to nzbToMedia?
The logs appear to show this being an issue when trying to view error logs in SickGear...

If this is in anyway connected to nzbToMedia, post the nzbtomedia.log so I can try and see what might be going wrong.

**Comment by galant56k** [comment]
Sorry, I thought I was in the sickgear site. Just seamed to be similar error code.


Regards,

Ashley Schloss
Technician

[cid:image001.jpg@01D65B8A.BBD76BC0]

3/1155 Gympie Rd
Aspley QLD 4034
Ph. 07 3350 6555
ashley@asquick.com.au<mailto:gareth@asquick.com.au>

**Comment by clinton-hall** [comment]
fair enough. I hope you find a solution to your issue.
