### ISSUE TITLE
Scene name in Radarr/Sonarr lost when using nzbToMedia

### ISSUE THREAD

**Issue by kocane** [clinton-hall/nzbToMedia#1728]
Radarr and Sonarr has a field called 'Scene name' in which, I'm guessing, it'll keep  the original name of the release even when renaming. My main use for it is with the subtitle searcher Bazarr. However, when using nzbToMedia as post processing, this gets lost.

Any idea why and is it even at all related with nzbToMedia?

**Comment by clinton-hall** [comment]
It may be related, if the way we pass the call "breaks" the link between snatched release and files to be processed. 
I'd need to see the logs to what order things are happening.

**Comment by kocane** [comment]
@clinton-hall do you want logs from radarr where it processes a download without nzbToMedia?
