### ISSUE TITLE
nzbToMedia Update fails

### ISSUE THREAD

**Issue by ronrosenfeld** [clinton-hall/nzbToMedia#1729]
My nzbToMedia installation in nzbGet has AutoUpdate selected, but that doesn't seem to work.

I was having a problem of **recent** onset where an attempt to post-process would create a message in the Sickchill log  `User attempted a failed login to the sickchill web interface from IP 172.17.0.1` and the post-process would eventually fail.

That problem was apparently fixed by stopping and restarting both nzbGet and SickChill, but in the course of trouble shooting I tried to update nzbToMedia, since changelog.txt showed:  V11.03 15/01/2017

Executing `git pull` returned error message:
```
Updating 80c8ad5..5a68377
error: Your local changes to the following files would be overwritten by merge:
    long list of files
```
Tried:

```
git reset --hard
git pull
```
with same results

Was going to try `git stash …` but that returns a message:
```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.
```
and I really don't know what to do with this.

**Technical Specs**
1. Running on Docker
2. Python version '2.7.12'
3. Download Client: `NZBget`
4. Intended Media Management `SickChill`

**Expected behavior**
git pull should update the scripts

**Log**
see above

**Comment by clinton-hall** [comment]
Only thing I can suggest here is to re-clone, so from nzbToMedia directory:
```
cd ..
mv nzbToMedia nzbToMedia.old
git clone https://github.com/nzbToMedia.git
cp nzbToMedia.old/autoProcessMedia.cfg nzbToMedia/autoPorcessMedia.cfg
```
Then test if everything is working... if so, you can delete the nzbToMedia.old (backup)

**Comment by ronrosenfeld** [comment]
Thank you @clinton-hall 

I have recloned and checked the settings in nzbGet -- they all appear correct.
I'll wait until a few programs have been downloaded/processed before deleting the `.old` backup folder.

If anyone else is going through this, a few notes on the reclone script (which took me a bit to figure out, after getting error messages)

 - Should be executed from the **parent** of the nzbToMedia directory (probably the `scripts` directory
 - the URL to clone from is `git clone https://github.com/clinton-hall/nzbToMedia.git`

**Comment by clinton-hall** [comment]
thanks for confirming... sorry i have the git clone URL wrong previously (fixed now in my original post).
The `cd ..` cmd should have taken you into the parent (scripts) directory... but glad you figured it out.

**Comment by ronrosenfeld** [comment]
> The cd .. cmd should have taken you into the parent (scripts) directory... but glad you figured it out.

And it would have, had I executed it as written :-(

-----

A post-processing task completed successfully, but there are errors in a section of the log that were not there with the previous version.

Current Version:
```
Thu Mar 12 2020 05:42:17	INFO	nzbToMedia/nzbToMedia: -- Cleaning bytecode --
Thu Mar 12 2020 05:42:17	INFO	nzbToMedia/nzbToMedia: WARNING: Automatic cleanup could not be executed.
Thu Mar 12 2020 05:42:17	INFO	nzbToMedia/nzbToMedia:          If errors occur, manual cleanup may be required.
Thu Mar 12 2020 05:42:17	INFO	nzbToMedia/nzbToMedia: REASON : Error: [Errno 2] No such file or directory
Thu Mar 12 2020 05:42:17	INFO	nzbToMedia/nzbToMedia: -- Cleaning folders: [u'libs', u'core'] --
Thu Mar 12 2020 05:42:17	INFO	nzbToMedia/nzbToMedia: WARNING: Automatic cleanup could not be executed.
Thu Mar 12 2020 05:42:17	INFO	nzbToMedia/nzbToMedia:          If errors occur, manual cleanup may be required.
Thu Mar 12 2020 05:42:17	INFO	nzbToMedia/nzbToMedia: REASON : Error: [Errno 2] No such file or directory
Thu Mar 12 2020 05:42:17	INFO	nzbToMedia/nzbToMedia: Returning to directory:  /run/s6/services/nzbget
Thu Mar 12 2020 05:42:17	INFO	nzbToMedia/nzbToMedia: -- Cleanup finished --
```

There was no *cleaning bytecode* section in the previous version.

Is this something significant?

Thanks.
Ron

**Comment by clinton-hall** [comment]
nothing to worry about.
there was a lot of code change, so we had to introduce auto-clean features to remove old code or it would fail... on some systems, the auto-clean gives issues, but this isn't causing you any further problems on this clean install.

**Comment by ronrosenfeld** [comment]
Thanks.
