### ISSUE TITLE
Post Processing issues after updating Python

### ISSUE THREAD

**Issue by juliemars** [clinton-hall/nzbToMedia#1730]
**Describe the bug**
Hi
I decided to update Python from 2.7 to 3.7 using the link in the Wiki. I then started getting the following:

>error
Mon Mar 16 2020 06:23:32
Post-process-script nzbToMedia\nzbToSickBeard.py for XXXX failed (terminated with unknown status)
info
Mon Mar 16 2020 06:23:32
nzbToSickBeard: C:\Program Files\Python37\python.exe: can't open file 'L': [Errno 2] No such file or directory

I fixed this by adding in to NZBGet Shell Overide
`.py=C:\Program Files\Python37\python.exe`

However I now get the following 

>INFO	Mon Mar 16 2020 06:46:05	Unpausing download after post-processing
INFO	Mon Mar 16 2020 06:46:05	Collection XXXX added to history
ERROR	Mon Mar 16 2020 06:46:05	Post-process-script nzbToMedia\nzbToSickBeard.py for XXXX failed (terminated with unknown status)
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: KeyError: 'proc_type'
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: del fork_params['proc_type']
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: File "C:\ProgramData\NZBGet\scripts\nzbToMedia\core\auto_process\tv.py", line 171, in process
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: result = tv.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: File "C:\ProgramData\NZBGet\scripts\nzbToMedia\nzbToMedia.py", line 750, in process
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: failure_link=failure_link)
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: File "C:\ProgramData\NZBGet\scripts\nzbToMedia\nzbToMedia.py", line 856, in main
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: result = nzbToMedia.main(sys.argv, section)
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: File "C:\ProgramData\NZBGet\scripts\nzbToMedia\nzbToSickBeard.py", line 264, in <module>
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: Traceback (most recent call last):
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: -- Cleanup finished --
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: Returning to directory: C:\WINDOWS\system32
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: No folders to clean
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: -- Cleaning folders: ['libs', 'core'] --
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: b'Removing __pycache__/\nRemoving core/__init__.pyc\nRemoving libs/__init__.pyc\nRemoving libs/autoload.pyc\nRemoving libs/util.pyc\n'
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: b'Removing __pycache__/\nRemoving core/__init__.pyc\nRemoving libs/__init__.pyc\nRemoving libs/autoload.pyc\nRemoving libs/util.pyc\n'
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: -- Cleaning bytecode --
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: Changing to directory: C:\ProgramData\NZBGet\scripts\nzbToMedia
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: [06:46:05] [INFO]::TRANSCODER: SUCCESS: [XXXX.mkv] has no corruption.
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: [06:46:05] [INFO]::TRANSCODER: Checking [XXXX.mkv] for corruption, please stand by ...
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: [06:46:05] [INFO]::MAIN: FLATTEN: Flattening directory: C:\ProgramData\NZBGet\complete\TV\XXXX
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: [06:46:05] [INFO]::MAIN: SickBeard:TV fork set to custom
INFO	Mon Mar 16 2020 06:46:05	nzbToSickBeard: [06:46:05] [INFO]::MAIN: SickBeard:TV fork auto-detection found custom params {'delete_on': None, 'process_method': None, 'force': None, 'type': None, 'failed': None, 'proc_dir': None}
INFO	Mon Mar 16 2020 06:46:04	nzbToSickBeard: [06:46:04] [INFO]::MAIN: Attempting to auto-detect TV fork
INFO	Mon Mar 16 2020 06:46:04	nzbToSickBeard: [06:46:04] [INFO]::MAIN: Calling SickBeard:TV to post-process:XXXX
INFO	Mon Mar 16 2020 06:46:04	nzbToSickBeard: [06:46:04] [INFO]::MAIN: Auto-detected SECTION:SickBeard
INFO	Mon Mar 16 2020 06:46:04	nzbToSickBeard: [06:46:04] [INFO]::MAIN: Script triggered from NZBGet Version 21.1-testing-r2311.
INFO	Mon Mar 16 2020 06:46:04	nzbToSickBeard: [06:46:04] [INFO]::MAIN: #########################################################
INFO	Mon Mar 16 2020 06:46:04	nzbToSickBeard: [06:46:04] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
INFO	Mon Mar 16 2020 06:46:04	nzbToSickBeard: [06:46:04] [INFO]::MAIN: #########################################################
INFO	Mon Mar 16 2020 06:46:04	nzbToSickBeard: [06:46:04] [INFO]::MAIN: nzbToMedia Version:4896848099298ee2914760c56a66d4ad0674d181 Branch:master (Windows 10)
INFO	Mon Mar 16 2020 06:46:04	nzbToSickBeard: [06:46:04] [INFO]::MAIN: No update needed
INFO	Mon Mar 16 2020 06:46:03	nzbToSickBeard: [06:46:03] [INFO]::MAIN: Checking if git needs an update
INFO	Mon Mar 16 2020 06:46:02	nzbToSickBeard: [06:46:02] [INFO]::MAIN: Checking database structure...
INFO	Mon Mar 16 2020 06:45:58	Executing post-process-script nzbToMedia\nzbToSickBeard.py for XXXX
INFO	Mon Mar 16 2020 06:45:58	Pausing download before post-processing
INFO	Mon Mar 16 2020 06:45:58	Nothing to cleanup for XXXX
INFO	Mon Mar 16 2020 06:45:58	Cleaning up XXXX
INFO	Mon Mar 16 2020 06:45:58	Queueing XXXX for post-processing
INFO	Mon Mar 16 2020 06:45:58	XXXX returned from history back to download queue
INFO	Mon Mar 16 2020 06:45:58	Post-processing again XXXX

**Technical Specs**
1. Windows 10 
2. Python version 3.7.3
3. Download Client (NZBget, SABnbzd, Transmission) NZBGet 21.1-testing-r2311

4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) Medusa, Radarr, Lidarr

**Expected behavior**
File is Processed

**Log**
Enabled Debug and full log is:

> INFO	Mon Mar 16 2020 06:52:41	Unpausing download after post-processing
INFO	Mon Mar 16 2020 06:52:41	Collection XXXX added to history
ERROR	Mon Mar 16 2020 06:52:41	Post-process-script nzbToMedia\nzbToSickBeard.py for XXXX failed (terminated with unknown status)
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: KeyError: 'proc_type'
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: del fork_params['proc_type']
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: File "C:\ProgramData\NZBGet\scripts\nzbToMedia\core\auto_process\tv.py", line 171, in process
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: result = tv.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: File "C:\ProgramData\NZBGet\scripts\nzbToMedia\nzbToMedia.py", line 750, in process
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: failure_link=failure_link)
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: File "C:\ProgramData\NZBGet\scripts\nzbToMedia\nzbToMedia.py", line 856, in main
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: result = nzbToMedia.main(sys.argv, section)
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: File "C:\ProgramData\NZBGet\scripts\nzbToMedia\nzbToSickBeard.py", line 264, in <module>
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: Traceback (most recent call last):
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: -- Cleanup finished --
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: Returning to directory: C:\WINDOWS\system32
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: No folders to clean
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: -- Cleaning folders: ['libs', 'core'] --
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: b'Removing __pycache__/\nRemoving core/__pycache__/\nRemoving core/auto_process/__pycache__/\nRemoving core/extractor/__pycache__/\nRemoving core/utils/__pycache__/\nRemoving libs/__pycache__/\nRemoving libs/common/__pycache__/\nRemoving libs/common/babelfish/__pycache__/\nRemoving libs/common/babelfish/converters/__pycache__/\nRemoving libs/common/beets/__pycache__/\nRemoving libs/common/beets/util/__pycache__/\nRemoving libs/common/bs4/__pycache__/\nRemoving libs/common/bs4/builder/__pycache__/\nRemoving libs/common/certifi/__pycache__/\nRemoving libs/common/chardet/__pycache__/\nRemoving libs/common/dateutil/__pycache__/\nRemoving libs/common/dateutil/parser/__pycache__/\nRemoving libs/common/dateutil/tz/__pycache__/\nRemoving libs/common/dogpile/__pycache__/\nRemoving libs/common/dogpile/cache/__pycache__/\nRemoving libs/common/dogpile/cache/backends/__pycache__/\nRemoving libs/common/dogpile/util/__pycache__/\nRemoving libs/common/guessit/__pycache__/\nRemoving libs/common/guessit/rules/
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: b'Removing __pycache__/\nRemoving core/__pycache__/\nRemoving core/auto_process/__pycache__/\nRemoving core/extractor/__pycache__/\nRemoving core/utils/__pycache__/\nRemoving libs/__pycache__/\nRemoving libs/common/__pycache__/\nRemoving libs/common/babelfish/__pycache__/\nRemoving libs/common/babelfish/converters/__pycache__/\nRemoving libs/common/beets/__pycache__/\nRemoving libs/common/beets/util/__pycache__/\nRemoving libs/common/bs4/__pycache__/\nRemoving libs/common/bs4/builder/__pycache__/\nRemoving libs/common/certifi/__pycache__/\nRemoving libs/common/chardet/__pycache__/\nRemoving libs/common/dateutil/__pycache__/\nRemoving libs/common/dateutil/parser/__pycache__/\nRemoving libs/common/dateutil/tz/__pycache__/\nRemoving libs/common/dogpile/__pycache__/\nRemoving libs/common/dogpile/cache/__pycache__/\nRemoving libs/common/dogpile/cache/backends/__pycache__/\nRemoving libs/common/dogpile/util/__pycache__/\nRemoving libs/common/guessit/__pycache__/\nRemoving libs/common/guessit/rules/
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: -- Cleaning bytecode --
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: Changing to directory: C:\ProgramData\NZBGet\scripts\nzbToMedia
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: [06:52:41] [INFO]::TRANSCODER: SUCCESS: [XXXX.mkv] has no corruption.
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: [06:52:41] [DEBUG]::MAIN: calling command: C:\ffmpeg\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -show_error C:\ProgramData\NZBGet\complete\TV\XXXX\XXXX.mkv
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: [06:52:41] [INFO]::TRANSCODER: Checking [XXXX.mkv] for corruption, please stand by ...
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: [06:52:41] [DEBUG]::MAIN: calling command: C:\ffmpeg\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -show_error C:\ProgramData\NZBGet\scripts\nzbToMedia\tests\test.mp4
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: [06:52:41] [DEBUG]::MAIN: Checking for empty folders in:C:\ProgramData\NZBGet\complete\TV\XXXX
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: [06:52:41] [INFO]::MAIN: FLATTEN: Flattening directory: C:\ProgramData\NZBGet\complete\TV\XXXX
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: [06:52:41] [INFO]::MAIN: SickBeard:TV fork set to custom
INFO	Mon Mar 16 2020 06:52:41	nzbToSickBeard: [06:52:41] [INFO]::MAIN: SickBeard:TV fork auto-detection found custom params {'type': None, 'process_method': None, 'delete_on': None, 'force': None, 'proc_dir': None, 'failed': None}
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [INFO]::MAIN: Attempting to auto-detect TV fork
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [DEBUG]::SERVER: Server responded at http://IP/Sickrage
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [DEBUG]::SERVER: Attempting to connect to server at http://IP/Sickrage
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [INFO]::MAIN: Calling SickBeard:TV to post-process:XXXX
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [INFO]::MAIN: Auto-detected SECTION:SickBeard
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [DEBUG]::MAIN: Adding NZB download info for directory C:\ProgramData\NZBGet\complete\TV\XXXX to database
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [INFO]::MAIN: Script triggered from NZBGet Version 21.1-testing-r2311.
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [DEBUG]::MAIN: Options passed into nzbToMedia: ['C:\\ProgramData\\NZBGet\\scripts\\nzbToMedia\\nzbToSickBeard.py']
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [INFO]::MAIN: #########################################################
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [INFO]::MAIN: #########################################################
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [INFO]::MAIN: nzbToMedia Version:4896848099298ee2914760c56a66d4ad0674d181 Branch:master (Windows 10)
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [INFO]::MAIN: No update needed
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [DEBUG]::MAIN: git didn't return newest commit hash
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' with your shell in C:\ProgramData\NZBGet\scripts\nzbToMedia
INFO	Mon Mar 16 2020 06:52:40	nzbToSickBeard: [06:52:40] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" fetch origin : returned successful
INFO	Mon Mar 16 2020 06:52:39	nzbToSickBeard: [06:52:39] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" fetch origin with your shell in C:\ProgramData\NZBGet\scripts\nzbToMedia
INFO	Mon Mar 16 2020 06:52:39	nzbToSickBeard: [06:52:39] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse HEAD : returned successful
INFO	Mon Mar 16 2020 06:52:39	nzbToSickBeard: [06:52:39] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse HEAD with your shell in C:\ProgramData\NZBGet\scripts\nzbToMedia
INFO	Mon Mar 16 2020 06:52:39	nzbToSickBeard: [06:52:39] [INFO]::MAIN: Checking if git needs an update
INFO	Mon Mar 16 2020 06:52:39	nzbToSickBeard: [06:52:39] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD : returned successful
INFO	Mon Mar 16 2020 06:52:39	nzbToSickBeard: [06:52:39] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD with your shell in C:\ProgramData\NZBGet\scripts\nzbToMedia
INFO	Mon Mar 16 2020 06:52:39	nzbToSickBeard: [06:52:39] [DEBUG]::MAIN: Using: "C:\Program Files\Git\bin\git.exe"
INFO	Mon Mar 16 2020 06:52:39	nzbToSickBeard: [06:52:39] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" version : returned successful
INFO	Mon Mar 16 2020 06:52:39	nzbToSickBeard: [06:52:39] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" version with your shell in C:\ProgramData\NZBGet\scripts\nzbToMedia
INFO	Mon Mar 16 2020 06:52:39	nzbToSickBeard: [06:52:39] [DEBUG]::MAIN: Checking if we can use git commands: "C:\Program Files\Git\bin\git.exe" version
INFO	Mon Mar 16 2020 06:52:39	nzbToSickBeard: [06:52:39] [DEBUG]::MAIN: InitialSchema upgrade not required
INFO	Mon Mar 16 2020 06:52:39	nzbToSickBeard: [06:52:39] [DEBUG]::MAIN: Checking Initial Schema database upgrade
INFO	Mon Mar 16 2020 06:52:39	nzbToSickBeard: [06:52:39] [INFO]::MAIN: Checking database structure...
INFO	Mon Mar 16 2020 06:52:34	Executing post-process-script nzbToMedia\nzbToSickBeard.py for XXXX
INFO	Mon Mar 16 2020 06:52:34	Pausing download before post-processing
INFO	Mon Mar 16 2020 06:52:34	Queueing XXXX for post-processing
INFO	Mon Mar 16 2020 06:52:34	XXXX returned from history back to download queue
INFO	Mon Mar 16 2020 06:52:34	Post-processing again XXXX

Appreciate any ideas as I am pulling my hair out!

**Comment by clinton-hall** [comment]
ok, your version of nzbToMedia is quite ole from the looks of it. And Auto updating seems to be failing.

Can you try a git pull to update, or otherwise re-clone (and copy of the autoProcessMedia.cfg) and then try again.

**Comment by juliemars** [comment]
thanks I was sure I had copied over the latest install but this time i deleted and reran git and it seems to be working.

**Comment by clinton-hall** [comment]
glad to hear.
