### ISSUE TITLE
Sickchill - torrenttomedia not processing as expected

### ISSUE THREAD

**Issue by fidofido300** [clinton-hall/nzbToMedia#1731]
**Describe the bug**
I thinks its not a bug but config issue I am stuck.
Manual PostProcess at SickChill processes file.

**Technical Specs**
1. Running on Windows 10 1909
2. Python version  python 3.8
3. Download Client :utorrent (python.exe c:\SickRage\nzbToMedia\TorrentToMedia.py "%D" "%N" "%L" "%I")
4. Intended Media Management: SickChill

**Expected behavior**
1. Torrenttomedia script runs but after sending sickchill request it exits succesfully?????? without processing file. 
2. I don't want to use the COPYLINK feature and I could't disable it.
3. CLEARDIRECTORy feature cannot be disabled as well
[manual run.txt](https://github.com/clinton-hall/nzbToMedia/files/4365310/manual.run.txt)
[nzbtomedia.txt](https://github.com/clinton-hall/nzbToMedia/files/4365312/nzbtomedia.txt)
[autoProcessMedia.cfg.txt](https://github.com/clinton-hall/nzbToMedia/files/4365315/autoProcessMedia.cfg.txt)

**Log**
Provided :)
Thank you in advance.

**Comment by clinton-hall** [comment]
try setting
```
[SickBeard]
    [[tv]]
        fork = auto
```
then if this still fails, post the nzbToMedia log and the SickChill log from the same time.

**Comment by fidofido300** [comment]
It worked thank you.
if anything changes I will report
What about the Cleandir and copylink how can i stop those steps ??

**Comment by clinton-hall** [comment]
Both Cleandir and copylink are "disabled" by you other settings.
Because destination and source are the same, Copylink just ignores them... but it logs entries to say that (and I'd need to make other changes to actually suppress logging).
Because you use copy in SickChill, the files still exist at source, so the Cleandir also ignores these (again only logs to say why).

**Comment by fidofido300** [comment]
Ok Thank you for explaining :)
