### ISSUE TITLE
 nzbToSickBeard no such file or directory

### ISSUE THREAD

**Issue by reach4thelasers** [clinton-hall/nzbToMedia#1734]
**Describe the bug**
I got the error below when trying to run nzbToSickBeard from nzbget.  Seems to be a "no such file or directory" error but the log isn't clear on what file it is looking for.  Any ideas or support debugging this would be appreciated.

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) '....' QNAP TVS-471
2. Python version '....' Same issue with Python 2.7 or 3.7
3. Download Client (NZBget, SABnbzd, Transmission) '....' NZBGet
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) '....' SickChill

**Log**

ERROR | Sun Apr 05 2020 00:25:37 | Post-process-script nzbToMedia/nzbToSickBeard.py for Doctor.Foster.S02E01.BDRip.x264.1-HAGGiS-Obfuscated failed (terminated with unknown status)
-- | -- | --
INFO | Sun Apr 05 2020 00:25:37 | nzbToSickBeard: FileNotFoundError: [Errno 2] No such file or directory
INFO | Sun Apr 05 2020 00:25:37 | nzbToSickBeard: self.original_directory = os.getcwd() if original is None else original
INFO | Sun Apr 05 2020 00:25:37 | nzbToSickBeard: File "/share/CACHEDEV1_DATA/Download/NZBGet_temp/scripts/nzbToMedia/cleanup.py", line 38, in __init__
INFO | Sun Apr 05 2020 00:25:37 | nzbToSickBeard: with WorkingDirectory(module_path()) as cwd:
INFO | Sun Apr 05 2020 00:25:37 | nzbToSickBeard: File "/share/CACHEDEV1_DATA/Download/NZBGet_temp/scripts/nzbToMedia/cleanup.py", line 178, in clean
INFO | Sun Apr 05 2020 00:25:37 | nzbToSickBeard: cleanup.clean(cleanup.FOLDER_STRUCTURE)
INFO | Sun Apr 05 2020 00:25:37 | nzbToSickBeard: File "/share/CACHEDEV1_DATA/Download/NZBGet_temp/scripts/nzbToMedia/nzbToMedia.py", line 728, in <module>
INFO | Sun Apr 05 2020 00:25:37 | nzbToSickBeard: import nzbToMedia
INFO | Sun Apr 05 2020 00:25:37 | nzbToSickBeard: File "/share/Download/NZBGet_temp/scripts/nzbToMedia/nzbToSickBeard.py", line 270, in <module>
INFO | Sun Apr 05 2020 00:25:37 | nzbToSickBeard: Traceback (most recent call last):
INFO | Sun Apr 05 2020 00:25:37 | Executing post-process-script nzbToMedia/nzbToSickBeard.py for Doctor.Foster.S02E01.BDRip.x264.1-HAGGiS-Obfuscated

**Comment by clinton-hall** [comment]
This looks like the user that runs NZBGet does not have read permissions on the nzbToMedia directory.
os.getcwd() doesn't even seem to return a valid folder that the script can find.

**Comment by reach4thelasers** [comment]
Nope. Looks like Nzbget is running as "admin" and admin has full permissions on that folder.
To be safe I set a+rwx permissions recursively on the whole directory - same issue.

[/share/Download/NZBGet_temp/scripts/nzbToMedia] # ls -l
total 236
-rwxrwxrwx 1 admin administrators 22949 2020-04-05 00:12 autoProcessMedia.cfg.spec*
-rwxrwxrwx 1 admin administrators  1643 2020-04-05 00:12 azure-pipelines.yml*
-rwxrwxrwx 1 admin administrators  6369 2020-04-05 00:12 cleanup.py*
-rwxrwxrwx 1 admin administrators    26 2020-04-05 00:12 _config.yml*
drwxrwxrwx 6 admin administrators  4096 2020-04-05 00:12 core/
-rwxrwxrwx 1 admin administrators  5410 2020-04-05 00:12 eol.py*
-rwxrwxrwx 1 admin administrators   504 2020-04-04 23:52 getffmpeg.sh*
drwxrwxrwx 6 admin administrators  4096 2020-04-05 00:12 libs/
-rwxrwxrwx 1 admin administrators 35127 2020-04-04 23:52 license.txt*
-rwxrwxrwx 1 admin administrators  7506 2020-04-05 00:12 nzbToCouchPotato.py*
-rwxrwxrwx 1 admin administrators  2993 2020-04-05 00:12 nzbToGamez.py*
-rwxrwxrwx 1 admin administrators  3824 2020-04-05 00:12 nzbToHeadPhones.py*
-rwxrwxrwx 1 admin administrators  3413 2020-04-05 00:12 nzbToLazyLibrarian.py*
-rwxrwxrwx 1 admin administrators  6979 2020-04-05 00:12 nzbToLidarr.py*
-rwxrwxrwx 1 admin administrators 32161 2020-04-05 00:12 nzbToMedia.py*
-rwxrwxrwx 1 admin administrators  3378 2020-04-05 00:12 nzbToMylar.py*
-rwxrwxrwx 1 admin administrators  7121 2020-04-05 00:12 nzbToNzbDrone.py*
-rwxrwxrwx 1 admin administrators  7221 2020-04-05 00:12 nzbToRadarr.py*
-rwxrwxrwx 1 admin administrators  7405 2020-04-05 00:12 nzbToSickBeard.py*
-rwxrwxrwx 1 admin administrators  7269 2020-04-05 00:12 nzbToWatcher3.py*
-rwxrwxrwx 1 admin administrators  3640 2020-04-05 00:12 setup.py*
drwxrwxrwx 2 admin administrators  4096 2020-04-05 00:12 tests/
-rwxrwxrwx 1 admin administrators 16817 2020-04-05 00:12 TorrentToMedia.py*
-rwxrwxrwx 1 admin administrators  3849 2020-04-05 00:12 tox.ini*
[/share/Download/NZBGet_temp/scripts/nzbToMedia] # ps | grep nzbget
 3685 admin      2160 S   grep nzbget
10365 admin    143484 S   /opt/bin/nzbget --daemon --configfile /share/CACHEDEV1_DATA/.qpkg/NZBGet/config/config.ini
[/share/Download/NZBGet_temp/scripts/nzbToMedia] #

**Comment by clinton-hall** [comment]
has this script ever worked?
Have you tried a complete uninstall/reinstall?

**Comment by reach4thelasers** [comment]
I installed SABNzbd rather than NZBGet, followed the instructions for that and everything is working fine now.  In NZBGet there is a section in the settings where you can fill out the various params required by nzbToMedia.  I was filling these out as instructed by the docs.

However with SABNzbd the instructions are different.  You need to enter the settings directly into the NzbToMedia config file.  Doing it this way worked ok.

So I think this issue was down to NZBGet failing to pass the correct parameters to nzbToMedia.  So I've got things working ok, but think there might be some outstanding problem with NzbGet.

**Comment by clinton-hall** [comment]
I use NZBGet myself, so I know that the settings do pass in.
If you want to re-visit NZBGet let me know... the logs above suggested the script never ran to read in the parameters from NZBGet. it looks more like an environment issue. Is your NZBGet installed in a docker/container?
