### ISSUE TITLE
nzbToRadarr post processing is failing

### ISSUE THREAD

**Issue by shanester64** [clinton-hall/nzbToMedia#1735]
**Describe the bug**
Transitioning from CouchPotato to Radaar. Validated setting.  failed Post-process-script nzbToMedia\nzbToRadarr.py

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) 'Windows 10"
2. Python version '2.7.17'
3. Download Client (NZBget, SABnbzd, Transmission) 'NZBGet.'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) 'Radarr'

**Expected behavior**
Movie should get renamed and get moved to its final destination

**Log**
Please provide an extract, or full debug log that indicates the issue.

**Comment by clinton-hall** [comment]
These scripts do work best with Python3. This is readily available on Win10 and python2.7 support was really maintained for older style NAS where Python is hard to get...

Are you able to install Python3 and see if this works... if not I'll try and track down what specific issue is happening with the Radarr returned data that is in a different format.

**Comment by shanester64** [comment]
Updated to python 3.7.7
Paths updated
pywin32-227 pip-20.0.2
[Swallow.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG (3).log](https://github.com/clinton-hall/nzbToMedia/files/4439152/Swallow.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.3.log)

**Comment by shanester64** [comment]
Do you need any additional info from me?

**Comment by clinton-hall** [comment]
Sorry for the delay. I have looked at the logs and it really looks like Radarr is returning a list for the DownloadedMoviesScan command, but their api guide says this should be json data so I'm confused.
I see that you closed this, did you have any update since the log you posted?

**Comment by shanester64** [comment]
Unfortunately, I closed it without commenting first.
As I mentioned I was testing Radaar as a possible replacement for CouchPotato.I have been using NZBGet and the NZBtoCouchPotato script without issue.In my initial configuration and testing, I updated the NZBtoRadaar settings withing NZBGet.
What I had to do was update the Radarr section of NZBtoMedia in NZBGet (This wasn't needed for CP).After I validated that all of the radarr setting were accurate/matching in all scripts/platforms the post-processing worked great. 
Thanks,

Ken Shane

 
 

    On Sunday, April 12, 2020, 07:50:54 PM CDT, Clinton Hall <notifications@github.com> wrote:  
 
 


Sorry for the delay. I have looked at the logs and it really looks like Radarr is returning a list for the DownloadedMoviesScan command, but their api guide says this should be json data so I'm confused.
I see that you closed this, did you have any update since the log you posted?

**Comment by clinton-hall** [comment]
Ah... I see now.

FWIW: if you set the category to call nzbToRadarr.py, then that is the section that needs to have the settings entered.
If you set the category to call nzbToMedia.py, then that is the section that needs to have (all appropriate) settings entered. Also, if you have nzbToMedia.py set as default script for all Non-category downloads, that is the script that needs to be configured...

**Comment by shanester64** [comment]
I did set it to call nzbToRadarr.py. Something wasn't working ;)...

 

Thanks,

Ken Shane

 
 

    On Monday, April 13, 2020, 06:22:38 PM CDT, Clinton Hall <notifications@github.com> wrote:  
 
 


Ah... I see now.

FWIW: if you set the category to call nzbToRadarr.py, then that is the section that needs to have the settings entered.
If you set the category to call nzbToMedia.py, then that is the section that needs to have (all appropriate) settings entered. Also, if you have nzbToMedia.py set as default script for all Non-category downloads, that is the script that needs to be configured...
