### ISSUE TITLE
"Failed to get JSON data from response" halting script

### ISSUE THREAD

**Issue by SiraVista** [clinton-hall/nzbToMedia#1741]
Greetings,

When sabnzbd calls nzbToMedia, things churn along okay until it reaches "Attempting to auto-detect tv fork".

The fork in question should be responding as SickChill.  Instead it immediately stops with: "Failed to get JSON data from response".

This is running on a Synology NAS box with Python version 2.7.12.

I've been trying to sort out what this error is trying to tell me, but I'm not able to determine what I've done wrong.  If there is a better forum for this kind of question, please let me know.

At any rate, processing does not continue and the file is left alone in the download directory.

This log contains some ominous lines:
`File "/var/packages/python/target/lib/python2.7/json/decoder.py", line 382, in raw_decode
raise`
`ValueError("No JSON object could be decoded")`
`ValueError: No JSON object could be decoded`
`Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f16b363fa50>> ignored`

Here is the full debug log:  [ntm01.txt](https://github.com/clinton-hall/nzbToMedia/files/4519923/ntm01.txt)

Please help!

Thanks,
Sira

**Comment by clinton-hall** [comment]
SickChill is definitely running on `http://localhost:8899` and you have the correct SickChill api key entered in autoProcessMedia.cfg?

Have you tried running with `host = 127.0.0.1` instead of localhost?

**Comment by SiraVista** [comment]
I am so sorry! I knew it was _something_ I was doing wrong -- and you figured it out right away.

I had the wrong API key in the autoProcessMedia.cfg for SickChill.  

Now with that fixed it works perfectly!  Thank you very much for your help!

Sira

**Comment by clinton-hall** [comment]
No worries. Glad it was something simple and not another bug to explore :)
