### ISSUE TITLE
File permissions are changed after nzbtoSickbeard.py extraction 

### ISSUE THREAD

**Issue by Bra1984** [clinton-hall/nzbToMedia#1742]
I decided to upgrade NzbtoMedia, to the current version, but post-processing is failing, I can see that it happens due to a file permissions error. 
Somehow the file permissions are changed after extract.

I reverted back to NZBtoMedia version 12.0.7, which don't change the file permissions and is working perfectly fine.
Has anyone else experienced this error? 

**Technical Specs**
1. Running on Synology NAS 412+
2. Python version 2,7
3. Download Client SABnbzd
4. Intended Media Management Medusa

**Comment by clinton-hall** [comment]
12.0.7 is over a year old, and before major re-factoring of the code. It is too difficult to try and track specific changes to the code that may impact on extraction.

Do you have logs to show what is happening and where the file permissions error comes in?

Have you tried stepping through the releases to show where this first happened? i.e. was it at 12.0.8, or did the issue start later?

**Comment by Bra1984** [comment]
The logs don't give me much info, I just get "Processing failed: Unable to move the files to their new home" I even tried to enable all debug logging.
I haven't tried to step through the changes, just tried to do a fresh install today, and reverted it again.

If I try to do a manual post-process from Medusa I get the same error, due to the permission being reset. 

Can you tell me, where I can enable the extract log ?

**Comment by clinton-hall** [comment]
To enable debug logs, edit `autoProcessMedia.cfg`
```
[General]
    log_debug = 1
```
After processing send through the details from logs/nzbtomedia.log (Ideally one showing logs from 12.0.7, and then one from current master)

I have reverted the Py2 depreciation (in current master), so you can test this with python2 if you want, although I do recommend python3.

To clarify here, is nzbToMedia doing the extraction, and not SABnzbd? if so, why? SABnzbd should be able to do the extraction...

I would expect that the user running SABnzbd (sc-sabnzbd) would be the owner of any files extracted by SABnzbd or nzbToMedia. If Medusa is running as a different users, then that would cause issue unless the permissions are set appropriately for the Medusa user.... but this shouldn't be different for the 2 versions of nzbToMedia.

What do you have set for chmod in SABnzbd?

**Comment by Bra1984** [comment]
Already tried that, the debug log doesn't show anything about permission being applied. 
SABnzbd handles the extraction, I can see it displays "unpacking" before the post-processing happens. 
It seems like the new version of  Nzbtomedia, is changing file permissions ? can you confirm that? otherwise, I have no idea why older version works but the new version doesn't on the same build with the same file permissions.

chmod in SABnzbd is set to 777.
Medusa is running as a different user, but this doesn't cause any issues on NZBtoMedia version 12.0.7 

It's not a big issue, the old version is working perfectly fine - just annoying I can't use the current build :)

**Comment by clinton-hall** [comment]
I can't see anything that has changed that should make any differences.
Particularly since nzbToMedia shouldn't be doing much to the files themselves.

The only places where nzbToMedia touches the files is
to do corruption check (read only)
to rename files (for identified replacements of obfuscated names)
Transcoding
applying chmod (if option is set)

Does the nzbToMedia log say anything like
`renaming`, `moving`, `transcoding`?

if not, does both 12.0.7 and current try to send the same url to Medusa? or does it pass different parameters to Medusa to process?

**Comment by Bra1984** [comment]
Nope, the debug log doesn't contain `renaming, moving, transcoding?`

No not the same URL..

12.0.7: 

`2020-04-24 11:35:05 DEBUG   ::SICKBEARD: Opening URL: http://localhost:8081/home/postprocess/processEpisode with params: {'nzbName': 'file.nzb', 'quiet': 1, 'failed': '0', 'proc_dir': '/volume1/Downloads/_NZB/done/_TV/file', 'type': 'manual'}`

Current: 

`2020-04-24 11:13:17 DEBUG   ::SICKBEARD: Opening URL: http://localhost:8081/home/postprocess/processEpisode with params: {u'nzbName': 'file', u'quiet': 1, u'failed': 0, u'proc_dir': '/volume1/Downloads/_NZB/done/_TV/file', u'type': u'manual'}`

I notice that the file is missing it's nzb extension in the current build and that there is and `u` before each parameter?

**Comment by clinton-hall** [comment]
The `u` is showing that the data being transmitted is unicode.

I suggest setting nzbToMedia to use api to access medusa, and using autofork

so in autoProcessMedia.cfg
```
[SickBeard]
    [[TV]] <or what ever category you have>
          apikey = <medusa api key here>
          fork = auto
```

**Comment by Bra1984** [comment]
Hi, 
sorry for the late response, I have moved all my Synology applications to a Ubuntu VM, everything is working now.

Can you tell me how Nzbtomedia is downloading subs ? do I need to manually install Subliminal 
on my Ubuntu VM as well ?

**Comment by clinton-hall** [comment]
Glad to hear it is working.

Should not need to download Subliminal as this is included in nzbToMedia
https://github.com/clinton-hall/nzbToMedia/tree/master/libs/common/subliminal

So if you have set the option to download subs, and entered the language, this should download subs to pass off to Medusa. If this doesn't seem to be working, please let me know and I'll try and assist as best I can.

**Comment by Bra1984** [comment]
Thanks, can you tell me what debug component that will store the sub download ?  and which providers are used ? opensubs are disabled in my country, so that could be the reason ?
