### ISSUE TITLE
I am getting this error while running a python code using OANDA API key..Invalid return character or leading space in header: Authorization

### ISSUE THREAD

**Issue by bijaykumarnaik1992** [clinton-hall/nzbToMedia#1749]
**Describe the bug**

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) '....'
2. Python version '....'
3. Download Client (NZBget, SABnbzd, Transmission) '....'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) '....'

**Expected behavior**

**Log**
Please provide an extract, or full debug log that indicates the issue.

**Comment by clinton-hall** [comment]
Please post this on a related project page and not here.
