### ISSUE TITLE
importerror imghdr

### ISSUE THREAD

**Issue by ShivALLmyTinders** [clinton-hall/nzbToMedia#1758]
Hi,
I'm having issues with post-process all of a sudden (seemingly after a hard reset of my QNAP following a power out). After completing a download with NZBGet and extracting/cleaning up, nzbToMedia is attempting to pull modules and failing on imghdr. I have checked my Python version (3.5) and its modules to confirm imghdr exists and it is listed. I've also checked the directories are accurate in the NZBGet config and all looks fine. Log extract below. This happens for both TV nzb downloads  (through Sonarr) and movies (through CouchPotato).

1. Running on QNAP TS-451+
2. Python version 3.5 (through the QNAP app store)
3. NZBGet v21.1
4. Sonarr and CouchPotato (although in this instance the download was pulled from Sonarr).

LOG:

Sat Jul 25 2020 06:56:46	INFO	nzbToMedia: /share/CACHEDEV1_DATA/Download/nzbget/scripts/nzbToMedia/eol.py:147: LifetimeWarning: Python 2.7 is no longer supported.
Sat Jul 25 2020 06:56:46	INFO	nzbToMedia:   warnings.warn(msg, LifetimeWarning)
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia: Changing to directory: /share/CACHEDEV1_DATA/Download/nzbget/scripts/nzbToMedia
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia: -- Cleaning bytecode --
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia: WARNING: Automatic cleanup could not be executed.
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:          If errors occur, manual cleanup may be required.
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia: REASON : Error: [Errno 2] No such file or directory
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia: -- Cleaning folders: [u'libs', u'core'] --
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia: WARNING: Automatic cleanup could not be executed.
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:          If errors occur, manual cleanup may be required.
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia: REASON : Error: [Errno 2] No such file or directory
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia: Returning to directory:  /
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia: -- Cleanup finished --
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia: Traceback (most recent call last):
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/Download/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 730, in <module>
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:     import core
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/Download/nzbget/scripts/nzbToMedia/core/__init__.py", line 52, in <module>
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:     from core import logger, main_db, version_check, databases, transcoder
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/Download/nzbget/scripts/nzbToMedia/core/databases.py", line 11, in <module>
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:     from core.utils import backup_versioned_file
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/Download/nzbget/scripts/nzbToMedia/core/utils/__init__.py", line 13, in <module>
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:     from core.utils.common import clean_dir, flatten, get_dirs, process_dir
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/Download/nzbget/scripts/nzbToMedia/core/utils/common.py", line 14, in <module>
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:     from core.utils.files import list_media_files, move_file
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/Download/nzbget/scripts/nzbToMedia/core/utils/files.py", line 14, in <module>
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:     import beets.mediafile
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:   File "/share/CACHEDEV1_DATA/Download/nzbget/scripts/nzbToMedia/libs/common/beets/mediafile.py", line 51, in <module>
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia:     import imghdr
Sat Jul 25 2020 06:56:48	INFO	nzbToMedia: ImportError: No module named imghdr
Sat Jul 25 2020 06:56:48	ERROR	Post-process-script nzbToMedia/nzbToMedia.py for Yellowstone.US.S01E01.720p.BluRay.x264-DEMAND failed (terminated with unknown status)
Sat Jul 25 2020 06:56:48	INFO	Collection Yellowstone.US.S01E01.720p.BluRay.x264-DEMAND added to history

**Comment by ShivALLmyTinders** [comment]
I should have mentioned, all the downloaded files exist in the completed directory, they're just not being post-processed into the intended final directory as renamed and cleaned up files.

Cheers.

**Comment by clinton-hall** [comment]
`LifetimeWarning: Python 2.7 is no longer supported`

So this script is being called through Python 2.7, not Python 3.5

You need to make sure your Python 2.7 has imghdr installed, or the script is called with Python 3.5

**Comment by ShivALLmyTinders** [comment]
Hmm ok, I thought that might have just been a permanent warning. When I ssh and ask for the python version it says 3.5 so I thought I had symlinked it all properly.

How do I direct it to call 3.5 and not 2.7?

**Comment by ShivALLmyTinders** [comment]
Ok so after a reset of the NAS it seems to be working again itself (albeit now with a warning about 3.5 being end of life soon... FML)

Sat Jul 25 2020 21:46:12	INFO	Executing post-process-script nzbToMedia/nzbToMedia.py for Yellowstone.2018.S02E06.720p.BluRay.x264-DEMAND
Sat Jul 25 2020 21:46:19	INFO	nzbToMedia: /share/CACHEDEV1_DATA/Download/nzbget/scripts/nzbToMedia/eol.py:147: LifetimeWarning: Python 3.5 is no longer supported.
Sat Jul 25 2020 21:46:19	INFO	nzbToMedia:   warnings.warn(msg, LifetimeWarning)
Sat Jul 25 2020 21:46:19	INFO	nzbToMedia: [21:46:19] [INFO]::MAIN: Python v3.5 will reach end of life in 50 days.
Sat Jul 25 2020 21:46:19	INFO	nzbToMedia: [21:46:19] [WARNING]::MAIN: Please upgrade to a more recent Python version.
Sat Jul 25 2020 21:46:19	INFO	nzbToMedia: [21:46:19] [INFO]::MAIN: Checking database structure...
Sat Jul 25 2020 21:46:20	INFO	nzbToMedia: [21:46:20] [INFO]::MAIN: Checking if git needs an update
Sat Jul 25 2020 21:46:20	INFO	nzbToMedia: [21:46:20] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
Sat Jul 25 2020 21:46:20	INFO	nzbToMedia: [21:46:20] [INFO]::MAIN: No update needed
Sat Jul 25 2020 21:46:20	INFO	nzbToMedia: [21:46:20] [INFO]::MAIN: nzbToMedia Version:12.1.05 Branch:master (Linux 4.14.24-qnap)
Sat Jul 25 2020 21:46:20	INFO	nzbToMedia: [21:46:20] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
Sat Jul 25 2020 21:46:20	INFO	nzbToMedia: [21:46:20] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
Sat Jul 25 2020 21:46:20	INFO	nzbToMedia: [21:46:20] [INFO]::MAIN: #########################################################
Sat Jul 25 2020 21:46:20	INFO	nzbToMedia: [21:46:20] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
Sat Jul 25 2020 21:46:20	INFO	nzbToMedia: [21:46:20] [INFO]::MAIN: #########################################################
Sat Jul 25 2020 21:46:20	INFO	nzbToMedia: [21:46:20] [INFO]::MAIN: Script triggered from NZBGet Version 21.1-testing-r2311.
Sat Jul 25 2020 21:46:20	INFO	nzbToMedia: [21:46:20] [INFO]::MAIN: Auto-detected SECTION:NzbDrone
Sat Jul 25 2020 21:46:20	INFO	nzbToMedia: [21:46:20] [INFO]::MAIN: Calling NzbDrone:TV to post-process:Yellowstone.2018.S02E06.720p.BluRay.x264-DEMAND
Sat Jul 25 2020 21:46:21	INFO	nzbToMedia: [21:46:21] [INFO]::MAIN: Attempting to verify TV fork
Sat Jul 25 2020 21:46:22	INFO	nzbToMedia: [21:46:22] [INFO]::MAIN: NzbDrone:TV fork set to default
Sat Jul 25 2020 21:46:22	INFO	nzbToMedia: [21:46:22] [INFO]::MAIN: FLATTEN: Flattening directory: /share/CACHEDEV1_DATA/Download/nzbget/downloads/completed/Yellowstone.2018.S02E06.720p.BluRay.x264-DEMAND
Sat Jul 25 2020 21:46:22	INFO	nzbToMedia: [21:46:22] [POSTPROCESS]::NZBDRONE: SUCCESS: The download succeeded, sending a post-process request
Sat Jul 25 2020 21:47:27	INFO	nzbToMedia: [21:47:27] [INFO]::MAIN: The /share/CACHEDEV1_DATA/Download/nzbget/scripts/nzbToMedia/nzbToMedia.py script completed successfully.
Sat Jul 25 2020 21:47:27	INFO	nzbToMedia: Changing to directory: /share/CACHEDEV1_DATA/Download/nzbget/scripts/nzbToMedia
Sat Jul 25 2020 21:47:27	INFO	nzbToMedia: -- Cleaning bytecode --
Sat Jul 25 2020 21:47:27	INFO	nzbToMedia: WARNING: Automatic cleanup could not be executed.
Sat Jul 25 2020 21:47:27	INFO	nzbToMedia:          If errors occur, manual cleanup may be required.
Sat Jul 25 2020 21:47:27	INFO	nzbToMedia: REASON : Error: [Errno 2] No such file or directory: 'git'
Sat Jul 25 2020 21:47:27	INFO	nzbToMedia: -- Cleaning folders: ['core', 'libs'] --
Sat Jul 25 2020 21:47:27	INFO	nzbToMedia: WARNING: Automatic cleanup could not be executed.
Sat Jul 25 2020 21:47:27	INFO	nzbToMedia:          If errors occur, manual cleanup may be required.
Sat Jul 25 2020 21:47:27	INFO	nzbToMedia: REASON : Error: [Errno 2] No such file or directory: 'git'
Sat Jul 25 2020 21:47:27	INFO	nzbToMedia: Returning to directory:  /
Sat Jul 25 2020 21:47:27	INFO	nzbToMedia: -- Cleanup finished --
Sat Jul 25 2020 21:47:27	INFO	nzbToMedia: NzbDrone: Successfully post-processed Yellowstone.2018.S02E06.720p.BluRay.x264-DEMAND!
Sat Jul 25 2020 21:47:27	INFO	Post-process-script nzbToMedia/nzbToMedia.py for Yellowstone.2018.S02E06.720p.BluRay.x264-DEMAND successful
Sat Jul 25 2020 21:47:28	INFO	Collection Yellowstone.2018.S02E06.720p.BluRay.x264-DEMAND added to history


Now I just need to find a Python 3.8 package for my QNAP!

**Comment by OneCDOnly** [comment]
> Now I just need to find a Python 3.8 package for my QNAP!

Python v3.8.3 is installable via Entware.

**Comment by ShivALLmyTinders** [comment]
Perfect thanks! If only I'd realised the power of Entware before!

**Comment by ShivALLmyTinders** [comment]
So I've used entware to update my python3 to version 3.8.3, and it was working fine after initial testing. Now all of a sudden nzbToMedia is saying it "can't execute python". My python symlink points to the right python3 file (python3.8) and it seems executable (ie when I ssh and type `python3 -V` it returns 3.8.3.

I have tried updating nzbToMedia via `git pull` but no luck there.

Can you help me @clinton-hall or @OneCDOnly ?

NZBGet log below:

Fri Aug 07 2020 12:56:59	INFO	Executing post-process-script nzbToMedia/nzbToMedia.py for Yellowstone.2018.S03E07.WEB.h264-CookieMonster
Fri Aug 07 2020 12:56:59	INFO	nzbToMedia: env: can't execute 'python': No such file or directory
Fri Aug 07 2020 12:56:59	ERROR	Post-process-script nzbToMedia/nzbToMedia.py for Yellowstone.2018.S03E07.WEB.h264-CookieMonster failed (terminated with unknown status)
Fri Aug 07 2020 12:56:59	INFO	Collection Yellowstone.2018.S03E07.WEB.h264-CookieMonster added to history

**Comment by ShivALLmyTinders** [comment]
Fixed the issue - had to add an extra symlink in the opt/bin folder as well as the usr/bin folders to ensure everything points to Python3. Seems to be working now.
