### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by ikkeenjij36** [clinton-hall/nzbToMedia#1760]
**Describe the bug**
script doesnt run while i confiugered everything as should be,came up out of nowhere

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) '.synology 3617xs...'
2. Python version '...3.5.'
3. Download Client (NZBget, SABnbzd, Transmission) '.sabnzbd...'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) '..radarr headphones and sonarr..'

**Expected behavior**
script to pp as it should

**Log**
Please provide an extract, or full debug log that indicates the issue.
`2020-08-02 12:20:16 ERROR   ::MAIN: Unable to migrate config file /volume1/scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...
2020-08-02 12:24:33 ERROR   ::MAIN: Unable to migrate config file /volume1/scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...
`
`/volume1/scripts/nzbToMedia/eol.py:147: LifetimeWarning: Python 2.7 is no longer supported.
warnings.warn(msg, LifetimeWarning)
[12:20:16] [ERROR]::MAIN: Unable to migrate config file /volume1/scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...
Changing to directory: /volume1/scripts/nzbToMedia

-- Cleaning bytecode --
Removing cleanup.pyc
Removing eol.pyc

Removing cleanup.pyc
Removing eol.pyc

-- Cleaning folders: [u'libs', u'core'] --
No folders to clean

Returning to directory:  /volume1/@appstore/sabnzbd/share/SABnzbd

-- Cleanup finished --

Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f34637fba90>> ignored`

**Comment by ikkeenjij36** [comment]
Solved by redoing the install stepps again
Threw away my config.spec and .db and started from notinhg,filled in all categories and is working as never before
Just 1 little issue it say python 3.5.is eol in 47 days need i to be worried?

**Comment by clinton-hall** [comment]
Glad you got it working again.

Don't worry too much about eol warning... in 47 days it will change the message to say that python 3.5 is no longer supported etc, but will continue to run.

In general, it is recommended that you see what support exists for updated python. 

If/When I introduce new features I will make them work in all "Supported" python versions, and then try and add support for the other "common" versions if it is possible to do so without too much inconvenience.

So, a new feature may not support Python 2.7 or Python 3.5 if that support is problematic to add. However I don't have any immediate plans to add new features at this time. And if a new feature were to be added without Python 2.7 or Python 3.4 support, I would still accept Pull Requests from the community to add that support.
