### ISSUE TITLE
Post processing no longer working after upgrade to Sab3

### ISSUE THREAD

**Issue by GTunney** [clinton-hall/nzbToMedia#1762]
I copied my nzbtomedia config on my QNAP nas from sab 2.3.9 to my new sab 3 install.

When trying to postprocess i get the below error. I have also tried the manual cleanup steps found in Issue#1585 but this resulted in the below error when trying to run.

Any help would be appreciated.

`[/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia] # find . -name "*.pyc" -exec rm -f {} ;
find: -exec requires an argument
[/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia] #
`

`/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia/eol.py:147: LifetimeWarning: Python 2.7 is no longer supported.
warnings.warn(msg, LifetimeWarning)
Changing to directory: /share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia

-- Cleaning bytecode --
Removing cleanup.pyc
Removing eol.pyc
Removing nzbToMedia.pyc

Removing cleanup.pyc
Removing eol.pyc
Removing nzbToMedia.pyc

-- Cleaning folders: [u'libs', u'core'] --
No folders to clean

Returning to directory:  /share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SABnzbd-3.0.0

-- Cleanup finished --

Traceback (most recent call last):
File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia/nzbToCouchPotato.py", line 269, in <module>
import nzbToMedia
File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia/nzbToMedia.py", line 730, in <module>
import core
File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia/core/__init__.py", line 52, in <module>
from core import logger, main_db, version_check, databases, transcoder
File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia/core/databases.py", line 11, in <module>
from core.utils import backup_versioned_file
File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia/core/utils/__init__.py", line 13, in <module>
from core.utils.common import clean_dir, flatten, get_dirs, process_dir
File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia/core/utils/common.py", line 14, in <module>
from core.utils.files import list_media_files, move_file
File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia/core/utils/files.py", line 14, in <module>
import beets.mediafile
File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia/libs/common/beets/mediafile.py", line 51, in <module>
import imghdr
ImportError: No module named imghdr`

**Comment by clinton-hall** [comment]
try
```
cd /share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia
find . -iname "*.pyc" -exec rm -f {} ;
git clean -fdx -e *.* -e !*.py[co] -e !/**/__pycache__/
git clean -fdx core libs
```

**Comment by GTunney** [comment]
Hi Clinton,

Still the same issue after running the above which also resulted in a few errors.

`[~] # cd /share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia
[/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia] # find . -iname "*                          .pyc" -exec rm -f {} ;
find: -exec requires an argument
[/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia] # git clean -fdx -                          e *.* -e !*.py[co] -e !/**/__pycache__/
-sh: !/**/__pycache__/: event not found
[/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia] # git clean -fdx c                          ore libs
[/share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/nzbToMedia] #
`

**Comment by clinton-hall** [comment]
ok... lets just try a clean install
```
cd /share/CACHEDEV1_DATA/.qpkg/QSabNZBd3/SAB_CONFIG/
mv nzbToMedia nzbToMedia.old
git clone https://github.com/clinton-hall/nzbToMedia.git
cp nzbToMedia.old/autoProcessMedia.cfg nzbToMedia/autoProcessMedia.cfg
```

see if that runs ok.

**Comment by clinton-hall** [comment]
actually... I think this might be related to #1758 

See if updating python3 via entware works for you.

**Comment by GTunney** [comment]
Ok fresh install didn't work. Installed entware and installed python3 but for some reason nzbtomedia is still picking up python 2.7.5 even though python maps to 3.8.3

```
[~] # which python
/opt/bin/python
[~] # python
Python 3.8.3 (default, Jun 12 2020, 20:24:48)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

/usr/bin/env python also returns python 3.8.3 which is what i believe the eol.py script calls?

**Comment by GTunney** [comment]
> actually... I think this might be related to #1758
> 
> See if updating python3 via entware works for you.

Hi Clinton,

Is there any particular update on this? OneCD mentioned something about nzbtomedia using the built in python on the NAS and not python3 / entware.

**Comment by clinton-hall** [comment]
I'm not sure about this. USUALLY, SABnzbd would call .py scripts in Python, so I thought it was SABnzbd that defined the Python version to be called???

I do know that @OneCDOnly is working on the sherpa project and looking to add nzbToMedia... perhaps this package will resolve this issue?

**Comment by OneCDOnly** [comment]
Yup, working fine via sherpa. :+1: 

I recall Safhire recently confirmed that post-processing scripts are executed according to their hashbang directives - not in a Python3 shell. 

As sherpa no-longer needed Python 2, I chose to make Python 3 the default:  
```
ln -s /opt/bin/python3 /opt/bin/python
```
So, now any calls to `python` invoke Python 3.

**Comment by GTunney** [comment]
> I'm not sure about this. USUALLY, SABnzbd would call .py scripts in Python, so I thought it was SABnzbd that defined the Python version to be called???
> 
> I do know that @OneCDOnly is working on the sherpa project and looking to add nzbToMedia... perhaps this package will resolve this issue?

Thanks Clinton, I’ll have to look into moving my things over from Stephanes packages. Shame as I’ve used his packages for years but seems every man and his dog is now using Sherpa on QNAPs.

**Comment by captainhowie** [comment]
Hi There
I have recently upgraded to Python3 using sabnzbd and sickchill on a QNAP NAS.  I was having some trouble setting up the post processing and have discovered that the issue is with the fact that my password has a # at the end of it and this often is removed from the .cfg file after saving and running it.

Is there a restriction on the use of the # symbol in passwords for the purposes of the .cfg script and if not, is there some sort of parenthesis required to indicate that it is part of the password and not a comment.

Thanks
Andrew
