### ISSUE TITLE
SABnzbd + SickChill Post Processing Fails w/Return log from SickBeard was not expected

### ISSUE THREAD

**Issue by sramacha2** [clinton-hall/nzbToMedia#1763]
**Describe the bug**
After SABnzbd download completes, nzbToSickBeard.py is called for PP but then it exits with message "Exit(1) SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.! (More)".
Tried it on 3 different episodes and it fails consistently with the same error.

**Technical Specs**
1. Running on Centos 8 kernel 4.18.0-193.14.2.el8_2.x86_64
2. Python version 3.6.8
3. Download Client (NZBget, SABnbzd, Transmission) SABnzbd v3.0.0-develop
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) SickChill

**Expected behavior**
Post-processing to complete successfully and episode marked as 'Downloaded'

**Log**
I have turned on 'log_debug' in autoProcessMedia.cfg and have attached the log files from SickChill and nzbToMedia. Also attached is the output of 'ls -al /usr/bin|grep python'.
[nzbtomedia.log](https://github.com/clinton-hall/nzbToMedia/files/5038520/nzbtomedia.log)
[python_ls.txt](https://github.com/clinton-hall/nzbToMedia/files/5038521/python_ls.txt)
[sickchill.log](https://github.com/clinton-hall/nzbToMedia/files/5038522/sickchill.log)

**Comment by sramacha2** [comment]
This all started happening after I enabled username+password for SABnzbd, SickChill and Radarr but didn't update the autoProcessMedia.cfg file. Updated it and now it works perfectly!
One question though, in the autoProcessMedia.cfg file, the section for Radarr does not have a place for username and password, does that mean I cannot set a username and password in Radarr?

Thanks,
-SR

**Comment by clinton-hall** [comment]
for Radarr, enter the apikey...

In fact, using the api key for SickChill works best too... still keep the user/pass on the webui, but in autoProcessMedia.cfg, put in the api key and you can remove the user/pass.

**Comment by sramacha2** [comment]
Works like a charm now :+1: 

As always appreciate your time on this!

Take care,
-SR
