### ISSUE TITLE
project icon?

### ISSUE THREAD

**Issue by OneCDOnly** [clinton-hall/nzbToMedia#1764]
Hi Clinton. :smile: 

I'm currently building nzbToMedia into a QPKG (for installation via [sherpa](https://forum.qnap.com/viewtopic.php?f=320&t=132373)) but I've just realised there doesn't seem to be an icon associated with this project. Do you have one I can use? 

Cheers mate.

**Comment by clinton-hall** [comment]
Wow. I recall discussions on sherpa a while back. I wasn't aware it was up an running. Great job.

I have never really created an icon as this has not (yet?) turned into a service that runs on its own, and Graphic design is definitely NOT my thing.
Within Github I had created a very basic "social media preview" image... but this is nothing to talk about and I don't even know where this gets displayed to be honest, and now I can't see how to display or download it!

I'm happy for you to any stock-standard icon...

**Comment by OneCDOnly** [comment]
Thanks Clinton!

Yes, sherpa has been running for about 3 years now. Loads of fun since I decided to turn it into a package manager. 

The stock icon I chose for nzbToMedia can be seen here: https://github.com/OneCDOnly/sherpa/blob/master/QPKGs/nzbToMedia/shared/.qpkg_icon.gif
