### ISSUE TITLE
SABnzbd 3.0 docker and python3 path

### ISSUE THREAD

**Issue by Riot504** [clinton-hall/nzbToMedia#1767]
After updating to the SABnzbd 3.0 docker I received the following message in sab when trying to postprocess a download

"Exit(127) /usr/bin/env: ‘python’: No such file or directory"

Updating nzbToSickBeard.py line 1 to point to the python3 dir solved the issue.

#!/usr/bin/env python
to
#!/usr/bin/env python3

**Technical Specs**
1. Running on: Unraid 6.8.3
2. Python version 3.6.9
3. Download Client: SABnzbd 3.0.0
4. Intended Media Management: Medusa
nzbtomedia script 12.1.05

**Comment by Riot504** [comment]
Just figured a lot of your users would end up looking for this so I opened an issue. Please delete if unnecessary

**Comment by clinton-hall** [comment]
There is something wrong with this docker.... `python` should be in the path. Even if it points to python2, the python command should be there.

Changing the hash-bang will break the script and prevent updating.

The better fix would be to do a simlink for the python command
`ln -sf /usr/local/bin/python3 /usr/local/bin/python`

**Comment by clinton-hall** [comment]
which docker?
`linuxserver/sabnzbd` or `sabnzbd/sabnzbd`?

**Comment by Riot504** [comment]
linuxserver/sabnzbd

**Comment by Riot504** [comment]
I would have to make that symlink again every time that docker is updated though right?

**Comment by clinton-hall** [comment]
So they have confirmed that python will be linked in future builds of docker. But they are still migrating away from py2.
It appears the `unstable` tag should work. Otherwise do the edit you have provided here, but once the docker updates and python is linked, I would recommend doing a `git reset --hard` to revert the changes and allow you to keep updating.

Thanks for posting this.

**Comment by clinton-hall** [comment]
@Riot504 
new version of sab image just pushed. Py2 is removed and `python` is symlinked to `python3`

So if you update your docker, you should be able to reset the changed to the hash-bang and nzbToMedia should run in python3

**Comment by Riot504** [comment]
Updated docker and reset nzbToMedia. Everything working as it should. Thanks for your help and for the great script.

**Comment by clinton-hall** [comment]
Glad to hear. Let me know if you have any issues.
