### ISSUE TITLE
Post Process failure with latest nzbToMedia

### ISSUE THREAD

**Issue by ronrosenfeld** [clinton-hall/nzbToMedia#1775]
**Describe the bug**
Recently updated SickChill windows, which included an install of python 3.8.5.  But newly downloaded programs now show PP failure in nzbGet.

After installation, error message in log   `nzbToSickBeard: Could not find file C:\Sickchill\python\python.exe`

So edited nzbGet config file to add line to correct the directory name:

    ShellOverride=.py=C:/Sickchill/Python3/python.exe

Now showing error messages as seen in **log** below.

One of those messages referred to installing pywin32 which I tried (in the Python3 folder):

```
C:\SickChill\Python3>pip install pywin32
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already satisfied: pywin32 in c:\python27\lib\site-packages (228)

C:\SickChill\Python3>
```
Please note that I have a critically important financial program that requires Python 2.7 and will not run with Python 3.  It broke when I added the Python3 path to the Environment PATH entry.

It seems to me that I've done something wrong setting this up causing nzbToMedia to not be able to find all the files it needs.

Any help appreciated.

    

**Technical Specs**
1. Running on:  `Windows 10 Pro x64`
2. Python version `3.8.5` and `2.7.18` are both installed
3. Download Client: `NZBget`
4. Intended Media Management: `Sickchill`

**Expected behavior**
Download to succeed
**Log**
```
Thu Sep 17 20:01:51 2020	INFO	Reloading...
Thu Sep 17 20:01:52 2020	INFO	nzbget 21.0 service-mode
Thu Sep 17 20:01:52 2020	INFO	Scheduler: setting download rate to 7000 KB/s
Thu Sep 17 20:02:04 2020	INFO	Post-processing again Shtisel.S01E08.1080p.NF.WEB-DL.DD.2.0.H.264-NYH-WhiteRev
Thu Sep 17 20:02:04 2020	INFO	Shtisel.S01E08.1080p.NF.WEB-DL.DD.2.0.H.264-NYH-WhiteRev returned from history back to download queue
Thu Sep 17 20:02:04 2020	INFO	Queueing Shtisel.S01E08.1080p.NF.WEB-DL.DD.2.0.H.264-NYH-WhiteRev for post-processing
Thu Sep 17 20:02:04 2020	INFO	Cleaning up Shtisel.S01E08.1080p.NF.WEB-DL.DD.2.0.H.264-NYH-WhiteRev
Thu Sep 17 20:02:04 2020	INFO	Nothing to cleanup for Shtisel.S01E08.1080p.NF.WEB-DL.DD.2.0.H.264-NYH-WhiteRev
Thu Sep 17 20:02:04 2020	INFO	Executing post-process-script nzbToSickBeard.py for Shtisel.S01E08.1080p.NF.WEB-DL.DD.2.0.H.264-NYH-WhiteRev
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard: fatal: Not a git repository (or any of the parent directories): .git
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard: Changing to directory: C:\ProgramData\NZBGet\scripts
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard: -- Cleaning bytecode --
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard:          If errors occur, manual cleanup may be required.
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard: REASON : Error Code: 128
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard: Directory is not a git repository
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard: Force cleaning folder: libs
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard: Skipping required subfolders ['common', 'custom', 'py2', 'win']
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard: Force cleaning folder: core
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard: Skipping required subfolders ['auto_process', 'extractor', 'utils']
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard: Returning to directory:  C:\WINDOWS\system32
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard: -- Cleanup finished --
Thu Sep 17 20:02:05 2020	INFO	nzbToSickBeard: Please install pywin32
Thu Sep 17 20:02:05 2020	ERROR	Post-process-script nzbToSickBeard.py for Shtisel.S01E08.1080p.NF.WEB-DL.DD.2.0.H.264-NYH-WhiteRev failed (terminated with unknown status)
Thu Sep 17 20:02:05 2020	INFO	Collection Shtisel.S01E08.1080p.NF.WEB-DL.DD.2.0.H.264-NYH-WhiteRev added to history
```

**Comment by clinton-hall** [comment]
I think what you need is
```
C:\SickChill\Python3>C:/Sickchill/Python3/python.exe -m pip install pywin32
```
You will note that when you tried running `C:\SickChill\Python3>pip install pywin32` it gave you errors about python2.7 because pip was trying to install pywin32 into python2.7...

**Comment by ronrosenfeld** [comment]
Thanks. That did it. 

My inexperience led me to believe that since the `python --version` command returned the `3.8.5`, the `pywin` would get installed there.  Or was it the `-m` flag that made the difference?

In any event, I really appreciate your program and the support you've been providing over the years.

**Comment by clinton-hall** [comment]
No worries.
It wasn't the '-m' flag. The difference was actually calling the correct python version, and then calling pip through python.
You could also use your previous xommand, but call the pip executable that is associated with the correct python version. But I wasn't sure where that was (probably same dir as your python exe) so I went with the one I knew.

Multiple python versions can make like fun.
