### ISSUE TITLE
NZbtoWatcher.py executable

### ISSUE THREAD

**Issue by GTunney** [clinton-hall/nzbToMedia#1780]
Everytime there is an update for Nzbtomedia or it's freshly installed I need to set nzbtowatcher.py as executable due to the executable bit missing in source.

All other nzbtoxxxxxx.py are fine.

**Comment by clinton-hall** [comment]
Thanks for pointing this out. Updated this in Nightly.
This will eventually merge to master, so you won't have to fix this after the next update.
