### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by clarky0000** [clinton-hall/nzbToMedia#1784]
Im getting this for all of my downloads in SABNZBD now:

/scripts/nzbToMedia/eol.py:147: LifetimeWarning: Python 2.7 is no longer supported.
warnings.warn(msg, LifetimeWarning)
Changing to directory: /scripts/nzbToMedia

-- Cleaning bytecode --

No bytecode to clean

-- Cleaning folders: [u'libs', u'core'] --
No folders to clean

Returning to directory:  /etc/sabnzbd

-- Cleanup finished --

Traceback (most recent call last):
File "/scripts/nzbToMedia/nzbToNzbDrone.py", line 256, in <module>
import nzbToMedia
File "/scripts/nzbToMedia/nzbToMedia.py", line 730, in <module>
import core
File "/scripts/nzbToMedia/core/__init__.py", line 52, in <module>
from core import logger, main_db, version_check, databases, transcoder
File "/scripts/nzbToMedia/core/databases.py", line 11, in <module>
from core.utils import backup_versioned_file
File "/scripts/nzbToMedia/core/utils/__init__.py", line 14, in <module>
from core.utils.download_info import get_download_info, update_download_info_status
File "/scripts/nzbToMedia/core/utils/download_info.py", line 14, in <module>
database = main_db.DBConnection()
File "/scripts/nzbToMedia/core/main_db.py", line 65, in __init__
self.connection = sqlite3.connect(db_filename(filename), 20)
sqlite3.OperationalError: unable to open database file

**Technical Specs**
Running on a Rasperry Pi on DietPie
Download Client - SABnbzd
Intended Media Management - Sonarr

I've read other threads indicating that the SQL error can be permission related but Im not sure what account I need to set the permissions for. If someone can tell me how to confirm that would be great.

Cheers,
Clarky

**Comment by clinton-hall** [comment]
find out what user is running SABnzbd
```
ps | grep sab
```
this should show the sab process that is running, and which user the service is running as.

Make sure that user has full read and write permissions for /scripts/nzbToMedia and all sub folders etc.
In particular, check permissions on /scripts/nzbToMedia/nzbtomedia.db

if that all looks ok. try making a backup/copy of nzbtomedia.db, then delete it and see if the script runs ok.

**Comment by clarky0000** [comment]
for some reason I dont get anything back when i run 
ps | grep sab 
even sudo ps | grep sab

is there some other way to find this?

**Comment by clinton-hall** [comment]
if there is no /scripts/nzbToMedia/nzbtomedia.db file then the issue is probably that the user running sabnzbd doesn't have write permissions in the /scripts/nzbToMedia/ directory.
