### ISSUE TITLE
nzbtomedia.db is re-created as read-only.

### ISSUE THREAD

**Issue by MrCee** [clinton-hall/nzbToMedia#1792]
**Technical Specs**
1. Running on 'SYNOLOGY'
2. Python version '3.7.7'
3. Download Client (NZBget, SABnbzd, Transmission) 'SABNZBD/DOWNLOAD STATION'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) 'ALL'

Sometimes when I'm required to clear out a few files, deal with problem downloads, and do a manual run of TorrentToMedia.py I've had to delete nzbtomedia.db and let it be re-created. 

Still today, I find myself in a new scenario when logs say files are/have been processed and moved, and they are not. I don't have an example for you right now (usually to do with older entries in the db from what I see), so deleting nzbtomedia.db and manually running TorrentToMedia.py fixes this up. (it doesn't happen often).

I'm currently on nightly, and just wanted to give you the heads up that nzbtomedia.db has only begun to be re-created as read-only, which is new to my system, and not something I have needed to worry about setting the permissions for after recreation in the past. Was kind of hoping you could make an adjustment in the code.

One thing I have changed lately is upgrade Python via the Syno package centre. 

 Many thanks

**Comment by clinton-hall** [comment]
Thanks for reporting.

I have had a bit of a look and interestingly this is created by the sqlite3.connect('nzbtomedia.db') command that (in a world where it can create/write a file) should create the file with read/write permissions.

I'll keep looking, but I can't see how I can make this change.

Can you confirm that the parent directory has write permissions?

**Comment by MrCee** [comment]
Thanks, Clinton.
Yes, the parent folder does have write permissions, I should have mentioned, and I have since repeated the same results with  permissions set recursively to `rwxrwxrwx  root root`

In the past, I was running a nightly bash script to check if the logs were ever stuck at a SELECT statement and then fixing things up. Maybe truncating the db `> nzbtomedia.db` is a better way to go. There's nothing in my logs currently to show it's been used lately.

```
#!/bin/bash
VARDBERROR=$(tail -n 1 /volume1/@appstore/nzbToMedia/logs/nzbtomedia.log | grep -i  --line-buffered  'SELECT \* FROM downloads WHERE')

if [ -n "$VARDBERROR" ]  ; then
echo "nzbToMedia.db SELECT problem. External script will attempt to fix" >> /volume1/@appstore/nzbToMedia/logs/nzbtomedia.log
> /volume1/@appstore/nzbToMedia/nzbtomedia.db
/volume1/@appstore/nzbToMedia/TorrentToMedia.py
fi
```

**Comment by MrCee** [comment]
In summary, the answer to this permission problem is not to delete the `nzbtomedia.db` file.
Just truncate it to nothing. `> /your_path_nzbToMedia/nzbtomedia.db`
