### ISSUE TITLE
QQ: universal script

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1793]
This is probably a yes or no question but I've been experimenting and searching and haven't found an answer.

I would like to run a script, on all categories, right before the end of nTM's run.
regardless of success or failure of the postproc, I need a script to run right at the end.

I found setting a custom script at the end was only running the script, not the regular postproc first, then the custom script.

Suggestions?

**Comment by clinton-hall** [comment]
The way Custom Script was intended, was as a script to be run for categories where regular PP isn't to be run.

So, the way it works now, it is either postproc, or custom script. Not one, and then the other.

What downloader are you using? What is the custom script supposed to be doing after the postproc?

If using NZBget you can specify multiple scripts to run.
For other downloaders, you can create an sh/bat file that will accept all input parameters, then call nzbToMedia (passing in the correct params) and then call the custom script after.

**Comment by mgaulton** [comment]
SABnzbd is the downloader.
What's happening is possibly unique to me. I have a machine that hosts Emby, running as a user. Then I have a vpn namespace where all apps run as another user. neither are root equiv. Emby creates metadata files, SAB launches postproc, some of the files aren't owned by the vpn user, so nTM marks jobs as failed, because it can't remove or update the metadata files. I have a script that runs periodically to update ownerships to the vpn user, but it's a race.
I was hoping to have a step that says when you're done this job, run that script to update ownership so the next job doesn't choke on the perms.

**Comment by clinton-hall** [comment]
Interesting... Even if I changed the process so that nzbToMedia could launch the custom script during (or at the end) of processing, I'm not sure this would work for this case... the script would be launched as the same user that SAB is running as (vpn user).

In short, if nzbToMedia (vpn user) can't remove or update the metadata files, then it wouldn't be able to update ownership (unless the script specifically stored and passed the root/su password... and this would not be the best idea).

**Comment by mgaulton** [comment]
True! i hadn't thought of that.
I'm trying the bash route at the moment, see how that goes.

**Comment by mgaulton** [comment]
sadly, its still not using py3 for my nTM :(

**Comment by clinton-hall** [comment]
What does your Bash script look like?

In theory, if you did the following
```
#!/bin/bash
/usr/bin/python3 /path/to/nzbToMedia.py "$@"
```
and has this script called `myScript.sh`
then set SABnabd to call `myScript.sh`
this should start nzbToMedia using Python3 and should pass in all of the variables needed.
Potentially, you could add routines to run before/after nzbToMedia so long as the environment it is running in has the permissions needed.

**Comment by mgaulton** [comment]
Realized i hadn't switched all the jobs to the bash script, likely why it was running py2.
that's basically what I had, calling my permissions script right before the nTM part. Still waiting to catch a job in action.
I think i'm good now, thank you for your help, i'll keep an eye on things.
You're awesome as always.

**Comment by mgaulton** [comment]
So update. Seems to be working, I had to add a sudo exception for the user to the one script so it would run, but seems stable. Thank you again.

**Comment by clinton-hall** [comment]
No worries... glad you got it working.
Just did a quick search for sudo exception... brilliant. You can actually specify the path to a single script that can call sudo without password...

**Comment by mgaulton** [comment]
Yes that's what I did. For the bash script  only that script is allowed for that user.  Sent from my Galaxy
-------- Original message --------From: Clinton Hall <notifications@github.com> Date: 2020-11-12  8:38 p.m.  (GMT-05:00) To: clinton-hall/nzbToMedia <nzbToMedia@noreply.github.com> Cc: mgaulton <markgaultonsecurity@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [clinton-hall/nzbToMedia] QQ: universal script (#1793) 
No worries... glad you got it working.
Just did a quick search for sudo exception... brilliant. You can actually specify the path to a single script that can call sudo without password...

**Comment by mgaulton** [comment]
QQ: running the bash script, i just get "ran postproc.sh" instead of any kind of logging in the SAB interface. Is there a way to return at least the success/fail message from nTM to have it show ?

**Comment by clinton-hall** [comment]
it shouldn't be too difficult to return the exit code and last line of output...
The format for capturing last line of output (both stdout and std err is `|& tail -1`
This can be passed into a variable `output` to return later using output=$(<command> |& tail -1`)
The exit or return-code can be captured to `status` using `status=$?` immediately after the command has run.

So, to do all of this, calling the command `/usr/bin/python3 /path/to/nzbToMedia.py "$@"`

```
#!/bin/bash
#execute nTM and capture the last line of logging to output using using |& tail -1
output=$(/usr/bin/python3 /path/to/nzbToMedia.py "$@" |& tail -1)
#get the return code from nTM
status=$?
#do other stuff if needed
#now print the nTM last output line
echo $output
#now return the nTM return code
exit $status
```

**Comment by mgaulton** [comment]
ahh let me try that. thank you

**Comment by clinton-hall** [comment]
ah, yes, that will do it.

**Comment by mgaulton** [comment]
just an update, I discovered a seeming issue, trying to track down an issue, i discovered that the shell script wasn't launching nTM properly. 

This line was passing $0 to nTM, which was casuing it to a unparameterized run
/usr/bin/python3 /path/to/nzbToMedia.py "$@"

I had to explictly change it to the below to give it the parameters in the right order, i will test this.
/usr/bin/python3 /opt/Sick-Beard/autoProcessTV/nzbToMedia.py "$1" "$2" "$3" "$4" "$5" "$6" "$7"
