### ISSUE TITLE
Doubts regarding transmission and nzbToMedia post-processing to Radarr in case of just .mkv (no folder) downloads

### ISSUE THREAD

**Issue by neothematrix** [clinton-hall/nzbToMedia#1794]
Hello!
I'm struggling a little to understand what the issue could be:
I setup Radarr, Transmission and nzbToMedia and I've been using them for a while.
It seems the postprocessing is not always working, meaning Radarr refuses to process the movie when called from nzbToMedia upon torrent completion, this happens ONLY if the downloaded movie doesn't have its own folder, so if it's downloaded just as .mkv directly into the "category" folder (MOVIES-FLEXGET in my specific case).
Before I paste the whole config/log, here's the relevant parts of logs coming from nzbtomedia and Radarr:

### nzbToMedia.log
>2020-11-06 23:05:29 DEBUG   ::RADARR: Opening URL: http://radarr:7878/radarr/api/command with PARAMS: {'name': 'DownloadedMoviesScan', 'path': '/downloads/transmission/completed/MOVIES-FLEXGET', 'downloadClientId': '6e669e0471e5abf0fb96e7acafdeea6636e25d59', 'importMode': 'Copy'}
2020-11-06 23:05:29 POSTPROCESS::RADARR: Starting DownloadedMoviesScan scan for Movie.Title.Removed.2020.ENG.AC3.Sub.1080p.WebRip.x264.mkv

### radarr.debug.log
>2020-11-6 23:05:29.6|Debug|Api|[GET] /api/command: 401.Unauthorized (3 ms)
2020-11-6 23:05:30.1|Debug|Api|[POST] /api/command: 201.Created (332 ms)
2020-11-6 23:05:30.1|Warn|DownloadedMovieCommandService|External directory scan request for unknown download 6e669e0471e5abf0fb96e7acafdeea6636e25d59, attempting normal import. [/downloads/transmission/completed/MOVIES-FLEXGET]
2020-11-6 23:05:30.1|Debug|Parser|Parsing string 'MOVIES-FLEXGET'
2020-11-6 23:05:30.1|Debug|Parser|Unable to parse MOVIES-FLEXGET
2020-11-6 23:05:30.1|Debug|DownloadedMovieImportService|Unknown Movie MOVIES-FLEXGET
2020-11-6 23:05:30.2|Debug|Api|[GET] /api/command/1677016?media_folder=%2Fdownloads%2Ftransmission%2Fcompleted%2FMOVIES-FLEXGET: 200.OK (68 ms)
2020-11-6 23:05:50.4|Debug|Api|[GET] /api/command/1677016?media_folder=%2Fdownloads%2Ftransmission%2Fcompleted%2FMOVIES-FLEXGET: 200.OK (3 ms)

it looks like the postprocessing request contains only the "MOVIES-FLEXGET" path info only and no reference to the downloaded file, and Radarr doesn't recognize just the "MOVIES-FLEXGET" info since it doesn't parse to any movie name.

I must add, a few minutes later, Radarr seems to correctly process the movie anyways, but probably because it detects that download is completed on its own connecting directly to transmission.

If the movie is downloaded with its own folder, everything works as expected.

thanks for any hint you could provide!

**Comment by clinton-hall** [comment]
nzbToMedia should take the single file download and put it into its own directory in the outputDirectory

The only reason I can see that this wouldn't be happening is if you have set
```
[Radarr]
  [[MOVIES-FLEXGET]]
        Torrent_NoLink = 1
```

I suggest you try the following.
```
[Radarr]
  [[MOVIES-FLEXGET]]
        Torrent_NoLink = 0

[Torrent]
    useLink = hard
    outputDirectory = /downloads/transmission/proessed
```
and see if this works as required.

**Comment by neothematrix** [comment]
hello @clinton-hall ,
sorry for the very late reply, indeed I had Torrent_NoLink=1 and also outputDirectory = default_downloadDirectory, that turns out was the reason I initially set torrent_NoLink as I had all files renamed with ".cp(imdbid)" appended, and I wanted to avoid that.
But now I understand the worflow, with both Torrent_NoLink=0 and outputDirectory != default_downloadDirectory everything worked beautifully!
thanks a lot for the spot-on hint!

**Comment by clinton-hall** [comment]
Glad you have it working.
