### ISSUE TITLE
Post Process failure

### ISSUE THREAD

**Issue by ronrosenfeld** [clinton-hall/nzbToMedia#1797]
**Describe the bug**
Post process failure in nzbGet

This is a new machine and I have moved nzbGet and SickChill here.  Trying to get nzbToMedia to work.

I used  [Windows From Source](https://github.com/clinton-hall/nzbToMedia/wiki/installation#windows-from-source) installation method using the `git install` option.

**Technical Specs**
1. Running on Windows 10 Pro 64-big
2. Python version '**3.9.0**'
3. Download Client  '**NZBGet**'
4. Intended Media Management  '**Sickchill**'

**Expected behavior**
successful post-processing

**Log**
```
Wed Dec  2 17:00:06 2020	INFO	Reloading...
Wed Dec  2 17:00:06 2020	INFO	nzbget 21.0 service-mode
Wed Dec  2 17:00:06 2020	INFO	Scheduler: setting download rate to 7000 KB/s
Wed Dec  2 17:00:18 2020	INFO	Post-processing again Star.Trek.Deep.Space.Nine.S01E06.SDTV.Captive.Pursuit-Obfuscated
Wed Dec  2 17:00:18 2020	INFO	Star.Trek.Deep.Space.Nine.S01E06.SDTV.Captive.Pursuit-Obfuscated returned from history back to download queue
Wed Dec  2 17:00:18 2020	INFO	Queueing Star.Trek.Deep.Space.Nine.S01E06.SDTV.Captive.Pursuit-Obfuscated for post-processing
Wed Dec  2 17:00:18 2020	INFO	Cleaning up Star.Trek.Deep.Space.Nine.S01E06.SDTV.Captive.Pursuit-Obfuscated
Wed Dec  2 17:00:18 2020	INFO	Nothing to cleanup for Star.Trek.Deep.Space.Nine.S01E06.SDTV.Captive.Pursuit-Obfuscated
Wed Dec  2 17:00:19 2020	INFO	Executing post-process-script nzbToMedia\nzbToSickBeard.py for Star.Trek.Deep.Space.Nine.S01E06.SDTV.Captive.Pursuit-Obfuscated
Wed Dec  2 17:00:19 2020	INFO	nzbToSickBeard: C:\Program Files\Python39\python.exe: can't open file 'C:\Windows\system32\L': [Errno 2] No such file or directory
Wed Dec  2 17:00:19 2020	ERROR	Post-process-script nzbToMedia\nzbToSickBeard.py for Star.Trek.Deep.Space.Nine.S01E06.SDTV.Captive.Pursuit-Obfuscated failed (terminated with unknown status)
Wed Dec  2 17:00:19 2020	INFO	Collection Star.Trek.Deep.Space.Nine.S01E06.SDTV.Captive.Pursuit-Obfuscated added to history
```
**System Variables**
![image](https://user-images.githubusercontent.com/18516066/100937530-1f190d00-34c1-11eb-888d-93ea9a9c15fa.png)

I have also tried various "shell override" entries in `nzbGet` but none have enabled successful postprocessing.  Aslo tried using a shell override to an installation of python 3.8 that was installed with sickchill, to no avail.

Thanks for any help.

**Comment by clinton-hall** [comment]
Ok, this does appear to be an issue with either Python or NZBGet. It isn't correctly calling nzbToMedia.

https://forum.nzbget.net/viewtopic.php?t=2565

I note the link above does only suggest using shell override, which you indicate you have already done... 
Have you used
```
.py="C:\Program Files\Python39\python.exe"
```

**Comment by ronrosenfeld** [comment]
Yes, I did try that. Surprisingly, I see:

 

 

Wed Dec  2 19:01:50 2020            ERROR  nzbToMedia: Could not find file "C:\Program Files\Python39\python.exe"

**Comment by ronrosenfeld** [comment]
*Ok, this does appear to be an issue with either Python or NZBGet. It isn't correctly calling nzbToMedia.*

In addition to setting the extension path not working `(Could not find file "C:\Program Files\Python39\python.exe)`, I should also mention that NZBGet is not calling the extension script at all.  I didn't mention that at first thinking it was an issue strictly with nzbGet, but maybe there's a relation between that and this.

In order to run the extension script, I have been manually triggering it within nzbGet after turning the script "on" in one of that programs dropdowns.  Previous reports have indicated that can be a problem if the category ('tv' in this case) is not set correctly.  But it sure seems to be properly set.

And I haven't changed anything since using these programs on the old computer.  Even using the same config files (and the drives and folder paths are all the same.

**Comment by ronrosenfeld** [comment]
Well, the problem with not being able to successfully run the script had to do with the Python installation.

 - I uninstalled 3.9 (which I had downloaded from python.org), 
 - I installed 3.8 from `activestate` (free for registration), and I have used them before.  
    - I deselected the options to add it to the PATH environmental variable, and to set file associations; 
    - I set the nzb script Shell Overide to `.py=C:\Python38\python.exe` 
 - and post-processing seems to work without a hitch.

The only problem I have now is that the script will not run automatically.  

I am thinking there must be a setting in nzbGet that got fubar'd when I copied the config file over from my old machine, but I haven't found that yet.

**Comment by ronrosenfeld** [comment]
Whew.  Finally found it.  In the "categories" section of nzbGet there is another place where the proper script (to run on a given category) as to be defined. This was not defined properly, so no scripts were being set to run.

Once defined properly there, everything now works.

So I had two problems:

 - Bad python install -- scripts would not run successfully
 - Bad setting in nzbget -- scripts would not be triggered to run automatically.

Maybe this thread will help someone on the future.

(Reinstalling programs is my least favorite thing about building a new computer).

Ron

**Comment by clinton-hall** [comment]
glad you got it all working.
