### ISSUE TITLE
Exit(-1) Cannot run script /share/Applications/nzbToMedia/nzbToRadarr.sh

### ISSUE THREAD

**Issue by LennyM8472** [clinton-hall/nzbToMedia#1798]
**Describe the bug**
Cannot run script /share/Applications/nzbToMedia/nzbToRadarr.sh

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) QNAP QTS 5.4
2. Python version Python 3
3. Download Client (NZBget, SABnbzd, Transmission) SABnbzd
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) Radarr

**Expected behavior**

**Log**
Please provide an extract, or full debug log that indicates the issue.

Hi,

I have a really strange problem:

upfront, for SickChill everythings runs smooth with the setup of nzbToMedia.

1. Upon completion of a Radarr download with Sabnzbd and running the nzbToRadarr script (via the bash script nzbToMedia/nzbToRadarr.sh to access python3)

`#!/bin/bash
/opt/QPython3/bin/python3 /share/Applications/nzbToMedia/nzbToRadarr.py "$@"`

I receive the follwoing error in Sabnzbd 

`Exit(-1) Cannot run script /share/Applications/nzbToMedia/nzbToRadarr.sh`

2. The strange thing is that running the script nzbToRadarr.sh with ssh works perfectly fine

3. I have no clue why sabnzbd can't run script. Any ideas?

Best regards
Lenny

**Comment by clinton-hall** [comment]
I would start looking at permissions for /share/Applications/nzbToMedia/nzbToRadarr.sh

This needs to have execute permissions for the user that runs SABnzbd App.

**Comment by LennyM8472** [comment]
unfortunately it is not the problem, all files are accessible via 777 or 757 permissions.

**Comment by clinton-hall** [comment]
if the scripts runs correctly from terminal, but fails when called from SABnzbd, then this must relate to the environment? in which case the issue is with SABnzbd app.
