### ISSUE TITLE
KeyError: (3, 9) when running post-processing in SABNZDB to Medusa

### ISSUE THREAD

**Issue by Kvothe1970** [clinton-hall/nzbToMedia#1800]
Describe the bug
I used to have the integration of Post Processing from SabNZDB to Medusa working. Suddenly this stopped working and I am not sure if I broke something.

When running the script, the following error is logged:

Traceback (most recent call last): File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToSickBeard.py", line 270, in import nzbToMedia File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/nzbToMedia.py", line 727, in eol.check() File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/eol.py", line 99, in check warn_for_status(version, grace_period) File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/eol.py", line 140, in warn_for_status days_left = lifetime(version) File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/eol.py", line 70, in lifetime time_left = PYTHON_EOL[(major, minor)] - now

This is the config in autoProcessMedia.cfg

```
[SickBeard]
#### autoProcessing for TV Series
#### tv - category that gets called for post-processing with SB
[[tv]]
enabled = 1
host = localhost
port = 7073
apikey = ""
username = ""
password = ""
###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
web_root = ""
ssl = 0
fork = auto
delete_failed = 0
# Enable/Disable linking for Torrents
Torrent_NoLink = 0
keep_archive = 1
process_method = ""
# force processing of already processed content when running a manual scan.
force = 0
# tell SickRage/Medusa to delete all source files after processing.
delete_on = 1
# tell Medusa to ignore check for associated subtitle check when postponing release
ignore_subs = 0
extract = 1
nzbExtractionBy = Downloader
# Set this to minimum required size to consider a media file valid (in MB)
minSize = 0
# Enable/Disable deleting ignored files (samples and invalid media files)
delete_ignored = 0
##### Enable if SickBeard is on a remote server for this category
remote_path = 0
##### Set to path where download client places completed downloads locally for this category
watch_dir = ""
##### Set the recursive directory permissions to the following (0 to disable)
chmodDirectory = 0
```

Medusa Info: |
Branch: master
Commit: ce68da57b3878591f77c21bb2acf28e6a58269faVersion: .0.5.0
Database: 44.17
-- | --
Python Version: | 3.9.0 (default, Nov 30 2020, 13:01:15) [GCC 8.4.0]
SSL Version: | OpenSSL 1.1.1h 22 Sep 2020
OS: | Linux-4.2.8-armv7l-with-glibc2.27
Locale: | en_US.UTF-8

I had a look at https://github.com/pymedusa/Medusa/wiki/NZBtoMedia but I am pretty sure that a) have not changed a thing, and b) the sections are as outlined there: but I would appreciate any help. I checked the logs for nzbtomedia and they are not being updated after a download is finished.

**Comment by clinton-hall** [comment]
you updated python to V3.9?

currently python 3.9 is only available in nightly branch. I'll look to merge to master soon.

**Comment by Kvothe1970** [comment]
I am using oneCDs Sherpa script to manage my setup. I did update the Entware IPKGs a while ago and I am pretty sure it happened then. So, basically I should be looking at downgrading for now`? I will have a chat with oneCD and see if he can do that with Sherpa. If not, I will just wait until you merge and then upgrade. Thanks for the explanation, Clinton.

**Comment by Kvothe1970** [comment]
For the record, I just switched to the nightly branch and post processing worked again :) I will switch back to master once you have merged.

**Comment by clinton-hall** [comment]
This should now be working in master. Please let me know if there are any issues.

**Comment by Kvothe1970** [comment]
Will do, thanks a bunch for the quick update, Clinton. I will change back to master branch and send feeback via a new issue, if something else comes up.

**Comment by Kvothe1970** [comment]
something didn't work. Oddly enough, the only thing I changed was switching back to master. 

10:00:59] [INFO]::MAIN: Loading config from [/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/autoProcessMedia.cfg]
[10:00:59] [INFO]::MAIN: Python v3.9 will reach end of life in 1756 days.
[10:00:59] [INFO]::MAIN: Checking database structure...
[10:00:59] [INFO]::MAIN: Database upgrade required: Initial Schema
[10:01:00] [INFO]::MAIN: Checking if git needs an update
[10:01:00] [INFO]::MAIN: No update needed
[10:01:00] [INFO]::MAIN: nzbToMedia Version:9d64c2f47869584ebf3ca269632e1f03a461f99e Branch:master (Linux 4.2.8)
[10:01:01] [INFO]::MAIN: #########################################################
[10:01:01] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[10:01:01] [INFO]::MAIN: #########################################################
[10:01:01] [INFO]::MAIN: Script triggered from SABnzbd Version 3.1.1.
[10:01:01] [ERROR]::MAIN: Unable to locate a section with subsection:tv enabled in your autoProcessMedia.cfg, exiting!
[10:01:01] [ERROR]::MAIN: A problem was reported in the /share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToSickBeard.py script.
Changing to directory: /share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /share/CACHEDEV1_DATA/.qpkg/SABnzbd/SABnzbd

-- Cleanup finished --

**Comment by Kvothe1970** [comment]
I did not make any change in the autoProcessMedia.cfg file prior to testing: and this looks like a vanilla file, right? I should have backed up that file. Let me see if I remember how to configure this to work from sab to medusa

```
[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[tv]]
        enabled = 0
        host = localhost
        port = 8081
        apikey = ""
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        process_method = ""
        # force processing of already processed content when running a manual scan.
        force = 0
        # tell SickRage/Medusa to delete all source files after processing.
        delete_on = 0
        # tell Medusa to ignore check for associated subtitle check when postponing release
        ignore_subs = 0
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""
        ##### Set the recursive directory permissions to the following (0 to disable)
        chmodDirectory = 0
```

**Comment by Kvothe1970** [comment]
Yep, sorted it out :) https://github.com/pymedusa/Medusa/wiki/NZBtoMedia still seems to be up to date. Post Processing from SAB to Medusa using Python 3.9 works! Cheers
