### ISSUE TITLE
Feature Request: Readarr Support

### ISSUE THREAD

**Issue by markfaine** [clinton-hall/nzbToMedia#1803]
Feature Request:  Readarr support.  I see you have support for LazyLibrarian but to the best of my knowledge that project is dead.  Readarr is still very new but it should be very similar to the existing radarr support, hopefully.

Thanks

**Comment by jangrewe** [comment]
seconded!

**Comment by clinton-hall** [comment]
ok, this one completely slipped by and I forgot about it.
I'll try and find some time to set up a Readarr instance and start testing.

**Comment by landcraft** [comment]
Just set up Readarr so would also be very keen on this!

**Comment by SomeGuyKai** [comment]
Sorry to bump an old thread. Just installed Readarr and was seeing it this was still being worked on.

**Comment by clinton-hall** [comment]
I haven't started working on this. To be honest I'm not sure that anything is likely to happen anytime soon.
For me at the moment I am trying to ensure this project is maintained and functioning, but I haven't had any time to work on new development.

**Comment by markfaine** [comment]
Understandable, keeping the lights on is far more important.

**Comment by bushbrother** [comment]
+1 from me for this :)
