### ISSUE TITLE
QQ: ignored files

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1806]
I noticed this in the logs and I'd like to actually keep the release srt and nfo but i'm not finding a setting for this in nTM and wondering what I need to change?

20x2021-01-16 13:51:14 DEBUG   ::MAIN: Ignored file Star Trek Picard - S01E01 - REPACK 720p CBS WEB-DL AAC2 0 x264 2-TEPES.rar has been removed ...                        x
0px2021-01-16 13:51:14 DEBUG   ::MAIN: Ignored file Star Trek Picard - S01E01 - REPACK 720p CBS WEB-DL AAC2 0 x264 2-TEPES.1.rar has been removed ...

**Comment by clinton-hall** [comment]
in autoProcessMedia.cfg
```
[sickbeard]
    [[tv]]
        delete_ignored = 0
```
if this is set to 1, then it will delete the ignore files at the cleanup stage of the process.

**Comment by mgaulton** [comment]
Ah, so SB is the thing ignoring the files. Hmm. Thanks, I'll keep digging.

**Comment by clinton-hall** [comment]
I think there are options in SB renaming to "Move original nfo" and "Move extras" or is it "Keep extras" something like that.
If those options are checked, then SB should move these files and therefore nTM wouldn't delete them during the cleanup.

**Comment by mgaulton** [comment]
I checked those first.
SRT, SRR, NFO are all associated and move associated is on, that's how I
came to ask here.
I'll keep digging, thanks.

**Comment by clinton-hall** [comment]
the logs entries you showed above indicate the .rar files been removed after processing.... 
Can you show full logging for a download where .srt and .nfo are deleted? 
I wonder if, for torrents, the issue is that we aren't processing these files for SB to see?

**Comment by mgaulton** [comment]
Let me see if I can find one and I'll share it.
That job in particular was from SAB, as I use 2 instances of nTM, one for
torrent and one for nzb.
