### ISSUE TITLE
sabnzbd: failed to post process

### ISSUE THREAD

**Issue by zerosaber071** [clinton-hall/nzbToMedia#1808]
Good day!

First time posting, apologies if I break any rules. I also want to note that my competency with scripting and ubuntu is beginner at best, I had a friend a long time ago help me set this up. 

I recently updated sabnzbd to 3.11 and I also updated the scripts in nzbtoMedia. When trying to post process (hopefully that's the right term) I get the following error.  

CouchPotato: Failed to post-process - No change in status!
[ERROR]::MAIN: A problem was reported in the /home/(user)/.sickrage/nzbToMedia/nzbToMedia.py script.
Changing to directory: /home/(user)/.sickrage/nzbToMedia

I made a backup and compared the old nzbtoMedia.py script to the new one and I couldn't notice any differences.

The only other thing that might be worth noting is the entire process seems to be done between root and the user (me). 

Thanks in advance

**Comment by clinton-hall** [comment]
Ok, check the CouchPotato logs at the time of the Postprocess event. See if the logs there say that it couldn't find any media, or refused to process for some reason.

what user is SickRAGE running as, what user is CouchPotato running as?

**Comment by zerosaber071** [comment]
> Ok, check the CouchPotato logs at the time of the Postprocess event. See if the logs there say that it couldn't find any media, or refused to process for some reason.
> 
> what user is sabnzbd running as, what user is CouchPotato running as?

Hey!

I checked the logs in CP and saw nothing that couldn't find any media or refusing to process.

This is going to sound dumb, but how do I check what user Couchpotato and sabnabd as? I know believe they are both user

**Comment by clinton-hall** [comment]
`ps | grep couchpotato`
`ps | grep sabnzbd`
if they don't work, try
`ps | grep python`

**Comment by zerosaber071** [comment]
None of them output anything......

**Comment by clinton-hall** [comment]
so it looks like sabnzbd is running (twice?) as root, but CP is running as user.
This means CP may not have permissions to see/move the files that are downloaded by SABnzbd.

I would try setting up SABnzbd to run as the same user as CouchPotato

**Comment by zerosaber071** [comment]
Thanks for the help! Once I figure out how to do that, I'll come by here and let you know

**Comment by zerosaber071** [comment]
Everything is working now. Got sabnzbd and CouchPotato to run as the same user.

Thanks!

**Comment by clinton-hall** [comment]
glad to hear you got it working.
