### ISSUE TITLE
Post Processing Errors

### ISSUE THREAD

**Issue by HPMSGEN8** [clinton-hall/nzbToMedia#1809]
Hi Clinton-Hall

The issues i am getting is the below. What rights are required for this please. 

warning: unable to access '.git/config': Permission denied
fatal: unable to access '.git/config': Permission denied
warning: unable to access '.git/config': Permission denied
fatal: unable to access '.git/config': Permission denied

Thanks

**Comment by clinton-hall** [comment]
The user that runs nzbToMedia needs to have full (read/write) access to the nzbToMedia directory.

Based on the above errors, I would guess that nzbToMedia was installed (via git) as an administrator (or root/SU) and then the user that is running nzbToMedia (the user that runs your download app) is a different user with different privileges.

**Comment by HPMSGEN8** [comment]
Thanks let me go see what is going on.

What do you Recommend on how to get this to install. I am on an Synology. 

Thanks

**Comment by clinton-hall** [comment]
Honestly Syno is the NAS I know least about.... I do know Syno has more complex user/permissions config than other brands (in many ways it is a more secure system, but requires more user intervention to make everything co-operate).

I would start by looking through this. 
https://github.com/clinton-hall/nzbToMedia/wiki/Synology-NAS---Docker-Remote-Host-General-Help

This was created by Syno users, so I hope it covers most of the needed info.

**Comment by HPMSGEN8** [comment]
Thanks will do

**Comment by HPMSGEN8** [comment]
All Solved :)
