### ISSUE TITLE
post-processing failing for NZB not found

### ISSUE THREAD

**Issue by brianjmurrell** [clinton-hall/nzbToMedia#1816]
**Describe the bug**
When SABnzbd is given an NZB url that ultimately fails to download, the failed processing back to SickChill fails.

**Technical Specs**
1. Running on Linux
2. Python version 2.7
3. Download Client SABnbzd
4. Intended Media Management SickChill

**Expected behavior**
nzbToMedia should take the notification from SABnzbd about the failed download and process it rather than throwing an error.

**Log**
```
2021-02-17 09:47:50 INFO    ::MAIN: nzbToMedia Version:43ba9b1e469f957261a384f852704f058b281235 Branch:master (Linux 3.10.0-1160.11.1.el7.x86_64)
2021-02-17 09:47:50 INFO    ::MAIN: #########################################################
2021-02-17 09:47:50 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2021-02-17 09:47:50 INFO    ::MAIN: #########################################################
2021-02-17 09:47:50 DEBUG   ::MAIN: Options passed into nzbToMedia: ['/nzbToMedia/nzbToSickBeard.py', '', 'http://nzb:5076/getnzb/api/-[redacted]?apikey=[redacted]', 'http://nzb:5076/getnzb/api/-[redacted]?apikey=[redacted]', '', 'sickbeard-tv', 'None', '3', '']
2021-02-17 09:47:50 INFO    ::MAIN: Script triggered from SABnzbd Version 2.3.9.
2021-02-17 09:47:50 ERROR   ::MAIN: The input directory:[] is the Default Download Directory. Please configure category directories to prevent processing of other media.
2021-02-17 09:47:50 ERROR   ::MAIN: A problem was reported in the /nzbToMedia/nzbToSickBeard.py script.
```

The problem appears to be the `''` as the second item in the list: `['/nzbToMedia/nzbToSickBeard.py', '', 'http://nzb:5076/getnzb/api/-[redacted]?apikey=[redacted]', 'http://nzb:5076/getnzb/api/-[redacted]?apikey=[redacted]', '', 'sickbeard-tv', 'None', '3', '']`, but that seems to be empty because there was no actual file download, just a failed NZB fetch.

**Comment by clinton-hall** [comment]
Ah... looks like a repeat of #1673

I haven't implemented a fix for that.

It might be possible to use a "generic" failed-to-snatch directory that can be passed in to the media manager if we get passed `''`

**Comment by brianjmurrell** [comment]
Yeah, this looks exactly like #1673, and could be closed as a dup of it.

I did set `[Nzb] -> default_downloadDirectory` to a non-empty value to get further (even before reading through #1673) but then did also run into the issue of nzbtomedia passing back the URL as the nzbname rather than a filename.

**Comment by miigotu** [comment]
@clinton-hall I reimplemented old parameter names so that it would pick up things like nzbName and the process_dir even if the fork was set wrong. But nzbName is expected to be the nzb filename, possibly including the path to it.(blah.x264.hdtv-lol.nzb or whatever)

Am I making the wrong assumption or should I make a change to try and match the nzb download url back to a release name?

As far as I know, SC has just been doing a full pp every time nzbtomedia calls our pp, within whatever folder you passed, and that can't be the intention.

Lmk what I can do to help out, I'm willing to change the API for you or even create a custom api endpoint just for nzbtomedia if it helps.

**Comment by p0psicles** [comment]
I refactored the SickBeard code to a more OO approach. For every sb fork a new class souls be added now. This is something that needs to be done now anyway. So you might as well add the class for sc and fix the issue while at it.

**Comment by clinton-hall** [comment]
yeah, agree that this should be added to new class etc. The biggest issue I see here is that the start-point (the data passed in from SABnzbd) is causing the problems and not the data that is passed to any of the SB forks.

`Options passed into nzbToMedia: ['/nzbToMedia/nzbToSickBeard.py', '', 'http://nzb:5076/getnzb/api/-[redacted]?apikey=[redacted]', 'http://nzb:5076/getnzb/api/-[redacted]?apikey=[redacted]', '', 'sickbeard-tv', 'None', '3', '']`

so we aren't given a directory to process (I believe SC and most/all other SB forks require a directory to process even when we are marking as failed). I am sure we can over-come that part... but then without a directory we need to have the correct name to be able to mark as failed or at least have some details of the nzb itself.

I myself have never experienced this, and have struggled to understand how this comes about. It seams that if SABnzbd downloads the nzb file and then fails to download and unpack the contents, we get the Directory and the name and all is well.
But when SABnzbd fails to download the nzb file, and again I have never seen this happen myself, then it simply passes us the url that it tried to download from.

Probably what I need to do is call SABnzbd api to see if we have any other details that we can get to be able to match this to a snatched release. If I can get the actual nzb name, or a download id etc, I can send that to the appropriate media manager and if needed pass a "generic" failed path.

@brianjmurrell 
I just noted the download URL... can I assume that this is trying to download from your own newznab server? `http://nzb:5076` looks like this might be a local server you are running... If so, that might help explain what is leading to this particular configuration. Is it possible that you are trying to snatch an nzb before your newznab server has finished scrubbing that nzb?

**Comment by brianjmurrell** [comment]
> I just noted the download URL... can I assume that this is trying to download from your own newznab server?

Not really.  Just an aggregator/proxy/cache called NZBHydra.

**Comment by miigotu** [comment]
Is the nzb name in the url?

**Comment by miigotu** [comment]
@brianjmurrell mind trying out that branch `failed_and_pp`? I need to go over it well before merge but I think this fixes the issue.

**Comment by brianjmurrell** [comment]
> failed_and_pp

Sorry, just finding a bit of time for this now.  Is this a SickChill branch or an nzbToMedia branch?

**Comment by miigotu** [comment]
SC, and it was already merged. Just use master

**Comment by brianjmurrell** [comment]
In any case, it seems to work.  Great!
