### ISSUE TITLE
Postprocess fail, not a git repository

### ISSUE THREAD

**Issue by jbravo2ru** [clinton-hall/nzbToMedia#1825]
Hello, I recently had a problem with a postprocess script. Otherwise it always ran perfectly, since a few weeks the error message has been appearing:

fatal: not a git repository (or any of the parent directories): .git Changing to directory: /var/packages/sabnzbd/scripts/nzbToMedia-12.1.08 - Cleaning bytecode - WARNING: Automatic cleanup could not be executed. If errors occur, manual cleanup may be required. REASON: Error Code: 128 Directory is not a git repository Force cleaning folder: libs Skipping required subfolders ['common', 'custom', 'py2', 'win'] Force cleaning folder: core Skipping required subfolders ['auto_process', 'extractor', 'plugins', 'utils'] Returning to directory: / volume1 / @ appstore / sabnzbd / share / SABnzbd - Cleanup finished - Traceback (most recent call last): File "/var/packages/sabnzbd/scripts/nzbToMedia-12.1.08/nzbToSickBeard.py", line 273, in <module> result = nzbToMedia.main (sys.argv, section) File "/var/packages/sabnzbd/scripts/nzbToMedia-12.1.08/nzbToMedia.py", line 885, in main core.initialize (section) File "/var/packages/sabnzbd/scripts/nzbToMedia-12.1.08/core/__init__.py", line 1024, in initialize configure_migration () File "/var/packages/sabnzbd/scripts/nzbToMedia-12.1.08/core/__init__.py", line 339, in configure_migration if not config.migrate (): File "/var/packages/sabnzbd/scripts/nzbToMedia-12.1.08/core/configuration.py", line 257, in migrate CFG_NEW.write () File "/var/packages/sabnzbd/scripts/nzbToMedia-12.1.08/libs/common/configobj/__init__.py", line 2098, in write with open (self.filename, 'wb') as h: PermissionError: [Errno 13] Permission denied: '/var/packages/sabnzbd/scripts/nzbToMedia-12.1.08/autoProcessMedia.cfg'

I have a disk station and loaded the latest Sabnzbd from the synocommunity on it. I also checked the authorizations today, Sabnzbd has read and write rights. I hope someone can help me.

**Comment by clinton-hall** [comment]
check the file `/var/packages/sabnzbd/scripts/nzbToMedia-12.1.08/autoProcessMedia.cfg` and directory `/var/packages/sabnzbd/scripts/nzbToMedia-12.1.08/' to make sure that both of these have read-write permissions for the Sabnzbd user.

the error that stops everything is `Permission denied: '/var/packages/sabnzbd/scripts/nzbToMedia-12.1.08/autoProcessMedia.cfg'` so the user that is calling the script doesn't currently have permission to write to this file.

**Comment by jbravo2ru** [comment]
I don't know how to change, in my Diskstation the user have the permissions to read and write to all folders🤔

**Comment by MrCee** [comment]
Out of interest, what DSM version are you running?
I suggest you clone (or move) nzbTomedia to `/volume1/@appstore/nzbToMedia` without the version in the path (folder) and work on permissions from there.
sabnzbd will often override permissions during updates. Don't keep nzbToMedia within that path.

**Comment by jbravo2ru** [comment]
The version on DSM is 6.2.4-25556.

I've already tried to put nzbToMedia script in another folder, it didn't worked there.

**Comment by MrCee** [comment]
Where did you put it?

**Comment by jbravo2ru** [comment]
I tried to put it on volume1 ind the download folder, but it didn't work, although sabnzbd there constantly writes and reads.

**Comment by jbravo2ru** [comment]
> 
> 
> Out of interest, what DSM version are you running?
> I suggest you clone (or move) nzbTomedia to `/volume1/@appstore/nzbToMedia` without the version in the path (folder) and work on permissions from there.
> sabnzbd will often override permissions during updates. Don't keep nzbToMedia within the sabnzbd path.

unfortunately that doesn't work either, still the same error message: /
