### ISSUE TITLE
Failure to post process with new pymedusa v2 api.

### ISSUE THREAD

**Issue by Slurp** [clinton-hall/nzbToMedia#1827]
**Describe the bug**

Failure to post process with new pymedusa v2 api.

using @p0psicles new code (https://github.com/clinton-hall/nzbToMedia/pull/1812) gives this error when using api=medusa-apiv2 as a setting.
```
File "/.sabnzbd/nzbToMedia/core/auto_process/managers/pymedusa.py", line 118, in api_call
if not jdata.get('status') or not jdata['status'] == 'success':
UnboundLocalError: local variable 'jdata' referenced before assignment
```

**Technical Specs**
Ubuntu 20.04
Python 3.6.9
SABNZB
PyMedusa

**Comment by p0psicles** [comment]
You used medusa api key?

**Comment by Slurp** [comment]
Hi @p0psicles ,

No i didn't have that an api key in the script present.
With the api key filled in it worked perfectly.

Still without an api key i would expect a connection error instead of this UnboundLocalError.

**Comment by p0psicles** [comment]
Your right. I will add a warning for that

**Comment by clinton-hall** [comment]
@p0psicles 
Do I need to add anything here? add handling for no jdata returned?

**Comment by p0psicles** [comment]
Ooh yeah. I can als PR when I get to it. But yeah that was what I was planning to do. Maybe try to provide the user with a decent warning
