### ISSUE TITLE
SICKBEARD: {"status": "failed", "message": "Missing Post-Processing dir"}

### ISSUE THREAD

**Issue by abatchx** [clinton-hall/nzbToMedia#1837]
**Describe the bug**
Post processing fails with the following error:

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) '....'
2. Python version '....'
3. Download Client (NZBget, SABnbzd, Transmission) '....'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) '....'

**Expected behavior**

**Log**
Please provide an extract, or full debug log that indicates the issue.

**Comment by clinton-hall** [comment]
no details?

The title includes a clear description of the error. Basically the script is passing through the details to SickBeard but isn't passing the correct parameter for the post-processing directory.

Make sure you set the correct for (or try fork = auto) for your version of SickBeard.

**Comment by abatchx** [comment]
Sorry Clinton - was putting this post together whilst doing a load of experimentation and managed to resolve it myself. Absolutely no idea how this got posted with zero details. 

For reference, my folder paths have a space in them (long story) so needed to be enclosed in quotations. Additionally Medusa wasn't being recognised in the fork, so as you rightly point out I needed to set the correct fork to 'medusa'.

Apologies for the time wasting looking at this entirely useless post!!

**Comment by clinton-hall** [comment]
All good... glad you got it sorted.
