### ISSUE TITLE
Docker Setting Issues

### ISSUE THREAD

**Issue by HPMSGEN8** [clinton-hall/nzbToMedia#1843]
**Describe the bug**
I am having an issue with ffmpeg & git. I cannot seem to get this to work in Docker.

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) 'Synology'
2. Python version '3.8'
3. Download Client (NZBget, SABnbzd, Transmission) 'SABnbzd'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) 'medusa'

**Expected behavior**
Working

**Log**
[08:47:57] [INFO]::MAIN: Python v3.8 will reach end of life in 1147 days.
[08:47:57] [INFO]::MAIN: Checking database structure...
[08:47:57] [INFO]::MAIN: Checking if git needs an update
[08:47:57] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
[08:47:57] [INFO]::MAIN: No update needed
[08:47:57] [INFO]::MAIN: nzbToMedia Version:12.1.08 Branch:master (Linux 4.4.59+)
[08:47:57] [WARNING]::MAIN: Failed to locate ffmpeg. Transcoding disabled!
[08:47:57] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[08:47:57] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
[08:47:57] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...

-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory: 'git'

-- Cleaning folders: ['libs', 'core'] --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory: 'git'
Returning to directory:  /app/sabnzbd

-- Cleanup finished --

**Comment by HPMSGEN8** [comment]
/ffprobe: error while loading shared libraries: libavdevice.so.58: cannot open shared object file: No such file or directory

**Comment by MrCee** [comment]
This is something I've figured out today as I found it annoying to have to install ffmpeg & git after every image re-build. 

You can get Docker to containers to work with Synology apps/libraries from `/volume1/@appstore` using docker-compose or CLI (you can't really map from the GUI). I'm not sure if it's the best way to do things, but this works well.
FYI: I have 1 clone of nzbToMedia and this sits outside of ALL docker containers. I don't add anything more to the containers. I use the approach of naming all paths inside Docker containers exactly as they are in Syno DSM, so passing in and out of containers to Download Station is seamless 

add this to your LinuxServer.io SABnzbd Docker config and make sure autoProcessMedia.cfg is updated.
In

```
    environment:
      - PATH=$PATH:/volume1/@appstore/git/libexec/git-core
      - LD_LIBRARY_PATH=/volume1/@appstore/git/lib:/volume1/@appstore/ffmpeg/lib
    volumes:
      - /volume1/@appstore/git:/volume1/@appstore/git
      - /volume1/@appstore/ffmpeg:/volume1/@appstore/ffmpeg
```

**Comment by MrCee** [comment]
The above stopped working after one of the recent DSM updates. For whatever permission reason, I cannot execute the host installed git or ffmpeg/ffprobe.

I thought I'd revisit this and use a similar method, i.e. make sure all of your container paths exist as they normally would on the host and adjust the external nzbToMedia config file e.g. `/volume1/docker/nzbToMedia/autoProcessMedia.cfg`

Assuming you have the image `linux-server/sabnzbd:latest` this will work....

**Update autoProcessMedia.cfg**
```
[General]
    # Set to the full path to the git executable
    git_path = /volume1/@appstore/git/bin/git
    # Set to the directory where your ffmpeg/ffprobe executables are located
    ffmpeg_path = /volume1/@appstore/ffmpeg/bin
```

Create a file called **90-config** in your sabnzbd config directory and map it to volumes:
This **90-config** will be executed when the container is built the first time...

```
#!/usr/bin/with-contenv bash

## To install ffmpeg/ffprobe and git within container, create a file called 90-config, map in docker as per 'volumes:' below, and re-build the container
##    volumes:
##      - /volume1/docker/sabnzbd/config/90-config:/etc/cont-init.d/90-config

# linux-server/sabnzbd
if [[ -x $(command apk ) ]] ; then
apk update
apk add ffmpeg
apk add git
fi

# just incase you have this built differently.....
if [[ -x $(command apt-get ) ]] ; then
apt-get update
apt-get install ffmpeg
apt-get install git
fi

## Symlink ffmpeg/ffprobe & git to a container path that reflects the usual host executable location
## This will allow external scripts to reference the same path normally used on host. Apply the same symlinks to all docker containers using external scripts 
mkdir -p  /volume1/@appstore/ffmpeg/bin/
mkdir -p  /volume1/@appstore/git/bin/
ln -s /usr/bin/ffmpeg /volume1/@appstore/ffmpeg/bin/ffmpeg
ln -s /usr/bin/ffprobe /volume1/@appstore/ffmpeg/bin/ffprobe
ln -s /usr/bin/git /volume1/@appstore/git/bin/git
```

**Comment by HPMSGEN8** [comment]
Thanks alot @MrCee 

This worked 100% now. I decided to move back to Docker as it seems easier in the log run,

Closing Issue as RESOVLED.

HI @clinton-hall 

Can this not be put on the Wiki if other people have issues.

Thanks all & Happy Holidays.
