### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by quacker1982** [clinton-hall/nzbToMedia#1847]
nzbTomedia showing error when running nzbToSickbeard script

1. Running on Qnap
2. Python version '3.8.6.0'
3. Download Client (NZBget)
4. Intended Media Management (Medusa)

Had to re-install via Sherpa both NZBGet and nzbToMedia and the following error keeps occurring.

[Paw.Patrol.S08E01-02.Pups.Save.A.Sweet.Mayor-pups.Save.A.Magic.Trick.720p.NICK.WEB-DL.AAC2.0.H.264-BTN.log](https://github.com/clinton-hall/nzbToMedia/files/7168877/Paw.Patrol.S08E01-02.Pups.Save.A.Sweet.Mayor-pups.Save.A.Magic.Trick.720p.NICK.WEB-DL.AAC2.0.H.264-BTN.log)

**Comment by clinton-hall** [comment]
that is odd... It looks like it is giving an error on `os.getcwd()`
https://stackoverflow.com/questions/3210902/python-why-does-os-getcwd-sometimes-crash-with-oserror

It looks like what ever directory is the working directory used to call nzbToMedia is somehow deleted before the script really gets going.

So, a couple of things to look at:

- Make sure Medusa isn't auto-processing the downloads. If it identifies the downloads and moves the files etc. before nzbToMedia runs, this could cause the issue.
- Check the Directory where nzbToMedia is located and also how this is mapped in to NZBGet. I note the Path is /share/50014EE2B2C87120_DATA/.qpkg/nzbToMedia/nzbToMedia/nzbToSickBeard.py

So what is the path in NZBGet for scripts? Why do you have the duplicate `nzbToMedia` in the path?

**Comment by quacker1982** [comment]
Checked Medusa, everything appears to be correctly set, scheduled PP is turned off etc.
I tried deleting the nzbToMedia via WinSCP from the Qnap and using the uninstall method via Sherpa, each time it re-installs it creates the duplicate directory.  In NZBGet the script path has been set to 
/share/50014EE2B2C87120_DATA/.qpkg/nzbToMedia/nzbToMedia
Still producing the same error.
![NZBtomedia 1](https://user-images.githubusercontent.com/1976774/133516318-a1fdf256-7a00-4029-94b7-c82a9d8bb1c7.png)
![NZBtomedia 2](https://user-images.githubusercontent.com/1976774/133516330-d145292a-5add-4ec5-aa09-54119734aba3.png)

**Comment by clinton-hall** [comment]
Have you tried restarting NZBGet? Perhaps even restart the NAS?
It almost feels like the Python session is being spawned from a cached/non-existent location.

**Comment by quacker1982** [comment]
Unreal... Just tried another restart and now it's working. Cleary an ID-10-T error.
Appreciate your time Clinton, I'll close this ticket.

**Comment by clinton-hall** [comment]
All good... There is that part of me that was worried that wouldn't make any difference, but I just couldn't see any other reason why that error would persist.
In general, across multiple NAS models, depending of how the Apps are compiled (cross compiles vs containers or Optware/Entware etc) there can be a lot of odd combinations that trigger unexpected results... Saying that, everything I have seen with Sherpa is pretty reliable.

Glad you got it sorted now.
