### ISSUE TITLE
AutoProcessMedia.cfg problem with NZBGet

### ISSUE THREAD

**Issue by nstead** [clinton-hall/nzbToMedia#1852]
**Describe the bug**
I'm using nzbToMedia with nzbget.   
Every time it tries to post-process the download I get
[ERROR]::MAIN: Unable to migrate config file /scripts/nzbToMedia/autoProcessMedia.cfg, exiting
On looking at the autoProcessMedia.cfg file, it's clear that it's not valid - it has subsections under [[Couchpotato]], [[Headphones]] and [[SickBeard]] with [""]  (even though I don't use Headphones or SickRage).

If I delete the autoProcessMedia.cfg file (or edit it manually, to correct it), and Post-process the file again, it works perfectly.... and then fails on the very next file, recreating the corrupted autoProcessMedia.cfg

I've tried reinstalling nzbget, reinstalling nzbToMedia, but I'm still getting nowhere.

**Technical Specs**
1. Running on Synology 1815+ (DSM 6.2.4-25556 Update 2)
2. Python version 2.7  (I've also tried with 3.9, but the same thing happens, plus some extension scripts that aren't Python3 compatible don't run)
3. Download Client NZBGet V21.1
4. Intended Media Management:  Sonarr

**Expected behavior**
Post-processing should complete correctly.  The autoProcessMedia.cfg file should not contain errors.

**Log**
[nzbtomedia.log](https://github.com/clinton-hall/nzbToMedia/files/7273635/nzbtomedia.log)

The log below is from the NZBGet Messages page (most recent message first):
`
INFO | Sun Oct 03 2021 16:58:50 | Unpausing download after post-processing
-- | -- | --
INFO | Sun Oct 03 2021 16:58:49 | Collection The.Great.British.Bake.Off.An.Extra.Slice.S08E02.1080p.HDTV.H264-DARKFLiX-xpost added to history
ERROR | Sun Oct 03 2021 16:58:49 | Post-process-script nzbToMedia/nzbToMedia.py for The.Great.British.Bake.Off.An.Extra.Slice.S08E02.1080p.HDTV.H264-DARKFLiX-xpost failed (terminated with unknown status)
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: 30 more error(s)!
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: Duplicate keyword name at line 88.
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: Duplicate keyword name at line 87.
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: Duplicate keyword name at line 86.
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: Duplicate keyword name at line 85.
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: Cannot compute the section depth at line 84.
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: configobj.ConfigObjError: Parsing failed with 35 errors.
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: raise error
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: File "/scripts/nzbToMedia/libs/common/configobj/__init__.py", line 1302, in _load
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: self._load(infile, configspec)
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: File "/scripts/nzbToMedia/libs/common/configobj/__init__.py", line 1205, in __init__
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: super(configobj.ConfigObj, self).__init__(*args, **kw)
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: File "/scripts/nzbToMedia/core/configuration.py", line 102, in __init__
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: cfg_new = config()
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: File "/scripts/nzbToMedia/core/configuration.py", line 289, in addnzbget
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: CFG = config.addnzbget()
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: File "/scripts/nzbToMedia/core/__init__.py", line 352, in configure_migration
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: configure_migration()
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: File "/scripts/nzbToMedia/core/__init__.py", line 1028, in initialize
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: core.initialize(section)
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: File "/scripts/nzbToMedia/nzbToMedia.py", line 885, in main
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: exit(main(sys.argv))
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: File "/scripts/nzbToMedia/nzbToMedia.py", line 1061, in <module>
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: Traceback (most recent call last):
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: -- Cleanup finished --
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: Returning to directory: /
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: No folders to clean
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: -- Cleaning folders: ['libs', 'core'] --
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: b'Removing __pycache__/\n'
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: b'Removing __pycache__/\n'
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: -- Cleaning bytecode --
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: Changing to directory: /scripts/nzbToMedia
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: [16:58:49] [ERROR]::MAIN: Unable to migrate config file /scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: 30 more error(s)! when copying to .cfg
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: Duplicate keyword name at line 88.
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: Duplicate keyword name at line 87.
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: Duplicate keyword name at line 86.
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: Duplicate keyword name at line 85.
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: Cannot compute the section depth at line 84.
INFO | Sun Oct 03 2021 16:58:49 | nzbToMedia: [16:58:49] [ERROR]::MAIN: Error Parsing failed with 35 errors.
INFO | Sun Oct 03 2021 16:58:38 | Executing post-process-script nzbToMedia/nzbToMedia.py for The.Great.British.Bake.Off.An.Extra.Slice.S08E02.1080p.HDTV.H264-DARKFLiX-xpost
INFO | Sun Oct 03 2021 16:58:38 | Post-process-script mkvdts2ac3/mkvdts2ac3.py for The.Great.British.Bake.Off.An.Extra.Slice.S08E02.1080p.HDTV.H264-DARKFLiX-xpost successful

`

** autoProcessMedia.cfg file after processing *
[autoProcessMedia cfg.txt](https://github.com/clinton-hall/nzbToMedia/files/7273611/autoProcessMedia.cfg.txt)
*

Help!  I've spent hours trying to work out what's going on, without success.

**Comment by clinton-hall** [comment]
Try deleting the autoProcessMedia.cfg and setting the hpCategory and cpCategory in NZBGet -> nzbToMedia.py

I believe by having these blank, this is causing the duplicate issue. Basically, each **Category in the GUI for nzbToMedia.py needs to have a unique (non blank) category set. These DON'T need to actually have a category defined in NZBGet's categories, and therefore the script would never get called with these categories passed in, but they need to be defined.

The other option here is to set each Category to only call the appropriate script, and set the config for that script only.
i.e. 
set category movies to call nzbToRadarr.py (and set the appropriate config in nzbToRadarr.py via NZBGet)
set category tv to call nzbToNzbDrone.py (and set the appropriate config in nzbToNzbDrone.py within NZBGet)
