### ISSUE TITLE
nzbToMedia Log Managment?

### ISSUE THREAD

**Issue by neo-neo1** [clinton-hall/nzbToMedia#1854]
Does nzbToMedia automatically clear it's log file? I see it growing and growing on a new installation.

I didn't see it covered in the wiki. I will add all relevant information. Thank you.

**Comment by clinton-hall** [comment]
I believe it does store up to 3 logs. This was tested some time ago, and as far as I am aware should still be true.
in /core/logger.py
```
# number of log files to keep
NUM_LOGS = 3

# log size in bytes
LOG_SIZE = 10000000  # 10 megs
```
so there would be , after some time:
nzbToMedia.log
nzbToMedia.log.1
nabToMedia.log.2

the first one keeps growing until it hits 10 MB, after that it copies to log.1 and a new log is created. (and next time 10 MB is reacted, log.1 is copies to log.2 etc... log.2 is deleted next time log.1 is copied across etc).
