### ISSUE TITLE
mount_points gets erased

### ISSUE THREAD

**Issue by CiViC321** [clinton-hall/nzbToMedia#1855]
I have a setup where my dowload client, NAS and KODI server is all on seperate machines.

The mount_points directive is successfully used to do the mapping between local and remote mount point.

However, sometimes the mount_point get erased or zerod to 
mount_points = ""

I spec mount_points in the autoProcessMedia.cfg.spec and autoProcessMedia.cfg file.

It gets changed automatically ny the python script in the autoProcessMedia.cfg file.

How do I stop this?

**Comment by clinton-hall** [comment]
The only reason I can think of why this would get reset is if you are using NZBGet.

In that case, you would need to set the Mount Points in the NZBGet WebUI for the script you are calling.
i.e. if you are calling nzbToMedia.py, in NZBGet, nzbToMedia.py, there will be an option to set Mounts_Points:

```
# Network Mount Points (Needed for remote path above)
#
# Enter Mount points as LocalPath,RemotePath and separate each pair with '|'
# e.g. mountPoints=/volume1/Public/,E:\|/volume2/share/,\\NAS\
#mountPoints=
```
if this is blank, it will always over-write whatever you have manually entered into autoProcessMedia.cfg
