### ISSUE TITLE
Post Processing Error - KeyError: (3, 10)

### ISSUE THREAD

**Issue by bartley69** [clinton-hall/nzbToMedia#1871]
**Describe the bug**

**Technical Specs**
1. Running on QNAP TS-421
2. Python version - 3.10.0 (default, Dec 10 2021, 08:29:27) [GCC 8.4.0] [UTF-8]
3. Download Client - SABnzbd
4. Intended Media Management - SickGear

sab, sickgear and nzbtomedia were all installed via oneCD';s sherpa script to my NAS.

I edited my autoprocessmedia.cfg with my details as follows.

<pre>[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[tv]]
        enabled = 1
        host = localhost
        port = 7181
        apikey = KEYISHERE
        username =
        password =
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root =
        ssl = 0
        fork = auto
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        process_method =
        # force processing of already processed content when running a manual scan.
        force = 0
        # Additionally to force, handle the download as a priority downlaod.
        # The processed files will always replace existing qualities, also if this is a lower quality.
        is_priority = 0
        # tell SickRage/Medusa to delete all source files after processing.
        delete_on = 0
        # tell Medusa to ignore check for associated subtitle check when postponing release
        ignore_subs = 0
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir =
        ##### Set the recursive directory permissions to the following (0 to disable)
        chmodDirectory = 0
        ##### pyMedusa (fork=medusa-apiv2) uses async postprocessing. Wait a maximum of x minutes for a pp result
        wait_for = 10`</pre>

The script starts to run but spits this error when trying to process a download.

`Traceback (most recent call last):
File "/share/MD0_DATA/Download/nzbToMedia/nzbToSickBeard.py", line 270, in <module>
import nzbToMedia
File "/share/MD0_DATA/.qpkg/nzbToMedia/nzbToMedia/nzbToMedia.py", line 727, in <module>
eol.check()
File "/share/MD0_DATA/.qpkg/nzbToMedia/nzbToMedia/eol.py", line 100, in check
warn_for_status(version, grace_period)
File "/share/MD0_DATA/.qpkg/nzbToMedia/nzbToMedia/eol.py", line 141, in warn_for_status
days_left = lifetime(version)
File "/share/MD0_DATA/.qpkg/nzbToMedia/nzbToMedia/eol.py", line 71, in lifetime
time_left = PYTHON_EOL[(major, minor)] - now
KeyError: (3, 10)`

Categories in sabnzbd are set up as follows.

https://i.postimg.cc/W38Y1CnZ/sabnzbd.png

Any idea what I'm doing wrong?

Thanks.

**Comment by clinton-hall** [comment]
Python 3.10 wasn't supported by Master branch.
I have now merged this. On update (next run) this should work.

**Comment by bartley69** [comment]
Worked perfectly! Happy new year @clinton-hall

**Comment by TheQL** [comment]
Same thing might have happened with Python 3.11 now.
