### ISSUE TITLE
NZBtomedia.py error

### ISSUE THREAD

**Issue by PaulM507** [clinton-hall/nzbToMedia#1876]
Morning. 

After a recent issue, an uninstall and re-install of all SHERPA packages seemed to fix things but I've now got a weird error with nzbtomedia.py (below). I've checked my .py files and .cfg files but can't see what is wrong. Line 194 only contains a #. All that happens now is the folder gets moved to my TV folder but no renaming or placing in the correct show folder.

Grateful for any thoughts or suggestions. 

Cheers

-- Cleanup finished --

**Technical Specs**
1. Running on NAS Model TS-673, QTS 5.0.0.1932
2. Python version 3.10
3. Download Client SABNZBD
4. Intended Media Management SickGear '....'

**Expected behavior**
For the file to be post processed by renamed and moved to the correct folder

**Log**
[22:08:02] [ERROR]::MAIN: Error Cannot compute the section depth at line 194. when copying to .cfg
[22:08:02] [ERROR]::MAIN: Unable to migrate config file /share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/autoProcessMedia.cfg, exiting ...
Changing to directory: /share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory: /share/CACHEDEV1_DATA/.qpkg/SABnzbd/SABnzbd

**Comment by clinton-hall** [comment]
what did you use to edit the autoProcessMedia.cfg?
I would suggest deleting the file and starting again.
If you use windows and edit the file through notepad or similar, it may be setting the wrong line-feed... or when indenting sections make sure you use 4 spaces and not tabs...

**Comment by PaulM507** [comment]
Thanks for the reply mate. I used the  QNAP text editor (which I think I've used before). I'll try deleting and starting again. Cheers

**Comment by PaulM507** [comment]
That's seems to have fixed it mate. Brilliant. Thanks for the help!
