### ISSUE TITLE
SiCKRAGE API call doesn't pass cmd for post-processing api/v1

### ISSUE THREAD

**Issue by andycoates** [clinton-hall/nzbToMedia#1900]
**Describe the bug**
SiCKRAGE API call doesn't pass `cmd` for post-processing `api/v1`.  Currently using SABnzbd `3.6.0` and SiCKRAGE `10.0.70` but not sure that matters as my older `nzbToMedia` was working fine with those versions - seems with the change to specifically supporting SiCKRAGE that maybe got missed.

I got it to work by tweaking the `api/v1` call to set it (and also added logging) with the following:
```
diff --git a/core/auto_process/tv.py b/core/auto_process/tv.py
index 84a93427..037d1c53 100644
--- a/core/auto_process/tv.py
+++ b/core/auto_process/tv.py
@@ -316,6 +316,7 @@ def process(section, dir_name, input_name=None, failed=False, client_agent='manu
             url = '{0}{1}:{2}{3}/api/v{4}/postprocess'.format(protocol, host, port, web_root, api_version)
         else:
             url = '{0}{1}:{2}{3}/api/v{4}/{5}/'.format(protocol, host, port, web_root, api_version, apikey)
+            fork_params['cmd'] = 'postprocess'
     elif section == 'NzbDrone':
         url = '{0}{1}:{2}{3}/api/command'.format(protocol, host, port, web_root)
         url2 = '{0}{1}:{2}{3}/api/config/downloadClient'.format(protocol, host, port, web_root)
@@ -371,6 +372,7 @@ def process(section, dir_name, input_name=None, failed=False, client_agent='manu
             else:
                 params = fork_params

+            logger.debug('Opening URL: {0} with params: {1}'.format(url, params), section)
             r = s.get(url, params=params, stream=True, verify=False, timeout=(30, 1800))
         elif section == 'NzbDrone':
             logger.debug('Opening URL: {0} with data: {1}'.format(url, data), section)
```

**Comment by clinton-hall** [comment]
Thanks for reporting this and providing the fix.
If you can test the fork [SR-patch-1](https://github.com/clinton-hall/nzbToMedia/compare/SR-patch-1) I'll try and merge that once verified.

**Comment by andycoates** [comment]
Thanks - the patch is the same so expect its fine, but I'll double check on my next upgrade - the diff between master seemed a fair bit so I don't want to rock the boat just yet.
