### ISSUE TITLE
Python 3.11 end-of-life check fails

### ISSUE THREAD

**Issue by labrys** [clinton-hall/nzbToMedia#1901]
**Describe the bug**
Python 3.11 not listed in end-of-life dates

**Technical Specs**
1. Running on any system
2. Python version 3.11
3. Any Download Client
4. Any Intended Media Management

**Expected behavior**
End of life check should not fail for Python 3.11 as it is not yet end-of-life.

**Comment by clinton-hall** [comment]
Thanks that looks good.
I think 3.11 needs to be added to azure-pipelines.yml (and possibly remove Pyhton3.6 tests)?
I know last time I added a new python version, I ran into the issue where it wasn't available in the azure image yet.... so that had to wait for the image to be updated.

**Comment by labrys** [comment]
@clinton-hall I'm holding off on removing Python 3.6 and haven't checked if 3.11 is available on Azure yet.  I'll update that in the `deadsnakes` branch where I'm working on removing Python 2.7.  Additionally the versions in the `tox` tests are also outdated, I'll fix those as well.
