### ISSUE TITLE
nzbToMedia in `virtualenv`? 

### ISSUE THREAD

**Issue by OneCDOnly** [clinton-hall/nzbToMedia#1944]
Hi guys, 

Any thoughts on how nzbToMedia should be called when it's been installed in a `virtualenv`? Do we need to `activate` it first?

All Python apps installed via [sherpa](https://github.com/OneCDOnly/sherpa) on QNAP NAS now establish and run in their own `virtualenv`s (something Clinton suggested I do a long time ago). I'm just not 100% sure how that will affect nzbToMedia post-processing when called from SABnzbd. 

Thank you.

**Comment by clinton-hall** [comment]
ok... perhaps @labrys can clarify here, as the mastermind behind making this project deployable via pip.

My understanding is that currently (master branch) nzbToMedia is installed via git clone and then will be called/referenced from SABnzbd (all running under SABnzbd's venv). Doing this SABnzbd will need the full path to nzbToMedia and will call the script and pick up the libs within nzbToMedia and then drop back to any other libs within the SABnzbd venv

Once this is fully pip installable, then you would add the `pip install nzbToMedia` as part of the installation routine within your SABnzbd venv. I assume that within SABnzbd you would just reference nzbToMedia.py without the full path as this should be found within the PATH inside SABnzbd's venv and the venv installation will ensure all needed libs are installed and configured.

The only thing to look out for here is if nzbToMedia has any requirements that conflict with SABnzbd requirements... that would cause issues when installing nzbToMedia within the SABnzbd venv. 

While it is theoretically possible to install nzbToMedia within its own venev, that would require you to create a separate script to activate the venev and then pass off all parameters into nzbToMedia.py, and then you would need to call that script from SABnzbd... I really don't think this is a practical way to approach this.

Essentially nzbToMedia is called by SABnzbd (and doesn't run as its own service) so should be installed in the SABnzbd venv.

**Comment by labrys** [comment]
@OneCDOnly When I make the `nzbTo*` scripts console entry points, it will create executables that will live in the Python `/scripts` directory.  While I haven't tested it, you should be able to pip install into its own dedicated virtualenv and point to the executable in the virtualenv's script directory.  This would run nzbToMedia in its own venv and would not require you to activate the venv either.

**Comment by labrys** [comment]
@clinton-hall @OneCDOnly The console entry-points also solve the issue with SABnzb or other apps using a different version of Python than nzbToMedia.  For example if SAB was still running on Python 2.7, you could still call nzbToMedia running in Python 3.11.

**Comment by clinton-hall** [comment]
@labrys 
consider my mind blown!
I hadn't realised you could call scripts within a venv without activating.... I look forward to testing that.

**Comment by labrys** [comment]
@clinton-hall Activating a virtual environment is essentially just rewriting the path so a specific python version is used.  Generally when working with a venv you do want to activate it.  See this quote from [RealPython](https://realpython.com/python-virtual-environments-a-primer/#activate-it) about virtual environments:

> Note: You can also work with your virtual environment without activating it. To do this, you’ll [provide the full path](https://realpython.com/python-virtual-environments-a-primer/#it-runs-from-anywhere-with-absolute-paths) to its Python interpreter when executing a command. However, most commonly, you’ll want to activate the virtual environment after creating it to save yourself the effort of repeatedly having to type long paths.

I know the console entry point works for windows systems to sidestep python version conflicts.  I've used it in the past.  I've also used manual changes to sys.path to point to the desired python interpreter.  I would want to test it on multiple platforms to see if there's any edge cases or issues before I would recommend using a venv in this way.

**Comment by OneCDOnly** [comment]
> While I haven't tested it, you should be able to pip install into its own dedicated virtualenv and point to the executable in the virtualenv's script directory. This would run nzbToMedia in its own venv and would not require you to activate the venv either.

Thanks @labrys for your suggestion. So, does that mean I need only create a symlink in the directory SABnzbd is using for external scripts, and ensure this symlink points towards the `nzbToMedia.py` sourcefile located in it's own `virtualenv`?

**Comment by labrys** [comment]
@OneCDOnly This won't even be testable until I make more changes in the deadsnakes branch.  And it's definitely not close to being ready for use yet as I'm making drastic changes (and likely breaking lots of things 🤣 ).
