### ISSUE TITLE
Odd Errors

### ISSUE THREAD

**Issue by HPMSGEN8** [clinton-hall/nzbToMedia#1951]
**Describe the bug**
I have seem some strange issues with the old and new new version

1.  Why does this error popup about safe 
2. there is an beets error
3. GIT location on my NAS is correct so why does it not show all of an sudden. 

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) 'DSM 7.1.1'
4. Python version '3.10'
5. Download Client (NZBget, SABnbzd, Transmission) SABnbzd'
6. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) 'medusa'

**Expected behavior**
No errors :) 

**Log**
`fatal: detected dubious ownership in repository at 'xxx/nzbToMedia'
To add an exception for this directory, call:

git config --global --add safe.directory 'xxx/nzbToMedia'
fatal: detected dubious ownership in repository at 'xxx/nzbToMedia'
To add an exception for this directory, call:

git config --global --add safe.directory 'xxx/nzbToMedia'
xxx/nzbToMedia/libs/common/beets/mediafile.py:19: UserWarning: beets.mediafile is deprecated; use mediafile instead
warnings.warn("beets.mediafile is deprecated; use mediafile instead")
[20:28:17] [INFO]::MAIN: Loading config from [xxx/nzbToMedia/autoProcessMedia.cfg]

[20:28:17] [INFO]::MAIN: Python v3.10 will reach end of life in 1377 days.
[20:28:17] [INFO]::MAIN: Checking database structure...
[20:28:17] [INFO]::MAIN: Checking if git needs an update
[20:28:17] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
[20:28:17] [INFO]::MAIN: No update needed
[20:28:17] [INFO]::MAIN: nzbToMedia Version:12.1.11 Branch:master (Linux 4.4.180+)`

-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error Code: 128

-- Cleaning folders: ['libs', 'core'] --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error Code: 128

**Comment by labrys** [comment]
My first assumption would be a permissions error on the folder.

**Comment by clinton-hall** [comment]
Yes, permissions/ownership... 
DSM is still the NAS I have never played with so I can't test...
I would firstly make sure that the user that runs SABnzbd has full permissions for nzbToMedia directory... even better is to do the git clone AS the users that runs SABnzbd.

Or perhaps try setting the git safe.directory
`git config --global --add safe.directory 'xxx/nzbToMedia'`

**Comment by HPMSGEN8** [comment]
Thanks both. I will go check again but the rights was correct. I am not sure i can use the account for SABnzbd.

Let me go look at this. Thanks again & Happy Holidays

**Comment by HPMSGEN8** [comment]
Still getting the same errors on git. i have even tried docker as well and all the same.

Any advice please.

**Comment by HPMSGEN8** [comment]
Closing Issue Solved

**Comment by labrys** [comment]
What was the fix?
