### ISSUE TITLE
Cannot run any python scripts on Synology (nzbToMedia.py / TorrentToMedia.py)

### ISSUE THREAD

**Issue by MrCee** [clinton-hall/nzbToMedia#1957]
**Describe the bug**

**Technical Specs**
1. Running on Synology
2. Python version 'Python 3.10.5'
3. Download Client 'SABnbzd, Download Station
4. Intended Media Management 'SickChill, Radarr'
**Expected behavior**

I haven't been able to run any scripts for a few months now

```
./nzbToMedia.py

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean


-- Cleanup finished --

Traceback (most recent call last):
  File "/volume1/docker/nzbToMedia/./nzbToMedia.py", line 734, in <module>
    import core
  File "/volume1/docker/nzbToMedia/core/__init__.py", line 52, in <module>
    from core import logger, main_db, version_check, databases, transcoder
  File "/volume1/docker/nzbToMedia/core/logger.py", line 10, in <module>
    import logging
ModuleNotFoundError: No module named 'logging'
```

I have tried a fresh git clone and dropped the `autoProcessMedia.cfg` in the new clone.

Any suggestions?

Ive tested all of them to see if they will run, they don't run. I'd still like to use `TorrentToMedia.py` with Download Station

```
./TorrentToMedia.py 

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean


-- Cleanup finished --

Traceback (most recent call last):
  File "/volume1/docker/nzbToMedia/./TorrentToMedia.py", line 20, in <module>
    import core
  File "/volume1/docker/nzbToMedia/core/__init__.py", line 52, in <module>
    from core import logger, main_db, version_check, databases, transcoder
  File "/volume1/docker/nzbToMedia/core/logger.py", line 10, in <module>
    import logging
ModuleNotFoundError: No module named 'logging'

```

**Comment by clinton-hall** [comment]
it looks like your python is missing logging.

you will need to install logging (within your docker?) using
'pip install logging'

**Comment by MrCee** [comment]
The thing is, I've found the great way to have your script alongside ever docker, and although the nzbToMedia folder is simply a git clone, ever docker container reaches in and uses it seamlessly without the need to adjust docker containers.
Can we add logging toy wooer script instead? 

I don't build a fancy docker container with extra parameters, willing to try... but if there is a way for you to unsure login will work with your script without changing a container that would be great. 

I opten am used to running your scripts and they work on all containers.There was so much work we put into TorrentToMedia.py for download station, and on Synology this is not a docker container... so maybe we could include what is missing here in your script?

**Comment by labrys** [comment]
@MrCee logging is built in to Python.  If logging isn't available its likely because the system has explicitly removed it from Python or is otherwise preventing it from importing.  Its more of a problem with the configuration of the system and trying to include logging within nzbToMedia could cause issues for other users that are properly configured.  Could you provide more information about the docker containers that you are using?

**Comment by MrCee** [comment]
The docker containers I used are:

linuxserver/sabnzbd
linuxserver/radarr:latest

with the current config each container reaches in to the nzbToMedia folder easily. Here's and example where I ensures the internal path is the same as the external path in the docker-compose.yml 
My nzbToMedia folder sits alongside all docker containers and reaching into this folder is very straight forward when you set the exact same path externally and internally. Everything just works. Until this logging issue. Note: Python 3.10.5 is now the default on Synology NAS.

```
    volumes:
    - /volume1/docker/nzbToMedia:/volume1/docker/nzbToMedia
```

**Comment by MrCee** [comment]
Fixed issue by removing /opt/bin/python &  /opt/bin/git and re-installing python and git using Synology Package Manager, and updating `autoProcessMedia.cfg` for correct path of git.

Received this message and ran the command as requested. All works again.

```
fatal: detected dubious ownership in repository at '/volume1/docker/nzbToMedia'
To add an exception for this directory, call:

	git config --global --add safe.directory /volume1/docker/nzbToMedia
```
