### ISSUE TITLE
Required Subfolder Missing (Postprocess)

### ISSUE THREAD

**Issue by W13N3N** [clinton-hall/nzbToMedia#1961]
I just configured the nzbtomedia script and when i'm post processing my download from sabnzbd to medusa i'm getting the following error;

`Changing to directory: C:\nzbToMedia-master

-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [WinError 2] Het systeem kan het opgegeven bestand niet vinden

Directory is not a git repository

Force cleaning folder: libs
Skipping required subfolders ['common', 'custom', 'py2', 'win']

Force cleaning folder: core
Skipping required subfolders ['auto_process', 'extractor', 'plugins', 'processor', 'utils']
Traceback (most recent call last):
File "C:\nzbToMedia-master\nzbToMedia.py", line 732, in <module>
cleanup.clean(cleanup.FOLDER_STRUCTURE)
File "C:\nzbToMedia-master\cleanup.py", line 208, in clean
force_clean_folder(folder, subfolders)
File "C:\nzbToMedia-master\cleanup.py", line 169, in force_clean_folder
raise Exception('Required subfolders missing:', missing)
Exception: ('Required subfolders missing:', ['processor'])`

**Technical Specs**
1. Running on 'Windows'
2. Python version '3.10.9'
3. Download Client 'SABnzbd'
4. Intended Media Management 'Medusa'

**Expected behavior**
The processing from the download to medusa

**Log**
See code above

**Comment by labrys** [comment]
It looks like you may have a corrupted install of nzbToMedia.  It can't find a the folder `C:\nzbToMedia-master\core\processor'.  I would recommend reinstalling.

**Comment by W13N3N** [comment]
@labrys ; thanks for your reply and apologies for my late reply. (i've been very busy)

You are correct, the "processor" folder was indeed missing. But i've downloaded the latest v12.1.10 release (https://github.com/clinton-hall/nzbToMedia/releases/tag/12.1.10) and within the .zip file it is also missing. I assume it also should be presented there?

I now downloaded the "Master" release and it's working again!

**Comment by W13N3N** [comment]
@labrys; all of a sudden my "processor" folder is missing again. I haven't done anything in my configuration. Only auto updating nzbtomedia.

Could there be a reason why this folder is missing? Could it have something to do with the auto update?

**Comment by W13N3N** [comment]
@clinton-hall does the auto updater use the latest .zip release? Because as mentioned earlier, when i download the .zip file the processor folder is missing?

**Comment by clinton-hall** [comment]
If installed via git, the auto updater should use git. If you installed a zip release, then it should update to the latest zip release.
I haven't done a release for a while so not sure why this has just popped up again.

I'll look at trying to push out the latest release and see if that fixes it.

**Comment by W13N3N** [comment]
@clinton-hall , thanks for your quick reply! I indeed installed a zip release. I wasn't aware there was a difference. I will reinstall with Git if this will fix the problem.

**Comment by clinton-hall** [comment]
I created a new release last night. Check to see if this new release works.

**Comment by W13N3N** [comment]
The auto update found the newer version and installed it correctly! Problem solved! Thanks for your quick help/response @clinton-hall
