### ISSUE TITLE
nzbToNzbDrone: NzbDrone: Failed to post-process - Returned log from NzbDrone was not as expected.!

### ISSUE THREAD

**Issue by specter9mm** [clinton-hall/nzbToMedia#1965]
**Describe the bug**
I recently updated sonarr 3.0.10.1567, and at first it seemed to work fine with nzbtomedia, but now I am getting the error in the title.

**Technical Specs**
1. Sonarr is running in a container on truenas scale, and nzbget is running on a debian 11 VM on the same machine. At first I switch back to python 2.7 to try to remediate the issue, but both puthon 2 and 3 produce the same error.
2. Python version I have tried both 2 and 3 with the same error.
3. Download Client NzbGet
4. Intended Media Management Sonarr

**Expected behavior**
Normally the script notifies nzbget and the import proceeds without issue.

**Log**
Please provide an extract, or full debug log that indicates the iss
[nzbtomedia.log](https://github.com/clinton-hall/nzbToMedia/files/11071057/nzbtomedia.log)
ue.

**Comment by specter9mm** [comment]
Reverse proxy ended up being the issue, corrected the root web dir in the nzbtomedia nzbdrone config resolved the issue, sorry for the noise.

**Comment by clinton-hall** [comment]
Good catch. Glad you have it all working.
