### ISSUE TITLE
Error with Addic7ed subtitle

### ISSUE THREAD

**Issue by shizo971** [clinton-hall/nzbToMedia#1977]
**Describe the bug**
I have the right setup but i can't use addic7ed subtitles. I don't know why.
https://www.addic7ed.com/user/62**** and my password.
Any one have this error too plz ? How to provide a solution please?
Or, is there another problem with addic7ed api ?
Best regards.

**Technical Specs**
1. Running on Synology DS918+
2. Python version 3.11.4
3. Download Client SABnbzd 4.0.3 [[9fafe64]
4. Intended Media Management Medusa Version: 1.0.17 / Branch: master / Commit: 3d656652ab277e47689483912ed7fc443e7023e8

**Expected behavior**

**Log**
2023-08-03 19:46:37 WARNING  Thread_2 :: [3d65665] Failed to login, check your userid, password

**Comment by clinton-hall** [comment]
#1035
I don't think this has been updated to add Addic7ed login details

**Comment by clinton-hall** [comment]
all good. Hope you get it fixed.
