### ISSUE TITLE
binhex SABnzbd nzbtomedia script errors - how to get the latest version of your script?

### ISSUE THREAD

**Issue by PonyXpress** [clinton-hall/nzbToMedia#1981]
**Describe the bug**

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) '.unraid, sabnzbd docker...'
2. Python version '.3.10.10...'
3. Download Client (NZBget, SABnbzd, Transmission) '..sabnzbd docker..'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) '.sickchill...'

**Expected behavior*script has been running great for years, but how I get errors with the latest version of sabnbzd docker*
I had to roll back my docker version and it worked again.  sabnbzd support says I need the updated nzbtomedia script so it will work with the new version of his docker.

I don't remember how to update the script.  I think I need to git pull to get your latest version, but I don't remember how to do that.  I found another post here that looks to be the same issue as me, https://github.com/clinton-hall/nzbToMedia/issues/1960

*Traceback (most recent call last): File "/nzbToMedia/nzbToSickBeard.py", line 275, in <module> import nzbToMedia File "/nzbToMedia/nzbToMedia.py", line 732, in <module> eol.check() File "/nzbToMedia/eol.py", line 101, in check warn_for_status(version, grace_period) File "/nzbToMedia/eol.py", line 142, in warn_for_status days_left = lifetime(version) ^^^^^^^^^^^^^^^^^ File "/nzbToMedia/eol.py", line 72, in lifetime time_left = PYTHON_EOL[(major, minor)] - now ~~~~~~~~~~^^^^^^^^^^^^^^^^ KeyError: (3, 11)*Log**
Please provide an extract, or full debug log that indicates the issue.

**Comment by clinton-hall** [comment]
Yes, you will need to do a git pull. You may need to do that from within the Docker terminal if you can.

Once you are connected via terminal (as the appropriate user) try the following commands to do a git pull (and clean etc)
```
cd /nzbToMedia
git reset --hard
git pull
git clean
```

**Comment by PonyXpress** [comment]
Thank you for the guidance here.  All commands worked except the last one.

sh-5.1# git clean
fatal: clean.requireForce defaults to true and neither -i, -n, nor -f given; refusing to clean

**Comment by PonyXpress** [comment]
I have two issues.  The git clean command refused, as it wants a -i, -n
which one do I use?

for some reason, sabnzbd isn't running the script anymore, and I have not changed anything.  I just confirmed that I have your latest version.  Any ideas what to check?

**Comment by clinton-hall** [comment]
when you say sabnzbd isn't running the script... Is there any logging in SABnzbd to say that it tired it run the script, or any errors?
If not, then it sounds like the SABnzbd settings got changed somehow and the scripts are not set to run.

**Comment by PonyXpress** [comment]
nothing in the logs about anything failing.  Today I forced the docker to update and did a fresh git for your script, and now everything is working again.  I have no idea what happened.  thank you for the quick response to help!
