### ISSUE TITLE
KeyError: (3, 12)

### ISSUE THREAD

**Issue by DrakeJones** [clinton-hall/nzbToMedia#1983]
I use nzbToMedia for qBittorrent and manual post processing. Everything was set up and working perfectly on my old server, but I just built a new server and nzbToMedia isn't working on it.  I have no idea how to resolve this.  Thanks in advance!

**Describe the bug**
C:\Scripts\nzbToMedia>C:\Scripts\nzbToMedia\nzbToSickBeard.py
Traceback (most recent call last):
  File "C:\Scripts\nzbToMedia\nzbToSickBeard.py", line 275, in <module>
    import nzbToMedia
  File "C:\Scripts\nzbToMedia\nzbToMedia.py", line 731, in <module>
    eol.check()
  File "C:\Scripts\nzbToMedia\eol.py", line 102, in check
    warn_for_status(version, grace_period)
  File "C:\Scripts\nzbToMedia\eol.py", line 143, in warn_for_status
    days_left = lifetime(version)
                ^^^^^^^^^^^^^^^^^
  File "C:\Scripts\nzbToMedia\eol.py", line 73, in lifetime
    time_left = PYTHON_EOL[(major, minor)] - now
                ~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: (3, 12)

**Technical Specs**
1. Running on Windows 10
2. Python version '3.12
3. Download Client  SABnbzd, qBittorent.'
4. Intended Media Management Radar, Lidar, Medusa

**Expected behavior**
Post Process all media files in completed folder

**Log**
No log entries

**Comment by wraithfive** [comment]
I'm having the same issue for last couple days.

**Comment by DrakeJones** [comment]
Fixed: Added `(3, 12): date('2028-10-1'),` to eol.py.
