### ISSUE TITLE
sickbeard:tv could not create a fork object for sickgear-api. probaly class not added yet.

### ISSUE THREAD

**Issue by potestus** [clinton-hall/nzbToMedia#1992]
**Describe the bug**
sickbeard:tv could not create a fork object for sickgear-api. probaly class not added yet.

**Technical

Qnap sherpa sickgear sabnzb etc

This is just an annoyance as it still works is there a solution?

**Comment by clinton-hall** [comment]
https://github.com/clinton-hall/nzbToMedia/commit/acf843ab176b9ac051e17a9be24c16689e2ef3e8

Put into debug logging only.
Need time to actually look at creating more class objects for each fork.
