### ISSUE TITLE
Failed Downloads - Unable to Delete Folder Error

### ISSUE THREAD

**Issue by abatchx** [clinton-hall/nzbToMedia#1998]
**Describe the bug**
Permission denied error, on temp folder deletion - when using failed downloads handling

**Technical Specs**
1. Running on - Synology DSM 6 (not in a docker container)
2. Python version - 3.7.12 (according to medusa interface) 
3. Download Client - SABnbzd
4. Intended Media Management - medusa

**Expected behavior**
Folder deletion of the temp (failed) download folder(s)

**Log**
`2024-07-18 12:33:58 WARNING  Thread_5 :: [c5a1e37] Unable to delete folder: /volume1/downloads/Incomplete Downloads/Star.Trek.Discovery.S05E04.1080p.HEVC.x265-MeGusta: Error: 13: Permission denied
Traceback (most recent call last):
File "/volume1/@appstore/medusa/var/src/medusa/process_tv.py", line 704, in delete_folder
shutil.rmtree(folder)
File "/var/packages/python3/target/lib/python3.7/shutil.py", line 494, in rmtree
_rmtree_safe_fd(fd, path, onerror)
File "/var/packages/python3/target/lib/python3.7/shutil.py", line 428, in _rmtree_safe_fd
onerror(os.open, fullname, sys.exc_info())
File "/var/packages/python3/target/lib/python3.7/shutil.py", line 426, in _rmtree_safe_fd
dirfd = os.open(entry.name, os.O_RDONLY, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'ADMIN`

**Additional notes**
Using the above setup, I've added both the Sab user and also the medusa user with the ability to delete these folders. I'm assuming that the NZBtoMedia script is running as an another user, hence the error. But I can't work out which one - any help would be appreciated 😄 the log above is from medusa and I've assumed that this is a NZBtoMedia error - but I could be entirely incorrect!

Thank you

**Comment by clinton-hall** [comment]
nzbToMedia should run as the same user that SABnzbd runs as.

I'm not sure what happened with the log posted above, but I suspect something was truncated? I note the last bit of that log says `ADMIN` so is it possible that something is actually running as ADMIN user here?

If you have (ideally debug) logs from nzbToMedia from this same execution we could try and tell what is going on, but in general, for a failed download nzbToMedia shouldn't be touching the files/folders unless it is to do the deletion/cleanup and then I wouldn't expect medusa to try and delete it as it shouldn't find anything to delete... or the error should be different (no such file, not permissions related)

**Comment by abatchx** [comment]
Sorry Clinton - My paste job from Notion was terrible. Grabbed the logs from Sab / Medusa / NZBtoMedia (just the standard one) for the same run - see below.

The more I've looked at this the more I don't think this is your awesome script causing the error. But I'm still at a loss as to what I've done wrong....

[Medusa Log - Extract.txt](https://github.com/user-attachments/files/16502164/Medusa.Log.-.Extract.txt)
-Error starts at line 61
[Sab - Script Log.txt](https://github.com/user-attachments/files/16502165/Sab.-.Script.Log.txt)
[NZBtomedia - Extract.txt](https://github.com/user-attachments/files/16502419/NZBtomedia.-.Extract.txt)

**Comment by clinton-hall** [comment]
Who is the current owner, and what are the permissions set for
`/volume1/downloads/Incomplete Downloads/Star.Trek.Discovery.S05E04.1080p.HEVC.x265-MeGusta/__ADMIN__`

I can see that nzbToMedia does extract some files:
`Extraction was successful for /volume1/downloads/Incomplete Downloads/Star.Trek.Discovery.S05E04.1080p.HEVC.x265-MeGusta/__ADMIN__/Star.Trek.Discovery.S05E04.1080p.HEVC.x265-MeGusta.nzb.gz to /volume1/downloads/Incomplete Downloads/Star.Trek.Discovery.S05E04.1080p.HEVC.x265-MeGusta/__ADMIN__`
but this would have added files into the __ADMIN__ directory and should not have changed the permissions.

Also, check the files within this directory to see if there are any strange ownership of permissions... I wonder if the extraction has extracted with ownership/permissions from within the .gz (i.e. ownership was set on the .gx creator's system???). If there is a file within the directory that cannot be deleted, that could prevent the directory itself from being deleted?

**Comment by abatchx** [comment]
Thanks Clinton - Did some more digging...

Screenshot of permissions for those folders here:
![Permissions Screenshot](https://github.com/user-attachments/assets/ff0dfb2b-1170-4acf-a2f0-7aa3b5a79231)

Using the synology permissions inspector (its a lot nicer to look at than the terminal view). It would appear that its creating the temp folder with every permission **minus** the delete permission :/

I've tried forcing the permission on this folder / sub-folders. But its hard to recreate without a download that I know will fail. I'm going to see if this will work and if not try your config setting as above.

Thank you for your help in diagnosing this issue :)

**Comment by clinton-hall** [comment]
I don't think the settings I suggested will make any difference.
The concern I had was that the extraction was creating some non-defined user.

The details you posted above show that all files inside the __ADMIN__ folder have the same user and permissions.

I don't think there is any issue with a "delete" permission. I believe the "drwxrwxrwx" in the lines above show
d = directory
rwx = read, write, execute permissions for the owner (sc-sabnzbd)
rwx = read, write, execute permissions for the group members (sabnzbd)
rwx = read, write, execute permissions for guests/other users

The problem is the __admin__ directory is only drwx------ which means ONLY sc-sabnzbd user has any permissions.
all files in the folder have only -rw------- which again means only sc-sabnzbd user (or root) can see, read, write, delete the files.

SABnzbd has the option to set permissions for successful downloads, but I don't know if it does for failed... If so, you would want to set that.
Otherwise what you would need to do I try and get both sabnzb and medusa running as the same user (but I don't think DSM likes that).

The other option would be to enable clean-up deletion of failed downloads in SABnzbd, or try getting nzbToMedia to delete failed files
in autoProcessMedia.cfg
```
[sickbeard]
    [[tv]]
        delete_failed = 1
```

**Comment by abatchx** [comment]
> SABnzbd has the option to set permissions for successful downloads, but I don't know if it does for failed... If so, you would want to set that.
Just checked and you are correct it doesn't
>Otherwise what you would need to do I try and get both sabnzb and medusa running as the same user (but I don't think DSM likes that).
Yeah again DSM really doesn't like that, plus I don't think my Linux talent is enough to actually get it to work.

I've set the two settings that you've suggested with the AutoProcessMedia.cfg file and I'll monitor whether this works. As much as this is really annoying it doesn't break anything and just means that I have to randomly go in and delete the temp folders.. Remembering is the biggest issue :D

As always, thank you very much for the really helpful responses :)

**Comment by abatchx** [comment]
Applied both the config changes and ironically had a number of files fail last night. Issue still persists with the errors in the medusa log. On the basis that I don't think this is your issue to resolve (and you've already been more than helpful) feel free to close this one :)
