### ISSUE TITLE
Current support status.

### ISSUE THREAD

**Issue by bengalih** [clinton-hall/nzbToMedia#1999]
Hey Clinton.

I'm just curious as to the current state of this project.  I'm asking because I had this configured on my setup (mostly for Sonarr usage, but other stuff was configured but not highly used).
I have a deluge post download script that is calling TorrentToMedia.py, but on review of my setup it doesn't look like that script is running due to me changing directories and never updating the script?  Maybe?

I have the watch_dir configured wrong, but I call the script directly with parameters from deluge:
torrent id, name, directory

So honestly I don't even know if this thing is doing anything on my system anymore.  I remember when I set it up I had a need for it and it solved my issues, but that was 5 years ago and I can't recall everything I did and the eccentricities of what I learned about the scripts.

So I'm wondering:
1) How can I figure out if the script is actually doing anything
2) Should this script actually still be compatible with all the latest versions of the supported apps?
3) Is it still being supported when changes are made?
4) Has everyone just moved on?  If so to what newer solutions??

I appreciate your time coding this and for any answers you can provide.

**Comment by clinton-hall** [comment]
Ok, firstly, the project is still being maintained, but without any significant new development work, i.e. I just try to keep it running for those who need it.

To answer the specific questions:

1. How can I figure out if the script is actually doing anything
    Check the logs at nzbToMedia/logs/nzbToMedia.log
    If there are no recent entries, then the script isn't even being called/run.
    If there are entries, reading through these should clarify what processing are being used.
2. Should this script actually still be compatible with all the latest versions of the supported apps?
    Yes. As any changes to apps are identified, I update nzbToMedia to match.
3. Is it still being supported when changes are made?
    Yes.
4. Has everyone just moved on? If so to what newer solutions??
    To be honest, I believe a lot of people have moved on for various reasons:

- One of the key reasons for on-completion postprocessing was to reduce the load on small NAS systems. As CPU power has increased I don't believe this is a concern for the majority of people.
- Streaming services are more popular (compared to when this project first started) and for a number of people this might be easier than trying to set up automated downloading etc. Obviously for those of us annoyed with the changing streaming services and availability, downloading is actually the better option....
- CouchPotato is no-longer being maintained (I do still use it, and it works for me). This was the catalyst for this project.
- Sonarr and Radarr, while supported by this project don't really need the post-processing as they handle the file renaming differently.
- Many of the additional postprocessing features of this project have been made available within the SickChiil, SickBeard, SickGear, Medusa, Sonarr, Radarr products. i.e. Failed download handling.
- Many of the other features may not be as relevant.
    Transcoding was originally added to allow files to be converted to formats playable on apple/roku etc... I believe newer devices have much greater codec support and I don't know how necessary this feature is for the majority of users.
    The file fake detection is available in other scripts for nzbGet (no longer supported) and I believe major usenet indexers are doing better at removing these (or this isn't as big an issue any more)
- A number of people are using RSS feeds directly in their Usenet indexers and therefore not even using Sick* , Sonarr, Radarr. I'm not sure what they use for their renaming etc. I assume there are other tools.
- One of the other key features of this script is the ability to link torrent files to both the download location (to keep seeding) and the final (renamed) library location. Again, I suspect other tools probably exist to do this. I believe some of the Sick* forks and maybe Sonarr/Radarr support this functionality internally.

I am sure there are a number of other changes. To be honest I don't know all of the different setups that exist, and I don't really have visibility as to how many people are still using this project (I can see there were 35 unique clones in the last 2 weeks, and 329 unique visitors to the project...)

You could try turning off nzbToMedia and see if everything still works. If so, it isn't required. If you have a specific requirement that nzbToMedia meets, then by all means feel free to use it.

**Comment by bengalih** [comment]
Thanks for the in-depth reply.
Looking deeper into my config it appears that the script hasn't been running for me, perhaps for a couple of years now ever since a drive letter change.
I think that I was using it mostly with CouchPotato as well, which I too still use, but barely.
I will be redoing my setup soon and not sure if I will have the need for this, but great to know it is still functional and you still support.
Appreciate your efforts!
