### ISSUE TITLE
qBittorrent V5.0 - Resume/Pause Functions Replaced With Start/Stop

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [clinton-hall/nzbToMedia#2000]
@clinton-hall 
Just letting you know that:

`api/v2/torrents/pause` and `api/v2/torrents/resume` is now `api/v2/torrents/stop` and `api/v2/torrents/start`

full credits goes to this post here by @borntohonk on pyMedusa's issue page: https://github.com/pymedusa/Medusa/issues/11844#issuecomment-2395316482 _<-- more info about all the changes here._

I know that nzbtomedia pauses the torrent before post-processing, so you may want to update your script to fix this to add support to qBittorrent 5.0 while still having legacy support for 4.0 etc.

**Comment by borntohonk** [comment]
> @clinton-hall Just letting you know that:
> 
> `api/v2/torrents/pause` and `api/v2/torrents/resume` is now `api/v2/torrents/stop` and `api/v2/torrents/start`
> 
> full credits goes to this post here by @borntohonk on pyMedusa's issue page: [pymedusa/Medusa#11844 (comment)](https://github.com/pymedusa/Medusa/issues/11844#issuecomment-2395316482) _<-- more info about all the changes here._
> 
> I know that nzbtomedia pauses the torrent before post-processing, so you may want to update your script to fix this to add support to qBittorrent 5.0 while still having legacy support for 4.0 etc.

https://github.com/qbittorrent/qBittorrent/blob/21b03676296356ece74c4902de190beccc119c7b/src/webui/www/private/scripts/mocha-init.js#L527

https://github.com/qbittorrent/qBittorrent/blob/21b03676296356ece74c4902de190beccc119c7b/src/webui/www/private/scripts/mocha-init.js#L541

the specific source-code related objects can be found here.

**Comment by XxUnkn0wnxX** [comment]
I've tested it, more details here: https://github.com/clinton-hall/nzbToMedia/pull/2001#issuecomment-2425460906

**Comment by XxUnkn0wnxX** [comment]
ok should be working on commit: c689f5c6b3e0f4b91a57a669ecee810305d8f3f2 final tests are done..
