### ISSUE TITLE
[Couchpotato] No JSON object could be decoded

### ISSUE THREAD

**Issue by Mirabis** [clinton-hall/nzbToMedia#226]
INFO    ====================
16:06:15|INFO    nzbToMedia V8.6
16:06:15|INFO    MAIN: Loading config from C:\nzbToMedia\autoProcessMedia.cfg
16:06:15|INFO    MAIN: Script triggered from SABnzbd
16:06:15|INFO    MAIN: Calling CouchPotatoServer to post-process: this is the end 2013 bluray 1080p dts-hd x264-grym.cp(tt1245492).nzb
16:06:15|INFO    Loading config from C:\nzbToMedia\autoProcessMedia.cfg
16:06:15|INFO    Found movie id tt1245492 in name
16:06:18|INFO    Found movie id 142 in CPS database for movie tt1245492
Traceback (most recent call last):
  File "C:\nzbToMedia\nzbToMedia.py", line 391, in <module>
    result = autoProcessMovie.process(nzbDir, inputName, status, clientAgent, download_id)
  File "C:\nzbToMedia\autoProcess\autoProcessMovie.py", line 250, in process
    initial_status, clientAgent, download_id, initial_release_status = get_status(baseURL, movie_id, clientAgent, download_id)
  File "C:\nzbToMedia\autoProcess\autoProcessMovie.py", line 128, in get_status
    result = json.load(urlObj)
  File "C:\Python27\lib\json__init__.py", line 290, in load
    **kw)
  File "C:\Python27\lib\json__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

On every download :(

**Comment by icebal** [comment]
after trying the newest dev and stable branches, im getting this error on both. pastebin link from sab's log here:
http://pastebin.com/F4WSzms1

**Comment by clinton-hall** [comment]
Please edit autoProcessMedia.cfg
[General]
    Log_debug = 1

Then post logs after next pp event.

Check the CouchPotato apiary and url_base as set in autoProcessMedia.cfg
