### ISSUE TITLE
OSX error:  env: python2: No such file or directory

### ISSUE THREAD

**Issue by Tjiet** [clinton-hall/nzbToMedia#454]
During PP using latest dev build a error is logged, no update process is running.

env: python2: No such file or directory

Perhaps a sticky is in order to manual fix this ??

**Comment by BinaryDennis** [comment]
sudo ln -sf /usr/bin/python2.7 /usr/local/bin/python2 works better for me :)

**Comment by PaulAustin** [comment]
Yes "/usr/local/bin" works better for El Capitan. I ran into the same thing. Looks to be part of [System Integrity Protection](https://en.wikipedia.org/wiki/System_Integrity_Protection). There is a bit more of a write up [here.](http://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really)

**Comment by nbara** [comment]
@BinaryDennis This doesn't work for me on El Capitan.

The only thing that works is replacing ` #!/usr/bin/env python2 ` by `#!/usr/bin/env python` in all the nzbtomedia scripts. But then it breaks the git updates.

**Comment by greggman** [comment]
I'm on El Capitan, worked fine for me

<img width="737" alt="screen shot 2016-02-05 at 12 29 53 am" src="https://cloud.githubusercontent.com/assets/234804/12821737/9e28bacc-cb9f-11e5-8944-696dd1afeaf1.png">

**Comment by Morgon** [comment]
I've installed python via brew, which already puts symlinks in `/usr/local/bin`. Python works great within a terminal session, but when NZBGet runs an nzbToMedia script, the script claims (or env claims, at least) that it can't find python2. This is probably because if you haven't restarted your user session, `/usr/local/bin` hasn't been added to your PATH.

I was able to run `open -a nzbget` from the command line to get everything working in the current session. I've no doubt it'll be fine during reboots now.

**Comment by greggman** [comment]
I'm guessing this is clear but you shouldn't need `brew` for `python`. `python` is a default part of OSX

**Comment by nbara** [comment]
@greggman could it be because I mostly use anaconda python?

Here's what my .bash_profile looks like:
```# Anaconda python comes first
export PATH="/Users/nicolas/anaconda/bin:/usr/local/bin:/usr/local/sbin:$PATH"```

**Comment by fgreco** [comment]
I'm on Yosemite on my Mac and I've tried all the suggestions here with no luck.

The furthest I've gotten is after I setup the symlink:
   % sudo ln -sf /usr/bin/python2.7 /usr/local/bin/python2

I get:
% ./s3cmd --version

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

Error loading some components of s3cmd (Import Error)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


any help is appreciated!

**Comment by clinton-hall** [comment]
ok... created a new Branch `OSX`
switch to this branch and see if that works.
I will keep this up-to-date with Master Branch

**Comment by loganjeon** [comment]
In High-Sierra, OSX, I shoud setup the symlink like below:

% ln -sf /usr/bin/python2.7 /usr/local/bin/python2

It is works well.

**Comment by shchypylov** [comment]
Thanks @loganjeon, also works for Mojave
