### ISSUE TITLE
TorrentToMedia not being called? (now: DS compatibility WIP)

### ISSUE THREAD

**Issue by piejanssens** [clinton-hall/nzbToMedia#469]
I've set up SR to use torrents for backlog.
Followed the nzbToMedia wiki on how to setup TorrentToMedia.
The torrent is added to transmission, but when the download finishes nothing happens and I don't see any errors or log traces of calling the TorrentToMedia.py script in logs/nzbtomedia.log.

Update: when I stop/start the transmission package (SynoCommunity) the settings.json file is overwritten or at least this part is overwritten:

```
"script-torrent-done-enabled": true, 
"script-torrent-done-filename": "/volume1/downloads/nzbToMedia/TorrentToMedia.py",
```

**Comment by Danikool** [comment]
Hello,

After hours and hours, I managed to make TorrentToMedia work with Transmission. But I can't make it work it work with Download Station, even though I religiously followed the wiki how-to.

I get a "failed to connect to transmission".

I tried without password, with password, assigning a port to DS. Nothing seems to work.

So I wonder, is the wiki still up-to-date and I'm doing something wrong, or has something change with the recent DS updates ?

**Comment by piejanssens** [comment]
Just stick to Transmission. I gave up on DS because it shuts down the service when the queue is idle.

**Comment by Danikool** [comment]
Ok thanks. Good to know. Nevertheless, do you know if TorrentToMedia can still connect to DS like you used to (using the transmission setting with port 9093) ?

**Comment by MrCee** [comment]
Yes it does, but so far I have not been able to get further scripts invoked. This used to work. I have raised this with Synology. I also have needed to move away from Download Station to Transmission just to get TorrentToMedia.py to run.
