### ISSUE TITLE
Add Plex update

### ISSUE THREAD

**Issue by clinton-hall** [clinton-hall/nzbToMedia#566]
Looking at adding plex notification. As suggested in #545
Need plex notification (with a Plex library update command) to be called after the files have been renamed/moved by SB/CP.
Need this to support user authentication.

**Comment by endiz** [comment]
any way we can star this request? :)

**Comment by clinton-hall** [comment]
Consider it stared ;)
I just need time to work on it.

**Comment by climmax** [comment]
you could use this

http://[PMS_IP_Address]:32400/library/sections?X-Plex-Token=YourTokenGoesHere

token can be found here
https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token?preview%5Btheme_id%5D=201342253%27+%27&use_theme_settings=false

**Comment by clinton-hall** [comment]
ok.. in theory this should be in nightly branch...you add the following into the .cfg

```
[Plex]
    plex_host = localhost
    plex_port = 32400
    plex_token =
    plex_ssl = 0 
    # Enter Plex category to section mapping as Category,section and separate each pair with '|'
    # e.g. plex_sections = movie,3|tv,4
    plex_sections = 
```

so what you need to add, for most installs, is `    plex_token =` your token as found on https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token?preview%5Btheme_id%5D=201342253%27+%27&use_theme_settings=false

and `plex_sections` needs to be a list of the categories (as defined in your downlaoder and their appropriate section number in your Plex database.

e.g if your movies is section 1 and your downlaoder category is "Movies", and your shows are section 2 and your downlaoder category is "TV" you would have
`plex_sections = Movies,1|TV,2`

Please let me know if this works as wanted... haven't really been able to test, just made sure the basic functions didn't break.

**Comment by endiz** [comment]
I'll try and test this weekend. Thanks!

**Comment by climmax** [comment]
Great Job! I will give it a go tomorrow.

**Comment by climmax** [comment]
Tested! Works like a charm!
After download finished
In plex server activity i got this Alert notification:
Scanning the "TV Shows" section
[03:28:32] [DEBUG]::PLEX: Attempting to update Plex Library for category tv.
[03:28:32] [DEBUG]::PLEX: Plex Library has been refreshed.

**Comment by simonbasle** [comment]
hi @clinton-hall

it seems like this feature breaks the script for people (like me) who don't use plex :cry:, when autoupgrading the script without adding the [Plex] config section...

it will complain about `TypeError: 'NoneType' object is not iterable` in [`for item in core.PLEXSEC`][0], but originally I think this is because of the ` or None` in [there][1]...

to make it transparent upon upgrade you could choose to alternatively use an empty list, `[]` instead of `None`, wdyt? :thought_balloon:

[0]: https://github.com/clinton-hall/nzbToMedia/commit/042fcce6b7a7ab0f697af68d6f4e0eff25fd159b#diff-9fecf744635dbfd1b368c4bee46a1d63R1064

[1]: https://github.com/clinton-hall/nzbToMedia/commit/042fcce6b7a7ab0f697af68d6f4e0eff25fd159b#diff-3464e388711711d3f415d392db0de2ceR365

**Comment by clinton-hall** [comment]
Hopefully fixed...

**Comment by simonbasle** [comment]
:+1:

**Comment by Mirabis** [comment]
Is it possible to do this? 
"tv,1|tv-drone,1|movie,2|,movie3d,2|tv,4|tv-drone,4"
To update multiple sections? As sonar downloads both anime / regular with same category but to different library ;p

**Comment by clinton-hall** [comment]
Yes, that should be possible. Exactly as suggested. Please test and report the outcome.

**Comment by frriction** [comment]
If someone comes wondering how to find section number in PMS than go to 
http://[PMS_IP_Address]:32400/library/sections
find in page for word "key" , value of key is section number.

**Comment by clinton-hall** [comment]
Great info. 
Thanks, I'll add to wiki.

**Comment by thesatman** [comment]
Do I need to configure autoProcessMedia.cfg with my Plex credentials if I am using CouchPotato and SickRage where I already have configured this part there as well? If not, maybe a good idea to add this in a ##comment. I was reading and testing this new feature. Only to find out after an hour or two that I already had this configured in another place ;)

**Comment by clinton-hall** [comment]
yeah, fair call... I've edited the wiki and the comments in autoProcessMedia.cfg
