### ISSUE TITLE
Add Concat option for cd1 cd2 movies.

### ISSUE THREAD

**Issue by clinton-hall** [clinton-hall/nzbToMedia#570]
From @thesatman #545

> It has come to my attention that there are some Plex issues with stacked multi part movies.
> The problem is discussed several times on the Plex forum, and many cases are still waiting for an answer. This is the problem:
> 
>   [movie (year)] folder containing :
>   movie (year)- cd1.avi
>   movie (year)- cd1.en.srt
>   movie (year)- cd2.avi
>   movie (year)- cd2.en.srt
> 
>   Plex webclient plays the 2 media files without any problems. The cd2.en.srt file however is not loaded. It repeats cd1.en.srt. In VLC the correct srt file is loaded when playing cd2.avi. The same issue when playback via Roku Stick.
> 
>   Another issue is when playing via Roku Stick is that the movie is not playing the 2 files without a pause between the 2 files. When file 2 is loaded you get a blue screen and a "Retrieving" bar for several seconds.
> 
>   If I want to avoid the Plex issues with multi part movies (until they have solved the issue, which they haven't since the first time it was reported in 2012), and to make sure that I get no interruptions between file 1 and 2, I need to merge the 2 media files. I see ffmeg has an option "concat".
> 
>   Maybe this could be an option in NzbToMedia ? Activate/Deactivate concat . If activated, run concat, then optioanally load 1 srt file, unless srt files can be merged as well. (or don't search for srt, let Plex do this... I have it activated and see that I have often srt doubles, one from NzbToMedia, and the others from Plex internally... ). What do you think of this?

I think this is worth looking into :dancer:

**Comment by thesatman** [comment]
Hi Clinton. Please allow me to ask a few questions on this subject. I never really managed to use this as intented. Back in November 2014 when you closed this topic, I entered a last question, asking how you finally programmed the entire transcode section. But I never got an answer, and I kind of forgot about it...
 
How is this now intended to work, how do I set up my config file? Not sure if you went for solution 1, 2 or 3...  Let's assume that what I want is following:
 
1) ISO VOB and video_TS needs to be transcoded to one big file in mkv
2) cd1 and cd2 cdxx files need to be glued together to one file.

**Comment by thesatman** [comment]
Not sure if you are reading this closed thread. I have opened new #792.
