### ISSUE TITLE
Add/improve bit-rate handling for transcoding and ripping

### ISSUE THREAD

**Issue by clinton-hall** [clinton-hall/nzbToMedia#606]
From #545 
Question: When converting a DVD to avi or mkv I often end up with a high bitrate media file. The same goes for some downloaded content that appears to be reasonable sized, but often has a high bitrate. ;y CPU can handle 720p transcoding without a problem, but goes into overload when transcoding high bitrate files. I noticed that most files that work well on my server have a bitrate of anywhere between 800 upto 4000-5000 (or somewhere about). But anything higher is likely to make the playback stutter.

I see ffmpeg can deal with scaling down the bitrate. Some good info I found here:
http://superuser.com/questions/582198/how-can-i-get-high-quality-low-size-mp4s-like-the-lol-release-group

In your autoProcessMedia.cfg you have some presets under the [Transcoder] section. What do you suggest if I would like to set a max bitrate for all media files that get transcoded?

Is it only the bitrate I need to look at or is it a combination of the width and height and bitrate? Not sure how to optimize this. As an example I could say that following file plays without any issues on my server:

Video Resolution 720p
Bitrate 4122 kbps
Width 1280
Height 528

But this one does not:

Video Resolution 576p
Bitrate 7587 kbps
Width 720
Height 576

How does this feature interact with your # outputDefault parameter?

**Comment by thesatman** [comment]
Hi Clinton, How did things work out with the bitrate check before converting to mp4-scene? How do I put all this in my config?

**Comment by thesatman** [comment]
Old thread #606 is closed now and I am not sure if you are following this, so I took the liberty to open a new issue #793.

**Comment by mgaulton** [comment]
I'm curious, I'm wanting to mimic the mp4_scene_release settings to sickbard_mp4_automator so I can do a bulk check on my library to get a consistent media for streaming.
Anyone done something like this and suggest changes to the mp4 automator config?
