### ISSUE TITLE
Transcode by quality or showname.

### ISSUE THREAD

**Issue by oppsig** [clinton-hall/nzbToMedia#608]
Would it be possible to add a flag to transcode if the show is in a spesific profile like SD or HD, and skip if not. Or maybe if it is a spesific show? I guess the only option right now is to run two instances of nzbdrone and then two different category's in nzbget/sabnzbd?
I don't' know if there is anyway for you to fetch this kind of info before determining if transcoder should run or not. I guess it would have been easier if it was a profile/quality or show option in nzbdrone/sickrage to use another category.

What do you think?

**Comment by grantsewell** [comment]
Adding to this - would love the capability to selectively transcode based on category.

For instance, if it's a TV Show, I don't really care about adding subtitles, but for a Movie, I'd always like to download subtitles.

Also, some advanced transcode control.

Ignore the file if it meets my presets (i.e. m4v/mp4, 720p, aac/ac3).
If the file extension is correct, but it's 1080p, we still need to transcode down to 720p.

Right now I just about transcode everything; not a huge deal, but not ideal either.

**Comment by thesatman** [comment]
Looks like this could fit right into my issue #606 Add/improve bit-rate handling for transcoding and ripping (old #606 closed now) and #793.

**Comment by clinton-hall** [comment]
yep... Basically I want to change the whole "entry" into transcoder.
Ideally I want to test the categories/tags/extensions/formats/codecs/butrates etc of the video then use these to apply user settings to determine what output settings to apply... then it would go and build the transcoder command the same as it does currently...

As per comments on #793 I haven't had any time to look into this yet :(
