### ISSUE TITLE
Extract file permissions

### ISSUE THREAD

**Issue by thenom** [clinton-hall/nzbToMedia#609]
Hi Clinton,

This issue is almost identical to <a href="https://github.com/clinton-hall/nzbToMedia/issues/508">issue 508</a> but it also applies to extracted files:

```
drwxrwx---+ 3 sasabnzb root         4096 Nov  9 10:02 .
drwxrws---+ 4 root     root         4096 Nov  9 10:53 ..
-rw-rw----+ 1 sasabnzb sasabnzb   152998 Nov  9 10:51 HARVEST CDS ) Flac.nzb
-rw-rw----+ 1 sasabnzb sasabnzb    25504 Nov  9 10:51 HARVEST CDS ) Flac.par2
drwx------+ 2 sasabnzb sasabnzb     4096 Nov  9 10:53 HARVEST CDS ) Flac (Unprocessed)
-rw-rw----+ 1 sasabnzb sasabnzb   409572 Nov  9 10:53 HARVEST CDS ) Flac.vol000+01.par2
-rw-rw----+ 1 sasabnzb sasabnzb   819068 Nov  9 10:53 HARVEST CDS ) Flac.vol001+02.par2
-rw-rw----+ 1 sasabnzb sasabnzb  1612632 Nov  9 10:53 HARVEST CDS ) Flac.vol003+04.par2
-rw-rw----+ 1 sasabnzb sasabnzb  3174332 Nov  9 10:53 HARVEST CDS ) Flac.vol007+08.par2
-rw-rw----+ 1 sasabnzb sasabnzb  6272304 Nov  9 10:53 HARVEST CDS ) Flac.vol015+16.par2
-rw-rw----+ 1 sasabnzb sasabnzb 10881120 Nov  9 10:53 HARVEST CDS ) Flac.vol031+28.par2
-rw-rw----+ 1 sasabnzb sasabnzb 21276384 Nov  9 10:53 HARVEST CDS ) Flac.vol059+55.par2
```

This has only happened recently so not sure if this came out of the previous fix.  as you can see i have set the parents folder sgid and also have acl set but no group permissions on the extraceted directory causes headphones\couchpotato\sickbeard to fail the copy because a mask gets applied.

```
# owner: sasabnzb
# group: sasabnzb
user::rwx
group::rwx          #effective:---
group:downloadsaccess:rwx   #effective:---
mask::---
other::---
default:user::rwx
default:group::rwx
default:group:downloadsaccess:rwx
default:mask::rwx
default:other::---
```

Any help appreciated,

Thanks.

**Comment by chancez** [comment]
I seem to be having this issue currently. I have debug logging enabled, but I don't see any logs about permissions being applied. 

The parent directory and the show's directories permissions, umask, and ACLs are all correctly applied. If I manually create a new file as the sabnzbd user, files are created with the correct permissions, and I'm seeing all files have correct permissions during processing by nzbToMedia. After the extraction, I'm seeing the contents of the archive have 0600 permissions.
