### ISSUE TITLE
[Request] audioLanguage = eng , support for multiple

### ISSUE THREAD

**Issue by Mirabis** [clinton-hall/nzbToMedia#624]
Hello would it be possible to allow more input for audioLanguage?

```
# audioLanguage. set the 3 letter language code you want as your primary audio track.
audioLanguage = eng,nld
# allAudioLanguages. 1 will keep all audio tracks (uses AudioCodec3) where available.
allAudioLanguages = 0
```

Where it would keep english & dutch, for the off chance a show is dutch (nzbdrone)?

Right now u have the option to pick 1 main one and either keep or discard the others.

**Comment by kocane** [comment]
@clinton-hall  is this still not possible?
