### ISSUE TITLE
Login to Sickrage fails due to new sickrage login page

### ISSUE THREAD

**Issue by lbjb** [clinton-hall/nzbToMedia#635]
Sickrage dev branch introduced a new login html page in a recent commit.

This causes nzbToSickrage to error out when attempting to log in:

[10:47:23] [ERROR]::MAIN: A problem was reported in the nzbToSickBeard.py script.
SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!

**Comment by behtjes** [comment]
How to update nzbtomedia on a synology nas? Or how to change it to dev edition? I can't figure it out...

**Comment by clinton-hall** [comment]
yes, same process; WinSCP is good for editing files, but not good for sending commands.
Use putty to connect and send commands.
