### ISSUE TITLE
Question: Is it possible to call my own script and the default couchpotato renamer?

### ISSUE THREAD

**Issue by mapleleafs89** [clinton-hall/nzbToMedia#642]
My media is processed and renamed correctly, but I want to add some additional functionality of my own. I see the userscript section which looks to be what I need, so I thought I could name it movies and it would also get called in addition to my Couchpotato movies section but it doesn't allow it.

Anyway to call my own script in addition to the default couchpotato movies category (cp renamer).

I want it to be executed after the CouchPotato renamer is done processing the files.

**Comment by clinton-hall** [comment]
#664
