### ISSUE TITLE
sonarr CDH, torrents with .rar files

### ISSUE THREAD

**Issue by sea3pea0** [clinton-hall/nzbToMedia#649]
I hadn't been using torrent providers that have .rar archives in them for a while but when I switched them on recently I haven't been able to get sonarr/nzbtomedia to process them. On all other downloads that contain un-archived media files sonarr's CDH handles them. The one thing I need nzbtomedia to do is take over when there is an archived torrent because for now sonarr doesn't handle those. It looks like sonarr isn't processing torrents from the /proccess/.tv folder but rather CDH is just hard linking the episodes right out of transmissions download folder.

Here is nzbtomedia logs with an example of what happens when a torrent with .rar files is processed:
https://gist.github.com/sea3pea0/b91761ffc289b9fa83e1

Here are the sonarr logs from the same time period:

https://gist.github.com/sea3pea0/bf9b4f27f7266f7f2c27

**Comment by clinton-hall** [comment]
any updates to this issue? i.e is it still happening?

**Comment by sea3pea0** [comment]
I basically switched off the providers that have their releases in .rar files. I would still like to try to get it working though.

**Comment by clinton-hall** [comment]
There was a report that sonarr was ignoring the directory that was passed via api... this is being fixed and once fixed TorrentTomedia should extract all files and then send /proccess/.tv to sonarr...

so I expect this should start working very soon...

**Comment by sea3pea0** [comment]
Great, I will try to see if I can get it working.

**Comment by sea3pea0** [comment]
Ok I can confirm nzbToMedia is now working with sonarr when torrents with .rar files are downloaded.
