### ISSUE TITLE
7z and unrar on Mac

### ISSUE THREAD

**Issue by BurningTheSky** [clinton-hall/nzbToMedia#654]
Hey, I have recently migrated this script to my Mac and am getting 2 errors I'm not sure how to resolve, although, I'm sure it is probably simple. I have installed unrar and p7zip through Homebrew but when the script (nzbtoCouchpotato in this instance) runs I get the following error:
[11:18:47] [ERROR]::MAIN: EXTRACTOR: unrar not found, disabling support for .rar
[11:18:47] [ERROR]::MAIN: EXTRACTOR: 7zr not found, disabling support for .7z

But if I run the commands from terminal they are working:
$ unrar
UNRAR 5.20 freeware      Copyright (c) 1993-2014 Alexander Roshal
Usage:     unrar <command> -<switch 1> 

$ 7zr
7-Zip (A) [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=utf8,Utf16=on,HugeFiles=on,4 CPUs)
Usage: 7zr <command> 

I'm assuming I just need to update some configure somewhere but I'm not sure where, any help would be greatly appreciated. Thanks

**Comment by clinton-hall** [comment]
where are your 7zr and unrar binaries? `which unrar` `which 7zr`
This location needs to be added to the PATH that is used by the downloader (NZBGet or SABnzbd)

this can be easily added to the init script for your downloader... i.e. if unrar and 7zr are in /usr/local/bin you would add this to the init script
```
export PATH=$PATH:/usr/local/bin
```

**Comment by BurningTheSky** [comment]
Locations as follows:
$ which 7zr
/usr/local/bin/7zr
$ which unrar
/usr/local/bin/unrar

Which script do I add it to? One of the nzbtomedia files? Will it be overwritten in updates if that's the case?

**Comment by clinton-hall** [comment]
No, you make the changes to your NZBGet or SABnzbd launch scripts (init.d scripts)

How do you stat art your downloader?

**Comment by BurningTheSky** [comment]
I just launch the app, so I'm guessing it might be contained in the package?

**Comment by BurningTheSky** [comment]
It is a bit strange. Sab is running under the same account as the which query. I'm looking in the package contents and I can't find any .sh files, have founds a sabnzbd.py? I'll keep hunting for a .sh file though

**Comment by clinton-hall** [comment]
is there an /etc/init.d/sabnzbd.sh or similar?

**Comment by BurningTheSky** [comment]
I'm even more confused now, I'm looking in the application package and it contains its own copy of unrar, and unzipping seems to be working, so why is it moaning I wonder. Could it be a red herring error message perhaps?

**Comment by clinton-hall** [comment]
if files are extracted, then this warning isn't really relevant as nzbToMedia doesn't need to extract. So you can just ignore the warning/error/
the only other feature that uses 7zr is the ability to transcode .iso images...

Still not sure why it can't find these binaries... bu I don't understand the ways Apps run on OSX.

**Comment by BurningTheSky** [comment]
Ah OK, in that case it can definitely be ignored as I don't need it to do any transcoding.

It is very strange, quirk of a mac I guess
