### ISSUE TITLE
Exit(1) NameError: name ’configobj’ is not defined

### ISSUE THREAD

**Issue by bo0st** [clinton-hall/nzbToMedia#657]
I'm running sabnzbd on freenas 9.3 and I'm getting the following error after the file file downloads
The configobj module is installed. Been trying to figure this out for the past week but still no luck. Any ideas to what might be causing this issue?

This is the python error
           Traceback (most recent call last):
  File "/scripts/autoProcessTV/nzbToCouchPotato.py", line 244, in <module>
    import nzbToMedia
  File "/scripts/autoProcessTV/nzbToMedia.py", line 491, in <module>
    import nzbtomedia
  File "/scripts/autoProcessTV/nzbtomedia/__init__.py", line 34, in <module>
    from nzbtomedia.nzbToMediaConfig import config
  File "/scripts/autoProcessTV/nzbtomedia/nzbToMediaConfig.py", line 10, in <module>
    class Section(configobj.Section):
NameError: name 'configobj' is not defined

This is the sabnzbd error
Exit(1) NameError: name ’configobj’ is not defined (More)

Thanks!

**Comment by clinton-hall** [comment]
How did you install the script? was this a git clone?You need the complete package, as it is hosted on github. The libs directories includes all non-standard modules, including configobj, so this should be importing from the included libs...

So, do you have a libs folder in /scripts/autoProcessTV ?

**Comment by bo0st** [comment]
I've just checked for the libs directory but couldn't find it.

I did run "git clone https://github.com/clinton-hall/nzbToMedia.git" again but it didn't pull down the lib directory.

**Comment by clinton-hall** [comment]
somehings is not right there... when you do a clone, you should get a directory called nzbToMedia and inside that would be the full structure as shown here https://github.com/clinton-hall/nzbToMedia

Try the following
```
cd /scripts
rm -rf autoProcessTV
git clone https://github.com/clinton-hall/nzbToMedia.git autoProcessTV
cd autoProcessTV
ls -l
cp autoProcessMedia.cfg.spec autoProcessMedia.cfg
```
then edit the autoProcessMedia.cfg as needed...

The ls command above should show all contents of the directory and should have included a libs directory.

**Comment by bo0st** [comment]
Thank you Clinton for taking the time to help me out. This process worked like a charm without any errors.

Keep up the epic work!

**Comment by Serg86** [comment]
Hi, I have the same problem, though I can't seem to solve it. I am on RetroPie 4.1 and had to install a bunch of missing python extensions, configobj among them.

nzbToSickBeard: NameError: name 'configobj' is not defined

The module was missing entirely so I tried to install it using pip, which gave me this error, then apt python-configobj, still the same error.

I also tried to export the libs path to LD_LIBRARY_PATH, still nothing.

The nzbToMedia scripts are all functioning because I used this same script folder on the same Pi on LibreElec just yesterday. After failing everything, I updated them, still the same. Then I deleted the script folder entirely and cloned them again, configured autoprocesstv.cfg, no change.

**Comment by clinton-hall** [comment]
can you show the output of trying to run `./nzbToMedia.py` ?

**Comment by Serg86** [comment]
Weird, it says Permission Denied, I tried with user 'pi', with root and under su.

**Comment by clinton-hall** [comment]
yeah permissions, the most fun issue to try and resolve perhaps try 
```
sudo chown -R <user>:<group> /media/usb0/Downloads/scripts
```
where `<user>:<group>` represent the user and group that will be calling the script (the user and group that runs the downloader...)

**Comment by Serg86** [comment]
It was pi:pi just now, I just changed it to root:root and had nzbget rerun the post processing, unfortunately no change.

But shouldn't root be able to execute the scripts even if another user owns the files?

**Comment by clinton-hall** [comment]
So when NZBGet calls the script what error is this? Permission denied, or 'configobj' is not defined?

is is possible that NZBGet has export of PATH in the start script and is therefore calling a different version of Python?

**Comment by Serg86** [comment]
Start command:
'/opt/retropie/configs/ports/kodi/addons/script.module.audo-programs/resources/nzbget/nzbget -D -c /opt/retropie/configs/ports/kodi/userdata/addon_data/script.service.audo/nzbget.conf'

NZBGet says confobj not defined.

Trying to start ./nzbToMedia.py, with the dot slash, says Permission denied, no matter what user, even root.

Ok, I just went over the logs again and noticed an error, it tried to use the scripts which came with audo, I changed the script folder in the settings but it didn't save, apparently.

Now it says Permission denied even in NZBGet.

**Comment by clinton-hall** [comment]
Can you show me the contents of /media/usb0/Downloads/scripts ?
`ls -l /media/usb0/Downloads/scripts`

**Comment by Serg86** [comment]
pi@retropie:/media/usb0/Downloads/scripts $ ls -l
total 236
-rwxr-xr-x  1 root root 17706 Feb  2 03:11 autoProcessMedia.cfg
-rwxr-xr-x  1 root root 17706 Feb  2 03:11 autoProcessMedia.cfg.old
-rwxr-xr-x  1 root root 17534 Feb  2 03:08 autoProcessMedia.cfg.spec
-rwxr-xr-x  1 root root 22600 Jan 17 03:40 changelog.txt
drwxr-xr-x 10 root root  4096 Feb  2 03:08 core
-rwxr-xr-x  1 root root   504 Jan 17 03:40 getffmpeg.sh
drwxr-xr-x 30 root root  4096 Feb  2 03:08 libs
-rwxr-xr-x  1 root root 35127 Jan 17 03:40 license.txt
drwxr-xr-x  2 root root  4096 Feb  2 03:08 logs
-rwxr-xr-x  1 root root  7074 Jan 17 03:40 nzbToCouchPotato.py
-rwxr-xr-x  1 root root  2719 Jan 17 03:40 nzbToGamez.py
-rwxr-xr-x  1 root root  3372 Jan 17 03:40 nzbToHeadPhones.py
-rwxr-xr-x  1 root root  4096 Feb  2 03:08 nzbtomedia.db
-rwxr-xr-x  1 root root 27064 Jan 17 03:40 nzbToMedia.py
-rwxr-xr-x  1 root root  3087 Jan 17 03:40 nzbToMylar.py
-rwxr-xr-x  1 root root  6677 Jan 17 03:40 nzbToNzbDrone.py
-rwxr-xr-x  1 root root  6999 Jan 17 03:40 nzbToSickBeard.py
-rwxr-xr-x  1 root root  5042 Jan 17 03:40 README.md
drwxr-xr-x  2 root root  4096 Feb  1 19:48 tests
-rwxr-xr-x  1 root root 16385 Jan 17 03:40 TorrentToMedia.py

**Comment by clinton-hall** [comment]
interesting, what happens if you run
`/usr/bin/env python2` ?

**Comment by Serg86** [comment]
$ /usr/bin/env python2
Python 2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

Exact same with sudo.

**Comment by clinton-hall** [comment]
so the script runs when calling `python nzbToMedia.py` but not when running `./nzbToMedia.py`??

what about `/media/usb0/Downloads/scripts/nzbToMedia.py`?

**Comment by Serg86** [comment]
Permission Denied.

Sorry I'll need to pick this up tomorrow, it's getting very late/early. Thanks for you help.

**Comment by Serg86** [comment]
Ok I think I found the issue, the ext4 external drive the script folder is on is mounted with the 'noexec' flag, but I haven't specified it in fstab. I'm looking for an answer right now, but that is apparently the issue, I'll report back if I find a solution.
