### ISSUE TITLE
SickRage issue: Returned log from SickBeard was not as expected.!

### ISSUE THREAD

**Issue by rbeall** [clinton-hall/nzbToMedia#658]
Just moved across the country and finally got my server up and running.  Updated SickRage, Plex, nzbtomedia, and sabnzbd is V:0.7.20.  I'm getting the "Returned log from SickBeard was not as expected.!" with a ton of html code which looks like sick rage stuff?  Any help would be greatly appreciated.  Love your work!

It is working with CouchPotato as of my test just now (nzbtoCouchPotato).  I tried it with a different show completely and it looks like it is all shows processed through nzbtosickbeard now that's doing it.  Possibly an update to SickRage that it's not connecting the dots with?

Here is the log file: http://pastebin.com/ziGQqC5Q

**Comment by rbeall** [comment]
SABnzbd is also popping errors for api issues.  

API Key missing, please enter the api key from Config->General into your 3rd party program: ::1>python-requests/2.3.0 CPython/2.7.6 FreeBSD/9.1-RELEASE

Going to check that now.

**Comment by rbeall** [comment]
For some reason my NZB section didn't have the api key in the autoProcessMedia config.  So I added that and the SABnzb errors are gone except I'm still getting the same style html garbage logs from nzbtosickbeard

**Comment by clinton-hall** [comment]
can you enable debug logging?
edit autoProcessMedia.cfg
```
[General]
    log_debug = 1
```
and then show the full log after another postprocess event?

also, please check the option
```
[SickBeard]
    [[tv]]
        web_root
```
if you have anything set for this (you use reverse proxy etc), please make sure there is no trailing `/` at the end... i.e 
`web_root = /sickrage` should be used and NOT `web_root = /sickrage/`

**Comment by rbeall** [comment]
web_root was correct i.e.: web_root = /sickbeard (haven't changed it on my nginx server yet)

I clicked on the post process button in SickRage and it finds the files and processes them just fine so it is something in the connecting the dots between SR and NZBtoMedia.  The log looks mostly the same as before at the bottom:

[23:53:22] [ERROR]::MAIN: A problem was reported in the /usr/local/share/nzbToMedia/nzbToSickBeard.py script.
SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!

Here is the full log out:  http://pastebin.com/JGv28gUA

**Comment by clinton-hall** [comment]
so if you go to http://localhost:8081/sickbeard/home/postprocess in your local browser... what happens? 

if this redirects to home page, that is the problem... 
basically, if you go to home page, then select manual postprocessing, what is the url that is displayed for that page??

**Comment by rbeall** [comment]
I can't get there on my local browser using that link:  I have to use this - http://192.168.X.XXX:8081/home/postprocess/

I tried putting the ip in the place of localhost and it's doing the same thing?

**Comment by clinton-hall** [comment]
it's doing the same thing?
what is that, what does the page look like?

**Comment by rbeall** [comment]
SickRage is working fine if I manually que up the post process from the link I previously posted about.  However when nzbtosickbeard quest it up, SABnzb fails the post process and says: Returned log from SickBeard was not as expected.!  Which is also mirrored in the nzbtomedia log.

My .cfg looks like this:

[[tv]]
        enabled = 1
        host = localhost
        port = 8081
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = /sickbeard
        ssl = 0


This has been working for 6-8 months with no changes to my major setup except for updating SR and NZBtoMedia occasionally.

**Comment by clinton-hall** [comment]
ok, so you don't have a username or password?
try setting 
```
[[tv]]
enabled = 1
host = localhost
port = 8081
username = 
password = 
###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
web_root = /sickbeard
ssl = 0
fork = auto
```

if that doesn't work, try
```
fork = sickrage
```

the issue here is that Sickrage changed the login page and therefore now needs to be authenticated... the non username/password can cause issues with the autofork detection.

**Comment by rbeall** [comment]
Changed both and am getting exact same response.

**Comment by clinton-hall** [comment]
Yeah, try setting user/pass...
I did test without, but SickRage may have changed something again?

**Comment by rbeall** [comment]
damn, now I'm locked out for some reason ha perfect.

**Comment by rbeall** [comment]
Still no luck with adding the password and username.  Trying switching back to a manual ip address.

**Comment by rbeall** [comment]
the link for SR manual post process is:
http://192.168.X.XXX:8081/home/postprocess/

But the link that nzbtosickbeard is calling for is
http://192.168.X.XXX:8081/sickbeard/home/postprocess/processEpisode

**Comment by clinton-hall** [comment]
Ok... `web_root = `

I.e leave this blank if you don't have a web root... That extra `sickbeard` is your web_root value, which clearly isn't needed now.

**Comment by k3ilbasa** [comment]
I am getting this exact error, but I do need a webroot because I am using a reverse proxy.  What can I do?

**Comment by clinton-hall** [comment]
Set the same web_root in SickBeard and the autoProcessMedia.cfg

**Comment by boatguypat** [comment]
just changing fork = sickrage worked for me.

**Comment by K405** [comment]
Just wanted to report that using spaces and or / characters in your password will also cause these exceptions. II use Keepass to generate my passwords and I just mindlessly copy and paste any passwords it generates hence I stumbled upon this problem. It's just generally not a good idea to use / \ and spaces in your passwords.
