### ISSUE TITLE
nzbToCouchpotato call to Couchpotato's media.get results in "Wrong API key used"

### ISSUE THREAD

**Issue by zx3junglist** [clinton-hall/nzbToMedia#660]
Ubuntu 14.04, latest sabnzbd, latest couchpotato, latest nzbtomedia. Using nzbToCouchpotato.py, the API call to couchpotato's media.get results in "Wrong API key" when in fact the API key is correct and functions on other calls such as movie.get. The result is the same when using a browser to get the same call, however the browser complains of a 404. This is for all movies, not just one.

Pastebin of the nzbtomedia log is here: http://pastebin.com/0SSExmRu

Couchpotato debug log shows the following, which seems to correlate to the 404 from the browser:

`01-05 14:57:59 DEBUG 404 GET /api/05604eeb8630484cb99e4f0e90d32408/media.get?id=tt2334873 (127.0.0.1) 101.60ms`

Meanwhile, if I use a browser to make another api call, to movie.get for example, it works fine:

`http://serverhost:5050/api/05604eeb8630484cb99e4f0e90d32408/movie.get/?id=tt1491044`

`{"movie": {"profile": {"core": true, "hide": false, "order": 0, "types": [{"finish": true, "quality_id": 6, "order": 0, "wait_for": null, "quality": {"size_min": 600, "identifier": "dvdrip", "size_max": 2400, "order": 5, "label": "DVD-Rip"}, "id": 6}], "label": "DVD-Rip"}, "library_id": 124, "releases": [{"status": {"identifier": "snatched", "label": "Snatched"}, "files": [], "quality_id": 6, "status_id": 4, "info": {"download_id": "SABnzbd_nzo_bNzQoT", "name": "The.Iceman...`

Since this happens with either a browser or nzbToCouchpotato.py, I opened an issue with couchpotato which was promptly closed, suggesting to open an issue here. Perhaps media.get is deprecated, I could not find it in the couchpotato documentation.

**Comment by clinton-hall** [comment]
can you show the details on your couchpotato, settings, about?

The current CouchPotato has media.get but NOT movie.get... movie.get is the old version, so it would appear your version is not up to date...

**Comment by zx3junglist** [comment]
The version reported by the page is Version


2f5526d57ee3601c3d465a631b16b5e47fd3b88e (1/2/2015, 5:54:36 PM)

----- Reply message -----

**Comment by clinton-hall** [comment]
https://github.com/RuudBurger/CouchPotatoServer/blob/master/couchpotato/core/media/_base/media/main.py#L59

media.get is the correct call for current version. movie.get is obsolete.
I am guessing you have leftover files from older CouchPotato layout...
try stopping couchpotato, deleting all .pyc files, doing a git reset and then git pull...

**Comment by clinton-hall** [comment]
As per https://github.com/RuudBurger/CouchPotatoServer/issues/4464#issuecomment-68834325
it appears your install really is broken (some old code stuck in there).
Also https://github.com/RuudBurger/CouchPotatoServer/issues/4465
