### ISSUE TITLE
nzbToSickBeard.py 

### ISSUE THREAD

**Issue by Rawh** [clinton-hall/nzbToMedia#663]
Greetings,

Keep on getting the issue about nzbToSickbeard.py not being able to connect to the sickbeard url.
I've triple checked the url and the port, which are set ok as I can open a browser and go there.

No idea exactly what goes wrong.

Here's what nzbget is showing me:
http://pastebin.com/EfQR3WrY

It's odd how it's complaining about the following, as remote_path is empty and the setting is set to 0
nzbToSickBeard: [15:54:17] [ERROR]::MAIN: Remote Path {} is not valid for SickBeard:SickBeard Please set this to either 0 to disable or 1 to enable!

Using
- NZBGet 14.1
- Latest pull from this git repo (commit ab24081e30171539d0b65283b62d87d0d6294a12)

**Comment by Rawh** [comment]
Found it.

When using configuring the host address, it might be a good idea give an example, like "127.0.0.1".

I used it with "http://" infront of it and it went totally haywire on that :)

Just putting in an IP address in the host-config and retrying it, everything went a-ok!

**Comment by clinton-hall** [comment]
fair point...

Note that the wiki is open for editing, so please feel free to clear any settings up ;)

https://github.com/clinton-hall/nzbToMedia/wiki/autoProcessMedia.cfg

**Comment by Rawh** [comment]
What about the tooltip inside the addon itself (ie when inside nzbget), can you change that to include an example (thats what I meant).

**Comment by clinton-hall** [comment]
Added into nightly build.
