### ISSUE TITLE
created new category, can't remember how to point to final destination folder, pls help?

### ISSUE THREAD

**Issue by thesatman** [clinton-hall/nzbToMedia#669]
(I am also posting this on the Couchpotato forum)

In Couchpotato http://localhost:5050/settings/searcher/category/ I have created "adults // kids // family".
In SABnzbd http://localhost:8080/sabnzbd/config/categories/ I have created "film".

I can not find the setup in Couchpotato, nor in the nzbtomedia ini file, how the movie needs to "land" into the correct media folder. I forgot how I did it.... black out ... :(

W:/media_server/adults
W:/media_server/kids
W:/media_server/family

Where should I look. I need to add a new category.

According to instructions I got earlier in 2014 (https://couchpota.to/forum/viewtopic.php?f=5&t=2498#p12019) I should find this under "Renamer" in CP. But  I only see the following options ::

Download subtitlesafter rename
Download trailerafter rename

I am running the latest update from 2015-01-14 16:01:25 
hash 4603b0c3b96e81d6d635e3cc3cab2ef9352d17c7

Strange enough, no info is showing when loading "about" (I got the info from "Notify my Android")

**Comment by clinton-hall** [comment]
If your about page isn't displaying correctly, I am guessing something is broken with your install.
The renamer "to" directories for each category will only be displayed after creating the categories (settings, categories) and then refreshing the page...

**Comment by thesatman** [comment]
A shutdown and new start fixed both problems.

**Comment by clinton-hall** [comment]
Glad to hear.
