### ISSUE TITLE
SB couldn't find show ID - Returned log from SickBeard was not as expected.!

### ISSUE THREAD

**Issue by milefork** [clinton-hall/nzbToMedia#671]
Hi,

I've a problem, i think it relies on that i've configured to "Abort jobs that cannot be completed" in sabnzb. When this happens the postProcess for SB will start for sure. But then I find this in the logs: http://pastebin.com/Kg6brg71
And the autoProcessMedia claims `SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!`
Shouldn't autoProcessMedia send smth like `mark release as bad`?

**Comment by clinton-hall** [comment]
Well the script did tell SickBeard to mark as failed, but SickBeard couldn't identify which series/episode it was.
Was this episode originally snatched by SickBeard?

**Comment by milefork** [comment]
Yes it was originaly snatched by SB.

**Comment by clinton-hall** [comment]
ultimately this appears to be an issue with SickRage not determining the series... Possible this is because the failed download had some bad naming....

**Comment by clinton-hall** [comment]
does this happen often? or was this a once off event?

**Comment by milefork** [comment]
No it was reproducable, but it might occur with bad named rlses. I'll have a watch on it.

**Comment by milefork** [comment]
Several more errors like this happend http://pastebin.com/1TAG6zVZ . Should I also post it into the SB Bug Tracker?

**Comment by clinton-hall** [comment]
Try posting on the repository for the fork you are using...
I honestly don't know what else to do here... we pass in all of the relevant information.

What version of SickBeard are you using?

**Comment by milefork** [comment]
https://github.com/midgetspy/Sick-Beard

**Comment by clinton-hall** [comment]
oh... didn't realise the development branch there supported failed... 
Yeah, I would let them known on sickbeard forums... http://sickbeard.com/forums/index.php
Please let me know if they think my script is doing anything wrong ;)

**Comment by milefork** [comment]
Hey I've found the problem exactly. It happens when the Name in Sabnzb start with a {.,-,[,]}
Sometimes the names look like this: [0028].-.REALNAME
Is it possible to add an option to prefilter with a regex or something the waste until the real name starts?
