### ISSUE TITLE
Transcode Scaling Error

### ISSUE THREAD

**Issue by grantsewell** [clinton-hall/nzbToMedia#672]
I've been troubleshooting an issue with the transcoder, specifically scaling 1080 videos down to 720. The current math in transcoder.py is using int, so scaling a standard 1920x1080 to 1280x720 is yielding a scale value of 1 instead of 1.5. This cause the video to remain at the original resolution.

Unless I'm missing something greater, I think making changes to lines 218 & 219 from int to float will solve this.

So changing the operator from this:

218            w_scale = width/int(scale.split(':')[0])
219            h_scale = height/int(scale.split(':')[1])

To this:

218            w_scale = width/float(scale.split(':')[0])
219            h_scale = height/float(scale.split(':')[1])

Solved the problem for me. Thoughts?

**Comment by grantsewell** [comment]
There may be something more to this. I just finished transcoding a file and it successfully. Here's the generated code:

`nice -n0 ionice -c2 -n4 /home/supervisor/bin/ffmpeg -loglevel warning -hwaccel auto -i /home/downloads/complete/MyMediaFolder/MyMediaFile.mkv -i /home/downloads/complete/MyMediaFolder/MyMediaFile.srt -map 0:0 -map 0:1 -map 0:1 -c:v libx264 -vf scale=trunc(iw/2)*2:720 -crf 19 -level 3.1 -c:a:0 aac -strict -2 -ac:a:0 2 -c:a:1 ac3 -sn /home/downloads/complete/MyMediaFolder/MyMediaFile.m4v`

But it was generated with a resolution of **1920**x720. Here are my autoProcessMedia.cfg settings:

```
    outputVideoExtension = .m4v
    outputVideoCodec = libx264
    VideoCodecAllow = "libx264,h264,h.264,AVC,avc,mpeg4,msmpeg4,MPEG-4"
    outputVideoPreset = ""
    outputVideoResolution = 1280:720
    outputVideoFramerate = ""
    outputVideoBitrate = ""
    outputVideoCRF = 19
    outputVideoLevel = 3.1
    outputAudioCodec = aac
    AudioCodecAllow = "libfaac,aac,ac3,mp3,libfdk_aac"
    outputAudioChannels = 2
    outputAudioBitrate = ""
    outputAudioTrack2Codec = ac3
    AudioCodec2Allow = ""
    outputAudioTrack2Channels = 6
    outputAudioTrack2Bitrate = ""
    outputAudioOtherCodec = ""
    AudioOtherCodecAllow = ""
    outputAudioOtherChannels = ""
    outputAudioOtherBitrate = ""
    outputSubtitleCodec = mov_text
```

**Comment by clinton-hall** [comment]
this should address both issues... please test on latest nightly

**Comment by grantsewell** [comment]
That fixed it. Thanks, great work!
