### ISSUE TITLE
QQ: transcoding uncategorized 

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#682]
Out of curiosity, is there a way to just run the transcoder on any relevant uncategorized download instead of having to call a userscript ? Or what would you recommend? I have a couple of categories that would apply.

**Comment by clinton-hall** [comment]
I am looking at a re-structure of the Transcoder, so this should be possible.

**Comment by mgaulton** [comment]
Roger. Thanks.
