### ISSUE TITLE
Sonarr doesn't import from nzbToMedia

### ISSUE THREAD

**Issue by Taloth** [clinton-hall/nzbToMedia#684]
Due to a regression in Sonarr after a refactoring. Sonarr ignores the path in the message from nzbToMedia. This means if CDH is disabled Sonarr won't import at all, with CDH enabled it will import but won't handle alternate directories.

A fix for this is currently being reviewed by the other Sonarr developers and I'll try to get it merged to master within a day or two (hopefully sooner).

I'm sorry for the inconvenience.

**Comment by clinton-hall** [comment]
Thanks for letting me know...
I saw a post regarding this but thought it was an anomaly.

**Comment by Taloth** [comment]
Forgot to post earlier this week, but we merged develop to master a couple of days ago, so it should be fixed for all users.

**Comment by clinton-hall** [comment]
Thanks for the confirmation. I had a look yesterday when i was doing some cleanup and thought it looked to have been merged.
