### ISSUE TITLE
Postprocessing unable to work with Sickrage

### ISSUE THREAD

**Issue by Youmi15** [clinton-hall/nzbToMedia#686]
I keep getting the following error when I try to run nzbtosickbeard. Any idea on how to solve this?

I updated to the latest branch this morning, so maybe it is just a wrong setting.

Hopefully you can help me with this!

Btw, how do I make the code appear in a block?

Fri Jan 23 07:21:57 2015	INFO	Executing post-process-script nzbToSickBeard.py for The.Affair.S01E01.720p.HDTV.x264-BATV
Fri Jan 23 07:22:05 2015	INFO	nzbToSickBeard: [15:22:05] [INFO]::MAIN: Checking database structure...
Fri Jan 23 07:22:05 2015	INFO	nzbToSickBeard: [15:22:05] [INFO]::MAIN: Checking if source needs an update
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard: [15:22:06] [ERROR]::MAIN: Unknown current version number, don't know if we should update or not
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard: [15:22:06] [INFO]::MAIN: nzbToMedia Version:10.9 Branch:master (Linux 2.6.29.6-33-sigma)
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard: [15:22:06] [WARNING]::MAIN: Failed to locate 7zip. Transcosing of disk images and extraction of .7z files will not be possible!
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard: [15:22:06] [INFO]::MAIN: #########################################################
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard: [15:22:06] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard: [15:22:06] [INFO]::MAIN: #########################################################
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard: [15:22:06] [INFO]::MAIN: Script triggered from NZBGet Version 12.0-testing-r883.
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard: [15:22:06] [WARNING]::MAIN: Par-repair failed, setting status "failed"
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard: [15:22:06] [INFO]::MAIN: Auto-detected SECTION:SickBeard
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard: [15:22:06] [INFO]::MAIN: Calling SickBeard:Series to post-process:The.Affair.S01E01.720p.HDTV.x264-BATV
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard: Traceback (most recent call last):
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:   File "/share/Apps/NZBget/ppscripts/nzbToSickBeard.py", line 257, in <module>
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:     result = nzbToMedia.main(sys.argv, section)
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:   File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/NZBget/ppscripts/nzbToMedia.py", line 696, in main
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:     failureLink=failureLink)
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:   File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/NZBget/ppscripts/nzbToMedia.py", line 598, in process
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:     download_id, inputCategory, failureLink)
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:   File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/NZBget/ppscripts/nzbtomedia/autoProcess/autoProcessTV.py", line 66, in processEpisode
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:     if not server_responding("%s%s:%s%s" % (protocol,host,port,web_root)):
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:   File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/NZBget/ppscripts/nzbtomedia/nzbToMediaUtil.py", line 1048, in server_responding
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:     requests.get(baseURL, timeout=60, verify=False)
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:   File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/NZBget/ppscripts/libs/requests/api.py", line 55, in get
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:     return request('get', url, **kwargs)
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:   File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/NZBget/ppscripts/libs/requests/api.py", line 44, in request
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:     return session.request(method=method, url=url, **kwargs)
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:   File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/NZBget/ppscripts/libs/requests/sessions.py", line 452, in request
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:     resp = self.send(prep, **send_kwargs)
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:   File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/NZBget/ppscripts/libs/requests/sessions.py", line 581, in send
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:     history = [resp for resp in gen] if allow_redirects else []
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:   File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/NZBget/ppscripts/libs/requests/sessions.py", line 162, in resolve_redirects
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:     proxies = self.rebuild_proxies(prepared_request, proxies)
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:   File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/NZBget/ppscripts/libs/requests/sessions.py", line 236, in rebuild_proxies
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard:     username, password = get_auth_from_url(new_proxies[scheme])
Fri Jan 23 07:22:06 2015	INFO	nzbToSickBeard: UnboundLocalError: local variable 'scheme' referenced before assignment
Fri Jan 23 07:22:07 2015	INFO	nzbToSickBeard: Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <nzbtomedia.nzbToMediaUtil.PosixProcess instance at 0x2bdf1080>> ignored
Fri Jan 23 07:22:07 2015	ERROR	Post-process-script nzbToSickBeard.py for The.Affair.S01E01.720p.HDTV.x264-BATV failed (terminated with unknown status)
Fri Jan 23 07:22:07 2015	INFO	Unpausing queue after post-process-script
Fri Jan 23 07:22:07 2015	INFO	Collection The.Affair.S01E01.720p.HDTV.x264-BATV added to history'

**Comment by clinton-hall** [comment]
To put code in a block, you add three "ticks" before and after. This is the character that is on the same key as ~ (top left) on a standard qwerty keyboard.

Can you confirm the url that you usually connect to SickBeard? Can you confirm the host, port, ssl settings in autoProcessMedia.cfg?
What version of SickBeard do you use?

**Comment by Youmi15** [comment]
I connect to localhost:8081 without SSL, this is correct in the nzbToSickBeard settings.
Working with the latest SR version as well, since I updated it together this morning ( COMMIT: (9466bddc3ee2679fe476b02d94b6227381536637) ).

```Thanks for the hint :) ```

**Comment by Youmi15** [comment]
Oh, I just fixed it.
Changed localhost to the actual IP and that solved it.
Thanks for the help though!
