### ISSUE TITLE
why beets in libs?

### ISSUE THREAD

**Issue by kooimens** [clinton-hall/nzbToMedia#688]
For what reason are you delivering a beets lib in the master branche. Is it used when post-processing to headphones or is it just for testing? I assume that it is not been used, because the headphones script will trigger headphones and that will use it's own beets?

I'm asking this because I want to force headphones make use of my already and more up-to-date beets setup.

**Comment by clinton-hall** [comment]
This is only used on a manual run of TorrentToMedia to determine if a download is an album and then link the files to the album/artist folder structure to more easily process.

**Comment by kooimens** [comment]
Thanks for elaborating! Can be closed
