### ISSUE TITLE
FR: stale pid handling

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#693]
I couldn't figure out why nTM wasn't doing anything in either instance i have running and it appears for some reason there were stale pids. Perhaps a startup check on the age of the pid would be needed. for example, if its older than x minutes, nuke it on start.

**Comment by clinton-hall** [comment]
For Linux this should be handled better in nightly branch...

**Comment by mgaulton** [comment]
Switching to nightly, will let you know if i notice anything
