### ISSUE TITLE
Extraction fails

### ISSUE THREAD

**Issue by nikagl** [clinton-hall/nzbToMedia#694]
Hi all,

I have a weird issue. Suddenly extraction started to fail and therefore the rest of the script also fails (notifying sickbeard, etc.). I get the following errors:
```
2015-01-22 03:37:12 INFO    ::MAIN: Extracting X:\.....rar to X:\....
2015-01-22 03:37:12 DEBUG   ::MAIN: Extracting ['X:\\....\\nzbToMedia\\nzbtomedia\\extractor\\bin\\invisible.cmd', 'X:\\....\\nzbToMedia\\nzbtomedia\\extractor\\bin\\x86\\7z.exe', 'x', '-y'] X:\.....rar X:\....
2015-01-22 03:37:12 ERROR   ::MAIN: EXTRACTOR: Extraction failed for X:\.....rar. Could not call command ['X:\\....\\nzbToMedia\\nzbtomedia\\extractor\\bin\\invisible.cmd', 'X:\\....\\nzbToMedia\\nzbtomedia\\extractor\\bin\\x86\\7z.exe', 'x', '-y', 'X:\\.....rar']
```

I debugged it be removing part of the code till it succeeds (ie. I have no idea what I am doing and why it is now successfull). I have replaced the following lines:
```
            info = subprocess.STARTUPINFO()
            info.dwFlags |= subprocess.STARTF_USESHOWWINDOW
```

With
```
            nzbtomedia.logger.info("EXTRACTOR: Skipped Windows settings")
```

And now it works. Any idea why the subprocess items cause the extractor to fail?

Regards,

Nika.

**Comment by nikagl** [comment]
Looks like it's caused by that last commit:
https://github.com/clinton-hall/nzbToMedia/commit/9a715773befe312bc0db5022afeb1b6f19ecdfd2#diff-bdd2db419a5d0671b92bb6f9808d5f39

**Comment by clinton-hall** [comment]
Can you open a python terminal and issue
```
import subprocess
info = subprocess.STARTUPINFO()
info.dwFlags |= subprocess.STARTF_USESHOWWINDOW
```
and post the output?

**Comment by nikagl** [comment]
It doesn't return anything:
```
C:\Python27>python.exe
Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> info = subprocess.STARTUPINFO()
>>> info.dwFlags |= subprocess.STARTF_USESHOWWINDOW
>>> ^Z
```

**Comment by nikagl** [comment]
Not sure whether it's usefull:
```
>>> print info
<subprocess.STARTUPINFO instance at 0x00A9AF80>
>>> print info.dwFlags
1
```

**Comment by clinton-hall** [comment]
What Version of Windows are you using?

Can you try a test with line 17 of extractor.py changed from
```
        cmd_7zip = [invislocation, nzbtomedia.SEVENZIP, "x", "-y"]
```
to
```
        cmd_7zip = [nzbtomedia.SEVENZIP, "x", "-y"]
```

**Comment by clinton-hall** [comment]
@Jaerin 
with the info.dwFlags set, do we still need `invisible.cmd` and `invisible.vbs`?

Do you know of any limitations pertaining to this method? I have read the docs and it looks like it should all be simple enough.

**Comment by nikagl** [comment]
I use Windows 2003... the cmd and vbs originally came from me to make the 7zip process invisible and keep waiting till the process exists. I think you previously used chp.exe or something like that, but that had an issue where it exited before the process was finished... not sure why you guys changed to using subprocess? Possibly it's a win2003/xp thing where that does not work well?

**Comment by Jaerin** [comment]
I don't believe they are necessary anymore.  I think you can call extractor.py directly and it will all be invisible.  All the mklink and extract commands run invisible regardless.

With that said it might be worth to use invisible.vbs as a wrapper around torrenttomedia.py as a means to allow utorrent to call it invisibly.  At least on my system I can't call torrenttomedia.py directly without a window popping up.  Unless I call a vbs that calls the python.

**Comment by nikagl** [comment]
It still fails when removing the invislocation. @Jaerin, any thoughts on why the subprocess commands fail on Windows 2003/XP (32-bit)?

**Comment by clinton-hall** [comment]
Yeah... this is where I wasn't sure how it all came together.
I defer to you both with regards to Windows :)

I like the idea of wrapping TorrentTomedia.py in invisible.vbs... Why would this be for TorrentToMedia.py and not for nzbToMedia.py? or does this come from the way the scripts are launched from different clients?

I did some searching and it appears the showwindow flags were implemented in Windows 2000 and above... so it shouldn't be an issue... https://msdn.microsoft.com/en-us/library/windows/desktop/ms633548(v=vs.85).aspx

**Comment by clinton-hall** [comment]
actually... looks like Winxp and above...
https://msdn.microsoft.com/en-us/library/windows/desktop/ms686331(v=vs.85).aspx

But in any case, no reason why yours isn't working...

**Comment by nikagl** [comment]
I wish I knew what the whole subprocess thing does :-P. invisible.cmd/vbs worked fine for me :)

**Comment by clinton-hall** [comment]
Can you confirm if you are on dev, nightly, or master?

master and dev do not have the `import subprocess` and therefore will fail...
this was fixed in nightly... I need to merge this up...

**Comment by nikagl** [comment]
Ahaaaaaa.... I'm running from master:

**Comment by Jaerin** [comment]
Am I supposed to be calling nzbtomedia.py instead?  I only do torrents so I have been calling torrenttomedia.py directly from my vbs script.  Seems like configuration on this is mostly what you figure out works instead of having a specific set of steps.

**Comment by clinton-hall** [comment]
damn... Sorry I didn't pick this one earlier...
I just went back to your log and checked the error message and noticed this was the message from the `except` and not the generic 7zip failure...
So as I was putting to get a quick test code to run to get the trace-back I noticed I had the missing import!

I'll try and merge up shortly... but if you could test nightly that would help.

**Comment by clinton-hall** [comment]
@Jaerin 
No need to call nzbTomedia unless you are using SABnzbd or NZBGet. If using a torrent Client you are calling TorrentToMedia...
My question was really to see if you were using nzbToMedia (nzb downloads) and if TorrentToMedia behaved differently... So if I try and write a wrapper around these to make them hidden on windows, I actually want to do it for all scripts.

Yes, To be honest, I don't know how to make a set of steps, as every setup is slightly different and people use different combinations etc... I have tried to document the very basic setup in my wiki, but this is by no means perfect... https://github.com/clinton-hall/nzbToMedia/wiki

**Comment by clinton-hall** [comment]
merged nightly up to master... should fix this.

**Comment by nikagl** [comment]
Thanks! It works now :)
