### ISSUE TITLE
Global invisible.vbs to hide all scripts called from windows

### ISSUE THREAD

**Issue by clinton-hall** [clinton-hall/nzbToMedia#695]
As per comments in #694 

When called on windows, the main script causes a windows to pop-up briefly. A global wrapper can be called to pass all args to TorrentToMedia or nzbToMedia...

**Comment by Hellowlol** [comment]
Or the user can set .py files to be opened with pythonw.exe by default

**Comment by clinton-hall** [comment]
Oh, that easy?
And everything else runs fine when called from Pythonw?

**Comment by Hellowlol** [comment]
Should be, I have been running cp, sb/se that way for years :)
