### ISSUE TITLE
Deluge and Sabnzbd with Couchpotato directory structure.

### ISSUE THREAD

**Issue by GR360RY** [clinton-hall/nzbToMedia#697]
From the wiki articles it is unclear how to setup Deluge, Sabnzbd and Couchpotato directory structure.
There are contradictory articles on the subject:
- [linux ](https://github.com/clinton-hall/nzbToMedia/wiki/linux) wiki page:

```
/media
    /download
        /incomplete
            /nzbget
        /complete
            /deluge
                /movies
                /tv
            /sabnzbd
                /movies
                /tv
        /process            # autoProcessMedia [Torrent] outputDirectory
            /movies         #(couchpotato, settings, renamer, from)
            /tv             #(sickbeard, config, postProcessing, config/postProcessing)
    /movies                 #(couchpotato, settings, renamer, To. Also your media player "movies" media folder )
    /tv                     #(sickbeard, tv series destination. Also your media player "tv" media folder)
```

In this example  Couchpotato **Rename From** should be set to `/media/download/process/movies`. This is o.k in case we use only Deluge Torrent Client ( process/movies is set to outputDirectory ), but it is unclear how Sabnzbd **movie** category files will end up in `process/movies` directory as categorised downloads are stored in `/media/download/complete/sabnzbd/`.
- [couchpotato](https://github.com/clinton-hall/nzbToMedia/wiki/couchpotato) wiki page:

The below example sets **Renamer From** to `sabnzbd/movies` which will probably work only with usenet clients.

> From = Must be set to the full path to your completed download movies (including any additional category paths)
> e.g. /media/download/sabnzbd/movies

In the same Couchpotato page the Deluge Part defined as following:

> Directory = The directory for completed/seeding files. NOT the renamer "from" directory. `/media/download/deluge/movies`

It us unclear if **Renamer From** will work with torrents when both download clients are used.
Secondly, if `movie` labels are defined in Torrent client, Movies will end up this directory in any case...

I am trying to automate the nzbtomedia configuration together with deluge, sabnzbd, couchpotato and sickbeard and this part simply escapes me :)

**Comment by clinton-hall** [comment]
The good thing about this script is it will actually pass the directory containing the downlaods to Couchpotato... it actually ignores the renamer "from" directory. So using usenet and torrents is fine if both download clients are calling nzbToMedia and TorrentToMedia.

**Comment by GR360RY** [comment]
@clinton-hall , so to get things clear:

> __Rename From:__ in Couchpotato can be skipped for Deluge and Sabnzbd.

Do you want to send a pull request with Wiki Update ?

**Comment by clinton-hall** [comment]
It can't be skipped as it has to be set. This folder will be scanned every x hours (as set in CouchPotato, settings, renamer, force_every). But these scripts actually tell CouchPotato what directory to scan.

The wiki doesn't use pull requests... You can just edit the wiki to try and make this clearer... I certainly appreciate anything yo can do to clear this up. The script itself has changed over time, so conflicting settings may be present.

**Comment by GR360RY** [comment]
Thanks for a quick response. I will play with the setup and try to simplify the documentation.

**Comment by GR360RY** [comment]
The following directory structure works ideal for me with couchpotato, sickbeard, sabnzbd and deluge:

    ├── downloads           # all (categorised and uncategorised ) content is being downloaded here
    │   └── incomplete      
    │       ├── deluged     # deluge incomplete
    │       ├── process     # autoProcessMedia [Torrent] outputDirectory
    │       │   ├── movie   # (couchpotato, settings, renamer, from)
    │       │   └── tv      # (sickbeard, config, postProcessing, config/postProcessing)
    │       └── sabnzbd     # sabnzbd incomplete
    ├── movies              # (couchpotato, settings, renamer, To. Also your media player "movies" media folder )
    └── tv                  # (sickbeard, tv series destination. Also your media player "tv" media folder)

All content is being downloaded into one place unrelated to `deluge label`/`sabnzbd category`.
For my taste it a little bit cleaner the the one that we have in linux wiki page. 

@clinton-hall , do you want me to extend the linux wiki page with this setup in addition to one that is already presented ?

**Comment by clinton-hall** [comment]
yes. please add this to the wiki.
I agree this is a clean structure fo anyone who can customize the download location.

**Comment by clinton-hall** [comment]
just for my clarification here, where do deluge download complete (seeding) files go and where do sabnzbd download complete files go?

**Comment by GR360RY** [comment]
All goes to single top downloads folder. In both deluge and sabnzbd labels/categories are enabled but files are not saved into dedicated folders. 

* In deluge: completed downloads go from `downloads->incomplete->deluged` to `downloads` and are being seeded from this directory. Processed files go to `downloads->incomplete->process` and then are being moved to the relevant `tv`/`movies` folders

* In sabnzbd: completed downloads go from `downloads->incomplete->sabnzbd` to `downloads`. Sabnzbd runs postprocessing script following the download:

![screen shot 2015-02-07 at 4 10 07 am](https://cloud.githubusercontent.com/assets/828309/6090407/8d60c47e-ae80-11e4-9913-0b372aa2eadb.png)

If it is clear enough and you don't see any problem with this setup,  say "go" and I will update the wiki ;)

**Comment by GR360RY** [comment]
The nice part is if you share your media drive over nfs/cifs/afp all the content is placed under single path and can be easily accessed. No need to go to completed folders independent on which download client was used. When torrent is removed from deluge with data, the item is being removed from downloads folder as well. Since we already have another copy/hardlink in movies/tv folders it looks like pretty save bet to me.
