### ISSUE TITLE
transcoder.py "scales up" lower quality videos

### ISSUE THREAD

**Issue by grantsewell** [clinton-hall/nzbToMedia#699]
I recently was converting some 480p DVD-quality videos. The resolution was 624x352, approximately 700MB. I noticed after the conversion that these files were actually growing in size to 1.1-1.3 GB. My scale is currently set to transcoder to 1280:720.

It seems that the way the scaling determination is written in the transcoder.py script, it will actually scale up lower resolutions to meet the 1280x720 resolution. Since we're not increasing the quality of the source, and really just taking up storage space.

To combat this, I think we could modify transcoder.py on lines 222 and 226 to only permit scaling down. This how many transcoders function natively. Thoughts?

On line 222 from:
```
if w_scale != 1: 
```
To:
```
if w_scale > 1:
```

And on line 226 from:
```
if h_scale != 1:
```
To:
```
if h_scale > 1:
```

**Comment by clinton-hall** [comment]
good catch.I'll try and fix soon...
oryou could just send a pull request to nightly branch.

**Comment by grantsewell** [comment]
Will do. I've confirmed the fix works.
