### ISSUE TITLE
files that already exists delete new downloads

### ISSUE THREAD

**Issue by rbeall** [clinton-hall/nzbToMedia#701]
It seems like everything is working fine for files that I already don't have a copy of.  But when I manually cue something up or something gets cued up via transmission for a file that I already have (i.e. lesser quality file) it goes through the processing and just deletes the new file instead of deleting the old file and moving the new one in it's place.

**Comment by clinton-hall** [comment]
can you show logs for such an event?
Is this for SickBeard, CouchPotato or all downloads?

**Comment by rbeall** [comment]
Well I just refreshed my log to do just that and it worked on the movie I just checked it with using CP.  I'll try the one that failed here quick and give you the full log.

**Comment by rbeall** [comment]
yeah same file failed again.  Both files I tested were already in my library.  My process was this:  I manually added files to transmission to be processed automatically.  Looks like it cues CP etc.  You should be able to pick up what I'm putting down I think.  Basically it looks like it's working.  But I'm not getting the email from CP and it isn't actually updating the old file with the new one and then it deletes my file I just acquired.

Log here:
http://pastebin.com/7PZDfh6E

**Comment by clinton-hall** [comment]
Can you show the logs from CouchPotato from the same time (18:19)?

**Comment by rbeall** [comment]
02-06 18:19:11INFO[tato.core.plugins.renamer] Scanning media folder /media/Server/Downloads/Transmission/Complete/movie/Dumb and Dumber To (2014) [1080p]...
02-06 18:19:11ERROR[tato.core.plugins.renamer] Download ID 604e8eabe10b23bbd6a5f74463d1a026e3a05904 from downloader transmission not found in releases
02-06 18:19:11ERROR[tato.core.plugins.renamer] Missing `cd` or `cd_nr` in the renamer. This will cause multi-file releases of being renamed to the same file. Please add it in the renamer settings. Force adding it for now.

**Comment by rbeall** [comment]
here is the previous one:

http://pastebin.com/1fYkZPP1

**Comment by clinton-hall** [comment]
So why does the MP4 already exist in the destination? As far as CouchPotato showed, there was only an avi....
This doesn't look to be related to the script, rather to the manage folder in CouchPotato getting out of sync.

**Comment by rbeall** [comment]
yeah, you are probably right.  Is CP doing the deleting or is your script?  If it all on CP then no worries, if your script deletes the files, then it would be nice to not have them deleted if CP fails for some reason or "thinks" that it's done something correctly.  I know that's a little chicken or the egg and only as good as the information coming in but just a thought.
