### ISSUE TITLE
Duplicate Subtitle Languages

### ISSUE THREAD

**Issue by grantsewell** [clinton-hall/nzbToMedia#704]
Still digging into the code, but I wanted to open an issue to see if anyone else has seen it. Recently, I've noticed several of my movie files with two copies of the same subtitle language. In my case, I have nzbToMedia set to only permit english, and set to download subtitles and embed.

My theory is that the files I'm processing already have an english subtitle, and nzbToMedia is downloading an additional english subtitle, and then embedding it as well.

I'm investigating around Line 454 of transcoder.py right now.

**Comment by clinton-hall** [comment]
this certainly could be possible.

I don't do any "independet" checks for subs when embedding subs... The theory was that subs should only be downloaded when the video file does not already include subs of that language (This should be handled by subliminal).

What I should probably do here is have a list/dict that has all of the wanted languages, and if the wanted language is found (and mapped) in the streams then this langue is removed (or set to status "used" etc) and then this is skipped for the embed section...

Currently embed option basically means any external file is written into the media file.
