### ISSUE TITLE
sonarr torrents - folder structure

### ISSUE THREAD

**Issue by 11182711114** [clinton-hall/nzbToMedia#706]
Sonarr torrents uses ".${assigned}" structure, so they force a "." before the assigned directory name e.g. ".tv" instead of what should be "tv", this causes TorrentToMedia to not recognize category for the file and end.

**Comment by clinton-hall** [comment]
So in autoProcessMedia.cfg can you edit 

    [NZBDrone]
        [[tv]]

To be

    [NZBDrone]
        [[.tv]]

**Comment by 11182711114** [comment]
Indeed, I simply wanted to make you aware to that fact so that the default value(or perhaps simply add in a comment to explain this inside autoProcessMedia.cfg to avoid more people trying to fix it for 2 hours before realizing that sonarr doesn't just use the catergory assigned) :)

**Comment by clinton-hall** [comment]
Are you able to add these details to the wiki? Perhaps even edit the NZBDrone page to now reflect "Sonarr"?

**Comment by nikotime** [comment]
Sorry to pop in on this thread, but I'm looking to setup Sonarr with nzbtoMedia and deluge (windows) and, with their not being a wiki, was wondering are there any potential hiccups/steps that I should take or is it pretty intuitive based on being able to setup couchpotato and sickbeard correctly in the past?

**Comment by clinton-hall** [comment]
There is  a wiki.... https://github.com/clinton-hall/nzbToMedia/wiki

Feel free to edit change as you think appropriate. 

Ask specific questions here and I'll try and help the st I can.

**Comment by nikotime** [comment]
Cheers Clinton - find the wiki invaluable but was just wondering about
sonarr in particular! Will start a thread if I experience any problems
(currently fighting with deluge not executing torrenttomedia...life was so
much easier in Linux)

**Comment by clinton-hall** [comment]
See #734 for issues with executing TorrentToMedia.py from deluge in windows.

Also, make sure you use deluged.exe not deluge.exe

**Comment by nikotime** [comment]
You're a star - will have some time on Sunday which I can devote to it.
