### ISSUE TITLE
SABNZBD Issue - Exit(-1) Cannot run script 

### ISSUE THREAD

**Issue by computerconsulting** [clinton-hall/nzbToMedia#707]
Hi Clinton,

Like the work you do on the various packages. 

I was wondering if you could help in determining why the CharTranslator.py script (which is in the SABNZBD package) executes with an Exit(-1) error within SABNZBD on a QNAP TS-670. Note that All other scripts (sabTo SickBeard.py) work perfectly.
## Problem

A new installation was required of Sickbeard, SABNZBD etc after it was found that QNAP had an issue with Twonky installation process that impacted firmware upgrade 

After re-installing Python 2.7, SAB and Sickbeard and completing configs the following occurs only for the CharTranslator.py script

"Exit (-1) Cannot run script /share/Download/nzbToMedia/CharTranslator.py"
## Attempted Solutions & Verification's:

1)  Checked that the sab scripts folder is correct -  Post-Processing Scripts Folder: /share/Download/nzbToMedia (Both CharTranslator.py, sabToSickBeard.py)
2)  Made sure that a copy of CharTranslator.py was moved from the Qpackage install to /share/Download/nzbToMedia and that the linked file of CharTranslator.py was removed
3)  Set chmod 777 on /share/Download/nzbToMedia/ CharTranslator.py
4)  Executed /share/Download/nzbToMedia/ CharTranslator.py on the command line against a download NZB… RESULT Works:

Command: python /share/Download/nzbToMedia/CharTranslator.py /share/Entertainment/Downloads/Complete/aaaa.S02E03.HDTV.x264-RiVER

Current folder is /share/CACHEDEV2_DATA/Entertainment/Downloads/Complete/aaaa.S02E03.HDTV.x264-RiVER
Renaming destination folder to UTF-8 format...
/share/CACHEDEV2_DATA/Entertainment/Downloads/Complete/aaaa.S02E03.HDTV.x264-RiVER -> No special characters detected: Nothing to be done
Destination folder renamed !

Renaming folders to UTF-8 format...
Folder renaming Done !

Renaming files to UTF-8 format...
./aaaa.s02e03.hdtv.x264-river.sfv -> No special characters detected: Nothing to be done
./aaaa.s02e03.hdtv.x264-river.srr -> No special characters detected: Nothing to be done
./Aaaa.S02E03.HDTV.x264-RiVER.nzb -> No special characters detected: Nothing to be done
./aaaa.s02e03.hdtv.x264-river.nfo -> No special characters detected: Nothing to be done
./aaaa.s02e03.hdtv.x264-river.mp4 -> No special characters detected: Nothing to be done
Files renaming Done !

Character encoding translation done!

**Comment by clinton-hall** [comment]
Can you confirm the output of "which python"?

I am wondering if SABnzbd calls a different Python to your manual run?

**Comment by computerconsulting** [comment]
QNAP Python 2.7 from APP centre as per the directions on the web page to download.
http://forum.qnap.com/viewtopic.php?f=133&t=86644

Command line verification:
---------------------------------
[/] # python
Python 2.7 (r27:82500, Aug 21 2010, 07:52:47)
[GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

Other Verifications
------------------------
ps -ef on python

 1236 admin     63768 S   /usr/bin/python2.7 SABnzbd.py -f /share/CACHEDEV1_DATA/.qpkg/SABnzbdplus/Config/sabnzbd.ini --daemon --pid /tmp
15716 admin     30352 S   python /KVM/opt/htdocs/webvirtmgr/lib/TaskDaemon.py
15983 admin     28624 S   python /KVM/opt/htdocs/webvirtmgr/noVNC/utils/websockify.py --cert=/KVM/opt/conf/server.crt --target-config=/share/CACHEDEV1_DATA/.qpkg/.QKVM/tmp/sunsto
26832 admin       548 S   grep python
26952 admin     40248 S   /usr/bin/python2.7 /share/CACHEDEV1_DATA/.qpkg/SickBeard/SickBeard/SickBeard.py --daemon --datadir /share/CACHEDEV1_DATA/.qpkg/SickBeard/config --pidfil

The original python was removed due to firmware problem. Thats' not to say something was left over. Here is a "find" and ls -l list. They all seem to point to python2.7

[/] # find -name python
./usr/local/bin/python
./usr/bin/python
./mnt/ext/opt/Python/bin/python
./share/CE_CACHEDEV3_DATA/my name/NetBakData/my name@pc/VistaProfileData/AppData/Roaming/CouchPotato/cache/python
./share/CACHEDEV1_DATA/.qpkg/Python/bin/python
./share/CACHEDEV1_DATA/.qpkg/SABnzbdplus/Repository/lib/python
./share/CACHEDEV1_DATA/.qpkg/SABnzbdplus/x31/python
./share/CACHEDEV1_DATA/.qpkg/SABnzbdplus/x86/bin-utils/python
./share/CACHEDEV1_DATA/.qpkg/SABnzbdplus/x86/python
./share/CACHEDEV1_DATA/.qpkg/SABnzbdplus/arm/python
./share/CACHEDEV1_DATA/.qpkg/SickBeard/Repository/lib/python
./share/CACHEDEV1_DATA/.qpkg/SickBeard/x31/python
./share/CACHEDEV1_DATA/.qpkg/SickBeard/x86/python
./share/CACHEDEV1_DATA/.qpkg/SickBeard/arm/python
./share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Python/bin/python

[/usr/local/bin] # ll python
lrwxrwxrwx    1 admin    administ        30 Feb 16 13:34 python -> /mnt/ext/opt/Python/bin/python*
[/usr/local/bin] # cd /mnt/ext/opt/Python/bin
[/mnt/ext/opt/Python/bin] # ll python
lrwxrwxrwx    1 admin    administ         7 Feb 16 13:34 python -> python2*
[/mnt/ext/opt/Python/bin] # ll python*
lrwxrwxrwx    1 admin    administ         7 Feb 16 13:34 python -> python2*
lrwxrwxrwx    1 admin    administ         9 Feb 16 13:34 python2 -> python2.7*
-rwxr-xr-x    1 admin    administ      3.6k Jan 26 20:26 python2.7*
[/mnt/ext/opt/Python/bin] # cd /usr/bin
[/usr/bin] # ll python
lrwxrwxrwx    1 admin    administ        45 Feb 16 20:31 python -> /share/CACHEDEV1_DATA/.qpkg/Python/bin/python*
[/usr/bin] #


Please advise if you need more information.

**Comment by clinton-hall** [comment]
/usr/local/bin/Python points to opt... This is likely not working.

Try your manual execution of the script using /usr/local/bin/Python

If that fails, you need to edit /etc/unit.d/sabnzbd.sh and edit the path export so that /usr/bin is before /usr/local/bin

**Comment by computerconsulting** [comment]
The Path for /usr/local/bin is not in the script.

The env PATH has /usr/bin before /usr/local/bin

/usr/local/bin/python is the following:

[/usr/local/bin] # cd /mnt/ext/opt/Python/bin
[/mnt/ext/opt/Python/bin] # ll python*
lrwxrwxrwx    1 admin    administ         7 Feb 16 13:34 python -> python2*
lrwxrwxrwx    1 admin    administ         9 Feb 16 13:34 python2 -> python2.7*
-rwxr-xr-x    1 admin    administ      3.6k Jan 26 20:26 python2.7*

Appears all links to point to python2.7 in this instance

**Comment by computerconsulting** [comment]
# cd /usr/local/bin
[/usr/local/bin] # ll pyth*
lrwxrwxrwx    1 admin    administ        30 Feb 16 13:34 python -> /mnt/ext/opt/Python/bin/python*
lrwxrwxrwx    1 admin    administ        31 Feb 16 13:34 python2 -> /mnt/ext/opt/Python/bin/python2*
lrwxrwxrwx    1 admin    administ        33 Feb 16 13:34 python2.7 -> /mnt/ext/opt/Python/bin/python2.7*

**Comment by computerconsulting** [comment]
Arrrgh!! There's 2 x 2.7 versions

[/mnt/ext/opt/Python/bin] # /usr/local/bin/python
Python 2.7.5 (default, Jan 26 2015, 17:26:01)
[GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
[/mnt/ext/opt/Python/bin] # python
Python 2.7 (r27:82500, Aug 21 2010, 07:52:47)
[GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by computerconsulting** [comment]
Here is SABnzbd installed Python version from the config page: 

Python Version:	2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]

Is this correct or should it be 2.7.5 version?

Although I've tested both versions on the command line and they both work.

**Comment by clinton-hall** [comment]
SABnzbd is running the correct version. I'm just not sure what environment variable is causing issues when trying to run this external script. I thought it might have been trying to launch the script using a different python version that had issues.

**Comment by computerconsulting** [comment]
I'm scratching my head as well. I'm not familiar with the code inside SAB. There must be something as you mentioned above in terms of SAB install in the way it tries to execute the script... I do notice SAB tried to run the script then exited with an error. Ive actually tried switching versions externally and neither work (same error).

**Comment by computerconsulting** [comment]
FIGURED IT OUT!!!

The CharTranslator.py that comes with the SAB install has the following header

#!/opt/bin/python2.7 -OO The path here is wrong...

IT Should be

#!/usr/bin/python2.7 -OO

Needles and Haystacks you gotta love the farm....!!

**Comment by clinton-hall** [comment]
Ah... I hadn't noticed you only ran with Python... You never try to run the script direct.

I.e. It would have worked with

    python CharTranslator.py

But not with

    ./CharTranslator.py

Sorry I hadn't noticed this earlier. I should have insisted on doing a manual run that way! It was a long day for me, so I just didn't notice.

Even though this isn't nzbToMedia, I'm re-opening so I can keep track of this and lit matey fit his script in the SABnzbd qpkg.

**Comment by computerconsulting** [comment]
Thanks for your help Clinton. Totally empathize on the long day...

Yes I realised the same. I had not gone looking within the py script itself. And as you say I was executing the absolute path of the CharTranslator.py when I was running the py manually (as above).

Python install does not place a link in /opt/bin so it was easier at the time to simply edit the .py itself as I have it in the nzbToMedia folder where I'd rather focus on any changes. 

Thanks again Clinton.

**Comment by Brianbeastsu** [comment]
Hi, I have this same issue but do not understand how you fixed it. I am not well versed in scripts and/or python so any help in simple terms would be greatly appreciated.Thanks

**Comment by clinton-hall** [comment]
edit the first line in the script o read 

    #!/usr/bin/python2.7

**Comment by lukenukum** [comment]
thanks folks, editing first line of: /share/Download/nzbToMedia/CharTranslator.py
from: #!/usr/bin/python2.7
to: #!/opt/bin/python2.7

worked for me :-)

**Comment by maaksel** [comment]
I changed /share/Download/nzbToMedia/CharTranslator.py

First line:  #!/opt/bin/python2.7
to: #!/usr/bin/python2.7

I went to verify the paths first, and found that in /opt/bin was python2.6, while in /usr/bin was python2.7

**Comment by CoolMacDude** [comment]
Hiya Clinton, Please can you help?
I have been using your SABNZB fine for over a year on my QNAP hassle free, but today I noticed there was an update available so all I did was stop the app and start it again so it updated automatically. now when I login to the web interface i get the old error similar to above "SABYenc module... NOT found! Expecting v3.0.2 - https://sabnzbd.org/sabyenc"
I have chmod 777 on /share/Download/nzbToMedia/ CharTranslator.py and toggled the first line between #!/usr/bin/python2.7 and #!/opt/bin/python2.7 without luck....

please, please, please can you help..

kindest regards

Darren
