### ISSUE TITLE
File passed processing but vlc throws error

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#708]
While i realize this is likely a codec issue, this is the first time I've seen where something passed post-proc but wasn't playable. Just curious what I can do to avoid this.

No suitable decoder module:
VLC does not support the audio or video format "hev1". Unfortunately there is no way for you to fix this.

**Comment by clinton-hall** [comment]
It looks like you should be able to update VLC, or install the needed codec 
https://forum.videolan.org/viewtopic.php?t=118343

In theory I could add a list of "valid" codecs that should be rejected, or even try to transcode these to a playable codec on your system... But that is a bit more work...
I am planning some transcoder changes, but I don't know when I am likely to find time to do this.

**Comment by mgaulton** [comment]
Sounds good man. I appreciate it.

I dug up the 2.2.0 pre 3 http://download.videolan.org/testing/vlc-2.2.0-pre3/win32/vlc-2.2.0-pre3-win32.exe wince 2.1.5 is latest release and it appears to be working.
