### ISSUE TITLE
QQ: orphan file cleanup

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#709]
I'm running into a situation that orphan files/folders are left behind in my utorrent processing folder after the torrent is removed from the web ui. (Linux, utserver latest). Just curious if this is something that would make sense to be included here? If files exist but torrent doesn't, nuke folder.

**Comment by clinton-hall** [comment]
This could be added. The idea is to monitor seed status etc and ultimately stop seeding/deleted torrents. And extra "cleanup" check could be added.
All of this is in the growing list of new features, and I don't honestly know when I'll get time to look into it.

**Comment by mgaulton** [comment]
Sounds good. I recall being a culprit in adding to that transcoder wishlist so I understand. Appreciate all the help.

**Comment by mgaulton** [comment]
Another thought. Process the resume.dat and clean up the "inprogress" torrents to ensure they get cleanup as well as the orphaned data folders.

I use a php based script to managed labels and remove "blacklist" words and sometimes i've noticed it doesn't remove the .torrent file from the inprogress folder so it grows and grows.
