### ISSUE TITLE
Can nzbToMedia Remove MP4 Metadata??

### ISSUE THREAD

**Issue by imadunatic** [clinton-hall/nzbToMedia#710]
Clinton, 

Is it possible to have nzbToMedia remove the metadata properties from MP4 files (such as "title")? Plex really likes to pick up this embedded name as the gospel and I'm currently manually removing it. If not, no big deal, as always, thanks for the great work on this.

**Comment by clinton-hall** [comment]
I'm sure it is possible... 
I'll try and look into this, but not sure when I'm going to be ale to get to this.

**Comment by imadunatic** [comment]
No problem. I think the easiest fix may be to play with the settings in Plex.

**Comment by imadunatic** [comment]
For the future user looking for something along these lines: 

It appears adding "-map_metadata -1" as an option to ffmpeg strips out most of the metadata. At the very least it strips the title which is what I was really after.

**Comment by sugarfunk** [comment]
I know this is closed, but was this ever implemented or @imadunatic did you find a work around? Plex is killing me with this.

**Comment by clinton-hall** [comment]
I believe you can add this yourself with
```
[Transcoder]
    generalOptions = -map_metadata,-1
```
