### ISSUE TITLE
FR - Delete Dupe on Schedule

### ISSUE THREAD

**Issue by breezytm** [clinton-hall/nzbToMedia#711]
I am transcoding my files after post-processing. I would like to keep the duplicate and delete it on schedule just in case something happens during the transcoding.

**Comment by clinton-hall** [comment]
On schedule? As in a set time of day week etc? Or after a set interval following transcoding?

I think this would fit in nicely with the other interval/services I am hoping to implement.

**Comment by breezytm** [comment]
My original request is about time of a day. But an X amount of minutes, hours or days would be nice too. 

Keep in mind anything that is downloaded that day must remain. If
I run it every Sunday at 1:00 AM it shouldn't delete something downloaded after 12:00 AM.
