### ISSUE TITLE
Does nzbToMedia hard-linking work with Storage Spaces/Drivepool?

### ISSUE THREAD

**Issue by nikotime** [clinton-hall/nzbToMedia#712]
Hi Clinton,

Been using your service for a good amount of time now and it has been perfect. I am now migrating from Linux to a new Windows build (I know, the shame...) and am wanting to use Storage Spaces in parity mode (similar to Raid 5) which will host all of my media. Ideally, I would love to have transmission set up to download to the storage space with nzbToMedia able to hard link/do something clever which would enable me to continue seeding and only have one copy on my system. Any idea whether this would work, or any potential workarounds?

If Storage Spaces is unfeasible, it would be great to know whether Drivepool would be an alternative.

Cheers
Niko

**Comment by clinton-hall** [comment]
according to this http://www.windowsnetworking.com/articles-tutorials/windows-server-2012/windows-server-2012-r2-storage-spaces-part2.html
the table shows that with NTFS hard-links are supported, but ReFS is not...

so it comes down to the file system you use.

Please try it out and let me know how you get on.

**Comment by nikotime** [comment]
I've just spotted this post in Drivepool which uses NTFS: http://community.covecube.com/index.php?/topic/1066-plex-db-on-drivepool/?p=7005 which I believe would mean that I am out of luck for both Storage Spaces and Drivepool. Will have to download and seed on my boot drive (2tb) and then manually delete when it reaches a certain ratio. I don't suppose you are aware of any torrent application which would allow the deletion of the torrent file and data automatically when hitting that ratio?

**Comment by clinton-hall** [comment]
A sym link will work, but be careful. If the original (seeding file) is deleted, edited, renamed etc, the symbolic link can link to nothing! I.e you can loose the data.
If you never touch your seeding files, this is fine.

As to being able to copy the files and then auto delete the original torrents, I don't know of any torrent client that does this. It is a feature request here, that I hope to add (some day).

**Comment by nikotime** [comment]
That definitely sounds overtly dangerous! And defies the purpose of me running the Storage Spaces in the first place. I'll do a few tests between Storage Spaces and Drivepool to see what gets 

One thing I have found in my googling today is this Deluge plugin: http://forum.deluge-torrent.org/viewtopic.php?f=9&t=47243. I can set it to auto remove my data once it has been seeded for a week and has reached 2.0 seeding ratio. Looks like it should hopefully work! Also has the (quite large) bonus of meaning that only my boot drive will be spinning, which it would be anyway, and my pool will only wake up from standby if I am copying over a file or streaming from Plex.

The github is here: https://github.com/omaralvarez/deluge-autoremoveplus if you want to have a more technical gander!
