### ISSUE TITLE
ImportError: No module named datetime

### ISSUE THREAD

**Issue by yeanpc** [clinton-hall/nzbToMedia#716]
Hello Clinton,

For a couple of weeks I have been running your scripts for post-processing nzbToSickBeard on my Q-NAP-251.

I followed all the instructions related to the installation and configuration of the scripts. After a reboot of my NAS the following error appears in post-processing in sabnzbd:

Traceback (most recent call last):
  File "/share/Download/nzbToMedia/nzbToSickBeard.py", line 254, in <module>
    import nzbToMedia
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py", line 502, in <module>
    import datetime
ImportError: No module named datetime

Can you please provide some guidance on how to troubleshoot this issue?. I'm running Python2.7 as requested in your instructions for the installation and I have re-installed it twice already with no result.

This is the file configuration from my NAS after running find command from Putty for Python2.7

/bin] # find / -name 'python2.7'
/usr/include/python2.7
/usr/local/include/python2.7
/usr/local/bin/python2.7
/usr/local/lib/python2.7
/usr/bin/python2.7
/usr/lib/python2.7
/mnt/ext/opt/Python/include/python2.7
/mnt/ext/opt/Python/bin/python2.7
/mnt/ext/opt/Python/lib/python2.7
/mnt/ext/opt/samba/lib/python2.7
/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Python/include/python2.7
/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Python/lib/python2.7
/share/CACHEDEV1_DATA/.qpkg/Python/bin/python2.7
/share/CACHEDEV1_DATA/.qpkg/Python/include/python2.7
/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7
/share/CACHEDEV1_DATA/.qpkg/CloudLink/python/bin/python2.7
/share/CACHEDEV1_DATA/.qpkg/CloudLink/python/include/python2.7
/share/CACHEDEV1_DATA/.qpkg/CloudLink/python/include/python2.7/python2.7
/share/CACHEDEV1_DATA/.qpkg/CloudLink/python/lib/python2.7
/share/CACHEDEV1_DATA/.qpkg/CloudLink/python/lib/python2.7/python2.7

Any help is greatly appreciated.

Pablo C.

**Comment by clinton-hall** [comment]
Via ssh

    which python

**Comment by yeanpc** [comment]
This is what I executed:

[~] # which python2
/usr/local/bin/python2
[~] # ls -l /usr/local/bin/python2
lrwxrwxrwx    1 admin    administ        31 Feb 26 22:51 /usr/local/bin/python2 -> /mnt/ext/opt/Python/bin/python2*
[~] #

**Comment by clinton-hall** [comment]
Yeah, that's the problem..Somehow /usr/local/bin/python2 is now pointing to /mnt/ext/opt/Python/bin/python2

This is a built in version that misses many modules. Installing Python qpkg should change these symlinks...to point to the .qpkg/python/bin version.

Can you check to see where /usr/local/bin/python and /usr/local/bin/python27 point to?

**Comment by yeanpc** [comment]
As requested:

/usr/local/bin/python -> /mnt/ext/opt/Python/bin/python

/usr/local/bin/python2.7 -> /mnt/ext/opt/Python/python2.7

**Comment by clinton-hall** [comment]
Oh. I just checked. Indeed /usr/local/bin/python links as you have shown, and /usr/bin/python links to the qpkg version.

The difference is which Python for me returns /usr/bin/python
So my PATH variable has /usr/bin/ before /usr/local/bin

There are three ways to tackle this.
1. Edit your system PATH (not sure what happens after reboot)
2. Link /usr/local/bin/python2 to point to /usr/bin/python2
3. Edit /etc/init.d/SABnzbd.sh
    There will be an export PATH line there... Change this to put '/usr/bin:' before the other paths...
    Then restart SABnzbd app.

**Comment by yeanpc** [comment]
I executed option 2 from your list: 

1.- Created a symlink using the following command

ln -sf /usr/bin/python2.7 /usr/local/bin/python2

2.- Checked the results via ssh:
[~] # python2
Python 2.7 (r27:82500, Aug 21 2010, 07:52:47)
[GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>>

and the script completes successfully now:

[INFO]::MAIN: The /share/Download/nzbToMedia/nzbToSickBeard.py script completed successfully.

Thanks a lot for your time and help Clinton.

Pablo C.

**Comment by clinton-hall** [comment]
no worries. glad this is working.
Please let me know if you have any further issues.
