### ISSUE TITLE
Can't execute torrent2media

### ISSUE THREAD

**Issue by endiz** [clinton-hall/nzbToMedia#718]
Hey Clinton, for some reason the torrenttomedia.py script won't execute when a torrent finished within transmission-qt (windows). I set the .py file to execute upon complete, and i set sickrage to download to ..\tv directory. Is there anything else I need to do? I can't see any errors related to torrents in nzbtomedia.log either.

I know my python installation is working because sickrage is humming along. I also updated the path\pathext locations.

**Comment by clinton-hall** [comment]
We need to know if the script is failing, or not starting, or not even being called.
Are there any logs from Transmission to say that it tried to call the script?

**Comment by endiz** [comment]
Nope, not calling it.
This is how transmission is setup: http://i.imgur.com/KnUzWeC.png

**Comment by endiz** [comment]
Seems like someone had luck calling it with a bat file. Let me try that!

**Comment by endiz** [comment]
Switched to utorrent and everything works other than its downloading to the wrong directory!

Seems like transmission-qt is inherently broken when it comes to script executions in windows. Oh well!

**Comment by clinton-hall** [comment]
why is utorrent downloading to the wrong directory?

**Comment by saitoh183** [comment]
Auto labels are so broken on Utorrent 3.4.2...i cant get it to work either
