### ISSUE TITLE
[Request] Additional bitrate option for 3D Content (Movies)

### ISSUE THREAD

**Issue by Mirabis** [clinton-hall/nzbToMedia#724]
Would it be possible to specify another bitrate for CouchPotato when a movie is marked as 3D?

**Comment by clinton-hall** [comment]
is this for the transcoder?

**Comment by clinton-hall** [comment]
flag this in #608

**Comment by Mirabis** [comment]
Yes, it is - sorry. E.g. Having 12M as bit rate for normal movies but using 20M for 3D movies. Because right now it will use 12M for my normal and 3D movies which kills the quality on the 3D ones.

**Comment by clinton-hall** [comment]
cool.. I have flagged this. I'll try and add this when I do the transcoder re-write... 
To be honest, I don't know when this will be... there is a lot going on at the moment...

**Comment by Mirabis** [comment]
Okay cool - Switched provider so with a 500/500 connection this isn't as high priority as it was with the 200/20 connection.
