### ISSUE TITLE
better character conversion to utf-8

### ISSUE THREAD

**Issue by clinton-hall** [clinton-hall/nzbToMedia#725]
Still not detecting all..

from QNAP forums

```
Is there a way to sanitize the filename so both par2 and unrar can handle this during the nzbToCouchPotato.py script or does this have to be handled from within the script itself?


PS. I tried executing CharTranslator.py as pre-queue user script but that is probably too early in the process I guess? The sanitize_safe option in Sab didn't seem to have much effect either since Windows probably doesn't have any qualms with using the © character in a filename.

EDIT: I installed the Enterware GNU version of ls instead of the busybox one to see what character set this copyright sign was from since it obviously wasn't UTF-8. It turns out to be \251
```

**Comment by hugepants** [comment]
Could pyICU help here?
https://github.com/clinton-hall/nzbToMedia/issues/565#issuecomment-62217984

**Comment by KRiZ-R** [comment]
Hi, is this te same problem I have?
After downloading and extracting a file with a copywrite character, the filename is :
©.U.T.SBuS.LN-462x.LD-BEW.p0801.4102.AES.KCALB.mkv

After processing with nzbToMedia it will be reversed, but the copywrite sign becomes 2 strange questionmarks:
Black.Sea.2014.1080P.Web-Dl.X264-Nl.Subs.T.U.��.mkv
This file then cannot normally be removed or renamed, so the script will fail.

INFO	2015-03-09 21:50:11	Executing post-process-script nzbToMedia/nzbToMedia.py for BLACK_SEA_2014_1080p_DD5_1_WEB-DL_x264-NL_SuBS_T_U__#169_
INFO	2015-03-09 21:50:23	nzbToMedia: [21:50:23] [INFO]::MAIN: Checking database structure...
INFO	2015-03-09 21:50:24	nzbToMedia: [21:50:24] [INFO]::MAIN: Checking if git needs an update
INFO	2015-03-09 21:50:26	nzbToMedia: [21:50:26] [INFO]::MAIN: No update needed
INFO	2015-03-09 21:50:26	nzbToMedia: [21:50:26] [INFO]::MAIN: nzbToMedia Version:77da142216ba6dc91bb654635d4bd03f13c881e5 Branch:master (Linux 2.6.32.12)
INFO	2015-03-09 21:50:27	nzbToMedia: [21:50:27] [INFO]::MAIN: #########################################################
INFO	2015-03-09 21:50:27	nzbToMedia: [21:50:27] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
INFO	2015-03-09 21:50:27	nzbToMedia: [21:50:27] [INFO]::MAIN: #########################################################
INFO	2015-03-09 21:50:27	nzbToMedia: [21:50:27] [INFO]::MAIN: Script triggered from NZBGet Version 14.1.
INFO	2015-03-09 21:50:28	nzbToMedia: [21:50:28] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
INFO	2015-03-09 21:50:28	nzbToMedia: [21:50:28] [INFO]::MAIN: Calling CouchPotato:Films to post-process:BLACK_SEA_2014_1080p_DD5_1_WEB-DL_x264-NL_SuBS_T_U__#169_
INFO	2015-03-09 21:50:41	nzbToMedia: [21:50:41] [INFO]::MAIN: Attemping imdbID lookup for BLACK_SEA_2014_1080p_DD5_1_WEB-DL_x264-NL_SuBS_T_U__#169_
INFO	2015-03-09 21:50:41	nzbToMedia: [21:50:41] [INFO]::MAIN: Searching folder and file names for imdbID ...
INFO	2015-03-09 21:50:41	nzbToMedia: [21:50:41] [INFO]::MAIN: Searching IMDB for imdbID ...
INFO	2015-03-09 21:50:47	nzbToMedia: [21:50:47] [WARNING]::MAIN: Unable to find a imdbID for BLACK_SEA_2014_1080p_DD5_1_WEB-DL_x264-NL_SuBS_T_U__#169_
INFO	2015-03-09 21:51:48	nzbToMedia: Traceback (most recent call last):
INFO	2015-03-09 21:51:48	nzbToMedia:   File "/usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 794, in <module>
INFO	2015-03-09 21:51:48	nzbToMedia:     exit(main(sys.argv))
INFO	2015-03-09 21:51:48	nzbToMedia:   File "/usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 696, in main
INFO	2015-03-09 21:51:48	nzbToMedia:     failureLink=failureLink)
INFO	2015-03-09 21:51:48	nzbToMedia:   File "/usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 595, in process
INFO	2015-03-09 21:51:48	nzbToMedia:     inputCategory, failureLink)
INFO	2015-03-09 21:51:48	nzbToMedia:   File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbtomedia/autoProcess/autoProcessMovie.py", line 167, in process
INFO	2015-03-09 21:51:48	nzbToMedia:     if not listMediaFiles(dirName, media=True, audio=False, meta=False, archives=False) and listMediaFiles(dirName, media=False, audio=False, meta=False, archives=True) and extract:
INFO	2015-03-09 21:51:48	nzbToMedia:   File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbtomedia/nzbToMediaUtil.py", line 907, in listMediaFiles
INFO	2015-03-09 21:51:48	nzbToMedia:     elif isMediaFile(curFile, media, audio, meta, archives):
INFO	2015-03-09 21:51:48	nzbToMedia:   File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbtomedia/nzbToMediaUtil.py", line 871, in isMediaFile
INFO	2015-03-09 21:51:48	nzbToMedia:     if fileName.startswith('._'):
INFO	2015-03-09 21:51:48	nzbToMedia:   File "/usr/local/python/lib/python2.7/encodings/utf_8.py", line 16, in decode
INFO	2015-03-09 21:51:48	nzbToMedia:     return codecs.utf_8_decode(input, errors, True)
INFO	2015-03-09 21:51:48	nzbToMedia: UnicodeDecodeError: 'utf8' codec can't decode byte 0xa9 in position 45: invalid start byte
INFO	2015-03-09 21:51:48	nzbToMedia: Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <nzbtomedia.nzbToMediaUtil.PosixProcess instance at 0x48ad23a0>> ignored
ERROR	2015-03-09 21:51:48	Post-process-script nzbToMedia/nzbToMedia.py for BLACK_SEA_2014_1080p_DD5_1_WEB-DL_x264-NL_SuBS_T_U__#169_ failed (terminated with unknown status)
INFO	2015-03-09 21:51:48	Executing post-process-script Logger.py for BLACK_SEA_2014_1080p_DD5_1_WEB-DL_x264-NL_SuBS_T_U__#169_

**Comment by forkless** [comment]
Yes, this is the same problem. 

PS. You can also handle the file via SMB if you have access to a Windows client.

**Comment by forkless** [comment]
Little update here. I was able to extract the offending file without compiling all sorts of libraries and a python wrapper. I simply enclosed the filename in double quotes.

Eg. unrar x "*.part01.rar"
