### ISSUE TITLE
Sickbeard and Couchpotato.py scripts hanging on PP

### ISSUE THREAD

**Issue by thermike** [clinton-hall/nzbToMedia#728]
For the last couple of days (though I'm pretty certain I've not changed anything), whenever I try to PP a download via nzbToSickbeard.py or nzbToCouchpotato.py, the job will get to either script, then begin executing and then hang. Causing all other jobs to stop downloading. 

I can't seem to see anything in the log to report what the error might be but I've attached it anyway. I'm also not seeing any error reports in the log of Sickbeard.

I'm running NZBget 14.2 stable and nzbToMedia V10.10 29/01/2015

```
INFO    Mon Mar 09 2015 23:57:54    Collection Family.Guy.S13E12.HDTV.x264-KILLERS added to history
INFO    Mon Mar 09 2015 23:57:54    Unpausing download after post-process-script
ERROR   Mon Mar 09 2015 23:57:54    Post-process-script EMail.py for Family.Guy.S13E12.HDTV.x264-KILLERS failed (terminated with unknown status)
INFO    Mon Mar 09 2015 23:57:54    Executing post-process-script EMail.py for Family.Guy.S13E12.HDTV.x264-KILLERS
ERROR   Mon Mar 09 2015 23:57:54    Post-process-script NotifyXBMC.py for Family.Guy.S13E12.HDTV.x264-KILLERS failed (terminated with unknown status)
INFO    Mon Mar 09 2015 23:57:54    Executing post-process-script NotifyXBMC.py for Family.Guy.S13E12.HDTV.x264-KILLERS
ERROR   Mon Mar 09 2015 23:57:54    Post-process-script Logger.py for Family.Guy.S13E12.HDTV.x264-KILLERS failed (terminated with unknown status)
INFO    Mon Mar 09 2015 23:57:54    Executing post-process-script Logger.py for Family.Guy.S13E12.HDTV.x264-KILLERS
ERROR   Mon Mar 09 2015 23:57:54    Post-process-script nzbToMedia/nzbToSickBeard.py for Family.Guy.S13E12.HDTV.x264-KILLERS failed (terminated with unknown status)
WARNING Mon Mar 09 2015 23:57:54    Interrupted post-process-script nzbToMedia/nzbToSickBeard.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:57:54    Deleting active post-job Family.Guy.S13E12.HDTV.x264-KILLERS
DETAIL  Mon Mar 09 2015 23:52:02    Usenet Crawler Magazines Feed has no new items
DETAIL  Mon Mar 09 2015 23:52:02    Download Usenet Crawler Magazines Feed completed
WARNING Mon Mar 09 2015 23:52:02    URL Usenet Crawler Magazines Feed: Content-Length is not submitted by server, cannot verify whether the file is complete
DETAIL  Mon Mar 09 2015 23:52:01    Downloading Usenet Crawler Magazines Feed
DETAIL  Mon Mar 09 2015 23:52:01    URL http://www.usenet-crawler.com/rss?t=7010&dl=1&i=94797&r=b689e2a3ee1b7ddf400c4834c31364c6 redirected to https://www.usenet-crawler.com/rss?t=7010&dl=1&i=94797&r=b689e2a3ee1b7ddf400c4834c31364c6
DETAIL  Mon Mar 09 2015 23:52:01    Downloading Usenet Crawler Magazines Feed
DETAIL  Mon Mar 09 2015 23:51:31    Usenet My Movies has no new items
DETAIL  Mon Mar 09 2015 23:51:31    Download Usenet My Movies completed
WARNING Mon Mar 09 2015 23:51:31    URL Usenet My Movies: Content-Length is not submitted by server, cannot verify whether the file is complete
DETAIL  Mon Mar 09 2015 23:51:30    Downloading Usenet My Movies
DETAIL  Mon Mar 09 2015 23:50:47    Usenet Crawler Cart Feed has no new items
DETAIL  Mon Mar 09 2015 23:50:47    Download Usenet Crawler Cart Feed completed
WARNING Mon Mar 09 2015 23:50:47    URL Usenet Crawler Cart Feed: Content-Length is not submitted by server, cannot verify whether the file is complete
DETAIL  Mon Mar 09 2015 23:50:46    Downloading Usenet Crawler Cart Feed
DETAIL  Mon Mar 09 2015 23:50:46    URL http://www.usenet-crawler.com/rss?t=-2&dl=1&i=94797&r=b689e2a3ee1b7ddf400c4834c31364c6&del=1 redirected to https://www.usenet-crawler.com/rss?t=-2&dl=1&i=94797&r=b689e2a3ee1b7ddf400c4834c31364c6&del=1
DETAIL  Mon Mar 09 2015 23:50:46    Downloading Usenet Crawler Cart Feed
DETAIL  Mon Mar 09 2015 23:49:59    NZB Club has no new items
DETAIL  Mon Mar 09 2015 23:49:59    Download NZB Club completed
DETAIL  Mon Mar 09 2015 23:49:58    Downloading NZB Club
INFO    Mon Mar 09 2015 23:47:10    Executing post-process-script nzbToMedia/nzbToSickBeard.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:47:10    Post-process-script GetScripts/DeleteSamples.py for Family.Guy.S13E12.HDTV.x264-KILLERS successful
INFO    Mon Mar 09 2015 23:47:10    DeleteSamples: Script triggered from NZBGet Version 14.2.
INFO    Mon Mar 09 2015 23:47:10    Executing post-process-script GetScripts/DeleteSamples.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:47:10    Post-process-script GetScripts/flatten.py for Family.Guy.S13E12.HDTV.x264-KILLERS successful
INFO    Mon Mar 09 2015 23:47:10    flatten: Checking for empty folders in:/media/Media/TV/Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:47:10    flatten: Flattening directory: /media/Media/TV/Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:47:10    flatten: Script triggered from NZBGet Version 14.2.
INFO    Mon Mar 09 2015 23:47:10    Executing post-process-script GetScripts/flatten.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:47:10    Post-process-script nzbget-subliminal/Subliminal.py for Family.Guy.S13E12.HDTV.x264-KILLERS skipped
INFO    Mon Mar 09 2015 23:47:10    Subliminal: There were no files found.
ERROR   Mon Mar 09 2015 23:47:10    Subliminal: NZBParse - NZB-File is corrupt: /media/Media/_nzbget/nzb/Family.Guy.S13E12.HDTV.x264-KILLERS.nzb.2.queued
INFO    Mon Mar 09 2015 23:47:10    Subliminal: NZB-File detected: Family.Guy.S13E12.HDTV.x264-KILLERS.nzb.2.queued
INFO    Mon Mar 09 2015 23:47:09    Executing post-process-script nzbget-subliminal/Subliminal.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:47:09    Post-process-script FailureLink.py for Family.Guy.S13E12.HDTV.x264-KILLERS successful
INFO    Mon Mar 09 2015 23:47:09    FailureLink: SUCCESS: [Family.Guy.S13E12.HDTV.x264-KILLERS.mp4] has no corruption.
INFO    Mon Mar 09 2015 23:47:09    FailureLink: Checking [Family.Guy.S13E12.HDTV.x264-KILLERS.mp4] for corruption, please stand by ...
INFO    Mon Mar 09 2015 23:47:09    FailureLink: SUCCESS: [Family.Guy.S13E07.INTERNAL.720p.HDTV.x264-BATV.mkv] has no corruption.
INFO    Mon Mar 09 2015 23:47:09    FailureLink: Checking [Family.Guy.S13E07.INTERNAL.720p.HDTV.x264-BATV.mkv] for corruption, please stand by ...
INFO    Mon Mar 09 2015 23:47:08    Executing post-process-script FailureLink.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:47:08    Post-process-script FakeDetector.py for Family.Guy.S13E12.HDTV.x264-KILLERS successful
DETAIL  Mon Mar 09 2015 23:47:08    FakeDetector: Removing temp file /var/nzbget/tmp/FakeDetector/1614
DETAIL  Mon Mar 09 2015 23:47:08    FakeDetector: Detecting completed for Family.Guy.S13E12.HDTV.x264-KILLERS
DETAIL  Mon Mar 09 2015 23:47:08    FakeDetector: Created temp file /var/nzbget/tmp/FakeDetector/1614
DETAIL  Mon Mar 09 2015 23:47:08    FakeDetector: Detecting fake for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:47:07    Executing post-process-script FakeDetector.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:47:07    Pausing download before post-process-script
INFO    Mon Mar 09 2015 23:47:07    Queueing Family.Guy.S13E12.HDTV.x264-KILLERS for post-processing
INFO    Mon Mar 09 2015 23:47:07    Family.Guy.S13E12.HDTV.x264-KILLERS returned from history back to download queue
INFO    Mon Mar 09 2015 23:47:00    Collection Family.Guy.S13E12.HDTV.x264-KILLERS added to history
INFO    Mon Mar 09 2015 23:47:00    Unpausing download after post-process-script
ERROR   Mon Mar 09 2015 23:47:00    Post-process-script EMail.py for Family.Guy.S13E12.HDTV.x264-KILLERS failed (terminated with unknown status)
INFO    Mon Mar 09 2015 23:47:00    Executing post-process-script EMail.py for Family.Guy.S13E12.HDTV.x264-KILLERS
ERROR   Mon Mar 09 2015 23:47:00    Post-process-script NotifyXBMC.py for Family.Guy.S13E12.HDTV.x264-KILLERS failed (terminated with unknown status)
INFO    Mon Mar 09 2015 23:47:00    Executing post-process-script NotifyXBMC.py for Family.Guy.S13E12.HDTV.x264-KILLERS
ERROR   Mon Mar 09 2015 23:47:00    Post-process-script Logger.py for Family.Guy.S13E12.HDTV.x264-KILLERS failed (terminated with unknown status)
INFO    Mon Mar 09 2015 23:47:00    Executing post-process-script Logger.py for Family.Guy.S13E12.HDTV.x264-KILLERS
ERROR   Mon Mar 09 2015 23:47:00    Post-process-script nzbToMedia/nzbToSickBeard.py for Family.Guy.S13E12.HDTV.x264-KILLERS failed (terminated with unknown status)
WARNING Mon Mar 09 2015 23:47:00    Interrupted post-process-script nzbToMedia/nzbToSickBeard.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:47:00    Deleting active post-job Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:46:21    Executing post-process-script nzbToMedia/nzbToSickBeard.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:46:21    Post-process-script GetScripts/DeleteSamples.py for Family.Guy.S13E12.HDTV.x264-KILLERS successful
INFO    Mon Mar 09 2015 23:46:21    DeleteSamples: Script triggered from NZBGet Version 14.2.
INFO    Mon Mar 09 2015 23:46:21    Executing post-process-script GetScripts/DeleteSamples.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:46:21    Post-process-script GetScripts/flatten.py for Family.Guy.S13E12.HDTV.x264-KILLERS successful
INFO    Mon Mar 09 2015 23:46:21    flatten: Checking for empty folders in:/media/Media/TV/Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:46:21    flatten: Flattening directory: /media/Media/TV/Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:46:21    flatten: Script triggered from NZBGet Version 14.2.
INFO    Mon Mar 09 2015 23:46:20    Executing post-process-script GetScripts/flatten.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:46:20    Post-process-script nzbget-subliminal/Subliminal.py for Family.Guy.S13E12.HDTV.x264-KILLERS skipped
INFO    Mon Mar 09 2015 23:46:20    Subliminal: There were no files found.
ERROR   Mon Mar 09 2015 23:46:20    Subliminal: NZBParse - NZB-File is corrupt: /media/Media/_nzbget/nzb/Family.Guy.S13E12.HDTV.x264-KILLERS.nzb.2.queued
INFO    Mon Mar 09 2015 23:46:20    Subliminal: NZB-File detected: Family.Guy.S13E12.HDTV.x264-KILLERS.nzb.2.queued
INFO    Mon Mar 09 2015 23:46:18    Executing post-process-script nzbget-subliminal/Subliminal.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:46:18    Post-process-script FailureLink.py for Family.Guy.S13E12.HDTV.x264-KILLERS successful
INFO    Mon Mar 09 2015 23:46:18    FailureLink: SUCCESS: [Family.Guy.S13E12.HDTV.x264-KILLERS.mp4] has no corruption.
INFO    Mon Mar 09 2015 23:46:18    FailureLink: Checking [Family.Guy.S13E12.HDTV.x264-KILLERS.mp4] for corruption, please stand by ...
INFO    Mon Mar 09 2015 23:46:18    FailureLink: SUCCESS: [Family.Guy.S13E07.INTERNAL.720p.HDTV.x264-BATV.mkv] has no corruption.
INFO    Mon Mar 09 2015 23:46:18    FailureLink: Checking [Family.Guy.S13E07.INTERNAL.720p.HDTV.x264-BATV.mkv] for corruption, please stand by ...
INFO    Mon Mar 09 2015 23:46:17    Executing post-process-script FailureLink.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:46:17    Post-process-script FakeDetector.py for Family.Guy.S13E12.HDTV.x264-KILLERS successful
DETAIL  Mon Mar 09 2015 23:46:17    FakeDetector: Removing temp file /var/nzbget/tmp/FakeDetector/1614
DETAIL  Mon Mar 09 2015 23:46:17    FakeDetector: Detecting completed for Family.Guy.S13E12.HDTV.x264-KILLERS
DETAIL  Mon Mar 09 2015 23:46:17    FakeDetector: Created temp file /var/nzbget/tmp/FakeDetector/1614
DETAIL  Mon Mar 09 2015 23:46:17    FakeDetector: Detecting fake for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:46:16    Executing post-process-script FakeDetector.py for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:46:16    Nothing to cleanup for Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:46:16    Cleaning up Family.Guy.S13E12.HDTV.x264-KILLERS
INFO    Mon Mar 09 2015 23:46:16    Pausing download before cleanup
```

**Comment by clinton-hall** [comment]
check to see if anything was added to nzbtomedia.log at this time? check to see if anything was added to the logs.

Also, check to see if there is an nzbtomedia.pid file... if so, delete this and try postprocessing again. (although if this existed it should be logging a message to say the script is already running (or similar).

**Comment by thermike** [comment]
Removing the existing log and .pid file from /var/nzbget/ppscripts/nzbToMedia/log seems to have stopped the pp-script process from hanging which is good.

However I'm still finding that nzbToMedia is failing in pp. Resulting in the downloaded item showing as a 'pp-failure' in nzbget history.

Oddly though I'm getting an email saying the downloaded file was a success.

Email log

Download of "Family.Guy.S13E12.HDTV.x264-KILLERS" has successfully completed.
	Par-Status: skipped
	Unpack-Status: success

	Files:
	_postprocesslog.txt
	family.guy.s13e12.hdtv.x264-killers.nfo
	Family.Guy.S13E12.HDTV.x264-KILLERS.mp4

	Post-processing log:
	INFO    2015-03-11 00:32:31     Executing post-process-script FakeDetector.py for Family.Guy.S13E12.HDTV.x264-KILLERS
	DETAIL  2015-03-11 00:32:31     FakeDetector: Detecting fake for Family.Guy.S13E12.HDTV.x264-KILLERS
	DETAIL  2015-03-11 00:32:31     FakeDetector: Created temp file /var/nzbget/tmp/FakeDetector/1614
	DETAIL  2015-03-11 00:32:31     FakeDetector: Detecting completed for Family.Guy.S13E12.HDTV.x264-KILLERS
	DETAIL  2015-03-11 00:32:31     FakeDetector: Removing temp file /var/nzbget/tmp/FakeDetector/1614
	INFO    2015-03-11 00:32:31     Post-process-script FakeDetector.py for Family.Guy.S13E12.HDTV.x264-KILLERS successful
	INFO    2015-03-11 00:32:31     Executing post-process-script FailureLink.py for Family.Guy.S13E12.HDTV.x264-KILLERS
	INFO    2015-03-11 00:32:32     FailureLink: Checking [Family.Guy.S13E07.INTERNAL.720p.HDTV.x264-BATV.mkv] for corruption, please stand by ...
	INFO    2015-03-11 00:32:32     FailureLink: SUCCESS: [Family.Guy.S13E07.INTERNAL.720p.HDTV.x264-BATV.mkv] has no corruption.
	INFO    2015-03-11 00:32:32     FailureLink: Checking [Family.Guy.S13E12.HDTV.x264-KILLERS.mp4] for corruption, please stand by ...
	INFO    2015-03-11 00:32:32     FailureLink: SUCCESS: [Family.Guy.S13E12.HDTV.x264-KILLERS.mp4] has no corruption.
	INFO    2015-03-11 00:32:32     Post-process-script FailureLink.py for Family.Guy.S13E12.HDTV.x264-KILLERS successful
	INFO    2015-03-11 00:32:32     Executing post-process-script nzbget-subliminal/Subliminal.py for Family.Guy.S13E12.HDTV.x264-KILLERS
	INFO    2015-03-11 00:32:33     Subliminal: NZB-File detected: Family.Guy.S13E12.HDTV.x264-KILLERS.nzb.2.queued
	ERROR   2015-03-11 00:32:33     Subliminal: NZBParse - NZB-File is corrupt: /media/Media/_nzbget/nzb/Family.Guy.S13E12.HDTV.x264-KILLERS.nzb.2.queued
	INFO    2015-03-11 00:32:33     Subliminal: There were no files found.
	INFO    2015-03-11 00:32:33     Post-process-script nzbget-subliminal/Subliminal.py for Family.Guy.S13E12.HDTV.x264-KILLERS skipped
	INFO    2015-03-11 00:32:33     Executing post-process-script GetScripts/flatten.py for Family.Guy.S13E12.HDTV.x264-KILLERS
	INFO    2015-03-11 00:32:34     flatten: Script triggered from NZBGet Version 14.2.
	INFO    2015-03-11 00:32:34     flatten: Flattening directory: /media/Media/TV/Family.Guy.S13E12.HDTV.x264-KILLERS
	INFO    2015-03-11 00:32:34     flatten: Checking for empty folders in:/media/Media/TV/Family.Guy.S13E12.HDTV.x264-KILLERS
	INFO    2015-03-11 00:32:34     Post-process-script GetScripts/flatten.py for Family.Guy.S13E12.HDTV.x264-KILLERS successful
	INFO    2015-03-11 00:32:34     Executing post-process-script GetScripts/DeleteSamples.py for Family.Guy.S13E12.HDTV.x264-KILLERS
	INFO    2015-03-11 00:32:34     DeleteSamples: Script triggered from NZBGet Version 14.2.
	INFO    2015-03-11 00:32:34     Post-process-script GetScripts/DeleteSamples.py for Family.Guy.S13E12.HDTV.x264-KILLERS successful
	INFO    2015-03-11 00:32:34     Executing post-process-script nzbToMedia/nzbToSickBeard.py for Family.Guy.S13E12.HDTV.x264-KILLERS
	INFO    2015-03-11 00:32:37     nzbToSickBeard: [00:32:37] [INFO]::MAIN: Checking database structure...
	INFO    2015-03-11 00:32:37     nzbToSickBeard: [00:32:37] [INFO]::MAIN: Checking if git needs an update
	INFO    2015-03-11 00:32:39     nzbToSickBeard: [00:32:39] [INFO]::MAIN: No update needed
	INFO    2015-03-11 00:32:39     nzbToSickBeard: [00:32:39] [INFO]::MAIN: nzbToMedia Version:77da142216ba6dc91bb654635d4bd03f13c881e5 Branch:master (Linux 3.4.90)
	INFO    2015-03-11 00:32:39     nzbToSickBeard: [00:32:39] [WARNING]::MAIN: Failed to locate ffmpeg. Transcoding disabled!
	INFO    2015-03-11 00:32:39     nzbToSickBeard: [00:32:39] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
	INFO    2015-03-11 00:32:39     nzbToSickBeard: [00:32:39] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
	INFO    2015-03-11 00:32:39     nzbToSickBeard: [00:32:39] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
	INFO    2015-03-11 00:32:39     nzbToSickBeard: [00:32:39] [INFO]::MAIN: #########################################################
	INFO    2015-03-11 00:32:39     nzbToSickBeard: [00:32:39] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
	INFO    2015-03-11 00:32:39     nzbToSickBeard: [00:32:39] [INFO]::MAIN: #########################################################
	INFO    2015-03-11 00:32:39     nzbToSickBeard: [00:32:39] [INFO]::MAIN: Script triggered from NZBGet Version 14.2.
	INFO    2015-03-11 00:32:39     nzbToSickBeard: [00:32:39] [ERROR]::MAIN: Unable to locate a section with subsection:tv enabled in your autoProcessMedia.cfg, exiting!
	INFO    2015-03-11 00:32:39     nzbToSickBeard: [00:32:39] [ERROR]::MAIN: A problem was reported in the /var/nzbget/ppscripts/nzbToMedia/nzbToSickBeard.py script.
	ERROR   2015-03-11 00:32:39     Post-process-script nzbToMedia/nzbToSickBeard.py for Family.Guy.S13E12.HDTV.x264-KILLERS failed
	INFO    2015-03-11 00:32:39     Executing post-process-script Logger.py for Family.Guy.S13E12.HDTV.x264-KILLERS
	INFO    2015-03-11 00:32:43     Post-process-script Logger.py for Family.Guy.S13E12.HDTV.x264-KILLERS successful
	INFO    2015-03-11 00:32:43     Executing post-process-script NotifyXBMC.py for Family.Guy.S13E12.HDTV.x264-KILLERS
	DETAIL  2015-03-11 00:32:43     NotifyXBMC: Script successfully started
	INFO    2015-03-11 00:32:49     NotifyXBMC: Sending update command: {"jsonrpc":"2.0","method":"VideoLibrary.Scan","params":{"directory":"smb://192.168.0.20/Media/TV/Family.Guy.S13E12.HDTV.x264-KILLERS"},"id":1} to 192.168.0.15:1230
	ERROR   2015-03-11 00:32:49     NotifyXBMC: Unable to open URL: [Errno socket error] [Errno 113] No route to host
	INFO    2015-03-11 00:32:49     NotifyXBMC: Displaying notification...
	ERROR   2015-03-11 00:32:49     NotifyXBMC: Unable to open URL: [Errno socket error] [Errno 113] No route to host
	INFO    2015-03-11 00:32:49     NotifyXBMC: Failed.
	ERROR   2015-03-11 00:32:50     Post-process-script NotifyXBMC.py for Family.Guy.S13E12.HDTV.x264-KILLERS failed
	INFO    2015-03-11 00:32:50     Executing post-process-script EMail.py for Family.Guy.S13E12.HDTV.x264-KILLERS
	DETAIL  2015-03-11 00:32:50     EMail: Script successfully started


nzbToMedia.log

	$cat nzbtomedia.log
	2015-03-11 00:32:37 INFO    ::MAIN: Checking database structure...
	2015-03-11 00:32:37 INFO    ::MAIN: Checking if git needs an update
	2015-03-11 00:32:39 INFO    ::MAIN: No update needed
	2015-03-11 00:32:39 INFO    ::MAIN: nzbToMedia Version:77da142216ba6dc91bb654635d4bd03f13c881e5 Branch:master (Linux 3.4.90)
	2015-03-11 00:32:39 WARNING ::MAIN: Failed to locate ffmpeg. Transcoding disabled!
	2015-03-11 00:32:39 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...
	2015-03-11 00:32:39 WARNING ::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
	2015-03-11 00:32:39 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...
	2015-03-11 00:32:39 INFO    ::MAIN: #########################################################
	2015-03-11 00:32:39 INFO    ::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
	2015-03-11 00:32:39 INFO    ::MAIN: #########################################################
	2015-03-11 00:32:39 INFO    ::MAIN: Script triggered from NZBGet Version 14.2.
	2015-03-11 00:32:39 ERROR   ::MAIN: Unable to locate a section with subsection:tv enabled in your autoProcessMedia.cfg, exiting!
	2015-03-11 00:32:39 ERROR   ::MAIN: A problem was reported in the /var/nzbget/ppscripts/nzbToMedia/nzbToSickBeard.py script.

**Comment by clinton-hall** [comment]
In your autoProcessMedia.cfg, try changing
    
    [SickBeard]
        [[tv]]
            Enabled = 1

Or try deleting autoProcessMedia.cfg and let NZBGet recreate this from the webUI settings/migration.

**Comment by thermike** [comment]
I've deleted /var/nzbget/ppscripts/nzbToMedia/autoProcessMedia.cfg. 

I've reloaded and re-saved the nzbget.conf using the nzbget GUI. However the autoProcessMedia.cfg file hasn't been recreated in /var/nzbget/ppscripts/nzbToMedia/ and the same fail error occurs. I'm using a non-standard category for my sickbeard auto-grabbed downloads. [tv-sickbeard] is how I have it configured.

Output from /var/nzbget/ppscripts/nzbToMedia/logs/

	2015-03-11 20:45:56 INFO    ::MAIN: No update needed
	2015-03-11 20:45:56 INFO    ::MAIN: nzbToMedia Version:77da142216ba6dc91bb654635d4bd03f13c881e5 Branch:master (Linux 3.4.90)
	2015-03-11 20:45:56 WARNING ::MAIN: Failed to locate ffmpeg. Transcoding disabled!
	2015-03-11 20:45:56 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...
	2015-03-11 20:45:56 INFO    ::MAIN: #########################################################
	2015-03-11 20:45:56 INFO    ::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
	2015-03-11 20:45:56 INFO    ::MAIN: #########################################################
	2015-03-11 20:45:56 INFO    ::MAIN: Script triggered from NZBGet Version 14.2.
	2015-03-11 20:45:56 ERROR   ::MAIN: Unable to locate a section with subsection:tv enabled in your autoProcessMedia.cfg, exiting!
	2015-03-11 20:45:56 ERROR   ::MAIN: A problem was reported in the /var/nzbget/ppscripts/nzbToMedia/nzbToSickBeard.py script.

**Comment by clinton-hall** [comment]
can you try deleting all of the `.pyc` files in nzbToMedia?

It appears from the log that this is actually calling the .pyc, which isn't being updated...

**Comment by thermike** [comment]
Deleting *.pyc files from the nzbToMedia/ folder has definitely helped.

However now I'm getting an error about 'Permissions Denied'

	2015-03-12 11:37:58 POSTPROCESS::SICKBEARD: Checking size of existing file:
	2015-03-12 11:37:58 POSTPROCESS::SICKBEARD: There is no existing file
	2015-03-12 11:37:58 POSTPROCESS::SICKBEARD: File doesn't exist, marking it safe to replace
	2015-03-12 11:37:58 POSTPROCESS::SICKBEARD: This download is marked as safe to replace existing file
	2015-03-12 11:37:58 POSTPROCESS::SICKBEARD: Found release name Family.Guy.S13E12.HDTV.x264-KILLERS
	2015-03-12 11:37:58 POSTPROCESS::SICKBEARD: Destination folder for this episode: /media/Media/TV/Family Guy
	2015-03-12 11:37:58 POSTPROCESS::SICKBEARD: Moving file from /media/Media/TV/Family.Guy.S13E12.HDTV.x264-KILLERS/Family.Guy.S13E12.HDTV.x264-KILLERS.mp4 to /media/Media/TV/Family Guy/Family Guy - 13x12 - Stewie is Enceinte.mp4
	2015-03-12 11:37:58 POSTPROCESS::SICKBEARD: Unable to move file /media/Media/TV/Family.Guy.S13E12.HDTV.x264-KILLERS/Family.Guy.S13E12.HDTV.x264-KILLERS.mp4 to /media/Media/TV/Family Guy/Family Guy - 13x12 - Stewie is Enceinte.mp4: error 13 : Permission denied
	2015-03-12 11:37:58 POSTPROCESS::SICKBEARD: Processing failed for /media/Media/TV/Family.Guy.S13E12.HDTV.x264-KILLERS/Family.Guy.S13E12.HDTV.x264-KILLERS.mp4: Unable to move the files to destination folder: /media/Media/TV/Family Guy
	2015-03-12 11:37:58 ERROR   ::MAIN: A problem was reported in the /var/nzbget/ppscripts/nzbToMedia/nzbToSickBeard.py script.
	
Again the odd thing is, the files have the correct 664. Sickbeard (group: samba) runs on it's own users but is part of the same group that the files are owned.

	$lla Family.Guy.S13E12.HDTV.x264-KILLERS/
	total 69M
	drwxr-xr-x  2 nzbget samba 4.0K Mar 12 11:37 .
	drwxrwxr-x 68 nzbget samba  12K Mar 12 11:24 ..
	-rw-rw-r--  1 nzbget samba  69M Mar  8 17:14 Family.Guy.S13E12.HDTV.x264-KILLERS.mp4
	-rw-rw-r--  1 nzbget samba  11K Mar  9 20:35 family.guy.s13e12.hdtv.x264-killers.nfo
	-rw-rw-r--  1 nzbget samba  11K Mar 12 11:37 _postprocesslog.txt

**Comment by clinton-hall** [comment]
what about the next directory up.. where it tries to move the file to..

What are the permissions for `/media/Media/TV/Family Guy/` ?

**Comment by thermike** [comment]
`/media/Media/TV/Family Guy/` has the same same ownership and permissions should it shouldn't be causing an issue.

	$ls -la /media/Media/TV/
	drwxrwxr-x  9 nzbget samba 4.0K Mar 13 03:32 Family Guy

**Comment by clinton-hall** [comment]
yes, the permissions look correct, but SickBeard appears to not be able to move these files.
You could try making 777 permissions, or try making nzbget and sickbeard run as the same user.
