### ISSUE TITLE
CouchPotato - uTorrent - It removes the important file to seed after extracting and not moving file to proper directory.

### ISSUE THREAD

**Issue by nucce1** [clinton-hall/nzbToMedia#731]
Hi.

My directory structure is like this:
D:\download\movie (labled movies from couchpotato to utorrent goes here).
Y:\Movies\ (here is where my movies shall end up) (This is a network mapping)

When I download a movie, it correctly ends up in D:\download\movie as intended, but then the postprocessing comes in and ruin everything.
What I think is wrong:
* It removes all the rar files so it can't go back to seed mode again.
* It extract files same to same directory(don't know if that's correct).
* It never(according to log) even try to move the folder/file to Y:\Movies.

Logfile: http://pastebin.com/C6WPybP1
The link http://localhost:8082/api/b3c1884edeee457d8e6d3e58ceee45db/media.get says:
{"media": null, "success": false}

Configuration for CouchPotato in autoProcessMedia.cfg:
[CouchPotato]
    #### autoProcessing for Movies
    #### movie - category that gets called for post-processing with CPS
    [[movie]]
        enabled = 1
        apikey = b3c1884edeee457d8e6d3e58ceee45db
        host = localhost
        port = 8082
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        ssl = 0
        web_root = ""
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        method = renamer
        delete_failed = 1
        wait_for = 7
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleteing ignored files (samples and invalid media files)
        delete_ignored = 1
        ##### Enable if Couchpotato is on a remote server for this category
        remote_path = 0
        ##### Set to path where download

[Torrent]
    ###### clientAgent - Supported clients: utorrent, transmission, deluge, rtorrent, vuze, other
    clientAgent = utorrent
    ###### useLink - Set to hard for physical links, sym for symbolic links, move to move, and no to not use links (copy)
    useLink = no
    ###### outputDirectory - Default output directory (categories will be appended as sub directory to outputDirectory)
    outputDirectory = D:\download\
    ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode. 
    default_downloadDirectory = D:\download\
    ###### Other categories/labels defined for your downloader. Does not include CouchPotato, SickBeard, HeadPhones, Mylar categories.
    categories = music_videos, pictures, software, manual
    ###### A list of categories that you don't want to be flattened (i.e preserve the directory structure when copying/linking.
    noFlatten = pictures, manual
    ###### uTorrent Hardlink solution (You must edit this if your using TorrentToMedia.py with uTorrent)
    uTorrentWEBui = http://localhost:8083/gui/
    uTorrentUSR = nucce
    uTorrentPWD = apapa
    ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
    deleteOriginal = 0

What I'm doing wrong?

Regards/nucce

**Comment by clinton-hall** [comment]
The reason this isn't renamed should be in the CouchPotato logs at 2015-03-15 11:50:18

The reason the .rar files were deleted is because you have your output directory the same as the input..
try editing autoProcessMedia.cfg

```
[Torrent]
useLink = hard
###### outputDirectory - Default output directory (categories will be appended as sub directory to outputDirectory)
outputDirectory = D:\download\processed
```
and create a folder 
D:\download\processed
