### ISSUE TITLE
Couchpotato Overwriting previous movie ?

### ISSUE THREAD

**Issue by Artwebb1986** [clinton-hall/nzbToMedia#732]
Not sure if this is a couchpotato issue or the script issue ?

I manually sent Penguins.of.Madagascar NZB to sab and have it in the movie category with the couchpotato script it will finish and process the movie and copy to the proper dirs.
Then I manually sent Annie and it processed and overwrote the mkv in the Penguins.of.Madagascar dir and keep the same name as Penguins.of.Madagascar but when played it was Annie.

If i add .cp(ttxxxxxxx) after the Penguins.of.Madagascar & Annie names manually or couchpotato snags them it works just fine.

Happened to me on 2 separate computers. One using windows sab/couchpotato/nzbtomedia
and second machine running Ubuntu linux. also using sab/couchpotato/nzbtomedia

**Comment by clinton-hall** [comment]
#722 
I'll try and fix this soon.
