### ISSUE TITLE
QQ: tracking complete torrents

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#733]
I have a php script using the utorrent web api for categorizing, scrubbing unwanted downloads etc and am trying to create a file with torrent titles that have already been completed.  I just need one title per line, this gets imported and processed in my script. i've tried the below but the done.list is blank.

 [[ALL]]
        enabled = 1
        Torrent_NoLink = 0
        extract = 0
        remote_path = 0
        user_script_mediaExtensions = ALL
        user_script_path = /opt/tortrack.sh
        user_script_param = TN
        user_script_runOnce = 1
        user_script_successCodes = 0
        user_script_clean = 0
        delay = 120
        unique_path = 1
        watch_dir = /home/processed

:tortrack.sh
echo "$1" >> /opt/done.list

**Comment by clinton-hall** [comment]
Are you using any other features of my scripts? i.e CouchPotato or SickRage processing?

Currently the userscript only gets called if it matches a category that doesn't get used for sickbeard/couchpotato.

There is already a request here to run the userscript In Addition to any other processing. #664 

I hope to add this at some stage.
