### ISSUE TITLE
[REQ] Category selection torrents

### ISSUE THREAD

**Issue by schumi2004** [clinton-hall/nzbToMedia#737]
I was wondering if the following is or would be possible to implement.

I'm using Transmission for both Sonarr and CouchPotato but i'm letting Sonarr handle post-processing.
Side effect is that i can't implement post-processing in Transmission because Sonarr post-processing would break and in the end i would have to chose if I would like to use Transmission for or Sonarr or CouchPotato because both isn't possible in this situation.

Is there a way to make a check in script that checks for categorie/folder aka .series or .movies and skips if folder is .series and proceeds for .movies so post-processing for Sonarr is kept intact?

I'm running Transmission on a Synology and there isn't a alternative that could handle post-processing scripts per category.

**Comment by clinton-hall** [comment]
I believe this is possible.

```
[CouchPotato]
    [[.movies]]
        enabled = 1

[NZBDrone]
    [[.series]]
        enabled = 0
```

so basically, if the .series category is not defined and enabled anywhere, then it won't be processed by nzbToMedia.

does this achieve what you want?

**Comment by schumi2004** [comment]
Looks good to me ;)

**Comment by schumi2004** [comment]
You haven't added this yet right?
I'll have a play with code to see if i can accomplish such.

**Comment by clinton-hall** [comment]
no, I haven't added anything here. I thought setting the config as above would do this already.
