### ISSUE TITLE
Post-Process failure

### ISSUE THREAD

**Issue by Jonnehs** [clinton-hall/nzbToMedia#738]
http://pastebin.com/ZZDgrzSd

Not sure what this all means, basil.

**Comment by seanjohnite** [comment]
Did you happen to recently set up a reverse proxy server or set a new web root? Make sure to reflect these changes in your nzbToMedia config.

**Comment by Jonnehs** [comment]
No I didn't, all I've done is install sickrage and sabnzbd+ and put the relevant details into the config. The output seems to indicate its getting to the login page and not getting much further..?

**Comment by seanjohnite** [comment]
Yeah, I think I might double and triple check your login information for Sickbeard in your autoProcessMedia.cfg. Maybe clear any cookies you've set and try to log in to Sickbeard itself with the information you're trying?

Another thing I might try is to turn debug (in the .cfg under [General], log_debug = 1). Then you can see and test the address that nzbToMedia is trying to use for its API, should happen right after 
```
[POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
```
It will look like
```
[DEBUG]::SICKBEARD: Opening URL: http://localhost:8081/sickrage/home/postprocess/processEpisode with params: ...
```
That's mine, but yours may be different (different port, may not have "/sickrage" in the middle). Make sure that you can open that URL in an incognito window.

**Comment by Jonnehs** [comment]
[18:22:37] [DEBUG]::SICKBEARD: Opening URL: http://localhost:7073/home/postprocess/processEpisode with params:

The page loads fine, presenting a login page which works with the credentials i gave it

**Comment by Jonnehs** [comment]
@seanjohnite Thanks - fixed it. Password had a hash in it, which apparently this doesn't like. Removed it and changed the pw - all ok now
