### ISSUE TITLE
Question - Delete After Transcode

### ISSUE THREAD

**Issue by breezytm** [clinton-hall/nzbToMedia#740]
Hi,

I am having an issue here. I don't know if this is a bug or not but I remembered at first my original episode file used to get deleted after the transcoding is completed. That seems to have stop working. I don't recall making any changes to the config.
duplicate setting is set to 0

**Comment by breezytm** [comment]
This issue is so frustrating. I think it's due to the fact the path NzbGet is feeding sonarr is not the transcoded folder not the actual download dir. Since Sonarr isn't aware of it so It can't delete it.

**Comment by clinton-hall** [comment]
Can you try setting
```
[General]
    force_clean = 1
```

**Comment by breezytm** [comment]
Unfortunately that didn't work.

**Comment by breezytm** [comment]
Any additional thoughts on how to make Sonarr clean up after post-processing?

**Comment by Taloth** [comment]
breez, you have Completed Download Handling enabled in Sonarr, right?

**Comment by breezytm** [comment]
Yes sir. ![capture](https://cloud.githubusercontent.com/assets/3412923/7393666/145a2c9c-ee5d-11e4-9087-b45cd09069e8.PNG)
