### ISSUE TITLE
manual run not working

### ISSUE THREAD

**Issue by FlyingPersian** [clinton-hall/nzbToMedia#743]
Hi.
I'm trying to manually run nzbToMedia, but it isn't working :/ It fails to identify whether to use sickbeard or Couchpotato. I tried these commands:

python nzbToMedia.py /path/to//download/dir/Shows/Showname
python TorrentToMedia.py /path/to/download/dir/Shows/Showname

Both give me this log:

http://pastebin.com/55hfgAZA

Any ideas why this isn't working? :/

**Comment by FlyingPersian** [comment]
Fixed it myself :D Thanks to a post of yours on a different issue. This is the command to run:

./nzbToMedia.py "/path/to/movie" "moviename" "moviename" "" "category" "" "0"

It's important to use "" before and after "category", not sure what they do but they fixed it. Also not sure what the "0" is :x

**Comment by FlyingPersian** [comment]
I actually have to reopen it :x How do I tell it to use my autoProcessMedia.cfg? It just extracted everything to where the rars are located and not to my process folder. I want it to run as always, just manually this time.

**Comment by seanjohnite** [comment]
I'm not sure whether Sickbeard has this feature, but you can manually test (and process other "forgotten" episodes) the TV-post-processing end in SickRage by going to Shows > Manual Post-Processing, specifying the directory, and running the script.

Again, not sure if this is a feature of the SickRage fork or if it's built into Sickbeard as well.

**Comment by clinton-hall** [comment]
process folder is only used by TorrentToMedia, not nzbToMedia.

So manually run torrent To Media.

What downloader do you use for torrents? I can help confirm the actual commands for manual run.

**Comment by FlyingPersian** [comment]
I want the script to be run because things have to be extracted first.

@clinton: rtorrent

**Comment by clinton-hall** [comment]
@FlyingPersian 
`./ToeewntToMedia.py "/path/to/movie" "moviename" "category" "torrenthash"`
This should link everything to the "process" directory.

**Comment by FlyingPersian** [comment]
I'll try that on tuesday. My damn VPN server at home isn't working correctly, so I've to wait till I'm back. I'll report back then.

**Comment by FlyingPersian** [comment]
Works like a charm, thanks a lot!
