### ISSUE TITLE
revisited: AttributeError: 'module' object has no attribute 'main'

### ISSUE THREAD

**Issue by seanjohnite** [clinton-hall/nzbToMedia#744]
Hey Clinton (my username used to be slyde56),

I think I've figured something out about this error, cross referencing #670 and [this other discussion](https://sickrage.tv/forums/forum/help-support/nzbtomedia-support/16712-attributeerror-module-object-has-no-attribute-main)

I'm now running NZBGet on an Ubuntu 14.04 virtual machine, and trying to get post-processing to work. This is what my log files looked like, similar to brando:

```
Tue Apr 14 03:37:01 2015	INFO	Executing post-process-script nzbToMedia/nzbToCouchPotato.py for Movie
Tue Apr 14 03:37:03 2015	INFO	nzbToCouchPotato: Traceback (most recent call last):
Tue Apr 14 03:37:03 2015	INFO	nzbToCouchPotato:   File "/media/sf_Odin/Downloads/NZBget/scripts/nzbToMedia/nzbToCouchPotato.py", line 249, in <module>
Tue Apr 14 03:37:03 2015	INFO	nzbToCouchPotato:     result = nzbToMedia.main(sys.argv, section)
Tue Apr 14 03:37:03 2015	INFO	nzbToCouchPotato: AttributeError: 'module' object has no attribute 'main'
Tue Apr 14 03:37:03 2015	ERROR	Post-process-script nzbToMedia/nzbToCouchPotato.py for Movie failed (terminated with unknown status)
```

I realized after reading a bit that our Python was actually trying to import the `nzbtomedia` module folder instead of the `nzbToMedia.py` file. They're both technically valid imports (because of the `__init__.py` in the nzbtomedia folder), and for some reason our Python does not seem to notice the capital letter difference. I changed `nzbToMedia.py` to `nzbToMediar.py`, changing the import line to `import nzbToMediar`, and the script now calls `nzbToMediar.py` perfectly. This is obviously not the optimal fix, but I just wanted to check to make sure that this was the root of the issue.

Thoughts?

**Comment by clinton-hall** [comment]
oh wow... so the issues is the imports are not case sensitive???

Ah, a bit of reading reveals this happens when the system does not have case sensitive paths...

Can you check to see if you have an environment variable `PYTHONCASEOK` set?

**Comment by seanjohnite** [comment]
I don't get any response to `env | grep PYTHONCASEOK`...

I think the answer to this might be complicated. I'm running my Ubuntu VM on a Windows PC, where I have given the VM access to one of the drives on my Windows PC (via Shared Folders in VirtualBox). The NZBGet folder and the one with the scripts actually resides on this drive (mounted at `/media/sf_Odin/`. It's possible that something about the way this is mounted changes the case information.

Yep, simply moving the script folder from the shared folder to a folder "on" the VM causes the error to stop happening.

**Comment by clinton-hall** [comment]
Wow... good info.

So, to make this more reliable, I will try and avoid folders and files with the same (case different) names for future restructures.

At this time, any attempt to resolve this will require either changing the name of the script that some people may be calling directly, or a lot of editing the paths for imports throughout every script in the project...
