### ISSUE TITLE
Transcode enchange request for x265

### ISSUE THREAD

**Issue by Jorman** [clinton-hall/nzbToMedia#745]
Hi with the new hevc coded there is a problem with the files that use the new codec, but many hw can't reproduce them well!

So the idea is:
If codec is hevc (mediainfo --Inform="Video;%Format%") convert it to h264, only the codec change, resolution, audio, extension, etc etc, remain the same or if one want to change some value specify the new value, obviously with a low nice priority, one file by one

What do you think about it?

**Comment by kingmotley** [comment]
Can we have the opposite?  If it's not hevc, then transcode the video otherwise just bitcopy it?
