### ISSUE TITLE
ImportError: No module named nzbtomedia

### ISSUE THREAD

**Issue by marthiel** [clinton-hall/nzbToMedia#746]
Hey guys,

I followed the Instrustions in the wiki, but i get this error when running any of scripts through sabnzb or manually with ./nzbToCouchPotato.py

I use python 2.7.6 and also did the sym-link

Any idea what's going on??

 Traceback (most recent call last):
  File ".sickrage/autoProcessTV/nzbToCouchPotato.py", line 246, in <module>
    import nzbToMedia
  File ".sickrage/autoProcessTV/nzbToMedia.py", line 503, in <module>
    import nzbtomedia
ImportError: No module named nzbtomedia

**Comment by clinton-hall** [comment]
#744 
This appears to be a case insensitive Python environment.
As per the post linked above, a simple rename will fix this. I'll try and fix permanently when I get time.

**Comment by clinton-hall** [comment]
try the latest nightly branch.
