### ISSUE TITLE
NzbtoSickbeard error under OpenElec 5.0.8

### ISSUE THREAD

**Issue by Freakadude** [clinton-hall/nzbToMedia#750]
Hi There,

I have recently moved Nzbget from my NAS to my Cubox-i 4 Pro running OpenElec 5.0.8. Everything is fine except that most of my ppscripts such az nzbtomedia e.g.: nzbtosickbeard are failing on PP. I had no such issue on my NAS setup as everything works fine there.

Not sure what the exact issue is but based on the log and some forum digging i believe it may be related to OpenElec developers having removed distutils.util for some reason. And since i think the srcipts would be using this it is causing this issue. Also other PP scripts are failing also (e.g.: Deletesamples, CFP. etc) but i am not sure if for the same reasons

Below is an example from my log:
ERROR	Tue Apr 28 2015 23:12:14	Post-process-script nzbToMedia/nzbToSickBeard.py for Bates.Motel.S03E07.1080p.WEB-DL.DD5.1.H.264-KiNGS failed (terminated with unknown status)
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: IndentationError: unexpected indent
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: ^
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: if sys.platform == "darwin" and not plat.startswith('macosx-'):
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: File "/storage/nzbget/scripts/nzbToMedia/libs/pkg_resources.py", line 218
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: import pkg_resources
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: File "/storage/nzbget/scripts/nzbToMedia/libs/guessit/__init__.py", line 23, in <module>
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: import guessit
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: File "/storage/nzbget/scripts/nzbToMedia/nzbtomedia/nzbToMediaUtil.py", line 11, in <module>
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: from nzbtomedia.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: File "/storage/nzbget/scripts/nzbToMedia/nzbtomedia/autoProcess/autoProcessComics.py", line 6, in <module>
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: from nzbtomedia.autoProcess.autoProcessComics import autoProcessComics
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: File "/storage/nzbget/scripts/nzbToMedia/nzbtomedia/__init__.py", line 28, in <module>
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: import nzbtomedia
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: File "/storage/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 503, in <module>
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: import nzbToMedia
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: File "/storage/nzbget/scripts/nzbToMedia/nzbToSickBeard.py", line 254, in <module>
INFO	Tue Apr 28 2015 23:12:14	nzbToSickBeard: Traceback (most recent call last):
INFO	Tue Apr 28 2015 23:12:13	Executing post-process-script nzbToMedia/nzbToSickBeard.py for Bates.Motel.S03E07.1080p.WEB-DL.DD5.1.H.264-KiNGS

Any advice or help how i could fix this would be most appriciated!

Thank you!

**Comment by Freakadude** [comment]
Nevermind. Issue is solved thanks to forum help.

**Comment by clinton-hall** [comment]
glad to hear it is solved.
