### ISSUE TITLE
Postprocess api

### ISSUE THREAD

**Issue by Hellowlol** [clinton-hall/nzbToMedia#751]
Both sb and sr can use the api to initialize post process.

**Comment by clinton-hall** [comment]
they both have api, but last I checked there was no api call to actually do postprocessing.

can you provide any links/docs to show that these do now support this?
keep in mind, we need to be able to pass: directory, passed/failed, force, method etc.

**Comment by Hellowlol** [comment]
https://github.com/midgetspy/Sick-Beard/commit/7cfff7f0fa69946d37be8762b71b88ac60f10505, 
https://github.com/Hellowlol/SickRage/blob/master/sickbeard/webapi.py#L1361

**Comment by clinton-hall** [comment]
Hmmm... Looks like "failed" needs a second call? But regular PostProcessing should be possible via api.

I'll put this on my to-do list.

**Comment by Hellowlol** [comment]
I have no idea how it handles failed. I just added it since i something download stuff manually and needed it to htpc-manager.

**Comment by Hellowlol** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1536
