### ISSUE TITLE
nzbtomedia script failing?

### ISSUE THREAD

**Issue by ikkeenjij36** [clinton-hall/nzbToMedia#754]
Hi  tried to find the solution here and on google but can't figure out what is going wrong.
I pp my files first by another script and after that nzbToMedia get's called.
When i heve the blank script in it still goes wrong and gettint this as result back,just want to know where it goes wrong and how i can solve this,i am running it on synology with sabnzbd.
[code][INFO] Running: /volume1/downloads/scripts/nzbToMedia/nzbToMedia.py
[INFO] Success : /volume1/downloads/scripts/nzbToMedia/nzbToMedia.py
[10:45:21] [INFO]::MAIN: Loading config from [/volume1/downloads/scripts/nzbToMedia/autoProcessMedia.cfg]
Traceback (most recent call last):
  File "/volume1/downloads/scripts/nzbToMedia/nzbToMedia.py", line 794, in <module>
    exit(main(sys.argv))
  File "/volume1/downloads/scripts/nzbToMedia/nzbToMedia.py", line 624, in main
    nzbtomedia.initialize(section)
  File "/volume1/downloads/scripts/nzbToMedia/nzbtomedia/__init__.py", line 273, in initialize
    LOG_ENV = int(CFG['General']['log_env'])
ValueError: invalid literal for int() with base 10: ''
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <nzbtomedia.nzbToMediaUtil.PosixProcess instance at 0x7f54087d0cb0>> ignored[/code]
Any help will be great.

**Comment by clinton-hall** [comment]
in /volume1/downloads/scripts/nzbToMedia/autoProcessMedia.cfg

```
[General]
    log_env = 0
```

make sure log_env is set to either 0, or 1. this can't be anything else.
