### ISSUE TITLE
Unable to migrate autoProcessMedia.cfg 

### ISSUE THREAD

**Issue by gutrenchladd** [clinton-hall/nzbToMedia#755]
my log file is just line after line of 
> 2015-05-10 14:27:03 ERROR   ::MAIN: Unable to migrate config file >C:\Users\Administrator\Documents\autoProcessMedia.cfg, exiting ...

I have double triple and quadruple checked my setting (yes all categories have names).. i have deleted and allowed the system to remake the cfg file. i have double checked permissions as well. im genuinely at a loss for what to do next. running on win server 2012 r2. Unlike some with similar errors my script has never run a single time successfully

**Comment by clinton-hall** [comment]
what downloader do you use?

can you send me a copy of C:\Users\Administrator\Documents\autoProcessMedia.cfg
just send to my email address as linked on my github profile.

**Comment by gutrenchladd** [comment]
i use nzbget specifically i am using only the nzbget script not the all encompassing one. email incoming.

**Comment by clinton-hall** [comment]
were there any log entries before the line logged above?
That .cfg loads fine for me.

**Comment by gutrenchladd** [comment]
none that i could see at all... i think its just a permission error or my own ignorance with server 2012... ill do my best to find a fix this weekend if possible and update here.. setting python and nzbget to "run as admin" in properties didnt seem to change anything.

**Comment by clinton-hall** [comment]
any update?

**Comment by gutrenchladd** [comment]
Feel free to re close this. Sorry for lack of answer. i have since switched my OS to Windows 8. Server was just giving me errors abound.
