### ISSUE TITLE
nzbToCouchPotato keeps getting stuck at 'movie.searcher.try_next'

### ISSUE THREAD

**Issue by MrAdam** [clinton-hall/nzbToMedia#756]
The last couple of months I have had a problem where the nzbToCouchPotato script keeps getting stuck at the 'movie.searcher.try_next' step, after a release was downloaded unsuccessfully.
If I restart nzbget and do the post-processing again, it works - but it gets stuck again at some point when downloading another release.

```
nzbToCouchPotato: [13:11:17] [DEBUG]::COUCHPOTATO: Opening URL: http://localhost:5050/api/[API KEY REMOVED]/movie.searcher.try_next
```

**Comment by clinton-hall** [comment]
Thanks for reporting. I'll try and look into this soon.
