### ISSUE TITLE
[BUG] Download failed (terminated with unknown status)

### ISSUE THREAD

**Issue by imran0** [clinton-hall/nzbToMedia#757]
I am getting error once file is downloaded, the post-processing fails.

Kind	Time	Text
INFO	Wed May 13 2015 20:34:30	Collection lowkey.2015.limited.1080p.bluray.x264-amiable added to history
INFO	Wed May 13 2015 20:34:30	Unpausing download after post-process-script
ERROR	Wed May 13 2015 20:34:29	Post-process-script nzbToMedia/nzbToCouchPotato.py for lowkey.2015.limited.1080p.bluray.x264-amiable failed (terminated with unknown status)
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <nzbtomedia.nzbToMediaUtil.PosixProcess instance at 0x415b9508>> ignored
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: ValueError: No JSON object could be decoded
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: raise ValueError("No JSON object could be decoded")
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: File "/usr/local/python/lib/python2.7/json/decoder.py", line 384, in raw_decode
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: File "/usr/local/python/lib/python2.7/json/decoder.py", line 366, in decode
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: return _default_decoder.decode(s)
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: File "/usr/local/python/lib/python2.7/json/__init__.py", line 338, in loads
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: return json.loads(self.text, **kwargs)
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/libs/requests/models.py", line 799, in json
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: result = r.json()
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbtomedia/autoProcess/autoProcessMovie.py", line 242, in process
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: inputCategory, failureLink)
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 595, in process
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: failureLink=failureLink)
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 696, in main
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: result = nzbToMedia.main(sys.argv, section)
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: File "/usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToCouchPotato.py", line 249, in <module>
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: Traceback (most recent call last):
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: [20:34:29] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: [20:34:29] [ERROR]::MAIN: Wrong API key used
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: [20:34:29] [ERROR]::MAIN: CouchPotato returned the following non-json data
INFO	Wed May 13 2015 20:34:29	nzbToCouchPotato: [20:34:29] [WARNING]::MAIN: Unable to find a imdbID for lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Wed May 13 2015 20:34:23	nzbToCouchPotato: [20:34:23] [INFO]::MAIN: Searching IMDB for imdbID ...
INFO	Wed May 13 2015 20:34:23	nzbToCouchPotato: [20:34:23] [INFO]::MAIN: Searching folder and file names for imdbID ...
INFO	Wed May 13 2015 20:34:23	nzbToCouchPotato: [20:34:23] [INFO]::MAIN: Attemping imdbID lookup for lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Wed May 13 2015 20:34:23	nzbToCouchPotato: [20:34:23] [INFO]::MAIN: Calling CouchPotato:Movies to post-process:lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Wed May 13 2015 20:34:23	nzbToCouchPotato: [20:34:23] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
INFO	Wed May 13 2015 20:34:23	nzbToCouchPotato: [20:34:23] [INFO]::MAIN: Script triggered from NZBGet Version 14.2.
INFO	Wed May 13 2015 20:34:23	nzbToCouchPotato: [20:34:23] [INFO]::MAIN: #########################################################
INFO	Wed May 13 2015 20:34:23	nzbToCouchPotato: [20:34:23] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
INFO	Wed May 13 2015 20:34:23	nzbToCouchPotato: [20:34:23] [INFO]::MAIN: #########################################################
INFO	Wed May 13 2015 20:34:23	nzbToCouchPotato: [20:34:23] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
INFO	Wed May 13 2015 20:34:23	nzbToCouchPotato: [20:34:23] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
INFO	Wed May 13 2015 20:34:23	nzbToCouchPotato: [20:34:23] [INFO]::MAIN: nzbToMedia Version:77da142216ba6dc91bb654635d4bd03f13c881e5 Branch:master (Linux 2.6.32.12)
INFO	Wed May 13 2015 20:34:23	nzbToCouchPotato: [20:34:23] [INFO]::MAIN: No update needed
INFO	Wed May 13 2015 20:34:22	nzbToCouchPotato: InsecureRequestWarning)
INFO	Wed May 13 2015 20:34:22	nzbToCouchPotato: /volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/libs/requests/packages/urllib3/connectionpool.py:747: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
INFO	Wed May 13 2015 20:34:22	nzbToCouchPotato: [20:34:22] [INFO]::MAIN: Checking if source needs an update
INFO	Wed May 13 2015 20:34:22	nzbToCouchPotato: [20:34:22] [INFO]::MAIN: Checking database structure...
INFO	Wed May 13 2015 20:34:15	nzbToCouchPotato: nzbget.conf(701): Option "ResetLog" is obsolete, ignored, use "WriteLog" instead
INFO	Wed May 13 2015 20:34:15	Executing post-process-script nzbToMedia/nzbToCouchPotato.py for lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Wed May 13 2015 20:34:15	Nothing to cleanup for lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Wed May 13 2015 20:34:15	Cleaning up lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Wed May 13 2015 20:34:15	Pausing download before cleanup
INFO	Wed May 13 2015 20:34:15	Queueing lowkey.2015.limited.1080p.bluray.x264-amiable for post-processing
INFO	Wed May 13 2015 20:34:15	lowkey.2015.limited.1080p.bluray.x264-amiable returned from history back to download queue

**Comment by clinton-hall** [comment]
can you enable debug logging in 
/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/autoPrcoessMedia.cfg 
```
[General]
    log_debug = 1
```
Then postprocess again?

Also, in NZBGet, settings, nzbToCouchPotato.py please make sure you have the correct host, port and apikey enabled for CouchPotato.

**Comment by imran0** [comment]
I updated the file, reloaded nzbget and post-processed again...

Looks like the same error logs to me.

INFO	Thu May 14 2015 21:31:53	Collection lowkey.2015.limited.1080p.bluray.x264-amiable added to history
INFO	Thu May 14 2015 21:31:53	Unpausing download after post-process-script
ERROR	Thu May 14 2015 21:31:53	Post-process-script nzbToMedia/nzbToCouchPotato.py for lowkey.2015.limited.1080p.bluray.x264-amiable failed (terminated with unknown status)
INFO	Thu May 14 2015 21:31:53	nzbToCouchPotato: Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <nzbtomedia.nzbToMediaUtil.PosixProcess instance at 0x415b9508>> ignored
INFO	Thu May 14 2015 21:31:53	nzbToCouchPotato: ValueError: No JSON object could be decoded
INFO	Thu May 14 2015 21:31:53	nzbToCouchPotato: raise ValueError("No JSON object could be decoded")
INFO	Thu May 14 2015 21:31:53	nzbToCouchPotato: File "/usr/local/python/lib/python2.7/json/decoder.py", line 384, in raw_decode
INFO	Thu May 14 2015 21:31:53	nzbToCouchPotato: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
INFO	Thu May 14 2015 21:31:53	nzbToCouchPotato: File "/usr/local/python/lib/python2.7/json/decoder.py", line 366, in decode
INFO	Thu May 14 2015 21:31:53	nzbToCouchPotato: return _default_decoder.decode(s)
INFO	Thu May 14 2015 21:31:53	nzbToCouchPotato: File "/usr/local/python/lib/python2.7/json/__init__.py", line 338, in loads
INFO	Thu May 14 2015 21:31:53	nzbToCouchPotato: return json.loads(self.text, **kwargs)
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/libs/requests/models.py", line 799, in json
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: result = r.json()
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbtomedia/autoProcess/autoProcessMovie.py", line 242, in process
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: inputCategory, failureLink)
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 595, in process
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: failureLink=failureLink)
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 696, in main
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: result = nzbToMedia.main(sys.argv, section)
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: File "/usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToCouchPotato.py", line 249, in <module>
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: Traceback (most recent call last):
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: [21:31:52] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: [21:31:52] [DEBUG]::COUCHPOTATO: Opening URL: http://localhost:5050/api//renamer.scan with PARAMS: {'download_id': 'e53a3283b88ac31206da02511a2b112f', 'media_folder': '/volume1/Downloads/Completed/Movies/lowkey.2015.limited.1080p.bluray.x264-amiable', 'downloader': 'nzbget'}
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: [21:31:52] [ERROR]::MAIN: Wrong API key used
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: [21:31:52] [ERROR]::MAIN: CouchPotato returned the following non-json data
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: [21:31:52] [DEBUG]::MAIN: Opening URL: http://localhost:5050/api//media.list with PARAMS: {}
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: [21:31:52] [WARNING]::MAIN: Unable to find a imdbID for lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Thu May 14 2015 21:31:52	nzbToCouchPotato: [21:31:52] [DEBUG]::MAIN: Opening URL: http://www.omdbapi.com
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [INFO]::MAIN: Searching IMDB for imdbID ...
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [INFO]::MAIN: Searching folder and file names for imdbID ...
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [INFO]::MAIN: Attemping imdbID lookup for lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [INFO]::MAIN: Calling CouchPotato:Movies to post-process:lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [DEBUG]::MAIN: Adding NZB download info for directory /volume1/Downloads/Completed/Movies/lowkey.2015.limited.1080p.bluray.x264-amiable to database
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [INFO]::MAIN: Script triggered from NZBGet Version 14.2.
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToCouchPotato.py']
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [INFO]::MAIN: #########################################################
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [INFO]::MAIN: #########################################################
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [INFO]::MAIN: nzbToMedia Version:77da142216ba6dc91bb654635d4bd03f13c881e5 Branch:master (Linux 2.6.32.12)
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [INFO]::MAIN: No update needed
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: [21:31:46] [DEBUG]::MAIN: cur_commit = 77da142216ba6dc91bb654635d4bd03f13c881e5 % (newest_commit)= 77da142216ba6dc91bb654635d4bd03f13c881e5, num_commits_behind = 0
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: InsecureRequestWarning)
INFO	Thu May 14 2015 21:31:46	nzbToCouchPotato: /volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/libs/requests/packages/urllib3/connectionpool.py:747: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
INFO	Thu May 14 2015 21:31:45	nzbToCouchPotato: [21:31:45] [INFO]::MAIN: Checking if source needs an update
INFO	Thu May 14 2015 21:31:45	nzbToCouchPotato: [21:31:45] [DEBUG]::MAIN: InitialSchema upgrade not required
INFO	Thu May 14 2015 21:31:45	nzbToCouchPotato: [21:31:45] [DEBUG]::MAIN: Checking Initial Schema database upgrade
INFO	Thu May 14 2015 21:31:45	nzbToCouchPotato: [21:31:45] [INFO]::MAIN: Checking database structure...
INFO	Thu May 14 2015 21:31:37	nzbToCouchPotato: nzbget.conf(701): Option "ResetLog" is obsolete, ignored, use "WriteLog" instead
INFO	Thu May 14 2015 21:31:37	Executing post-process-script nzbToMedia/nzbToCouchPotato.py for lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Thu May 14 2015 21:31:37	Nothing to cleanup for lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Thu May 14 2015 21:31:37	Cleaning up lowkey.2015.limited.1080p.bluray.x264-amiable
INFO	Thu May 14 2015 21:31:37	Pausing download before cleanup
INFO	Thu May 14 2015 21:31:37	Queueing lowkey.2015.limited.1080p.bluray.x264-amiable for post-processing
INFO	Thu May 14 2015 21:31:37	lowkey.2015.limited.1080p.bluray.x264-amiable returned from history back to download queue
INFO	Thu May 14 2015 21:31:27	nzbget 14.2 daemon-mode

**Comment by clinton-hall** [comment]
This shows that you have not entered your CouchPotato api key in NZBGet, settings, NZBTOCOUCHPOTATO, cpsapikey

**Comment by imran0** [comment]
You are correct, my mistake I have updated this now and rerun the post-processing. Unfortunately I'm still getting issues:

INFO	Sat May 16 2015 15:30:01	Collection plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1 added to history
INFO	Sat May 16 2015 15:30:01	Unpausing download after post-process-script
ERROR	Sat May 16 2015 15:30:01	Post-process-script nzbToMedia/nzbToCouchPotato.py for plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1 failed
INFO	Sat May 16 2015 15:30:00	nzbToCouchPotato: CouchPotato: Failed to post-process - No change in status!
INFO	Sat May 16 2015 15:30:00	nzbToCouchPotato: [15:30:00] [ERROR]::MAIN: A problem was reported in the /usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToCouchPotato.py script.
INFO	Sat May 16 2015 15:30:00	nzbToCouchPotato: [15:30:00] [WARNING]::COUCHPOTATO: plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1 does not appear to have changed status after 2 minutes, Please check your logs.
INFO	Sat May 16 2015 15:29:40	nzbToCouchPotato: [15:29:40] [DEBUG]::MAIN: Opening URL: http://localhost:5050/api/319172500d4a4382b90e948080dd691c/media.get with PARAMS: {'id': u'f4dd043ab0ff489c9dab31c25bcab126'}
INFO	Sat May 16 2015 15:29:40	nzbToCouchPotato: [15:29:40] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
INFO	Sat May 16 2015 15:29:20	nzbToCouchPotato: [15:29:20] [DEBUG]::MAIN: Opening URL: http://localhost:5050/api/319172500d4a4382b90e948080dd691c/media.get with PARAMS: {'id': u'f4dd043ab0ff489c9dab31c25bcab126'}
INFO	Sat May 16 2015 15:29:20	nzbToCouchPotato: [15:29:20] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
INFO	Sat May 16 2015 15:29:00	nzbToCouchPotato: [15:29:00] [DEBUG]::MAIN: Opening URL: http://localhost:5050/api/319172500d4a4382b90e948080dd691c/media.get with PARAMS: {'id': u'f4dd043ab0ff489c9dab31c25bcab126'}
INFO	Sat May 16 2015 15:29:00	nzbToCouchPotato: [15:29:00] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
INFO	Sat May 16 2015 15:28:40	nzbToCouchPotato: [15:28:40] [DEBUG]::MAIN: Opening URL: http://localhost:5050/api/319172500d4a4382b90e948080dd691c/media.get with PARAMS: {'id': u'f4dd043ab0ff489c9dab31c25bcab126'}
INFO	Sat May 16 2015 15:28:40	nzbToCouchPotato: [15:28:40] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
INFO	Sat May 16 2015 15:28:20	nzbToCouchPotato: [15:28:20] [DEBUG]::MAIN: Opening URL: http://localhost:5050/api/319172500d4a4382b90e948080dd691c/media.get with PARAMS: {'id': u'f4dd043ab0ff489c9dab31c25bcab126'}
INFO	Sat May 16 2015 15:28:20	nzbToCouchPotato: [15:28:20] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
INFO	Sat May 16 2015 15:28:00	nzbToCouchPotato: [15:28:00] [DEBUG]::MAIN: Opening URL: http://localhost:5050/api/319172500d4a4382b90e948080dd691c/media.get with PARAMS: {'id': u'f4dd043ab0ff489c9dab31c25bcab126'}
INFO	Sat May 16 2015 15:28:00	nzbToCouchPotato: [15:28:00] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
INFO	Sat May 16 2015 15:28:00	nzbToCouchPotato: [15:28:00] [POSTPROCESS]::COUCHPOTATO: SUCCESS: Finished renamer scan for folder /volume1/Downloads/Completed/Movies/plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1
INFO	Sat May 16 2015 15:28:00	nzbToCouchPotato: [15:28:00] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1
INFO	Sat May 16 2015 15:28:00	nzbToCouchPotato: [15:28:00] [DEBUG]::COUCHPOTATO: Opening URL: http://localhost:5050/api/319172500d4a4382b90e948080dd691c/renamer.scan with PARAMS: {'download_id': u'fd63672df1ad923b351367ebd7c5977b', 'media_folder': '/volume1/Downloads/Completed/Movies/plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1', 'downloader': u'NZBGet'}
INFO	Sat May 16 2015 15:27:59	nzbToCouchPotato: [15:27:59] [DEBUG]::MAIN: Opening URL: http://localhost:5050/api/319172500d4a4382b90e948080dd691c/media.list with PARAMS: {}
INFO	Sat May 16 2015 15:27:59	nzbToCouchPotato: [15:27:59] [WARNING]::MAIN: Unable to find a imdbID for plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1
INFO	Sat May 16 2015 15:27:56	nzbToCouchPotato: [15:27:56] [DEBUG]::MAIN: Opening URL: http://www.omdbapi.com
INFO	Sat May 16 2015 15:27:50	nzbToCouchPotato: [15:27:50] [INFO]::MAIN: Searching IMDB for imdbID ...
INFO	Sat May 16 2015 15:27:50	nzbToCouchPotato: [15:27:50] [INFO]::MAIN: Searching folder and file names for imdbID ...
INFO	Sat May 16 2015 15:27:50	nzbToCouchPotato: [15:27:50] [INFO]::MAIN: Attemping imdbID lookup for plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1
INFO	Sat May 16 2015 15:27:50	nzbToCouchPotato: [15:27:50] [INFO]::MAIN: Calling CouchPotato:Movies to post-process:plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1
INFO	Sat May 16 2015 15:27:50	nzbToCouchPotato: [15:27:50] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
INFO	Sat May 16 2015 15:27:50	nzbToCouchPotato: [15:27:50] [DEBUG]::MAIN: Adding NZB download info for directory /volume1/Downloads/Completed/Movies/plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1 to database
INFO	Sat May 16 2015 15:27:50	nzbToCouchPotato: [15:27:50] [INFO]::MAIN: Script triggered from NZBGet Version 14.2.
INFO	Sat May 16 2015 15:27:50	nzbToCouchPotato: [15:27:50] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToCouchPotato.py']
INFO	Sat May 16 2015 15:27:50	nzbToCouchPotato: [15:27:50] [INFO]::MAIN: #########################################################
INFO	Sat May 16 2015 15:27:50	nzbToCouchPotato: [15:27:50] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
INFO	Sat May 16 2015 15:27:50	nzbToCouchPotato: [15:27:50] [INFO]::MAIN: #########################################################
INFO	Sat May 16 2015 15:27:50	nzbToCouchPotato: [15:27:50] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
INFO	Sat May 16 2015 15:27:50	nzbToCouchPotato: [15:27:50] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
INFO	Sat May 16 2015 15:27:49	nzbToCouchPotato: [15:27:49] [INFO]::MAIN: nzbToMedia Version:77da142216ba6dc91bb654635d4bd03f13c881e5 Branch:master (Linux 2.6.32.12)
INFO	Sat May 16 2015 15:27:49	nzbToCouchPotato: [15:27:49] [INFO]::MAIN: No update needed
INFO	Sat May 16 2015 15:27:49	nzbToCouchPotato: [15:27:49] [DEBUG]::MAIN: cur_commit = 77da142216ba6dc91bb654635d4bd03f13c881e5 % (newest_commit)= 77da142216ba6dc91bb654635d4bd03f13c881e5, num_commits_behind = 0
INFO	Sat May 16 2015 15:27:49	nzbToCouchPotato: InsecureRequestWarning)
INFO	Sat May 16 2015 15:27:49	nzbToCouchPotato: /volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/libs/requests/packages/urllib3/connectionpool.py:747: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
INFO	Sat May 16 2015 15:27:49	nzbToCouchPotato: [15:27:49] [INFO]::MAIN: Checking if source needs an update
INFO	Sat May 16 2015 15:27:49	nzbToCouchPotato: [15:27:49] [DEBUG]::MAIN: InitialSchema upgrade not required
INFO	Sat May 16 2015 15:27:49	nzbToCouchPotato: [15:27:49] [DEBUG]::MAIN: Checking Initial Schema database upgrade
INFO	Sat May 16 2015 15:27:49	nzbToCouchPotato: [15:27:49] [INFO]::MAIN: Checking database structure...
INFO	Sat May 16 2015 15:27:40	nzbToCouchPotato: nzbget.conf(701): Option "ResetLog" is obsolete, ignored, use "WriteLog" instead
INFO	Sat May 16 2015 15:27:40	Executing post-process-script nzbToMedia/nzbToCouchPotato.py for plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1
INFO	Sat May 16 2015 15:27:40	Nothing to cleanup for plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1
INFO	Sat May 16 2015 15:27:40	Cleaning up plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1
INFO	Sat May 16 2015 15:27:40	Pausing download before cleanup
INFO	Sat May 16 2015 15:27:40	Queueing plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1 for post-processing
INFO	Sat May 16 2015 15:27:40	plastic plastic 2014 1080p bluray dts x264 cytsunee nfo yenc 1 1 returned from history back to download queue
INFO	Sat May 16 2015 15:27:29	nzbget 14.2 daemon-mode

**Comment by clinton-hall** [comment]
this was a manually downloaded movie?
Looks like an issue where it uses the wrong movie for CouchPotato... this should have been fixed, but might only be in dev, or nightly.

**Comment by clinton-hall** [comment]
can you please switch to nightly to test?

**Comment by imran0** [comment]
This was sent from CP to NZBGet, however it failed a few days ago, I simply pressed Post-process again after setting the debug log to 1 and adding the CP API key into NZBGet settings.

If you can show me how to do it, I will lol

**Comment by clinton-hall** [comment]
what is the status of this in CouchPotato? Is it in the manage list?

Try some new downloads and see what happens. No need to go to testing as that would only apply to a manually downloaded show.

**Comment by imran0** [comment]
Strangely they are visible in the Manage list, despite failing in NZBGet post-process. The files are also still sitting in NZBGets generic Completed folder instead of the Rename files location elsewhere.

I've started a new download now and will report back with the results.
