### ISSUE TITLE
Custom transmission RPC url

### ISSUE THREAD

**Issue by Madseason41** [clinton-hall/nzbToMedia#760]
Is there a way to use a custom transmission rcp-url? Maybe put it after the port such has 9091/xmsn?

I use /xmsn/ as my custom rpc and don't seem a setting in the autoconfig file.

Thanks,

**Comment by clinton-hall** [comment]
https://github.com/clinton-hall/nzbToMedia/blob/master/nzbtomedia/transmissionrpc/client.py#L145
This comes direct from the external Transmissionrpc module that I included.

I could parse a custom rpc... will need to investigate.

If you edit the line above, test and let me know I'd like to know if changing this does indeed work.
