### ISSUE TITLE
Script is not executing in DSM 5.2

### ISSUE THREAD

**Issue by trashhead** [clinton-hall/nzbToMedia#761]
Script doesn't get executed in DSM 5.2 :/

**Comment by clinton-hall** [comment]
I have no means to test...
Anything in logs to show what is going on?

**Comment by ketjap** [comment]
I'm also running DSM 5.2 and with me it's working fine.

**Comment by baz1860** [comment]
I can confirm that the scripts (nzbtonzbdrone, nzbtocouchpotato and nzbtomylar) run as expected on my Synology Ds415+ running DSM 5.2
