### ISSUE TITLE
nzbtosickbeard failing with Sickrage

### ISSUE THREAD

**Issue by mouseman85** [clinton-hall/nzbToMedia#762]
Hi keep getting a script failure using nzbtosickbeard, with NzbGetSickrage and Couch Potato. This was the main error I found in the NZbget logs:

My config file is still called: 

autoProcessMedia.cfg.spec

Do i need to rename that to just .cfg? I amended all settings using the NZBGet WebUI. 

The error I found in the NZbget logs:
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard: Traceback (most recent call last):
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:   File "/storage/.kodi/addons/script.module.audo-programs/resources/nzbget/scripts/nzbToMedia/nzbToSickBeard.py", line 254, in <module>
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:     import nzbToMedia
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:   File "/storage/.kodi/addons/script.module.audo-programs/resources/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 503, in <module>
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:     import nzbtomedia
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:   File "/storage/.kodi/addons/script.module.audo-programs/resources/nzbget/scripts/nzbToMedia/nzbtomedia/**init**.py", line 28, in <module>
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:     from nzbtomedia.autoProcess.autoProcessComics import autoProcessComics
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:   File "/storage/.kodi/addons/script.module.audo-programs/resources/nzbget/scripts/nzbToMedia/nzbtomedia/autoProcess/autoProcessComics.py", line 6, in <module>
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:     from nzbtomedia.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:   File "/storage/.kodi/addons/script.module.audo-programs/resources/nzbget/scripts/nzbToMedia/nzbtomedia/nzbToMediaUtil.py", line 11, in <module>
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:     import guessit
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:   File "/storage/.kodi/addons/script.module.audo-programs/resources/nzbget/scripts/nzbToMedia/libs/guessit/**init**.py", line 23, in <module>
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:     import pkg_resources
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:   File "/storage/.kodi/addons/script.module.audo-programs/resources/nzbget/scripts/nzbToMedia/libs/pkg_resources.py", line 692, in <module>
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:     class Environment(object):
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:   File "/storage/.kodi/addons/script.module.audo-programs/resources/nzbget/scripts/nzbToMedia/libs/pkg_resources.py", line 695, in Environment
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:     def **init**(self, search_path=None, platform=get_supported_platform(), python=PY_MAJOR):
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:   File "/storage/.kodi/addons/script.module.audo-programs/resources/nzbget/scripts/nzbToMedia/libs/pkg_resources.py", line 90, in get_supported_platform
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:     plat = get_build_platform(); m = macosVersionString.match(plat)
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:   File "/storage/.kodi/addons/script.module.audo-programs/resources/nzbget/scripts/nzbToMedia/libs/pkg_resources.py", line 215, in get_build_platform
Thu May 21 18:46:33 2015    INFO    nzbToSickBeard:     from distutils.util import get_platform

**Comment by clinton-hall** [comment]
what system is this running on? 
The error seems to be an unknown system name?

**Comment by mouseman85** [comment]
Hi Clinton,

It's running on Raspberry Pi 2, with Kodi, i've fixed the nzbtosickbeard
issue, it was a wrong port number, but i am having an issues with
transmission, its not sending any info to SickRage on a completed download,
i've follwed the guides but not sure with which autoprocess.cfg i should be
editing as i only have one that is labelled .cfg.spec.

Thanks for the reply

**Comment by clinton-hall** [comment]
Copy autoProcessMedia.cfg.spec to autoProcessMedia.cfg then edit that.
