### ISSUE TITLE
Postprocessing of big files fails.

### ISSUE THREAD

**Issue by FlyingPersian** [clinton-hall/nzbToMedia#765]
Hi
It happens to me quite a lot that the post processing of movies (HD) fails and it's related to nzbToMedia. My client is rtorrent and it executes nzbToMedia on complete. When I disable the script-execution on complete the rars are fine and I can unrar them normally. But when nzbToMedia is enabled and copies over the rars it fails to extract. Here the log of nzbToMedia:
http://pastebin.com/an6heHhW
 Strangely enough it worked just fine with three season packs I downloaded, each around 20GB. I usually have this issue with movies. 
AFAIk it copies the rars to a temp folder, extracts them there, deletes them and opens CP. At least that's the plan. But no .mkv is extracted due to some issue with the rars. Tried hard/symlinking, results in same. As far as I remember hard/symlinking even corrupted my rar files I downloaded when nzbToMedia was activated. A while back I couldn't even extract the downloaded rars manually. That's why I went with copyling. Any ideas how I could fix this?

**Comment by clinton-hall** [comment]
So what files are in the `/home/admin/rtorrent/downloads/processed/Movies/Chappie.2015.1080p.BluRay.x264-SPARKS` directory after the postprocess has finished?

perhaps this is a file size limitation on unrar for single files (TV packs are obviously many smaller files)?

**Comment by FlyingPersian** [comment]
Just the nfo, subs and cover pictures. Subs are what I extract manually also when I use symlinks instead of copylink. 
Yes true, just noticed that the season packs consist of folders with rars per episode.
It shouldn't be a limitation, extracting the movie does work when I go to the download folder when I run unrar manually.

**Comment by clinton-hall** [comment]
When you run unrar manually, are you using the same unrar binary that nzbget uses?

**Comment by FlyingPersian** [comment]
Well i hardly assume so as there is only "unrar" in the log, without any paths and I only have one unrar installed.

**Comment by clinton-hall** [comment]
What options do you pass manually?

`unrar x -o+ -y /home/admin/rtorrent/downloads/processed/Movies/Chappie.2015.1080p.BluRay.x264-SPARKS/chappie.2015.1080p.bluray.x264-sparks.rar /home/admin/rtorrent/downloads/processed/Movies/Chappie.2015.1080p.BluRay.x264-SPARKS`

is what nzbToMedia passed.

If this command works manually, then it must be an environment variable that is passed by your downloader,

**Comment by FlyingPersian** [comment]
I just tried it out again and for some weird reason the rars in the processed folder haven't been deleted. Here the log:

http://pastebin.com/U1tVWe01

I ran the same command  nzbToMedia runs manually and it worked fine, even as the user running rtorrent and thus nzbToMedia.

**Comment by clinton-hall** [comment]
What happens when you manually run the torrentToMedia script?

`/media/scripts/nzbToMedia/TorrentToMedia.py '/home/admin/rtorrent/downloads/Movies/Chappie.2015.1080p.BluRay.x264-SPARKS Chappie.2015.1080p.BluRay.x264-SPARKS' '' '344049EEBCE20ECDDFD34D66561427E64DA624EE'`

**Comment by FlyingPersian** [comment]
I ran this command.

 ./TorrentToMedia.py "/home/admin/rtorrent/downloads/Movies/Chappie.2015.1080p.BluRay.x264-SPARKS" "Chappie.2015.1080p.BluRay.x264-SPARKS" "Movies" "344049EEBCE20ECDDFD34D66561427E64DA624EE"

And it resulted in the exact same thing. No difference than before.

**Comment by FlyingPersian** [comment]
Hi.
It worked fine on a torrent that was mkv only. So no rars. It copied the files over to the temp folder and then opened CP.

**Comment by FlyingPersian** [comment]
This is strange:

http://pastebin.com/sEkn18zC

Look at the time stamps. It worked fine this time. I redownloadet nzb and recreated the autoProcessMedia.cfg. I first set it to hard linking and neither the extraction of the temp rars worked nor of the original downloaded rars. Setting it to copy link worked like a charm. Why is it starting to delete rars so quickly? Shouldn't it be waiting till the extract is done? I highly doubt the extract took 3s for 5,5GB..

**Comment by FlyingPersian** [comment]
I updated this to the newest version and it's still not working :/

**Comment by FlyingPersian** [comment]
I think I fixed it. I added *.rar files to the extensions a long time ago and now it's removed. Seems to be working now!
