### ISSUE TITLE
error code on failure

### ISSUE THREAD

**Issue by ugokanain** [clinton-hall/nzbToMedia#769]
Clinton

Now that sab does recognize the returned code by scripts, I found that nzbtomedia returns failure when it is unable to connect to the associated services (SR, CP, etc). 

It had gotten stuck while post processing a post and when I killed everything, it returned a -1 code. This caused all the post that NTM couldn't post process correctly (the services hadn't started yet) to be deleted.

Any chance for NTM to return 0 rather than -1, if the associated service isn't running?

**Comment by clinton-hall** [comment]
If Unable to connect to the service, this would return status `1` not `-1`

Can you show logs?

**Comment by ugokanain** [comment]
You are right. However, you might want to warn users not to turn "User script can flag job as failed" on for it NTM isn't able to talk to the services, it will tag the post as failed and sab will delete it.

**Comment by clinton-hall** [comment]
So that is an option in SABnzbd?
