### ISSUE TITLE
Config Migration Error

### ISSUE THREAD

**Issue by nextgenerd** [clinton-hall/nzbToMedia#770]
01:08:07    nzbToNzbDrone: AttributeError: 'module' object has no attribute 'PY2'
...............
01:38:31    nzbToNzbDrone: Traceback (most recent call last):
23:08:07] [ERROR]::MAIN: Unable to migrate config file C:\Program Files (x86)\nzbget-14.2\scripts\autoProcessMedia.cfg, exiting ..

These are the pertinent lines i saw in nzbget .

**Comment by clinton-hall** [comment]
the first is hard to know what this means without the context (please post the full log).
The second suggests you have an un-readable format/character on your autoProcessMedia.cfg. 

Did you edit the autoProcessMedia.cfg or just enter the values into the NZBGet web ui?

**Comment by gutrenchladd** [comment]
ERROR	Sun Jun 07 2015 01:45:20	Post-process-script nzbToNzbDrone.py for MythBusters.S15E01.Fire.in.the.Hole.720p.HDTV.x264-TERRA-NZBgeek failed (terminated with unknown status)
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: AttributeError: 'module' object has no attribute 'PY2'
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: if six.PY2 and isinstance(line, str):
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: File "C:\Program Files (x86)\nzbget-14.2\scripts\libs\configobj\configobj.py", line 1476, in _handle_bom
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: content = self._handle_bom(content)
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: File "C:\Program Files (x86)\nzbget-14.2\scripts\libs\configobj\configobj.py", line 1286, in _load
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: self._load(infile, configspec)
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: File "C:\Program Files (x86)\nzbget-14.2\scripts\libs\configobj\configobj.py", line 1228, in __init__
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: super(configobj.ConfigObj, self).__init__(*args, **kw)
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: File "C:\Program Files (x86)\nzbget-14.2\scripts\core\nzbToMediaConfig.py", line 86, in __init__
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: CFG_NEW = config()
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: File "C:\Program Files (x86)\nzbget-14.2\scripts\core\nzbToMediaConfig.py", line 244, in addnzbget
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: CFG = config.addnzbget()
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: File "C:\Program Files (x86)\nzbget-14.2\scripts\core\__init__.py", line 264, in initialize
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: core.initialize(section)
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: File "C:\Program Files (x86)\nzbget-14.2\scripts\nzbToMedia.py", line 624, in main
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: result = nzbToMedia.main(sys.argv, section)
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: File "C:\Program Files (x86)\nzbget-14.2\scripts\nzbToNzbDrone.py", line 236, in <module>
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: Traceback (most recent call last):
INFO	Sun Jun 07 2015 01:45:20	nzbToNzbDrone: [23:45:20] [ERROR]::MAIN: Unable to migrate config file C:\Program Files (x86)\nzbget-14.2\scripts\autoProcessMedia.cfg, exiting ...


full log above. just through the ui

**Comment by clinton-hall** [comment]
can you try editing
https://github.com/clinton-hall/nzbToMedia/blob/master/libs/configobj/configobj.py#L23

from
`import six`
to
`import libs.six as six`

then see if this runs?
It looks like this is using a different version of six to the one packaged in this repo.

**Comment by gutrenchladd** [comment]
line 23 of configobj.py is as follow 

import libs.six as six

still no change exact same error

**Comment by clinton-hall** [comment]
what version of python are you running?

**Comment by gutrenchladd** [comment]
python2.7

**Comment by clinton-hall** [comment]
Odd. I have tested on win 7, but don't have 8.1... I can't figure out what is going wrong here.
