### ISSUE TITLE
Only scond half of movies.

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#771]
Ive been noticing a recent batch randomly of movies where it shows it as complete but when i play the movie after postproc, only the second hald of the movie is present.

Since its random i havent found logs yet, but im still looking.

Has anyone noticed this behavior?

Also, is there a method to find movie files of less than feature length and flag/remove them? Its intermittent and frustrating me

**Comment by clinton-hall** [comment]
is this related to Transcoding going wrong (BUG)? or are you suggesting a new feature to catch these partial movies (Feature Request)?

**Comment by mgaulton** [comment]
Bit of both. I've added things like "cd1" "cd2" "part 1" "part 2" etc to my ignore list in couchpotato but they still seem to be getting through. I haven't been able to catch one in the act to see if its chopping it during transcoding.

**Comment by clinton-hall** [comment]
Make sure you enable debug logging, then post the PostProcessing log after this happens again, this should show what is happening.

**Comment by mgaulton** [comment]
I already enabled debugging. Just not sure how long it might take to catch
another one.

**Comment by mgaulton** [comment]
Funny enough, i came across one that was only the first half of the movie now. I discovered in the logs that it wasn't finding 7z or ffmpeg, thought both are installed, reinstalling them to try again but as always, it might take a big.

I do have concat turned on. I assume its concat then send to CP to postprocess?

**Comment by mgaulton** [comment]
Also, possibly related, would adding a "this file has already been processed, tell CP/SB etc it should be considered failed and move on with a default off option be possible? I have a py script that checks vid file length, if its until 60ish minutes, it gets nuked. I'm wondering if CP might just be reprocessing the same files over again.
