### ISSUE TITLE
Is the "From" option in CouchPotato renamer relevant at all?

### ISSUE THREAD

**Issue by rfgamaral** [clinton-hall/nzbToMedia#774]
(I see you have a `question` tag so I hope creating an issue for a question is not a problem.)

I have your scripts configured to work with NZBGet and Deluge for CouchPotato and all seems to be working. I believe this setup has made the `From` field (which is set to the `.process/couchpotato` folder described below) in the CouchPotato renamer irrelevant. Here's why...

My current folder structure is as follows:

```
Downloads/
├── Deluge
│   ├── completed
│   │   └── couchpotato
│   └── incomplete
├── .process
│   └── couchpotato
└── NZBGet
    ├── completed
    │   └── couchpotato
    └── intermediate
```

Basically, new files start to download to the `incomplete` and `intermediate` for Deluge and NZBGet, respectively. When a download finishes, the files will be moved to the `completed/couchpotato` folder (inside the respective the downloader folder parent).

Then, `TorrentToMedia.py` or `nzbToCouchPotato.py` will be executed and do their thing... Which, in this particular case involves calling CouchPotato's renamer. So far so good, everything is working just fine and my files are moved to the final output directory defined in the **`To`** field of CouchPotato's renamer.

I took a closer look at my `Downloads` directory (which includes incomplete and completed downloads) doing something like `for i in $(seq 1000); do tree; sleep 1; done` and noticed that the folder `.process/couchpotato` was empty all the time.

1. **How relevant the `From` field really is?**

2. **Maybe I could just set it to empty?**

**Comment by rfgamaral** [comment]
I just found out that this is not quite as I assumed... That field is still relevant and it cannot be empty.

I tried a download without setting the `From` field and the script could never finish, it would give me the following periodically:

> POSTPROCESS::COUCHPOTATO: Checking for status change, please stand by ...

However, like I said before, everything was working fine with a `Form` folder that was never used for anything. Downloads would always be moved from the `completed` folders to the final destination.

As such, I decided to revise my folder structure and completely removed the `completed` folders on both the NZBGet and Deluge folders.

I know have this:

```
Downloads/
├── Deluge
│   └── incomplete
├── .process
│   └── couchpotato
└── NZBGet
    └── intermediate
```
Files will be downloaded to the `incomplete` and `intermediate` folders, when finished, will be unpacked/moved to the `.process/couchpotato` folder and then the scripts will kick in and invoke CouchPotato's renamer, moving them from that folder o the final one.

Does everything I said makes sense? Is this a good setup or is there a problem I might be missing?

**Comment by clinton-hall** [comment]
yes. The From field must exist, but I recommend setting this to an empty directory to prevent any "regular" couchpotato scans from trying to process any files that are being downloaded/moved etc. The from field is in-fact ignored when using this script as we pass the directory to scan directly to CouchPotato's renamer.

your setup sounds spot on. That is the way I would do it (with the only difference being I would set from to an empty folder)

Does this make sense? Yes, I am more than happy for questions on here... hopefully this helps others too.

**Comment by rfgamaral** [comment]
Or I could simply leave as-is and set CouchPotato's `Run Every` and `Force Every` to `0`? Wouldn't that work too? Or do you recommend to at least set the `Force Every` for some reason?

Thanks for the clarification :)

**Comment by clinton-hall** [comment]
Correct, setting both to 0 will stop it running. Just be sure to restart CouchPotato after changing these settings.

**Comment by rfgamaral** [comment]
Thanks :)
