### ISSUE TITLE
Torrent_NoLink = 1 = Linking enabled or disabled.. confusing?

### ISSUE THREAD

**Issue by Mirabis** [clinton-hall/nzbToMedia#776]
If I set Torrent_NoLInk to 1 = is it enabled or disabled?

**Comment by clinton-hall** [comment]
setting `Torrent_NoLInk = 1` will prevent this category from using any linking/copying/moving and will leave the files in place for default application processing.

**Comment by Mirabis** [comment]
Okay thanks for explaining, I've edited the wiki page as well :)
