### ISSUE TITLE
[Request] Seperate transcoder duplicate/override setting for torrent  & usenet

### ISSUE THREAD

**Issue by Mirabis** [clinton-hall/nzbToMedia#778]
Hi,

For usenet post processing I have it overwrite the old file, but doing so with torrents causes errors with seeding :(  Any chance u could seperate it, so I can /duplicate for torrents and /overwrite for usenet downloads?

Kind Regards,

Mirabis

**Comment by clinton-hall** [comment]
possible... I am hoping to add more functionality into transcoder... just need the time...
