### ISSUE TITLE
Simple ffmpeg available when transcoding?

### ISSUE THREAD

**Issue by bensmeets** [clinton-hall/nzbToMedia#786]
Hi, thanks for all this. Quick question. I had a very old version running beautifully before. Just updated to the latest from git. I keep failing transcoding jobs, everytime a ffmpeg error with all kinds of parameters that are unrecognized.

Before, this wasn't really a problem. If I am correct, the older version used a much less sophisticated ffmpeg command. When I convert manually, I also use maybe 3 parameters tops. I don't need all the added functionality, just convert to m4v and aac.

Is there a way to "force" it to use a specific ffmpeg command (hard coded maybe?) that just uses variables for input/output names?

Cheers.

Just for kicks, a couple or random error ffmpeg gave me when using the generated commands:
```
Stream map '0:3' matches no streams.
Unrecognized option 'crf'.
Unrecognized option 'preset'.
Unable to find a suitable output format for 'libfdk_aac'
libfdk_aac: Invalid argument
Unable to find a suitable output format for '3.1'
3.1: Invalid argument
[NULL @ 0x26161a0] Unable to find a suitable output format for '19'
19: Invalid argument
```

**Comment by clinton-hall** [comment]
To achieve this, you need to set any "unwanted" variable to blank. if you want to ignore the various mapping and selection of tracks, you could remove ffprobe from the path so that this isn't called...

try:
```
[Transcoder]
    getSubs = 0
    subLanguages = 
    transcode = 1
    duplicate = 1
    concat = 1
    ignoreExtensions = .m4v
    outputFastStart = 0
    outputQualityPercent = 0
    outputVideoPath = 
    # processOutput. 1 will send the outputVideoPath to SickBeard/CouchPotato. 0 will send original files.
    processOutput = 0
    audioLanguage = 
    allAudioLanguages = 1
    allSubLanguages = 1
    embedSubs = 0
    burnInSubtitle = 0
    extractSubs = 0
    externalSubDir =
    hwAccel = 0
    generalOptions =
    outputDefault =
    #### Define custom settings below.
    outputVideoExtension = .m4v
    outputVideoCodec = libx264
    VideoCodecAllow = 
    outputVideoPreset =
    outputVideoResolution =
    outputVideoFramerate =
    outputVideoBitrate =
    outputVideoCRF =
    outputVideoLevel =
    outputAudioCodec = aac
    AudioCodecAllow = 
    outputAudioChannels = 
    outputAudioBitrate =
    outputAudioTrack2Codec =
    AudioCodec2Allow = 
    outputAudioTrack2Channels =  
    outputAudioTrack2Bitrate =
    outputAudioOtherCodec =
    AudioOtherCodecAllow = 
    outputAudioOtherChannels =
    outputAudioOtherBitrate =
    outputSubtitleCodec =
```

**Comment by bensmeets** [comment]
Thanks, that did the trick.

**Comment by clinton-hall** [comment]
Glad it is working for you.
