### ISSUE TITLE
Issues with Headphones transcoding from FLAC to MP3 from SABnzbd

### ISSUE THREAD

**Issue by KaraokeStu** [clinton-hall/nzbToMedia#789]
Hi,

At present, most downloads come down in FLAC format, however I'm always going to be streaming them, so I'm not too fussed about the quality.

Therefore, I'm converting them to MP3 using lame.

The server is a virtualised Xpenology install on a HP Microserver Gen8, but the transcode can take a few minutes, which goes over the 300 second timeout.

Is there any way to check if transcoding will happen and, if so, extend the timeout, or make the request asynchronous?

The log output is here:

```
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8084): Read timed out. (read timeout=300)
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x7f12eaf15680>> ignored
```

**Comment by KaraokeStu** [comment]
If it helps, an average processing time for a FLAC to MP3 conversion on this system is around 8 minutes

**Comment by clinton-hall** [comment]
Where is that timeout happening, is the transcoding happening as part of HeadPhones renaming?
I never knew this was an option.

**Comment by KaraokeStu** [comment]
Hi,

The transcoding happens as part of the rename process (its under "Advanced Settings") and is enabled only for FLAC files at present.

Stu

**Comment by clinton-hall** [comment]
I guess I'm going to have to add (back) a customisable timeout...

**Comment by KaraokeStu** [comment]
Sorry! :disappointed:

**Comment by clinton-hall** [comment]
Can you try editing https://github.com/clinton-hall/nzbToMedia/blob/master/core/autoProcess/autoProcessMusic.py#L109
On your local system, to show timeout = 30/600

**Comment by KaraokeStu** [comment]
Sure, I'll try that in a sec.

I might look at tweaking headphones to return with a processing status to state whether it is complete, along with a job id, so that if it is not, you can re-poll until either a success or a fail

**Comment by KaraokeStu** [comment]
Hi,

That works perfectly now, so it was just that the transcoding was causing things to timeout.

Stu

**Comment by KaraokeStu** [comment]
I just had the same error again, due to a slower post process. I'll look to increase the timeout further in code

**Comment by jsaddiction** [comment]
I have the same exact issue.  I edited the line as suggested and it fixed the pp failure.  Instead of adding an adjustable timeout is there a part of the headphones api that would indicate a transcoding in progress?  Could there be other ways to check the progress periodically? maybe even log transcoding progress?

**Comment by denics** [comment]
Hi all, any news on this?

**Comment by clinton-hall** [comment]
No news at this end. I have not checked lately to see if headphones has incorporated anyway of returning a "transcoding" job id for us to track progress etc.

**Comment by denics** [comment]
First of all thanks for the software and the follow up! it works great.
If you tell me where to look in Headphones I can try to have a look. I'm doing my first steps into python so it could be an interesting exercise.

**Comment by clinton-hall** [comment]
I suppose some of this depends on the HeadPhones fork in use.
The wiki here actually says this requires echel0n's version, but I believe those changes were included in https://github.com/rembo10/headphones version... There may be other forks out there and I don't know if they are all compatible.

In anycase, these scripts call the api command for `forceProcess`
https://github.com/rembo10/headphones/blob/master/API.md

It looks like this just runs until it completes (which includes transcoding.

These scripts do support a custom `wait-for` parameter
```
[HeadPhones]
    [[Music]]
        wait_for = 2
```
if you increase this value e.g. `wait_for = 10` this will wait for 10 minutes before timing out...
