### ISSUE TITLE
transcode 3D SBD/FP/xxx to Frame Sequential 

### ISSUE THREAD

**Issue by thesatman** [clinton-hall/nzbToMedia#796]
Hi, after copying / ripping my 3D bluray with makeMKV I end up with a file that needs to be converted to Frame Sequential. This because I use a 3D ready DLP projector. These projectors only can play Frame Sequential. Any suggestions?

**Comment by clinton-hall** [comment]
Not sure I can help much on this... I'm not familiar with 3d formats, but from what I read, the .vob files on the iso are already frame sequential, and makeMKV always converts to SBS...

so supposedly if you just rip/extract the .vobs from the disk/iso you should be able to play this?? If so, just use ffmpeg to convert to mkv?

**Comment by thesatman** [comment]
I would be very interested in the source where you found this info. From what I understand you can not play a 3D disk directly connected to a DLP 3D ready projector. You need a convertor. If your information is correct the BD player must do a conversion. I can give your suggestion a try. 

But this solves only one part of the problem. What is couch potato downloads a SBS file? It still needs to be converted to FS.

**Comment by clinton-hall** [comment]
Honestly, I just googled... I found a few forums talking about ripping bluray 3d to frame sequential.

Not sure how to convert SBS...

**Comment by thesatman** [comment]
Hi Clinton,

	 

	Thanks for the reply. I found a link on the internet. Some guy had made a script to create 3D Frame Sequential files that are playable from a Sony PS3 and Sony Bravia W8. I downloaded the media files he has created, and they are playable from my system (Plex server > Roku 3 > receiver > DLP 3D ready projector).

	 

	I don't know is if is of any interest to you. I was think in terms of if a NZBto_xxx user has a 3D file, and if in the config file is included that if playback device is DLP, then convert to 720p 120hz Frame Sequential.

	 

	I tried to get in touch with the developer "tal.aloni". I don't think he was very keen on assisting me. But you are more an expert then I am on the transcoding front, so it would be more correct for you to have a look at this.

	 

	The link: https://www.doom9.org/showthread.php?t=170863 ( [GUIDE] Encoding 3D Frame Sequential MP4 for the PlayStation 3 and Sony Bravia W8)

	 

	What do you think?
