### ISSUE TITLE
Configuration Assistance

### ISSUE THREAD

**Issue by boomertheweim** [clinton-hall/nzbToMedia#800]
Ok, I can't seem to get this to work 100%.  I have a word doc with my settings for Sabnzbd and SickRage,as well as nzbToMedia log files.  Can I post these somewhere so someone can offer possible suggestions.

**Comment by boomertheweim** [comment]
ok figured it all out.. Time to take some screen shots!

**Comment by clinton-hall** [comment]
Glad to hear you got it working.
If there were any particular issues or settings that didn't make sense, feel free to add details on my wiki.
