### ISSUE TITLE
Post processing seems to fail on alias show titles from thetvdb

### ISSUE THREAD

**Issue by forkless** [clinton-hall/nzbToMedia#801]
When post-processing series by their alias listing on thetvdb it seems to fail. 

Eg. Scream The TV Series (alias for Scream) will not pick up the epi.

**Comment by clinton-hall** [comment]
is this in nzbToMedia or is this actually in SicgBeard/SickRage?
Do you have logs?

**Comment by forkless** [comment]
Never mind you can close it. I finally found out the use for the Scene Exceptions (quite a bit of a misnomer)
