### ISSUE TITLE
get exception on file core/synchronousdeluge/transfer.py

### ISSUE THREAD

**Issue by yakovyarmo** [clinton-hall/nzbToMedia#803]
got the following:
Failed to connect to Deluge

which is caused by:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "core/synchronousdeluge/client.py", line 143, in connect
    self.transfer.connect((host, port))
  File "core/synchronousdeluge/transfer.py", line 22, in connect
    self.conn = ssl.wrap_socket(self.sock, None, None, False, ssl.CERT_NONE, ssl.SSLv23_METHOD)
AttributeError: 'module' object has no attribute 'SSLv23_METHOD'

in order to fix that I removed ssl.SSLv23_METHOD so now the line looks like this:
        self.conn = ssl.wrap_socket(self.sock, None, None, False, ssl.CERT_NONE)
and everything works as expected

**Comment by clinton-hall** [comment]
Is this the most recent version of Deluge?
I recall some time ago the ssl version changed and was not compatible. i believe these scripts were updated to work with the latest version and is not backwards compatible.

**Comment by yakovyarmo** [comment]
I test it with the latest : 1.3.11
