### ISSUE TITLE
Unverified SSL Certificate Warning - How to Disable/Hide?

### ISSUE THREAD

**Issue by gibxxi** [clinton-hall/nzbToMedia#804]
Hi Clinton,

I'm running the full suite of Usenet Apps on the Asustor AS5104T. Used to run your nzbToMedia scripts on a ReadyNAS with a similar setup, and somehow didn't get these messages, but on the Asustor, they do appear. Everything, and I mean EVERYTHING is SSL enabled. I use nzb360 on my phone to add/manage downloads when away from home so need SSL access for all the apps I'll be connecting with.

Basically, every time nzbToMedia.py or any of it's sub-modules (like nzbToCouchPotato.py, for example) runs, the log is polluted with multiples of the following message every time a bridge connection is made to one of the apps in question, from nzbToMedia:

INFO    2015-08-07 17:30:14 nzbToCouchPotato: /volume1/Download/nzbToMedia/libs/requests/packages/urllib3/connectionpool.py:747: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html

Since these SSL certificates are self-signed, there's no possibility of them passing a verification check. I understand and accept it for what it is; Far from perfect, but better than raw HTTP. With this in mind is there any way to prevent these messages being written to the log and/or prevent them being shown in the NZBGet PP message queue?

Dan/Gib.

**Comment by clinton-hall** [comment]
Can you try adding these lines here https://github.com/clinton-hall/nzbToMedia/blob/master/core/autoProcess/autoProcessMovie.py#L5

```
import urllib3
urllib3.disable_warnings()
```

and see if this works?

**Comment by gibxxi** [comment]
No joy Clinton. The version of python Asustor has on the App Center doesn't seem to include the urllib3 module:

INFO	2015-08-12 20:10:12	nzbToCouchPotato: ImportError: No module named urllib3

It's the 2.7.3.r13 package available from the App Center, provided by Asustor.

**Comment by count00zero** [comment]
HI together!
1st things 1st: thank you, clinton-hall, for your scripts, thank you very much!

I came across the same problem as gibxxi.
I did some (re)search around the internet and found THE solution which did the trick for me:

I added the following 
import requests
requests.packages.urllib3.disable_warnings()

and voila ... the warnings were gone!
Could these additions be included in future versions?

THANKS again and best regards,
count

**Comment by gibxxi** [comment]
It seems to work if the line "requests.packages.urllib3.disable_warnings()" is inserted directly below the already included "import requests" line in the AutoProcess "*.py" files.

Obviously, have turn off auto-updates in autoProcessMedia.cfg to prevent the changes being wiped. Not sure if an NZBGet restart also resets the files as I've not tested this.

**Comment by NiklasOlofsson** [comment]
I see the same thing in my log. What file do I need to update to remove it?

**Comment by gibxxi** [comment]
Browse to your "Download" share and find the following folder:

nzbToMedia\core\autoProcess

Depending on which apps you use with Usenet, edit the following files (recommend notepad++ so that your files don't get skewed to Windows line-ending format):

autoProcessComics.py
autoProcessGames.py
autoProcessMovie.py
autoProcessMusic.py
autoProcessTV.py

In each file (on or near line 5) you should see the following line:

import requests

Create a new line (move everything below it down one line) and enter the following text in/on the new line you created:

requests.packages.urllib3.disable_warnings()

Save all files (back to their original locations), then edit your autoProcessMedia.cfg and edit the following line:

auto_update = 1

Change the "1" to a "0" to prevent Git updates (each time the script runs) from wiping out your changes. Once Clinton confirms this issue has been addressed, you can reverse this setting.

Gib.

**Comment by clinton-hall** [comment]
Can you please send a pull request to my nightly branch?

**Comment by gibxxi** [comment]
This is running on my NAS, how do I change from master to your nightly 
branch? I need the CLI command or setting to change in the 
autoProcessMedia.cfg.

DM.

**Comment by clinton-hall** [comment]
To change to nightly, you can just cd into the nzbToMedia directory, then

git checkout nightly

To actually create the pull request, you can do this online.
In GitHub change to my nightly, then click "fork". Now edit the needed files, and then you should be able to "send pull request"

**Comment by gibxxi** [comment]
OK, will have a go at this later. With respect the edits, does the 
absolute positioning of that inserted code actually matter? I would 
like, for code tidiness (I'm a bit OCD) to place the statement after all 
the includes, on it's own line. Will this cause any issues?

Dan/Gib.

**Comment by clinton-hall** [comment]
after the `import ..` and `from ` lines is fine... just needs to be before the class is defined.

**Comment by gibxxi** [comment]
It's not working properly Clinton.

Using the website, as instructed, I logged in, changed to your nightly 
branch, then clicked 'clone in desktop' since I have GitHub for windows 
installed. The fork is created, and it's cloned to my local folder (I 
selected the NAS Download share). However, once the process completes, 
Github for Windows is showing me that my fork is a fork of your 'Master' 
branch, not the 'Nightly' branch as selected.

Dan/Gib.

**Comment by gibxxi** [comment]
Think I may have fixed it. I manually switched the remote tracking branch to your nightly branch, and did an update. That seems to have worked. Watch this space.

Dan/Gib.

**Comment by clinton-hall** [comment]
Ah... Not familiar with Github for windows...  but glad you sorted that part...

**Comment by gibxxi** [comment]
Sent a pull request. I think I did it right. I'm sure you'll correct me if not. ;)

**Comment by gibxxi** [comment]
Only issue with the initial mod, I detailed above is that each reboot of the NAS / Restart of NZBGet seems to reset the files and the modifications I made before going down the fork-route. Now that I'm cloning and working on the 'working' folder (/volume1/Download/nzbToMedia) Is there some script running that causes the files to be reset? If so, this could screw up not only the code changes, but the entire repo as it's located on my end.

**Comment by clinton-hall** [comment]
On Asustor the script is reset (git) on App start. 
If you ssh into it and git checkout nightly, as soon as I merge your pull request this should keep the new code.

**Comment by gibxxi** [comment]
OK, thought that would be the case. I was going to fix all the typos in the config template file as well, but it looks at first glance as if you beat me to the punch. :)

**Comment by gibxxi** [comment]
Clinton,

The Windows client seems to only allow me to send one pull request at a 
time. You'll need to accept or deny the first one, so as I can resubmit. 
Doing it via the website is too confusing at this stage for me.

Dan/Gib.

**Comment by gibxxi** [comment]
New pull request sent.

Dan/Gib.

**Comment by clinton-hall** [comment]
now merged

**Comment by gibxxi** [comment]
Just a heads-up Clinton as I don't feel like creating a separate issue just for this. Inside your nzbToMedia folder you have another folder with the same name that's sym-linked to itself. This causes an infinite loop and the folder cannot be deleted.

**Comment by clinton-hall** [comment]
What system is this on, the sumlink isn't in my repo, I guess this is from the simlink into nzbget directory as part of an App package?

**Comment by gibxxi** [comment]
Might be. I cleared the entire nzbToMedia folder to apply the git-pull to test our recent changes, but seeing as you have NZBGet reset the contents of the folder, that's probably being restored as well. Suffice to say the symlink as it stands only links to itself. The symlink from NZBGet's scripts folder is present too, and this works as expected.
