### ISSUE TITLE
NoneType error after upgrading scripts

### ISSUE THREAD

**Issue by mastermind-2** [clinton-hall/nzbToMedia#806]
Everything was working fine, but I decide to update my nxbToMedia scripts because it's been about a year.. I noticed they call python2 now, use a new 'core' and 'libs' directory. I've worked through some initial errors, but I'm now getting the following error in Sabnzb which I can't solve.

    [09:17:04] [ERROR]::MAIN: Unable to migrate config file /scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...
    Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__of <core.nzbToMediaUtil.PosixProcess instance at 0x109e20d40>>" ignored

I'm using Python 2.7.5 on Mac 10.10.4

**Comment by mastermind-2** [comment]
Since I was using Sabnzb and not NZBGet, I decided to delete the last ½ of NZBtoMedia where it referenced the NZBget processing section.. In doing so, i get this error

Traceback (most recent call last):
  File "/Users/admin/Downloads/scripts/nzbToMedia/nzbToCouchPotato.py", line 249, in <module>
    result = nzbToMedia.main(sys.argv, section)
AttributeError: 'module' object has no attribute 'main'

**Comment by clinton-hall** [comment]
What happens if you run the script manually?
If you delete autoProcessMedia.cfg and run the script does it re-create the .cfg file? (if so, can you then edit this file to set the needed config?)

**Comment by mastermind-2** [comment]
i'm not exactly sure how to run it manually. Can you provide me with the terminal command. Write now it's being called from SABNzb. 

However, I did delete the file, downloaded a new movie, it did recreate the file. I did edit for my settings and I get the same exact NoneType Error.

The thing is, that if I restart CoachPotato to invoke the renamed, then it picks up the movie, renames and movies correctly. So the download works it's just bugging out on the post processing script.

I have logging enabled in the autoProcessMedia file, but the only error I get is 

2015-08-13 16:42:30 ERROR   ::MAIN: Unable to migrate config file /scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...

**Comment by mastermind-2** [comment]
Hi clinton

Any update for me on this. It's driving me nuts.

**Comment by mastermind-2** [comment]
Any help here

**Comment by clinton-hall** [comment]
Please run manually using:

`/scripts/nzbToMedia/nzbToMedia.py`
and post the full output returned in the terminal window.

**Comment by mastermind-2** [comment]
If I run nzbToMedia by itself with no arguments I get the same error

    [13:40:02] [ERROR]::MAIN: Unable to migrate config file /scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...
    Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x103af7440>> ignored

When I run nzbtomedia using these parameters
    ./nzbToMedia.py "/path/to/movie" "moviename" "moviename" "" "category" "" "0"

I also get the same exact error

**Comment by clinton-hall** [comment]
Can you email me your autoProcessMedia.cfg file ?
Remove any account passwords/Apis etc to be safe.

**Comment by mastermind-2** [comment]
Thanks I've emailed them to you.

**Comment by mastermind-2** [comment]
resolution: be sure there are no quotes around paths in the autoProcessMedia file
