### ISSUE TITLE
change transcoder.py to allow user set loglevel

### ISSUE THREAD

**Issue by Symbiot78** [clinton-hall/nzbToMedia#811]
hi C.

I don't really know much about doing pull-requests or what that really means but I assume it's to add own changes.. so let's call this a feature request.

might I suggest changing transcoder.py line 445 & 528 to allow user to set loglevel. 
so add the option to autoprocess.cfg and let transcoder.py pick up the option set by user. 
Set warning as default.

**Comment by clinton-hall** [comment]
fair call... what are the allowed loglevel parameters?

**Comment by Symbiot78** [comment]
hi clint..

this is the std. logging options for ffmpeg, I hope it is/can be logged to nzbtomedia log files..

-loglevel [repeat+]loglevel | -v [repeat+]loglevel
Set the logging level used by the library. Adding "repeat+" indicates that repeated log output should not be compressed to the first line and the "Last message repeated n times" line will be omitted. "repeat" can also be used alone. If "repeat" is used alone, and with no prior loglevel set, the default loglevel will be used. If multiple loglevel parameters are given, using ’repeat’ will not change the loglevel. loglevel is a string or a number containing one of the following values:

‘quiet, -8’
Show nothing at all; be silent.

‘panic, 0’
Only show fatal errors which could lead the process to crash, such as and assert failure. This is not currently used for anything.

‘fatal, 8’
Only show fatal errors. These are errors after which the process absolutely cannot continue after.

‘error, 16’
Show all errors, including ones which can be recovered from.

‘warning, 24’
Show all warnings and errors. Any message related to possibly incorrect or unexpected events will be shown.

‘info, 32’
Show informative messages during processing. This is in addition to warnings and errors. This is the default value.

‘verbose, 40’
Same as info, except more verbose.

‘debug, 48’
Show everything, including debugging information.

‘trace, 56’
By default the program logs to stderr, if coloring is supported by the terminal, colors are used to mark errors and warnings. Log coloring can be disabled setting the environment variable AV_LOG_FORCE_NOCOLOR or NO_COLOR, or can be forced setting the environment variable AV_LOG_FORCE_COLOR. The use of the environment variable NO_COLOR is deprecated and will be dropped in a following FFmpeg version.

**Comment by clinton-hall** [comment]
hmmm... the problem is this doesn't actually do anything here since we write all output to "bitbucket" (/dev/null)

if you want to debug your transcode issues you will need to change the log level as you indicated AND
in line 696 and 698 of transcoder.py you need to set a file to write the output to.

e.g. for linux change line 698 from
```
        bitbucket = open('/dev/null')
```
to
```
        bitbucket = open('/home/admin/logs/ffmpeg.log')
```
Try that and see if that works to help you debug...
I can add this as a feature, but I don't have the time to submit this right now.. and I don't recall why I set this to bitbucket... but I think this may cause memory issues...

**Comment by Symbiot78** [comment]
hi clint.

Thanks, I'll give it a go at some point.. right now I'm still fiddling with actually getting ffmpeg to work properly.!
