### ISSUE TITLE
autoProcessMedia.cfg - typos

### ISSUE THREAD

**Issue by thezoggy** [clinton-hall/nzbToMedia#813]
few misspellings...

`# Enable/Disable deleteing ignored files (samples and invalid media files)`
typo for `deleting`, this is under each section.

`###### duplicate =1 will cretae a new file. =0 will replace the original`
typo for `create`

`# allSubLanguages. 1 will keep all exisiting sub languages. 0 will discare those not in your list above.`
typo for `existing` and `discard`

`#Set user_script_runOnce = 0 to run for each file, or 1 to only run once (presumably on teh entire directory).`
typo for `the`

`# be careful if your "group" is a common "real" word. Please report if you have any group replacments that would fall in this category.`
typo for `replacements`

**Comment by thezoggy** [comment]
`# embedSubs. 1 will embded external sub/srt subs into your video if this is supported.`
typo for `embed`

**Comment by thezoggy** [comment]
you left off a comment for `ignoreExtensions` :)

**Comment by clinton-hall** [comment]
Thanks... hopefully all good in nightly branch.
