### ISSUE TITLE
Add support for SickRage's delete_on 

### ISSUE THREAD

**Issue by WebSpider** [clinton-hall/nzbToMedia#814]
SickRage has the option to delete source files after postprocessing, which is done by setting delete_on to True. Currently nzbToMedia doesn't ever seem to pass this, so SiCKRAGE doesn't clean up after itself

See https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webserve.py#L2249
and https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/processTV.py#L254

**Comment by clinton-hall** [comment]
can you please test latest nightly...
I haven't had a change to test, or verify if this breaks auto-fork detection etc...

**Comment by WebSpider** [comment]
OK, just switched to nightly, will let you know once the first downloads get processed!

**Comment by WebSpider** [comment]
It doesn't seem to send it along:

https://gist.github.com/WebSpider/9c6d4244b82bdc7e057b

I'm on nightly/HEAD:

BLACKBOX> /usr/local/git/bin/git log | head -1
commit 22bb2b64b12bc917cb7116ee795d78500e7d67e4

**Comment by clinton-hall** [comment]
In autoProcessMedia.cfg did you set
[SickBeard]
    [[tv]]
        delete_on = 1

This is the new config to turn this on.

**Comment by WebSpider** [comment]
Ah.
Setting now :)

-----Original Message-----

**Comment by WebSpider** [comment]
It passes the command correctly now, however SR is not deleting the source files. :-1: 
I will investigate this further in SR code.
