### ISSUE TITLE
manual run

### ISSUE THREAD

**Issue by thezoggy** [clinton-hall/nzbToMedia#815]
upon trying to do a manual run I found on here that I need to just mimic sonarr/sickbeard's params.. so I did this but it would never work because it couldn't hit the fake sb/sonarr instance as suggested to do.. the end fix was to comment out this line that aborted continuing:
https://github.com/clinton-hall/nzbToMedia/blob/master/core/autoProcess/autoProcessTV.py#L68

only then did it continue with the transcode..  I would suggest allowing to bypass this check if manual run is specified.

**Comment by clinton-hall** [comment]
Ok... I'll try and look into this.. thanks.
