### ISSUE TITLE
nzbToMedia vs mp4_automator - HD to SD transcode

### ISSUE THREAD

**Issue by thezoggy** [clinton-hall/nzbToMedia#816]
source: 19m54s 720p HDTV rip thats 720 MB
mediainfo: http://pastebin.com/raw.php?i=jp28DUZS

Trying to re-encode this to 480p (SD) that mimics what scene would produce... since can't do VBR with audio stuck using CBR but trying to find acceptable settings that would produce similar results....

Forgot to time these to see if one is really faster than the other.. also can see that while video is close the audio is a bit different for each.

nzbtomedia:
`[13:17:45] [DEBUG]::MAIN: calling command: C:\ffmpeg\bin\ffmpeg.exe -loglevel warning -hwaccel auto -fflags +genpts -i F:\folder\file.mkv -i F:\folder\file.en.srt -map 0:0 -map 0:1 -map 1:0 -c:v libx264 -vf scale=720:404 -b:v 1400000 -crf 19 -level 3.1 -c:a:0 aac -strict -2 -b:a:0 192 -c:s mov_text -metadata:s:s:0 language=en -movflags +faststart F:\folder\file.mp4`
mediainfo: http://pastebin.com/raw.php?i=wG9KUdXd
result: 252 MB (w/sub embeded)

mp4 automator:
`Spawning ffmpeg with command: C:\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -i F:\folder\file.mkv -i F:\folder\file.en.srt -map 0:0 -map 0:1 -map 1:0 -vcodec libx264 -vf scale=720:-2 -vb 1400k -level 3.1 -c:a:0 aac -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:s:0 mov_text -metadata:s:s:0 language=eng -f mp4 -threads auto -y F:\folder\file.mp4`
mediainfo: http://pastebin.com/raw.php?i=tuYYDKTZ
result: 233 MB (unable to get subs working - even tried letting it use the subs nzbtomedia found)

nzbtomedia:

```
    # getsubs. enable to download subtitles.
    getSubs = 1
    # subLanguages. create a list of languages in the order you want them in your subtitles. 
    subLanguages = eng
    # transcode. enable to use transcoder
    transcode = 1
    # outputFastStart. 1 will use -movflags + faststart. 0 will disable this from being used.
    outputFastStart = 1
    # audioLanguage. set the 3 letter language code you want as your primary audio track.
    audioLanguage = eng
    # embedSubs. 1 will embed external sub/srt subs into your video if this is supported.
    embedSubs = 1
    # hwAccel. 1 will set ffmpeg to enable hardware acceleration (this requires a recent ffmpeg)
    hwAccel = 1
    #### Define custom settings below.
    outputVideoExtension = .mp4
    outputVideoCodec = libx264
    VideoCodecAllow = "libx264,h264,h.264,AVC,avc,mpeg4,MPEG-4"
    outputVideoPreset = ""
    outputVideoResolution = 720:480
    outputVideoFramerate = ""
    outputVideoBitrate = 1400k
    outputVideoCRF = 19
    outputVideoLevel = 3.1
    outputAudioCodec = aac
    AudioCodecAllow = "libfaac,aac,libfdk_aac"
    outputAudioChannels = 2
    outputAudioBitrate = 192
    outputAudioTrack2Codec = ""
    AudioCodec2Allow = ""
    outputAudioTrack2Channels = ""
    outputAudioTrack2Bitrate = ""
    outputAudioOtherCodec = ""
    AudioOtherCodecAllow = ""
    outputAudioOtherChannels = ""
    outputAudioOtherBitrate = ""
    outputSubtitleCodec = mov_text
```

mp4 automator:

```
[MP4]
ffmpeg = C:\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\ffmpeg\bin\ffprobe.exe
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = True
audio-codec = aac
video-codec = h264,x264
video-bitrate = 1400
h264-max-level = 3.1
ios-audio = True
max-audio-channels = 2
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 192
subtitle-language = eng
subtitle-default-language = eng
fullpathguess = True
convert-mp4 = False
tagfile = False
tag-language = en
download-artwork = False
download-subs = True
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
ios-first-track-only = False
subtitle-codec = mov_text
video-max-width = 720
```

**Comment by clinton-hall** [comment]
interesting results...

Is there anything you want me to try and tweak in here?

**Comment by thezoggy** [comment]
things to note,

* the source video is 1280x720 (720p) and the settings were to transcode down to 480p, both apps use the width to size down off of..

  * nzbtomedia resized the video correctly with proper aspect ratio of 720x404

  * automator resized the video incorrectly to 720x406

* the source video audio is 2 channel AC-3 with constant bitrate of 384 Kbps, stream size of 54.7 MiB

  * nzbtomedia ended up with 2 channel AAC (which is good) but with a horrible bitrate of 4,136 bps for a stream size of 603 KiB

  * automator ended up with 2 channel AAC (which is good) with bitrate of 256 Kbps for stream size of 36.5 MiB

**Comment by thezoggy** [comment]
it would be nice to use a pre defined template like:
`outputDefault = mp4-scene-release` 

then override options if specified, otherwise just use template settings.. so for example:
`outputVideoResolution = 720:480`

would result in the template used but resized.

this seems much more use friendly instead of trying to figure out what settings a template uses.. and specify them each or hacking in another template with the changes you want (trying to avoid modifying source)
