### ISSUE TITLE
FR/QQ:Mylar failed handling

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#817]
Is this on the map? I just noticed most recent Mylar has failed handling but i get the usual mylar doesn't support failed downloads message in SAB for exmpale.

Exit(1) Mylar: Failed to post-process. Mylar does not support failed downloads! (More

**Comment by clinton-hall** [comment]
Interesting. I didn't know mylar had added failed... is this in the main repo now?

**Comment by mgaulton** [comment]
From what i saw yes.

**Comment by allkindsofralph** [comment]
This ever get fixed?
