### ISSUE TITLE
sab 0.8.x - pp argument changes

### ISSUE THREAD

**Issue by thezoggy** [clinton-hall/nzbToMedia#819]
looking at when the user script is called, we see things have changed.. 

0.8.x:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/postproc.py#L447
`
                script_log, script_ret = external_processing(short_path(script_path, False), short_path(workdir_complete, False), nzo.filename,
                                                             dirname, cat, nzo.group, job_result,
                                                             nzo.nzo_info.get('failure', ''))
`

0.7.20:
https://github.com/sabnzbd/sabnzbd/blob/0.7.x/sabnzbd/postproc.py#L442
`
                script_log, script_ret = external_processing(script_path, workdir_complete, nzo.filename,
                                                             msgid, dirname, cat, nzo.group, job_result,
                                                             nzo.nzo_info.get('failure', ''))
`

just note this for now, seeing some oddities (.nzb part of the filename now and path having trailing ..)

**Comment by clinton-hall** [comment]
interesting... this would put the status, category, and failure link all out of sync!!

**Comment by thezoggy** [comment]
working with shy on fixing some bugs, but really the only major change is the paths return are the short path variants to try and prevent long path issues.. but that introduced a bug on windows where `\..` will show up at times..  yeah msgid really needs to get moved to the end.. ill see about getting this changed so it doesnt mess up legacy scripts
