### ISSUE TITLE
Sync integration

### ISSUE THREAD

**Issue by sea3pea0** [clinton-hall/nzbToMedia#820]
I posted [this](http://forum.bittorrent.com/topic/41036-run-script-when-folder-finishes-syncing/) over in the Bit Torrent Sync forums. I think it would be nice if btsync could run nzbtomedia each time after a folder completes a sync similar to the way torrent clients run nzbtomedia after a torrent completes a download.

**Comment by clinton-hall** [comment]
Thees api call they referenced would work well for a regular check from a running service. But this does not allow btsync to call the script when the sync completes...

So, this is possible, but requires nzbToMedia to be running as a service... on the cards, but requires a lot more dev time...

**Comment by sea3pea0** [comment]
I posted [this](https://forum.syncthing.net/t/script-upon-complete-transfer/5667) at the Syncthing forums. We'll see what they say, maybe they'll be more open to the idea of adding a feature.

**Comment by sea3pea0** [comment]
I finally ended up getting a working sshfs mount on my Synology so I no longer need this. Also it seems like a more complicated task than it is worth so I am closing this :)
