### ISSUE TITLE
Error when using nzbToMedia.py with Sabnzbd

### ISSUE THREAD

**Issue by josurr** [clinton-hall/nzbToMedia#821]
setup nzbToMedia as per Clinton's wiki, but receiving the following error in Sabnzbd when trying to use it for post-download processing:

http://pastebin.com/MwGkfX9b

let me know if there is more data needed

**Comment by clinton-hall** [comment]
Please ensure you have matching versions of Python AND PyWin installed.
This error suggests you do not have PyWin modules installed.
