### ISSUE TITLE
nzbToSickbeard errors at end of log - think it is Plex related

### ISSUE THREAD

**Issue by kazooless** [clinton-hall/nzbToMedia#822]
Hello. I am running FreeNAS with SickRage and SabNZBD in their own jails. I've configured nzbToMedia and it worked successfully except there is an error at the end. I think it is in the Plex notification code. What do you think?

Traceback (most recent call last):
  File "/media/scripts/nzbToSickBeard.py", line 252, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/media/scripts/nzbToMedia.py", line 712, in main
    download_id='')
  File "/media/scripts/nzbToMedia.py", line 611, in process
    plex_update(inputCategory)
  File "/media/scripts/core/nzbToMediaUtil.py", line 1063, in plex_update
    url = url + core.PLEXHOST + ':' + core.PLEXPORT + '/library/sections/'
UnboundLocalError: local variable 'url' referenced before assignment
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x80076abd8>> ignored

**Comment by kazooless** [comment]
I'm not a programmer but I opened up nzbToMediaUtil.py and searched for the Plex section. I think I see a typo. The third line has "ulr" instead of "url." I'll try changing that and report back.

def plex_update(category):
    if core.PLEXSSL:
        ulr = 'https://'
    else:
        url = 'http://'
    url = url + core.PLEXHOST + ':' + core.PLEXPORT + '/library/sections/'
    section = None
    if not core.PLEXSEC:
        return
    logger.debug("Attempting to update Plex Library for category %s." %(category), 'PLEX')
    for item in core.PLEXSEC:
        if item[0] == category:
            section = item[1]

**Comment by kazooless** [comment]
That fixed it. So I guess this is a bug, right?

**Comment by clinton-hall** [comment]
yes, bug... thanks for reporting.
