### ISSUE TITLE
nzbToMediaUtil SSL/SABnzbd Failure

### ISSUE THREAD

**Issue by imphocused** [clinton-hall/nzbToMedia#823]
Issue:
core/nzbToMediaUtil.py appears to be hard-coded to HTTP for everything except Plex

Scenario:
SABnzbd is configured to use SSL only (localhost:8080). Downloads successfully complete and when sent to post-processing, the 'nzbtomedia.log' shows
```
2015-09-13 16:13:49 INFO    ::MAIN: Script triggered from SABnzbd
2015-09-13 16:13:49 DEBUG   ::MAIN: Searching for nzoid from SAbnzbd ...
```
At this point it eventually fails, and the SABnzbd shows a successful download, but gives the error:
```
	Exception TypeError: "'NoneType' object is not callable" in <bound method PosixPro
```
Running the script manually from console works without any problems.

After modifying line 822 in core/nzbToMediaUtil.py:
```
 -   baseURL = "http://%s:%s/api" % (core.SABNZBDHOST, core.SABNZBDPORT)
 +   baseURL = "https://%s:%s/api" % (core.SABNZBDHOST, core.SABNZBDPORT)
```

I now get the expected results:
```
2015-09-13 16:30:13 INFO    ::MAIN: Script triggered from SABnzbd
2015-09-13 16:30:13 DEBUG   ::MAIN: Searching for nzoid from SAbnzbd ...
2015-09-13 16:30:13 DEBUG   ::MAIN: Adding NZB download info for directory <removed>
```

Files then show up as expected in SickRage then Plex. I still have the 'Exception TypeError' listed above, but I feel that's elsewhere.

**Comment by clinton-hall** [comment]
ok... update to latest nightly branch, then in autoProcessMedia.cfg
```
[Nzb]
    sabnzbd_host = http://localhost
```
or
```
    sabnzbd_host = https://localhost
```
If neither http or https are specified, then `http` is assumed.

**Comment by imphocused** [comment]
Successful on all accounts. Postprocessing worked as expected, and that 'Posix' error went away (was showing on sickrage and couchpotato).

```
CouchPotato: Successfully post-processed ...
SickBeard: Successfully post-processed ...
```
Thanks for the quick fix.
