### ISSUE TITLE
Simple questions from a Noob

### ISSUE THREAD

**Issue by TimDowker** [clinton-hall/nzbToMedia#824]
I have two basic questions
1. Which script do I run at the completion of a download? TorrentToMedia.py? Or does it depend on what I'm using to download?  Currently I have a working Transmission/Sickrage setup and I'm looking for something to do the transcoding automatically.  I'd also like to implement CouchPotato in the future.
2. Is it better to run the above script from Transmission or Sickrage?  Same question when I implement CouchPotato.

Thank you for taking the time to answer my noob questions.

**Comment by brutaldev** [comment]
1. Depends on your downlaoder. Follow the configuration steps here https://github.com/clinton-hall/nzbToMedia/wiki/transmission and here https://github.com/clinton-hall/nzbToMedia/wiki/sickbeard. SickRage is a fork of SickBeard so the configuration is the same.

2. Your downloader will always run the post-processing scripts (Transmission, SABnzbd etc.), not the media management application.
