### ISSUE TITLE
Failed to locate 7zip

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [clinton-hall/nzbToMedia#830]
hi i been using NZBtoMedia with sickrage and i keep getting this:

[WARNING]::MAIN: Failed to locate 7zip. Transcosing of disk images and extraction of .7z files will not be possible!

i have p7zip installed and when i do which 7z it show: /usr/local/bin/7z
but i cannot find anywhere in autoProcessMedia.cfg that refers to 7z Path to place /usr/local/bin/

like i did with: ffmpeg_path = /usr/local/bin/

i'm on a Mac OS system

**Comment by XxUnkn0wnxX** [comment]
found the solution just needed to create these symlinks after installing p7zip via homebrew
sudo ln -s /usr/local/bin/7z /usr/bin/7z
sudo ln -s /usr/local/bin/7za /usr/bin/7za
sudo ln -s /usr/local/bin/7zr /usr/bin/7zr

**Comment by clinton-hall** [comment]
or you can add 
`export PATH=$PATH:/usr/local/bin`
to your NZBGet start-up ??

Thanks for reporting your solution.

**Comment by TheQL** [comment]
Just stumbled upon this. With current macOS versions adding a link to /usr/bin is impossible. I am calling nzbToSickBeard.py from SABnzbd+ - not sure what path environment is loaded but suspecting it is also missing /usr/local/bin. Now I am not sure how I would add that, so it might be a sensible move to just add parameters to autoProcessMedia.cfg anyway.

**Comment by clinton-hall** [comment]
Can you update to latest nightly, then add
```
[General]
    sys_path = /uar/local/bin
```
or indeed set it to the location of a folder where you store your local executables.
In theory, this should then append to path before searching for 7zip, par2, ffmpeg etc.

**Comment by TheQL** [comment]
Ok, thanks, did that. Now let me wait until processing is started next time! Should be soon.

**Comment by TheQL** [comment]
This somehow didn't work out.

Log:
```
2019-03-01 05:01:35 INFO    ::MAIN: Loading config from [/Users/ql/bin/nzbToMedia/autoProcessMedia.cfg]
2019-03-01 05:01:35 INFO    ::MAIN: Python v2.7 will reach end of life in 306 days.
2019-03-01 05:01:35 WARNING ::MAIN: Please upgrade to a more recent Python version.
2019-03-01 05:01:35 INFO    ::MAIN: Checking database structure...
2019-03-01 05:01:35 INFO    ::MAIN: Checking if git needs an update
2019-03-01 05:01:36 INFO    ::MAIN: No update needed
2019-03-01 05:01:36 INFO    ::MAIN: nzbToMedia Version:27cfc3457719163015fcb30db3464d6da721c425 Branch:nightly (Darwin
18.2.0)
2019-03-01 05:01:36 WARNING ::MAIN: Failed to locate 7zip. Transcoding of disk images and extraction of .7z files will
not be possible!
2019-03-01 05:01:36 WARNING ::MAIN: Failed to locate par2. Repair and rename using par files will not be possible!
2019-03-01 05:01:36 INFO    ::MAIN: #########################################################
2019-03-01 05:01:36 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2019-03-01 05:01:36 INFO    ::MAIN: #########################################################
2019-03-01 05:01:36 INFO    ::MAIN: Script triggered from SABnzbd 0.7.17+
2019-03-01 05:01:37 INFO    ::MAIN: Auto-detected SECTION:SickBeard
```

binaries:
```
# which 7z par2
/usr/local/bin/7z
/usr/local/bin/par2
```

Config excerpt:
```
# grep path autoProcessMedia.cfg
    # Set to the full path to the git executable
    git_path = /usr/local/bin/git
    # Set to the directory to search for executables if not in default system path
    sys_path = /usr/local/bin
    ffmpeg_path = /Users/ql/Library/Application Support/FFmpegTools
...
```

**Comment by clinton-hall** [comment]
Sorry about this. Python appears to have 2 ways of interacting with the system PATH.

`sys.path` (as I appended to previously appears to be loaded when pythons starts, but changes to this appear not to be made outside of the python instance. So the daughter processes (i.e. Popen) don't actually read from this.

`os.environ[PATH]` however is reading from the environment variables, and changes to this are inherited by all daughter processes.

I have done a few tests at my end and this latest change seems to be working now.

**Comment by TheQL** [comment]
No problem. All in all this isn't really more than a cosmetic issue, I'm not relying on par2 checks to work in this stage of the processing. I did another manual git pull to be sure and will report back after the next processing has completed. Thanks!

**Comment by TheQL** [comment]
No more errors! Thanks.

**Comment by clinton-hall** [comment]
Glad to hear it. Thanks for confirming.

**Comment by TheQL** [comment]
Time to close this issue and merge it into master?

**Comment by clinton-hall** [comment]
We can close... or when it is merged into master it will close automatically.
As far as merge to master.... I need to update version numbers and create a new release.... I'll see how I go this weekend.
