### ISSUE TITLE
Windows Utorrent pythonw error

### ISSUE THREAD

**Issue by d4g79** [clinton-hall/nzbToMedia#834]
hi can someone let me know why when i use pythonw with nzbtomedia to hide the windows when the script runs that any .rar files or zips dont work.....

but when i use python without the w to show windows then nzbtomedia extracts the files and process....

with the pythonw it will only process no archive files......

thanx Denis

**Comment by clinton-hall** [comment]
I think this relates to different environment variables that are passed to the daughter processes?

Can you set
```
[General]
    log_env =1
```
then run nzbToMedia from python and pythonw... check the logs and compare the environemnt variables that are printed.

**Comment by d4g79** [comment]
Yeah I changed the torrenttomedia.py to .pyw and now it runs weird but if I use open with Python w then it fails.  

So it's working now. 

Thanx Clinton.
