### ISSUE TITLE
API Key missing In SabNZB when using nzbToSickBeard.py [SickRage]

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [clinton-hall/nzbToMedia#835]
i don't get this error when sickrage sends NZB's to Sab but each time nzbToSickBeard.py runs from SAB i get this error: 2015-09-27 05:11:33,568 WARNING:    API Key missing, please enter the api key from Config->General into your 3rd party program: ::1>python-requests/2.7.0 CPython/2.7.10 Darwin/14.5.0

and i know its nzbToMedia coz when i look in the logs only nzbToMedia has "Darwin/14.5.0" within it's logs

i found a workaround this but just setting this:

[Nzb]
    ###### clientAgent - Supported clients: sabnzbd, nzbget
    clientAgent = sabnzbd
    ###### SabNZBD (You must edit this if your using nzbToMedia.py with SabNZBD)
    sabnzbd_host = localhost
    sabnzbd_port = 8080
    sabnzbd_apikey = "MY API KEY"
    ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode.
    default_downloadDirectory = ""

within the API section.. but this doesnt explain why this happens. why should nzbToSickBeard.py need to have the API configured in the autoProcessMedia.cfg file?

this guide just says to configure the sickbeard section: https://github.com/SiCKRAGETV/sickrage-issues/wiki/NZBtoMedia#configure-autoprocessmediacfg-for-sabnzbd and just doing that i get the above error without doing the workaround & including the API key within the config file.

EDIT: close the request as i just realized this needs to be configured due to nzbToSickBeard.py imports nzbToMedia.py and the sabnzbd_apikey was needed to be configured as it was left out in the Wiki Guide

**Comment by clinton-hall** [comment]
Yeah, sorry about this. as new features are added I don't always remember to update the wiki.
The wiki is "open" so you can edit it if you feel the need/desire.
