### ISSUE TITLE
Showing the processed title instead of the .nzb file name in sabnzbd history

### ISSUE THREAD

**Issue by noodle-** [clinton-hall/nzbToMedia#836]
For instance, SABnzbd will get a new download from SickRage with "[-XO] Dragon Ball Super - 012 [720p]" as .nzb name. This same name is displayed in the last print line of the script as well, making it quite superfluous. 

I'd prefer the processed filename to be in that place (the last print command) instead. So the last print line would be the filename after sickbeard has postprocessed it: 
SickBeard: Successfully post-processed Dragon.Ball.Super.012.720p.HDTV.Episode.12.-XO.mkv!"

It should be relatively easy, as that same name is printed a few lines above as well:
[19:06:38] [POSTPROCESS]::SICKBEARD: Moving file from Y to X

I've tried setting "processOutput = 1" in the autoProcessMedia.cfg but apparantly that's unrelated.

I've tried looking for this in the code myself but I'm too dumb :)

Any info is appreciated.
btw, this should probably be labeled as enhancement, as it's not an error or malfunction.

**Comment by clinton-hall** [comment]
Yes, this is possible.
The biggest issue here is different versions of SickRage/SickBeard do have different outputs and as the logging changes, this script would need to change too.

Most reliable way would be to Parse the `Moving file from Y to X` line, then strip off all the remaining path...

**Comment by noodle-** [comment]
I hacked the commit in manually and it works for me. Thanks for the quick fix!
