### ISSUE TITLE
Error calling nzbToMedia.py through Sabnzbd

### ISSUE THREAD

**Issue by johndoe86x** [clinton-hall/nzbToMedia#838]
I get the following error when I try to call nzbToMedia.py through Sabnzbd.

```python
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x279aea8>> ignored
```

Here is the pastebin link: http://pastebin.com/1kgubhvR

I am running this on a headless Debian server with Python 2.7.3.  I cannot pin down when this issue may have started.  It works no problem manually running the nzbToMedia.py script.

Please let me know what other information I can provide. Thanks!

**Comment by clinton-hall** [comment]
`Permission denied: '/home/nzbToMedia/logs/nzbtomedia.log'`

Make sure the user running SABnzbd has read and write permissions to this file/folder

**Comment by johndoe86x** [comment]
Clinton, thank you for your response.  I believe what happened was that I both performed a git pull and backed up the log file as root, therefore, changing the permissions.  The permissions are reset now and it works great once again. I apologize for the inconvenience, and I very much enjoy your scripts!
