### ISSUE TITLE
Post Processing issue 

### ISSUE THREAD

**Issue by sea3pea0** [clinton-hall/nzbToMedia#839]
I have nzbtomedia and transmission on one server and headphones located across wan. When 1 download finishes everything works fine. But if it so happens that another download finishes before the first one has finished post processing it locks headphones up. It appears things are still working, just very very slowly, too slow to even load the headphones webui. I can tell by looking at headphones logs that the post processing is still happening though. I am not sure if this means there are two instances running, post processing the same folders or not but I would guess that's what's happening. Is there any way to prevent this from happening with my setup?

**Comment by clinton-hall** [comment]
nzbToMedia will not allow 2 occurrences to run. The "second" instance will sit idle until the first instance completes.

Do you have nzbToMedia logs/headphones logs at the time of the lock-up.

**Comment by sea3pea0** [comment]
Well here are some logs of headphones trying to post process the latest download. It looks like it get's an api request to post process the entire processing folder instead of just the release that is downloaded. So what happened yesterday, every time a new release was downloaded it would start the whole process over from the beginning. I think the lockup was an unrelated issue with headphones post processing a specific release.

**Comment by sea3pea0** [comment]
I am also having issues with Sonarr. When the script is run everything works fine, but when Sonarr's CDH notices that the download has finished it also tries to import the file causing the process to start over. In the wiki it says to have CDH on. Is this still the recommended setup for Sonarr or should I switch CDH off?

**Comment by sea3pea0** [comment]
I have a couple of other issues. Since I am copying across WAN, it can take a long time to transfer files. TorrentToMedia stops the torrent in transmission while it is copying. Is there a way to prevent transmission from stopping the torrent? Also, I set wait_for = 360 for each of the categories in cases where the files could take a really long time to transfer. Once the copy finishes nzbToMedia should detect that even if it is before 360 minutes right? I had an episode finish with sonarr and it had been about 20 minutes after the copy completed and the script was still waiting to see if sonarr had completed the import. Is this possibly because I have CDH off? I had problems with sonarr trying to process and restart when CDH was on. Thanks for your help!

**Comment by clinton-hall** [comment]
The pausing in Transmission is needed to remove any "locks" on files that are seeding.

CDH does need to be on.
