### ISSUE TITLE
Add Support To /usr/local/bin/python2 (El Capitan)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [clinton-hall/nzbToMedia#840]
@clinton-hall 

now El Capitan is on its way very soon and since 

NZBtoMedia scripts require to load python from /usr/bin/python2

i would highly recommend adding support to /usr/local/bin/python2 instead, Since Mac OS El Capitan will remove access to the following directories:
/System
/usr <-- everything but the local folder will be restricted
/sbin
/bin

so running this: ln -sf /usr/bin/python2.7 /usr/bin/python2 will fail since /usr/bin will be off limits..

![](http://puu.sh/ks929.png)

Edit: My Current Workaround this issue: https://gist.github.com/XxUnkn0wnxX/bf3d848232f4a71b6556

**Comment by XxUnkn0wnxX** [comment]
@nzbToMeida

**Comment by XxUnkn0wnxX** [comment]
all of these files that start with: #!/usr/bin/env

__init__.py
__main__.py
__version__.py
certs.py
chardetect.py
chardetect.py
commands.py
containers.py
date.py
expected_series.py
expected_title.py
extension.py
fileutils.py
get_files.py
guess_bonus_features.py
guess_country.py
guess_date.py
guess_episode_details.py
guess_episode_info_from_position.py
guess_episodes_rexps.py
guess_filetype.py
guess_idnumber.py
guess_language.py
guess_movie_title_from_position.py
guess_properties.py
guess_release_group.py
guess_video_rexps.py
guess_weak_episodes_rexps.py
guess_website.py
guess_year.py
guess.py
guessittest.py
hash_ed2k.py
hash_mpc.py
language.py
matcher.py
matchtree.py
numeral.py
nzbToCouchPotato.py
nzbToGamez.py
nzbToHeadPhones.py
nzbToMedia.py
nzbToMylar.py
nzbToNzbDrone.py
nzbToSickBeard.py
quality.py
score.py
slogging.py
split_explicit_groups.py
split_on_dash.py
split_path_components.py
test_api.py
test_autodetect_all.py
test_autodetect.py
test_doctests.py
test_episode.py
test_hashes.py
test_language.py
test_main.py
test_matchtree.py
test_movie.py
test_providers.py
test_quality.py
test_subliminal.py
test_utils.py
tests.py
textutils.py
TorrentToMedia.py
transformers.py

would need to be set to: #!/usr/local/bin/env

there are about 74 files since there are a few duplicates, i would do it my self but each time NZBtoMedia would get updated all my changes would be removed so it would be recommended if these changes where made from the source & all Linux distributions should have /usr/local/bin

**Comment by imphocused** [comment]
OS X 10.11 will not remove access to those directories, just restrict access to modifying files in those directories.
>The specifics of System Integrity Protection are that no user, application, or process will be able to write files or modify files in the root System folder or the /bin, /sbin, and /usr directories...
> - http://www.macworld.com/article/2948140/os-x/private-i-el-capitans-system-integrity-protection-will-shift-utilities-functions.html

'/usr/bin/env'  will continue to work as expected, determining which program (python2 in this case) is to be used by locating the first identified in the current $PATH environment variable.

nzbToMedia doesn't hardcode python2 to any directory, rather the call to '/usr/bin/env' will grab the first version it finds from the PATH environment.
```
$ egrep 'env python2$' -R .
./nzbToNzbDrone.py:#!/usr/bin/env python2
./nzbToMedia.py:#!/usr/bin/env python2
./tests/general.py:#! /usr/bin/env python2
./nzbToCouchPotato.py:#!/usr/bin/env python2
./nzbToHeadPhones.py:#!/usr/bin/env python2
./nzbToSickBeard.py:#!/usr/bin/env python2
./nzbToMylar.py:#!/usr/bin/env python2
./TorrentToMedia.py:#!/usr/bin/env python2
./nzbToGamez.py:#!/usr/bin/env python2

OSX 10.10.5:
➜  ~  which python
/usr/local/bin/python

CentOS 7.1:
$ which python2
/usr/bin/python2
```
If your path is starting at '/usr/bin/' then you can try editing '/etc/paths' so that '/usr/local/bin/' is first:
```
~  cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

**Comment by XxUnkn0wnxX** [comment]
yes i have /usr/local/bin first but it doesnt change anything when sabnzb calls the script it constantly tries to look for /usr/bin/python2 instead of /usr/local/bin/python2 i have examined my ~/.bash_profile

/etc/paths file, /etc/paths.d folder, ~/.bashrc & ~/MacOSX/environment.plist files they all start with /usr/local but NZBtoMedia constantly gave me this error no matter what i did to my paths
env: python2: No such file or directory

**Comment by XxUnkn0wnxX** [comment]
the Author os Sab said this: 
The thing is, when you run something from Terminal it gets its
environment variables from .bash_profile. The .app does not.
This may explain the difference.
One way to solve this is to find the place in nzbToSickBeard.py where it calls nzbToMedia.py
Put "python" before the script name and the first line of nzbToMedia.p will be ignored and the default
system Python will be used instead.

so @imphocused it seems that Sab doesnt follow the variables listed in /etc/paths nor .bash_profile
so how else would this issue be solved? the only way i see it is the script itself would need to be hardcoded to include the full python path.

& 

./nzbToCouchPotato.py:#!/usr/bin/env python2
./nzbToGamez.py:#!/usr/bin/env python2
./nzbToHeadPhones.py:#!/usr/bin/env python2
./nzbToMedia.py:#!/usr/bin/env python2
./nzbToMylar.py:#!/usr/bin/env python2
./nzbToNzbDrone.py:#!/usr/bin/env python2
./nzbToSickBeard.py:#!/usr/bin/env python2
./tests/general.py:#! /usr/bin/env python2
./TorrentToMedia.py:#!/usr/bin/env python2
XxUnkn0wnxX-iMac:nzbToMedia ovidijus$ egrep 'env python$' -R .
./libs/babelfish/data/get_files.py:#!/usr/bin/env python
./libs/babelfish/tests.py:#!/usr/bin/env python
./libs/chardet/chardetect.py:#!/usr/bin/env python
./libs/guessit/__init__.py:#!/usr/bin/env python
./libs/guessit/__main__.py:#!/usr/bin/env python
./libs/guessit/__version__.py:#!/usr/bin/env python
./libs/guessit/containers.py:#!/usr/bin/env python
./libs/guessit/date.py:#!/usr/bin/env python
./libs/guessit/fileutils.py:#!/usr/bin/env python
./libs/guessit/guess.py:#!/usr/bin/env python
./libs/guessit/hash_ed2k.py:#!/usr/bin/env python
./libs/guessit/hash_mpc.py:#!/usr/bin/env python
./libs/guessit/language.py:#!/usr/bin/env python
./libs/guessit/matcher.py:#!/usr/bin/env python
./libs/guessit/matchtree.py:#!/usr/bin/env python
./libs/guessit/patterns/__init__.py:#!/usr/bin/env python
./libs/guessit/patterns/extension.py:#!/usr/bin/env python
./libs/guessit/patterns/numeral.py:#!/usr/bin/env python
./libs/guessit/plugins/__init__.py:#!/usr/bin/env python
./libs/guessit/plugins/transformers.py:#!/usr/bin/env python
./libs/guessit/quality.py:#!/usr/bin/env python
./libs/guessit/slogging.py:#!/usr/bin/env python
./libs/guessit/test/__init__.py:#!/usr/bin/env python
./libs/guessit/test/__main__.py:#!/usr/bin/env python
./libs/guessit/test/guessittest.py:#!/usr/bin/env python
./libs/guessit/test/test_api.py:#!/usr/bin/env python
./libs/guessit/test/test_autodetect.py:#!/usr/bin/env python
./libs/guessit/test/test_autodetect_all.py:#!/usr/bin/env python
./libs/guessit/test/test_doctests.py:#!/usr/bin/env python
./libs/guessit/test/test_episode.py:#!/usr/bin/env python
./libs/guessit/test/test_hashes.py:#!/usr/bin/env python
./libs/guessit/test/test_language.py:#!/usr/bin/env python
./libs/guessit/test/test_main.py:#!/usr/bin/env python
./libs/guessit/test/test_matchtree.py:#!/usr/bin/env python
./libs/guessit/test/test_movie.py:#!/usr/bin/env python
./libs/guessit/test/test_quality.py:#!/usr/bin/env python
./libs/guessit/test/test_utils.py:#!/usr/bin/env python
./libs/guessit/textutils.py:#!/usr/bin/env python
./libs/guessit/transfo/__init__.py:#!/usr/bin/env python
./libs/guessit/transfo/expected_series.py:#!/usr/bin/env python
./libs/guessit/transfo/expected_title.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_bonus_features.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_country.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_date.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_episode_details.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_episode_info_from_position.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_episodes_rexps.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_filetype.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_idnumber.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_language.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_movie_title_from_position.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_properties.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_release_group.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_video_rexps.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_weak_episodes_rexps.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_website.py:#!/usr/bin/env python
./libs/guessit/transfo/guess_year.py:#!/usr/bin/env python
./libs/guessit/transfo/split_explicit_groups.py:#!/usr/bin/env python
./libs/guessit/transfo/split_on_dash.py:#!/usr/bin/env python
./libs/guessit/transfo/split_path_components.py:#!/usr/bin/env python
./libs/pysrt/commands.py:#!/usr/bin/env python
./libs/requests/certs.py:#!/usr/bin/env python
./libs/requests/packages/chardet/chardetect.py:#!/usr/bin/env python
./libs/subliminal/score.py:#!/usr/bin/env python
./libs/subliminal/tests/__init__.py:#!/usr/bin/env python
./libs/subliminal/tests/test_providers.py:#!/usr/bin/env python
./libs/subliminal/tests/test_subliminal.py:#!/usr/bin/env python

as i need it to point to the homebrew version of python not the SYS ver. so since Sab tells nzbtomedia to use the stuff in /usr/bin thats the sys ver.

so even if i hard code the few files that have #!/usr/bin/env python2 set if some other file is run that has 
#!/usr/bin/env python set and that uses the sys ver issue may happen as some scripts will be using the brewed version and other the sys ver without all the python components & modules installed..

**Comment by lennyk** [comment]
@XxUnkn0wnxX I also struggled with this today. I found the most elegant solution to be:

`sudo launchctl config user path /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

It seems to be the new way to change PATH within launchctl scripts.

**Comment by nbara** [comment]
I'm a bit late to the party but, how are we supposed to solve this? 

I tried the symlink method ` sudo ln -sf /usr/bin/python /usr/local/bin/python2 ` but I still get the same annoying error in SAB:

```env: python2: No such file or directory```

**Comment by nbara** [comment]
Up.

Anyone manage to get this working with non system python installed (Anaconda, Canopy, Homebrew)?

**Comment by Sarcas666** [comment]
Using non-system python (Homebrew) on OSX 10.11.3, but nzbtomedia just doesn't work for me. Keep getting the "env: python2: No such file or directory" error. Pity.

**Comment by nbara** [comment]
Up. Is there really no solution for this?

**Comment by Sarcas666** [comment]
Bumping the thread. Would really like to be able to use nzbtomedia...

**Comment by clinton-hall** [comment]
Just checkout the OSX branch

    git checkout osx

**Comment by Tjiet** [comment]
Well now this comes back with MacOS Sierra :-(

Did the ln trick as above...

Running the commmand from terminal give me the correct python version

/usr/bin/env python2
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

Any ideas as to why it fails in sabnzbd osx:
env: python2: No such file or directory

**Comment by Tjiet** [comment]
is it possible to create a nightly-osx ?
That way we can use the nightly version/features with osx support

**Comment by XxUnkn0wnxX** [comment]
I had this solved a while ago via [This](https://gist.github.com/XxUnkn0wnxX/bf3d848232f4a71b6556)

I have this saved in a .sh file:

#!/usr/local/bin/bash
source ~/.bash_profile
python ~/"Apps/nzbToMedia/nzbToSickBeard.py" "$@"

I'm using brewed bash btw, normal people would use #!/usr/bin/bash

the "Apps" is the folder where I'm keeping nzbtomedia git folder, "~/" = Home Root Folder. EG ur Username Folder.

the "source ~/.bash_profile" main part that makes it work since I load my bash profile b4 actual script it uses correct python, brewed ver with all modules installed. and SR is running under my brewed ver as well.

as I launch it with an Automater script:

#!/usr/local/bin/bash
source ~/.bash_profile
python ~/"Apps/SickRage/SickBeard.py" -d &

**Comment by XxUnkn0wnxX** [comment]
@lnhrdt your solution

`sudo launchctl config user path /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

may not work as launchctl.conf in etc no longer loads values placed there, I believe from Yosemite this was depreciated.

although there is a way via a launch agent plist file you could create but it get a bit complex.

**Comment by XxUnkn0wnxX** [comment]
well I believe found another way to solve issues:

1st create this and save it: http://apple.stackexchange.com/questions/106355/setting-the-system-wide-path-environment-variable-in-mavericks (the one where it say my.startup.plist)

then execute this: defaults write com.apple.dt.Xcode UseSanitizedBuildSystemEnvironment -bool NO

then this: sudo launchctl config user path $PATH

then make sure u have this line here in ur .bash_profile (found in ~/ : you can do open ~/ in terminal to open the folder)

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH

then make sure ur /etc/paths look like this: (/usr/local/bin has to be 1st same with .bash_profile)

/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

now reboot computer and untick the "Reopen windows when logging back in" [Important u untick it]

you can retick it again if u reboot 2nd time later on.

once rebooted do launchctl getenv PATH within terminal it should print out this:

/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

issues should be resolved now, hopefully.

**Comment by jcvignes** [comment]
@XxUnkn0wnxX I've used your method and the getenv path gives the right result but I still have the "Python2 no such file or directory" error… (El capitan, i have python 2 and Python 3 cohabiting). Could you help? Thanks!

**Comment by clinton-hall** [comment]
@XxUnkn0wnxX 
Are you able to confirm if the master branch now works on OSX? This has been updated to now call `python` and not `python2` this also now supports python 2 or python 3.

If this is working on master, I ant to push all OSX branch users back to master so that they can remain up to date and even use dev/nightly...
