### ISSUE TITLE
SABNZB El Capitan WorkAround Script

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [clinton-hall/nzbToMedia#845]
Hi, i been trying to figure a workaround to get NZBtoMedia to work on El Capitan properly as this command no longer works since the new SIP Protection:

sudo ln -s /usr/local/bin/python2 /usr/bin/python2

so i want to call out nzbToSickBeard.py via a bash script but unsure how to fully set the Download Dir when Sab Calls the script & the category:
# !/usr/local/bin/bash

source ~/.bash_profile
python /Users/USER/Apps/SickRage/contrib/nzbToMedia/nzbToSickBeard.py $@

with that it works but i get the following error:

 [03:58:45] [INFO]::MAIN: Loading config from [/Users/USER/Apps/SickRage/contrib/nzbToMedia/autoProcessMedia.cfg]
[03:58:45] [INFO]::MAIN: Checking database structure...
[03:58:45] [INFO]::MAIN: Checking if git needs an update
[03:58:47] [INFO]::MAIN: No update needed
[03:58:47] [INFO]::MAIN: nzbToMedia Version:1cd64053b0da1d351bb6af392e1ebb904c6b6ce2 Branch:master (Darwin 14.5.0)
[03:58:47] [INFO]::MAIN: #########################################################
[03:58:47] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[03:58:47] [INFO]::MAIN: #########################################################
[03:58:47] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[03:58:47] [ERROR]::MAIN: Category:[Bad] is not defined or is not enabled. Please rename it or ensure it is enabled for the appropriate section in your autoProcessMedia.cfg and try again.

any one know how to get the category working?

**Comment by XxUnkn0wnxX** [comment]
or is there a way i can edit the nzbToSickBeard.py when run it loads the path variables from
source ~/.bash_profile
first? as i know this would resolve my issue + this way nzbtomedia will file 7zip & unrar instead of looking for it in /usr/bin

**Comment by BurningTheSky** [comment]
Did you find a short term work around for this? Did I see you say something about manually running it works for now? Hopefully this can be resolved soon!

**Comment by eneglan** [comment]
Just updated my mac mini to el capitan and facing the same problem. Would this be a quick workaround for this? http://www.macbartender.com/system-item-setup/

Will try it later today and let you know. In the long term it would obviously be great if nzbToMedia could use the brew python or make use of the .path variables as mentioned in your other thread XxUnkn0wnxX.

**Comment by XxUnkn0wnxX** [comment]
yes via a bash script but i haven't gotten it to fully work the script runs but then nzbtomedia gives me errors saying wrong category meaning it is not detecting the parameters set by SabNZB.

i been waiting for some 1 to find the answer for that on why it doesnt work:

you can view the discussion here: http://forums.sabnzbd.org/viewtopic.php?f=2&t=19553&p=102115

for now all i did is edit all these files:
nzbToCouchPotato.py
nzbToGamez.py
nzbToHeadPhones.py
nzbToMedia.py
nzbToMylar.py
nzbToNzbDrone.py
nzbToSickBeard.py
TorrentToMedia.py

i replaced the #!/usr/bin/env python2 with #!/usr/local/bin/python2 for the moment but 7zip and unrar by the script won't work as it tries to look for them in /usr/bin. i used to have a fix for it via a soft link to /usr/bin but in el Capitan i can no longer do that. 

Scikrage has no issues since i load up the paths from my .bash_profile b4 it is run. i been trying to do the same for nzbtomedia but without success yet.

**Comment by XxUnkn0wnxX** [comment]
@eneglan yes thats about workaround then create the soft links from /usr/local/bin/python2 to /usr/bin/python2

but each OS update apple hinted they will re-enable SIP and chant changes made in any SIP protected sys areas like /usr/bin would be reset.

**Comment by XxUnkn0wnxX** [comment]
and like i said this is the script i am trying to get to work:

#!/usr/local/bin/bash
source ~/.bash_profile
python /Users/USER/Apps/SickRage/contrib/nzbToMedia/nzbToSickBeard.py $@

it runs but i get category errors. when Sab Runs nzbToSickBeard.py under normal conditions. the script auto detects the category set in Sab & download Directory but since i am trying to get sad to run my script first to load the path variables then run the nzbToSickBeard.py script it giving me errors.
you will also notice i am using the brewed version of bash #!/usr/local/bin/bash

you can install it via brew then

#Optional#
# Use Brewed Bash:
brew install bash
sudo -s
echo /usr/local/bin/bash >> /etc/shells
chsh -s /usr/local/bin/bash (run this under sudo -s and under your username then open dermal preferences, General and set command (complete path to: /usr/local/bin/bash)) restart terminal

**Comment by eneglan** [comment]
@XxUnkn0wnxX I just tried the workaround with disabling csrutil and it works. For the time being that's enough for me in the hopes that @clinton-hall will offer his insights on this specific problem in the next weeks. Autoupdate is turned off on my download machine so I'm not too worried about Apple overwriting the symlink.

**Comment by eneglan** [comment]
Ah, and you can turn on SIP again after creating the symlink, it stays in place. Probably until the next OS update.

**Comment by BurningTheSky** [comment]
I'm just looking for the simplest short term solution, hopefully wel can get a long term one soon. @echel0n so do you just set to disabled, recreate the link, set to enabled again and happy days for now?

**Comment by XxUnkn0wnxX** [comment]
@BurningTheSky i would recommend just edit the python file in the main Directory replace the #!/usr/bin/env python2 with #!/usr/local/bin/python2

**Comment by BurningTheSky** [comment]
@XxUnkn0wnxX just the nzbToMedia.py file or all the ones you mentioned above?

**Comment by XxUnkn0wnxX** [comment]
well for Sab i just edit
nzbToMedia.py & nzbToSickBeard.py

for you mainly nzbToMedia.py and what ever other script that you are using EG if couch potato edit the couch potato script etc...

**Comment by BurningTheSky** [comment]
So I changed the first line to #!/usr/local/bin/python2 but now I get "Cannot run script /path/to/nzbToSickBeard.py"

**Comment by XxUnkn0wnxX** [comment]
@BurningTheSky did you install python via brew 1st?

make sure homebrew is installed and u have the /usr/local Dir

set up brew perms like so: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md

then do brew install python

if already installed upgrade it to latest via brew update, brew upgrade

then brew unlink python && brew link python --overwrite --force

and check that ur /etc/paths are set to this:
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

then in terminal do which python and it should point to /usr/local/bin you can also do which python2 it will give u same result. once it set then it will work.

or you can use the system python instead of python do just do #!/usr/local/bin/python which is also python.

but i prefer the brewed version less issues + all my python dependancies and modules are installed via the brewed version.

**Comment by XxUnkn0wnxX** [comment]
also check you ~/.bash_profile and see if its correct it can be messy in there. its usually in your home folder as a hidden file. 

mine looks like this:

export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/lib:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/opt/coreutils/libexec/gnubin
export PATH=/usr/local/sbin:$PATH
export HOMEBREW_GITHUB_API_TOKEN=Hidden
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/opt/local/bin:/usr/local/git/bin
export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH"export PATH="/usr/local/sbin:$PATH"

where "Hidden" is the Github API key you should be using if you run into brew issues. recommend you have this set.. Documentation: https://gist.github.com/christopheranderton/8644743

**Comment by BurningTheSky** [comment]
It's been so long since I first set it up that I'm not sure, I have brew installed so I may have but it definitely isn't an el install, it would have been a while back. I will give your suggestions a go. I also don't appear to have a ~/bash_profile... Odd!

**Comment by XxUnkn0wnxX** [comment]
well u can use my bash profile it won't give u any issues and most os's have a similar profile. you will just need to get ur OWN Github API key...

just save it in text editor .bash_profile un your users home directory EG ur username Dir
~/ simply points to your home directory.

you can clean up the bash profile paths further if you wish remove and directors you may not have in ur System EG /usr/X11 or /usr/local/MacGPG2/bin

the double colon : is simply a separator between each path value.
and $PATH is simply a shortcut to the rest of your path variables EG:
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/lib:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/opt/coreutils/libexec/gnubin

when it comes to third party scripts EG NBZtoMedia or Sickrage etc i prefer to use the homebrew stuff much more reliable then using Apples defaults. EG outdated and unable to update..

also i use the brewed version of github with brewed openssl as apple's is way outdated 0.98 and causes many issues with todays up to date scripts and software..

**Comment by BurningTheSky** [comment]
What does the export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH"export PATH="/usr/local/sbin:$PATH" part of your profile do?

**Comment by BurningTheSky** [comment]
Looks like Python wasn't installed via brew, installing it via that now. Do I need to do anything with the version I did have installed?

**Comment by BurningTheSky** [comment]
That all looks like it's working, thanks!

**Comment by XxUnkn0wnxX** [comment]
PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH" <-- can be ignored unless u installed coreutils via brew then its needed

export PATH="/usr/local/sbin:$PATH" <-- this needed brew doctor said this should be in there

**Comment by eneglan** [comment]
@BurningTheSky just as a quick feedback to your question, that was exactly what I did. But you seem to have gotten @XxUnkn0wnxX solution to work.

**Comment by clinton-hall** [comment]
sorry I haven't chimed in yet...
To be honest, I'm not sure how best to tackle this. I looked at an automated script to try and select the "best" python version some time ago, but that was messy.

As it is, the current she bang (hash bang) line works for most Posix systems, but there are a few exceptions.

I'm not sure the logic behind what apple has done here, but it seems rather frustrating.

as far as keeping your changes, and still updating, try turning off auto update, then edit your files.
When you want to update, do 

```
git stash
git pull
git stash 
```
you could create a simple script to do this, then add that to a cron job etc to do periodically.

**Comment by XxUnkn0wnxX** [comment]
well @clinton-hall i was thinking of running ur script via a bash script but i keep getting that category error.

i would prefer to do this rather then editing ur script because, then i get load the path variables first before the script runs. i know usually the script should just work and load up the variables from /etc/paths or bash profile but this doesnt work when running the Compiled App version of Sab so the script doesnt see those path variables set.

so from the Original Post:

#!/usr/local/bin/bash
source ~/.bash_profile
python /Users/USER/Apps/SickRage/contrib/nzbToMedia/nzbToSickBeard.py $@

i want this to work as this way i get access to 7zip and all the other Dependancies the script uses

editing your script with #!/usr/local/bin/python2 is just a crude way doing it & it doesnt load up the other path variables EG where 7zip is located. which is /usr/local/bin but Sab Insists that its in /usr/bin due to the paths issue it has...

so would you know how to properly get 
python /Users/USER/Apps/SickRage/contrib/nzbToMedia/nzbToSickBeard.py (inside nabtomedia.sh)

working? 

the Sab admin said i should use $@ at the end of the command but it doesn't work $@ = input all SabNZB variables. so how would i pipe in the category and the Dir like when Sab runs ur script Normally? within my simple bash script?

**Comment by clinton-hall** [comment]
I would have expected `python /Users/USER/Apps/SickRage/contrib/nzbToMedia/nzbToSickBeard.py "$@"` should work...

**Comment by XxUnkn0wnxX** [comment]
ok i think i got it to work when i did it with "" on each end it worked without it it didn't work strange...

**Comment by XxUnkn0wnxX** [comment]
ok after lots of trial and error i finally got it to work & without symtext errors:

#!/usr/local/bin/bash
source ~/.bash_profile
python ~/"Apps/SickRage/contrib/nzbToMedia/nzbToSickBeard.py" "$@"

it should work like this Apps/SickRage/contrib/nzbToMedia/nzbToSickBeard.py without the "" but the "" must be set for the $@at the end.

~/ <-- points to your user home directory other wise copy the full path to where your script is.
EG
/Users/USER/Apps/SickRage/contrib/nzbToMedia/nzbToSickBeard.py

be sure there is no extra line in the bash script there should be only 3 lines of code.

**Comment by gigantaur** [comment]
Firstly thanks so much @XxUnkn0wnxX and @clinton-hall for doing the hard detective work - these posts on using a shell script to launch the relevent nzbtomedia scripts were so helpful.

This has got me wondering - why does sabtosickbeard.py run ok from sabnzdb without a shell script to launch it ?

Is it due to the env shebang at the start?

#!/usr/bin/env python

I found a comment [here](http://stackoverflow.com/questions/1352922/why-is-usr-bin-env-python-supposedly-more-correct-than-just-usr-bin-pyt) which says using #!/usr/bin/env python and virtualenvs will execute the script in current venv

Apparently it is also possible to do:

#!/usr/bin/env python2.7

This at the limit of my posix knowledge so appreciate anyone chiming in
