### ISSUE TITLE
"Error while opening encode for output stream"

### ISSUE THREAD

**Issue by dsh** [clinton-hall/nzbToMedia#849]
I had a new file land last night that nzbToMedia tried to process. It looks like a BluRay rip. It generated this ffmpeg command.

```
nice -n10 ionice -c2 -n0 /usr/bin/ffmpeg -loglevel warning -hwaccel auto -fflags +genpts -i /scratch/downloads/complete/tv/Humans.S01E01.1080p.BluRay.X264-DEFLATE English/Humans.S01E01.1080p.BluRay.X264-DEFLATE.mkv -i /scratch/downloads/complete/tv/Humans.S01E01.1080p.BluRay.X264-DEFLATE English/Humans.S01E01.1080p.BluRay.X264-DEFLATE.sub -i /scratch/downloads/complete/tv/Humans.S01E01.1080p.BluRay.X264-DEFLATE English/Humans.S01E01.1080p.BluRay.X264-DEFLATE.idx -map 0:0 -map 0:1 -map 0:1 -map 0:2 -map 0:3 -map 1:0 -map 2:0 -c:v copy -c:a:0 aac -strict -2 -ac:a:0 2 -b:a:0 160000 -c:a:1 ac3 -c:s mov_text -metadata:s:s:2 language=X264-DEFLATE -metadata:s:s:3 language=X264-DEFLATE -movflags +faststart /scratch/downloads/complete/tv/Humans.S01E01.1080p.BluRay.X264-DEFLATE English/Humans.S01E01.1080p.BluRay.X264-DEFLATE.mp4
```

It output this error. 

```
Error while opening encoder for output stream #0:5 - maybe incorrect parameters such as bit_rate, rate, width or height
```

I googled, but it didn't help me.

Ideas?

**Comment by dsh** [comment]
My config is in https://gist.github.com/dsh/11ad06818edd89ac4ad1

Also

    # ffmpeg -version
    ffmpeg version 2.8 Copyright (c) 2000-2015 the FFmpeg developers
    built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
    configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libdcadec --enable-libfreetype --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvo-aacenc --enable-libvidstab
    libavutil      54. 31.100 / 54. 31.100
    libavcodec     56. 60.100 / 56. 60.100
    libavformat    56. 40.101 / 56. 40.101
    libavdevice    56.  4.100 / 56.  4.100
    libavfilter     5. 40.101 /  5. 40.101
    libavresample   2.  1.  0 /  2.  1.  0
    libswscale      3.  1.101 /  3.  1.101
    libswresample   1.  2.101 /  1.  2.101
    libpostproc    53.  3.100 / 53.  3.100

**Comment by clinton-hall** [comment]
the part that looks questionable to me is `-metadata:s:s:2 language=X264-DEFLATE`
For some reason the external subs appears to have some strange metadata... or my script is readint he wrong field.

can you manually try
```
nice -n10 ionice -c2 -n0 /usr/bin/ffmpeg -loglevel warning -hwaccel auto -fflags +genpts -i /scratch/downloads/complete/tv/Humans.S01E01.1080p.BluRay.X264-DEFLATE English/Humans.S01E01.1080p.BluRay.X264-DEFLATE.mkv -i /scratch/downloads/complete/tv/Humans.S01E01.1080p.BluRay.X264-DEFLATE English/Humans.S01E01.1080p.BluRay.X264-DEFLATE.sub -i /scratch/downloads/complete/tv/Humans.S01E01.1080p.BluRay.X264-DEFLATE English/Humans.S01E01.1080p.BluRay.X264-DEFLATE.idx -map 0:0 -map 0:1 -map 0:1 -map 0:2 -map 0:3 -map 1:0 -map 2:0 -c:v copy -c:a:0 aac -strict -2 -ac:a:0 2 -b:a:0 160000 -c:a:1 ac3 -c:s mov_text -movflags +faststart /scratch/downloads/complete/tv/Humans.S01E01.1080p.BluRay.X264-DEFLATE English/Humans.S01E01.1080p.BluRay.X264-DEFLATE.mp4
```

If this works we know the issue is with the metadata...

**Comment by dsh** [comment]
My guess was that the script was interpreting X264-DEFLATE as a language, like "en" or "nl". 

I had to adjust your command, you had some extra "English" strings in there. 

    nice -n10 ionice -c2 -n0 /usr/bin/ffmpeg -loglevel warning -hwaccel auto -fflags +genpts -i /scratch/downloads/complete/tv/Humans.S01E01.1080p.BluRay.X264-DEFLATE/Humans.S01E01.1080p.BluRay.X264-DEFLATE.mkv -i /scratch/downloads/complete/tv/Humans.S01E01.1080p.BluRay.X264-DEFLATE/Humans.S01E01.1080p.BluRay.X264-DEFLATE.sub -i /scratch/downloads/complete/tv/Humans.S01E01.1080p.BluRay.X264-DEFLATE/Humans.S01E01.1080p.BluRay.X264-DEFLATE.idx -map 0:0 -map 0:1 -map 0:1 -map 0:2 -map 0:3 -map 1:0 -map 2:0 -c:v copy -c:a:0 aac -strict -2 -ac:a:0 2 -b:a:0 160000 -c:a:1 ac3 -c:s mov_text -movflags +faststart /scratch/downloads/complete/tv/Humans.S01E01.1080p.BluRay.X264-DEFLATE/Humans.S01E01.1080p.BluRay.X264-DEFLATE.mp4

Same problem without the metadata.

    Error while opening encoder for output stream #0:5 - maybe incorrect parameters such as bit_rate, rate, width or height
