### ISSUE TITLE
[Solved] Unable to migrate config file

### ISSUE THREAD

**Issue by Tritonpad** [clinton-hall/nzbToMedia#850]
Hi Folks,
First of all, I have to apologyze for my bad english cause I Am French... But I'll do my best, I swear. Till now, you may not have noticed
While I was seeking infos/solutions about a similar issue with NzbToMedia, I came aroud here...
Clinton, if you think it would be better to talk about postProcess on another board, just let me know.

so... Here's a ctrl+v :

[05:58:28] [ERROR]::MAIN: Unable to migrate config file C:\nzbToMedia\autoProcessMedia.cfg, exiting ...

The point is that I am actually not at home, so that I won't be able to test untill tonight (in France). But to make you wait, I can give you some details about what I use and how it is organised.
Sabnzbd + SickRage + Couchpotato + Headphones (but I don't really care about this one for the moment) and of course NzbToMedia.

SickRage was git cloned in C:\SickRage, so does NzbToMedia (C:\NzbToMedia)
Sab was installed in program files (x86).
Python 2.7.10 ok (with variable environnement path added)
Git of course
PyOpenSSL ok
Cheetah ok
PyWin ok
At the moment, I have only run tests with SickRage concernning postProcess. But I am completely new about all this, I have to say... To begin with, do you have advices about the locations of SickRage, NzbToMedia and Sab on C:\ ?? Considering postprocess with SickRage only, which py are to be modified manually ? (I know AutoProcessMedia.cfg must be edited, but I think I built it the bad way... explaining : I copied the ".spec", pasted it on the desktop, renamed it, and pasted back in NzbToMedia : I did this because the R/W rights were not correct at that time, but i modified since then...)

Thanx for reading dudes, can't wait to discuss about this with you !

edit : Now that I am home, I just can't find the correct log to show you... I guess it is all about Sabnzbd, but I don't know where yhe logs are located, and if there are options to configure to show more interresting infos.

**Comment by clinton-hall** [comment]
The log file itself is created in C:\nzbToMedia\logs\nzbtomedia.log

I am guessing there is some bad formatting in autoProcessMedia.cfg
Can you please send this to me for testing `fock_wulf@hotmail.com`
edit out any api/user/pass etc.

**Comment by Tritonpad** [comment]
email sent Clinton ;)
Thank you !

**Comment by Tritonpad** [comment]
problem solved By Clinton : be carefull not to have twice the same category in autoProcessMedia.cfg
The [[films]] category was present two times in couchpotato settings.
So thank you a lot Clinton.
All I have to do now is to make the whole stuff work (SR + CP + HP)
So just give me 1 day or two before editing the topic to [solved], Thanx !

**Comment by cdobbs9** [comment]
I know this an old, but I am having the same issue.

Running on a NAS
NZBGET 21.1-testing-r2311

If I run the script from the command line, this is what I get

[21:33:33] [ERROR]::MAIN: Unable to migrate config file /volume1/Download/nzbToMedia/autoProcessMedia.cfg, exiting ...
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f676696cb10>> ignored

I have looked through the autoProcessMedia.cfg and verified no duplicated categories and I removed quotes around paths.

**Comment by clinton-hall** [comment]
can you please send the autoProcessMedis.cfg file to `fock_wulf@hotmail.com`
edit out any api/user/pass etc.

**Comment by clinton-hall** [comment]
The issue was multiple duplicate sub-sections.

I have just added error logging that will display the line in the config where the duplicate or corrupt value is found.
Currently in nightly build.
