### ISSUE TITLE
Failed download handling, script looking in wrong folder?

### ISSUE THREAD

**Issue by TomNugter** [clinton-hall/nzbToMedia#854]
Hi,

I still struggling with the NZBTOSICKBEARD script (with sickrage). I though I had everything working, but for some reason the failed download handling is not working (anymore) for me. (It seems to work, but now i'm not sure anymore if the entries in ' failed downloads'  in sickrage where manual added or not).

Successful downloads are handled without any issues. After a successful download the download is picked up and processed beautifully and Sickrage get notified of the successful download. However, with fails downloads the script fails and ' Failed Downloads'  is not updated.

 With failed files I'm getting errors similar to this:
<code>
INFO    Thu Oct 15 2015 20:07:30    nzbToSickBeard: [18:07:30] [POSTPROCESS]::SICKBEARD: Unable to figure out what folder to process. If your downloader and SickRage aren't on the same PC make sure you fill out your TV download dir in the config.
INFO    Thu Oct 15 2015 20:07:30    nzbToSickBeard: [18:07:30] [POSTPROCESS]::SICKBEARD: Trying to use folder /mnt/nas/download/sickrage/Gotham.S02E04.720p.WEB-DL.DD5.1.H.264-NTb.#1048
INFO    Thu Oct 15 2015 20:07:30    nzbToSickBeard: [18:07:30] [POSTPROCESS]::SICKBEARD: TV_DOWNLOAD_DIR: /mnt/nas/download/sickrage
INFO    Thu Oct 15 2015 20:07:30    nzbToSickBeard: [18:07:30] [POSTPROCESS]::SICKBEARD: Processing folder /i-data/2d57e72c/HD/download/inter/Gotham.S02E04.720p.WEB-DL.DD5.1.H.264-NTb.#1048
INFO    Thu Oct 15 2015 20:07:23    nzbToSickBeard: [18:07:23] [POSTPROCESS]::SICKBEARD: FAILED: The download failed. Sending 'failed' process request to sickrage branch
</code>

As you see the script is looking for files to process in /mnt/nas/download/sickrage (wich is actually /i-data/2d57e72c/HD/download/sickrage, but this is linked in the settings) and this is most likely where it goes wrong. In this folder are only downloads that are successfully downloaded, NZBGET downloads incomplete files in a different folder (/i-data/2d57e72c/HD/download/inter or ${MainDir}/inter) and are only moved to after successful download to another folder (${MainDir}/dst for non categories downloads and /i-data/2d57e72c/HD/download/sickrage for sickrage downloads)

This assumption is supported by the fact that if a download fails, the downloaded files are still in /i-data/2d57e72c/HD/download/inter

Did I miss a setting somewhere? Any help is very much appreciated

Kind regards,
Tom

p.s I already shared some settings in https://github.com/clinton-hall/nzbToMedia/issues/825 
Please let me know if you need any more information from me.

Edit: Just after posting I found out that setting sbdelete_failed was not enabled. I've set that to 1 and now failed downloads are removed from the ' inter'  folder. However, I still don't understand the error that the script is failing while looking for files in /i-data/2d57e72c/HD/download/sickrage, there shouldn't be any, right?

**Comment by clinton-hall** [comment]
The issue is in SickRage...
These scripts tell it where the failed files are `SICKBEARD: Processing folder /i-data/2d57e72c/HD/download/inter/Gotham.S02E04.720p.WEB-DL.DD5.1.H.264-NTb`

Have you looked at the actual SickRage logs? have you tried to manually postprocess this as failed from within sickrage?

In SickRage Web UI config/postProcessing/ have you enabled "Use Failed Downloads"?

**Comment by TomNugter** [comment]
I can't find anything in Sickrage logs. What should I be looking for? I only see a message that a used logged on:
2015-10-25 20:21:44 INFO     TORNADO :: User logged into the SickRage web interface

Manual postprocessing does't change anything, same result.

Sickrage's " use failed downloads"  is on, I assume this is meant to be on?

**Comment by clinton-hall** [comment]
So you did a manual process from SickRage (Shiws, manual post-processing)?
The only other issue I think this might be is that SickRage doesn't have permissions to see inside the "inter" directory. So it then reverts to the default process directory.

Check your permissions.

**Comment by TomNugter** [comment]
I did a manual postprocess in nzbget, not in sickrage. I wasn't even ware that it was possible. Do you mean the magnify glass? AFAIK that download the whole show again, right?

Anyway, it's hard to reproducer, because failed downloads do not happen a lot. I had only one show that was marked as bad in the last week or so, but it looks like the show is marked as downloaded anyhow, although it still isn't in my failed downloads list in Sickrage.

Just to be sure: If a download is marked as bad in nzbget, it SHOULD show up in the failed downloads list in Sickrage?If not, I might be checking the wrong thing the whole time. :)

Anyhow, I will check permissions also. Thanks for the help!

**Comment by clinton-hall** [comment]
InSickRage, click the "Home" menu at top, there is a drop-down with an option to manual post-process.
You can point this to the directory of the failed download, and select "failed".
If it still can't find anything the issue is with sickrage (permissions).

**Comment by TomNugter** [comment]
Thanks, I didn't know about that option, that's handy to know. I suspect permissions as well. I'll wait until another post process failed and continue investigate. 

Just to make sure i know where to look for: If you script marks a file as failed, it should show up in the ' failed downloads'  in sickrage, right?
