### ISSUE TITLE
NzbToMedia installation synology

### ISSUE THREAD

**Issue by clarkzara** [clinton-hall/nzbToMedia#856]
Hi im a novice user of synology My setup is sickrage and  nzbget and postprocessing is being done by sickrage. I'm planning to use nzbtomedia since i would like to take advantage of the failed downloading handling feature of said script. Anyway, i just would like confirm my understatnding of the installation procedure. First, python3 and 2.7 are already installed via synocommunity package. Install via git, i assume i would do this thru a ssh terminal or putty? Then intended scripts directory, can i create a separate folder then set read and write permission settings to everyone? Then via putty go to the said folder/directory then key in this command? git clone https://github.com/clinton-hall/nzbToMedia.git

**Comment by clarkzara** [comment]
Symlink Python libraries kindly confirm if i need to this

**Comment by ecnahc515** [comment]
@clarkzara You simply need to `git clone` or copy the nzbToMedia folder into your synology NAS, and then setup your downloader to use the scripts. Also you'll need to copy the config file and update it, but the install process is simple, it just needs to be on the NAS with the ability to be read by whatever program is invoking it.

**Comment by clarkzara** [comment]
Thanks for the reply. Im having difficulty executing git clone command in my synology. Can i copy the files from my pc which i have downloaded via git?

**Comment by clinton-hall** [comment]
Yes, you can copy these, but this will probably prevent you from using auto-updating, and you need to be careful with file/folder permissions to be able to run the scripts.

**Comment by clarkzara** [comment]
Thanks for the reply clinton, i can't execute git clone command in my synology. Tried to execute the same command in my pc running windows and it worked. Im not sure if i missed something in my synology. I installed python and python3, and git server thru synocommunity. the result whenever i typed git clone command is  result is -ash: git:not found.

**Comment by clinton-hall** [comment]
Might be a PATH issue on Syno?
Or you might need a git / git client app, not git server?

Try
find / -name 'git'

**Comment by clarkzara** [comment]
yup i did install the git app, i think you need that app to install sickrage? anyway executed that command. here is the result:
DiskStation> find / -name 'git'
/usr/local/git
/usr/syno/etc/packages/git
/var/packages/git
/volume1/@tmp/pkglist.tmp/icon/AVAIL/OTHER/git
/volume1/@tmp/@synopkg/@download/git
/volume1/@appstore/git
/volume1/@appstore/git/bin/git
/volume1/@appstore/git/libexec/git-core/git

**Comment by clinton-hall** [comment]
In stead of "git clone" or "git pull", try the full path "/usr/local/git clone" or "/usr/local/git pull"

**Comment by clarkzara** [comment]
thanks will try

**Comment by clarkzara** [comment]
hello again, tried full path..i got "Permission denied", should this be the reason why i can't do "git clone"? anyway, appreciate your usual support.

**Comment by chancez** [comment]
@clarkzara if you never figured it out, you might need to be the `root` user, which you can do by running `sudo su` and typing your sudo password. Alternatively you can `sudo /usr/local/ git clone`, to run the command with elevated privileges.

**Comment by djdaniels90** [comment]
I have been debugging in depth on my synology. In order to run git you need the full path as the appstore path is not in the PATH.

`/volume1/@appstore/git/bin/git clone`

The permission denied error is because you need to run it as root so try putting a sudo infront of that.  Alternatively you could run `sudo chown <user>:users -R /volume1/@appstore/git` replace the <user> with your user.  I am actively getting pretty in depth with the code base now in order to resolve some of my problems which are mostly centered around permissions (nzbToMedia outputs as root so plex can't see the new files).

I assume you are logged in as admin on the synology.  When using sudo, root password is your admin password.  But as far as i can tell root is on no login so you can't ssh in with it.

**Comment by MrCee** [comment]
@clarkzara

After you SSH into synology as your username, 

`ssh -l USERNAME  192.168.X.X` 
You need to elevate permissions to root.
`sudo su -`

I am assuming you have installed GIT from the Synology Package Centre. If not, do so.
Next you need to create a symlink so GIT commands work across all apps.
```
ln -s /volume1/@appstore/git/bin/git           /usr/local/bin/git
```

ln -s  (Creates a symbolic link)
/volume1/@appstore/git/bin/git  (The location to link to)
 /usr/local/bin/git (The location you have stored this to which is in your PATH by default)

You should be able to type `git` anywhere now and it will run.
