### ISSUE TITLE
nzbToMedia Unable to migrate config file

### ISSUE THREAD

**Issue by kennexDEWA** [clinton-hall/nzbToMedia#857]
Hi Clinton,
For the last couple of nights ive been sitting at my laptop trying to fix an issue with your post processing script.

On completion of download, SABnzbd runs the script and errors out with:
[06:38:08] [ERROR]::MAIN: Unable to migrate config file D:\SickRage-master\SickRage-master\autoProcessTV\autoProcessMedia.cfg, exiting ...

The config file has been copied, renamed and edited with what i believe are the correct settings following your install guide.

I've searched multiple forums, read other users posts and tried all fixes still to no avail.. Any help would be appreciated.

Operating System is Windows 10 64bit,
Using SickRage, SABnzbd, Couchpotato, have installed the correct python and pywin.

**Comment by mason-xx** [comment]
Did you check 5 issues below? https://github.com/clinton-hall/nzbToMedia/issues/850
Sounds similar...

**Comment by kennexDEWA** [comment]
yes, didnt fix the issue :(

**Comment by clinton-hall** [comment]
email through the .cfg file (blank out any passwords/apikeys etc) and I'll see if I can find the issue.
`fock_wulf@hotmail.com`
