### ISSUE TITLE
[Q] Seedbox setup

### ISSUE THREAD

**Issue by WebSpider** [clinton-hall/nzbToMedia#862]
With the copyright policy going after PopcornTime (which is Bittorrent based), I figure it's only a matter of time before they will start drilling down on bigger Bittorrent users in Europe as well, and after that, downloading in general.

My expectation is, that this would mean seedboxes gain in popularity.

I've looked through the wiki, to check how nzbToMedia could support this, and I cant quite make it out.

Seedboxes usually have some form of downlink (btsync, rsync+ssh), after which someone would call the nzbToMedia scripts. Who would that be, without losing information that prevents everything being processed over and over again?

**Comment by clinton-hall** [comment]
From what I have seen (and to be honest I don't have a lot of knowledge regarding seedboxes) this would require a service to run on the local system, that does some api polling of your seedbox, or your sync client and then calls the script when a download has finished and synced...

Incorporating a service that will run, and monitor status etc is something that has been on my to-do list for some time, but I have not had any chance to look into this...

**Comment by WebSpider** [comment]
Well, a seedbox is effectively just a download client whose filesystem you cannot reach (well, not easily, at least)

I've been thinking about getting sshfs going between my NAS and a seedbox I will be getting for some experiments soon .. or indeed a daemon listening for new sync commands.

Given that you're wanting to keep polling down (looking at your wiki about effective postprocessing ;) ), it may be a good solution to not poll for new downloads, but instead in a post-download trigger post an api call to "go fetch media from seedbox and postprocess once done", where you could use the downloadclient's api to figure out which files need to be fetched to begin with.

Would this still be in the scope of nzbToMedia?

**Comment by clinton-hall** [comment]
yes, that sounds reasonable.
The issue is the trigger... is there something from the seedbox/sync that can tell us when the sync is complete?
