### ISSUE TITLE
failed (terminated with unknown status)

### ISSUE THREAD

**Issue by dastrixuk** [clinton-hall/nzbToMedia#864]
Post-process-script nzbToSickBeard.py for ******\* failed (terminated with unknown status)

I am getting this error is there any way of getting better logs to try and get to the bottom of it.?

**Comment by clinton-hall** [comment]
in the logs folder (inside nzbToMedia) there should be an nzbtomedia.log file. if not, probably an issue with Python2 not exisiting?

What Downloader and what OS?

**Comment by dastrixuk** [comment]
Nzbget for downloading and openmediavault as os based on debian

Regards 

Chris

**Comment by clinton-hall** [comment]
make sure your Nzbget environment has a python2 listed in the PATH.
i.e if you sym-link /usr/bin/python2.7 to /usr/bin/python 2 or even just symlink /usr/bin/python to /usr/bin/python2, this should work

**Comment by dastrixuk** [comment]
does this help

Thu Oct 29 08:44:41 2015    INFO    nzbToMedia: No log folder, logging 
to screen only
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia: Traceback (most recent 
call last):
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:   File 
"/home/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 796, in <module>
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:     exit(main(sys.argv))
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:   File 
"/home/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 626, in main
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:     core.initialize(section)
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:   File 
"/home/nzbget/scripts/nzbToMedia/core/__init__.py", line 259, in initialize
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:     
logger.ntm_log_instance.initLogging()
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:   File 
"/home/nzbget/scripts/nzbToMedia/core/logger.py", line 97, in initLogging
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:     self.cur_handler = 
self._config_handler()
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:   File 
"/home/nzbget/scripts/nzbToMedia/core/logger.py", line 116, in 
_config_handler
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:     file_handler = 
logging.FileHandler(self.log_file_path, encoding='utf-8')
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:   File 
"/usr/lib/python2.7/logging/__init__.py", line 901, in __init__
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:     
StreamHandler.__init__(self, self._open())
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:   File 
"/usr/lib/python2.7/logging/__init__.py", line 926, in _open
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:     stream = 
codecs.open(self.baseFilename, self.mode, self.encoding)
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:   File 
"/usr/lib/python2.7/codecs.py", line 881, in open
Thu Oct 29 08:44:41 2015    INFO    nzbToMedia:     file = 
__builtin__.open(filename, mode, buffering)

> Clinton Hall <mailto:notifications@github.com>
> 28 October 2015 11:40
>
> make sure your Nzbget environment has a python2 listed in the PATH.
> i.e if you sym-link /usr/bin/python2.7 to /usr/bin/python 2 or even 
> just symlink /usr/bin/python to /usr/bin/python2, this should work
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/clinton-hall/nzbToMedia/issues/864#issuecomment-151812155>.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>

**Comment by clinton-hall** [comment]
Please make sure the user that runs the script (the user your downloader runs under) has full read and write permissions to the nzbToMedia directory.
Preferably, this user should be used to clone and configure nzbToMedia.
