### ISSUE TITLE
Sabnzbd error - unable to open database file

### ISSUE THREAD

**Issue by davey4444** [clinton-hall/nzbToMedia#865]
Hi, I'm trying to set up nzbToMedia on my Windows machine between Sickrage and Sabnzbd.  To date I have copied autoprocessMedia.cfg.spec to autoprocessMedia.cfg and have enabled Sickrage as well as adding the Sabnzbd API and folder.

Whenever anything completes with the [TV] marker I get the following error from Sabnzbd and don't know where to start looking to fix it.

```
12:58:38 INFO::MAIN: Loading config from C:\Program Files\SABnzbd\PostP\autoProcessMedia.cfg
```

Traceback (most recent call last):
  File "C:\Program Files\SABnzbd\PostP\nzbToSickBeard.py", line 252, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "C:\Program Files\SABnzbd\PostP\nzbToMedia.py", line 626, in main
    core.initialize(section)
  File "C:\Program Files\SABnzbd\PostP\core__init__.py", line 288, in initialize
    nzbToMediaDB.upgradeDatabase(nzbToMediaDB.DBConnection(), mainDB.InitialSchema)
  File "C:\Program Files\SABnzbd\PostP\core\nzbToMediaDB.py", line 27, in **init**
    self.connection = sqlite3.connect(dbFilename(filename), 20)
sqlite3.OperationalError: unable to open database file

**Comment by clinton-hall** [comment]
what happens when you run this script manually (not from SABnzbd)?

**Comment by davey4444** [comment]
Thanks for the reply.  Sadly it gets stuck at the same point again, the line saying -

        self.connection = sqlite3.connect(dbFilename(filename), 20)

in nzbToMediaDB.py
