### ISSUE TITLE
[SOLVED] autoProcessMedia.cfg/SickBeard keeps reverting config after nzbToSickbeard is run

### ISSUE THREAD

**Issue by xios01** [clinton-hall/nzbToMedia#868]
when I run nzbToSickbeard.py ... it processes the media file successfully, but but fails to process into sickbeard (lots of HTML in the log file, sicrage logs an invalid login attempt).  Turns out, it can't log into sickbeard... but when I go into autoProcessMedia.cfg, the sickbeard user/password values are blank... additionally, anything else set in the Sickbeard section appears to return to the default config (i.e. fork=sickrage returns to "auto") etc...
some additional info... I had nzbtomedia working flawlessly under windows.. no issues.. I just migrated to Linux... the drive (ntfs) is now being shared via CIFs and mounted on the linux server (where the script is located)... 
all other scripts are working well with the exception of the nzbtomediascript... I removed the original installation and installed fresh new copy of nzbtomedia (as of this posting)... unfortunatley, same behavior.. SickBeard config keeps reverting.

I did make a change to autoProcessMedia.cfg to enable debug logging... as well, changed section for deluge, those config's remained persistent, only the SickBeard section so far keeps reverting... note, I do verify config is persistent after saving the file... it only reverts after nzbToSickbeard.py is run.

installation details:
 nzbToMedia Version:1cd64053b0da1d351bb6af392e1ebb904c6b6ce2 Branch:master (Linux 3.16.0-4-amd64)
debian 8. 
uname -r
3.16.0-4-amd64

Any thoughts or ideas?

**Comment by xios01** [comment]
DOH!... had nothing to do with nzbtomedia...   turns out, nzbget has a seperate set of settings for nzbtomedia scripts... once I set the username/password in nzbget (for the nzbToTorrent script) all worked great...

**Comment by clinton-hall** [comment]
all good...
Please let me know if you find any other issues.
