### ISSUE TITLE
Really struggling installing nzbToMedia

### ISSUE THREAD

**Issue by wigwam12** [clinton-hall/nzbToMedia#869]
Hi
Noob alert
I have searched and read as much as I can but I think I am missing something really fundamental.
Have issued with the sabtosickrage autoprocessTV script and was advised to bin in and move to nzbToMedia.
As others have posted my folder in  contrib is also empty
I have read that I need to manually git pull it vis git submodule init and then git submodule update
BUT I clearly don't know how.
I have tried moving to /usr/local/sickrage/var; /usr/local/sickrage/var/SickRage; /usr/local/sickrage/var/SickRage; /usr/local/git; /volume1/@appstore/sickrage; /volume1/@appstore/got
and once in that folder i type "git submodule init" and I get the error back:
-ash: git: not found

Please advise me how to get these scripts so I can start the process of trying to edit to get Sabnzbd, CP and Tramission working.
At the moment Sickage and CP seem to be handling the processing

**Comment by clinton-hall** [comment]
Try
`/usr/local/git submodule init`
or otherwise just do
`/usr/local/git clone https://github.com/clinton-hall/nzbToMedia.git`

**Comment by wigwam12** [comment]
I tried both of the above but now I am getting the error:
-ash: /usr/local/git: permission denied.
I have done chmod -R 777 to /usr/local/git but it ha made no difference

**Comment by wigwam12** [comment]
No matter.
I have just checked the folder again and magically the scripts etc are now in the folder!!
Many thanks for your kind help, I really appreciate it

**Comment by clinton-hall** [comment]
All good. Let me know if you have any more issues.
