### ISSUE TITLE
Unable to locate a section with subsection:UNCAT enabled in your autoProcessMedia.cfg, exiting!

### ISSUE THREAD

**Issue by dashboardy** [clinton-hall/nzbToMedia#873]
Using Transmission 2.83 on my NAS; I have autodl IRSSI community grab torrent files based on my filters. Up until recently I had transmission call sabtosickbeard.py upon completion, and this would tell sickrage to scan my download directory which would then process the finished torrent. Worked like a charm.

However as I learned tonight,  this is deprecated and has now been removed. Since I have IRSSI grab the torrent file (to a watch dir), I'm assuming this means no category is being assigned to a downloaded file. Is there a way to assign the category other than using sickrage, or am I now forced to using sickrage to download the file?

**Comment by dashboardy** [comment]
Disregard. I found a thread that advised to name the download folder as "tv". 

Recommend to make this more clear in the wiki for transmission.

**Comment by clinton-hall** [comment]
Please feel free to edit the wiki to make this clearer.
