### ISSUE TITLE
Cannot run script /share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia/nzbToSickBeard.py

### ISSUE THREAD

**Issue by devdevil85** [clinton-hall/nzbToMedia#875]
I have tried everything in my power (changing permissions, making a symlink, editing nzbToSickBeard.py and nzbToMedia.py files to replace "python2" with "python 2.7" and even "python".

Yet I keep getting this error.  I don't know what else to do.

**Comment by clinton-hall** [comment]
What happens when you run this manually?
What are the permissions on this file?

**Comment by devdevil85** [comment]
I don't know what you mean by running it manually.  How do you run it manually?

The file permissions are:

**-rwxrwxrwx    1 admin    administ     27018 Nov  8 03:05 nzbToMedia.py***
-rwxrwxrwx    1 admin    administ      9012 Nov  8 03:07 nzbToMedia.pyc*
-rwxrwxrwx    1 admin    administ      6382 Nov  8 02:53 nzbToNzbDrone.py*
**-rwxrwxrwx    1 admin    administ      6981 Nov  8 03:45 nzbToSickBeard.py***
-rwxrwxrwx    1 admin    administ      4096 Nov  8 03:25 nzbtomedia.db*

lrwxrwxrwx    1 admin    administ        48 Nov  8 02:06 python2.7 -> /share/CACHEDEV1_DATA/.qpkg/Python/bin/python2.7*
lrwxrwxrwx    1 admin    administ        55 Nov  8 02:06 python2.7-config -> /share/CACHEDEV1_DATA/.qpkg/Python/bin/python2.7-config*

**Comment by clinton-hall** [comment]
Via ssh session, logged in as admin, just typed the full path/name of the script and hit enter.

**Comment by devdevil85** [comment]
This is what I get:

[/] # /share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia/nzbToSickBeard.py
-sh: /share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia/nzbToSickBeard.py: /usr/local/bin/python^M: bad interpreter: No such file or directory

**Comment by clinton-hall** [comment]
How are you editing the file. It looks like you have corrupted the first line using a non-recognized character... perhaps using notepad on windows or the likes?

try doing the following via ssh and post the output

```
cd /share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia
git reset --hard
git pull
./nzbToSickBeard.py
```

**Comment by devdevil85** [comment]
I was using **vi**

[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia] # git reset --hard
HEAD is now at c195264 Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/3580
[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia] # git pull
remote: Counting objects: 58, done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 58 (delta 20), reused 6 (delta 6), pack-reused 4
Unpacking objects: 100% (58/58), done.
From https://github.com/SiCKRAGETV/SickRage
   04bc64a..42ef697  develop    -> origin/develop
 * [new branch]      syno       -> origin/syno
Already up-to-date.
[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia] # ./nzbToSickBeard.py
-sh: ./nzbToSickBeard.py: /usr/bin/python2.7^M: bad interpreter: No such file or directory
[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia] #

**Comment by clinton-hall** [comment]
So that hasn't reset the edit you made.
I'm not sure how you can revert the change when this is a git repository nested inside another git repository.

Try changing the first line back to the original and try executing again.

**Comment by devdevil85** [comment]
**I copied the originals back over after removing the modified versions:**

[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia] # rm nzbToSickBeard.py
[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia] # rm nzbToMedia.py
[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia] # cp /share/Download/nzbToMedia/nzbToSickBeard.py nzbToSickBeard.py
[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia] # cp /share/Download/nzbToMedia/nzbToMedia.py nzbToMedia.py

**This is what I get when I try executing again:**
[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia] # /share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia/nzbToSickBeard.py
: No such file or directory

**This is what I get when I try executing again after modifying the first line to be /usr/bin/python2.7**
[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia] # /share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia/nzbToSickBeard.py
-sh: /share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/contrib/nzbToMedia/nzbToSickBeard.py: /usr/bin/python2^M: bad interpreter: No such file or directory

**Comment by clinton-hall** [comment]
When you edit the first line, are you stil putting #! In front of the path?

**Comment by devdevil85** [comment]
Yes

#!/usr/bin/python2.7
#
##############################################################################
### NZBGET POST-PROCESSING SCRIPT                                          ###

**Comment by devdevil85** [comment]
Any ideas? Should I just start all over? What editor should I be using?

**Comment by clinton-hall** [comment]
You can try using winSCP as a more "explorer" like editing tool.

The only way I was able to reproduce this exact same error is to edit the first line to
`#!/usr/bin/python2.7^M`

Any other non-existent path etc would yield a different error.

**Comment by devdevil85** [comment]
Ok Clinton. I will try that.  I don't see ^M when I view the file.

**Comment by clinton-hall** [comment]
I didn't expect you would see it. I was thinking there might be some weird file encoding/special character being saved?

What happens when you manually execute a non-edited file?

E.g. From the nzbToMedia folder run

    ./TorrentToMedia.py

Post the full output.

**Comment by devdevil85** [comment]
I decided to uninstall everything and start over.  Now I'm having an issue with installing the Git package- git_2.4.6-1_qnapx86.ipk.  I have a TS-451 and the x86 package is failing to install (due to file format error).  I am on QTS 4.2.0.

**Comment by devdevil85** [comment]
Alright, I figured it out and got all of the necessary packages installed.  I setup everything as before and changed the first line to **/usr/bin/python2.7** using the WinSCP editor.

This is what I get in Putty when I execute nzbToSickbear.py

**/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/contrib/nzbToMedia-master/libs/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
[20:03:41] [ERROR]::MAIN: Unknown current version number, don't know if we should update or not
[20:03:41] [INFO]::MAIN: nzbToMedia Version:10.12 Branch:master (Linux 3.12.6)
[20:03:41] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
[20:03:41] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[20:03:41] [INFO]::MAIN: #########################################################
[20:03:41] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[20:03:41] [INFO]::MAIN: #########################################################
[20:03:41] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[20:03:41] [INFO]::MAIN: The /share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/contrib/nzbToMedia-master/nzbToSickBeard.py script completed successfully.
[/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/contrib/nzbToMedia-master] #**

**Comment by devdevil85** [comment]
Clinton, good news!  It is finally working.

[22:27:49] [INFO]::MAIN: The /share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/contrib/nzbToMedia-master/nzbToSickBeard.py script completed successfully.
SickBeard: Successfully post-processed *[TV Show I watch]*!
