### ISSUE TITLE
Ignore .rar files

### ISSUE THREAD

**Issue by FlyingPersian** [clinton-hall/nzbToMedia#878]
Hi
A while ago I posted an issue where my movies failed to extract. I solved this temporarily by removing the .rar file from the extensions setting in the autoProcessMedia.cfg. Unfortunately since some time the script started extracting .rar files again. I think the issue was that it had to start with r00 files instead of .rar files. Is there any way to disable the extraction of .rar files? The appropriate line looks like this:

[Extensions]
    compressedExtensions = .zip, .7z, .gz, .bz, .tar, .arj, .1, .01, .001, r00

Kind Regards

**Comment by clinton-hall** [comment]
what happens if you remove all of these?.. ie.

```
[Extensions]
compressedExtensions = .zip, .7z, .gz, .bz, .tar, .arj
```

**Comment by FlyingPersian** [comment]
Same. It seems to ignore the setting and just extracts the rar, which fails :x
It shouldn't totally ignore .rar extensions as the subs are only one .rar, but it should start with r00 when extracting the movie.

**Comment by clinton-hall** [comment]
Sorry, I thought you were saying you wanted the script to ignore .rar and NOT extract?

Have you got logs to show what it is doing? And can you clarify what it should be doing?

**Comment by FlyingPersian** [comment]
I want it NOT to extract rars on movies, since it always fails. The extraction takes 1s. It works fine for shows though. 
Here the log:

http://pastebin.com/BkJpCa0R

**Comment by clinton-hall** [comment]
I don't understand why extracting .rar fails (but reports success) while extracting .r00 works...

**Comment by FlyingPersian** [comment]
Neither do I. But as you can see it fails to extract and I don't know how else to solve this. I tried downloading and reconfiguring nzbToMedia multiple times, thought it might be due to a faulty config or something. Unfortunately that didn't solve the problem. Do you have any suggestions?

**Comment by clinton-hall** [comment]
can you download the same (without running nzbToMedia) and then try manually running the unrar command on the .rar

e.g.
`unrar x -o+ -y /home/admin/rtorrent/downloads/Movies/The.Man.from.U.N.C.L.E.2015.720p.BluRay.x264-SPARKS/the.man.from.u.n.c.l.e.2015.720p.bluray.x264-sparks.rar /home/admin/rtorrent/downloads/Movies/The.Man.from.U.N.C.L.E.2015.720p.BluRay.x264-SPARKS`

**Comment by FlyingPersian** [comment]
Yes, I'll do that in a sec. Another thing: When linking the files (hard or sym) the original files become broken once the script deletes the processed rar files. When I do ls -lh in the original folder it looks like this:

lrwxr-xr-x  1 admin  admin   155B Nov 11 12:21 the.man.from.u.n.c.l.e.2015.720p.bluray.x264-sparks.r88 -> /home/admin/rtorrent/downloads/processed/Movies/The.Man.from.U.N.C.L.E.2015.720p.BluRay.x264-SPARKS/the.man.from.u.n.c.l.e.2015.720p.bluray.x264-sparks.r88

It still shows that the file is linked. Extracting doesn't work then. To fix this I always delete a file and let it redownload that file, then it works fine again. Copylinking doesn't do that. I'll run the command you just said in a sec and report back.

**Comment by clinton-hall** [comment]
this indicates that something isn't working with the hard-link.
What system is this on again?
I have not seen anything like this on any platform I have tested...

**Comment by FlyingPersian** [comment]
On FreeNAS. Maybe the linking works slightly different here or the removal of links? Give me one more minute to run the command you told me, I had to redownload the movie :x

**Comment by FlyingPersian** [comment]
Running the command you gave me works fine:

unrar x -o+ -y /home/admin/rtorrent/downloads/Movies/The.Man.from.U.N.C.L.E.2015.720p.BluRay.x264-SPARKS/the.man.from.u.n.c.l.e.2015.720p.bluray.x264-sparks.rar /home/admin/rtorrent/downloads/Movies/The.Man.from.U.N.C.L.E.2015.720p.BluRay.x264-SPARKS

**Comment by clinton-hall** [comment]
What happens if you set
```
[Torrent]
    useLink = no
```
And then have a downlaod call TorrentToMedia.py (or call it manually)?

**Comment by FlyingPersian** [comment]
That's what I always use. It copies the files, extracts the subs and the .rar (and fails) and then deletes the rars. Is there a way of it not deleting the rars? Then I can try and extract the copied rars manually, maybe I can find an error there.

**Comment by clinton-hall** [comment]
Sorry the log you showed before was using hard-link, so I thought perhaps that was the issue...
If these files have been copied over to /home/admin/rtorrent/downloads/processed/Movies/The.Man.from.U.N.C.L.E.2015.720p.BluRay.x264-SPARKS

can you try running the following?
```
unrar x -o+ -y /home/admin/rtorrent/downloads/processed/Movies/The.Man.from.U.N.C.L.E.2015.720p.BluRay.x264-SPARKS/the.man.from.u.n.c.l.e.2015.720p.bluray.x264-sparks.rar /home/admin/rtorrent/downloads/processed/Movies/The.Man.from.U.N.C.L.E.2015.720p.BluRay.x264-SPARKS
```

**Comment by FlyingPersian** [comment]
Well that's my plan, but once the script "finishes" the extraction it deletes those rar files again. How can I make it not do that?

**Comment by clinton-hall** [comment]
Only way is to set
```
[CouchPotato]
    [Movies]
        extract = 0
```

**Comment by FlyingPersian** [comment]
Extracting the processed rars manually works like a charm. There must be some issue between copying them and then extracting them. I don't think it goes to fast as the subs are extracted first, so all the files should be copied properly. Any idea?

**Comment by FlyingPersian** [comment]
No idea Clinton?

**Comment by clinton-hall** [comment]
No... I can't understand why the extraction doesn't work.

Do you have more than 1 version of unrar installed? perhaps nzbToMedia is calling a different unrar version that has file-size limitations?

**Comment by FlyingPersian** [comment]
I just updated unrar-5.21_1,5 to 5.30,5 and now it seems to work. It's weird as I haven't updated anything in a long time and it worked a while back. Thanks for your help!

**Comment by FlyingPersian** [comment]
Nevermind -.- I accidentally deleted the log file. extraction in the autoProcessMedia.cfg was still disabled, I dunno why it extracted the movie, but it did and worked fine. Tried a different movie with extraction enabled int he autoProcessMedia.cfg and I got the same issue as before.

**Comment by FlyingPersian** [comment]
Can I make nzbToMedia ignore the fact that there's no media file present if I disable extraction? I enabled extraction in CouchPotato and disabled it in nzbToMedia and it gave me this log after copying the rar files:

http://pastebin.com/Cf35RB14

Or is it possible that the extraction option in CouchPotato is meant for when it scans the download folder every x hours? I've disabled that as I rely on CouchPotato & Sickbeard being called by nzbToMedia..

**Comment by clinton-hall** [comment]
check_media = 0
does this help?

**Comment by FlyingPersian** [comment]
Nope :/ Wouldn't make sense either as this is done after the extraction and removal of the rar files.

**Comment by FlyingPersian** [comment]
Okay I did some change which fixed it a little. I changed the file extractor.py in core/extractor and added 
".r00": ["unrar", "x", "-o+", "-y"],
Now r00 files are also extracted. I could comment out the unrar line, but then subtitles won't be extracted as they're only rar files. Now the thing is that it's random whether it tries to unrar the .rar or .r00 file. That totally depends on which file is scanned first and I don't know how to influence that. Any suggestions?

**Comment by clinton-hall** [comment]
i still don't understand why .00 will extract but .rar wont...this makes no sense.

**Comment by FlyingPersian** [comment]
I know. And it only doesn't work when the script tries to unrar it. I can unrar manually just fine. The weirdest thing is that sometimes it works and sometimes it doesn't, but most of the time it doesn't..

**Comment by FlyingPersian** [comment]
If you like you can check via TeamViewer, maybe you see something I don't..

**Comment by FlyingPersian** [comment]
Sometimes I get "Extraction failed for: *.r00" -.-

**Comment by FlyingPersian** [comment]
I changed the extractor to 7z in the core/extractor/extractor.py and recompiled the extractor.py. Seems to be working for now. I'll report back if it should stop working again :D

**Comment by FlyingPersian** [comment]
7z reported failure on extraction. What actually helped me was this here:

https://sickrage.tv/forums/forum/help-support/general-support/236-unpack-post-processing-feature-on-macos-x?p=514#post514
