### ISSUE TITLE
100% CPU - Freezing server and needs to be restarted.

### ISSUE THREAD

**Issue by UnR34L** [clinton-hall/nzbToMedia#883]
Something is misbehaving, "sh" will be stuck at 100% CPU and my server will be brought to it's knees, I'm running it on the SabNZB plugin Jail on my FreeNAS server.

I can't even restart the jail or access the drives when this happens. 

I've checked the CPU usage logs so I know when the script is being triggered it's directly responsible somehow. It has happened about 5 times

**Comment by clinton-hall** [comment]
I have tested multiple systems and not seen any CPU usage as suggested.
I don't have FreeNAS so I can't test here.
Are there any logs produced when this happens? Can you post the logs?

**Comment by UnR34L** [comment]
Since not using nzbToMedia the issue has stopped, so it's fair to say it's the script or a dependency.

I switched to Sonaar because I use the server for other stuff and cant having it completely crashing, it has failed downloading and I'm happy with it.

The best I can do with the Logs: http://pastebin.com/mpZNJRzH
