### ISSUE TITLE
torrent script extracting wrong folder

### ISSUE THREAD

**Issue by tloskpd** [clinton-hall/nzbToMedia#900]
updated to nightly branch to fix the proc_dir change to sickrage, now when torrents are completed and the script runs, it links the files to my process folder but then does the extraction on the seeding folder archive outputting to the seeding directory.  When the script then looks at the processed folder for the media file, it finds none obviously as the file wasn't extracted there and sends failed download to sickrage to process.  Attached full log of a failed process.
[nzbtomedia.txt](https://github.com/clinton-hall/nzbToMedia/files/52769/nzbtomedia.txt)

**Comment by clinton-hall** [comment]
Can you please update to latest nightly and test again. Hopefully this is fixed... I am surprised this hasn't been flagged previously as this is not a recent change.

**Comment by clinton-hall** [comment]
Ah.. I see... it WAS a recent change.
Hopefully this fix works, if not, I know what else to change back... please confirm...

**Comment by MrCee** [comment]
Thanks guys, I have been seeing the same problem.
