### ISSUE TITLE
A way to manually re-run the script to process previously failed items?

### ISSUE THREAD

**Issue by Jonnehs** [clinton-hall/nzbToMedia#908]
Hi,

Sorry if this is obvious or documented somewhere I can't find. Is there an easy way to just re-run the script against completed downloads in an attempt to get it to process them correctly?

Cheers

**Comment by clinton-hall** [comment]
yes, in autoProcessMedia.cfg set the watch_dir for the appropriate section

e.g.
```
[CouchPotato]
   [[movies]]
       watch_dir = /volume1/downloads/movies
```

then manually execute the script. i.e. execute nzbToMedia.py or TorrentToMedia.py
