### ISSUE TITLE
No subsection:movie when manually downloading via sabnzbd

### ISSUE THREAD

**Issue by larrym** [clinton-hall/nzbToMedia#910]
Periodically I manually download a movie via sabnzbd (Windows v0.7.20) by pushing the 'Add NZB' button, selecting 'movie' from the dropdown associated with Category and pressing the Upload button. As a result, I get the following error. 

Is there a way to configure this to work properly?

    INFO    ::MAIN: #########################################################
    INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
    INFO    ::MAIN: #########################################################
    DEBUG   ::MAIN: Options passed into nzbToMedia: ['C:\\SickRage_v0.3\\SickRage\\contrib\\nzbToMedia\\nzbToMedia.py', s\\sabnzbd\\complete\\movie\\Xyz.movie', 'Xyz.movie.nzb', 'Xyz.movie', '', 'movie', 'alt.binaries.nl', '0']
    INFO    ::MAIN: Script triggered from SABnzbd
    DEBUG   ::MAIN: Searching for nzoid from SAbnzbd ...
    DEBUG   ::MAIN: Adding NZB download info for directory E:\media\downloads\sabnzbd\complete\movie\Xyz.movie to database
    DB      ::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?,  input_directory = ? with args [0, u'sabnzbd', 735942, u'None', u'None', u'Xyz.movie.nzb', ds\\sabnzbd\\complete\\movie\\Xyz.movie']
    DB      ::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (status, client_agent, last_update, input_id, input_hash, input_name, UES (?, ?, ?, ?, ?, ?, ?) with args [0, u'sabnzbd', 735942, u'None', u'None', u'Xyz.movie.nzb', ds\\sabnzbd\\complete\\movie\\Xyz.movie']
    ERROR   ::MAIN: Unable to locate a section with subsection:movie enabled in your autoProcessMedia.cfg, exiting!
    ERROR   ::MAIN: A problem was reported in the C:\SickRage_v0.3\SickRage\contrib\nzbToMedia\nzbToMedia.py script.

**Comment by clinton-hall** [comment]
add 
```
[CouchPotato]
    [[movie]]
```
to the autoProcessMedia.cfg 
and enter all necessary parameters below this.

Otherwise change the category in SABnzbd to match the category defined in autoProcessMedia.cfg

**Comment by larrym** [comment]
Thanks. I needed to install CouchPotato. After I added CouchPotato's missing API in autoProcessMedia.cfg,  post-processing works great.
