### ISSUE TITLE
removes few trailing characters from processing directory and PP gets failed. 

### ISSUE THREAD

**Issue by frriction** [clinton-hall/nzbToMedia#916]
here is log
http://pastebin.com/nbvBCHdU
inputDirectory is /media/pendrive/rtorrent/complete/tv/The.Wire.S01.576p.BluRay.DD5.1.x264-HiSD
but outputDirectory is /media/pendrive/rtorrent/complete/tv/The.Wire.S01.576p.BluRay.DD5.1
trailing .x264-HISD is missing.
 here is torrent section of my autoProcessMedia.cfg http://pastebin.com/VtMeEQwx

**Comment by clinton-hall** [comment]
update to latest nightly and verify if this works as wanted.

**Comment by frriction** [comment]
Nightly works.
