### ISSUE TITLE
Transcode Custom Settings Assistance

### ISSUE THREAD

**Issue by breezytm** [clinton-hall/nzbToMedia#927]
Hello and thanks in advanced for the help. I would like configure a custom profile to transcode my mkv to mp4. The default IPad-1080p with a higher ac3 bitrate in second track. Currently I am using the IPad-1080p defaults and I am getting 448k ac3 and would like to amp this up without changing anything else. Please let me know if I have it set correctly. Thanks. 

![capture](https://cloud.githubusercontent.com/assets/3412923/12056064/dde65a54-af00-11e5-9ec5-e353fdde7c83.PNG)
![capture1](https://cloud.githubusercontent.com/assets/3412923/12056063/dde59420-af00-11e5-8701-a85c7b3427e7.PNG)

**Comment by clinton-hall** [comment]
this looks spot on to me... please test and let me know if there are any issues... may need tweaking, but this looks right.

**Comment by breezytm** [comment]
nzbToCouchPotato: [14:46:28] [DEBUG]::MAIN: calling command: /share/MD0_DATA/.qpkg/NZBGet/repository/bin/ffmpeg -loglevel warning -fflags +genpts -i /share/Download/nzbget/dst/movies/Inside.Man.2006.1080p.BluRay.DTS-HD.x264-BARC0DE.cp(tt0454848)/Inside.Man.2006.1080p.BluRay.DTS-HD.x264-BARC0DE.mkv -map 0:0 -map 0:1 -map 0:1 -c:v libx264 -crf 19 -level 3.1 -c:a:0 aac -strict -2 -ac:a:0 2 -b:a:0 128000 -c:a:1 ac3 -b:a:1 640000 -sn /share/Download/nzbget/dst/movies/Inside.Man.2006.1080p.BluRay.DTS-HD.x264-BARC0DE.cp(tt0454848)/Inside.Man.2006.1080p.BluRay.DTS-HD.x264-BARC0DE.mp4

Two hours later the file was still transcoding. It was a 13GB file. Two afters later the mp4 file had only grew 100,000KB. Something is not right somewhere. If I used one of the defaults, the files gets transcoded in about 20 minutes.

**Comment by clinton-hall** [comment]
Please check the autoProcessMedia.cfg to be sure that
```
[Transcoder]
    outputVideoCRF = ""
    outputVideoLevel = ""
```

somehow these have been set... and the NZBGet settings don't include these... when using defaults, these are cleared and therefore the video stream is copied...

**Comment by breezytm** [comment]
Doesn't match the picture. Am I missing something? or is the default for all scripts?

[Transcoder]
    # getsubs. enable to download subtitles.
    getSubs = 0
    # subLanguages. create a list of languages in the order you want them in your subtitles. 
    subLanguages = eng
    # transcode. enable to use transcoder
    transcode = 1
    ###### duplicate =1 will create a new file. =0 will replace the original
    duplicate = 0
    # concat. joins cd1 cd2 etc into a single video.
    concat = 1
    # IgnoreExtensions is a comma-separated list of extensions that will not be transcoded.
    ignoreExtensions = ".avi,.mp4"
    # outputFastStart. 1 will use -movflags + faststart. 0 will disable this from being used.
    outputFastStart = 0
    # outputQualityPercent. used as -q:a value. 0 will disable this from being used.
    outputQualityPercent = 0
    # outputVideoPath. Set path you want transcoded videos moved to. Leave blank to disable.
    outputVideoPath = ""
    # processOutput. 1 will send the outputVideoPath to SickBeard/CouchPotato. 0 will send original files.
    processOutput = 1
    # audioLanguage. set the 3 letter language code you want as your primary audio track.
    audioLanguage = eng
    # allAudioLanguages. 1 will keep all audio tracks (uses AudioCodec3) where available.
    allAudioLanguages = 1
    # allSubLanguages. 1 will keep all existing sub languages. 0 will discard those not in your list above.
    allSubLanguages = 0
    # embedSubs. 1 will embed external sub/srt subs into your video if this is supported.
    embedSubs = 1
    # burnInSubtitle. burns the default sub language into your video (needed for players that don't support subs)
    burnInSubtitle = 0
    # extractSubs. 1 will extract subs from the video file and save these as external srt files.
    extractSubs = 0
    # externalSubDir. set the directory where subs should be saved (if not the same directory as the video)
    externalSubDir = ""
    # hwAccel. 1 will set ffmpeg to enable hardware acceleration (this requires a recent ffmpeg)
    hwAccel = 0
    # generalOptions. Enter your additional ffmpeg options here with commas to separate each option/value (i.e replace spaces with commas).
    generalOptions = ""
    # outputDefault. Loads default configs for the selected device. The remaining options below are ignored.
    # If you want to use your own profile, leave this blank and set the remaining options below.
    # outputDefault profiles allowed: iPad, iPad-1080p, iPad-720p, Apple-TV2, iPod, iPhone, PS3, xbox, Roku-1080p, Roku-720p, Roku-480p, mkv, mp4-scene-release
    outputDefault = iPad
    #### Define custom settings below.
    outputVideoExtension = .mp4
    outputVideoCodec = libx264
    VideoCodecAllow = ""
    outputVideoPreset = medium
    outputVideoResolution = 1920:1080
    outputVideoFramerate = 24
    outputVideoBitrate = 800k
    outputVideoCRF = 19
    outputVideoLevel = 3.1
    outputAudioCodec = libmp3lame
    AudioCodecAllow = ""
    outputAudioChannels = 6
    outputAudioBitrate = 128k
    outputAudioTrack2Codec = libfaac
    AudioCodec2Allow = ""
    outputAudioTrack2Channels = 2
    outputAudioTrack2Bitrate = 128k
    outputAudioOtherCodec = libmp3lame
    AudioOtherCodecAllow = ""
    outputAudioOtherChannels = 2
    outputAudioOtherBitrate = 128k
    outputSubtitleCodec = ""

**Comment by clinton-hall** [comment]
the issue is not every setting shows in the nzbToMedia screen in NZBGet... I obviously  missed some.

Any setting that doesn't show in NZBGet web ui can only be set manually in autoProcessMedia.cfg.

So please  set these 2 parameters to be blank `""` in autoProcessMedia.cfg to see if that works

**Comment by breezytm** [comment]
Okay Great. Thank you for your great help Clinton-hall. That seems to have solve the issue. I think these settings would be great as a default. For others who may came across this thread trying to accomplish the same thing. Here are my final settings in autoProcessMedia.cfg under [Transcoder]:

    outputDefault = None
    #### Define custom settings below.
    outputVideoExtension = .mp4
    outputVideoCodec = libx264
    VideoCodecAllow = "libx264,h264,h.264,AVC,avc,mpeg4,msmpeg4,MPEG-4"
    outputVideoPreset = ""
    outputVideoResolution = 1920:1080
    outputVideoFramerate = ""
    outputVideoBitrate = ""
    outputVideoCRF = ""
    outputVideoLevel = ""
    outputAudioCodec = aac
    AudioCodecAllow = libfaac
    outputAudioChannels = 2
    outputAudioBitrate = 128k
    outputAudioTrack2Codec = ac3
    AudioCodec2Allow = ""
    outputAudioTrack2Channels = 6
    outputAudioTrack2Bitrate = 640k
    outputAudioOtherCodec = ""
    AudioOtherCodecAllow = ""
    outputAudioOtherChannels = ""
    outputAudioOtherBitrate = ""
    outputSubtitleCodec = mov_text

**Comment by breezytm** [comment]
As a side note Clinton-hall, I noticed some mkv have both DTS and AC3 tracks. Some of the AC3 tracks are stereo tracks. I've read in this link https://github.com/clinton-hall/nzbToMedia/issues/474 you were explaining to someone about a way to determine the channel in the stream and set it accordingly. I was wondering if the same step can be used to allow AC3 tracks base on if the channel is greater or equal to 6. 

If less than 6? ignore it and transcode the DTS track to 5.1. 
If greater than 6? transcode track to ac3 5.1 
if equal to 6? copy

After coming across one of those mkvs I decided not to allow any ac3 tracks at all and force transcode everything. As you can see, my settings 'AudioCodec2Allow' is not set to anything.

**Comment by depraved22** [comment]
I wish I had something to share but I've been just letting plex handle majority of my transcodes since I replaced my basement server so I haven't been transcoding via nzbToMedia in ages.
