### ISSUE TITLE
Can I run nzbtomedia independently?

### ISSUE THREAD

**Issue by mbeebe43083** [clinton-hall/nzbToMedia#929]
I finally got transcoding to work.  What I would like to do is rerun it on a folder to transcode a bunch of previously downloaded videos.  Is this possible?

**Comment by clinton-hall** [comment]
Yes, but I don't personally recommend it.

Basically you can set the watch_dir for a category then run the script manually. Or you can manually pass in the directory, download name, category etc to process each video individually

**Comment by Mycah** [comment]
I'm interested in this as well.  I don't download enough movie, game, or music content to justify a daemon always being active, so I'd like to manually point nzbToMedia to my download to post process when I download something.  Is there any documentation on how this might be achieved?
