### ISSUE TITLE
Data from SABnzbd could not be parsed

### ISSUE THREAD

**Issue by kesawi** [clinton-hall/nzbToMedia#930]
I have nzbToMedia successfully working with SABnzbd in conjunction with Sickrage and CouchPotato, however I keep getting the warning message *Data from SABnzbd could not be parsed* despite the script completing successfully under both Sickrage and CouchPotato. Log shows the following:

    [INFO]::MAIN: Loading config from [/opt/SickRage/contrib/nzbToMedia/autoProcessMedia.cfg]
    [INFO]::ENVIRONMENT: LANG: en_AU.UTF-8
    [INFO]::ENVIRONMENT: SHELL: /sbin/nologin
    [INFO]::ENVIRONMENT: LOGNAME: sabnzbd
    [INFO]::ENVIRONMENT: USER: sabnzbd
    [INFO]::ENVIRONMENT: HOME: /var/lib/sabnzbd
    [INFO]::ENVIRONMENT: PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
    [INFO]::MAIN: Checking database structure...
    [DEBUG]::MAIN: Checking Initial Schema database upgrade
    [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
    [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
    [DEBUG]::MAIN: InitialSchema upgrade not required
    [INFO]::MAIN: Checking if source needs an update
    [DEBUG]::MAIN: cur_commit = 3e4861e87c543a4d2debd8997feb16bda3ef5339 % (newest_commit)= 3e4861e87c543a4d2debd8997feb16bda3ef5339, num_commits_behind = 0
    [INFO]::MAIN: No update needed
    [INFO]::MAIN: nzbToMedia Version:3e4861e87c543a4d2debd8997feb16bda3ef5339 Branch:master (Linux 3.10.0-327.3.1.el7.x86_64)
    [DEBUG]::MAIN: Connecting to deluge: http://bt.localdomain.net:58846
    [INFO]::MAIN: #########################################################
    [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
    [INFO]::MAIN: #########################################################
    [DEBUG]::MAIN: Options passed into nzbToMedia: ['/opt/SickRage/contrib/nzbToMedia/nzbToSickBeard.py', '/var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup', 'ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.nzb', 'ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup', '', 'tv', 'alt.binaries.misc', '0']
    [INFO]::MAIN: Script triggered from SABnzbd
    [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
    [WARNING]::MAIN: Data from SABnzbd could not be parsed
    [DEBUG]::MAIN: Adding NZB download info for directory /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup to database
    [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'sabnzbd', 735968, u'None', u'None', u'ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.nzb', u'/var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup']
    [DB]::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (status, client_agent, last_update, input_id, input_hash, input_name, input_directory) VALUES (?, ?, ?, ?, ?, ?, ?) with args [0, u'sabnzbd', 735968, u'None', u'None', u'ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.nzb', u'/var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup']
    [INFO]::MAIN: Auto-detected SECTION:SickBeard
    [DEBUG]::MAIN: Checking for archives to extract in directory: /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup
    [INFO]::MAIN: Calling SickBeard:tv to post-process:ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.nzb
    [INFO]::MAIN: Attempting to auto-detect tv fork
    [INFO]::MAIN: SickBeard:tv fork auto-detection successful ...
    [INFO]::MAIN: SickBeard:tv fork set to sickrage
    [DEBUG]::EXCEPTION: Replacing file name XXXX with directory name ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup
    [DEBUG]::EXCEPTION: Replacing file name /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup/XXXX.mkv with download name /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.mkv
    [INFO]::MAIN: FLATTEN: Flattening directory: /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup
    [DEBUG]::MAIN: Checking for empty folders in:/var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup
    [DEBUG]::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /opt/SickRage/contrib/nzbToMedia/tests/test.mp4
    [INFO]::TRANSCODER: Checking [ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.mkv] for corruption, please stand by ...
    [DEBUG]::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.mkv
    [INFO]::TRANSCODER: SUCCESS: [ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.mkv] has no corruption.
    [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
    [DEBUG]::SICKBEARD: Opening URL: https://sb.localdomain.net:8083/home/postprocess/processEpisode with params: {'nzbName': 'ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.nzb', 'quiet': 1, 'failed': '0', 'dir': '/var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup'}
    [POSTPROCESS]::SICKBEARD: Processing folder /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup
    [POSTPROCESS]::SICKBEARD: PostProcessing Path: /var/lib/usenet/complete/tv
    [POSTPROCESS]::SICKBEARD: PostProcessing Dirs: [u'ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup']
    [POSTPROCESS]::SICKBEARD: PostProcessing Files: []
    [POSTPROCESS]::SICKBEARD: PostProcessing VideoFiles: []
    [POSTPROCESS]::SICKBEARD: PostProcessing RarContent: []
    [POSTPROCESS]::SICKBEARD: PostProcessing VideoInRar: []
    [POSTPROCESS]::SICKBEARD: Processing folder ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup
    [POSTPROCESS]::SICKBEARD: Processing folder /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup
    [POSTPROCESS]::SICKBEARD: Processing /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.mkv (ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.nzb)
    [POSTPROCESS]::SICKBEARD: Retrieving episode object for XxXX
    [POSTPROCESS]::SICKBEARD: Snatch history had a quality in it, using that: Quality HDTV
    [POSTPROCESS]::SICKBEARD: SR snatched this episode and it is not processed before
    [POSTPROCESS]::SICKBEARD: Is ep a priority download: True
    [POSTPROCESS]::SICKBEARD: There is no existing file so there's no worries about replacing it
    [POSTPROCESS]::SICKBEARD: This download is marked a priority download so I'm going to replace an existing file if I find one
    [POSTPROCESS]::SICKBEARD: Found release name ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup
    [POSTPROCESS]::SICKBEARD: Destination folder for this episode: /media/TV Shows/ShowName/Season XX
    [POSTPROCESS]::SICKBEARD: No associated files for /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.mkv were found during this pass
    [POSTPROCESS]::SICKBEARD: Moving file from /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.mkv to /media/TV Shows/ShowName/Season XX/ShowName - SXXEXX - EpisodeName.mkv
    [POSTPROCESS]::SICKBEARD: Processing succeeded for /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.mkv
    [POSTPROCESS]::SICKBEARD: Deleted folder: /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup
    [POSTPROCESS]::SICKBEARD: Successfully processed
    [DB]::DB: Updating status of our download ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.nzb in the DB to 1
    [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status=?, last_update=? WHERE input_name=? with args [1, 735968, u'ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup.nzb']
    [INFO]::CLEANDIR: Directory /var/lib/usenet/complete/tv/ShowName.SXXEXX.Quality.HDTV.Codec-ReleaseGroup has been processed and removed ...
    [INFO]::MAIN: The /opt/SickRage/contrib/nzbToMedia/nzbToSickBeard.py script completed successfully.
    SickBeard: Successfully post-processed ShowName - SXXEXX - EpisodeName.mkv!

**Comment by clinton-hall** [comment]
in autoProcessMedia.cfg set
```
[Nzb]
    sabnzbd_host = http://localhost
    sabnzbd_port = 8080
    sabnzbd_apikey = 
```
With your correct port and api key set, this will check with SABnzbd to get the correct nzoid which helps ensure correct processing with CP etc.
It is just a warning... so no error.

**Comment by kesawi** [comment]
Does it need to be set to localhost? I have it set to the FQDN of the server as SABnzbd isn't bound to the lo interface. I also have it set to use SSL as well.

**Comment by kesawi** [comment]
Resolved the issue by putting `https://` in front of my server address under `sabnzbd_host =`. While the `autoProcessMedia.cfg.spec` file makes this clear, the [wiki entry](https://github.com/clinton-hall/nzbToMedia/wiki/autoProcessMedia.cfg) doesn't, which is where I become confused and entered the misconfiguration. I corrected the wiki entry to reflect the configuration requirement.

**Comment by clinton-hall** [comment]
Thanks for correcting the wiki..

like most things, as I add featured and fix bugs, I don't always remember to update the wiki :(
