### ISSUE TITLE
Sickrage & Nightly build of nzbToMedia not working.

### ISSUE THREAD

**Issue by phybersplice** [clinton-hall/nzbToMedia#932]
Sickrage (Master) and nzbToMedia (nightly) won't post-process TV downloaded via NZBGET on the Synology.  

Here's the debug log:
http://pastebin.com/2CsYXXgT

I can't seem to locate a legitimate error within.

Help would be greatly appreciated.

**Comment by emeljay42** [comment]
LIne 38 in the logs looks like mine where the parameters passed do NOT include proc_dir.

From a earlier successful process, I see [01:10:03] [DEBUG]::SICKBEARD: Opening URL: http://localhost:7073/home/postprocess/processEpisode with params: {'nzbName': 'Survivor.S31E14.HDTV.x264-UAV.nzb.nzb', 'quiet': 1, 'proc_dir': '/share/Download/sabnzbd/complete/Survivor.S31E14.HDTV.x264-UAV.nzb'}

MY assumption is that something has dropped the proc_dir information from the http call to sickrage

**Comment by emeljay42** [comment]
last successful process was December 18. All downhill since then

**Comment by clinton-hall** [comment]
Check user and pass for SickRage (as set in NZBGet under nzbToMedia settings).
This error suggests nzbToMedia is not able to log in to SickRage webui.
