### ISSUE TITLE
Transcoding to DTS

### ISSUE THREAD

**Issue by hjone72** [clinton-hall/nzbToMedia#949]
Hi,

I seem to be running into an issue when trying to transcode the audio format to DTS from AC3.

I am wanting to have the following settings;
AudioTrack1: DTS
AudioTrack2: AC3
AudioTrack3: AAC

I get the following error:
```
nzbToSickBeard: [05:55:54] [DEBUG]::MAIN: calling command: nice -n10 ionice -c2 -n4 /usr/bin/ffmpeg -loglevel warning  -fflags +genpts -i /home/downloads/nzb/sickrage/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS.mkv -map 0:0 -map 0:1 -map 0:1 -c:v copy -c:a:0 dts -c:a:1 copy -sn /home/downloads/nzb/sickrage/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS-transcoded.mkv

nzbToSickBeard: [05:55:54] [ERROR]::MAIN: Transcoding of video to /home/downloads/nzb/sickrage/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS-transcoded.mkv failed with result 1

nzbToSickBeard: [05:55:54] [ERROR]::SICKBEARD: FAILED: Transcoding failed for files in /home/downloads/nzb/sickrage/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS
```

When I run the command directly from the command line I get this message:
`[dca @ 0x3f41ac0] The encoder 'dca' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.`

If I add the "-strict -2" to the other ffmpeg options i still get the same error.
```
nzbToSickBeard: [05:55:54] [DEBUG]::MAIN: calling command: nice -n10 ionice -c2 -n4 /usr/bin/ffmpeg -loglevel warning -strict -2 -fflags +genpts -i /home/downloads/nzb/sickrage/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS.mkv -map 0:0 -map 0:1 -map 0:1 -c:v copy -c:a:0 dts -c:a:1 copy -sn /home/downloads/nzb/sickrage/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS-transcoded.mkv

nzbToSickBeard: [05:55:54] [ERROR]::MAIN: Transcoding of video to /home/downloads/nzb/sickrage/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS-transcoded.mkv failed with result 1

nzbToSickBeard: [05:55:54] [ERROR]::SICKBEARD: FAILED: Transcoding failed for files in /home/downloads/nzb/sickrage/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS
```

If I however run the following command:
`nice -n10 ionice -c2 -n4 /usr/bin/ffmpeg -loglevel warning -fflags +genpts -i /home/downloads/nzb/sickrage/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS.mkv -map 0:0 -map 0:1 -map 0:1 -c:v copy -c:a:0 dts -c:a:1 copy -strict -2 -sn /home/downloads/nzb/sickrage/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS/Suits.S05E11.REPACK.720p.HDTV.x264-KILLERS-transcoded.mkv`
Everything works perfectly encoding the DTS stream. 

Any help on this would be appreciated.

Thanks,

**Comment by clinton-hall** [comment]
Please update to latest nightly build and test.

**Comment by hjone72** [comment]
Thanks working great!
