### ISSUE TITLE
sickrage/contrib/nzbToMedia is Empty

### ISSUE THREAD

**Issue by Electr0Fi** [clinton-hall/nzbToMedia#955]
Hey all. 

It seems link the link bewteen the the SickRage/SickRage repo and the clinton-hall/nzbToMedia repo has failed.

I just cloned a new copy using the `sudo git clone https://github.com/SickRage/SickRage.git /opt/sickrage` command. The nzbToMedia directory is created but there is nothing in it.

I'm assuming this should be an easy fix somehow?

**Comment by lsellens** [comment]
git clone --recursive https://github.com/SickRage/SickRage.git /opt/sickrage
google submodels for git

**Comment by clinton-hall** [comment]
Has this been resolved? I believe the SickRage repo recently pulled in some changes from here...

**Comment by Electr0Fi** [comment]
Yes, I think so. Cheers :)
