### ISSUE TITLE
Failed to locate ffmpeg. Transcoding disabled!

### ISSUE THREAD

**Issue by alienx2** [clinton-hall/nzbToMedia#960]
How to skip ffmpeg to transfer file? bec my router has very small memory ram and low CPU. there is no enable/disable..

**Comment by clinton-hall** [comment]
This should only print a warning and then continue anyway. Basically, when ffmpeg isn't found, the functions that require it are disabled automatically.

**Comment by alienx2** [comment]
got it thanks.
