### ISSUE TITLE
Wiki for Mylar may be updated

### ISSUE THREAD

**Issue by Theli93** [clinton-hall/nzbToMedia#962]
ref: Local Wiki for Mylar: https://github.com/clinton-hall/nzbToMedia/wiki/Mylar

ref: fix for using nzbToMylar addressed (2014): https://github.com/evilhero/mylar/issues/900

copy of, or link to, nzbToMylar must be available in sabnzbd's default scripts folder
stop Mylar
open Mylar's `config.ini`
modify line to match: `post_processing_script = nzbToMylar.py`
restart Mylar

good to go

**Comment by clinton-hall** [comment]
Thanks.
Updated https://github.com/clinton-hall/nzbToMedia/wiki/Mylar

this is a public page, so feel free to correct/add any details.
