### ISSUE TITLE
TorrentToMedia + Transmission

### ISSUE THREAD

**Issue by theman480** [clinton-hall/nzbToMedia#966]
I read the wiki to setup sickrage + transmission , everything is fine, but for some reason when the download finish, I am receiving the following error:

`2016-02-21 18:51:57 INFO    ::MAIN: ## ..::[TorrentToMedia.py]::.. ##
2016-02-21 18:51:57 INFO    ::MAIN: #########################################################
2016-02-21 18:51:57 INFO    ::MAIN: SEARCH: Found torrent directory Shameless.US.S06E04.720p.HDTV.X264-DIMENSION[rarbg] in input directory directory /home/user/Multimedia/complete
2016-02-21 18:51:57 INFO    ::MAIN: SEARCH: Setting inputDirectory to /home/user/Multimedia/complete/Shameless.US.S06E04.720p.HDTV.X264-DIMENSION[rarbg]
2016-02-21 18:51:57 ERROR   ::MAIN: Unable to locate a section with subsection:UNCAT enabled in your autoProcessMedia.cfg, exiting!
2016-02-21 18:51:57 ERROR   ::MAIN: A problem was reported in the /opt/sickrage/contrib/nzbToMedia/nzbToMedia/TorrentToMedia.py script.`

Any one can help me?

**Comment by XenonPK** [comment]
Your paths need to be set based on what media you are processing:
In my case I have the folders setup like this:
/mnt/downloads/complete (manually added downloads)
/mnt/downloads/movies (category [movies] in config file)
/mnt/downloads/tv (category [tv] in config)

Then for the output directory I have
/mnt/downloads/process

You would configure the downloader section of couchpotato with /mnt/downloads/movies
/mnt/downloads/tv for sickrage , etc.... 
This way, all your downloads are separated into the categories (that the error is complaining about)

**Comment by clinton-hall** [comment]
thanks @XenonPK

**Comment by theman480** [comment]
I am sorry XenonPK, but i cant get it.
Should I change the output directory on transmission too?
I have a tv folder /home/user/Multimedia/tv
I have a movies folder /home/user/Multimedia/movies
And my output directory is /home/user/Multimedia/complete
WIth Sickrage>Search settings>Torrent Search>Transmission>Downloaded files location = /home/user/Multimedia/complete/TV 

Where is the problem?

And thank you for the support.

**Comment by XenonPK** [comment]
> And my output directory is /home/user/Multimedia/complete (Same place where transmission download the files)

This is your problem, the output dir and download dir should not be the same, in your example, keep your current structure but if you create a subdir like /home/user/Multimedia/output , and set it to the output dir in the config file, the script will then automatically create the directories that correspond to your categories and hardlink/symlink/copy... the files there , where couchpotato/sickrage then go find  them.

So, to recap, transmission receives the torrent ( and the path where the files should go ) from couchpotato/sickrage (regardless of the default download dir) when it finishes, it calls the script, the script analyses the files, looks for the media files, then depending on your config either copies/moves/symlinks/hardlinks the media and relevant metadata files it finds to the output dir , and instructs couchpotato/sickrage where the files are (the output dir) and from this point on the rest of the work is done by couchpotato/sickrage. 

the ideal solution would be something like this:
/home/user/Multimedia/downloads/complete (nothing from couchpotato/sickrage comes here, it's the default download dir for transmission)
/home/user/Multimedia/downloads/**tv** (where sickrage instructs transmission to put it's downloads)
/home/user/Multimedia/downloads/**movie** (where couchpotato  instructs transmission to put it's downloads)
**/home/user/Multimedia/downloads/output** (the output dir that is set in nzbToMedia config file)

the script will then create within the output dir:
**tv
movie**

corresponding to the **exact names** of the categories set in the config file

sickrage then goes into** /home/user/Multimedia/downloads/output/tv/ ** for all it's files
an couchpotato goes to ** /home/user/Multimedia/downloads/output/tv/ ** for it's files

Hope it helps

**Comment by theman480** [comment]
Perfect, thank you XenonPK! And sorry for the delay replying.
