### ISSUE TITLE
OT sorta, not really? Duplicate media

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#970]
So I keep running into an issue where after post proc etc, i end up with multiple movie files in a folder. 
ie
Scream (1996).avi
Scream (1996).mkv
Scream (1996).nfo

I'm wondering if anyone has suggestions on how to avoid this (its something CP is doing i think) and possibly a script to recurse through folders and make sure only 1 media file per name is present in the folder, ignoring all other nfo/srt/ etc files

**Comment by clinton-hall** [comment]
can you show some logs for this?
the only reason I can see that this would happen is if you have transcoding enabled.

But are these duplicate files showing up after CouchPotato has renamed? if so, you might want tocheck CP logs after a rename...

**Comment by mgaulton** [comment]
I'll try and catch one in the act, haven't had any luck so far, hence the generic question.

I have transcode and replace turned on. I suspect its CP after doing some manual cleaning up, some of the files were as old as 2011, so they weren't being replace by the newer files.

**Comment by clinton-hall** [comment]
ah... if you download a better version of an existing movie, and the extension is the same (e.g. Scream (1996).mkv in 720p is replaced by Scream (1996).mkv in 1080p) then it will replace the existing. but  from .avi to .mkv, this doesn't replace the file, and you end up with 2. this is all inside on CouchPotato and can't be influenced from this script.

**Comment by mgaulton** [comment]
Ahhh bummer. Thanks for the info. I'll have to figure out a way to do the scrubbing :)
