### ISSUE TITLE
SickRage Sub-Directory

### ISSUE THREAD

**Issue by notlimahrelyt** [clinton-hall/nzbToMedia#975]
I'm running SickRage with NZBGet, but SickRage is running with a sub-directory involved (localhost:8081/sickrage).

How can i configure the NZBtoSickBeard script to include this sub-directory?

**Comment by clinton-hall** [comment]
it is called `web_root`
in NZBGet web ui, under nzbToSickBeard
`sbweb_root = sickrage`

in autoProcessMedia.cfg it looks like
```
[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[tv]]
        enabled = 1
        host = localhost
        port = 8081
        username =
        password =
        web_root = sickrage
```
