### ISSUE TITLE
error Sun Feb 28 2016 23:35:43 Post-process-script nzbToMedia/nzbToHeadPhones.py for SONGNAME_HERE failed (terminated with unknown status)

### ISSUE THREAD

**Issue by billbo01028** [clinton-hall/nzbToMedia#977]
Please let me know what other logs, setting outputs, or directory listings are needed to troubleshoot this error.  I am finding a large number of nzbToHeadphones downloads failing with similar output, but, not all of them...

error	Sun Feb 28 2016 23:35:43	Post-process-script nzbToMedia/nzbToHeadPhones.py for SONGNAME_HERE failed (terminated with unknown status)
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x7ffa15b088c0>> ignored
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: UnicodeDecodeError: 'utf8' codec can't decode byte 0xb4 in position 15: invalid start byte
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: return codecs.utf_8_decode(input, errors, True)
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: if fileName.startswith('._'):
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: File "/opt/nzbget/scripts/nzbToMedia/core/nzbToMediaUtil.py", line 884, in isMediaFile
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: elif isMediaFile(curFile, media, audio, meta, archives):
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: File "/opt/nzbget/scripts/nzbToMedia/core/nzbToMediaUtil.py", line 920, in listMediaFiles
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: for filename in listMediaFiles(dirname):
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: File "/opt/nzbget/scripts/nzbToMedia/core/nzbToMediaSceneExceptions.py", line 24, in process_all_exceptions
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: process_all_exceptions(inputName, dirName)
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: File "/opt/nzbget/scripts/nzbToMedia/core/autoProcess/autoProcessMusic.py", line 82, in process
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: result = autoProcessMusic().process(sectionName, inputDirectory, inputName, status, clientAgent, inputCategory)
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: File "/opt/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 600, in process
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: failureLink=failureLink)
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: File "/opt/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 698, in main
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: result = nzbToMedia.main(sys.argv, section)
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: File "/opt/nzbget/scripts/nzbToMedia/nzbToHeadPhones.py", line 117, in <module>
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: Traceback (most recent call last):
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: [23:35:43] [INFO]::MAIN: Calling HeadPhones:Music to post-process:Sean Paul-Imperial Blaze-NMR-2009-NMR
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: [23:35:43] [INFO]::MAIN: Auto-detected SECTION:HeadPhones
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: [23:35:43] [INFO]::MAIN: Script triggered from NZBGet Version 16.4.
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: [23:35:43] [INFO]::MAIN: #########################################################
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: [23:35:43] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: [23:35:43] [INFO]::MAIN: #########################################################
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: [23:35:43] [INFO]::MAIN: nzbToMedia Version:3e4861e87c543a4d2debd8997feb16bda3ef5339 Branch:master (Linux 4.3.4-300.fc23.x86_64)
info	Sun Feb 28 2016 23:35:43	nzbToHeadPhones: [23:35:43] [INFO]::MAIN: No update needed
info	Sun Feb 28 2016 23:35:27	nzbToHeadPhones: [23:35:27] [INFO]::MAIN: Checking if git needs an update
info	Sun Feb 28 2016 23:35:27	nzbToHeadPhones: [23:35:27] [INFO]::MAIN: Checking database structure...
info	Sun Feb 28 2016 23:35:25	Executing post-process-script nzbToMedia/nzbToHeadPhones.py for SONGNAME_HERE

**Comment by clinton-hall** [comment]
can you list the files in the directory?
Send via email if you don't want to post here... it looks like an encoding issue with a file, so I need to see how it is named.

**Comment by billbo01028** [comment]
Attached are copies of the completed music directory from NZBget, one file is ls -ll, the other is du -h

[completedmusiclistoffilesll.txt](https://github.com/clinton-hall/nzbToMedia/files/154003/completedmusiclistoffilesll.txt)
[completedmusiclistoffilesdu.txt](https://github.com/clinton-hall/nzbToMedia/files/154002/completedmusiclistoffilesdu.txt)

**Comment by clinton-hall** [comment]
please update to latest nightly branch and test again

**Comment by billbo01028** [comment]
test results the same, thank you for your prompt replies, BTW!

[terminated_unknown_status.txt](https://github.com/clinton-hall/nzbToMedia/files/155284/terminated_unknown_status.txt)
