### ISSUE TITLE
Sickrage on another server

### ISSUE THREAD

**Issue by ncfitzge** [clinton-hall/nzbToMedia#981]
I have two NAS servers. One is set to download and the other is the media center holds the files. When nzbToSickBeard runs I get the following error. I have added the NAS to the net work \IP\ in the network and turned on remote_path. Not sure whats the error or how I transfer the file to the media server.

`[INFO]::TRANSCODER: SUCCESS: [Call.The.Midwife.S01E01.720p.HDTV.x264-FoV.mkv] has no corruption.
Traceback (most recent call last):
  File "nzbToSickBeard.py", line 252, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/share/CE_CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py", line 771, in main
    download_id=download_id, inputCategory=subsection)
  File "/share/CE_CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py", line 598, in process
    download_id, inputCategory, failureLink)
  File "/share/CE_CACHEDEV1_DATA/Download/nzbToMedia/core/autoProcess/autoProcessTV.py", line 206, in processEpisode
    fork_params[param] = remoteDir(dirName)
  File "/share/CE_CACHEDEV1_DATA/Download/nzbToMedia/core/nzbToMediaUtil.py", line 75, in remoteDir
    for local,remote in core.REMOTEPATHS:
ValueError: need more than 1 value to unpack
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x1e47810>> ignored
`

**Comment by ncfitzge** [comment]
I figured I was writing the mount incorrectly. But when I added the correct linking, nzbToMedia ads additional '\'
`[DEBUG]::SICKBEARD: Opening URL: https://192.168.1.25:7073/home/postprocess/processEpisode with params: {'nzbName': 'Call The Midwife S01E01 720p HDTV x264-FoV', 'quiet': 1, 'failed': 0, 'dir': u'\\QNAP-NAS-451\\Download\\sabnzbd\\complete\\tv\\Call The Midwife S01E01 720p HDTV x264-FoV', 'delete_on': 1}`

**Comment by clinton-hall** [comment]
can you show the sickbeard logs?
There should be something to say what path was received.

The issue here is python doesn't like `\` and these are handled as `\\`, but when printed should only be `\`. 

e.g. in python

```
test = '\\IP\Download\sabnzbd\complete'
test
```
will output
` \\IP\\Download\\sabnzbd\\complete`
but 
`print test`
will output
`\IP\Download\sabnzbd\complete`

So if SickRage is receiving
`\IP\Download\sabnzbd\complete`
then you want to set 
`mount_points = /share/Download/sabnzbd/complete,\\\\IP\Download\sabnzbd\complete`
