### ISSUE TITLE
PostProcessing failure

### ISSUE THREAD

**Issue by notlimahrelyt** [clinton-hall/nzbToMedia#982]
I am having trouble getting nzbToSickBeard to communicate from NZBGet to SickRage. I am only receiving the following log:

_Post-process-script nzbToSickBeard.py for Madam.Secretary.S02E02.The.Doability.Doctrine.1080p.WEB-DL.DD5.1.H.264-NTb failed (terminated with unknown status)_

My Settings are as below:

![screen shot 2016-03-05 at 11 15 47 pm](https://cloud.githubusercontent.com/assets/5624324/13552234/385a0232-e328-11e5-96e4-6b51a42edac4.png)

![screen shot 2016-03-05 at 11 16 28 pm](https://cloud.githubusercontent.com/assets/5624324/13552239/5004b3b4-e328-11e5-8aaa-7ee3c508fe82.png)

**Comment by clinton-hall** [comment]
Was there any logging prior to the error?

I believe after updates to SickRage, this only works when using a user/pass in SickRage.

**Comment by thamilton91** [comment]
I tried with and without username/password, but same result with both.

Here is a screenshot of the full post processing log.

![screen shot 2016-03-07 at 11 25 29 am](https://cloud.githubusercontent.com/assets/5624324/13575545/70002254-e457-11e5-871b-211424e2a947.png)

**Comment by thamilton91** [comment]
Heres another example where the download was actually successful, but NZBtoSickbeard was not.

![screen shot 2016-03-07 at 11 29 38 am](https://cloud.githubusercontent.com/assets/5624324/13575639/f7cfd684-e457-11e5-99bb-de3a641e941a.png)

**Comment by clinton-hall** [comment]
`env python2: no such file or directory`

you need to ensure you have python2 available on your system path.
try creating a symlink `python2` that points to `python2.7` or `python`
