### ISSUE TITLE
Post Processing Failure

### ISSUE THREAD

**Issue by juliemars** [clinton-hall/nzbToMedia#983]
Hi

I am hoping someone can help me, I am in the process of getting NZBToMedia setup, and I got it working once, but since then I am getting the following messages:

`
    error Sat Feb 27 2016 06:49:03 Post-process-script nzbToMedia/nzbToSickBeard.py for XXX failed (terminated with unknown status)
    info Sat Feb 27 2016 06:49:03 nzbToSickBeard: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x75ebd2b0>> ignored
    info Sat Feb 27 2016 06:49:03 nzbToSickBeard: First error at line 113.
    info Sat Feb 27 2016 06:49:03 nzbToSickBeard: configobj.configobj.ConfigObjError: Parsing failed with several errors.
    info Sat Feb 27 2016 06:49:03 nzbToSickBeard: raise error
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: File "/opt/nzbget/scripts/nzbToMedia/libs/configobj/configobj.py", line 1317, in _load
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: self._load(infile, configspec)
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: File "/opt/nzbget/scripts/nzbToMedia/libs/configobj/configobj.py", line 1228, in __init__
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: super(configobj.ConfigObj, self).__init__(*args, **kw)
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: File "/opt/nzbget/scripts/nzbToMedia/core/nzbToMediaConfig.py", line 86, in __init__
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: CFG_NEW = config()
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: File "/opt/nzbget/scripts/nzbToMedia/core/nzbToMediaConfig.py", line 244, in addnzbget
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: CFG = config.addnzbget()
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: File "/opt/nzbget/scripts/nzbToMedia/core/__init__.py", line 277, in initialize
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: core.initialize(section)
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: File "/opt/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 626, in main
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: result = nzbToMedia.main(sys.argv, section)
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: File "/opt/nzbget/scripts/nzbToMedia/nzbToSickBeard.py", line 252, in <module>
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: Traceback (most recent call last):
    info Sat Feb 27 2016 06:49:02 nzbToSickBeard: [06:49:02] [ERROR]::MAIN: Unable to migrate config file /opt/nzbget/scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...
`

I am sure it is simple but not sure what, I am using the sickbeard script and sickrage as the client if that helps.

appreciate any help

**Comment by clinton-hall** [comment]
Can you confirm which files exist?
`/opt/nzbget/scripts/nzbToMedia/autoProcessMedia.cfg`
`/opt/nzbget/scripts/nzbToMedia/autoProcessMedia.cfg.spec`

have you manually edited either of these files? 
you should not edit the.spec, and the .cfg should be created by nzbToMedia when it is run from NZBGet.

**Comment by juliemars** [comment]
thanks Clinton-hall both files exist along with a autoProcessMedia.cfg.old all dated 11/12/2015 11:26:34

Will try deleting the autoProcessMedia.cfg and autoProcessMedia.cfg.old and see if that works.

**Comment by clinton-hall** [comment]
This looks like something funny with the NZBGet config for nzbToSickBeard.

try deleting the .cfg file again and then manually run nzbToSickBeard to see what happens.
if that runs correctly, then the issue must be with a setting in nzbToSickBeard config inside NZBGet web UI.

**Comment by juliemars** [comment]
hi clinton-hall, thanks, I deleted the files but it still failed. 

What I decided to do was delete the folder and all files, reboot, and then use the git pull method to install it and it seems to be working now.

Thanks for your time and help
