### ISSUE TITLE
nzbToNzbDrone exception error (causing entire process to fail).

### ISSUE THREAD

**Issue by c0m3d1an** [clinton-hall/nzbToMedia#986]
Getting this error on every Sonarr (nzbdrone) download.  Don't know when it started as I just wiped my logs and scratch-reinstalled.  :-(

info	Wed Mar 16 2016 15:43:56	nzbToNzbDrone: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x3515dd0>> ignored
info	Wed Mar 16 2016 15:43:56	nzbToNzbDrone: ValueError: need more than 1 value to unpack
info	Wed Mar 16 2016 15:43:56	nzbToNzbDrone: REMOTEPATHS = [ (local.strip(), remote.strip()) for local, remote in REMOTEPATHS ] # strip trailing and leading whitespaces
info	Wed Mar 16 2016 15:43:56	nzbToNzbDrone: File "/Users/bob/Downloads/NZBGet/scripts/nzbToMedia/core/__init__.py", line 369, in initialize
info	Wed Mar 16 2016 15:43:56	nzbToNzbDrone: core.initialize(section)
info	Wed Mar 16 2016 15:43:56	nzbToNzbDrone: File "/Users/bob/Downloads/NZBGet/scripts/nzbToMedia/nzbToMedia.py", line 633, in main
info	Wed Mar 16 2016 15:43:56	nzbToNzbDrone: result = nzbToMedia.main(sys.argv, section)
info	Wed Mar 16 2016 15:43:56	nzbToNzbDrone: File "/Users/bob/Downloads/NZBGet/scripts/nzbToMedia/nzbToNzbDrone.py", line 236, in <module>
info	Wed Mar 16 2016 15:43:56	nzbToNzbDrone: Traceback (most recent call last):
info	Wed Mar 16 2016 15:43:56	nzbToNzbDrone: [15:43:56] [INFO]::MAIN: nzbToMedia Version:c50957d0b4683a125df039329d8f90df630d4e28 Branch:master (Linux 3.19.8-100.fc20.x86_64)

**Comment by c0m3d1an** [comment]
Never mind.  I have a remote mapping setup between nzbget and sonarr, and had the (single) mapping separated with a | instead of a comma.  | is for separating distinct mappings, comma is for separating local and remote in each mapping.  Dur.

**Comment by clinton-hall** [comment]
All good. Glad you got it sorted...
and not `Dur` I always have to look closely to remember how that mapping works ;)
