### ISSUE TITLE
nzbToNzbDrone.py help

### ISSUE THREAD

**Issue by stayupthetree** [clinton-hall/nzbToMedia#987]
I have had nzbget and sonarr setup successfully for many many months. I have changed no settings with either program, but now all of a sudden I get this. Any help would be greatly appreciated. Something is going wrong in the move I think.

Sat Mar 19 01:01:08 2016    INFO    Unpack for Criminal.Minds.Beyond.Borders.S01E01.The.Harmful.One.720p.WEB-DL.DD5.1.H.264-BS successful
Sat Mar 19 01:01:08 2016    INFO    Checking renamed files for Criminal.Minds.Beyond.Borders.S01E01.The.Harmful.One.720p.WEB-DL.DD5.1.H.264-BS
Sat Mar 19 01:01:08 2016    INFO    No renamed files found for Criminal.Minds.Beyond.Borders.S01E01.The.Harmful.One.720p.WEB-DL.DD5.1.H.264-BS
Sat Mar 19 01:01:09 2016    INFO    Cleaning up Criminal.Minds.Beyond.Borders.S01E01.The.Harmful.One.720p.WEB-DL.DD5.1.H.264-BS
Sat Mar 19 01:01:09 2016    INFO    Deleting file a900abb657c7ea8338aaeb6d69dff0ec.par2
Sat Mar 19 01:01:09 2016    INFO    Cleanup for Criminal.Minds.Beyond.Borders.S01E01.The.Harmful.One.720p.WEB-DL.DD5.1.H.264-BS successful
Sat Mar 19 01:01:09 2016    INFO    Moving completed files for Criminal.Minds.Beyond.Borders.S01E01.The.Harmful.One.720p.WEB-DL.DD5.1.H.264-BS
Sat Mar 19 01:01:09 2016    INFO    Moving file dad8da60b6f551fa7404959b81f970fdf66eab86.nfo to D:\Downloads\NZBGet\complete\tv\Criminal.Minds.Beyond.Borders.S01E01.The.Harmful.One.720p.WEB-DL.DD5.1.H.264-BS
Sat Mar 19 01:01:09 2016    INFO    Move for Criminal.Minds.Beyond.Borders.S01E01.The.Harmful.One.720p.WEB-DL.DD5.1.H.264-BS successful
Sat Mar 19 01:01:10 2016    DETAIL  Successfully downloaded Marvels.Daredevil.S02E03.720p.WEBRip.x264-SKGTV\marvels.daredevil.s02e03.720p.webrip.x264-skgtv.r10 [19/66]
Sat Mar 19 01:01:10 2016    INFO    Executing post-process-script nzbToMedia\nzbToNzbDrone.py for Criminal.Minds.Beyond.Borders.S01E01.The.Harmful.One.720p.WEB-DL.DD5.1.H.264-BS
Sat Mar 19 01:01:10 2016    DETAIL  Downloading Marvels.Daredevil.S02E03.720p.WEBRip.x264-SKGTV\marvels.daredevil.s02e03.720p.webrip.x264-skgtv.r10 [22/66] @ supoernews (news.supernews.com)
Sat Mar 19 01:01:10 2016    INFO    nzbToNzbDrone: C:\Python27\python.exe: can't open file 'L': [Errno 2] No such file or directory
Sat Mar 19 01:01:10 2016    ERROR   Post-process-script nzbToMedia\nzbToNzbDrone.py for Criminal.Minds.Beyond.Borders.S01E01.The.Harmful.One.720p.WEB-DL.DD5.1.H.264-BS failed (terminated with unknown status)
Sat Mar 19 01:01:10 2016    INFO    Cleaning up download queue for Criminal.Minds.Beyond.Borders.S01E01.The.Harmful.One.720p.WEB-DL.DD5.1.H.264-BS

**Comment by clinton-hall** [comment]
`INFO nzbToNzbDrone: C:\Python27\python.exe: can't open file 'L': [Errno 2] No such file or directory`
It looks like the path to nzbToNzbDrone is wrong? this is trying to open something on L:

**Comment by stayupthetree** [comment]
Is that something I can set in NzbGet? I've been up and down through all settings. I think as long as the script is in the scripts folder I set(which it is), there is nothing else.

**Comment by clinton-hall** [comment]
So where is the nzbToNzbDrone script located?
