### ISSUE TITLE
Can't migrate autoProcessMedia.cfg

### ISSUE THREAD

**Issue by TVBoy999** [clinton-hall/nzbToMedia#988]
OK, so I know I screwed up the format, but the only thing I can think of is the watch_dir.

Is it expecting quotes or some other delimiter?

Log says:

2016-03-19 21:03:52 ERROR   ::MAIN: Unable to migrate config file /mnt/cache/appdata/AutoProcess/autoProcessMedia.cfg, exiting ...

**Comment by TVBoy999** [comment]
Still getting this error and I've been through the config file a few times. :-(

**Comment by clinton-hall** [comment]
@TVBoy999 
I know this says you opened the issue 2 days ago... but I checked this morning and there were no new issues!!

As such, I have only just seen this now.

please be sure that the file /mnt/cache/appdata/AutoProcess/autoProcessMedia.cfg has read and write permissions for the user that runs nzbToMedia

If you are happy to send your .cfg file to me, please send to `fock_wulf@hotmail.com`
