### ISSUE TITLE
post processing errors

### ISSUE THREAD

**Issue by wknight7** [clinton-hall/nzbToMedia#992]
Hello-
I am getting errors in post processing when I have nzbToNzbdrone set to transcode, and I've been unable to figure out what is wrong.  Here is a log from one of the failures on nzbget.  Any help will be greatly appreciated.  

http://pastebin.com/BvA3wT9L

**Comment by clinton-hall** [comment]
Check your autoProceeeMedia.cfg
under [Transcoder]
you either need to have an ` outputDefault` set or you need to set up the custom parameters (in particular you must have an `outputVideoCodec`

**Comment by clinton-hall** [comment]
Actually looks more like `outputAudioTrack2Codec` that has issues... so what do you currently have set for this?

**Comment by wknight7** [comment]
Thanks for taking a look... When setting it up, I just reviewed the settings for the script on nzbget and don't see where I would set that.  I'm unable to figure out how.  Is there a guide or post on the subject you can point me to?  I've tried to find somewhere this has already been addressed but can't find anything.  Thanks.

**Comment by clinton-hall** [comment]
I tired to document the settings in the wiki https://github.com/clinton-hall/nzbToMedia/wiki

As far as where to find the settings, in NZBGet Web Ui, go to settings, NZBTOMEDIA

**Comment by wknight7** [comment]
Thanks.  I had set the outputDefault set to Roku-720p, and looked like I didn't need to pay attention to anything below that and I didn't change anything.  What is set in outputAudioTrack2Codec is libfaac.
