### ISSUE TITLE
CouchPotato PP error

### ISSUE THREAD

**Issue by Pseudomax** [clinton-hall/nzbToMedia#993]
Hi, I keep having NZBtoMedia giving me Post Processing failure (due to unknown error) with NZBget and CouchPotato (but not NZBget and SickRage ... which works fine). Essentially, the download and unpacking works fine and the output is moved to the 'Completed' folder (which is what I think should happen based on the settings I have put in).

CouchPotato is set to scan that folder and seems to do this correctly on occasion ... but not sure why NZBget lists the NZBtoMedia script as a failure?

Thanks

**Comment by clinton-hall** [comment]
Can you show the logs from a PP failure?

**Comment by Pseudomax** [comment]
Sorry, only way I know is Copy & Paste ... (you will see that I replaced the name of the download with "movie")

INFO	Sat Mar 26 2016 22:39:57	Collection movie added to history
DETAIL	Sat Mar 26 2016 22:39:57	Deleting file movie.vol251+45.PAR2 from download queue
DETAIL	Sat Mar 26 2016 22:39:57	Deleting file movie.vol206+45.PAR2 from download queue
DETAIL	Sat Mar 26 2016 22:39:57	Deleting file movie.vol161+45.PAR2 from download queue
DETAIL	Sat Mar 26 2016 22:39:57	Deleting file movie.vol116+45.PAR2 from download queue
DETAIL	Sat Mar 26 2016 22:39:57	Deleting file movie.vol071+45.PAR2 from download queue
DETAIL	Sat Mar 26 2016 22:39:57	Deleting file movie.vol038+33.PAR2 from download queue
DETAIL	Sat Mar 26 2016 22:39:57	Deleting file movie.vol021+17.PAR2 from download queue
DETAIL	Sat Mar 26 2016 22:39:57	Deleting file movie.vol007+05.PAR2 from download queue
DETAIL	Sat Mar 26 2016 22:39:57	Deleting file movie.vol003+04.PAR2 from download queue
DETAIL	Sat Mar 26 2016 22:39:57	Deleting file movie.vol001+02.PAR2 from download queue
INFO	Sat Mar 26 2016 22:39:57	Cleaning up download queue for movie
ERROR	Sat Mar 26 2016 22:39:57	Post-process-script nzbToMedia.py for movie failed (terminated with unknown status)
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.1.120', port=5050): Read timed out. (read timeout=1800)
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: raise ReadTimeout(e, request=request)
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: File "G:\Media\Scripts\nzbToMedia-master\libs\requests\adapters.py", line 431, in send
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: r = adapter.send(request, **kwargs)
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: File "G:\Media\Scripts\nzbToMedia-master\libs\requests\sessions.py", line 577, in send
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: resp = self.send(prep, **send_kwargs)
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: File "G:\Media\Scripts\nzbToMedia-master\libs\requests\sessions.py", line 469, in request
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: response = session.request(method=method, url=url, **kwargs)
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: File "G:\Media\Scripts\nzbToMedia-master\libs\requests\api.py", line 50, in request
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: return request('get', url, params=params, **kwargs)
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: File "G:\Media\Scripts\nzbToMedia-master\libs\requests\api.py", line 69, in get
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: r = requests.get(url, params=params, verify=False, timeout=(30, 1800))
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: File "G:\Media\Scripts\nzbToMedia-master\core\autoProcess\autoProcessMovie.py", line 240, in process
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: inputCategory, failureLink)
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: File "G:\Media\Scripts\nzbToMedia-master\nzbToMedia.py", line 602, in process
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: failureLink=failureLink)
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: File "G:\Media\Scripts\nzbToMedia-master\nzbToMedia.py", line 705, in main
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: exit(main(sys.argv))
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: File "G:\Media\Scripts\nzbToMedia-master\nzbToMedia.py", line 807, in <module>
INFO	Sat Mar 26 2016 22:39:57	nzbToMedia: Traceback (most recent call last):
INFO	Sat Mar 26 2016 22:09:57	nzbToMedia: [22:09:57] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for movie
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [INFO]::MAIN: Found imdbID [tt0167260]
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [INFO]::MAIN: Searching folder and file names for imdbID ...
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [INFO]::MAIN: Attemping imdbID lookup for movie
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [INFO]::MAIN: Calling CouchPotato:movies to post-process:movie
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [INFO]::MAIN: Script triggered from NZBGet Version 16.4.
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [INFO]::MAIN: #########################################################
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [INFO]::MAIN: #########################################################
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [WARNING]::MAIN: Failed to locate ffprobe.exe. Video corruption detection disabled!
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [WARNING]::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [INFO]::MAIN: nzbToMedia Version:c50957d0b4683a125df039329d8f90df630d4e28 Branch:master (Windows 8)
INFO	Sat Mar 26 2016 22:09:56	nzbToMedia: [22:09:56] [INFO]::MAIN: No update needed
INFO	Sat Mar 26 2016 22:09:54	nzbToMedia: [22:09:54] [INFO]::MAIN: Checking if source needs an update
INFO	Sat Mar 26 2016 22:09:54	nzbToMedia: [22:09:54] [INFO]::MAIN: Checking database structure...
INFO	Sat Mar 26 2016 22:09:52	Executing post-process-script nzbToMedia.py for movie
INFO	Sat Mar 26 2016 22:09:52	Move for movie successful
INFO	Sat Mar 26 2016 22:09:52	Moving completed files for movie
INFO	Sat Mar 26 2016 22:09:52	Cleanup for movie successful
INFO	Sat Mar 26 2016 22:09:52	Deleting file _brokenlog.txt
INFO	Sat Mar 26 2016 22:09:52	Deleting file movie.vol012+09.PAR2
INFO	Sat Mar 26 2016 22:09:52	Deleting file movie.vol000+01.PAR2
INFO	Sat Mar 26 2016 22:09:52	Deleting file movie.sfv
INFO	Sat Mar 26 2016 22:09:52	Deleting file movie.par2
INFO	Sat Mar 26 2016 22:09:52	Cleaning up movie
INFO	Sat Mar 26 2016 22:09:52	No renamed files found for movie
INFO	Sat Mar 26 2016 22:09:50	Checking renamed files for movie
INFO	Sat Mar 26 2016 22:09:50	Unpack for movie successful
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part65.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part64.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part63.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part62.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part61.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part60.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part59.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part58.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part57.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part56.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part55.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part54.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part53.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part52.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part51.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part50.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part49.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part48.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part47.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part46.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part45.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part44.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part43.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part42.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part41.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part40.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part39.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part38.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part37.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part36.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part35.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part34.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part33.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part32.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part31.rar
INFO	Sat Mar 26 2016 22:09:50	Deleting file movie.part30.rar

**Comment by clinton-hall** [comment]
in NZBGet settings for nzbToMedia.py check the host and port settings for CouchPotato.
According to the logs, this times out.

Please check these settings and verify they are correct. Also, if NZBGet and CouchPotato areon the same system, just use host = localhost or host = 127.0.0.1 to see if these work better.

**Comment by Pseudomax** [comment]
Hi

I have checked this (including adding 127.0.0.1 as host), but still not working. I did find inith NZBtoCouchPotato an incorrect host IP, but I haven't specifically used this script ... rather the NZBtoMedia script. I have noticed that CP becomes unresponsive when it is called and has to be ended from the task manager ... when it restarts it works as expected. (I have just posted in the CP forums as well).

Many thanks for trying to help & Happy Easter!

**Comment by Pseudomax** [comment]
Hi Clinton

I have completely deleted couchpotato (I think ... \AppData\Roaming\CouchPotato & C:\CouchPotato folders deleted) and reinstalled from source (using git from admin command prompt). However, after doing so the problem still remains! I tried to change all the CouchPotato folder paths from mapped network drives to UNC names ... and still no solution. I did this as NZBget starts from the installer setup script and did not seem able to access mapped network drives. However UNC drives work fine. CouchPotato starts from a script triggered from the startup folder. It does accept mapped paths and actually seems to dislike UNC paths as it keeps adding extra '\' to the path.

I would really appreciate any help as every movie has to be manually added by stopping CP and restarting ...

**Comment by Pseudomax** [comment]
An additional log (it seems to have some differnet entries ...?)

Kind	Time	Text
INFO	Tue Mar 29 2016 01:12:12	Collection Movie added to history
DETAIL	Tue Mar 29 2016 01:12:12	Deleting file movie .vol21+5.par2 from download queue
DETAIL	Tue Mar 29 2016 01:12:12	Deleting file movie .vol16+5.par2 from download queue
DETAIL	Tue Mar 29 2016 01:12:12	Deleting file movie .vol11+5.par2 from download queue
DETAIL	Tue Mar 29 2016 01:12:12	Deleting file movie .vol06+5.par2 from download queue
DETAIL	Tue Mar 29 2016 01:12:12	Deleting file movie .vol03+3.par2 from download queue
DETAIL	Tue Mar 29 2016 01:12:12	Deleting file movie .vol01+2.par2 from download queue
DETAIL	Tue Mar 29 2016 01:12:12	Deleting file movie .vol00+1.par2 from download queue
INFO	Tue Mar 29 2016 01:12:12	Cleaning up download queue for Movie 
ERROR	Tue Mar 29 2016 01:12:12	Post-process-script nzbToMedia.py for Movie failed
INFO	Tue Mar 29 2016 01:12:12	nzbToMedia: CouchPotato: Failed to post-process - No change in status!
INFO	Tue Mar 29 2016 01:12:12	nzbToMedia: [01:12:12] [ERROR]::MAIN: A problem was reported in the G:\Media\Scripts\nzbToMedia-master\nzbToMedia.py script.
INFO	Tue Mar 29 2016 01:12:12	nzbToMedia: [01:12:12] [WARNING]::COUCHPOTATO: Movie does not appear to have changed status after 2 minutes, Please check your logs.
INFO	Tue Mar 29 2016 01:11:52	nzbToMedia: [01:11:52] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
INFO	Tue Mar 29 2016 01:11:32	nzbToMedia: [01:11:32] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
INFO	Tue Mar 29 2016 01:11:12	nzbToMedia: [01:11:12] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
INFO	Tue Mar 29 2016 01:10:51	nzbToMedia: [01:10:51] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
INFO	Tue Mar 29 2016 01:10:31	nzbToMedia: [01:10:31] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [POSTPROCESS]::COUCHPOTATO: SUCCESS: Finished renamer scan for folder \\Qnap\tv\Completed\movies\Movie 
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for Movie 
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [INFO]::MAIN: Found imdbID [tt0441773]
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [INFO]::MAIN: Searching folder and file names for imdbID ...
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [INFO]::MAIN: Attemping imdbID lookup for Movie 
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [INFO]::MAIN: Calling CouchPotato:movies to post-process:Movie 
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [INFO]::MAIN: Script triggered from NZBGet Version 16.4.
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [INFO]::MAIN: #########################################################
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [INFO]::MAIN: #########################################################
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [WARNING]::MAIN: Failed to locate ffprobe.exe. Video corruption detection disabled!
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [WARNING]::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [INFO]::MAIN: nzbToMedia Version:c50957d0b4683a125df039329d8f90df630d4e28 Branch:master (Windows 8)
INFO	Tue Mar 29 2016 01:10:11	nzbToMedia: [01:10:11] [INFO]::MAIN: No update needed
INFO	Tue Mar 29 2016 01:10:09	nzbToMedia: [01:10:09] [INFO]::MAIN: Checking if source needs an update
INFO	Tue Mar 29 2016 01:10:09	nzbToMedia: [01:10:09] [INFO]::MAIN: Checking database structure...
INFO	Tue Mar 29 2016 01:10:07	Executing post-process-script nzbToMedia.py for Movie 
INFO	Tue Mar 29 2016 01:10:07	Move for Movie successful
INFO	Tue Mar 29 2016 01:10:07	Moving completed files for Movie 
INFO	Tue Mar 29 2016 01:10:07	Cleanup for Movie successful
INFO	Tue Mar 29 2016 01:10:07	Deleting file movie .par2
INFO	Tue Mar 29 2016 01:10:07	Cleaning up Movie 
INFO	Tue Mar 29 2016 01:10:07	No renamed files found for Movie 
INFO	Tue Mar 29 2016 01:10:06	Checking renamed files for Movie 
INFO	Tue Mar 29 2016 01:10:06	Unpack for Movie successful
INFO	Tue Mar 29 2016 01:10:06	Deleting file movie .part52.rar
INFO	Tue Mar 29 2016 01:10:06	Deleting file movie .part51.rar
INFO	Tue Mar 29 2016 01:10:06	Deleting file movie .part50.rar

**Comment by clinton-hall** [comment]
ok, so you are using NZBGet to download directly onto a network share? and then trying to send this network share to CouchPotato to rename?
if you have a QNAP why not run NZBGet and CP on QNAP?

**Comment by clinton-hall** [comment]
in CP the extra "\" in the UNC paths is correct. That is because in POSIX systems and in Python the "\" is a special character (in fact it is the escape character) and the only wayto displayspecial characters is to escape them. hence all "\" should be doubled.

can you please edit autoProcessMedia.cfg
```
[General]
    log_debug =1
```
then post the logs after the next pp attempt?

**Comment by Pseudomax** [comment]
Hi

To your first comment:
... yes ... I have win10 machine and have the 'incomplete folder' set to the local drive 'G' and then the 'completed folder' set to a mapped QNAP drive (well it is UNC for NZBget and mapped for CP & SickRage & Headphones). SickRage & Headphones work fine with the NZBtoMedia script but not CP ...? The 'completed folder' is on the same level as the 'Movies' & 'TV_Shows' folder ... all on the QNAP.
I actually was going to use the QNAP (TS451) to drive NZBget, SR, CP & Headphones when I purchased it about a year ago ... but there were no easy guides to install these packages and I was uncertain whether Python, Git etc were needed (I assumed they were) ... but the key thing that I to stuck at was the naming convention for the folders on the QNAP. I couldn't figure how to get everything organised correctly as it is so different to Windows (obviously!!). If you have a guide then that would still make a lot of sense!

To your second comment:
There weren't just 2 '\' ... CP repeatedly gave me a path of '\\\\QNAP\\tv\\Movies\\' as the path (even when choosing using the autofill box ...). And after correcting it to '\\QNAP\tv\Movies\' it would automatically go back to the error (this was most evident on the Manage tab for loading all the movies ... but I think it did it in the Renamer tab too). It did not do this if I used the mapped drive 'Z:\Movies\'

Finally ... again a newbie question ... but where do I find the autoProcessMedia.cfg to edit?

Thanks for your time Clinton ... very appreciated!

**Comment by Pseudomax** [comment]
github seem to auto correct the UNC path I posted ... it should be '\\\\' before QNAP and then '\\' between the other folders ...

**Comment by clinton-hall** [comment]
yes... github corrects it to display as it should be read...
`\\QNAP\tv\Movies\` is the way you would need it to be able to navigate/use, however in the config this would actually show as `\\\\QNAP\\tv\\Movies\\` where every `\` is escaped (i.e. `\\`)

autoProcessMedia.cfg is in the main nzbToMedia folder `G:\Media\Scripts\nzbToMedia-master\autoProcessMedia.cfg`

QNAP packages are relatively easy to use... I maintain several packages on the forums (git as well).

" UNC for NZBget and mapped for CP & SickRage "
this is the problem... NZBGet paths need to match the CP and SickRage paths (SickRage has a check to default to the watchdir when path doesn't exist, and hence this still works, but could cause issues if you use other features). 

So, if you want to use UNC for NZBGet and mapped for CP, you can use the Mount Points option in autoProcessMedia.cfg, or otherwise get both systems on UNC or both on Mapped drive.

**Comment by Pseudomax** [comment]
:)

Thank you!! And let me try correcting the UNC to the same across all the apps and then if for whatever reason I still fails ... I'll explore QNAP packages!

And let me say again ... I really do appreciate your efforts!

**Comment by Pseudomax** [comment]
Hi Clinton

Unfortunately changing all tro UNC did not solve my problem!

And trying to install Sickrage (which fork is this btw?) as well as CP & headphone gave me the following error in the QNAP App centre:
Error	2016/04/01	00:19:36	System	127.0.0.1	localhost	[App Center] App install failed due to file format error.	
(it worked for python & Git ... which are both required I assume? ... the packages seem to be a little out of date although I read they auto update ... so perhaps this is not the case?)

**Comment by kozze89** [comment]
@clinton-hall @Pseudomax I have the same issue, however my problem is that my storage is slow to write. nzbToMedia script runs and assumes things will be good after 1800 seconds, see https://github.com/clinton-hall/nzbToMedia/blob/master/core/autoProcess/autoProcessMovie.py#L241

Assuming that storage is fast and hoping that a HTTP request will finish is a naive solution. Is it possible to poll the rename endpoint for information? Ideally the post processing script could figure out if it's moving forward or not.

**Comment by clinton-hall** [comment]
I did look at different ways of doing this, but without the timeout the script can hang if CouchPotato stops during the rename, and therefore now new downloads can proceed etc. the timeout was specifically requested.

Also, while this may lead to a failed script notification, once the renamer is called, CP should eventually rename the file even after the 30 min timeout. So the only issue should be a "failed" script notification and maybe some folders/files not cleaned up?

**Comment by kozze89** [comment]
Perhaps nzbToMedia could deal with moving the files into the right location and then couchpotato could just do the actual renaming? My issue is that renaming is also moving it, which can take a while, especially when the storage is remote. 

I am not familiar with the CP API, but if nzbToMedia could call it and get the name, that would be even better. Then the script can do everything and once it's done call CP again to tell it how it went.
