### ISSUE TITLE
QQ: leaving behind unregistered show files

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#997]
Hey guys, 
Wondering if someone could suggest a config that would allow me to do the following:

-grab all pilot/premiere episodes of new shows (i have an RSS feed in SAB for this)
-grab dual audio anime releases of unregistered series (same in SAB)

The problem i'm running into is when nTM runs, it nukes the files because 1. the series isn't registered 2. the quality isn't in the preferred list 3. possibly something else i haven't noticed.

I'd like to have it run transcode/corruption check etc but it says "awesome, new registered show files, process normally. OR crap, i don't' know that show, but i'll keep the files for you to check it out and maybe add it to SR later "

**Comment by clinton-hall** [comment]
This needs to be requested at SR. nTM just passes the information on to SR.

One potential solution would be to set UP SAB to snatch these to a different Category (NewShow or similar) and run nTM.
Then in autoProcessMedia.cfg
```
[SickBeard]
    [[NewShow]]
        enabled = 1
```
then for the host/port etc put the wrong details in.
This way, after checking and transcoding etc this will attempt to process with SR, but fail. This will then print a warning in SAB to say PP failed.
At least no files will be deleted, you will be alerted, and you can then manually intervene.

**Comment by mgaulton** [comment]
So i played with this and I have to be careful about where the files end up so they don't get moved to external storage and then PP by SR itself but i think it'll work. thanks.
