### ISSUE TITLE
script exit code is 1

### ISSUE THREAD

**Issue by utookmyid** [clinton-hall/nzbToMedia#999]
Followed http://www.htpcguides.com/configure-sabnzbd-on-all-platforms/.  Now I'm gettin script exit code is 1.  Thinking it's something in switches/special.  What does it take for nzbtomedia?  I'm using Win10, SAB v1.0.0

**Comment by clinton-hall** [comment]
There should be more info in the logs. I need to know why the exit status is 1...

**Comment by utookmyid** [comment]
Try this 
[nzbtomedialog.txt](https://github.com/clinton-hall/nzbToMedia/files/207490/nzbtomedialog.txt)

**Comment by utookmyid** [comment]
Should I just reinstall SAB/nzbtomedia??

**Comment by utookmyid** [comment]
FWIW I changed from https/9090 to http/8080 and unticked Special/empty_proc and that 'seens' to work?

**Comment by clinton-hall** [comment]
https/9090should work as long as you put that into autoProcessMedia.cfg
```
[Nzb]
    clientAgent = sabnzbd
    sabnzbd_host = https://localhost
    sabnzbd_port = 9090
    sabnzbd_apikey = ""
 ```

**Comment by utookmyid** [comment]
yr right, BUT ...
1.  I changed the script from http://localhost:9090 to https://localhost:9090, and it worked with no script exit code, BUT ...
2.  In my SR, https://localhost:9090 is unable to connect, while http://localhost:8080 works?

**Comment by utookmyid** [comment]
I was doing great, d/l my azz off, now, It's doing it again!  Do you see anything in this ...
[nzbtomedia.txt](https://github.com/clinton-hall/nzbToMedia/files/212133/nzbtomedia.txt)
